### ISSUE TITLE
highlight text and select Anchor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1503]
Description of problem:

In version 4 (4.18) when highlighted text and select Anchor, it will delete all highlighted text (tested IE 11)

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6749](http://archive.tinymce.com/develop/bugtracker_view.php?id=6749) posted by [ceasar](http://archive.tinymce.com/profile.php?name=ceasar)_

> _**Tags:** [msie msie10 highlight anchor]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by jszoja** [comment]
Also replicated in IE11 on the official tinymce demo site. Just paste the following code:
`<p>This is a simple paragraph with <a id="link1" title="The link no 1" href="https://www.tinymce.com/" target="_blank">the link no.1</a> and <a id="link2" title="The link no 2" href="https://www.tinymce.com/" target="_blank">the link no.2</a></p>`

and select/highlight the second link and click on 'edit link' button from the toolbar. You will notice the URL disappeared and after saving it check the source code: all your previous attributes of this anchore are gone, eg id

It works well with the first link, which is sorrounded by text. that was fixed in #545.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
