### ISSUE TITLE
Inserting/edit picture was so much easier in version3.5

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1551]
Description of problem: I am busy migrating my three personal 2.5 joomla websites into a new empty Joomla 3.2.3 site and by installing this version I got version 4 of tinyMCE, which looks different which is no problem, but the major bug compared to the good old version 3.5 is the editing images: aligning and setting margin is not intuitive anymore (see attached screenshots) First of all right mmouse clicking on an image give option to insert image (not insert/edit) so this is confusing. But also you cannot just align left or right but have to input it as code. Is doable after learning curve, but not user-friendly

Steps to reproduce:
1. Right mouse click on an image
2. Select "Insert image"
3. set with new UI
4.
5.

Expected result: same UI as version 3.5

Actual result: code input instead of intuitive presets

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6810](http://archive.tinymce.com/develop/bugtracker_view.php?id=6810) posted by [fmdesigncc](http://archive.tinymce.com/profile.php?name=fmdesigncc)_
> 
> _**Tags:** [firefox msie safari chrome opera image edit]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by dkolodziejczyk** [comment]
I agree with the original bug reporter. Having those margin fields on the form was a good way for page editors to make changes to the default margins around images in different situations. If an image is in the body of an article maybe we want a margin of 8 px, but if we put it inside of an article sidebar maybe we only want a 4 px margin. In a full width aside maybe we want 6 or 8 again. Or maybe 8px is fine most of the time, but I've just created a page where 8 px creates a wrap orphan and if I could just shrink that to 7 px the page would be much more asthetically pleasing. Now they have to go into the html and manually add in-line margins. Just because google does it this way doesn't make it best. Don't we want to be better than them? Maybe they'll look at TinyMCE and say, "Hey, they're still using those margins, maybe we should add that feature."

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.
