### ISSUE TITLE
Allow block level elements inside an anchor if mode if html5

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1584]
Description of problem:
HTML5 allows an anchor to contain any child that is a valid child of the parent elment (transparent content model). TinyMce strips the anchor if the child element is not an inline element.
Steps to reproduce:
1. Go to fiddle
2. Check the source code.

Expected result:
Source code should be: &ltg;div>&ltg;a href="#">&ltg;p>abc&ltg;/p>&ltg;/a>&ltg;/div>
Actual result:
Source code is: &ltg;div>&ltg;p>abc&ltg;/p>&ltg;/div>
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6837](http://archive.tinymce.com/develop/bugtracker_view.php?id=6837) posted by [_jd](http://archive.tinymce.com/profile.php?name=_jd)_

> _**Tags:** [firefox msie safari chrome opera a anchor transparent contentmodel flowcontent]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/raeaab/2_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by bradical** [comment]
Trying to figure if my [example here on 4.5.7](http://fiddle.tinymce.com/1agaab) of:

```
<a class="my-class" href="file.txt" title="Some stuff."><img alt="A sample image" src="../path_to_image.jpg">

<h3><span>Products</span></h3>

</a>
```

being converted to:

```
<p><a class="my-class" title="Some stuff." href="file.txt"><img src="path_to_image.jpg" alt="A sample image" /></a></p>
<h3>Products</h3>
```

is an example of this issue or #2991. Based on the issue summary it seems like it's this one.

**Comment by blackcathikari** [comment]
@bradical I believe this behaviour isn't supported by TinyMCE (technically). To quote Spocke from #2991:

`This is the only thing we don't support from HTML5 since it would be hard to edit inline and block level anchors in a sane way. Since a user can potentially have links inside a block text and there is no way to switch between them etc. Say you want to link this content: <p>a</p> it could be linked like this: <a href="#"><p>a</p></a> or <p><a href="#">a</a></p> but the user would select the same thing in both scenarios <p>[a]</p>.`

However, there is a workaround I know of - adding `valid_children : '+a[div]'` to Tiny's init and changing the `a` tag to `<div><a ....> <div>`. [Fiddle.](http://fiddle.tinymce.com/7agaab/1) Beware that doing that might cause some strange behaviour in the editor though, regarding editing links and the like. If possible I'd recommend linking each block level element separately, the way Tiny does normally if you select the content and use the link dialogue. If you can't though, hopefully that helps.

**Comment by bradical** [comment]
Hi @blackcathikari, I think I'm following that. Though I'm a little confused about the workaround. Would I use `<h3>` in my `valid_children` rule since my issue is with nesting a header inside of a link? Or does the workaround use `<div>` to keep the header inside of the link?

**Comment by blackcathikari** [comment]
If you just want a h3 inside the a tag, adding h3 to valid children for a tags would work. If you want to have multiple elements inside the a tag, like in your example before, you want to wrap everything in the divs. Or, if you don't want to have to add a heap of valid children for a tags if you have more than just the h3, you could register divs as valid children of a tags and wrap them all in divs.

**Comment by bradical** [comment]
Got it. That makes sense. One rule and then a pattern for getting whatever block-level elements you want inside of the `<a>` tag. Thanks!
