### ISSUE TITLE
Inline-Mode: editor gets style="position:relative"

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1828]
Description of problem:
I recently upgrade a website from tiny3 to the latest tiny4 CDN version.
At this page I ran into the Problem, that the DIV element which is enhancend using the tinymce gets a inline style "position: relative".

this destroys the rendering of the page.
without tinymce applied the website looks like expected.

I am not sure what exactly triggers this problem, because I already upgraded some other websites with similar markup/css, but there the error does not happen.

Still trying to reduce the html/css of this current project, to get a reproducible testcase.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7100](http://archive.tinymce.com/develop/bugtracker_view.php?id=7100) posted by [clxstaab](http://archive.tinymce.com/profile.php?name=clxstaab)_

> _**Tags:** [firefox chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by Rycochet** [comment]
This still happens on 4.5.6 (and 4.4.3) - so I think you missed something. In my case - inline mode editor, added dynamically, and putting it on `<p>` elements that don't have `position:relative;` anywhere in their stylesheets.

The `position:relative` is getting added, despite it having absolutely nothing to do with TinyMCE, and manually removing it making no visible difference to the behaviour while editing. Looks like something left behind from legacy code that's getting missed in a review...

**Comment by spocke** [comment]
It needs to be position: relative in order to place absolute ui elements like the resize handles on images/tables and other similar things. These needs to be added to the body of the editor to behave properly on scroll and clipping.

**Comment by Rycochet** [comment]
@spocke I'd agree with you if any of those things were actually being used - and if it was then removing it if not needed (or preferably only adding if needed) - but this seems to be the core adding it simply because I'm only using the plain text styles on there - unfortunately breaking layout for everything else doesn't make this the right behaviour.

**Comment by spocke** [comment]
Sounds like an implementation detail we need to have that style there for tinymce to work properly for any contents. If you are positioning things by absolute styles I suggest putting the editor instances inside an container like this.
<div style="position: absolute"><div class="tinymce">...</div></div>

**Comment by Rycochet** [comment]
@spocke They're already inside relatively positioned elements, and TinyMCE does not put anything inside the element in question at all (as an `inline` mode it is putting the `mce-panel` directly in the `body`) - it is adding the `position:relative` for absolutely no reason whatsoever.

**Comment by spocke** [comment]
They are there for the reason illustrated in this fiddle: http://fiddle.tinymce.com/PNfaab
The are multiple workaround one of them is double wrapping as I suggested the other one is to use !important like described in the fiddle. However that means things like image selection would be broken and possible other things since then it's overriding the default suggested behavior.

**Comment by Rycochet** [comment]
@spocke Images are disabled, so that's not relevant. They're also guaranteed inside elements which have `position:relative` in the CSS - meaning your suggestion doesn't actually work anyway.

I can see that the TinyMCE control points there are inline to the element, which makes sense only in the fact that they'll be hidden if they're outside the scroll area if the element has any overflow scrolling value.

More telling however - adding `position: static!important;` to the class (to prevent that `relative` from taking effect) does not make any difference to it at all, so it's not related to the thing you thought it was - any idea why it's being added then?
