### ISSUE TITLE
Normalize characters with combining marks to precomposed characters

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#1971]
I ran into a little weird problem which I wanted to solve. And here it is:

I have a PDF file with German Umlauts (������) and if I copy & paste them into the TinyMCE from WordPress I get the vowel (uoaUOA) which followed by a diaeresis (http://www.fileformat.info/info/unicode/char/0308/index.htm) instead of just one precomposed character.

This results in some problems:

```
Search for words with umlauts doesn't work
Proofreading fails
W3C validation fails with warning "Text run is not in Unicode Normalization Form C." because precomposed characters are prefered (See: http://www.w3.org/International/docs/charmod-norm/#choice-of-normalization-form) 
```

Solution: I made a proof-of-concept with the "content_save_pre" filter in WordPress and it works. In this proof-of-concept I just replaced the two characters with the precomposed character:

$content = str_replace( "a\xCC\x88", "�", $content );
$content = str_replace( "o\xCC\x88", "�", $content );
$content = str_replace( "u\xCC\x88", "�", $content );
$content = str_replace( "A\xCC\x88", "�", $content );
$content = str_replace( "O\xCC\x88", "�", $content );
$content = str_replace( "U\xCC\x88", "�", $content );

If we could (I know we can't, because WP is still supporting PHP 5.2) rely on PHP 5.3+ we could use a function for that:
http://php.net/manual/de/normalizer.normalize.php

So the above code would be just one line and much more general:
$content = normalizer_normalize($content, Normalizer::FORM_C );

Fun facts:
The problem is just on Mac OS X (Lion, 10.7.5 and 10.9.5) for me (on Ubuntu 14.04 or Win 7 I couldn't reproduce the problem).

Description of problem:
Pasting from non-precomposed characters

Steps to reproduce:
1. Paste Text from attached PDF (which don't work - because the file extension is not allowed :( )

Expected result:
Precomposed characters

Actual result:
vowels plus diaeresis (vowel plus combining character)

I submitted a bugreport (incl patch) for WordPress, but maybe this can be solved better in TinyMCE.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7243](http://archive.tinymce.com/develop/bugtracker_view.php?id=7243) posted by [zodiac1978](http://archive.tinymce.com/profile.php?name=zodiac1978)_
> 
> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by Zodiac1978** [comment]
With ES6 we have a normalize function in JS:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize

And there is a polyfill for older browsers:
https://github.com/walling/unorm

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.

**Comment by Zodiac1978** [comment]
This is still valid. You can try to paste NFD text to TinyMCE on https://www.tinymce.com/ and see the issue.

![bildschirmfoto 2017-05-24 um 17 12 38](https://cloud.githubusercontent.com/assets/870475/26410694/52bacae6-40a4-11e7-96de-7af05b0aee88.png)

New Cross Reference: https://github.com/WordPress/gutenberg/issues/433

**Comment by Zodiac1978** [comment]
@fyrkant Why a new issue? Can't we re-open this one?

**Comment by fyrkant** [comment]
@Zodiac1978 There is no problem opening this old one up again, I just thought that it might be better to open up a new issue of those still valid because these old aren't connected to a real github user and are therefore really easy to forget about (if someone answering forgets to @ anyone the answer can just echo out into nothing...). 

But yeah as this is cross-referenced in gutenberg and so on maybe I should open it again, sorry about that!

**Comment by Zodiac1978** [comment]
No problem! I'm the the original reporter of the issue and monitoring this issue (and the Gutenberg issue as well).

I have written a blog post about the problem -in German- but maybe it helps to understand the underlying problem (Google Translate FTW) :
http://torstenlandsiedel.de/2016/01/08/normalisieren-eine-bugticket-erlebnisreise-in-die-unicode-welt/

There is a feature plugin for WordPress which uses the mentioned polyfill if the normalizer function is not available, maybe this can help someone:
https://github.com/gitlost/unfc-normalize

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .

**Comment by Zodiac1978** [comment]
Still valid issue. Please re-open.
