### ISSUE TITLE
IE: inline editing on "a" element container not working 

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2146]
Description of problem:
Using inline mode with an &ltg;a> tag as "editable" element doesn't show the toolbar in Internet Explorer.

It works fine with other browsers (see the attached fiddle)

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7432](http://archive.tinymce.com/develop/bugtracker_view.php?id=7432) posted by [bago](http://archive.tinymce.com/profile.php?name=bago)_
> 
> _**Tags:** [msie msie9 msie10 msie11]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/LFeaab_

**Comment by fyrkant** [comment]
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.

**Comment by bago** [comment]
I don't understand why you do close issues because of age. There are fiddles and they are still broken.... reporting bugs is time consuming.. if you don't fix them but instead close them, then it is a waste of time.

In the years I reported at least 3-4 bugs related to inline mode and none of them have been fixed, so I don't think I'll take the time to open more, I'm sorry. Thank you, anyway, for the great opensource editor, but closing issues only because they are there since too many years while they are there since many years because you dind't handle them, it is a nonsense. Close it as won't fix, or "we don't care enough, create a PR if you do".
