### ISSUE TITLE
Centering not working with aligncenter

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2161]
click in text and press center button

Expected result:

center text

Actual result:

nothing happen

because forced_root_block is false

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7448](http://archive.tinymce.com/develop/bugtracker_view.php?id=7448) posted by [Editorant](http://archive.tinymce.com/profile.php?name=Editorant)_

> _**Tags:** [firefox msie safari chrome forced_root_block]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/WGeaab_

**Comment by Daijobou** [comment]
Verified in 4.3.0 with forced_root_block = false.

**Comment by Daijobou** [comment]
Not working in 4.3.3 (tinymce-dist)

buttons for "align left", "align right" and "align center" not working. that a basic function, can you please please fix this bug for next release? please..... :)

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by Daijobou** [comment]
I have tested it again and found out, that its now work. But not, when I have set this setting too:

```
formats: {
    alignleft: {selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes: 'myleft'},
    aligncenter: {selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes: 'mycenter'},
    alignright: {selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes: 'myright'},
    alignfull: {selector: 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img', classes: 'myfull'}
},
```
Source: https://www.tinymce.com/docs/demo/format-custom/ => https://www.tinymce.com/docs/configure/content-formatting/#formats
Old version 3: http://archive.tinymce.com/wiki.php/Configuration3x:formats

**Comment by acshef** [comment]
TinyMCE seems to operating correctly, @Daijobou. Because you've overridden the classes/styling that get applied when applying any of the `align*` alignments, it is instead applying the classes you've selected.

![image](https://cloud.githubusercontent.com/assets/9013284/17184932/02abba9c-53ec-11e6-90cf-491d6e58429f.png)

As you can see, I applied the right-align to a `<p>`, and the source code *correctly reflects that*.

The alignment is not showing up because TinyMCE works as a *SANDBOX*. The contents are in an `<iframe>`, so styles of the parent window DO NOT TRANSFER. In order to allow TinyMCE to see any styling that you've defined outside it, you should have a look through the Documentation for [Content Appearance](https://www.tinymce.com/docs/configure/content-appearance/)

From the documentation, you can see that you can refer to external stylesheets using `content_css` or you can define actual style as a string directly in `content_style`!

Here's a workign example: http://fiddle.tinymce.com/g4faab

**Comment by Daijobou** [comment]
My mistake in my fiddle example. I use setting with "content_css" to load a external css-file which include myleft, mycenter,... classes.

Your fiddle example not work for me. (Win 10, not in chrome, not in firefox)

**Comment by acshef** [comment]
Make sure you are applying alignment on block-level elements. You're setting `forced_root_block` to `false`, which means by default, you're simply typing inline text content rather than a `<p>` element. Either remove that, or set the text to a block-level format.

**Comment by Daijobou** [comment]
Yes, I said this in this topic on 13 Jul 2015 (Editorant)

A normal user will never expect that he must first use "justify"-button. Thats not a solution. The "left"-button must set it as a block element itself.
