### ISSUE TITLE
Plugin for adding attributes to elements

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2208]
TinyMCE 4.x

Would be more than nice to have a plugin to add, delete, manage... elements attributes. I think we're in a bad need to have such a plugin.

Or is there one? Can't find any.

Andreas

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7495](http://archive.tinymce.com/develop/bugtracker_view.php?id=7495) posted by [Aybee](http://archive.tinymce.com/profile.php?name=Aybee)_
> 
> _**Tags:** [xhtmlxtras attribs attribute plugin]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by Gagaro** [comment]
I did one there: https://github.com/Gagaro/tinymce-editattributes

It's fairly simplistic but it does the job.

**Comment by Aybee** [comment]
Thank you very much this works fine with me. 👍

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
