### ISSUE TITLE
suggested bootstrap modal focusin code causes cursor issues in IE

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2222]
Description of problem:

In IE when editing or adding a link, the link is placed at the beginning of the editor contents instead of modify selected text or inserting at the cursor position. 

Steps to reproduce:
1. At least IE 9 and up to IE11 (is all I tested)
2a. Highlight some text in the editor
2b. Place the caret somewhere in the editor
3. Click the link button
4. fill out the information
5. Click ok

Expected result:

a. Highlighted text becomes a link
b. Link inserted at caret position

Actual result:

a & b. Link is created at the start of the editor.

The root cause cause be boiled down to the code proposed here:

http://www.tinymce.com/wiki.php/Tutorials:TinyMCE_in_a_boostrap_dialog

When this code is included it causes this issue in IE. This happens regardless if the editor is inside a modal window or not. (See: http://fiddle.tinymce.com/oxdaab).

Related:
http://www.tinymce.com/develop/bugtracker_view.php?id=6001
http://www.tinymce.com/develop/bugtracker_view.php?id=5917

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7509](http://archive.tinymce.com/develop/bugtracker_view.php?id=7509) posted by [aknosis](http://archive.tinymce.com/profile.php?name=aknosis)_
> 
> _**Tags:** [msie msie9 msie10 msie11 modal bootstrap jqueryui]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/mMeaab/1_

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by rgriffith** [comment]
I am able to reproduce this behavior in IE11 using the suggested fiddle http://fiddle.tinymce.com/oxdaab, which is running TinyMCE v4.6.3.

**Comment by blackcathikari** [comment]
Thanks for bringing this to our attention again @rgriffith. I'll reopen this. 

For me on Win7, IE11 http://fiddle.tinymce.com/oxdaab doesn't insert the link at all, but the cursor jumps to the start of the editor content. Without the e.stopImmediatePropagation() section it works in IE11 but I can't type anything in the link dialog in Firefox.

**Comment by rgriffith** [comment]
Thank you for re-opening this, @blackcathikari.

I found the `tinymce.isIE` check [proposed above](https://github.com/tinymce/tinymce/issues/2222#issuecomment-152003270) to be useful, but I didn't realize there are issues with FF, is that an older version of FF or latest?

**Comment by blackcathikari** [comment]
Latest I believe @rgriffith - 53.0.3. To make it clear, this contains my changes that causes input in the link dialog to break: http://fiddle.tinymce.com/oxdaab/422

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
