### ISSUE TITLE
Image Dimensions/Attributes Not Removed (Insert/Edit Image Button)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2225]
Description of problem:
When inserting an image, you cannot remove the height and width attributes.

Steps to reproduce:
1. Go to the demo site http://www.tinymce.com/tryit/basic.php
2. Ctrl+a and press delete to delete all current source
3. Click the Insert/Edit Image button
4. Click the browse button
5. Select the "cdrom.jpg" image
6. Remove (blank out) the height and width dimensions 
7. Click "Ok"
8. Choose Tools > Source Code

Expected result:
The &ltg;img> tag should not have height and width attributes

Actual result:
The &ltg;img> tag has height and width attributes

In Chrome, to continue:
9. Close the source window
10. Select the image
11. Click the Insert/Edit image button
12. Remove the dimensions (again) and click "Ok"
13. Choose Tools > Source Code

New Result is Original Expected Result:
The &ltg;img> tag does not have height and width attributes.

In IE this second step does not work, with IE the source always has the height and width attributes.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7512](http://archive.tinymce.com/develop/bugtracker_view.php?id=7512) posted by [FirstDivision](http://archive.tinymce.com/profile.php?name=FirstDivision)_
> 
> _**Tags:** [msie chrome msie11 chrome image dimensions]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by chrisdlangton** [comment]
+1

**Comment by spocke** [comment]
Never really understood the problem here with mobile. Since styles override attributes so in your mobile specific css you can always override the image sizes anyway.
Like for example: img { width: 10%; height: auto; } so the attributes doesn't have any meaning if styles gets applied.

**Comment by chrisdlangton** [comment]
Let me help you understand.

A non technical journo uses the editor.
They then add in an image via various methods.
That Image is resized to fit thier purpose.

This process sets specific width height attributes. 

Thus the images looks good to the user whom is viewing on desktop, typically using TinyMCE.

Your suggestion would be applied for all img tag elements within the targetted area, typically .editor-area, the editor doesnt allow class per img.

Having all images on page appear the same is not appropriate considering each are already sized custom dimension.

**Comment by halfpastfouram** [comment]
When inserting an image but leaving the height and width in their default sate the tag does not have height and width attributes. After changing the alt text of the image the height and width are suddenly set and cannot be removed.

**Comment by chrisdlangton** [comment]
P.S. saying “use css” and “attributes don’t matter” is so short sighted and narrow minded.
Do you think a div, p, a, ect tags should be considered irrelevant because all thier unique modifications can be done in css or js? That sounds redicous right? Yeah so is saying that width and height attributes are irrelevant due to css, it’s exactly the same statement, rediculous

**Comment by oilvier** [comment]
I'd like to add another problem related to this : 

if you upload an image larger than the tinyMCE editor it will be shrinked to the width of the editor via the width attribute, even if you leave it blank.

Let's say I want to add a 1000px large image for the hero part of my page and my tinyMCE editor is only 800px large.
In the published page, the image will be shorter than what I really want (800 instead of 1000) and no `max-width:100%` can help me with that.

If I try to remove the dimensions by editing the image, it's not working. Only solution is to edit the HTML source code and remove manually the width and height attributes.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
