### ISSUE TITLE
TinyMCE inline editor does not work inside iframe

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2243]
Description of problem: 
When displaying an iframe and then trying to initialize an inline-editor inside the iframe, the content is set to visibility:hidden but nothing else happens.

Steps to reproduce:
Download a SSCCE here: https://dl.dropboxusercontent.com/u/4852823/TinyMCE%20iframe%20SSCCE.zip
1. Create a html page with an iframe (to the same domain!).
2. Include jquery and TinyMCE (jquery version)
3. Try to create a TinyMCE inline editor for some content inside the iframe:
   $(this).contents().find('#content').tinymce({
   inline: true
   });

Expected result:
The content should be replaced by a TinyMCE editor.

Actual result:
The content vanishes, but no editor is displayed.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7531](http://archive.tinymce.com/develop/bugtracker_view.php?id=7531) posted by [Lars Ebert](http://archive.tinymce.com/profile.php?name=Lars Ebert)_
> 
> _**Tags:** [firefox msie safari chrome iframe inline]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://advitum.de/tinymce/_

**Comment by CSurieux** [comment]
Any news on this, I am experimenting it under orchard cms ?

**Comment by miikkaa** [comment]
Having the same issue. Any updates on this one?

**Comment by rogyvoje** [comment]
I tried to do the same. Why TinyMCE can't work inside an iframe, really don't get it?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
