### ISSUE TITLE
Can't paste image directly from clipboard

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2249]
I know I can paste rich text including images (http://www.tinymce.com/develop/bugtracker_view.php?id=7535) but if I try to paste an image directly from the clipboard into any of the online demos, nothing happens.

Pasting images has become pretty standard nowadays, and works in GitHub, StackOverflow, Slack, Google Docs etc.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7537](http://archive.tinymce.com/develop/bugtracker_view.php?id=7537) posted by [dandv](http://archive.tinymce.com/profile.php?name=dandv)_

> _**Tags:** []_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by gera2ld** [comment]
Same problem here on Linux and Windows, but works on Mac OS X.

When an image is pasted on Linux and Windows, the `e.clipboardData` will have both `text/html` and `File` types.
As a result, the paste-image operation is skipped due to `!hasHtmlOrText(clipboardContent)` [here](https://github.com/tinymce/tinymce/blob/ffc77a093ae8323ebbc3ff23b43fbe5423959574/js/tinymce/plugins/paste/classes/Clipboard.js#L540).

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
