### ISSUE TITLE
Font size of OL/UL bullet points stay the same size

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2260]
Description of problem:

Steps to reproduce:
1. create a list (ordered or not)
2. set a different font size

Expected result:
The size of the bullet points/numbers should be the same as the text size.

Actual result:
The size of the bullet points/numbers stay the same size.

This bug is mentionned here :
https://stackoverflow.com/questions/11905139/how-to-set-the-font-size-of-list-item-bullets-and-numbers-in-tinymce

And I believe it is related to :
http://www.tinymce.com/develop/bugtracker_view.php?id=4439

Thank you :)

Regards,
~Nico

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7548](http://archive.tinymce.com/develop/bugtracker_view.php?id=7548) posted by [ncarpi](http://archive.tinymce.com/profile.php?name=ncarpi)_
> 
> _**Tags:** [firefox msie safari chrome list]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by emanlangit** [comment]
I am experiencing the same issue. Is there an estimate or time frame for this item's disposition?

**Comment by jmsv63** [comment]
You can workaround this issue by editing the "source code" through menu Tools (activate plugin "code").
Example:
```html
<ol>
<ol>
<li style="font-size: 3em;">Text 1</li>
<li style="font-size: 3em;">Text 2</li>
<li style="font-size: 3em;">Text 3</li>
</ol>
</ol>
```

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by bmjfrantz** [comment]
This is definitely still an issue. The font size is not applied to the `<li>`  element, it is only applied to the span inside. The bullet (or number) for the list does not receive the style, so it doesn't change size with the text.

**Comment by dsakko** [comment]
Hi bmjfrantz,

We'll reopen this issue for you.

**Comment by MonoStas** [comment]
TinyMCE 4.4.3 - still not fixed

**Comment by alexandrlich** [comment]
4.5.5 also still has issues around bullet points.
When I played with an inline mode in Safari - it doesn't always change size properly when I change it back and force. Bullets sometimes disappear. Sometimes extra spacing stays even after we change to a smaller size etc. We counted like 5 different issues or so around applying colors and different text sizes to the selected text that contains bullet points.
Unfortunately, we decided to wait till those issues addressed before using it on production with the real users.

**Comment by jxmallett** [comment]
People on stack overflow have had a few cracks at fixing issues with pullets and numbers not getting styled. I ended up using [this solution](https://stackoverflow.com/a/41013909/1151228) with tinymce v4.7.1.

**Comment by KateMaruk** [comment]
Described issue  is still reproduced for v.4.8.3. 
Please, see screenshot:  http://img.mtrc.in/4401c379b4b2

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
