### ISSUE TITLE
Be able to style toolbar based on its position (top or bottom)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2290]
I want to style the toolbar differently based on its position (eg what direction the gradient points at). Therefore it would be awesome if each floating panel could be annotated with a state class with precisely that information.

This behaviour was added in a recent version to custom toolbars in the modern skin: https://github.com/tinymce/tinymce/blob/master/js/tinymce/themes/modern/theme.js

Is it possible to make this happen by default for all float panels? I would be willing to contribute if it was clear how to do this.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7578](http://archive.tinymce.com/develop/bugtracker_view.php?id=7578) posted by [roelvd](http://archive.tinymce.com/profile.php?name=roelvd)_
> 
> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by roelvanduijnhoven** [comment]
This was my ticket. 

Still stands. Also: still willing to contribute if I know where to look!

**Comment by roelvanduijnhoven** [comment]
Also: not really a bug; more a feature. So labels could be updated.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
