### ISSUE TITLE
Languages are not available via CDN

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2352]
Description of problem:
Custom language cannot be set when TinyMCE is loaded from CDN. Looks like the language files are missing on the CDN.

Steps to reproduce:
1. set up tinymce to be loaded from the CDN such as:
&ltg;script src="//tinymce.cachefly.net/4.2/tinymce.min.js">&ltg;/script>
2. set up initialize method for language such as:
tinyMCE.init({
    language: "sk"
});

Expected result: TinyMCE should load as usual, localized to Slovak language

Actual result: TinyMCE does not load and, in browser console, there is warning: "Failed to load: http://tinymce.cachefly.net/4.2/langs/sk_SK.js"
Please make all language files available via the CDN.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7645](http://archive.tinymce.com/develop/bugtracker_view.php?id=7645) posted by [Mek](http://archive.tinymce.com/profile.php?name=Mek)_
> 
> _**Tags:** [firefox msie safari chrome language cdn not available found]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by placyd** [comment]
The same error occur for Polish language.
Failed to load: http://tinymce.cachefly.net/4.2/langs/pl.js

**Comment by bazooka07** [comment]
Hi,
You can get more languages at http://www.tinymce.com/i18n/.
Download your language package and store it anywhere, e.g. at http://mysite.com/tinymcd/language/.
When you launch Tinymce, you need to add the following option "language_url
Look at https://www.tinymce.com/docs/configure/localization/#language_url for more infos
So init mcetiny like this : 
tinyMCE.init({
language: 'sk',
language: 'http://mysite.com/tinymcd/language'
});

**Comment by placyd** [comment]
Ok, thank you.
05.12.2015 10:31 "bazooka07" <notifications@github.com> napisał(a):

**Comment by Mazamazine** [comment]
Hi there,
For me it didn't work like this:
```
tinyMCE.init({
language: 'sk',
language_url: 'http://mysite.com/tinymcd/language'
});
```

At least, tinyMCE loads but in default language. To make it work, I had to specify the language file in the URL, which mean I don't even need the 'language' option:
```
tinyMCE.init({
language_url: 'http://mysite.com/tinymcd/language/language_file.js'
});
```

It's not a good solution though... What if I need several languages?!
Do you see what's wrong?
Thanks!

**Comment by donShakespeare** [comment]
Please add language files to CDN or at least make it explicit that users need the `language_url` and a own file to localize. Otherwise everything works perfectly.

Maybe it is time for the person responsible to add the files to 
https://cdnjs.com/libraries/tinymce also?

@Mazamazine technically for several languages it's no problem.
You only use one call at a time, or am I missing something?
`language_url: 'http://mysite.com/tinymcd/language/language_file.js'`

**Comment by babf** [comment]
An upvote from me for including the language packs on the CDNs, please

**Comment by cshelleig** [comment]
Anything new on this? We just did a fresh release and got totally bitten by no languages via the CDN
Big big big UPVOTE for including languages on the CDNs.

Does the custom url work for multiple languages (one at a time)?

**Comment by jayarjo** [comment]
We have this on a roadmap, so it will get resolved eventually.

**Comment by cshelleig** [comment]
Thanks for the update. 
Down stream it will make it a bit easier to deploy, but, at least for now, there is a viable work around by hosting the language packs on one's own servers and making the call at load time. 
Works just fine that way.

At this point a simple RED ALERT or some such would be useful on the CDN implementation page just to warn that NO LANGUAGES are available via the CDN.

It's a mistake one only makes once, now we know.

**Comment by davidfraser** [comment]
This seems to be working on cachefly now - http://tinymce.cachefly.net/4.2/langs/pl.js loads successfully
But http://cdn.tinymce.com/4.2/langs/pl.js still returns a 403 access denied...

**Comment by babarizbak** [comment]
@davidfraser Does it really work for you? At this time, I just get a 404 error when I go to http://tinymce.cachefly.net/4.2/langs/pl.js.

A big upvote for this feature; an editor is quite useless without i18n.

**Comment by davidfraser** [comment]
@babarizbak unfortunately it seems to have stopped working :(

**Comment by enigmatic-user** [comment]
Currently https://tinymce.cachefly.net/4.2/langs/de.js (and pl.js ;) ) works fine again.

**Comment by Olli-Suutari** [comment]
I have created a Github repository for the translation files and published it as Github page:
https://github.com/Olli-Suutari/tinyMCE-4-translations

Usage example:
                        config={{
                            language_url: 'https://olli-suutari.github.io/tinyMCE-4-translations/fi.jss',
                            language: 'fi',
                        }}

If hosting the translation files via my own Github is not acceptable, I can remove the repository.

**Comment by Evil2000** [comment]
It seems that the same issue exists with version 5 of the TinyMCE.
I get the same error when trying to use the 'de' language:
> Failed to load plugin url: https://cloud.tinymce.com/5/langs/de.js

Unfortunately TinyMCE only offers the languages which got translated to over 90% on the langage packages download site https://www.tiny.cloud/get-tiny/language-packages/

TinyMCE does not provide the language files directly, but uses Transifex for the translations. On https://www.transifex.com/moxiecode/tinymce/ the progress of translation for German is listed with 81.3%. Thats why it is not shown on the language packages download list.
Because I only use a very basic version of the editor (with bold, italic, underline buttons) I wanted to get the de.js file anyway,

It seems to be easier than I thought. Just take this URL: https://www.tiny.cloud/tinymce-services-azure/1/i18n/download?langs= and append the languages you want to get, separated by comma (,). In my case it was: https://www.tiny.cloud/tinymce-services-azure/1/i18n/download?langs=de
You'll get a ZIP file which includes all languages you specified.
After unpacking and uploading the JS files, you can inlcude them as language_url parameter, as mentioned above.

To download all offered languages in one large ZIP, use:
https://www.tiny.cloud/tinymce-services-azure/1/i18n/download?langs=ar,ar_SA,hy,az,eu,be,bn_BD,bs,bg_BG,ca,zh_CN,zh_TW,hr,cs,da,dv,nl,en_CA,en_GB,et,fo,fi,fr_FR,gd,gl,ka_GE,de,de_AT,el,he_IL,hi_IN,hu_HU,is_IS,id,it,ja,kab,kk,km_KH,ko_KR,ku,ku_IQ,lv,lt,lb,ml,ml_IN,mn_MN,nb_NO,fa,fa_IR,pl,pt_BR,pt_PT,ro,ru,sr,si_LK,sk,sl_SI,es,es_MX,sv_SE,tg,ta,ta_IN,tt,th_TH,tr,tr_TR,ug,uk,uk_UA,vi,vi_VN,cy
The download will take a while to start, because any language is fetched and zipped on the fly. So be patient.

Cheers!

**Comment by PanJiaChen** [comment]
I created a repository [tinymce-lang](https://github.com/PanJiaChen/tinymce-lang) and uploaded it to [cdn](https://www.jsdelivr.com/package/npm/tinymce-lang?path=langs)

**Comment by BoFFire** [comment]
Hi @PanJiaChen Can you please add the source of the strings in english, we need that to pull it into a weblate instance.

**Comment by fallen** [comment]
@BoFFire maybe create an issue specific to that question?

**Comment by tinydylan** [comment]
Hi,

The cachefly and cdn.tinymce.com are deprecated in favour of the Tiny Cloud CDN. We will not be updating the old CDNs.

Tiny Cloud now has languages available. Please see [this documentation page](https://www.tiny.cloud/docs/configure/localization/#language).

Thanks!

**Comment by AmirKaftari** [comment]
download your language package from this url : 
https://www.tiny.cloud/get-tiny/language-packages/

Done...

**Comment by yihuan** [comment]
I'm hosting the language file on a CDN server, and seems the language file is not fetched checking from the Network. Had the same folder path as it's suggested(`tinymce/langs`). What's the possible cause of this?
