### ISSUE TITLE
images_upload_handler causes JS error

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2443]
Description of problem:
Using the sample code provided in the documentation (at URL above) causes error:
"Uncaught (in promise) TypeError: Cannot read property 'indexOf' of undefined
    at Object.S.convertURL (https://domain.com/js/tinymce/tinymce.min.js:10:4790)
    at https://domain.com/js/tinymce/tinymce.min.js:9:18916
    at Array.&ltg;anonymous> (https://domain.com/js/tinymce/tinymce.min.js:2:27753)
    at n (https://domain.com/js/tinymce/tinymce.min.js:2:27583)
    at Object.r [as map] (https://domain.com/js/tinymce/tinymce.min.js:2:27728)
    at https://domain.com/js/tinymce/tinymce.min.js:9:18817
    at https://domain.com/js/tinymce/tinymce.min.js:9:18144

Steps to reproduce:
1. Set up editor using images_upload_handler code provided by tinymce
2. Create confirmed working (using default handler) server side script
3. Insert image into text
4. Edit image
5. See JS error in console

Expected result: image posted via AJAX to server side script

Actual result: JS error in console. AJAX call not made.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7742](http://archive.tinymce.com/develop/bugtracker_view.php?id=7742) posted by [Jknopp](http://archive.tinymce.com/profile.php?name=Jknopp)_

> _**Tags:** [firefox chrome firefox chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/wiki.php/Handling_Asynchronous_Image_Uploads_

**Comment by freekzero** [comment]
Sorry, I don't follow. The code I'm using comes straight from the sample provided in the wiki, which does take the string value of "location" and pass it into success(). Again though, that won't be the issue as the request is never even made to the server, so there is no response to pass into success yet.

**Comment by spocke** [comment]
The fileName(blobInfo) should be blobInfo.filename() in the examples so I updated that now. Other than that everything worked fine with the postAcceptor.php script and the example code.

**Comment by freekzero** [comment]
That did it!
Thx.

**Comment by sywa08** [comment]
Hi 

I'm sorry but even `formData.append("file", blobInfo.blob(), blobInfo.filename());`  doesn't work for me as of today in April 2017. 
The JS is broken with the message "Uncaught TypeError: blobInfo.blob is not a function". It is undefined if I remove the "()". and then the same error is shown on file. Plus, whatever I pass in success, it is always undefined.
Here is how my handler:
`images_upload_handler: function (blobInfo, success, failure) {
                            upload(blobInfo, success, failure);
                        }`
The upload function is in a javascript file which is included and the it gets called. then the upload function looks like this:

`function upload(blobInfo, success, failure) {
    var formData = new FormData();
    var formId = blobInfo.id;
    formData.append("file", blobInfo.blob(), blobInfo.filename());
    formData.append("formId", formId);`

So I don't understand how can filename() work because it is not a function. After almost 1.5 years of this post, things do not follow and still some bits are missing and/or broken.
I am using TinyMCEv4 by the way.

Any thoughts?

**Comment by Dmitriy-ateo** [comment]
I have the same issue, instead of object I receive `blobInfo = ƒ Promise() { [native code] }`

**Comment by z1lk** [comment]
I am also having this issue.
