### ISSUE TITLE
Error when inserting video embed code or using YouTube plugin

### ISSUE THREAD

**Issue by domeri** [tinymce/tinymce#2446]
When inserting video embed code (from Insert Video menu) or using YouTube plugin
`tinymce.min.js:4 Uncaught TypeError: Cannot set property 'prev' of null` error is generated.

P.S. I'm using inline mode of TinyMCE

**Comment by spocke** [comment]
Do you mean the media plugin we don't have an YouTube plugin?

**Comment by domeri** [comment]
YouTube is an external plugin, however the error is also generated when using the media plugin
(Insert->Insert Video->Embed)

**Comment by spocke** [comment]
So how do I reproduce it step by step. What do I need to paste where?

**Comment by spocke** [comment]
Can it be reproduced on fiddle.tinymce.com ?

**Comment by L-Cypher** [comment]
I have the very same error. The problem is in "media" plugin. If it is turned on (= string "media" is inside a "plugins" array in configuration) error occurs when inserting video embed code via "Insert/edit video" from Insert menu OR even editing source code via "source code" option from Tools menu. If it is turned off (= string "media" is not inside a "plugins" array in configuration) there is - of course - no "Insert/edit video" option in menu, but inserting video by editing source code works fine.

**Comment by domeri** [comment]
[http://jsbin.com/kayoyohiwe/edit?html,console,output](http://jsbin.com/kayoyohiwe/edit?html,console,output)

**Comment by spocke** [comment]
You have the media plugin twice in there. So it gets picked up and converted two times. I guess we should unique that list so there never can be multiple plugin inits.

@L-Cypher: You case could be something different. So you might need to report an separate ticket with steps for us to reproduce that.

**Comment by spocke** [comment]
Added a fix for multiple initialization of the same plugin. So closing this one.
