### ISSUE TITLE
Dynamic menubutton - not working since 4.2.7

### ISSUE THREAD

**Issue by jeroencornelissen** [tinymce/tinymce#2462]
We recently upgraded from 4.1.9 to 4.2.7.
Since then our custom plugin stopped working.
Seems like the _e.control.settings.menu = menu;_ behaviour has changed.

```
tinymce.PluginManager.add('customPlugin', function(editor, url) {
    editor.addButton('customPlugin', {
        type        : 'menubutton',
        text        : 'custom plugin',
        icon        : false,
        disabled    : true,
        menu        : [],
        onPostRender : function(e) {
            $.ajax({
                url     : '/TinyMCE/CustomButton/getCustomPluginButtons',
                dataType: 'json'
            }).done(function(response) {
                var menu = [];
                for(var i = 0, l = response.buttons.length; i < l; ++i) {
                    menu.push({
                        text : response.buttons[i].commentName,
                        commentText : response.buttons[i].commentText,
                        onClick : function(e) {
                            editor.execCommand('mceInsertContent', false, e.control.settings.commentText);
                        }
                    });
                }
                e.control.text(response.mainButtonLabel);
                if(menu.length > 0) {
                    e.control.settings.menu = menu;
                    e.control.disabled(false);
                }
                if(tinymce.settings['readonly']) {
                    e.control.disabled(true);
                }
            });
        }
    });
});
```

![schermafbeelding 2015-11-19 om 11 41 08](https://cloud.githubusercontent.com/assets/1894257/11268712/9b8de5c8-8eb2-11e5-9ae8-8b00a3cc6c97.png)

The menu button gets enabled and the label is being set (_e.control.text()_). If I debug the _e.control.settings.menu_, it contains my array with the generated objects. But the are not shown in the dropdown.

**Comment by spocke** [comment]
I couldn't reproduce the issue seems to be working fine when I try it. The menu needs to finish it's rendering call though. So I suggest pulling it in before that. Dyanmic menus are somewhat tricky.

**Comment by jeroencornelissen** [comment]
What do you mean with *finish it's rendering call*?
Can you provide some example code for the onPostRender with an ajax call?

**Comment by jeroencornelissen** [comment]
@spocke What do you mean with *finish it's rendering call*?

**Comment by jeroencornelissen** [comment]
Can we get some help on this issue?

**Comment by JeyKeu** [comment]
This is open for a very long time. Any workarounds?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
