### ISSUE TITLE
colorpicker & android 4.x support (fallback PNG overlays)

### ISSUE THREAD

**Issue by dev-101** [tinymce/tinymce#2468]
Hi, colorpicker plugin has a display problem in selected Android 4.0 - 4.4 devices (and possibly 5.x as well) with stock browser, because of limited/non-existent gradient overlay support.

This is how it appears:
![tinymce colorpicker plugin gradient android issue](https://cloud.githubusercontent.com/assets/5383059/11134116/b2977026-899a-11e5-9ad5-bc65e8e555d5.png)

It can be easily fixed with 2 fallback png gradient images:

```
.mce-colorpicker-overlay1,.mce-colorpicker-overlay2{width:100%;height:100%;position:absolute;top:0;left:0;background:url(img/colorpicker-gradient-overlay.png) no-repeat}

.mce-colorpicker-h{position:absolute;top:0;right:0;width:6.5%;height:100%;border:1px solid #CCC;cursor:crosshair;background:url(img/colorpicker-gradient-colors.png) no-repeat}
```

colorpicker-gradient-overlay.png
![colorpicker-gradient-overlay](https://cloud.githubusercontent.com/assets/5383059/11135704/ec22cc02-89a7-11e5-96fb-e715cd3c01e6.png)

alternative/improved colorpicker-gradient-overlay.png
![colorpicker-gradient-overlay](https://cloud.githubusercontent.com/assets/5383059/11154280/b6fcfa24-8a3e-11e5-8054-1e8a170deb36.png)

colorpicker-gradient-colors.png
![colorpicker-gradient-colors](https://cloud.githubusercontent.com/assets/5383059/11135710/f891464e-89a7-11e5-9582-db6e6e930a9f.png)

Fallbacks do work great.

Note: images were generated by me. Gradient overlay is not 100% perfect, but it is close. It could be improved to better emulate generated gradients.

**Comment by fyrkant** [comment]
Hi @dev-101 is this still a problem with the latest release of TinyMCE (4.6.2)?

**Comment by dev-101** [comment]
Hi, as far as I know, backward compatibility was never implemented, so the answer is - yes.

Cannot check it right now, as the basic/full featured example page does not work anymore in older browsers (editor is not even displayed in Results tab).

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
