### ISSUE TITLE
paste plugin + IE11 + word 2007 + <br>

### ISSUE THREAD

**Issue by stephanedelprat** [tinymce/tinymce#2469]
How to reproduce:
- Open attached file with Word 2007
- Open IE11 and go to http://www.tinymce.com/tryit/basic.php
- Copy the whole text from Word to tinymce

Result:
- br are removed

Expected result:
- br are kept

PS: I did not test other versions of Word, but I got the expected result "br are kept" with Firefox Chrome and Edge (Tested with Windows 10)
PS2: It also works with IE11 and without the paste plugin as you can see here: http://www.tinymce.com/tryit/custom_formats.php

Here is the file I tested with:
[tinymcepaste(1).docx](https://github.com/tinymce/tinymce/files/33774/tinymcepaste.1.docx)

**Comment by RolfBensch** [comment]
is there a workaround?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
