### ISSUE TITLE
Create snippet with toolbar button

### ISSUE THREAD

**Issue by Bugsbane** [tinymce/tinymce#2473]
Hi there,
While I love the snippet feature, and am personally technical enough to have figured out how to use it, it's currently far slower and more complicated than it needs to be from a UX perspective.

Rather than having to write code in a separate text editor, upload the file, modify tinymce.php etc, it could really be as simple as this:
1. User selects some text
2. User clicks a "Create snippet" button, placed next to the insert template button.
3. A popup dialogue asks for the name for the snippet and it's created + registered.

This can be done by the user in about 3 seconds instead of taking five minutes to sftp into their server, loading, modifying, saving files etc.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
