### ISSUE TITLE
Duplicit language cs_CZ

### ISSUE THREAD

**Issue by dosercz** [tinymce/tinymce#2481]
There is no sense to have two czech translations, cs translation is much better than cs_CZ, so I'm voting for cs and droping cs_CZ.

**Comment by fyrkant** [comment]
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.

**Comment by dosercz** [comment]
It's still an issue.

**Comment by lnewson** [comment]
Thanks for bringing this to our attention! Looking at https://www.tiny.cloud/get-tiny/language-packages/ `cs` is the only language shown now, so this appears to have been fixed since this was originally reported and as such I'll go ahead and close this. If I've missed something though, please let us know and we'll reopen this issue.
