### ISSUE TITLE
align top/middle/bottom

### ISSUE THREAD

**Issue by ManojSridhar** [tinymce/tinymce#2484]
Hi,
   I have a requirement to give the option in the tinymce editor to align the text in top/middle/bottom vertically. Can anyone guide me on this.

**Comment by spocke** [comment]
This can be handled with a custom plugin or the style formats. You can set the vertical-alignment property that way however this will only align vertically within the same line height. Alignment vertically otherwise is tricky you could use flex box in CSS or similar.

Not sure this is a bug report or a feature request since it can be "fixed" today with the tools that are available. So I'm closing this one.
