### ISSUE TITLE
plugin_url config option

### ISSUE THREAD

**Issue by davidearl** [tinymce/tinymce#2490]
Please could there be a config option plugin_url along the same lines as theme_url and skin_url. I am using extensive manipulation of the URLs with Apache's mod_rewrite, and the latter deal with where load tinymce loads things from, except for plugins. In the end I treated all the internal plugins as external ones, where you can give an absolute url, but it's a pity to have to do this, and it took me ages to work out how to work around this.

Hence:
  tinymce.init({
    ..
    plugin_url: "/tinymce/plugins/",
    ...
  });

**Comment by spocke** [comment]
Is this what you are looking for:
https://www.tinymce.com/docs/configure/integration-and-setup/#external_plugins

**Comment by davidearl** [comment]
Umm, no. That's what I'm already using to load the **internal** plugins, but what I'm after is a config option that lets me give the URL for the internal plugins so it doesn't try to guess (wrongly, when mod_rewrite is munging the urls). Apart from the contradictory naming, it means I have to supply the URL or every internal plugin separately, where what would be useful is to give the /tinymce/plugins/ part once and then the array of plugin names to load as normal (with plugins: [...])

**Comment by spocke** [comment]
But you can use that for the internal plugins as well it overrides where it looks for plugin X.

**Comment by davidearl** [comment]
Yes, I know, that's what I'm doing. But as I said it means you have to give a similar path for every one of 15 or 20 plugins, rather than just being able to say "the plugins are here", and it is a misnomer for internal plugins.

**Comment by donShakespeare** [comment]
Bump!!!
Or even 
```
tinymce.init({
plugin_url: "/tinymce/myPluginsCompressedJoined.min.js",
plugins: "-coolPlugin coolPlugin2"
});
```

This would be awesome

**Comment by mdhgriffiths** [comment]
*bump*

**Comment by rqton** [comment]
+1 for @davidearl. That's would be perfect :)

**Comment by ophite** [comment]
bump

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
