### ISSUE TITLE
"Insert/edit image" dialog hook callback

### ISSUE THREAD

**Issue by davidearl** [tinymce/tinymce#2491]
It would be really helpful to have a config option which provides a callback to be called when the image source input text box (and similar for media) change event is handled in tinymce, which given the URL can munge it and return a replacement.

Here's why: I have a site in which the editor runs in https, but people are likely to reference images from other sites in http. (These will ultimately be passed on in a formatted email). So what I want to do is replace http://www.example.com/im.jpg with /https/www.example.com/im.jpg so the image can be served by a local proxy.

It would also possibly avoid the need for all those complicated and hard to understand settings for getting tinymce to manage urls itself.

I have been able to do this quite successfully for myself using jQuery with a delegated event handler, like this:

```
    $("body").on("change", "div[aria-label='Insert/edit image'] input.mce-textbox", function(e){
      var jself = $(this);
      if ($("#"+jself.attr("aria-labelledby")).text() != "Source") { return; }
      var v = jself.val();
      if (v.substr(0,7) != "http://") { return; }
      jself.val("/https/"+v.substr(7));
    });
```

but it relies on (a) the order the events fire and (b) the structure tinymce uses for its dialog boxes. It would be much better if tinymce handled this.

Hence, for example:

```
    tinymce.init({
      ...
      image_url_callback: function(url){
        return (url.substr(0,7) != "http://") ? url : "/https/"+url.substr(7);
      },
      ...
    });
```

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
