### ISSUE TITLE
Generalise image drop / paste behaviour for any file type

### ISSUE THREAD

**Issue by jahudka** [tinymce/tinymce#2503]
It would be great if the paste / drop behaviour that TinyMCE currently employs for images was generalised for any file type (with perhaps an option to filter pasted / dropped files based on MIME type or extension) - non-image content could be represented in the editor with a link, but the upload mechanic could be the same, thus enabling a basic lightweight "attachment" option. Not necessarily hard to implement and would be a great feature.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
