### ISSUE TITLE
Fore|Back-color behaviour issue

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#2522]
The fore|back-color buttons behaviour was more user-friendly in 4.0 than in current versions.
Steps:
1. Write "abc",
2. Click the text-color button and select red color, write "def",
3. Just click the text-color button, write "ghi".

In 4.0 "ghi" is black. In 4.1, 4.2, 4.3 "ghi" is red and the HTML source contains redundant <span> tags. After the redundant spans are generated, setting the color back to black (using "no color" selector in color picker) is confusing (you need to repeat the procedure a couple of times).

If you decide that clicking the button should not unset the color that may be fine, but make sure no redundant spans are added.

**Comment by spocke** [comment]
So I guess it should be a toggle state and also I need to check into why it's generating redundant tags in this case. It shouldn't do that since the text is already red.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by alecpl** [comment]
This is not fixed!!!

**Comment by dsakko** [comment]
Reopening to track the fix for redundant spans.

**Comment by alecpl** [comment]
Still an issue in 4.7.13.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
