### ISSUE TITLE
Limit prism styles to TinyMCE only

### ISSUE THREAD

**Issue by nazar-pc** [tinymce/tinymce#2556]
Sometimes it might happen that standalone custom Prism theme might be included on the same page where editor is. In this case styles of standalone version might conflict with version bundled with TinyMCE. What about to prepend all classes of bundled version with something TinyMCE-specific? In this case styles will not be applied outside of TinyMCE and external styles will not influence bundled styles because of selectors specificity.

BTW, is there any way to control CSS file import?

**Comment by spocke** [comment]
Yes, we should do that for inline mode. I think prefixing would solve that since we can't know if the css is loaded elsewhere or not.

There is no way to block the loading of the prism css at the moment.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
