### ISSUE TITLE
pasting big images from word reduces the resolution

### ISSUE THREAD

**Issue by Demacri** [tinymce/tinymce#2571]
Hi, if I try to copy and then paste an image from word to tinymce editor, works but with big images it reduces the resolution
![c1](https://cloud.githubusercontent.com/assets/9558528/11906837/ce6e0e6c-a5cf-11e5-9f5e-72e9b5a54ac2.PNG)
![c2](https://cloud.githubusercontent.com/assets/9558528/11906838/ce702a76-a5cf-11e5-86c8-e583bc9bfdc9.PNG)

How to reproduce:
1) open word
2) drag and drop a big image(I tried with something about 1900x1200) in word
3) now select the image in word and press ctrl+c
4) paste the image in tinymce

In the screenshots you can see the resolution difference between word and tinymce.
Thanks for support, and Thanks for this awesome editor! :)

ps: tried with chrome 47

**Comment by AlexDevx** [comment]
instead if I drag and drop image directly from my computer to tinymce, it works perfectly with the right resolution! is there a solution?

**Comment by Shakil-Shahadat** [comment]
Have you tried `object_resizing : false`?

See https://www.tinymce.com/docs/configure/advanced-editing-behavior/#object_resizing

**Comment by AlexDevx** [comment]
Thanks for the answer
Yes, I tried it but the only result is the image not resizable in the editor

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
