### ISSUE TITLE
Sub-menu positioning is wrong with `remodal` dialogs

### ISSUE THREAD

**Issue by meglio** [tinymce/tinymce#2575]
Sub-menu positioning is broken when TinyMCE is placed in a [remodal](https://github.com/VodkaBears/Remodal#remodal) dialog.

The problem lies within `calculateRelativePosition()`. This function is used sub-menu position calculation when a top-menu item is clicked. The function currently only recognizes one special case:

```
if (ctrl.state.get('fixed') && DomUtils.getRuntimeStyle(document.body, 'position') == 'static') {
    x -= viewport.x;
    y -= viewport.y;
}
```

This case does not cover how _remodal_ works (and possibly other modal libraries as well, but I haven't tested).

When remodal dialog opens, the page scrolling is freezed and the modal appears viewport-centered (by default). When the `y`-position is calculated for the TinyMCE sub-menu, `calculateRelativePosition`does not recognize the TinyMCE container is fixed-positioned. As a result, the sub-menu is only positioned correctly when the page is scrolled to the top. As soon as you scroll the page down, the TinyMCE sub-menu moves to the top, while the TinyMCE instance does not.

To fix the problem, we had to add the following hack:

```
if (ctrl.state.get('fixed') && DomUtils.getRuntimeStyle(document.body, 'position') == 'static') {
    x -= viewport.x;
    y -= viewport.y;
}
// HACK START
else if (window.jQuery(targetElm).closest('.remodal').length) {
    x += viewport.x;
    y += viewport.y;
// HACK END
}
```

This hack isn't universal. However, it demonstrates the principle that should be introduced in the function: it should detect if the tinymce position is fixed, and if so, it should correct calculations by adding viewport's `x` and `y` to the coordinates being calculated.

The test could go through the TinyMCE' DOM parents to detect if any of its containers is fixed in its position. Hope this makes sense!

**Comment by force73** [comment]
It's one step in the right direction, thank you for this ...

**Comment by alxslnt** [comment]
The same thing in bootstrap modal https://jsfiddle.net/alxslnt/54dwbm2a/4/

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
