### ISSUE TITLE
paste_retain_style_properties not working from OpenOffice and LibreOffice text editors

### ISSUE THREAD

**Issue by FabriceGaudin** [tinymce/tinymce#2582]
paste plugin

I initialize a tinymce editor with this parameter: `paste_retain_style_properties: "font-style text-decoration"`, if I copy my text from Word, this param works, but when I copy my text from OpenOffice or LibreOffice, text color or size stays.
Even if I change to `paste_retain_style_properties: ""`, if I copy from Word, all style is removed, but if I copy from OpenOffice or LibreOffice, all style remains.

I reproduce easily the problem: http://fiddle.tinymce.com/EDeaab/2
1. Init a tinymce Editor with `paste_retain_style_properties: ""` (http://fiddle.tinymce.com/EDeaab/2)
2. Copy formatted text from OpenOffice/LibreOffice
3. Paste in tinymce editor

Result: Format remains
Expected results: All format must be removed

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by FabriceGaudin** [comment]
@blackcathikari I still reproduce it

**Comment by dsakko** [comment]
Hi, apologies for that. You are correct and I'll reopen this one for you.

**Comment by meetajhu** [comment]
Not just OpenOffice and LibreOffice has problem pasting from Google sheets as well.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
