### ISSUE TITLE
--content structure would disapper--- </ul> tag is not properly inserted

### ISSUE THREAD

**Issue by hikosato11** [tinymce/tinymce#2622]
if I do paste the text from attached text, the </ul> tag does not properly inserted and therefore content structure will disappear
[Line1.docx](https://github.com/tinymce/tinymce/files/88781/Line1.docx)

**Comment by nori-h** [comment]
We've looked into this and believe it is related to a few other bug reports regarding pasting lists from Word. The related reports are #2853, #3061, #1314, #1422, #1489, #1696 and #1708, and cover indentation, list styling and list item order not being preserved. Could you please take a look and let us know if you disagree? Thanks, the TinyMCE Team.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
