### ISSUE TITLE
Applying pre format to multiple blocks at once could combine blocks

### ISSUE THREAD

**Issue by ericandrewlewis** [tinymce/tinymce#2637]
While working with @iseulde on [wordpress#6331](https://core.trac.wordpress.org/ticket/6331) (Add a "code" button to TinyMCE), we stumbled upon interesting behavior. 

If a user has a selection that spans multiple block elements and then formats the selection to pre, each block element is changed to a `<pre>` element. 

I wonder if when applying a pre format to multiple blocks at once, the block contents could be concatenated with a double line break in between each? This seems like a user experience gain, as the result can be confusing, especially when pre blocks have css styling (e.g. background).

**Comment by ericandrewlewis** [comment]
Here's [a video showing the behavior](https://www.youtube.com/watch?v=B501fH5iJNU).

**Comment by spocke** [comment]
I changed the behavior now:
https://github.com/tinymce/tinymce/commit/7558e2269732e0c921d35393f78dd30ce1088587

Might add this under an option since doing a change like this on a patch release might be to radical and break integrations.

**Comment by ericandrewlewis** [comment]
Thanks @spocke! :smile: Putting it behind an option makes sense as this is quite the change.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
