### ISSUE TITLE
Html tags with display: inline or inline-block are removed when the last characters of text is deleted 

### ISSUE THREAD

**Issue by nicoladj77** [tinymce/tinymce#2638]
This is similar to #2510 and this is something that I experienced in Chrome/Safari, not in Firefox.
I've the following markup:

``` HTML
<div class="layout__item soft-small--bottom one-whole portable-one-whole ">
  <div class="svg-callout-container">
    <svg class="callout title">
      <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="icons.svg#number-01"></use>
    </svg><br>
   </div>
   <div class="callout-title push-small--left small primary-font primary-font--semibold">Title in black</div>
</div>

```

both classes, `svg-callout-container` and `callout-title`, have display set to inline-block. When I delete the last character of the `callout-title` div by pressing Backspace, the div ( but i tested with a `<p>` too ) with class  `callout-title` is removed. This doesn't happen if I remove `display: inline-block` from `callout-title`

I tested this on 4.3.3

**Comment by nicoladj77** [comment]
As a workaround, I'm suggesting to add text to the div before deleting the old one. This happens also if you highlight the whole text and replace it

**Comment by lassemt** [comment]
@nicoladj77 It also occurs on elements with display: block. I have been using the same workaround, but I was wondering if you have come up with any other fixes after this one?

**Comment by nicoladj77** [comment]
@lassemt no, I haven't. I've tried to have a quick look around but couldn't locate the component where this is happening. Do you have an idea of where to look?

**Comment by lassemt** [comment]
@nicoladj77 Sorry for answering so late, the project I was working out got put on the shelf for a while. I'm working on making a grid system for tinymce that works with shortcodes in wordpress. So I ended up putting a hidden div inside each column that I was going to use to delete columns, apparently this fixed my problem. The empty div also gets deleted when I backspace, so maybe adding a hidden element might be a solution.

I also looked into how lists are working in tinymce, because you would have the same problem in lists when you delete the last character. And tinymce have solved this problem for lists, the last list item actually stays when you delete the last character in it. This is because they add a bogus br when you backspace and the last character is deleted. 

I don't have too much time to look into it now, but I will definitely look at this problem again when I'm done with my school exams. Maybe @spocke can tell if I'm onto something by looking at how lists are working, or come up with another suggestion on where to look?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
