### ISSUE TITLE
Issue replacing highlighted text with inline mode

### ISSUE THREAD

**Issue by Michael4824** [tinymce/tinymce#2658]
Using the JSFiddle below, highlight any word and then replace it with different text.  The first letter is dropped.  (e.g. if I highlight "blue" and type "red", my end string becomes "yellow orange ed", the r is missing.)

https://jsfiddle.net/5Lzuqkt1/

This bug only appears to happen when inline is set, using a span, and the user uses Chrome.  The bug is not present in Firefox or IE.

Tested Using:
Windows 7 or 10
Chrome Version 48.0.2564.82

**Comment by spocke** [comment]
I think it needs to be a block based element as it's target. We might look into adding a check when initializing to make sure it's a block like div not span since spans cause all sorts of issues since they argent uniform.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by Michael4824** [comment]
Issue is still present in v4.4.0, ticket should be reopened.

**Comment by dsakko** [comment]
Hi Michael, yes my apologies. When testing internally we were unable to reproduce this but I can see your fiddle is still reproducing it. I'll reopen this for inclusion in a future release.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
