### ISSUE TITLE
Menutrigger if tinymce is inside a label

### ISSUE THREAD

**Issue by fabsn182** [tinymce/tinymce#2664]
Pen: http://codepen.io/anon/pen/wMjmME

Click somewhere in the menu or toolbar but not on a button/menu item. This might happen when you just miss an item or you click on a separator.

What's happening: the first button/menu item will get triggered in the lower example because TinyMCE is inside a `<label>`.

This should never happen since you will always trigger something you didn't mean to.
Changing the HTML is no alternative.

Solution: a click somewhere in the TinyMCE area should always trigger something like the jQuery `preventDefault()`.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by fabsn182** [comment]
Are you kidding me? To codepen shows the bug and you cannot reproduce it?
Have you even clicked the link?


Am 25. Juli 2016 5:15:36 vorm. schrieb blackcathikari 
<notifications@github.com>:

**Comment by dsakko** [comment]
Hi fabsn,
I've definitely checked out the codepen you've supplied, and thanks, it was helpful in tracking this one down. I'll try to elaborate, and apologies for not providing more info.

The root cause here is having TinyMCE in a label tag. Default browser behaviour is clicking on the content within a label tag triggers a click on the first input element - in this case, Tiny's File menu. Normally you'd have at most one input element within the tag, so having an instance of TinyMCE with lots of inputs is stretching the use of the label tag a little :) .

I hope this helps, but please feel free to add more info if there's a specific scenario you'd like TinyMCE to work in.

**Comment by fabsn182** [comment]
I create all my sites to be usable without Javascript; all my (single) inputs to be inside a <label>-tag. This makes setting both the `for`- and `id`-attributes unnecessary and it's perfectly valid. The problem is that if you have no file-menu but for example the "undo"-button at the very first position, clicking the toolbar and/or the label (places where a click shouldn't do anything) triggers the undo-function.

It might indeed be a more rare problem but it would be great if you could add something like jQuery's `event.preventDefault()` to the click on all toolbars (not buttons).

**Comment by dsakko** [comment]
Thanks for the feedback. I've logged this one as a possible improvement in a future release.
