### ISSUE TITLE
No content on Windows Cordova app

### ISSUE THREAD

**Issue by rudym87** [tinymce/tinymce#2666]
In a Cordova Windows Universal app, both on mobile and desktop; the the controls of the editor are visible, but the actual content is not visible and not editable.
In the console  I get this error:
`APPHOST9602: 'javascript:' is an invalid attribute value and will be ignored.  Don’t use 'javascript:' URIs in the local context.`
In fact the editor is an iframe with a "javascript:..." src attribute, which is against the [local context restrictions](https://msdn.microsoft.com/en-us/library/windows/apps/hh465373.aspx).
Are there any workarounds?

**Comment by spocke** [comment]
We use javascript: for older IE versions to avoid HTTPs warning message. Might not need that anymore. Currently a core fix is required so no workarounds.

**Comment by Wvhf** [comment]
Any solutions yet? Having the same issue

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
