### ISSUE TITLE
Bootstrap columns disappear

### ISSUE THREAD

**Issue by migliori** [tinymce/tinymce#2672]
Hi,

Here is the issue :
1. I create Bootstrap row with 2 columns inside (col-xs-*) into tinyMce
2. I remove content : columns are kept as intended
3. I attach Bootstrap css (content_css) in tinyMCE.init :
   `tinyMCE.init({
   [...]
   content_css: 'bootstrap.min.css'
   });
   `
   Then if I remove content colums are stripped.

Codepen here : https://codepen.io/migli/pen/vLrwyB

Thanks

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
