### ISSUE TITLE
CSS files for template plugin's iframe only

### ISSUE THREAD

**Issue by danomator** [tinymce/tinymce#2673]
The template plugin creates an iframe, where it loads HTML snippets and automatically inserts LINK elements for all content_css files. I have to provide the content_css setting in order to have the HTML in this iframe look right. But since I use the editor with inline activated, all content_css files are also appended automatically to the HEAD element of the main page. I already have my own LINK Element here and some CSS files are being loaded afterwards and may overwrite rules of this content_css file. When the editor appends this content_css file again and at the end of the HEAD elements, all overwritten rules reset, which makes my overall design look wrong. To avoid this, I use my own setting called _template_css_ instead of content_css and patched template/plugin.js (# 66-68, tinymce 4.3.3) like this:

`tinymce.each(editor.contentCSS.concat(editor.settings.template_css || []), function(url) {
                        contentCssLinks += '<link type="text/css" rel="stylesheet" href="' + editor.documentBaseURI.toAbsolute(url) + '">';
});`

The actual patch is:

`editor.contentCSS.concat(editor.settings.template_css || [])`

Is there a better way to provide CSS files which will only be used in the iframe of the template plugin (especially for inline editors)? Is there a chance a patch like this may be included in a future tinymce release?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
