### ISSUE TITLE
Backspace not removing the good object

### ISSUE THREAD

**Issue by rafdulaf** [tinymce/tinymce#2679]
Under Chrome 48/49 Linux/Windows.

Go to "Source mode" and replace all existing code by this one:
`<p>ertert</p>
<p><img src="blob:https%3A//s.codepen.io/6b580b55-0e79-4a8f-9fcc-54ed406259a9" alt="" width="256" height="62" /></p>`
Validate and put the cursor at the end (on the right of the image).
Press BACKSPACE.

Excepected behavior: the image should be removed
Actual behavior: the image is moved closed to the first para. Everything goes like the cursor was on the left of the image.

**Comment by tinydylan** [comment]
Hi,

I'm unable to get the content for your case - it looks like it got mangled in the GitHub issue text box. I actually did the same thing when responding to this issue - I think the trick is to put 3 backticks on one line, then paste the code, then put the final 3 backticks on a new line. 

I'm unable to reproduce the issue. I've tried on our [demo page](https://www.tiny.cloud/docs/demo/basic-example/#) with this content:

```
<p style="text-align: center;">etert</p>
<p style="text-align: center;"><img title="TinyMCE Logo" src="../../../images/glyph-tinymce@2x.png" alt="TinyMCE Logo" width="110" height="97" /></p>
```

but the backspace behaviour appears to be correct.

It's most likely that you've hit a problem that we've solved in the time since you've logged this issue. I've closed the issue for now, but please let us know if the issue still occurs. If it does, could you please ensure the content is within a code block? 

Thanks!
