### ISSUE TITLE
img inside a figure (problem with imagetools)

### ISSUE THREAD

**Issue by sbarex** [tinymce/tinymce#2680]
I insert a image inside a `figure` tag with the `image plugin`.
Then is not possible to select with the mouse the image but only the entire figure tag or the caption. So the imagetools toolbar can't activate.
The problem is because the figure tag has the attribute `contentEditable` set to false.
There is a reason to disable contentEditable?

Tested on chrome canary and firefox 44.

**Comment by rob006** [comment]
>  The problem is because the figure tag has the attribute contentEditable set to false.

This also makes impossible to use image as link, so you can't make thumbnail with link for full version of image.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by claviska** [comment]
This issue can be reproduced with a minimal example:

http://fiddle.tinymce.com/ELfaab

**Comment by blackcathikari** [comment]
Thanks for the fiddle @claviska. I had a play with it myself, I see what you mean. You can manually add `contenteditable="true"` to the image but that's certainly not the most-user friendly method. I'm not sure myself if this is a bug or intended though so I'm going to forward this onto the devs. Do you know what version of TinyMCE you're using, and whether you're using a local copy of Tiny or are getting it from the cloud?

**Comment by claviska** [comment]
It's the latest dist but also affects the edge version. Again, not sure I'd call it a bug — it's more like an undesirable side effect. Figured I'd post the fiddle since since I discovered it while testing something else. 🤷🏻‍♂️

**Comment by donShakespeare** [comment]
Ran into this issue today, and I dropped my jaw - the one. It is more like an undesirable bug @claviska

**Comment by blackcathikari** [comment]
Update: this is unfortunately a side effect and while we don't have plans to address this ticket specifically at the moment, the devs are aware of it now and have just started looking into a related problem which might mean some progress here too. I'm going to reopen this ticket because it is replicable, but again not sure we'll get to this in the near future.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
