### ISSUE TITLE
Translation "clipboard info" does not work

### ISSUE THREAD

**Issue by adminko-svk** [tinymce/tinymce#2682]
Hi,
I am using German translation and everything work fine, only when I click "paste button", TinyMCE displays info message in original language:

```
Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.
```

The translation in "de.js" file:

```
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": 
"Ihr Browser unterst\u00fctzt leider keinen direkten Zugriff auf die Zwischenablage. Bitte benutzen Sie die Strg + X \/ C \/ V Tastenkombinationen.",
```

Where is the problem?
I tested some languages files (*.js) and the problem is everywhere!

**Comment by adminko-svk** [comment]
Have you also this problem?
Nobody can help fix it?

**Comment by janniconl** [comment]
Same here. Not translating properly.

**Comment by adminko-svk** [comment]
Nobody can help?

**Comment by lnewson** [comment]
Hi,

Sorry that this hasn't been picked up earlier, however I just checked via http://fiddle.tinymce.com/4hhaab and this string now appears to be working as expected. It's likely we've fixed the underlying issue with this since you've logged the issue, so I'll go ahead and close this. If you're still experiencing issues though, please let us know and we'll reopen this issue.

Thanks!
