### ISSUE TITLE
Drag and drop images in Safari 9.0.3 (11601.4.4)

### ISSUE THREAD

**Issue by renderpci** [tinymce/tinymce#2685]
With TinyMCE 4.3.4 and Safari 9.0.3.

When you drag and drop any image, Tiny duplicate the image (create new tag and image).

You can see this in the home page of TinyMCE.

Image 1:
![screen shot 2016-02-11 at 10 41 07](https://cloud.githubusercontent.com/assets/8447635/12973363/2398a788-d0ac-11e5-8553-40bf8b2d3b1d.png)

Image 2:
![screen shot 2016-02-11 at 10 41 17](https://cloud.githubusercontent.com/assets/8447635/12973367/2cb85f16-d0ac-11e5-8513-20467925d03d.png)

**Comment by spocke** [comment]
This one is weird it doesn't happen on Chrome and it's only when the editor doesn't have focus.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
