### ISSUE TITLE
Fix creation of new root block when cursor is next to a div

### ISSUE THREAD

**Issue by rostagnolisandro** [tinymce/tinymce#2686]
I've added a custom button that inserts HTML to the editor.
More in detail, that button is to add youtube videos. The videos are inserted as an iframe, but I put the inframe inside a <div class="embed-responsive"><iframe.....
The class "embed-responsive" is a class from Bootstrap, and allows to make the video responsive.

However, this doesn't get well with tinymce: after having inserted the HTML, if I hit enter, tynimce creates the new root block like this: <div class="embed-responsive"></div>

That is, r**egardless of configuration forced_root_block = "p", the new root block created is a div and has the same class of the previously inserted one**.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
