### ISSUE TITLE
table_default_container

### ISSUE THREAD

**Issue by cochran1832** [tinymce/tinymce#2687]
Could you add a "table_default_container" to the options of the table plugin. There are instances where it is necessary to contain a table within a div or paragraph. We should be able to define a block element as the container and then add classes, styles, attributes, ect. to the container. I get there are work-arounds for this but it would be helpful to have a container added upon creation.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
