### ISSUE TITLE
TinyMCE stripping empty <div>s inside <td>s

### ISSUE THREAD

**Issue by paulschreiber** [tinymce/tinymce#2689]
Using WordPress trunk (4.5-alpha-36510) with TinyMCE 4.3.3 (2016-01-14).

TinyMCE is stripping empty <div>s inside <td>s.

Before:

```
<table>
<tr>
<td>
<div class="bar" style="width:100%; background-color:#ff2700"></div>
</td>
</table>
```

After:

```
<table>
<tbody>
<tr>
<td></td>
</tr>
</tbody>
</table>
```

Outside a table, this is preserved as expected.

```
<div class="bar" style="width:100%; background-color:#ff2700"></div>
```

**Comment by paulschreiber** [comment]
Interestingly, if you use a nonbreaking space:
```
<table>
<tbody>
<tr>
<td>
<div class="bar" style="width: 100%; background-color: #ff2700;">&nbsp;</div></td>
</tr>
</tbody>
</table>
```

And switch back to the visual editor, it preserves the `<div>` but strips the `&nbsp;`. Switching back and forth a second time will erase the `<div>`.

**Comment by paulschreiber** [comment]
Using `&#8291;` seems to be a valid workaround — that character is preserved.

**Comment by spocke** [comment]
This is kind of by design. div and td has whats called padding meaning that if they are treated as empty they will get padded with a &nbsp; this is to avoid useless span elements for example.

So this useless span gets removed: <div><span></span></div> and becomed <div>&nbsp;</div>
The same goes for table cells: <td><div></div></td> becomes <td>&nbsp;</td>

So I guess it should while checking if an element is considered empty check if they things in them are padded and always treat them as content.

We remove these empty elements since the user can never edit them if they are empty there is no way to place the caret inside them.

**Comment by Daijobou** [comment]
I have this problem too with a custom empty span but with a class. Tinymce should only remove empty tags which have not a class in it.

**Comment by hexalys** [comment]
I completely agree with @Daijobou. There is a very annoying persistent [issue with Wordpress 3.9+ removing empty `<i>` elements](https://core.trac.wordpress.org/ticket/28940) due to the tinymce 4 update. It affects *icon* elements being all removed. By default `<i>` elements will have at least one attribute.

If the element has a class or any other attributes. It shouldn't be removed.
Unless of course the attribute is specifically not allowed in a custom config.

**Comment by Ghostavio** [comment]
So, since 2016 no one took a look at this?

**Comment by TheNuclearCat** [comment]
It would be great if someone take a look into it, it breaks so many things in wordpress. Starting from Icons up to tables.

**Comment by spocke** [comment]
You can configure it to retain everything: http://fiddle.tinymce.com/Zsgaab by default we remove empty elements since they serve little purpose and is hard to edit in a WYSIWYG environment when there is no way to place the caret inside them.
