### ISSUE TITLE
iPad Safari : Virtual keyboard keeps poping up after Tinymce looses the focus

### ISSUE THREAD

**Issue by gwissem-mention** [tinymce/tinymce#2699]
Hi,

You can reproduce the issue on the own website of Tinymce : 
- Open Safari on iPad.
- Go to [https://www.tinymce.com/docs/demo/basic-example/](https://www.tinymce.com/docs/demo/basic-example/) .
- Go to the "Result" tab and tap inside the editor area to get the focus : you should see the virtual keyboard poping up.
- Now tap outside the editor area (but not on a link alement) to loose the focus : the keyboard remains open. (first bogus behaviour)
- Since now the keyboard keeps a strange behaviour : 
  - If you go to the "JS" or "HTML" tabs, the keyboard remains open.
  - If you manually close the keyboard, it will show up again everytime you tap anywhere on the page and remains open (for example on the "JS" or "HTML" tabs).
  - If you get back to the editor and click again inside the edior area and then manually close the keyboard, it behaves normally again ! (=> shows up when the editor gets the focus and hides when you go anywhere else)

I tried to debug a little bit, but unfortunately i'am not able to tell what is this caused by :/ 

Any feedback about this ?

**Comment by Steve-Richardson** [comment]
Confirmed here too!

It's something to do with focus, my best guess is to push the focus to something that doesn't bring up the keyboard on page load, but this is a good solution even if it works :(

Any one got any better idea on how to stop this from happening?

**Comment by blorriman** [comment]
I'm having exactly the same problem - if there is no solution I'm going to need to use a different textarea editor - any suggestions?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
