### ISSUE TITLE
Table context toolbar persists after editor closed

### ISSUE THREAD

**Issue by bjwildbore** [tinymce/tinymce#2701]
If you have an editor instance that is added and removed to a page you can end up with a situation where the table context toolbar still shows on the page even after the editor is closed.
Steps to repro:
1. Visit this page:
https://www.tinymce.com/docs/demo/inline/
2. Click on the content to open the editor
3. Insert a table anywhere in the editor
4. Enter some text into one of the table cells. (Only repros when table cell is edited)
5. Click outside the editor to close it.
The toolbar still shows.
![image](https://cloud.githubusercontent.com/assets/1875281/13065913/22ac025c-d4c6-11e5-84d8-fd2baf1dfc58.png)

**Comment by Zenorbi** [comment]
The problem seems to be in https://github.com/tinymce/tinymce/blob/e5019b456b60935f8be25400e0c31bdf34583eb5/js/tinymce/themes/modern/theme.js#L460
The `reposition()` re-shows the floating panel, even though the panel should stay hidden. As a temporary workaround, I commented out this line and everything seems to work ok.

**Comment by sutteth1** [comment]
We've got the same problem here with mulitple tinymce instances. We are using TinyMce 4.6.5.
![image](https://user-images.githubusercontent.com/9306853/29446762-33693b90-83ee-11e7-876e-a98b4d048fba.png)

Is there maybe a up to date workaround known? Otherwise it looks like we have to disable those toolbars until this is fixed.

**Comment by jordanade** [comment]
I'm getting this same thing with `5.0.1` and the quickbars_insert_toolbar.

**Comment by lnewson** [comment]
Hi,

I'm unable to replicate this issue using TinyMCE 4.9.10 and 5.2.2, so it's likely this issue has been fixed since the original issue was logged. As such I'm going to close this, but please let us know if you're still experiencing issues and we'll reopen this issue.

Thanks!
