### ISSUE TITLE
New option in Media plugin settings to add a callback for external embeds

### ISSUE THREAD

**Issue by srus** [tinymce/tinymce#2711]
I need to wrap the embeds/iframes with a `div` in order to make them responsive. For now the only way I found to do that is implementing a new plugin for pasting the iframe code. I think it's a waste of time making a new plugin just for that, so it would be better/easier if the Media plugin would allow adding a callback for embeds in the same way than `video_template_callback` for videos. Something like `embed_template_callback`.

**Comment by CaMer0n** [comment]
:+1:  I need this too.

**Comment by mbardelmeijer** [comment]
:+1:

**Comment by JayAdra** [comment]
+1

Also when putting a YouTube or Vimeo link in Source field, the editor ignores my "video_template_callback" and puts its own code?

We need to be able to control the markup for all videos and embeds.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .

**Comment by ahaverty** [comment]
@thedrjim  It would be great to have a "iframe_template_callback" setting for the media plugin.

**Workaround in the meantime:**
https://github.com/tinymce/tinymce/blob/e25ec422bcf3889fc47aa46f0a230666a21b5e22/modules/tinymce/src/plugins/media/main/ts/core/DataToHtml.ts#L22
I tracked down the template code (☝️), and put in a dirty workaround in one of my (ruby on rails) helper's:

```ruby
  def responsive_iframe_embed(html)
    html.gsub("<iframe", '<div class="embed-responsive embed-responsive-16by9"><iframe class="embed-responsive-item" ').gsub("</iframe>", "</iframe></div>")
  end
```

And an example of using it in one of my views:
```ruby
<%= responsive_iframe_embed(@apartment.apartment_type.description).html_safe %>
```

Not ideal, but it's working for us.
