### ISSUE TITLE
Google Chrome: getContent text format on inline editors with text-transform

### ISSUE THREAD

**Issue by danomator** [tinymce/tinymce#2713]
There's an unexpected behaviour in Google Chrome (48.0.2564.116 m) only. In an inline editor, `getContent({format : 'text'})` returns all contents in uppercase, if the container node is styled with `text-transform: uppercase`. It can be reproduced with this simple HTML file: [tinymce.zip](https://github.com/tinymce/tinymce/files/137868/tinymce.zip)

The returned text should use the real letters. Not those styled in uppercase. Since this only happens in Google Chrome, it might not be a tinymce related problem. But I don't have a workaround for that, so I let you know.

Edit:
In order to get the real text contents in Google Chrome, this seems to work:
`ed.getBody().innerHTML.replace(/<[^>]*>/g, '')` (`innerText` also returns everything in uppercase)
Or `ed.getContent()` with default format (html) and the `entity_encoding : 'raw'` option. But these are workarounds. `getContent({format : 'text'})` stays unusable for me.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .

**Comment by jpoints** [comment]
When opening a link if the link that has styling that alters the text, for example the css forces it to be upper case, <a style="text-transform: uppercase;" href="#">Hello world!</a>, then the display text in the insert link modal will display the text as uppercase. 

If the user edits the display text while in this state, then the text will be saved to the link as all uppercase (HELLO WORLD). 
The display text should have used the raw text value (Hello world!), so that alterations to the display text does not change the raw text value. 

If I had permission I would reopen.
