### ISSUE TITLE
Divs get converted to p tags when divs are not listed as a valid_element

### ISSUE THREAD

**Issue by seanjallen** [tinymce/tinymce#2725]
I have a tinymce element whose valid_element config is:

p[class|style],span[class|title|cid|userid|username|time],strong,em,a[target|href|title],blockquote,sup,sub,br

It seems like this causes tinymce to convert divs inside of the body to p tags on save. It seems more intuitive to me to just have them removed since they are not in the valid_elements list (or at least add another option to turn off the conversion behavior)? This becomes a problem when phantom divs (like those created by the paste plugin) are not cleaned up, and instead of being removed by the valid_elements whitelist check they get converted into p tags with their style attributes (display:none) dropped so they look like normal paragraphs that the user created in the editor.

Tested with Tinymce 4.2.8 in Chrome v48.0.2564.116 on Mac.

**Comment by spocke** [comment]
Root text nodes gets wrapped in paragraphs. So when the divs gets stripped they become root nodes and then wrapped in P tags. So this is the behavior you would get with that config and it's by design. If you want to keep the divs just allow them in the valid_elements if you want to convert them to something else add custom code for that.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
