### ISSUE TITLE
Dirty flag and Editor.setContent

### ISSUE THREAD

**Issue by bambuk6** [tinymce/tinymce#2739]
Editor.setContent seems to interfere with the dirty flag.

Fiddle: http://fiddle.tinymce.com/oqfaab

Steps:
1. Click the 'Show Dirty Flag' button - it shows isDirty=false.
2. Click on the editor (don't change content - just click).
3. Click 'Show Dirty Flag' again - it shows isDirty=true.

If Editor.insertContent is used instead - dirty flag stays false.

**Comment by pamtbaau** [comment]
@bambuk6 
In the meantime... Did you find a workaround for this issue?

**Comment by bambuk6** [comment]
@pamtbaauNo.. I have to compare original content with current to see it it's dirty. 

    On Tuesday, October 25, 2016 10:41 AM, pamtbaau <notifications@github.com> wrote:
 

 @bambuk6 
In the meantime... Did you find a workaround for this issue?—

**Comment by pamtbaau** [comment]
@bambuk6 
Working with  `editor.undoManager.clear()` and `editor.undoManager.hasUndo()` seems to provide a workaround for your use case. Have a look at this Fiddle [http://fiddle.tinymce.com/lAfaab/1](http://fiddle.tinymce.com/lAfaab/1)

**Comment by lnewson** [comment]
Hi,

Sorry for the late reply here, however as alluded to above, this is expected because the content is different from the initial state and focusing the editor triggers the undo manager to check for changes. So since the state was changed from the initial state (i.e. no content), a new undo level is created and it's flagged as dirty again.

A new [resetContent](https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#resetcontent) API was added in TinyMCE 5 to make it easy to reset the content and editor state. Here's a fiddle to show it works as expected: http://fiddle.tinymce.com/oqfaab/2 The resetContent API sets the content, clears the dirty state and resets the undo manager state (which was the part previously missing).

If you're still having issues using the above, then please let use know and we'll reopen this issue.

Thanks!

**Comment by JinKwangKu** [comment]
sadfsadf
