### ISSUE TITLE
More flexible table grid and table creation?

### ISSUE THREAD

**Issue by otter606** [tinymce/tinymce#2744]
Hi, 
 Our users like to create tables quickly using the table grid but find the 10x10 max size very limiting as for their work they often need 12x8 tables. It would be good if the table plugin could take additional configuration to:
1) Define max columns and rows appearing in the table grid (e.g. table_grid_columns=12, table_grid_rows=12)
2) Be able to access both the grid _and_ the regular table creation dialog. 
 e.g. so the table grid appears, but underneath the grid would be a 'Properties' button that would take you to the table configuration dialog. The use case here is that most of the time, the user is able to create a table quickly from the table grid, but occasionally they will want to create a very large table (e..g 100 rows) that would not be feasible from the table grid. Currently the only way is to tediously add rows one at a time to the bottom of the 10x10 table.
Additionally, it would be great to be able to add _n_ rows/columns to the table in one go. E.g. sometimes users may not know at creation time the size of the table, and want to expand it later.
An action 'Add _n_ rows'  and 'Add _n_ columns' would be useful here.
Thanks,
 Richard

**Comment by ZeGregg** [comment]
For sure the team should provide a way to display only table grid matrix from the toobar on 1 click

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
