### ISSUE TITLE
"page-break" with direct content is wrong

### ISSUE THREAD

**Issue by chrispcb** [tinymce/tinymce#2752]
Configuration : pagebreak_split_block: true
1. Insert a "page-break", the carret is at the end of line
2. type text
3. Show source code, the text after  is not displayed

Save is  #broken.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by chrispcb** [comment]
Thank you for your investigation, but in 4.4.0, I allways have this issue.
Checked on your web site (firefox 48) 

- go to https://www.tinymce.com/docs/demo/full-featured/
- "Edit on codepen"
- in js, insert "pagebreak_split_block: true" option
- codepen refresh
- File -> new document
- Insert -> Page break
- Insert text "hello word"
- Tools -> source code is not displayed
- "hello word"

**Comment by fabsn182** [comment]
Can confirm: that needs to be solved. Why has this issue been closed?

**Comment by dsakko** [comment]
Hi chrispcb,
Apologies for this. On the initial test we were unable to replicate the issue. Thanks for your instructions as this has helped me reproduce the issue. Can you confirm that this pen http://codepen.io/dsakko/pen/jAxgpO reproduces your exact scenario?

**Comment by chrispcb** [comment]
Hi,
Ok, no problemo!
Yes, I can confirm that this pen reproduces this exact scenario.

**Comment by fyrkant** [comment]
I can't seem to reproduce this anymore, are you still having the problem @chrispcb ?

**Comment by chrispcb** [comment]
@fyrkant yes, this problem still exists.
Look this pen http://codepen.io/dsakko/pen/jAxgpO

**Comment by odraencoded** [comment]
This happens because the pagebreak plugin inserts a `<p><img></p>`.

https://github.com/tinymce/tinymce/blob/a8c7c0e132cfcbdf0556f5ce82120093b4ba6d9d/modules/tinymce/src/plugins/pagebreak/main/ts/api/Commands.ts#L11-L14

https://github.com/tinymce/tinymce/blob/a8c7c0e132cfcbdf0556f5ce82120093b4ba6d9d/modules/tinymce/src/plugins/pagebreak/main/ts/core/FilterContent.ts#L15-L17

To figure out what's a pagebreak, the plugin searches through `<img>` tags and checks their classes. Since the plugin added an `<img>` wrapped in  `<p>`, it assumes it owns the parent of the `<img>`, which means if it deleted the entire `<p>` and replaced it by `<!-- page break -->` that's fine because that's supposed to be a pagebreak, not a paragraph.

https://github.com/tinymce/tinymce/blob/a8c7c0e132cfcbdf0556f5ce82120093b4ba6d9d/modules/tinymce/src/plugins/pagebreak/main/ts/core/FilterContent.ts#L40-L46

But tinymce treats `<p>` as editable paragraphs, which makes sense, that's why you can edit the element that will be deleted later by the plugin. :/

Personally, I don't like the way this plugin inserts pagebreaks, because I don't see the need in inserting something complicated like `<p><img></p>`. I think inserting a `<hr>` element instead would make more sense. I also would like it set only a single pagebreak instead of adding multiple #5787. So I tinkered with the source code to make a custom plugin to fit my needs.

https://gist.github.com/odraencoded/7da3e5d59205227ef77145b24b267b51

It works identical to `pagebreak`, but the plugin name is `readmore` instead. It inserts `<hr>` instead of `<img>`. There's no option to turn off splitting, but it looks like it works anyway in chrome because `<hr>` is a block element and can't go inside `<p>`. When the option `readmore_single` is set to true, it removes `hr.mce-pagebreak` elements before adding a new one.
