### ISSUE TITLE
Table Borders Do Not Work

### ISSUE THREAD

**Issue by ktroendle** [tinymce/tinymce#2753]
I see the behavior when using the TinyMCE demos.
https://www.tinymce.com/docs/demo/full-featured/
https://www.tinymce.com/docs/demo/basic-example/

Can not set table borders. You have to manually edit the Table Properties -> Advanced -> Style to get borders on tables. There should be a style UI (default to solid) control AND there should be a default border color. So if you select Border 1 or greater, it should select a default color of black or grey and default style solid.

**Comment by pootzko** [comment]
Any updates on this perhaps? Thnx

**Comment by pootzko** [comment]
Update - this approach works:

```js
        table_default_attributes: {
          border: 1,
          cellpadding: 4
        },
        table_default_styles: {
          borderCollapse: "collapse"
        }
```

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .

**Comment by mauricioprado00** [comment]
solution in here:
https://github.com/tinymce/tinymce/pull/10160

please vote up so they push the fix:
https://github.com/tinymce/tinymce/discussions/10165
