### ISSUE TITLE
Pasting from Excel

### ISSUE THREAD

**Issue by PaulDarling** [tinymce/tinymce#2756]
I have a relatively simple editor (version 4.3.6) using the following plugins "image link textcolor table contextmenu colorpicker".  My problem is that although I can create a table, If I try to paste one from Excel 2013 all the formatting (borders, colours etc) are missing, this is not the case if I first paste it into Word and then copy the word table into the editor.

**Comment by duro85** [comment]
I've encountered the same bug using excel 2010 with tinymce v 4.9.0

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
