### ISSUE TITLE
Incorrect French translations in the RichTextEditor

### ISSUE THREAD

**Issue by FRANCOISBONNET** [tinymce/tinymce#2760]
Hi,
According to SAP development for SAP S/4HANA, TinyMCE is responsible for the translation of the RichTextEditor.
We would like to report following inconsistencies in the French translation (see screenshot):
"View" menu item and "Find and replace" function are not correctly translated.
"View" is translated by "Voir" but should be "Affichage".
"Find and replace" menu item is translated by "Trouver et remplacer" but should be translated by "Rechercher et remplacer". Also, in the "Find and replace" dialog box, "Find" is translated by "Chercer" but should be "Rechercher".
![find and replace](https://cloud.githubusercontent.com/assets/17613644/13491108/d4b6a80a-e130-11e5-96e2-39fb24068b5a.png)

Thank you very much in advance for your help on that matter.
Best regards,
François Bonnet

**Comment by lnewson** [comment]
Translations for TinyMCE are done via community members, not by Tiny, so if you have an issue with the translations then you should be able to suggest fixes in transifex: https://www.transifex.com/tiny/tinymce/viewstrings/#fr_FR/core/23295079 It's worth noting it looks like most of these have been corrected since this was logged though. Either way, since this isn't handled by us directly I'm going to close this.

If you're an enterprise customer however, then that's a different story as Tiny does commission professional translations for enterprise customers. If you're an enterprise customer and still experiencing an issue, please log an enterprise [support ticket](https://support.tiny.cloud/hc/en-us/requests/new) and our support team can assist in getting this resolved.

Thanks!
