### ISSUE TITLE
Custom Attribute Support?

### ISSUE THREAD

**Issue by iam1me** [tinymce/tinymce#2764]
I'm attempting to use some of the configuration settings in the API to add a custom attribute to a span tag.

For instance:
	  tinymce.init({
		schema: 'html5',
		selector: 'textArea#templateEditor',
		plugins: ['code', 'image' ] ,
		content_css: 'styles/templateEditor.css',
		valid_classes: {
			'span' : 'template'
		},		
		**extended_valid_elements: '+span[myAttr]',**
		resize: true
	  });

I've also tried using valid_elements, custom_elements, and tried various settings like 'span[myAttr]' and '+span[myAttr]' etc.

Is there a way to get TinyMCE to support these custom attributes for standard tags like span?

**Comment by iam1me** [comment]
Actually - I found that I was about to get the following to work correctly:
tinymce.init({
schema: 'html5',
selector: 'textArea#templateEditor',
plugins: ['code', 'image' ] ,
content_css: 'styles/templateEditor.css',
valid_classes: {
'span' : 'template'
},

extended_valid_elements: '+span[myattr]',
resize: true
});


The only difference between this and the above is the casing of "myattr" versus "myAttr". The uppercase 'A' breaks it! This gives me what I need to continue what I was doing - but this should be marked as a bug.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by Ogure** [comment]
I have a similar problem, I can't use ngBootstrap attributes because they are case sensitive and extended_valid_elements only supports lowercase (for example with ngbTooltip or ngbPopover)

**Comment by dmitry-kostin** [comment]
seems issue is alive again on tiny v5

**Comment by blackcathikari** [comment]
Thanks for letting us know @dmitry-kostin. I suspect I know what the problem is, but could you please help us with a replication case? I tried to replicate the original bug report in Fiddle but couldn't get the right behaviour. My attempt is here: http://fiddle.tinymce.com/rCgaab/1

**Comment by dmitry-kostin** [comment]
@blackcathikari 
https://github.com/tinymce/tinymce/issues/4833

**Comment by blackcathikari** [comment]
Thanks @dmitry-kostin.

Regarding supporting case-sensitive attributes, the answer here, like Spocke said on #4833, is that unfortunately we can't do anything about it. Angular's case-sensitive attributes are not actually valid HTML. In accordance with the HTML spec, browsers themselves will lowercase all attributes on HTML elements. Since TinyMCE works in the browser, that means the editor output will always have lowercase attribute names. 

If you need case sensitive attribute names for any reason (I'm guessing you're using TinyMCE to create or edit Angular templates?) then I'm afraid you'll need to process TinyMCE's content yourself after you get it from the editor to transform the attribute names.

Alternatively, I would suggest contacting Angular to ask for a workaround for case-sensitive attributes.

Regarding the original bug report, we could maybe look at lowercasing any attributes we get in `extended_valid_elements` and related config properties, so that those properties will at least work with invalid casing. However, I'm not sure what the scope or cost of that could be, so I'll discuss it with the team before going any further with it.

**Comment by dmitry-kostin** [comment]
@blackcathikari 
Yes, thanks for detailed answer, 
You are right the purpose of this is to allow users to make an angular template across with regular templates, I've already thought about using lowercase in angular instead, but I had a strong feeling that this is part of wysiwyg editor.

Maybe some hack or internal workaround exist for this. Because after angular transform html will be valid in any case. Basically i need property like extended_valid_attributes and then it's up to me if something is valid or not; Eg I was able to do this trick with 'quill' wysiwyg editor, but moving to another editor is another headache.

**Comment by blackcathikari** [comment]
If you mean adding extended_valid_attributes to support case-sensitive attributes, there isn't anything we can do. We would support case-sensitivity if we could, but it isn't our code that is lowercasing the attributes - the browsers (Chrome, Firefox, IE, etc.) are. Browsers enforce the HTML specification that says that attributes must be lowercase - see [w3c.github.io/html-reference/documents.html](w3c.github.io/html-reference/documents.html). Since TinyMCE is a HTML editor that runs in the browser using contenteditable, the content in the editor is parsed by and limited by the browser's rules. Anything we tried to do to support case-sensitive attributes would just be reversed by the browser.

As far as I know, Angular is able to use case-sensitive attributes because it parses the "HTML" (which isn't valid HTML) you give it *then* sends it to the browser. Once it's in the browser Angular no longer cares about the attributes because all the required behaviour is already attached to the relevant elements. If you look at a web page that was rendered using Angular the attributes will be lowercase because the browser has filtered them, but it doesn't matter at that point because Angular has already done what it needs to.

As for Quill, it is able to use case-sensitive attributes in the editor because it isn't a HTML browser editor. Like Angular, it uses a different representation of the content (called "deltas" and written in JSON) which it renders into HTML when requested. Within the editor and when you request HTML from it, you would be able to have case-sensitive attributes. However, as soon as you render that HTML in a browser the attributes will once again be lowercased by the browser.

The best solutions I can think of using the current TinyMCE API are:
1. Add the Angular attributes you need to extended_valid_elements, use them in the editor (where they will be lowercase because of browser filtering) and write something that parses the editor content on submit/POST to capitalise the attribute names.
2. In the editor, use a custom data attribute to contain all the Angular attributes you want on an element, and on submit/POST parse the content to pull the Angular attributes out of the data attribute. See the specification for custom data attributes: [https://html.spec.whatwg.org/multipage/dom.html#custom-data-attribute](https://html.spec.whatwg.org/multipage/dom.html#custom-data-attribute). We do this for some styles, to keep the original values when the browser mutates them.

**Comment by GuillaumeBrook** [comment]
How about <svg viewBox="..."></svg> that isn't implemented in // 4.9.10 (2020-04-23)

extended_valid_elements: 'svg[viewBox]'

The viewBox attribute will be removed...
It is now a valid html attribute
