### ISSUE TITLE
Dialogs: The New Way?

### ISSUE THREAD

**Issue by iam1me** [tinymce/tinymce#2770]
In the documentation it says that there has been a change between how dialogs are done in TinyMCE v4+ from how it was done in v3. It says that v4 uses divs while v3 uses iframes - and that you can still use the iframe approach via the windowManager.

However, I haven't found anything specifying how to do it the v4+ way: what is the API to make a div dialog?

**Comment by donShakespeare** [comment]
Maybe they mean the notification
https://www.tinymce.com/docs/advanced/creating-custom-notifications/

If so, they are no match to the windowManager dialog
And I am not sure they are a replacement for the windowManager larger modals

**Comment by iam1me** [comment]
I'm referring to the custom dialogs page: https://www.tinymce.com/docs/advanced/creating-custom-dialogs/

Which says at the top: "In TinyMCE 3.x all dialogs where HTML pages that got loaded into a iframe or window. This was changed in TinyMCE 4 to make it easier to make plugins and fully support CDNs. But you can still load HTML based pages into TinyMCE dialogs by using the WindowManager."

And, indeed, if you go take a look at their v4.0+ plugins they aren't loading html pages - but are rather constructing the page with javascript. Unfortunately, I don't see anything about how we can take advantage of this new and improved version of custom dialogs that use divs instead of iframes and new windows.

**Comment by hlfcoding** [comment]
You'll basically need to dig through one of the existing plugins, although last I checked they're not well-written, a bunch of nested closures. `editor.windowManager.open`, when passed a plain config object (`title`, `data`, `bodyType`, `body`, `onClose`, `onSubmit`), returns a dialog window.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
