### ISSUE TITLE
how can I add prism line number plugin into tinymce

### ISSUE THREAD

**Issue by wubin1989** [tinymce/tinymce#2771]
I tried to add prism line number plugin into tinymce.
I used prism.js and prism.css with line number plugin integrated, but it couldn't display line number at all.
How can I fix it?

**Comment by spocke** [comment]
We ship it with the default prism code without line numbers. So this is currently not supported.

**Comment by wubin1989** [comment]
Do you have plan to support it?

**Comment by gabrielbratescu** [comment]
You can do it yourself, I did it this way:
1. At http://prismjs.com/download.html I chose core, a few languages and line numbers plugin. For CSS choose the desired skin, because TinyMCE has the default one. At the bottom at the page, 2 files are created (js and css) acoording to what you choose. Click download JS and download CSS.
2. Replace   tinymce_4.3.13/plugins/codesample/css/prism.css with prism.css generated in step 1.
3. Edit tinymce_4.3.13/plugins/codesample/plugin.min.js. Search for `<pre` and in the class property add `line-numbers` . It should now look like this: `(a.insertContent('<pre id="__new" class="language-'+b+' line-numbers">'+d+"</pre>")`. A little before that pre you will also find `(a.dom.setAttrib(f,"class","language-"+b)` , add the `line-numbers` class in there too, it should look like this: `(a.dom.setAttrib(f,"class","line-numbers language-"+b)`
4. Edit same file and add a new line with this thing (it is the line from prism.js generated in step 1 that take cares of line numbering). It should look like this:
   `!function(){"undefined"!=typeof self&&self.Prism&&self.document&&Prism.hooks.add("complete",function(e){if(e.code){var t=e.element.parentNode,s=/\s*\bline-numbers\b\s*/;if(t&&/pre/i.test(t.nodeName)&&(s.test(t.className)||s.test(e.element.className))&&!e.element.querySelector(".line-numbers-rows")){s.test(e.element.className)&&(e.element.className=e.element.className.replace(s,"")),s.test(t.className)||(t.className+=" line-numbers");var n,a=e.code.match(/\n(?!$)/g),l=a?a.length+1:1,r=new Array(l+1);r=r.join("<span></span>"),n=document.createElement("span"),n.setAttribute("aria-hidden","true"),n.className="line-numbers-rows",n.innerHTML=r,t.hasAttribute("data-start")&&(t.style.counterReset="linenumber "+(parseInt(t.getAttribute("data-start"),10)-1)),e.element.appendChild(n)}}})}();
`
5. Copy prism.js generated in step 1 to your your_website/js/ directory

If let's say you save the textarea content in a database and want to see it later in a normal HTML page,
you have to include in `<header>` the references to:
  - tinymce_4.3.13/plugins/codesample/css/prism.css
  - your_website/js/prism.js

I guess it will work with any other prism plugin.

Let me know if this was helpful  :)

**Comment by Xirt** [comment]
The solution appears to not work completely: in the editor the line numbers are not shown as I believe the hook created in step 4 is never triggered (quick analysis showed me that self.Prism is undefined). However, after saving the line numbers to show in the end result hence good on our way. Would love to see TinyMCE include the line numbers plugin by default though as the codesamples are now quite hard to refer to when having 10+ lines.
