### ISSUE TITLE
noneditable plugin changes focus after selection

### ISSUE THREAD

**Issue by elsuzio** [tinymce/tinymce#2776]
Sometimes, whenever you click a non editable element, the focus is lost and the document is automatically scrolled to the top or bottom of the page. 

Also, if two non-editable elements are together, you will not be able to position yourself between them, a click will always select one or the other.

These two bugs have appeared with the new noneditable plugin from the 4.3 version.

**Comment by spocke** [comment]
I need a way to reproduce this can you provide us with a fiddle at fiddle.tinymce.com?

**Comment by elsuzio** [comment]
There you have it: [http://fiddle.tinymce.com/Vsfaab/4](http://fiddle.tinymce.com/Vsfaab/4)

Steps to reproduce the bug:
- Load the fiddle.
- Scroll the editor to the middle of the content (without clicking it, use the mouse scroll).
- Click on the word "Morbi" (highlighted in red) at the start of the third paragraph. 

Always fails on Chrome, however, other problems exists at least on IE11: drag&drop following the same steps described above will change the focus to the end of the page.

Also, worth noticing:
- impossibility to click in the middle of two consecutive and adjacent cE=false areas (first paragraph, adspicing (cyan) and elit (orange)).
- it's not possible to change the style of a cE=false area, it was however possible with 4.1.9: a span was created outside of the cE=false area with the style and now it's not the case.

Thanks!

**Comment by ogdsgn** [comment]
Also running into this exact same issue. I have a number of n=cE=false areas and when I scroll down and click on one it automatically scrolls to the top of the page. 

Has any one found a solution for this yet?

cheers

**Comment by rachelslurs** [comment]
I've found the same issue in the context of a wordpress editor. I added a button to the editor interface for adding a snippet of text, and gave it the mceNonEditable class. Clicking on the non editable area the first time causes it to scroll to the top.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
