### ISSUE TITLE
Fullscreen plugin shortcut destroys square bracket for central/east european countries

### ISSUE THREAD

**Issue by tkapler** [tinymce/tinymce#2781]
Meta+Alt+F shortcut used for fullscreen plugin (https://github.com/tinymce/tinymce/blob/master/js/tinymce/plugins/fullscreen/plugin.js#L107) destroys possibility to type opening square bracket ([ character ) for Czech, Slovak, Polish and other central/east european countries.

This character is especially needed for WordPress, where it is used for shortcodes, but the developers consider this as a tinymce issue (https://core.trac.wordpress.org/ticket/35932), so please, if possible, use other character or allow definition of the shortcuts via language files (or find some best way how to solve it with wordpress guys). Thx

**Comment by spocke** [comment]
Updated the original wp ticket.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
