### ISSUE TITLE
menu & menu items custom size support

### ISSUE THREAD

**Issue by letsgolee** [tinymce/tinymce#2786]
This is not an issue but a request.

If toolbar_items_size is set as "small" then we have a small toolbar but the menu and menu items are stll the same.
A little change in theme.js then we have a small menus: 

``` javascript
        var enabledMenuNames = typeof settings.menubar == "string" ? settings.menubar.split(/[ ,]/) : defaultMenuBar;
        for (var i = 0; i < enabledMenuNames.length; i++) {
            var menu = enabledMenuNames[i];
            menu = createMenu(menu);

            if (menu) {
// {{{ here I added
                if (settings.toolbar_items_size) {
                    menu.size = settings.toolbar_items_size;
                }
// }}}
                menuButtons.push(menu);
            }
        }
        return menuButtons;
    }
```

**Still** menu items are unchanged. if I change a little futher then the source code should be touched, so I make a request. I mean if we set toolbar_items_size then menu and menu items can be changed by css settings.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
