### ISSUE TITLE
No apparent event to tell when toolbar elements are created.

### ISSUE THREAD

**Issue by programmin1** [tinymce/tinymce#2787]
It would be super useful to know when all of the toolbar ( _not the content_ ) is rendered. In cases where you need to get a particular editor's toolbar and change dom, you can change editor.theme.panel.$el and other buttons' elements.

You would think you could do editor.on('PostRender') but editor.theme.panel.$el and others don't exist at that point, I have tried a bunch of these, settimeout to wait to be last event, and it seems there is no simple event that is called on toolbar creation!

It would be great if you could
`tinymce.on('AddEditor',function(
.... editor.on("toolbarHasRendered", ... function...`

or similar. I'm using inline mode not iframe, if that matters.

**Comment by donShakespeare** [comment]
+1 
Will greatly enhance TinyMCE floating bubble bar

**Comment by programmin1** [comment]
It seems to be related to https://www.tinymce.com/docs/api/class/tinymce.dom.scriptloader/ when I did some debugging with object.watch. Any chance we can have an existing event for reliably seeing where all scripts loaded and editor.theme.panel exists, please? or even a duck-punch solution?

**Comment by Luke-SF** [comment]
Good example, donShakespeare

Is there any progress on this? Also it seems puzzling that there is no event for this or way to change default of hiding-when-inactive on inline, not-hiding-when-iframe-mode.

**Comment by programmin1** [comment]
@donShakespeare Did you check out the inline floating toolbar in their latest MCE 4.4 webcast? https://www.youtube.com/watch?v=024WptE1mtI&feature=youtu.be

Also setting a custom theme.js might be what you want.

**Comment by donShakespeare** [comment]
@Luke-SF yea, an event would be great, but if worse enters worst, there are a few methods to achieve exactly what you want.

@programmin1 great webcast, thanks for reminding me of it... I set to join the webinar, and clean forgot.
I have not entered the world of themes yet, I will soon.
The new inline floating toolbar is a welcome core addition, I'd say "it's about time, people!!!!"

My users have compared it with my legendary [tinymceBubbleBar.js](https://github.com/donShakespeare/tinymceBubbleBar). And tinymceBubbleBar.js comes at the top in plenty places. For example, it works flawlessly in both iframe and inline modes, no issues!!! It does not depend on any theme - so that means, it will not interfere or require you to change how you've been working.

The insert toolbar is awesome, great idea TinyMCE devs!!!
Now we need a core functionality (not plugin) that will insert block element at end or beginning of TinyMCE document.

In all, I can't wait to twist 4.4 to do all my biddings.
Oh...I heard the reasons they did not want to load Ace in that premium code source, but common people, there is CDN

I mean, I have two superb plugins, nothing to download:
https://github.com/donShakespeare/twAceEditor
https://github.com/donShakespeare/twCodeMirror

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
