### ISSUE TITLE
Safari: On focus is not always triggered

### ISSUE THREAD

**Issue by FabriceGaudin** [tinymce/tinymce#2792]
Sometimes, the "focus" event is not triggered on Ipad.

Example: http://fiddle.tinymce.com/Rsfaab/3
Steps to reproduce:
**On Ipad**
1. Focus the tinymce editor, the alert is showing, everything works great
2. Then focus the input field underneath
3. Focus again the tinymce editor, the alert is not triggered, you can type anything, and the editor is focused but the event is not triggered

**Comment by sgeraud** [comment]
I have experienced this issue on Safari 9.1 (Mac OS 10.11.4).
When I run the script, if I click below the tinymce editor, it seems that it is not blurred. That would explain why the alert is not triggered when focusing it again. Two clicks are necessary to really blur the tinymce editor, and then the alert will be triggered when clicking the editor again.

**Comment by FabriceGaudin** [comment]
@spocke Hello,
Do you know if there's any update on this one ? 
I still get the error.

**Comment by nori-h** [comment]
I believe this is similar to #2699. Could you please have a look and let us know if not? Thanks, Nori @ TinyMCE

**Comment by FabriceGaudin** [comment]
@nori-h onBlur works fine the first time (http://fiddle.tinymce.com/Rsfaab/4) so I don't think the problem is about losing the focus. Then it's not triggered, but maybe because it didn't focused correctly in the first place. I have no problem with the virtual keyboard. 

#2699 and this one may be linked (they both have to do with focus on Safari obviously) but they are different. Unfortunately I don't have any clue to explain this strange behavior.

**Comment by FabriceGaudin** [comment]
@spocke any update ?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
