### ISSUE TITLE
TinyMCE allows pasting multiple data images when paste_data_images is set to false

### ISSUE THREAD

**Issue by rpg1503** [tinymce/tinymce#2793]
Steps to reproduce (any browser):

1) Go to google, images tab and search for "large images"
2) Select and highlight multiple data images (not url images)
3) Copy (ctrl+c) them at once
4) Go to https://www.tinymce.com/
5) Paste (ctrl+v) data images into TinyMCE Editor

Images are pasted into the Editor and TinyMCE generates a large chunk of Html Code as a result due to the Image Data Encoding. It's also reproducible by copying Text + Data Image(s).

It works fine when I copy a single data image, which means TinyMCE does not allow me to paste it.

Has anyone ran into this same issue as well?

**Comment by wxlfight** [comment]
yes. i set paste_data_images false , it work in mac chrome, but not in window chrome.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
