### ISSUE TITLE
blockquote glues lines in br mode

### ISSUE THREAD

**Issue by dev-101** [tinymce/tinymce#2794]
Successfully reproduced on tinymce  fiddle: (4.3.8, Edge)

// specific config

>   force_p_newlines: false,
>   force_br_newlines: false,
>   forced_root_block: false,
>   remove_linebreaks: false,
>   remove_trailing_brs: true

// how to reproduce:

1) Start typing text in several rows, e.g.:

> a b c d e
> asfas fasf 
> asf asf a
> af asdf a
> af asfd f

2) Select that entire paragraph

3) Hit on blockquote. Result:

> a b c d easfas fasf asf asf aaf asdf aaf asfd f

(single line)

All lines are glued together in a single line instead of preserving paragraph structure. Working in "p" mode this does not happen.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
