### ISSUE TITLE
inserting "no-break space" does not work

### ISSUE THREAD

**Issue by fritzmg** [tinymce/tinymce#2797]
### Problem

Inserting a non breaking space in TinyMCE via _Insert » Special character » no-break space_ does not work.
### Reproduction
1. go to http://fiddle.tinymce.com/
2. click on _Run_
3. _(optional)_ type some text into TinyMCE 4's textarea and move the cursor within a word
4. choose _Insert » Special character » no-break space_

Nothing will be actually inserted. If you choose _Tools » Source code_ you won't see any additional space (or `&nbsp;`) either.

**Comment by HaraldWalker** [comment]
The charmap plugin has several 'space' characters that should add a decimal entity to the html and none of them seem to work. Reproducible with 4.3 version on tinymce.com demos.

**Comment by LudvikMichalek** [comment]
Any update on this, after more than year? I can reproduce the same error in 3.x.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
