### ISSUE TITLE
Fortify Issues

### ISSUE THREAD

**Issue by saroopg** [tinymce/tinymce#2814]
Hi all
We are having issues with Fortify scan for tinyMCE
In scan we are getting Critical and High issues related to tinymce

Critical >> Dynamic Code Evaluation: Code Injection

![code inj](https://cloud.githubusercontent.com/assets/13713310/14155467/d1ab20ea-f68f-11e5-9e21-c3b75cff5e55.JPG)

Abstract:

The file tinymce.min.js interprets unvalidated user input as source code on line 7. Interpreting user-controlled instructions at run-time can allow attackers to execute malicious code.

Explanation:

Many modern programming languages allow dynamic interpretation of source instructions. This capability allows programmers to perform dynamic instructions based on input received from the user. Code injection vulnerabilities occur when the programmer incorrectly assumes that instructions supplied directly from the user will perform only innocent operations, such as performing simple calculations on active user objects or otherwise modifying the user's state. However, without proper validation, a user might specify operations the programmer does not intend.

High>> tinymce.min.js:7 (Dynamic Code Evaluation: Code Injection)

![image](https://cloud.githubusercontent.com/assets/13713310/14155702/d393898c-f690-11e5-8bad-7461d224da07.png)

Abstract:

The file tinymce.min.js interprets unvalidated user input as source code on line 7. Interpreting user-controlled instructions at run-time can allow attackers to execute malicious code.

Explanation:

Many modern programming languages allow dynamic interpretation of source instructions. This capability allows programmers to perform dynamic instructions based on input received from the user. Code injection vulnerabilities occur when the programmer incorrectly assumes that instructions supplied directly from the user will perform only innocent operations, such as performing simple calculations on active user objects or otherwise modifying the user's state. However, without proper validation, a user might specify operations the programmer does not intend.

Can Some one help in solving these issues

**Comment by spocke** [comment]
I'm guessing it sees the eval and javascript: parts that is mostly to support IE 7-8. However since the minified file is just one big line of code it's hard to tell from that tool.

**Comment by saroopg** [comment]
We are actually stuck here. Our security team will not allow us to proceed unless the issues are fixed or has enough proof to prove that it is false positives. Any help in this regard is highly appreciated

**Comment by alecpl** [comment]
Don't use minified tinymce code. Download the development package and use tinymce.js file.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
