### ISSUE TITLE
Paste plugin: paste_filter_drop:true Doesn't work in 4.3.8

### ISSUE THREAD

**Issue by alphestdev** [tinymce/tinymce#2815]
If I understand this correctly, `paste_filter_drop:true` setting should convert HTML that is **drag&dropped** into editor into plain text, if `paste_as_text`  is also set to **true**.

If this is correct, then it doesn't work as of latest v4.3.8. Pasting HTML with right click does convert it to plain text normally, but dragging HTML into editor still keeps HTML and all the formatting. In my case all controls for extended formatting do not exist in the UI and user is unable to remove formatting after HTML is drag&dropped into editor. User has to reload the page and start over. Very frustrating.

It's not the browser issue because all the drag&dropped content is available in `paste_preprocess()` function. I could create a workaround there, but I wasn't able to find out how to use TinyMCE's native functions to convert HTML to plaintext.

**Comment by spocke** [comment]
I don't think we have logic to force plain text on drop.

**Comment by alphestdev** [comment]
While waiting for the official implementation, I've created a custom drop handling to make this work.

```
editor.on('drop', function(e){
    e.preventDefault();
    // Convert drag&dropped data to plain text (should happen by default, but does not? bug?)
    editor.selection.placeCaretAt(e.clientX, e.clientY);
    editor.insertContent((e.dataTransfer.getData('Text')).replace(new RegExp('\r?\n','g'), '<br>'));
    editor.focus();
});
```
Does it help?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
