### ISSUE TITLE
Insert template overlay problem with browser window zoom

### ISSUE THREAD

**Issue by jamesharvard** [tinymce/tinymce#2816]
When the browser window zoom level is increased (in Chrome at least) then the 'insert template' overlay begins to expand off the bottom of the screen (dependant on screen size). The 'OK' and 'cancel' buttons are then not visible to the user.

TinyMCE v4.3.7. Apologies if it's been fixed in a new version, but it's not very easy to test with the CodePen examples that presumably use the latest versions. Also CodePen reports that you need to confirm your email address before full screen mode is available.

![Screenshot showing 'insert template' buttons going off-screen](https://cloud.githubusercontent.com/assets/14975019/14174481/6adf7020-f73c-11e5-9c24-3e961cf77df0.png)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
