### ISSUE TITLE
Request: Option to disable TinyMCE 4 tooltips in favor of browser built-in tooltips

### ISSUE THREAD

**Issue by alphestdev** [tinymce/tinymce#2821]
Current behavior is not as user-friendly as browser built in tooltips as TinyMCE tooltips do not have a delay before they show up (makes them annoying), the positioning is not optimal because the mouse cursor overlaps tooltip text making it partially not readable.

Also we use browser's built-in tooltips across the the whole system. In addition to the above, we would like tooltips behavior to be consistent, and use browser built-in tooltips in wysiwyg editor as well.

Please make this optional.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
