### ISSUE TITLE
Dragging images inside content editor not working in Microsoft Edge with paste_data_images:true

### ISSUE THREAD

**Issue by jeffreymolina** [tinymce/tinymce#2824]
1.  Using codepen (http://codepen.io/tinymce/pen/NGegZK) in Edge 25.10586.0.0 set paste_data_images:true in options.
2.  Try to drag and drop image already in content to another line or position.

Image cannot be moved.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
