### ISSUE TITLE
Bug: Unnescessary <br> inserted after empty <ul> or <ol> when forced_root_block:false (v4.3.8)

### ISSUE THREAD

**Issue by alphestdev** [tinymce/tinymce#2827]
When applying Numbered list or Bullet list on an empty selection, there is a new unnecessary `<br>` inserted. Each time it's pressed.
This happens on `forced_root_block:false`

To reproduce the bug:
http://codepen.io/anon/pen/wGPpJb?editors=1010

Steps (also included in the codepen example):
1) Create new line between line 1 and line 2 by pressing Enter at the end of line 1.
2) Press Numeric list or Bullet list repeatedly. Each time the list is added, there will be a new BR tag inserted below.

**Comment by blackcathikari** [comment]
We've looked into this, and it seems that this bug and #2831 are generally related to `forced_root_block: false` causing extra `<br />` tags to be inserted. Would you agree? Regards, the TinyMCE Team.

**Comment by alphestdev** [comment]
Only this one is related to forced_root_block:false. #2831 isn't. As mentioned in descriptions

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
