### ISSUE TITLE
Bug: Formatting as Pre block inserts extra <br> between each line

### ISSUE THREAD

**Issue by alphestdev** [tinymce/tinymce#2831]
Steps to reproduce bug:
1) Select both Line 1 and Line 2.
2) Press Formats > Blocks > Pre.
3) `Line 1<br>Line 2` becomes `<pre>Line 1<br><br>Line 2<pre>`

Found in v4.3.8

http://codepen.io/anon/pen/reYoOx?editors=1010

**Comment by alphestdev** [comment]
This also happens with paragraphs, with forced_root_block: true:

`<p>Line 1</p><p>Line 2</p>` becomes `<pre>Line 1<br><br>Line 2<pre>`

Please fix asap. We are about to release our software.

**Comment by alphestdev** [comment]
Is there any chance you can fix this soon?

**Comment by blackcathikari** [comment]
In reply to your comment on #2827 @alphestdev, I can only reproduce this with forced_root_block: false; in the init code. If I remove that line, the additional `<br>` isn't added. Could you please confirm that it is the same for you? I want to make sure this is definitely a TinyMCE bug. I'm aware that without that option the `<pre>` is wrapped around all the text in the editor, not just those lines but that is, I believe, expected behaviour because the lines of text are broken up with `<br>` tags. 

I am testing mainly with IE11, FF47 and Chrome 51 on Windows 7. What environment(s) are you using?

Thanks, 
Millie @ TinyMCE.

**Comment by alphestdev** [comment]
Tested again today. I can confirm it's only with `forced_root_block: false;`.

**Comment by blackcathikari** [comment]
Thank you @alphestdev! 
- Millie @ TinyMCE

**Comment by alphestdev** [comment]
We are still experiencing this (major) formatting bug. Will this be fixed?

**Comment by blackcathikari** [comment]
@alphestdev I reminded the devs of this, as you can see from Spocke adding that label, but there's no ETA on a fix unfortunately.

**Comment by alphestdev** [comment]
Additionally found while debugging: What actually happens is TinyMCE replaces ANY amount of `<br>` with two. So  `Line 1<br>Line 2` becomes `<pre>Line 1<br><br>Line 2<pre>` and  `Line 1<br><br><br>Line 2` becomes `<pre>Line 1<br><br>Line 2<pre>`.

I was about to release a patch that replaces double br with singles afterwards, but because of this I'm unable to reliably detect if the number has increased or not when TinyMCE applies formatting.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
