### ISSUE TITLE
Request: Configurable option to Indent/Outdent with spaces or tabs

### ISSUE THREAD

**Issue by alphestdev** [tinymce/tinymce#2833]
While using the editor primarily for code, comments about code and other technical stuff, current identation is far from optimal. It inserts blocks where not needed, modifies padding of currently existing blocks (causing unexpected behavior) and is unable to outdent existing spaces.

Would you be willing to implement the ability to Indent/Outdent with **spaces** or **tabs**? 

Code formatting inside the editor plays a very important role for our user base. We would value it a lot to provide a good experience to them.

**Comment by spocke** [comment]
We will likely implement more strict rules to HTML indentation. Preserving white space is more or less impossible since it would produce a random mess out code indentation. We have had thoughts of applying rules for space/tab indentation of tables and lists for example.

**Comment by alphestdev** [comment]
I'm talking about blocks of code, whether `<pre>` or a custom `<div>`, it doesn't matter. As long as we can have a block level element, containing inline text that can be indented by spaces/tabs, each line independently.

**Why codesample plug-in is not usable as it is now**
Codesample plugin is a nice intent, but not convenient to use. 1) The code is not editable directly inside the editor. 2) It pops up a dialog, which is another interface that distracts user's focus and also breaks consistency of dialog behavior system wide. 3) It makes all other content not editable while editing code inside the modal dialog. 4) It introduces additional effort for the users. `1. Navigate 2. Click 3. Edit 4. Navigate 5. Click`, instead of `1. Edit`. We are not asking our users to do that each time the want to insert or fix a typo. Our (task management system) users write and rewrite the code a few dozen times a day, commonly with a few edits per task. If we introduce this kind of inconvenience, it will be worked around by not using code blocks and typing code as normal text, decreasing readability and reducing overall reputation of our system. We can't make a conscious decision to do that. 5) In addition to the above disadvantages, codesample is unable to indent/outdent anyway.

We would appreciate a very basic block, with `&nbsp;` / `\t` indention, that's it. Direct inline edit, no dialogs, no modals, no extra clicks. As it is now, except now we are unable to indent lines.

**Comment by alphestdev** [comment]
Any chance this will be implemented?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
