### ISSUE TITLE
Bug: Indenting a single line inside <pre> indents the whole <pre> block

### ISSUE THREAD

**Issue by alphestdev** [tinymce/tinymce#2834]
Like the title states: Indenting a single line inside `<pre>` indents the whole `<pre>` block, as seen in 4.3.8

Also, if there is already padding set in CSS for that `<pre>`, it's just replaced. For example if it's set in CSS to `15px` and `tinymce.settings.indentation = '15px'`, then first indent will do nothing visually. 15px is replaced by 15px. In case CSS padding is set to less than `tinymce.settings.indentation`, then first indent will even decrease the padding.

Reproduce:
http://codepen.io/anon/pen/jqaojZ?editors=1010

**Comment by spocke** [comment]
Yes, we indent at block level so each paragraph gets indented.

**Comment by alphestdev** [comment]
@spocke There are no paragraphs here. I mentioned `pre` tag, which purpose is to contain code. Otherwise it makes no sense to have it at all. In code, each line is separate and it makes no sense to indent all of them at once. Padding for the whole block is already done by CSS.

**Comment by fresc81** [comment]
I also think the indention of pre elements not optimal. A solution could be to use margin-left instead of padding-left for indention. At least for pre elements. This would still indent at block level though, but the indented pre-elements (which mostly are rendered within wells) would't look so odd. I guess this would also be good for indention in general but maybe I miss some side effects here.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
