### ISSUE TITLE
Bug: Adding/Removing block formatting also removes <br> brefore, after and inside the block

### ISSUE THREAD

**Issue by alphestdev** [tinymce/tinymce#2837]
Reproduce the bug:
http://codepen.io/anon/pen/NNXdEB?editors=1010

Steps (included in codepen):
1) Select Line 3.
2) Press Formats > Blocks > Blockquote.
3) BR tag above is removed.
4) Press it again to remove the formatting.
5) Now the BR below is also removed.

TinyMCE version 4.3.8

**Comment by alphestdev** [comment]
Addition: All `<br>` tags **inside** the block also disappear!

**Comment by alphestdev** [comment]
Is this going to be fixed? It's been a year..

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
