### ISSUE TITLE
Group new lines in paragraphs with tinyMce 4

### ISSUE THREAD

**Issue by alvarotrigo** [tinymce/tinymce#2838]
TinyMce by default uses paragraphs elements `<p>` to wrap the text on each line.

This is, every time you press enter to create a new line, this will create another paragraph. 
This is not quite desirable and that's why sites like Stackoverflow or Github Issues won't do it this way. 

Ideally I would like to get the following

```html
    <p>
       a <br/>
       b <br/>
       c <br/>
    </p>
    <p>
       d
    </p>
```

With the following input:
```html
    a
    b
    c

    d
```
And this is what I'm getting at the moment
```html
    <p>a</p>
    <p>b</p>
    <p>c</p>
    <p>&nbsp;</p>
    <p>d</d>
```
I tried the option [forced_root_block](https://www.tinymce.com/docs/configure/content-filtering/#forced_root_block) and set it to `false`, but then the result is I do not get a single paragraph:
```html
    a<br>
    b<br>
    c<br>
    <br>
    d
```
Any way to do this?

**Comment by spocke** [comment]
TinyMCE uses Google docs, Word, Libre office as benchmarks all those produce paragraphs on enter except that some of them might have 0 margin applied to those paragraphs.

I think we might remove the forced_root_block in the future and instead provide some form of plugin that wraps unwraps lines in paragraphs on load/save since it seems that it's only a minor part of usages of tiny that needs br that would be mail clients and commenting systems.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.
