### ISSUE TITLE
:active state is not triggered on toolbuttons in Firefox and IE

### ISSUE THREAD

**Issue by alphestdev** [tinymce/tinymce#2842]
When clicking on TinyMCE UI buttons, like toolbuttons and dialog buttons, the styles defined under `:active` in CSS never appear. There is no pressed down button style. This can be observed at least in IE11 and FF45. It appears ok in Chrome.

For ease of detection, compare FF vs Chrome ﻿pressing and holding mouse in **lightgray-gradient** skin on http://skin.tinymce.com/. But it also happens in the editor on your home page https://www.tinymce.com/

As far as I researched, this is prevented in your JS code. Please fix.

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by alphestdev** [comment]
I still see the problem with TinyMCE 4.4.0 on my site, on your homepage and the skin.tinymce.com. In both FF 47.0.1 and IE 11. How can you miss it?

**Comment by dsakko** [comment]
Hi, can you give us some more specific detail? 

The active styling of the toolbar buttons is applying correctly on mouseup, but are you referring to the active button styling on mousedown on the toolbar buttons for Firefox?

**Comment by alphestdev** [comment]
@dsakko `:active` CSS rule applies to the state of the element **during mouse down** (starting at mousedown and ending at mouseup JS events). What you are probably referring to is selected state. That's not what this bug report is about. Here I'm talking about the state of the toolbuttons while user holds the mouse button down.

For the ease of comparison set a red background in CSS under `:active` for toolbuttons. Red will be visible only in Chrome.

**Comment by dsakko** [comment]
I understand what you are saying but wanted to make sure we were referring to the same events and styling. I will reopen this.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
