### ISSUE TITLE
Image source path is converting into blop instead of real path

### ISSUE THREAD

**Issue by ghost** [tinymce/tinymce#2851]
Dear Folks,
I have an issue with latest tinyMCE editor, whenever I try to select and edit the image, it's source is converting into blob path like this.

[blob:http://localhost/87d42e34-9961-412c-914b-dc6a77ab68e0](url)

Did anyone of you face this issue or resolved... ?

Please help

**Comment by alecpl** [comment]
Confirmed on https://www.tinymce.com/ using Firefox.

**Comment by spocke** [comment]
This is by design if you edit images or add base64 images they will be converted into blobs and blob urls while within the editor until you call uploadImages on the editor instance. Or is it always producing these blob urls if so I can't reproduce it.

**Comment by siddhartha2083** [comment]
Thanks Spocke for your response, whenever I try to edit the image using Image tools, the path converts to blob, and suppose if I drag that edited image somewhere, it disappears, please suggest any solution on this.

**Comment by AlexTang0620** [comment]
Is there anyway to let the img tag contain src of the photo instead of the blob after using the editing tools?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
