### ISSUE TITLE
Dropdown panel is not properly affixed

### ISSUE THREAD

**Issue by jsowndarrajan** [tinymce/tinymce#2852]
Hi Team,

When a user selects the drop-down list, it will open the list panel but, when the user scroll the page the panel potion is not moved along with selected drop-down button instead its stays on the same page.

You can reproduce this problem on [this](http://skin.tinymce.com/) page (select any drop-down list on TinyMCE editor)

But this problem is not occurred in codepen demo. How to resolve this problem?

Thanks & Regards,
Sowndarrajan Jayapal

**Comment by spocke** [comment]
There is a pull request that enables you to specify a container for the editor that kind of solves this. We are looking into merging that.

**Comment by tinydylan** [comment]
If I've understood the issue correctly, I believe it still occurs in TinyMCE 5.2.0.

To replicate
1. Open http://skin.tiny.cloud/t5/
2. Shrink the browser window so that a scrollbar appears.
3. Open a drop-down menu.
4. Scroll the browser - the top of drop-down menu is no longer touching the menu button.

It looks like this:

![image](https://user-images.githubusercontent.com/41112113/79749560-c2624b00-8352-11ea-89bc-057be8da5e6a.png)
