### ISSUE TITLE
Paste Word - Numbered list items issue in IE11

### ISSUE THREAD

**Issue by woeteEASI** [tinymce/tinymce#2853]
Hi all,

I'm having a problem when I paste a word text into TinyMCE.
The issue is only noticed on IE11, probably earlier versions aswell.
The issue remains with all TinYMCE4 versions (4.0 /4.1 /4.2 /4.3)

Could anyone help me with this?

THanks in advance.

This in WORD
![image](https://cloud.githubusercontent.com/assets/18482422/14559592/19b303d6-030a-11e6-9dc8-4344a22ad309.png)

becomes this in TinyMCE
![image](https://cloud.githubusercontent.com/assets/18482422/14559576/068da8ec-030a-11e6-9cf1-1a13d0afa258.png)

**Comment by blackcathikari** [comment]
We've looked into this and believe it is related to a few other bug reports regarding pasting lists from Word. The related reports are #2853, #3061, #1314, #1422, #1489, #1696 and #1708, and cover indentation, list styling and list item order not being preserved. Could you please take a look and let us know if you disagree? Thanks, the TinyMCE Team.

**Comment by stevenmoberg** [comment]
[IE11 enhancements](https://blogs.msdn.microsoft.com/ie/2013/10/24/enhanced-rich-editing-experiences-in-ie11/) convert MsoLists to html Lists, but this only works correctly with simple lists.  If you paste into a div with contenteditable with IE10-vs-IE11 you can see what type of Word content is getting messed up.   Since this is happening prior to the paste event I'm not sure if it can be disabled

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
