### ISSUE TITLE
Plugin image: Caption image check too generic

### ISSUE THREAD

**Issue by qwerdy** [tinymce/tinymce#2854]
The check for caption images in the image plugin is very generic, and causes problems with non-caption-enabled images.

It will set "contenteditable" to `True` on any <figurecaption> in a <figure> when the class matches `/\bimage\b/` (which is _very_ generic)

Setting the editor setting "image_caption" to `False` does not seem to disable the behavior either, it just removes the option from the image dialog.

**Comment by spocke** [comment]
I guess we could add a way to configure the class that it acts on so you can specify a less generic one.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
