### ISSUE TITLE
Clear Formatting not removing elements added by styles with wrapper:true

### ISSUE THREAD

**Issue by ETPac** [tinymce/tinymce#2864]
Steps to reproduce:
1) in tinymce config add the style
 {title: "mystyle", block: "div", classes: "my_style","wrapper":true},
2) select a section of text that you want to apply a style to. 
3) apply style.  You will see that the editor added a div to wrap the content
4) select same text and select style again and note that the added div is removed.
5) reapply the style to a section of text
6) select text and clear the formatting using "Clear Formatting" button
7) note in the source that the <div> tag still remains. 

This also appears to be happening with inline tags as well.  We are seeing span tags that are getting added for inline styles, but remaining when clear formatting is selected

Thanks!

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
