### ISSUE TITLE
Paste from Word link display text gets cut-off in lists

### ISSUE THREAD

**Issue by bokibxs** [tinymce/tinymce#2872]
Link display text gets pasted ok while out of lists, in lists it gets cut-off on first dot, so:
www.google.com becomes google.com
and
google.com becomes just com

![word-content-example](https://cloud.githubusercontent.com/assets/313137/14717517/f508b4b2-07bf-11e6-8ae0-6ae6a126ce7d.png)
![tinymce-paste-results](https://cloud.githubusercontent.com/assets/313137/14717522/f8009162-07bf-11e6-868a-323f6062be6f.png)

**Comment by bokibxs** [comment]
here is example test 
[test.docx](https://github.com/tinymce/tinymce/files/230371/test.docx)
word document attached too

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
