### ISSUE TITLE
mceAutoResize doesn't work anymore on post render

### ISSUE THREAD

**Issue by cclaerhout** [tinymce/tinymce#2885]
Demo available here: http://fiddle.tinymce.com/Zvfaab
Triggered error : 

```
TypeError: self.quirks is undefined
self.quirks.refreshContentEditable();

```

It was working with 4.3.8 version, after this, no more.

As a workaround I can use the focus event, but I would like first to check with you if you confirm or not this is a bug.

**Comment by aduth** [comment]
We encountered a similar issue, and it seems to be rooted in trying to call `focus` during `PostRender`, as the `quirks` object has not yet been instantiated at this point.

Commit: https://github.com/tinymce/tinymce/commit/b4576a4
Line: https://github.com/tinymce/tinymce/blob/b4576a4/js/tinymce/classes/Editor.js#L1097

Note `PostRender` is called before `quirks` is assigned: https://github.com/tinymce/tinymce/blob/b4576a4/js/tinymce/classes/Editor.js#L975-L977

Minimal fiddle: http://fiddle.tinymce.com/Dwfaab/1

In original comment, `focus` is called as a result of `execCommand`:

![image](https://cloud.githubusercontent.com/assets/1779930/15035792/6b503944-1254-11e6-8dc3-cb9277ee0a4f.png)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
