### ISSUE TITLE
tinyMCEPopup is undefined in Tiny_mce_popup.js file in TinyMCE editor 4.3.7

### ISSUE THREAD

**Issue by shweta-16** [tinymce/tinymce#2888]
Hi,
I have currently upgraded TinyMCE package to 4.3.7 in my application as the older version 3.8 was not running on IE11.
We have a customised plugin named LoadImages in the tinymce plugins. This plugin has the following code:

(function(tinymce) {
    tinymce.create('tinymce.plugins.LoadimagesPlugin', {
        init : function(ed, url) {
            // Register commands
            ed.addCommand('mceLoadimages', function() {
                ed.windowManager.open({
                    file: url + '/Loadimages.aspx',
                    width: 480,
                    height: 270,
                    inline : 1
                }, {
                    plugin_url : url
                });
            });
            // Register buttons
            ed.addButton('Loadimages', { title: 'Insert image',tooltip: 'Insert/edit image', cmd: 'mceBNPimages' ,  icon: 'image' });
        }
    });
    // Register plugin
    tinymce.PluginManager.add('Loadimages', tinymce.plugins.BNPimagesPlugin);
})(tinymce);

The Loadimages.aspx page refers the LoadImage,js file. It also refers the tiny_mce_popup.js files in compat3x plugin folder. Content of LoadImage.js file is as follows:
tinyMCEPopup.requireLangPack();

var LoadimagesDialog= {
    init : function(ed) {
        tinyMCEPopup.resizeToInnerSize();
    },

```
insert : function(file, title) {
    var ed = tinyMCEPopup.editor, dom = ed.dom;

    tinyMCEPopup.execCommand('mceInsertContent', false, dom.createHTML('img', {
        src: tinyMCEPopup.downloadURL,
        alt: tinyMCEPopup.title,
        title: tinyMCEPopup.title,
        border : 0
    }));
    tinyMCEPopup.close();
}
```

};
aspx page tries to upload the image on another server. It has the following code to call tinymcepopup:

```
           javascriptContent += "<script type='text/javascript'>";
            javascriptContent += "    var urlDownload = '" + downloadPage + "';";
            javascriptContent += "    tinyMCEPopup.downloadURL = urlDownload;";
            javascriptContent += "    tinyMCEPopup.title = '" + txtTitle.Text + "';";
            javascriptContent += "    LoadimagesDialog.insert('', '');";
            javascriptContent += "</script>";

            Page.ClientScript.RegisterClientScriptBlock(GetType(), "uploaded", javascriptContent);
```

When I execute the above code I get error in tiny_mce_popup.js file at the following line:
if (t.features.translate_i18n !== false) {
            var map = {
                "update": "Ok",

It says t is undefined where t refers to tinyMCEPopup.
I have followed all the steps in order to use older plugins (in 3.x) in tinymce 4.3.7 version.
I have added reference of tiny_mce_popup.js file in  compat3x plugin and referred compat3x plugin in the list of plugins during TinyMCE configuration.

could you please help me know the cause of this error and how to fix it.
I am struggling with this issue since couple of days and need a solution for this.

**Comment by shweta-16** [comment]
Any updates on the above issue please?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
