### ISSUE TITLE
Can no longer set toolbar to show manually in latest TinyMCE

### ISSUE THREAD

**Issue by programmin1** [tinymce/tinymce#2890]
In earlier versions (4.2.8) you could have an input directly related to a inline TinyMCE field, set so that selecting it does not hide the editor toolbar, confusing the user:

```
jQuery('[type=text]').on('focus', function() {
        tinymce.activeEditor.fire('focus')
});

```

Unfortunately this does not work in the latest TinyMCE in Chrome, you can hardly ever actually get the related input to work, clicking it just jumps to the TinyMCE editor to type into it:
http://fiddle.tinymce.com/IKeaab/2

Is this a deep bug within MCE or am I missing a function other than fire('focus') that can call up the toolbar, yet not force focus?

**Comment by programmin1** [comment]
If #2787 were fixed we could know if editor.theme.panel.$el exists and after that event, call $el.show() as necessary.

**Comment by Luke-SF** [comment]
I'm surprised this is so deeply tied to inline vs iframe mode - seems [inline ](https://www.tinymce.com/docs/demo/inline/)editor cannot be set to always show a toolbar, and there isn't an option to not show toolbar when unfocused, on the default [iframe MCE editor](https://www.tinymce.com/docs/demo/basic-example/). Can we have an option to customize/override this behavior?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
