### ISSUE TITLE
Element after a table cannot be deleted with backspace in Firefox

### ISSUE THREAD

**Issue by dabalyan** [tinymce/tinymce#2892]
Elements after a table cannot be deleted with a backspace button. It can only be deleted with the delete button.

Can be reproduced on TinyMCE's own demo page:
https://www.tinymce.com/docs/demo/basic-example/

Steps to reproduce:
1. Put caret in the element after the table
2. Press backspace and remove all the content in the element
3. Now pressing backspace in the empty element will not do anything

![github image](https://cloud.githubusercontent.com/assets/17353112/14983152/0f643f14-1159-11e6-90bc-1434e6fdd6ff.png)

**Comment by dabalyan** [comment]
@spocke what's the status on this ? any progress ?

**Comment by mayurdhanokar8527** [comment]
@spocke same issue here wxpect get a positive feedback soon

**Comment by mayurdhanokar8527** [comment]
@spocke shall we really wait the bug to be resolved

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
