### ISSUE TITLE
Fullpage inserts default header HTML

### ISSUE THREAD

**Issue by cyau73** [tinymce/tinymce#2896]
When I enable Fullpage and upload an HTML, there is an additional block of code inserted at the top.
This has two effects:
1. Prevents the WYSIWYG preview.
2. Reformats the HTML code.

Can this additional code be disabled and the reformatting of the HTML? I just need it to be cut and paste HTML code as it is for Fullpage.

<!DOCTYPE html>
<html>
<head>
</head>
<body>

</body>
</html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><meta content="telephone=no" name="format-detection"><title>POSB Variant Programme</title><style type="text/css">/\* Default styles on body. And prevent Webkit and Windows Mobile platforms from changing default font sizes. _/body {    background-color: #ffffff;  margin: 0;  padding: 0; -webkit-font-smoothing: antialiased;    font-family: Arial; -webkit-text-size-adjust: none; -ms-text-size-adjust: none;}/_ Fixes for Links catering to mobile devices _/.androidWhite, .appleLinks a, .appleLinksWhite a {  color: #ffffff !important;  text-decoration: none;}.appleLinks a, .appleLinksDark a {   color: #444444 !important;  text-decoration: none;}/_ End:Common Style Fixes _//_\* Start:: Custom

**Comment by cyau73** [comment]
Found an old forum issue on this. 
Seems the bug has re-appeared or is there some config I need to set?
Can I use vpapadop's code until a fix is done?

http://archive.tinymce.com/forum/viewtopic.php?id=23303

**Comment by spocke** [comment]
Seems to be working by design. When the fullpage plugin is enabled a default html header/footer will be added to the contents that is the purpose of the fullpage plugin. Can you please setup a fiddle at fiddle.tinymce.com so I can see this problem in action?

**Comment by jorrigala** [comment]
Issue I faced is if I don't use fullpage plugin, it is removing the html,head and body tags,
and If I add fullpage plugin, it is adding html, head and body tags,

What I was look for is, it shouldn't modify my html.

you can test with following code in http://fiddle.tinymce.com/3Wfaab

`<html><body>without fullpage, editor is removing html,
head and body tags <br />
with fullpage plugin, editor is adding html,head and body 
tags</body></html>`

paste the above code in source code plugin

https://github.com/tinymce/tinymce/pull/3843 
I thought this will fix the issue.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
