### ISSUE TITLE
image_title not translatable

### ISSUE THREAD

**Issue by dcohend** [tinymce/tinymce#2905]
Hi,

I'm adding the following line to tinymce.init:
image_title: true

This gives me the ability to add image title in the image dialog in tinymce.

The problem is that when I open the dialog, the line for image_title is not translated to Hebrew. Actually, I have an account in transifex and it is not possible to translate 'image_title' to Hebrew (only the other parameters, such as the image description, could be translated).

Please add the ability to translate the image_title text string instead of hard code it.

Thanks,
David

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
