### ISSUE TITLE
Tinymce cannot handle a < unless there is a space after it.

### ISSUE THREAD

**Issue by happioca** [tinymce/tinymce#2906]
I read about the issue discussed last December (#2567) and feel very unsatisfied with the answer and the fact that the issue was closed.

I use Tinymce for medical content and sometimes it is necessary to state something like 

<0.01 (no space between the < and the number.)

If I enter < 0.01 the content is saved correctly;  I can also later edit the content later via tinymce and it is rendered correctly.

However, if I enter <0.01 (no space after the <) the content is saved correctly but if I try to edit the content again, everything after the < is truncated. (the 0.01 disappears).

The original closed issue #2567 explain this in detail. Could you try it, and see what happens, remember to save first and then edit the content again with tinymce. It always saves first just fine. It is upon a subsequent edit that all content after the less than sign is truncated.

**Comment by spocke** [comment]
I'm not sure that I can explain it better than in #2567 you need to properly entity encode the contents in side textareas or you won't be able to edit the contents if you type a<b since the browser won't see a difference between that and a tag like <b> the browser is able to handle some edge cases but not all of them we have our own parser that doesn't handle all edge cases since this issue is so easy to fix if you just properly entity encode the contents in the editor.

So this:
<textarea>a&lt;b</textarea>

Not this:
<textarea>a<b</textarea>

**Comment by spocke** [comment]
I created a fiddle to illustrate the point: https://jsfiddle.net/5ndjxLx9/

The first a<b is rendered since it's a space around the "<" the second is not rendered since the browsers html parser thinks that is a tag.

So even if we would fix the edge case where you can type `a < 10` it would still break if you typed `a<b` since that is how the browsers parse HTML and there is nothing we can do about that it's just the way the parsers work.

I also created a fiddle with tinymce that shows how it loads/saves contents with < and > characters in there. http://fiddle.tinymce.com/Uwfaab

**Comment by happioca** [comment]
thanks for the explanation.

**Comment by toddmay1** [comment]
happioca - I found a fix to my Dec concerns.  Below is a simply regex fix that I found works for us.

I wanted to update this item with a regex that others can use if you encounter a similar issue.  This fix is in perl, but should work in other languages.

Issue we encountered:
Adding <3 into TinyMCE results in public web display working good.
Attempting to edit item from database results in javascript error.   Even if standard HTML encoding is used to encode <3 into &lt;3 when returned data inside textarea for tinyMCE.

Fix:
You must encode your return results to TinyMCE in javascript friendly encoding (not just HTML encoding).   So if you try and send HTML encoding like &lt;3 to tinyMCE, it will fail.

The fix I used was to simply perform a regex replacement on our database value we are sending back to TinyMCE editing.
$yourTinyMCETextAreaData =~ s/\&(\w+)\;/\&amp;$1\;/ig;

The above regex is simply saying (take standard HTML escaped stuff and make it javascript friendly encoding).   So &lt;3  turns into &amp;lt;3.

The () you see in the regex is telling the regex to remember letters between & and ; like lt, gt, amp, etc.   It then stuffs that into $1.   We then transpose what we used to send &lt3; into &amplt;3

Hope that helps some folks.

**Comment by happioca** [comment]
great thank you.

**Comment by dtonhofer** [comment]
Just as a heads-up for people googling this, I think I am hitting this issue in Foswiki 2.1.2 (latest version is 2.1.4), but there writing something like a nonspaced "<500" in text-only editing mode results in TinyMCE locking up the whole Firefox if you edit the page in WYSIWYG mode later. I will upgrade the Foswiki and see what happens.
