### ISSUE TITLE
TinyMCE problems with BBCode encoding Bulleted Lists

### ISSUE THREAD

**Issue by Howshall** [tinymce/tinymce#2907]
Found 2x related problems associated with TinyMCE and BBCode encoding of standard basic unordered bulletted list.

1) Currently the TInyMCE BBCode Plugin does not include any code to support converting HTML into BBCode for standard HTML unordered bulletted list. i.e. `<ul><li>...<li></ul>` even though the BBCode for this is very simply `[list][*]...[/list]` - Please could this additional code be added to BBCode plugin?

2) A related bug is that if you do add a simple 2 item Unordered Bulletted list into TinyMCE configured to use BBCode plugin, then on 'Ok' of view 'Source code' it will cause duplicate opening and closing `<ul>...</ul>` tags to be added and any single list with multiple items to be split instead into into multiple 1 item lists.

So on 1st open of View Source you would see:
![initial tinymce visual appearance](https://cloud.githubusercontent.com/assets/13105488/15148289/7337a522-16bc-11e6-9719-6320fe03befb.jpg)

And opening 'View source' you would initially see correctly BBCode encoded [b] Bold and [i] Italic, with still HTML but otherwise correct `<ul>...</ul>` (As mentioned missing feature in 1) above)

```
[b]bold[/b] [i]italic[/i]

<ul>
<li>List 1</li>
<li>List 2</li>
</ul>
```

but then immediately after saying 'Ok' to 'View source' model pop-up TinyMCE previous now changed to look like:
![after view source ok tinymce visual appearance](https://cloud.githubusercontent.com/assets/13105488/15148372/d1be6202-16bc-11e6-9eef-94ea5b48829b.jpg)

And if 'View source' is immediately re-opened the reason for visual preview change is obvious as source has been updated by TinyMCE tool to now be:

```
[b]bold[/b] [i]italic[/i]




<ul>
<ul>
<li>List 1</li>
</ul>
</ul>


<ul>
<ul>
<li>List 2</li>
</ul>
</ul>
```

Please let me know if you need any more information or clarity to investigate/confirm these 2x behaviours in latest v4.3.11 code with BBCode plugin.

**Comment by mythjuha** [comment]
Still an issue

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
