### ISSUE TITLE
Cursor selection and scroll jump at the end of iframe

### ISSUE THREAD

**Issue by zmoky** [tinymce/tinymce#2908]
When embedding a iframe, after dragging and dropping the scrollbar near the iframe, the selection cursor jumps after the iframe ( the selection should be set previously to another location - for example: inside of a first paragraph ). 

After this if you scroll anywhere on the page the scroll position jumps back to the end of the iframe where the cursor jumped previously.

There is an example that I tested directly in the demo editor at https://www.tinymce.com/

`````` <p>&nbsp;</p>
<p style="text-align: center; font-size: 15px;"><img src="images/glyph-tinymce@2x.png" alt="TinyMCE" width="110" height="97" /></p>
<p style="text-align: center; color: #7e7e7e; font-size: 15px; font-family: avenir; font-weight: 200;">TinyMCE is a platform independent web-based JavaScript HTML WYSIWYG<br /> editor control released as open source under LGPL.</p>
<p style="text-align: center; color: #7e7e7e; font-size: 15px; font-family: avenir; font-weight: 200;">&nbsp;</p>
<p style="text-align: center; color: #7e7e7e; font-size: 15px; font-family: avenir; font-weight: 200;"><iframe src="//www.youtube.com/embed/XHirn93DlfI" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
<p style="text-align: center; color: #868686; font-size: 15px; font-family: avenir; font-weight: 200;"><em>TinyMCE enables you to convert HTML textarea fields or other HTML elements to editor instances.</em></p>
<p>&nbsp;</p>```
``````

**Comment by AboLojy** [comment]
if i understood this correctly i think i fixed this when i removed the body {position:relative;} , then it worked perfectly. i don't know what's the connection but it worked for me

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
