### ISSUE TITLE
Paragraph breaks when pasting plain text

### ISSUE THREAD

**Issue by davidearl** [tinymce/tinymce#2909]
If you paste plain text, tinymce appears to treat a single newline as a line break (&lt;br&gt;) and two or more newlines as end of paragraph and start of a new one. This seems sensible. However, if someone inadvertently puts a space on the blank line, it looks exactly the same to them (both before the paste in the original editor, and after the paste in tinymce), but behaves completely differently because it is rendered as two line breaks (&lt;br&gt;'s). My user couldn't understand why changing the first block to a heading then affected all the text.

I think the pattern that presumably controls this should allow white space between the new lines.

**Comment by ayZagen** [comment]
+1

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
