### ISSUE TITLE
Table plugin scroll bug

### ISSUE THREAD

**Issue by pliasetski** [tinymce/tinymce#2921]
Hello,
When I'am adding a table and resizing it, double scroll appears.

Double scroll is only appears with "auto resize" plugin.

You could check it here: http://codepen.io/Pashka/pen/EKzGXr

My screen resolution is 1920x1080.

Also you could check it on attached image:
![table scroll bug](https://cloud.githubusercontent.com/assets/2900934/15353248/c18d872a-1cf0-11e6-9c56-a6397a3d3928.PNG)

or video: https://dl.dropboxusercontent.com/u/73896408/Tinymce_table_scroll.mp4

With best regards, Pavel Liasetski

**Comment by freeads777** [comment]
@pliasetski I tested it in Chrome, I only see one bottom scroll bar. Just thought I'd let you know.

**Comment by pliasetski** [comment]
@freeads777 I'll added a video how you could reproduce this issue

**Comment by tinydylan** [comment]
Hi,

I have tested out this issue on Chrome/Firefox on Mac and Chrome on Windows. Unfortunately, I can't reproduce it. It's likely that this bug has fixed since you logged this case. Also, I'm unable to see the video - I get a 404.

If the bug happens again, please let us know and we can reopen this ticket. There might be something subtle that I'm doing wrong, which is causing me to not see the issue.

Thanks!
