### ISSUE TITLE
Remove editor with table in Edge error

### ISSUE THREAD

**Issue by SRoeffaers** [tinymce/tinymce#2923]
When I remove an editor where I have used a table,
I get following error in the console:
SCRIPT5007: Object expected
tinymce.min.js (3.3953)

I have tinyme 4.3.12 and I only get the error in Windows 10 Edge,
other browsers work as expected..
This is the command i use:
tinymce.execCommand('mceRemoveEditor', false, "active_editor_id");

**Comment by spocke** [comment]
Can you setup a test case at http://fiddle.tinymce.com that reproduces the issue so that we can look at it. Thanks

**Comment by Kleppo** [comment]
Here is the fiddle: http://fiddle.tinymce.com/cyfaab/2
If you open it in Edge on Windows 10, and you edit the table (insert a number after 'a' for example),
and you click on 'submit', you see the error in the console..

**Comment by oleksiipavlenko** [comment]
Could be the problem with the same original policy

**Comment by Niniania** [comment]
Is there any news on this ? Still getting the error in Edge in latest version of Tinymce, its making the Editor unusable for us in Edge browser as we add and destroy components and the Editor along with them and get this error.

**Comment by hasangursoy** [comment]
Having the same issue. Any workaround?

**Comment by Niniania** [comment]
Hi
From what I remember we had to rewrite the page to not destroy and recreate components but to reuse them.
Regards


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Hasan Gürsoy <notifications@github.com> Date: 13/07/2018  18:05  (GMT+01:00) To: tinymce/tinymce <tinymce@noreply.github.com> Cc: Niniania <ninniani@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [tinymce/tinymce] Remove editor with table in Edge error (#2923) 
Having the same issue. Any workaround?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tinymce/tinymce","title":"tinymce/tinymce","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/tinymce/tinymce"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hasangursoy in #2923: Having the same issue. Any workaround?"}],"action":{"name":"View Issue","url":"https://github.com/tinymce/tinymce/issues/2923#issuecomment-404878126"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/tinymce/tinymce/issues/2923#issuecomment-404878126",
"url": "https://github.com/tinymce/tinymce/issues/2923#issuecomment-404878126",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [tinymce/tinymce] Remove editor with table in Edge error (#2923)",
"sections": [
{
"text": "",
"activityTitle": "**Hasan Gürsoy**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@hasangursoy",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"tinymce/tinymce\",\n\"issueId\": 2923,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"tinymce/tinymce\",\n\"issueId\": 2923\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/tinymce/tinymce/issues/2923#issuecomment-404878126"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 142948718\n}"
}
],
"themeColor": "26292E"
}
]
