### ISSUE TITLE
When pasting from MS Office, decimals in unordered lists turn to integers

### ISSUE THREAD

**Issue by KarlBaumann** [tinymce/tinymce#2940]
There is a really nasty bug, which totally messes up the data when pasting from MS Offive, and the worst thing is that it is very difficult to notice a difference with larger amounts of text.

![wordpress paste bug](https://cloud.githubusercontent.com/assets/11026930/15476624/69a59ec0-2110-11e6-8ad5-b7570d65fb99.gif)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
