### ISSUE TITLE
Unable to use "id" attribute on Gmail

### ISSUE THREAD

**Issue by ueharak** [tinymce/tinymce#2941]
Following tags are provided by Anchor Plugin.

```
<a id="test"></a>
```

When it send via Gmail, Gmail omits id attribute as follows.

```
<a></a>
```

Because of this behavior, anchor on Gmail is broken.

https://github.com/tinymce/tinymce/pull/2915 is a p-r of this issue.
Adding new option to enable anchor plugin provide name attribute instead of id.

**Comment by merwok** [comment]
IMO using `a id` for anchors is a bit wrong / old-school (but not as much as `a name`!), any element can receive an ID since HTML 4.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
