### ISSUE TITLE
Browser spell checking not working instantaneously in chrome

### ISSUE THREAD

**Issue by itsananto** [tinymce/tinymce#2960]
I have used **browser_spellcheck: true** to enable browser spell checking in tinymce. Also i have used **paste plugin** in order to use paste anything as text (**paste_as_text: true**). 

Now when i paste something into tinymce it does not recognize errors instantaneously. If i click inside tinymce several times then it starts working.

When i removed the **paste plugin** everything started to work instantaneously.

Please note we encountered this issue in chrome. But there were no issues in IE though. I haven't checked other browsers.

**Comment by ShortBusKing** [comment]
Using TinyMCE 4.6.5, it seems the enterprise paste plugin `powerpaste` cause this issue as well. This appears to be a chrome only issue (this works correctly on Firefox 55 , Edge 38, IE11 as well). Running Chrome Version 60.0.3112.90 (Official Build) (64-bit).

**Comment by ShortBusKing** [comment]
After working with this issue, I determined that there was some chrome plugin which was interfering with the browser spell check feature. A quick way to test this is to see if the website in question works correctly in Incognito mode.

**Comment by glyder** [comment]
No this is still a problem.  If users have already typed text into a textbox the setting does nothing.

It needs to work retrospectively. If I hit space after word it works but i'm left cut n pasting whole pieces of text.

You need perhaps an additional flag of "browser_spellcheck_all" = true (ie. retrospective text typed before)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
