### ISSUE TITLE
Anonymous function error

### ISSUE THREAD

**Issue by mrbacay** [tinymce/tinymce#2964]
I'm trying to bundle the uncompressed TinyMCE Javascript with the rest of the Javascript of a project I'm working on using Gulp, and then minify it. 

The bundled file gives me an error that says Unidentified TypeError: (intermediate value)…Anonymous function right on the line where expose(["tinymce/geom/Rect",…]) is.

**Comment by spocke** [comment]
This ticket seems to be more of a general support question rather than a bug/feature request. Please use the community forums or register for an Enterprise license for commercial support.

But I think you should just be able to use the npm/bower package then manually concat all the files you need into one. This is how we produce the CDN version where all files are bundled.

Thanks.
