### ISSUE TITLE
TinyMce add a new language in codesample list

### ISSUE THREAD

**Issue by alvarotrigo** [tinymce/tinymce#2966]
I'm using TinyMce and I would like to add a new language in the default list provided by codesample.

Checking [the docs of codesample](https://www.tinymce.com/docs/plugins/codesample/) I didn't find anything regarding it, they are quite basic and limited. 

Is there any option to do so besides [having to modify tinymce](http://community.tinymce.com/forum/viewtopic.php?id=36347)?

**Comment by spocke** [comment]
We only support the top 10 most popular languages. We don't have a way to extend them at the moment since it's a some what tweaked prism we are using. Might need to figure out a way to customize this though.

**Comment by alvarotrigo** [comment]
It seems to me codesample is doing some extra work depending on the language. 
But in my case (and I guess many others) we only need to be able to change the class name in the `<code>` element for prism to detect it:

JSON
```html
<code class=" language-json">
</code>
```

XML
```html
<code class=" language-xml">
</code>
```

**Comment by alvarotrigo** [comment]
We just need to be able to add new objects [in `languages`](https://github.com/tinymce/tinymce/blob/master/js/tinymce/plugins/codesample/classes/Dialog.js#L24).

```javascript
	var languages = [
		{text: 'HTML/XML', value: 'markup'},
		{text: 'JavaScript', value: 'javascript'},
		{text: 'CSS', value: 'css'},
		{text: 'PHP', value: 'php'},
		{text: 'Ruby', value: 'ruby'},
		{text: 'Python', value: 'python'},
		{text: 'Java', value: 'java'},
		{text: 'C', value: 'c'},
		{text: 'C#', value: 'csharp'},
		{text: 'C++', value: 'cpp'}
	];
```

**Comment by alvarotrigo** [comment]
> We don't have a way to extend them at the moment since it's a some what tweaked prism we are using.

I'm loading the latest official prism in my side.
I don't know why tinyMce uses another version of it, but it seems irrelevant to me when displaying the content, isn't it?

**Comment by spocke** [comment]
We disabled the auto loader in it so it doesn't wait for DOMContentLoaded to get fired since that would never happen since it's lazy loaded.

**Comment by alvarotrigo** [comment]
@spocke that's alright, but I don't see why that change has anything to do with the `Dialog.js` file and the possibility of modifying the `languages` array.

**Comment by spocke** [comment]
The prism.js we have does only have the languages listed so adding anything to the languages array won't make it functional unless it maps to any of the existing formats.

**Comment by alvarotrigo** [comment]
That's exactly what I'm trying to understand / point out.
Prism only requires you to use the string `language-XXX` to be able to highlight the content. 
[Demo here](https://jsfiddle.net/z5maw74r/)

I've no idea what codesample does internally, but in order to display and highlight the content **once it has been edited**, we only need a class name.

So what I'm suggesting is enabling developers to add a new element in the languages list **with the only purpose of adding the proper class name in the `<code` block.**
```html
<code class="language-json">
</code>
```

**Comment by mahnunchik** [comment]
Hi,

I am using `highlightjs` in the frontend because it has automatic language detection feature.

It would be really helpful to have also `Other language` option in the select list.

I think that in this case produced html should be without any `language-` class:
```html
<code>
  <pre>
  </pre>
</code>
```

**Comment by mahnunchik** [comment]
Hi @spocke 
Any news?

**Comment by donShakespeare** [comment]
@alvarotrigo and @mahnunchik I understand your pains.

Bear this in mind, that TinyMCE devs have been so kind as to put their ingenious work on github. This means, poor folk like me get to be motivated to find solutions to other needs of the community. Let's face it, @spocke is a busy genius. So I consider plugin creation as:
>**doing my own part**

Hundreds of my users have never even used codesample, thanks to my alternative: https://github.com/donShakespeare/twPreCodeManager
This is a true manager for:
1.  `<pre></pre>`
2.  `<pre><code></code></pre>`
3. `<code></code>`

## Features

1. No prism.js highlighter whatsoever in the editor (absolutely unnecessary)
2. All (not 10) prism.js preselect in drop down (why prism preselects? for lazy people..., change it!)
3. Ability to add custom class name (or no class at all) in either `pre` or `code` or both their input fields. ( I use google prettify and I do not often care for prism's classname structure)
4. Single file. One JS file, done!

## Codesample makes some dangerous assumptions: 
I think codesample plugin is new; with time it might or might not be fleshed out. As it is right now it is quite unusable in many legit use-case scenarios.

1. that you want to see untouchable [contenteditable=false] fancy highlighted text in your editor. 
2. because it uses prism.js in the editor, you too, mister user, are going to use prism.js in your finished published document - whether or not your prism.js has been packed differently

## Why codesample has only about 10 preset languages
On prism.js website, you get to custom-pack what you need.
Codesample custom-packed what it deems the 10 most popular language files.
So, why have more than 10 preset languages in the drop down menu when there are only 10 physical files that it packed? Get it???

Question, but I am not using prism.js in the "frontend" or I am using a prism language that you do not have in your drop-down, what do to do since the _only way_ I can _access_ my `<pre class="etc">` and `<code class="etc">` is via the codesample.

Heck! I am using Google prettify ... with auto detect of language. But how do I access the classname of my Pre tag using codesample?

Oh wait, I don't want to only manage my Pre elements, I also want to give my inline `<code>` a treat.

Okay `</rant>`. Case closed! Now scroll back up and download the solution :+1:

**Comment by spocke** [comment]
There are multiple reasons why we choose prism and why we embed color coded source code inside the editor:
1. PrismJS is lightweight.
2. PrismJS was relatively easy to embed.
3. It was under MIT license.

The drawbacks is that it doesn't automatically detect language so we need to list languages we don't want to include all the languages it supports since it's around 200k so the plugin would become bloated for languages not commonly used. Also having a list long long list of languages to pick from would be problematic from a user perspective.

The power of open source is that you can make your own plugins. So if you want support for google prettify then go for and create your own plugin.

We might expand the "common" languages of the default plugin if needed. XML and JSON might be something that should be provided out of the box. Having a "Other language" that just does a pre tag might also be an option or a way to tweak the list with custom languages that doesn't get highlighted within the editor.

**Comment by donShakespeare** [comment]
>The power of open source is that you can make your own plugins. So if you want support for google prettify then go for and create your own plugin.

@spocke absolutely! I understand this.  And I am grateful for your codes in github. Awesome!

**Comment by Afraithe** [comment]
Option to specify language was added in last version.

A hint here is, if you want say JSON, add JSON with the javascript syntax check and it should work well.

https://www.tinymce.com/docs/plugins/codesample/
