### ISSUE TITLE
Image becomes un-editable in this scenario

### ISSUE THREAD

**Issue by freeads777** [tinymce/tinymce#2973]
Tested on your site, does the same thing.
- Insert an image using the insert/edit image button.
- Click on the image and then link it to whatever link you want using the insert/edit link button.

Now you have a clickable image that is editable (you can drag one corner, for instance, to change its size).
- Click on the image again and then click again on the insert/edit link button and finally click OK. The image will be un-editable. You can make it editable again if you first click outside the image and then on the image.

Seems like no big deal, however, if someone links an image to a wrong link then wants to change it he/she will be somewhat confused since the image is not going to be editable anymore after the edit. Especially if it's a large image and they can't click outside of it.

**Comment by freeads777** [comment]
@spocke Do you think this issue will be addressed anytime soon? I am  using the editor as part of an ad posting website and my users do change / update their links within their clickable images. It takes them by surprise when they can't edit their links after an edit since the images becomes un-editable as I have described above.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
