### ISSUE TITLE
content_css body background color is applied to submenu items

### ISSUE THREAD

**Issue by drlippman** [tinymce/tinymce#2974]
If the content_css styles set a background-color for the body element, then tinymce is applying that style to the text spans inside second-level menu items, in particular the Formats menu.  A screenshot demonstrating the issue is shown below, and it can be seen live [here](http://codepen.io/anon/pen/rLVEVv)

![image](https://cloud.githubusercontent.com/assets/190505/15811697/5e7b2c54-2b60-11e6-8e4a-f20c8e6cc7d4.png)

**Comment by tinydylan** [comment]
Hi,

This is actually expected behaviour. The heading styles in the format menu are displaying a red background because they would be rendered with a red background in the editor.

You can adjust this behaviour using the [preview_styles](https://www.tiny.cloud/docs/configure/editor-appearance/#preview_styles) setting.

Thanks!
