### ISSUE TITLE
tinymce problem with draggable Item in Firefox/Safari

### ISSUE THREAD

**Issue by proggen** [tinymce/tinymce#2980]
Tinymce does not work correctly in Firefox/Safari if outer div is draggable.

Example: http://codepen.io/proggen/pen/WxQEez inhereted from inline Example on https://www.tinymce.com/docs/demo/inline/

**Comment by spocke** [comment]
It's like some events doesn't get passed though. Not sure this can be fixed or not since the browser is doing something weird when having this attribute set.

**Comment by watway** [comment]
@revaxarts has offered a solution that deals with Safari in #3232 by adding `-webkit-user-select:text` to the draggable div.  Adding this style to Firefox/Edge/IE with their appropriate vendor prefixes doesn't help though, the cursor does appear but always at the start of the text, not where mouse clicked.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
