### ISSUE TITLE
Container element for float panels

### ISSUE THREAD

**Issue by manishbafna** [tinymce/tinymce#2985]
For float panels (table and image toolbars), it will be good if we have a container element. That way, if we want to make the position fixed, it can be done too. Right now, the toolbar floats on the top of the table and sometimes it is difficult to make edits to table.

**Comment by spocke** [comment]
I think we recently fixed this. So that if it doesn't fit inside the editor it's placed under it so it doesn't block the table if the table is really big.

**Comment by manishbafna** [comment]
If we have configuration similar to fixed_toolbar_container, it will be easy to place. 
We would ideally like to place it inside the inline toolbar container, so that user sees all the options at a single place.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
