### ISSUE TITLE
Extra large tables cause performance drops

### ISSUE THREAD

**Issue by church29** [tinymce/tinymce#2987]
To Reproduce:
1. Create a large table with content, (at least 5 x 700)
2. Attempt to edit that table 

Cause: 
ResizeBars.js triggers  refreshBars() on mouseover
This leads to a lot of position calculation, but the big drop was editor.dom.add for each row bar (700 adds)

Proposed Solution:
Only draw row bars that are in view

**Comment by CitySim** [comment]
the same thing also happens with smaller tables on bigger/more complex pages. Only rendering the handles in view probably won't fix it for this case.
a workaround is to disable table drag & drop using `object_resizing: "img"`

**Comment by jayarjo** [comment]
Added a codepen with table generator here: http://codepen.io/jayarjo/pen/VmYVRY?editors=1011

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
