### ISSUE TITLE
Adding image then attaching link in webkit causes error

### ISSUE THREAD

**Issue by jlove73071** [tinymce/tinymce#2995]
To replicate, use image plugin.
Add image then simply click the  image and click link button to add a link, you'll be able to add the link successfully except the OK button generates an error and won't close the window. You have to hit "OK" then "Cancel" for it to work properly.

Note: This only happens 1 time per page load, the second time you try, it works fine.

**Comment by spocke** [comment]
Can you setup a test case at http://fiddle.tinymce.com that reproduces the issue so that we can look at it. I wasn't able to reproduce it this is what I did:

Steps A:
1. Opened Safari since I assume that it's Safari when you say webkit
2. Clicked the insert image button.
3. Entered an image url.
4. Clicked ok in the image dialog.
5. Clicked link
6. Entered a link url.
7. Clicked ok
8. Verified that a link got created and no error messages in console.

Steps B:
1. Opened Safari
2. Clicked the insert image button.
3. Entered an image url.
4. Clicked ok in the image dialog.
5. Clicked on the image.
6. Clicked link
7. Entered a link url.
8. Clicked ok
9. Verified that a link got created and no error messages in console.

Both tests where on an empty editor and a reload between them. Would be helpful with steps to reproduce this thanks.

Thanks

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by Ertan9** [comment]
I have the same issue on Firefox 57.0. But clicking OK and Cancel respectively won't solve the problem, I just cannot add a link to images using TinyMCE 4.3.3 and 4.7.2, nothing happens after clicking OK.  It's OK with chrome, only Firefox has this problem.
