### ISSUE TITLE
hyperlink to template(html) element

### ISSUE THREAD

**Issue by flamner** [tinymce/tinymce#2996]
Hi, I use templates to special formated call to action boxes(something like blockquote). I can't set one hyperlink for this element, but only for text inside it. It will be a very useful feature to take this html content in templates for an single element e.g picture.

**Comment by androb** [comment]
@flamner I am not sure I understand your issue here?

Were you trying to wrap some content in a hyperlink? I am sure you can probably do this with the existing Template plugin features. Perhaps I am misunderstanding you.

Given this issue is 2 years old I am going to close this issue, but feel free to reopen if you have more information.
