### ISSUE TITLE
editor.fire('ScrollWindow', e); Uncaught TypeError: Cannot read property 'fire' of undefined

### ISSUE THREAD

**Issue by claudemangen** [tinymce/tinymce#3011]
Version 4.3.7. is working for me, but in newer version I get this error.

<img width="984" alt="screen shot 2016-06-20 at 16 41 23" src="https://cloud.githubusercontent.com/assets/10960903/16198362/f75163a2-3705-11e6-8e98-9ecbe7496f82.png">

I have Tinymce integrated in a Foundation 5 Template.

**Comment by spocke** [comment]
Can you setup a test case at http://fiddle.tinymce.com that reproduces the issue so that we can look at it. I need to be able to reproduce this out side the integration to verify that it's a tinymce bug. Thanks

**Comment by cjke** [comment]
Don't want to be "that guy" but getting the same thing, only in the last few days. I will try to put up something over the weekend (pressing deadline means I will need to live with the error for now).

**Comment by spocke** [comment]
I guess we could wrap it in a if statement checking so that the editor is a proper editor. But would have been nice to know why it's not an editor. If you could provide me with a fiddle reproducing it or a dump of what the editor is in that case and also what the whole EditorManager.editors is. Thanks for helping out.

**Comment by cjke** [comment]
This is uber knock together example: http://jsbin.com/licove/1/edit?js,output

Have the edit, output, and your browser console open (the jsbin one doesn't output the errors). 

1. Click "Run with JS"
2. Click the micro button
3. TinyMCE correctly appears with the correct text
4. Resize the browser inspector / the JSBin divider 
5. .fire error 

Sorry about the brevity, but best i can do. Thanks for taking the time to reply

**Comment by spocke** [comment]
Ahh, yeah this has to do with the fact that the editors structure is both an array and an object at the same time this is a bug that we are a bit afraid to fix due to it could potentially break integrations if users have things like tinymce.editors[0] or tinymce.editors["abc"] this can be avoided by providing a string ID such as "e123" instead of "123" and we will probably add a guard for that instead forcing users to provide proper valid HTML id:s since they need to start with a non numeric character by spec.

**Comment by spocke** [comment]
Anyway thanks a lot for the jsbin code very helpful.

**Comment by cjke** [comment]
Man easy - thanks for taking the time to reply. Easy fix for me this end so cheers for that

**Comment by claudemangen** [comment]
Thank very much, this solves the problem for me.

**Comment by claudemangen** [comment]
Should I close the bug now?

**Comment by blackcathikari** [comment]
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by esr360** [comment]
I still receive this issue using version 4.5.2

**Comment by blackcathikari** [comment]
@esr360 Does Spocke's answer above help you at all with fixing it? If not, could you reproduce your situation in a fiddle and show me what you get if you run tinyMCE.EditorManager.editors in the console please? I need more information to try to reproduce this.

**Comment by esr360** [comment]
Hi @blackcathikari , could you elaborate on what the fix in Spocke's answer is? My setup is quite complicated, but when I log 

    console.log(tinyMCE.EditorManager.editors);

I just get an empty array []

**Comment by blackcathikari** [comment]
@esr360 I was referring to ensuring the editor's id contains only valid characters. If this is still a problem for you, could you please open a new issue explaining your situation in detail - the above information plus further details such as what environment you're using TinyMCE in (OS, desktop and/or mobile, embedded in something else), how you've configured TinyMCE and any messages you're seeing in the console. If you're able to replicate your issue at fiddle.tinymce.com and link us to it that would be brilliant. Unfortunately I can't do much without more information, and it'll be easier to keep track of this if it's a new issue rather than continuing here.

**Comment by saransh944** [comment]
@blackcathikari, just FYI, seeing this bug in version 4.5.3. The fix provided by Spocke did resolve the issue, but I'm not sure why it has a limitation that the id must start with a non-numeral.
