### ISSUE TITLE
"X" button on "Table Properties" modal not tabbable 

### ISSUE THREAD

**Issue by rfogar2** [tinymce/tinymce#3014]
The close button on the Table Properties modal is not tabbable

Steps to Reproduce:
1. Navigate to an instance of the RCE
2. Move keyboard focus to the main input of the RCE and press alt+f9 to move focus to the menu bar
3. Use the arrow keys to move focus to the Table menu and press Enter
4. Press Enter to bring up the 'Table properties' modal
5. Press Tab several times attempting to move focus to the X in the top right
6. Note that focus does not move that far back

**Comment by spocke** [comment]
You can close it using the Esc key. Not sure we need to make it tab focusable.

**Comment by cannona** [comment]
I asked on the WebAIM list about this, and folks seemed to feel that your reasoning was sound, but it would be a little better if it could be tabbed to.

Personally, it still feels suboptimal to me.  When KB-only users see a close button, they generally, I would think, expect to be able to tab to it.  So, perhaps consider this a feature request, rather than a bug. :)

Either way, thanks for the quick response.

**Comment by simonista** [comment]
Recognizing that there is a work around so this may not be a high priority for the TinyMCE core team, I'm curious if we submitted a pull request with support for making the close button tab focusable, would it be accepted?

**Comment by MarcoZehe** [comment]
I believe this issue can be closed. I just played with this today, and there are now "Cancel" and "Save" buttons in the Table, Row and Cell properties dialogs.
