### ISSUE TITLE
Problem with copy & paste Word lists with numbers into editor

### ISSUE THREAD

**Issue by kboerner** [tinymce/tinymce#3017]
We detected the following behavior. When you copy & paste sorted or unsorted lists from Word into the editor, the tinymce removes number(s) before points. 

That happens when the number is placed at the beginning of the list. With double byte characters the problem exist at any position in the list. e.g.23.9 km/L  changed to 9 km/L 

You can see the behavior if you insert the attached example list (word) in the demo editor on https://www.tinymce.com. 
[editor_list_word.docx](https://github.com/tinymce/tinymce/files/327829/editor_list_word.docx)

Finger cross you have an idea for a solution.
Thanks, Kirk

**Comment by kknopp** [comment]
I think it's more than just numbers before points. We encountered the same issue, however we found that when pasting any sorted or unsorted list from word (version 15.23.2), with double spaces after a ., you lose whatever comes next. Attached is a word document that you can use to reproduce this issue on the tinymce website.

[whitespace_issue-1.docx](https://github.com/tinymce/tinymce/files/357984/whitespace_issue-1.docx)

**Comment by smares** [comment]
This bug is open for so long and still present in the latest version 5. We're using TinyMCE on a page for publishing press releases and this bug affects a lot of users.

**Comment by kknopp** [comment]
> This bug is open for so long and still present in the latest version 5. We're using TinyMCE on a page for publishing press releases and this bug affects a lot of users.

They have a premium add-on available called "PowerPaste." This plugin works to better retain formatting when copying/pasting from external sources, and we no longer encounter this issue now that we've paid for the module.

**Comment by TheSpyder** [comment]
Lists are the single hardest thing to get right when importing content from Microsoft Office. Due to the level of investment that has been put into them we have thus far only fixed this issue in our premium PowerPaste plugin (actually I'm not sure if it was a problem using that plugin even back in 2016).

If you paste into the https://www.tiny.cloud/ demo where the premium plugin is now enabled both documents work.

I'm not saying we will leave the paste plugin to stagnate forever, this is a bad default experience, but there are solutions available.
