### ISSUE TITLE
Can't remove "figure" tag in the beginning

### ISSUE THREAD

**Issue by Riorita** [tinymce/tinymce#3024]
It reproduces even on the example page (https://www.tinymce.com/). 
1) So open "Tools" -> "Source code"
2) Remove all and paste:

```
<figure><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfftTt7ZxF4tTVS6iZOhk39AtHNg-Sjsirqi77JWzPtFiGlDH6bg" /></figure>
<p>Some paragraph</p>
```

3) Select image in editor and remove it by backspace
4) You still have empty "figure" and it is not removable by backspace

PS If there is smth before "figure" like:

```
<p>Some paragraph</p>
<figure><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfftTt7ZxF4tTVS6iZOhk39AtHNg-Sjsirqi77JWzPtFiGlDH6bg" /></figure>
<p>Some paragraph</p>
```

Everything works well and you can remove it by backspace

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
