### ISSUE TITLE
No way to exit block to the right when at end of buffer

### ISSUE THREAD

**Issue by scribe777** [tinymce/tinymce#3027]
There seems to be no way to exit (to the right) a block when at the end of the editing buffer.
For example, if one chooses to have code to add a simple HTML block, `<b>LB</b>`, at the press of the enter key.
I can't seem to exit the `<b>LB</b>` block (to the right) and keep typing.  Here's code to show the problem:

```
tinymce.init({
     selector : '#editor',
     setup : function(ed) {
          ed.on('keydown', function(e) {
               if (e.keyCode == 13) {
                    ed.selection.setContent('<br/><b>LB</b>');
                    return false;
               }
          });
     }
});

```

Here's a jsfiddle to show the scenario:

http://jsfiddle.net/1v2tL8pu/3/

In the jsfiddle, try to type something in the tinymce editor, then press [Enter], then continue to type and notice that you are still in the `<b>LB</b>` block.  Arrow right or click to the right and notice that you cannot escape (to the right) the `<b>LB</b>` block.

Chrome and Safari seem to show the problem.  Firefox doesn't show the problem.

**Comment by scribe777** [comment]
This might seem like a keyboard issue, as you have labeled it, but please note that one cannot mouse click out of the block to the right, either.

We've tried adding an extra space to the end of the buffer ('<br/><b>LB</b> '); so we can position the cursor outside the block. Nothing works.  There seems to be no workaround for this.  It is unfortunate because our users cannot continue to type in the editor after they hit return.

Thanks for any help on this issue.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
