### ISSUE TITLE
Cell type cannot be set to Cell.

### ISSUE THREAD

**Issue by ereed** [tinymce/tinymce#3031]
1. With the table selected in the editor, select _Table > Cell > Cell properties_.
2. Try to set **Cell type** to **Cell**.
3. --> You cannot select **Cell** without first selecting **Header cell** and then trying to select it again.
4. With **Cell** selected, click _Ok_.
5. Reopen **Cell properties**.
6. --> **Cell type** is set to **None**.

**Comment by tinydylan** [comment]
Hi,

Thanks for the bug report. I'm unable to reproduce the issue in the latest version of TinyMCE - the Cell Properties dialog appears to be behaving correctly and not exhibiting the bug you describe. 

A lot of these dialogs were overhauled in TinyMCE 5, so it's likely that the issue was addressed then. Please let us know if you encounter any other issues, or if this issue persists.

Many thanks!
