### ISSUE TITLE
Insert link into incorrect place after using browser find 

### ISSUE THREAD

**Issue by ghost** [tinymce/tinymce#3036]
1.  highlight some text
2.  click link (to create a link)
3.  while on the Link popup windows do ctrl-F to bring up the browser default find function
4.  search something in the document other than the highlighted text which will move the selected text range
5. Fill in link information and finish creating the link by clicking ok
6. You will notice the link will be created on the top of the document not on the highlighted text.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
