### ISSUE TITLE
Multilevel bullets list from word

### ISSUE THREAD

**Issue by SlavaPoddubny** [tinymce/tinymce#3061]
Description of problem:
Rich text editor doesn't interpret all types of bullets correctly
When I copy multilevel bullets list created in word to tinymce (4.3.13), list is rendered incorrectly

Steps to reproduce:
1. create multilevel bullets list in word
2. copy list to clipboard
3. paste list to tinymce as html

Expected result:
list is rendered incorrectly

Actual result:
see attachment
![44](https://cloud.githubusercontent.com/assets/18720123/16763912/f0d096bc-4833-11e6-8f36-36ff04692bdc.jpg)

**Comment by blackcathikari** [comment]
We've looked into this and believe it is related to a few other bug reports regarding pasting lists from Word. The related reports are #2853, #3061, #1314, #1422, #1489, #1696 and #1708, and cover indentation, list styling and list item order not being preserved. Could you please take a look and let us know if you disagree? Thanks, the TinyMCE Team.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
