### ISSUE TITLE
Drag'n'drop numbered list

### ISSUE THREAD

**Issue by cmoneverybody** [tinymce/tinymce#3081]
Hello.
We ran into unexpected behavior when you use a numbered list.
We create a list, select its elements, drag them to a new location.
Numbered list then becomes a bullet list.
screenshotes:
![1](https://cloud.githubusercontent.com/assets/7736571/17099522/91ea6e46-5271-11e6-9cfe-f0299a07bf43.png)
![2](https://cloud.githubusercontent.com/assets/7736571/17099521/91ea0078-5271-11e6-8b38-305337337f3b.png)
![3](https://cloud.githubusercontent.com/assets/7736571/17099541/a4cf9798-5271-11e6-9f32-9f0ac0a7405f.png)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
