### ISSUE TITLE
Customizations

### ISSUE THREAD

**Issue by pcfmello** [tinymce/tinymce#3086]
Good morning!
Can I customize as: The textarea in a div and the panel buttons in other div? If yes, how I do?  Because I have a toolbox customized by us and I want to insert the functions in it. Awayting!

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
