### ISSUE TITLE
Check setting for rtl

### ISSUE THREAD

**Issue by infinitydesign** [tinymce/tinymce#3088]
Hi
In **FormatControls.js** file line 28, plugin must check **e.editor.settings.rtl** to check editor was RTL or not, but code check **e.editor.rtl**.

Best regards.

**Comment by lnewson** [comment]
I'm going to close this due to it's age, however if it's still causing an issue then please let us know.

From what I can tell though it was referring to this line: https://github.com/tinymce/tinymce/blob/4.2.x/js/tinymce/classes/ui/FormatControls.js#L28 in which case that looks correct given my admitted limited knowledge of earlier versions of TinyMCE. Reason being that is for the UI not the content and is initialised here using the settings/editor manager UI properties: https://github.com/tinymce/tinymce/blob/4.2.x/js/tinymce/classes/Editor.js#L485
