### ISSUE TITLE
Getting Extra Line Breaks In IE

### ISSUE THREAD

**Issue by md-saifur-rahman** [tinymce/tinymce#3089]
I was trying to extract content using getContent({format:'text'}). It works fine in Chrome, but in IE (tested v10 & v11), I got some extra line breaks between lines. I found that this tag ,  `<meta http-equiv="X-UA-Compatible" content="IE=edge">` , was creating that problem. Removing this tag from the page solves it. The following fiddle shows the problem-  
[http://fiddle.tinymce.com/j4faab](http://fiddle.tinymce.com/j4faab)

You can see the extra line breaks in the browser  console by clicking on editor after adding lines. I need to keep that tag. How do I get around it?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
