### ISSUE TITLE
upgrading to 4.4.1 causing error "Cannot read property 'settings' of undefined"

### ISSUE THREAD

**Issue by chagamkamalakar** [tinymce/tinymce#3091]
Tinymce is created dynamically , and the code to create is as follows

```
var ed = new tinymce.Editor(this.id, { settings }, tinymce.EditorManager);
        var self=this;
        this.ed.on('keyup',()=> {
          self.model = self.ed.getContent();
        });

        this.ed.render();

```

is it bug? any help please

**Comment by cisarpavel** [comment]
Similar for me. Upgraded from 4.3.10 to current version because of issue https://github.com/tinymce/tinymce/issues/2870 and tinymce fails on Cannot read property 'settings' of undefined

**Comment by chagamkamalakar** [comment]
i upgraded from 4.4.0 to 4.4.1 that caused this problem

**Comment by spocke** [comment]
We need a way to reproduce this. Can you setup a fiddle at fiddle.tinymce.com or provide with a link or stack trace of where the error is thrown. Thanks

**Comment by cisarpavel** [comment]
Here is fiddle https://jsfiddle.net/cisarpavel/uaoqewf2/2/

And copypasted console output
[staging-1469867955849.txt](https://github.com/tinymce/tinymce/files/391776/staging-1469867955849.txt)

**Comment by ersandeepranjit** [comment]
same here from 4.3.1 to 4.4.1

**Comment by spocke** [comment]
Hmm, can't seem to reproduce it at this fiddle: https://jsfiddle.net/cisarpavel/uaoqewf2/2/

When is it supposed to fail it loaded without errors on both chrome and firefox?

**Comment by cisarpavel** [comment]
It's permanent problem. Both firefox and chrome. But in firefox error message is
```
TypeError: n is undefined
.postRender()
 tinymce.min.1469555800.js:12
s/<()
 tinymce.min.1469555800.js:8
i.exec/<()
 tinymce.min.1469555800.js:8
n()
 tinymce.min.1469555800.js:3
i.each()
 tinymce.min.1469555800.js:8
i.exec()
```

Not think it's related to plugins.
See screenshot from anonymous Chrome session 52.0.2743.82 (64-bit) attached. From latest Linux Mint. Error also reproduced in latest Chrome on Windows 8.1 for Virtualbox  downloaded from modern.ie. 

![tiny_problem](https://cloud.githubusercontent.com/assets/4312197/17322070/ffcbe98c-589b-11e6-88da-003ea6c5461d.png)

**Comment by spocke** [comment]
That is very strange I have tested that fiddle on chrome, firefox on both linux and windows it always loads without errors. I also tested it with/without the cache enabled and with throttled speed on chrome in case it was some form of slow loading problem.

It might be some security proxy or filter? Does the examples on tinymce.com work? Can you try using the tinymce.js rather than tinymce.min.js so we get a better stack trace.

**Comment by cisarpavel** [comment]
I just noticed, that with tinymce.min.js from cdn.tinymce.com/4/tinymce.min.js it's working. Minimized file on your CDN is almost double size, than in downloaded tinymce_4.4.1.zip. These files should differ?

**Comment by spocke** [comment]
Yes, the cdn version has most plugins bundled into the same js file to reduce the number of requests for the client.

**Comment by cisarpavel** [comment]
Ok, seems my problem is connected to my cdn. Tried same file with different url (and also without CDN) and tinymce works fine. JSFiddle seems to have still some problems but who knows. Thanks for your help.

**Comment by krisleech** [comment]
I've been getting the same error, `Cannot read property 'settings' of undefined`, from a few users today, most are not effected.

I haven't been able to reproduce on any browser combo, but the effected users are on Windows 7 with latest Chrome. They do not have any extension apart from the default Google Docs ones.

I've downgraded to TinyMCE 4.4.0 to see if this solves the problem.

**Comment by spocke** [comment]
Is the script loaded from a cdn if so what is the url to that script? Another user said it might be cdn related.

**Comment by krisleech** [comment]
We downgraded to 4.4.0 - self hosted, no CDN, and the problem has gone away. Sorry I can't be more helpful.

**Comment by miseeger** [comment]
Hi, I just had the same problem when upgrading from 4.3.3 to 4.4.1 :neutral_face: is there any progress in solving this issue?

**Comment by mikedebock** [comment]
I also expected the same issue when upgrading to 4.4.1 (from 4.4.0). With self hosted, no CDN.

**Comment by dev-101** [comment]
Same issue. I have replaced with dev version and here's a log which might help a bit:

>Uncaught TypeError: Cannot read property 'settings' of undefined
>Path.extend.postRender @ tinymce.js:42796
>(anonymous function) @ tinymce.js:24733
>(anonymous function) @ tinymce.js:26168
>each @ tinymce.js:3605
>proto.each @ tinymce.js:26071
>proto.exec @ tinymce.js:26166
>Control.extend.postRender @ tinymce.js:29044
>(anonymous function) @ tinymce.js:24733
>(anonymous function) @ tinymce.js:26168
>each @ tinymce.js:3605
>proto.each @ tinymce.js:26071
>proto.exec @ tinymce.js:26166
>Control.extend.postRender @ tinymce.js:29044
>(anonymous function) @ tinymce.js:24733
>proto.renderBefore @ tinymce.js:27653
>k @ theme.min.js:1
>l.renderUI @ theme.min.js:1
>Editor.init @ tinymce.js:37381
>(anonymous function) @ tinymce.js:37286
>(anonymous function) @ tinymce.js:9589
>each @ tinymce.js:3605
>loadScripts @ tinymce.js:9588
>(anonymous function) @ tinymce.js:9581
>done @ tinymce.js:9418

**Comment by spocke** [comment]
This error suggest to me that the tinymce.min.js and themes/modern/theme.min.js isn't both updated to version 4.4.1. Make sure both files are properly updated.

**Comment by dev-101** [comment]
Thanks spocke!
Not sure how I missed to merge /themes dir, but this solved the issue :+1:

**Comment by slamere** [comment]
I also had this problem and v4.4.2 didn't fix the it either -- it was definitely a CDN issue.  Using [tinymce-rails](https://github.com/spohlenz/tinymce-rails), the theme files weren't being updated.  Using the <tt>:compile</tt> method, all assets are fingerprinted but a symlink masks the fingerprinted version and the CDN keeps the old theme files.

**Comment by murrah** [comment]
Same problem in 4.4.2 and 4.4.3 Community Version.
FF works fine. Chrome Version 53.0.2785.101 m (64-bit) threw the error.

It turned out to be a caching issue for me! Doh! Emptied the cache and reloaded. Fixed. Was picking up the new tinymce.min.js file but not picking up the correct updated theme file. See Spocke's post above.

**Comment by rafaelmaciel** [comment]
Hi people, in 4.4.3 i has the same issue. You can help?

**Comment by Trapulo** [comment]
same problem using 4.4.0/4.4.1/4.4.2/4.4.3: the .min file will reaise a n is undefined exception. The NOT minified file works
Back to 4.3.13 it works

**Comment by spocke** [comment]
Make sure that tinymce.min.js and tinymce.js and theme.min.js and theme.js is all updated. If you run an older version of tinymce core with a newer version of theme.js this error will occur. This is not a bug in tinymce but a deployment issue where you haven't uploaded/updated all the files. If you still think this is some form of bug please reproduce it on fiddle.tinymce.com since it uses the latest tinymce core and theme.

**Comment by foodaka** [comment]
I keep getting this error im using "tinymce": "^4.5.1".  i installed from npm

**Comment by foodaka** [comment]
whenever trying to input an image or media file

**Comment by EifX** [comment]
I use bower for my plugins. I switched to tinymce.js (instead of tinymce.min.js), then it works. This problem is there since v4.4.0 (currently I use 4.5.2)

The minified-versions are broken...

**Comment by omer-sds** [comment]
i just downloaded 4.6.2 and this error vanished i was having the same problem on chrome but not any more

**Comment by jackbanditdude** [comment]
Working in Joomla, letting the Joomla application update the tinymce plugin appeared to work, but was receiving this error. Had to manually download the current version of tinymce and upload the root jquery.tinymce.min.js (it wasn't even present on my server), overwrite the tinymce.min.js, and update the themes/modern folder and add the themes/inlite folder.

**Comment by herrvigg** [comment]
I add the same issue and i solved it by clearing the web cache (through cloudflare iny my case), file by file:

- tinymce.min.js 
- jquery.tinymce.min.js
- themes/modern/theme.min.js
- themes/inlite/theme.min.js

I'm not sure all are necessary, but i give you what worked for me. I guess the crucial part is `themes/modern/theme.min.js` as the main `tincymce.min.js` was versioned by the web server and therefore should be handled properly. The problem very likely comes from the various `theme.min.js` because they are not versioned and loaded by the MCE client itself. The cache server is not able to detect a change by itself and therefore will provide the previous version which might be incompatible.

A solution could be to add the version in the call, and give a version number to the theme file but it's a bit of overhead in the file management.

Another solution could be to load a version string as a constant in the theme and the caller should check that the version is compatible with the current version also defined locally in the main script. If not compatible, raise an error so that the developer can easily understand the issue comes from the cache.

**Comment by smoothGrace** [comment]
i met this problem too,searching so much on internet, not good idead.
at last ,i'm using chome,press f12->network-disable cache  
check it.
f5
ok
uncheck it.

**Comment by henrymendis** [comment]
i met this problem too,searching so much on internet, not good idead.
at last ,i'm using chome,press f12->network-disable cache
check it.
f5
ok
uncheck it.

also using Opera browser, ran smoothly without error
