### ISSUE TITLE
Selecting Non-Editables in IE would automatically scroll the editor to the end

### ISSUE THREAD

**Issue by gaut4m** [tinymce/tinymce#3092]
I have some non editable fields in my editor, when you double click on these non editables you would see a popup where you can edit it. But in IE clicking on some of the non-editable but result in auto scrolling
I have created a fiddle to explain my issue: http://fiddle.tinymce.com/e3faab/25
In the fiddle all non-editable have a yellow background. The ones which work with out any problem have green color and the ones which would get auto scrolled to the end are in red color

**HOW TO REPRODUCE THE ISSUE**
- Try to single click the placeholder which are in green color. It would let to select the non-editable.
- Scroll down to the end of the text where you see non-editables with yellow background and red color.
- Try  to single click one of the red colored non-editable the editor would automatically scroll to the bottom

In chrome it won't auto-scroll but the scroll-able area increases to more than the length of the text

I think the problem may be because I have a zoom plugin in my editor but I could not figure out where the auto scrolling takes place

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
