### ISSUE TITLE
<br /> getting inserted when format untoggled if <textarea> is prefilled

### ISSUE THREAD

**Issue by clawicco** [tinymce/tinymce#3094]
Let me show you what I'm talking about. I've got two codepens that are identical except that the `<textarea>` is prefilled in one and not in the other.

First, to see the expected behavior, go to the following pen (`<textarea>` is not prefilled) and follow the steps I will outline below ...
https://codepen.io/clawicco/pen/AXgrZz?editors=1000
1) click "Formats" menu; click "format1"
2) type "test"
3) type a space
4) click "Formats" menu; click "format1" (untoggling format1)
5) click "Formats" menu; click "format2"
6) type "test"
At this point, you should see red and then blue text on the same line; the HTML is as follows:
`<p><span class="format1">test </span><span class="format2">test</span></p>`

Next, see the bug I am reporting, go to the following pen (`<textarea>` is prefilled with htmlspecialchars'd `<p><span class="format1">test</span></p>` (this is the HTML as it appears after step 2 above)) and use mouse to insert your cursor after "test" then follow steps 3-6 from above ...
https://codepen.io/clawicco/pen/rLAwXo?editors=1000
Once you have completed steps 3-6, you should see red and then blue text on SEPARATE lines; the HTML is as follows:
`<p><span class="format1">test <br /></span><span class="format2">test</span></p>`

Note that the `<br />` is inserted as soon as you type a space -- it only becomes obvious once you untoggle format1 (technically the title of this bug isn't accurate in this respect).

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
