### ISSUE TITLE
Dragging and dropping a video in IE11 makes it disappear

### ISSUE THREAD

**Issue by starquake** [tinymce/tinymce#3097]
Steps to reproduce:
- Open http://www.tinymce.com in IE11
- Remove contents of the example editor
- Add a youtube movie using "Insert" -> "Insert/edit video"
- Drag the video and drop it somewhere

**Comment by dsakko** [comment]
Hi starquake can you confirm the last step? Previous steps to reproduce this you mentioned dropping it outside of the editor. Just want to make sure we're looking into the right scenario for you :)

**Comment by starquake** [comment]
Just tried it. It actually doesn't matter where you drop. It always disappears.

**Comment by dsakko** [comment]
Thanks, we'll look into it.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
