### ISSUE TITLE
valid_elements isn't working properly (with pagebreak)

### ISSUE THREAD

**Issue by Rido** [tinymce/tinymce#3102]
I try to add a hr-element as a page-break but this doesn't work when I use the `valid_elements` parameter.

Example without `valid_elements` (does work): http://fiddle.tinymce.com/44faab
Example with `valid_elements` (doesn't work): http://fiddle.tinymce.com/54faab

When you type two lines of text and then try to insert a page break, you will immediately see the problem. You're not able to add the `hr` element.

**Comment by drmonkeyninja** [comment]
We've been having a similar problem. In the past we've been able to use `<!-- pagebreak -->` as the breaking markup and allow it in `valid_elements` by using `--[*]` but this no longer works in the current version of TinyMCE. We tried changing the `pagebreak_separator` to a `hr` and adding that to our valid elements but still no joy, TinyMCE strips it out every time.

**Comment by arlomedia** [comment]
I can verify this problem. It seems that no matter what value I enter for pagebreak_separator, nothing is inserted into my HTML if I have any value for valid_elements. For example, none of these combinations work:

		pagebreak_separator: "<div class=\"page_break\"></div>",
		valid_elements : "p[style],br,div[class<page_break],strong,em",

		pagebreak_separator: "<hr />",
		valid_elements : "p[style],br,hr,strong,em",

		pagebreak_separator: "x",
		valid_elements : "p[style],br,strong,em",

However, if I comment out the valid_elements, then all these examples insert the specified text.

I was using TinyMCE 4.1.0 when I noticed the problem; then I updated to the latest TinyMCE 4.6.5 and the problem is still there.

**Comment by drmonkeyninja** [comment]
@arlomedia I figured out how to get this working just yesterday. You need to include `img[class]` in the valid elements; I presume that TinyMCE needs this so that it can draw the break in the editor window even if it isn't using an `img` tag for the break itself.

Example: http://fiddle.tinymce.com/54faab/2

**Comment by arlomedia** [comment]
@drmonkeyninja Ah yes, that works, thanks! The rule can be a little more specific to exclude other image tags: `img[class<mce-pagebreak]`.

To the TinyMCE developers, I think you should automatically allow the page break image code, regardless of how valid_elements is set up.

**Comment by drmonkeyninja** [comment]
@arlomedia I like the more specific valid element.

I don't agree that the page break image code should be automatically allowed as that would go against how other features of the editor works. You can currently include toolbar buttons but not allow the markup it produces which forces you to have to maintain the `valid_elements` when in use.

**Comment by arlomedia** [comment]
@drmonkeyninja The difference here is that the page break button appears to be adding the code you specify in `pagebreak_separator`, but actually adds an image tag that you can't see when viewing the HTML source. I think TinyMCE's use of this image tag is supposed to be abstracted from the user, and it's a mistake that the user needs to be aware of it when using `valid_elements` -- if it's going to be abstracted, it should be completely abstracted. Also, that would allow TinyMCE to change the code it uses internally to display a page break without becoming incompatible with everyone's `valid_elements` setting.

I would agree, however, that the code specified in `pagebreak_separator` needs to be added to `valid_elements`. That would seem consistent with other toolbar buttons.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
