### ISSUE TITLE
Failed to auto focus on Ipad

### ISSUE THREAD

**Issue by nngottn** [tinymce/tinymce#3115]
Hi TinyMCE team,
I'm using TinyMCE editor to create the editor for my project. I used the 'auto_focus' plugin to auto focus the content when the editor is activated, it worked wells on Samsung but failed to focus on Ipad.

Please use the example to reproduce: http://fiddle.tinymce.com/kgfaab/1

I tried these following suggestions:
- http://stackoverflow.com/questions/12447472/cant-set-focus-to-tinymce-textarea-on-ipad
- http://community.tinymce.com/forum/viewtopic.php?id=8238
- http://community.tinymce.com/forum/viewtopic.php?pid=91307#p91307
- https://github.com/tinymce/tinymce/issues/1809

But could not resolve my problem.

I'm looking for the workaround to fix it.

Regards,
Ngoc

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
