### ISSUE TITLE
Block or element merging is inconsistent between browsers (reopened)

### ISSUE THREAD

**Issue by christianwach** [tinymce/tinymce#3116]
This is essentially re-opening #2406 which seems to have been closed even though the problem seems to persist. I'll re-state the issue:

Consider the following raw editor content:

``` html
<p class="a">Blah</p>
<p class="b">Blah</p>
```

Place the cursor at the beginning of the second paragraph and hit `backspace` to merge the two paragraphs.

Webkit result: `<p class="a">BlahBlah</p>`
Gecko result: `<p class="b">BlahBlah</p>`

There is clearly inconsistent behaviour between browsers here.

@blackcathikari was unable to reproduce this in TinyMCE v4.4.0, but I have just verified that this bug is still present in TinyMCE v4.4.1 which ships with WordPress 4.5.3. The bug is therefore still present for millions on WordPress users.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
