### ISSUE TITLE
XSS vulnerability issue

### ISSUE THREAD

**Issue by rmmistry** [tinymce/tinymce#3118]
SurveyMonkey uses tinymce for rich text editing. We are unsure how the xss gets triggered on textarea where ever we use tinymce.
steps to repro:
1. go to www.surveymonkey.com
2. add any question i.e multiple choice
3. insert this payload  </script><img/*%00/src="worksinchrome&colon;prompt&#x28;1&#x29;"/%00*/onerror='eval(src)'>
4. verify you get XSS is getting triggered.

Expected: this payload shouldn't get evaluated as html and trigger XSS but should always get rendered as plain text.

findings through debugging: the string gets encoded and gets rendered as text, but somehow the way this string gets handeled by tinymce - which gets evaluated as html and triggers xss. 

would like to know how to prevent this xss on fields whereever we are using tinymce.

thanks

**Comment by spocke** [comment]
Can you setup a test case at http://fiddle.tinymce.com that reproduces the issue so that we can look at it. Need to be able to reproduce it out side your environment. Thanks

**Comment by rmmistry** [comment]
hi Johan,

I have tried pasting this payload using fiddle.tinymce.com editor

 </script><img/*%00/src="worksinchrome&colon;prompt&#x28;1&#x29;"/%00*/onerror='eval(src)'>

but is not evaluating src and giving XSS.

[image: Inline image 1]

**Comment by YuriKap** [comment]
I don't know if this is the same issue or should be filed as a separate issue. I was able to reproduce a self-XSS in Firefox with the following fiddle: http://fiddle.tinymce.com/XNfaab

In order to have it work I needed both the "paste" plugin and a "paste_postprocess"

All you have to do is the following:
# create a file with the following content `"><img src=x onerror=prompt()>` 
# open that file in firefox
# drag and drop the broken image from that window into tinymce fiddle
# see the prompt pop up

**Comment by YuriKap** [comment]
@spocke is the information I added above enough to be able to identify and fix this bug? I see it is still marked as "needs more info". Should I open a separate bug instead?

**Comment by fyrkant** [comment]
@YuriKap Can you create a new issue about your problem (if you still have it with the latest version of TinyMCE), I can't seem to reproduce it so I'm closing this issue.
