### ISSUE TITLE
tfoot tag move in first

### ISSUE THREAD

**Issue by bahamut100** [tinymce/tinymce#3120]
Hi, I found an issue with tfoo tag.

Exemple : https://www.tinymce.com/docs/demo/full-featured/

Insert table (4 rows)
Select 1st row ->row properties -> row type -> header

Look source code : all is ok

Then, select last row -> row properties -> row type -> footer

Look source code : tfoot tag has moved in first.

**Comment by spocke** [comment]
That is by design. thead and tfoot is required to be before tbody in HTML4 however it seems more relaxed in HTML5. But does this cause any issues for the end user other than the source code?

**Comment by bahamut100** [comment]
Yes it's a problem, because if you remove the row as footer, your datas are not in the correct order, and the array is "wrong"

**Comment by spocke** [comment]
If the HTML4 spec enforced it then it's a valid behavior as it is. tfoot is always rendered at the end of the table by the browser. So I guess if you have logic that parses tables and require it to be at the end then that logic in correct and should take into consideration that the tfoot might be at the top of the table element since both scenarios are valid HTML5 since they relaxed the rule.

**Comment by frankl7800** [comment]
The code produced by the table editor is html5.1-incompatible.

Depending on which line was last formatted, this line appears at the beginning of the table.

Example: first the headline is formulated, then the foot area. In the HTML is written <table> <tfoot> <thead> ...

Result: Element <thead> not allowed as child of element <table> in this context.
