### ISSUE TITLE
Autosave plugin - default content

### ISSUE THREAD

**Issue by smogg** [tinymce/tinymce#3137]
How do I go about setting up a default content for my editor while having the Autosave plugin turned on? I can't seem to find API section that'd help me with that.

edit:
the solution that I'm using right now is to use `setup` and wait for autosave to update the input field (or not). If it's empty after X ms then I set the content manually:

``` javascript
...
setup: function(editor) {
  editor.on('postRender', function(e) {
     var el = e.target;
     setTimeout(function() {
         if(!el.getContent()) el.setContent("default content");
     }, 300);
 })
}
```

**Comment by spocke** [comment]
If you want it to pick up existing content just place it in the element you are converting into an editor before you call tinymce.init.

**Comment by smogg** [comment]
@spocke sure, but then autosave won't update the content with what's stored in localStorage for me (if something is there).

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
