### ISSUE TITLE
Insert text in firefox adds additional line breaks

### ISSUE THREAD

**Issue by thomich** [tinymce/tinymce#3138]
Inserting text copied from Libreoffice Writer or even M$ Word into TinyMce on Firefox will add additional line breaks if using CTRL+SHIFT+V or feature **Paste as Text**.

Insert normal: CTRL+V
will insert text as it come from Libreoffice Writer or M$ Word...
![selection_005](https://cloud.githubusercontent.com/assets/4398840/17800742/026b494c-65e6-11e6-880f-1d897cbb85d5.png)

![selection_006](https://cloud.githubusercontent.com/assets/4398840/17800770/2d0556ca-65e6-11e6-9db9-67d51f3c8594.png)

Insert as text: CTRL+SHIFT+V
will insert only text, but with additional line breaks...
![selection_007](https://cloud.githubusercontent.com/assets/4398840/17800774/3343f550-65e6-11e6-8b8d-25bfafaa59eb.png)

![selection_008](https://cloud.githubusercontent.com/assets/4398840/17800776/3c29a66a-65e6-11e6-927a-bf0699b90b8c.png)

Insert as text: **Paste as Text** feature and CTRL+V
![selection_009](https://cloud.githubusercontent.com/assets/4398840/17800787/4ce20e20-65e6-11e6-947d-fea507b69111.png)

![selection_010](https://cloud.githubusercontent.com/assets/4398840/17800788/51bc4168-65e6-11e6-8cb6-b294a167ba83.png)

Doing the same in Chrome will work as it should:
![selection_011](https://cloud.githubusercontent.com/assets/4398840/17800807/76f84602-65e6-11e6-874b-d6e2932b4149.png)

![selection_012](https://cloud.githubusercontent.com/assets/4398840/17800808/7ba756f2-65e6-11e6-86ee-d8be818b2e21.png)

thanks for checking and solving it..

regards
thomi

**Comment by thomich** [comment]
I tested this on latest TinyMCE 4.5.1 and can't reproduce, seams its' fixed.

Inserting Text from LibreOffice Writer or M$ Word with CTRL+SHIFT+V (or paste as text) works no also in Firefox as expected.

Can anybody confirm that it is solved?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
