### ISSUE TITLE
Contenteditable = false doesn't allow formatting the text

### ISSUE THREAD

**Issue by pjfsilva** [tinymce/tinymce#3141]
Steps:
1. Go to https://jsfiddle.net/bL2eyhk4/
2. Type 'lipsum' on the editor and then click on 'tag' button and add the :test tag on the same line so you get: 'lipsum :test'.
3. select the whole line and make it bold
4. You can see the text you typed 'lipsum' is bold but the :test is not bold as I expected.

Steps:
1. Go to https://jsfiddle.net/bL2eyhk4/
2. Type 'lipsum' on the editor.
3. Select the whole line and make it bold.
4. go to the end of line and then click on 'tag' button and add the :test tag on the same line so you get: 'lipsum :test'.
4. You can see both normal text and :test gets bold.

My custom button adds '&nbsp;<span class="" contenteditable="false">:test</span>&nbsp;' to the editor. I understand and I want this content to not be editable by the user but I want to be able to style it as if normal text is there.

If you do the steps on the 2nd order I specified it actually becomes bold. If we use the 1st order it doesn't get bold so it seems inconsistent and a bug. If you ask me, I think formatting should apply to cE = false or we can make this as a setting that can be changeable.

Please inform if I can help in fixing this.

**Comment by spocke** [comment]
This is currently by design. But maybe there should be a way to tell the formatter if the contentEditable item is allowed to be wrapped or not. It probably should be wrapped since you can copy paste then inside bolds or drag drop them there.

**Comment by JorgeMadson** [comment]
This fixed my issue, i edited the tinymce.js at line
`if (contentEditable && !hasContentEditableState && FormatUtils.isValid(ed, wrapName, nodeName) && FormatUtils.isValid(ed, parentName, wrapName) && !(!nodeSpecific && node.nodeType === 3 && node.nodeValue.length === 1 && node.nodeValue.charCodeAt(0) === 65279) && !isCaretNode(node) && (!format.inline || !dom.isBlock(node))) {`
to
`if (/*contentEditable && !hasContentEditableState &&*/ FormatUtils.isValid(ed, wrapName, nodeName) && FormatUtils.isValid(ed, parentName, wrapName) && !(!nodeSpecific && node.nodeType === 3 && node.nodeValue.length === 1 && node.nodeValue.charCodeAt(0) === 65279) && !isCaretNode(node) && (!format.inline || !dom.isBlock(node))) {`

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
