### ISSUE TITLE
Tinymce 4 code editor rearrange my html code

### ISSUE THREAD

**Issue by robcaa** [tinymce/tinymce#3142]
I copy paste these html into the tinymce 4 source editor:

```
<a href="/hu/szinhaz/Partnerek/Atrium_Filmszinhaz">
    <div class="partner">
        <img src="/uploads/_partnerek_/Atrium_Filmszinhaz/logo.jpg">
    </div>
    Átrium Filmszínház
</a>
```

then I click to OK, and reopen the source editor. HTML structure changed. Here is the result:

```
<div class="partner">
    <img src="/uploads/_partnerek_/Atrium_Filmszinhaz/logo.jpg" alt="" />
</div>
<p>
    <a href="/hu/szinhaz/Partnerek/Atrium_Filmszinhaz">Átrium Filmszínház </a>
</p>
```

This is very painful. Why is it? And how to solve this? You can try the offical tinymce source editor. Same result.

I've tried a lot of options:

```
cleanup_on_startup: false,
trim_span_elements: false,
verify_html: false,
cleanup: false,
convert_urls: false,
cleanup : false,
verify_html : false,
element_format : 'html',
```

but it did not help.

Is this a bug?

**Comment by spocke** [comment]
This the the only thing about the HTML5 spec we don't allow since block based anchors are problematic in a rich text editor since how do you handle nested links and how do one make a UI to edit these block based links. You need some form of block link editor that can wrap things in blocks.

**Comment by GaryStanton** [comment]
Has there been any progress on this? There are loads of similar questions around the web - even if it's problematic from a UI perspective, currently the code editor is simply stripping out valid HTML5.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
