### ISSUE TITLE
Inline mode paste triggers undesired blur event in MS IE 

### ISSUE THREAD

**Issue by hipi1** [tinymce/tinymce#3151]
When using TinyMCE in inline mode an undesired _blur_ event will be triggered on _paste_.
Affected browser is only MS IE (tested with IE 11), latest Firefox and Chrome are OK.
It can cause problems in such applications which are listen to onBlur event.

Note: if you use a simple contenteditable element it is not affected, only when TinyMCE is attached to it.

See my sample at http://fiddle.tinymce.com/85faab/15

**Comment by spocke** [comment]
Yes, you need to use the tinymce blur/focus events not the browsers. Since when paste occurs we move focus to a hidden element and paste into that. I guess we could stop propagation. But since this can be easily avoided by using editor.on('blur', ...). So closing since it can be worked around easily.

**Comment by hipi1** [comment]
@spocke , thank you, the workaround is fine for me.
