### ISSUE TITLE
TinyMCE preserves the style of content being edited even after being deleted

### ISSUE THREAD

**Issue by sandyjoshi** [tinymce/tinymce#3153]
in TinyMCE on the [example](https://www.tinymce.com/docs/demo/basic-example/#liveexample)
- Apply format to any word ( like bold, italic, background color etc.)
- Delete that word by pressing back space ( just that word, nothing extra )
- start typing new word again
- That new word will have the same format which you have applied earlier

I want to make it like whenever that word is deleted that formatting will be lost.

Is there any configuration property to get this done ? I want TinyMCE to forget that style whose word is just deleted.

**Note** : In current behavior we have to delete one more letter or move cursor to some different position to change the formatting being applied.

**Comment by pywebdesign** [comment]
I would argue it is a great feature. we are trying to make this thing happen on select all and delete to.

**Comment by donShakespeare** [comment]
@sandyjoshi when you hit backspace you only delete to the beginning of the HTML element.
You simply removed the `text()` value of the element not the element itself. The element itself has the CSS style and other properties.

This is not a bug or glitch, I don't think. But quite to be expected.

You want a tiny plugin to enable you to:
   right-click on any element and hit "Delete the whole of this element"
This plugin will go to the DOM and replacewith or remove selected text container

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
