### ISSUE TITLE
Noneditable a tag is still editable through dialog

### ISSUE THREAD

**Issue by chaot1x** [tinymce/tinymce#3158]
Hello, im using link and noneditable plugins, i've set noneditable class on one a tag in editor, It can't be edited directly in editor, but when I open connected dialog I can edit everything here. Any ideas how can I fix it so It's not possible to edit it in dialog?

**Comment by spocke** [comment]
Yes, the link button should probably be disabled in that case.

**Comment by chaot1x** [comment]
@spocke Hey any updates on this?
Maybe someone can provide some fast fix for this.
Thanks!

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
