### ISSUE TITLE
Text indentation parse float value

### ISSUE THREAD

**Issue by karantin2020** [tinymce/tinymce#3161]
Hello.
Commands `indent`, `outdent` just get `int` value only.
See: https://github.com/tinymce/tinymce/blob/c8d57d7b8491ea431ab68d2c26ad6d020e3aeada/js/tinymce/classes/EditorCommands.js#L473.

Why not to pass to function float value too? E.g. `1.25cm` or something similar.
This thing is useful when formatting document.
Thanks

**Comment by noahduncan** [comment]
Implemented in my [pull request](https://github.com/tinymce/tinymce/pull/3808)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
