### ISSUE TITLE
Duplicate style declarations are being stripped out

### ISSUE THREAD

**Issue by jasonsamuels** [tinymce/tinymce#3163]
I'm running into an issue with TinyMCE where, after pasting code in via Source Code view, the WYSIWYG editor strips out duplicate style declarations in the code.

The problem is that those duplicate style declarations are intentional and necessary for the email to render properly across email clients, per [this design technique](https://medium.freecodecamp.com/the-fab-four-technique-to-create-responsive-emails-without-media-queries-baf11fdfa848).

Here's a screen capture of what it's doing:
![image](https://cloud.githubusercontent.com/assets/11141357/18094930/df377c12-6e9a-11e6-8254-23f800ee0fa3.png)

And a link to the [before and after code via Diffchecker](https://www.diffchecker.com/aV7SzTUT)

I've scoured the documentation and tried many settings changes in the fiddle, but nothing seems to prevent TinyMCE from affecting the code this way. Is there any way to prevent this or is it just not supported?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

*Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)*

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
