### ISSUE TITLE
i18n issue in inlite theme

### ISSUE THREAD

**Issue by ozgrozer** [tinymce/tinymce#3170]
http://codepen.io/anon/pen/gwOPwA

As you can see in the link above, some toolbar items like "Insert/Edit link" and "Paste or type a link" seem untranslated. I didn't try all of the toolbar items, just those ones. So is there any way to fix them or waiting for new update?

**Comment by spocke** [comment]
I think you just need to add the proper key. So "Insert/edit link": "your translation".

**Comment by ozgrozer** [comment]
http://codepen.io/anon/pen/ambYRY

Yes, that one is working but "Paste or type a link" is not working.

**Comment by spocke** [comment]
Yes, you are correct. We will look into this. Thanks for the report.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
