### ISSUE TITLE
Keyboard selecting from down to up is weird

### ISSUE THREAD

**Issue by Mrten** [tinymce/tinymce#3172]
Type three sentences with enter in between:

1oiwjeoij
2oijoijw
3oisoijg

Now, with the cursor still at the bottom, press shift and arrow-up a few times. Tinymce will select the third sentence, then nothing, the the second, then nothing, every key press something else, but never what happens if you try this from top to bottom (selecting all sentences).

Even more fun is if you now enter two or three more sentences separated with shift+enter, make a bulleted list from it with the button and then try to go up with shift+enter, if you reach the original three sentences they will half-select (meaning that only first half of sentence 3 + last half of sentence 2 get selected, etc).

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
