### ISSUE TITLE
question make element be treated as an image or non editable but let it be formatted

### ISSUE THREAD

**Issue by thesquaremedia** [tinymce/tinymce#3173]
hi id like to have a tag with a specific class be treated as either an image or non editable element while maintaining the capabilities for it to be formatted as having font color,size or alignment still be attach or wrapped around it.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .

**Comment by lostkeys** [comment]
We're doing a bit of spring cleaning of the TinyMCE Github issues. Your feature request were submitted a very long time ago and the description isn't too clear about what you want to achieve or what the use case is. Therefore we are going to close this issue. If you're still around, please feel free to add some more details to your feature request and we'll reopen it. Thanks.
