### ISSUE TITLE
Empty noneditable element gets removed if inserting into empty html via mceInsertContent

### ISSUE THREAD

**Issue by josh18** [tinymce/tinymce#3175]
I think this looks like a bug with TinyMCE but I'm not 100% sure.

I have a [plugin](https://github.com/josh18/TinyMCE-FontAwesome-Plugin) and when you trying to insert an icon onto an empty editor it removes it. However if the editor has something in it the insert works fine.

The relevant code is is something like this:

``` js
// plugin.min.js
editor.execCommand('mceInsertContent', false, '<span class="fa fa-adjust"></span>');
```

``` js
tinymce.init({
    ...
    extended_valid_elements: 'span[*]',
    noneditable_noneditable_class: 'fa',
});
```

[Demo](https://fiddle.jshell.net/5v5nzo91/2/)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
