### ISSUE TITLE
cursor before last symbol

### ISSUE THREAD

**Issue by PetrBorisov** [tinymce/tinymce#3176]
see: tinymce/tinymce/issues/2674

how can I solve this problem?

maybe i need call something function in 'focusin' event?

**Comment by spocke** [comment]
Wasn't this resolved in the other ticket. Moving foucs from the editor to something else will blur the editor. You can prevent that by blocking onclick and preventing focus or make the button part of the tinymce ui. There is also a predicate that you can define with custom logic that tells that the item is part of the editor UI.

Closing this since it seems more like a question than a bug or feature request.
