### ISSUE TITLE
target="_blank" vulnerability

### ISSUE THREAD

**Issue by dakshalraijada** [tinymce/tinymce#3177]
Hi Guys, 

Big fan of your work and really appreciate it. 
This is a feature request and not an issue.

If you use the target="_blank" attribute on a link, and do not accompany it with a rel="noopener" attribute, you are leaving your users open to a very simple phishing attack. 

When a website uses target="_blank" on their links in order to open a new tab or window, that website gives the new page access to the existing window through the window.opener API, allowing it a few permissions. Some of these permissions are automatically negated by cross-domain restrictions, but window.location is fair game.

In order to restrict the behavior window.opener access, the original page needs to add a rel="noopener" attribute to any link that has target="_blank". However, Firefox does not support that tag, so you should actually use rel="noopener noreferrer" for full coverage.

There is a further reading over [here ](https://dev.to/ben/the-targetblank-vulnerability-by-example) with example

**So, the request is to add rel="noopener noreferrer" whenever open in new tab is selected by the user in wysiwyg editor.**

If you do have this feature, please ignore, I might be using an older version.

Thanks,

**Comment by Afraithe** [comment]
Thanks for reporting this by the way. 

I guess it should be possible to configure tinymce already to force that option on all links, but that might not be the best way of implementing this. Will look into it.

**Comment by jayarjo** [comment]
While we do not enforce `rel="noopener noreferrer"` on `_blank` links (and we probably should), we provide [rel_list](https://www.tinymce.com/docs/plugins/link/#rel_list) option, that lets you define a list of values to apply to `rel` attribute if selected.

**Comment by jayarjo** [comment]
This has been addressed now in v4.5.0. Related option - `allow_unsafe_link_target` is described [here](https://www.tinymce.com/docs/configure/content-filtering/#allow_unsafe_link_target).

**Comment by dakshalraijada** [comment]
Thank you guys!! 👍

**Comment by johndubya** [comment]
Hang on a minute. Why are internal (i.e. relative) links with target `_blank` also getting `rel="noopener noreferrer"`? Isn't it true that if the link goes to your own website, reverse tabnabbing is impossible? A hacker would have to put malicious code on your website for reverse tabnabbing to work for internal links. I've been reading that this can potentially have a serious SEO impact on sites. Was the difference between internal vs. external links with target `_blank` considered?

**Comment by RealDavidoff** [comment]
No, nothing was considered, neither by dakshalraijada who posted this idiotic "feature request" nor by jayarjo et al who followed suit. :-(

Idiotic? You read that right. Sadly, you didn't read that "feature request" right that brought this MESS onto hundreds of millions of wp users! :-(((

Didn't read right? Indeed: ONLY a link that a SITE OWNER puts(!) or allows(!) to ANOTHER one's site ("alien" site) that he/she neither checked for quality nor is interested(!), ONLY such a link would pose any risk at all.

NO other link. In fact, the millions of site OWNERS(hello!) have always posted links to external sites that they know very well what site that is. And for NONE of all those links that we site OWNERS(get that!) post on OUR sites bear any "risk" at all. Is that so hard to READ and understand?

> site owner adds internal link >> NO risk
> site owner adds research links >> NO risk
> site owner adds media links >> NO risk
> site owner adds links to owned network sites >> NO risk

>> ONLY a link risk exists for the few site owners who a) don't know what they link to, and b) don't care!

And frankly, those few deserve to bear risk. 

But is wp serving those idiots, or the millions of decent wp users who put links ON PURPOSE, links they WANT, and the way they PUT them. WITHOUT those idiotic tags SECRETLY ADDED by non-site owners = wp programmers.

Unbelievable.

**Comment by spocke** [comment]
The code was changed to forcing rel="noopener" on links with target="_blank" since the admin page might not be the same domain as where it's being displayed we can't simply check the domain.

There is an option to opt out of this security feature but security should be opt out not opt in. If you have a blog and a link to an external site that site can be hacked and redirect your blog page in another tab to a faked admin login for your wordpress then you login to that hackers site and they grab the username/password and boom your blog is p0wned!

It might not be an issue for experienced users but there is a lot of people that doesn't really look at the location bar when they do things and if it's a targeted attack you would just change a letter or to in the domain name and you wouldn't notice.

**Comment by RealDavidoff** [comment]
Wrong. There is NO option that works, to "opt out" of this idiocracy! I have tried everything that's posted online and Google can find, and NONE works.

Security?? As clearly shown above, that particular wp gimmick adds ZERO security but huge confusion and annoyance to millions of site owners. As always, only a handful speak out, But all are suffering.

We clearly do NOT wish ANY secret changes of content WE AS SITE OWNERS put on our sites.
But with that crap of misunderstood "security" feature, now we save some widget content or comment content, BELIEVE it gets posted AS WE ENTERED IT, but hey no: while saving, wp has changed OUR content, and secretly! So we go in, correct that to OUR content, save it, and again the persistent, stubborn change from wp! That's hijacking of user content. Illegal. Unethical. Unacceptable.

If you persist in such idiocracy, add a tick box like earlier for other things.
And if you are that stubborn, okay, make the tickmark the default.
But at the very least, provide a meaningful way for site owners to post EXACTLY the content they *believe* they post to their site. Here, WITHOUT the foolish noopener tag.

Foolish? What, did you miss the earlier explanation??
ONLY linking to questionable sites CAN at all pose a risk. We don't do that. Very few wp users overall do that.

**Comment by fyrkant** [comment]
@RealDavidoff 

First of all I think you need to step away from the computer and cool down a little. 

Secondly, what do you mean there isn't a a way to opt out? The [allow_unsafe_link_tarket](https://www.tinymce.com/docs/configure/content-filtering/#allow_unsafe_link_target) setting that @jayarjo links above should work just fine.

**Comment by johndubya** [comment]
@RealDavidoff, I wrote a [blog post](http://washamdev.com/2017/04/why-rel-noopener-noreferrer-in-wordpress-links/) about turning this feature off for a WordPress site.

**Comment by RealDavidoff** [comment]
I read that too, and that too doesn't work.
Read above, wp now hijacks site owner content in widgets, comments, posts, pages.

As I explained in the wp forum long ago, we already CORRECT wp here:
wp-includes/default-filters.php: row 212, to NOT have wp add nofollow to comment links
DELETE
add_filter( 'pre_comment_content',      'wp_rel_nofollow',              15    );

EVERY TIME we have to redo that, since wp programmers choose to foolishly follow fake "security" issues that NO legit wp user has anyway (they don't link to risky sites, only the programmers in their dreams do!), instead of addressing the pressing content issues we users have called for for some 6 years...!

**Comment by Afraithe** [comment]
Sorry, but since they are re-adding it, there isn't much we can do on our side here.

**Comment by RealDavidoff** [comment]
That's why my wording is so harsh. You now realized that the wp programmers who blindly followed that idiotic "security" report of someone who can't think clearly (or just READ WHAT I WROTE) left us users NO WAY to simply "opt out" of that nonsense. Like you and others naively claimed we can.

Thus again, hopefully one day soon one of those "programmers" wakes up, READS this thread (or any of my other related threads) and cuts out that idiocracy altogether!

**Comment by gtrufitt** [comment]
Gotta say @RealDavidoff, you've really got to learn how to have a constructive conversation. There's no reason to keyboard-warrior the way you're doing here, act like an adult.

**Comment by RealDavidoff** [comment]
Either you cannot READ or you aren't an adult yourself: Wasting your time like a child on sth you have neither READ nor understand.

And if only(?) you hav a personal issue with language, reconsider attending language school. Or, learn not to take everything as serious as you seemingly do. ;-)

**Comment by gtrufitt** [comment]
Frankly I'm just glad I don't work with you @RealDavidoff

**Comment by donShakespeare** [comment]
I am the master of language, and also the master of human nature, and I tell you candidly, in all my 500 years of composing, honey is better than vinegar, well, depends on what you are trying to achieve - and what kind of vinegar.

But, I find that telling people that they are nincompoops because they cannot fathom the plainness of your erudition will never motivate them to go back to read anything you wrote no matter how outstanding and sincere.

>Fighting nincompoopity with nincompoopity is a two-way stop-sign junction in a rough lawless country.
> ... all manners fly out da wyndow

**Comment by RealDavidoff** [comment]
@everyone who's spoofed by those few people posting above such nonsense:

READ this: https://wordpress.org/support/topic/delete-wordpress-automatic-nofollow-filter-plugin/#post-9662581

Same with noopener tag. Gotta THINK before you post, before you work, before you program, before you sell.
Well, I do.

**Comment by fyrkant** [comment]
I think we have talked about this issue enough now, and there is nothing we can do about it in TinyMCE. Locking this conversation.
