### ISSUE TITLE
question: Is there a way to only edit the font-size and styles only?

### ISSUE THREAD

**Issue by xxvii27** [tinymce/tinymce#3182]
Hi, 

I'm wondering if there's a way to only edit the styles (colors, bold, italic) and font-size of an element only, and disable the text editing for that element? I tried using the nonEditable plugin, but that disables everything.

**Comment by sstragier** [comment]
+1
I'd also like to know if there is a way to style nonEditable elements or to create elements that can be styled/formatted but the text cannot be edited.

**Comment by jayarjo** [comment]
Could you guys elaborate in more detail on scenario when this might be required/useful?

**Comment by sstragier** [comment]
@jayarjo I am using nonEditable elements in tinymce to manage templates where users can insert template tokens that will later be replaced with values when the template is rendered. Because of this, it would be great if users can use the same tinymce formatting methods (i.e. the toolbar) to format the template tokens (currently implemented using nonEditable so the user can't edit the tokens directly). Here is a plunker showing what I am talking about: https://plnkr.co/edit/HbaTMldm9CuIjrSTPAI7

Additionally (maybe this is a separate issue that I need to open), I created a plunker (https://plnkr.co/edit/dUxPRne4zkdRg6cJx04Q) which shows what happens...

1. If you highlight text surrounding a nonEditable element and try changing the style (i.e. bold)
 * The text before and after the nonEditable element is bold but the nonEditable element is not.
2. If you drag (or paste with the paste plugin) the nonEditable element into the bolded text
 * The nonEditable element will be bolded

It seems like the behavior for those two actions should be the same.

FYI, I'm testing in Chrome. I noticed that drag-and-drop of nonEditable elements does not appear to work in IE.

**Comment by qodo** [comment]
+1

I think it would also be useful to be able to select a noneditable element and then format it. The reason for this is that I would like to use these as variables that are replaced with real values later. It would be good to be able to wrap them in simple formatting tags like `h1`, `p`, `strong `etc.

If you view my fiddle: [http://fiddle.tinymce.com/h9faab/11](url) and select one of the {{variables}} and try and make it bold for example it doesn't work. 

Is this possible?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
