### ISSUE TITLE
Cannot indent tables

### ISSUE THREAD

**Issue by aiftariyani** [tinymce/tinymce#3186]
reproduceable on https://www.tinymce.com/docs/demo/classic/

If you create table i.e 3*3
block the table
then click indent 

actual  : looks like it can be indented but there is an odd additional outer border. 

See images for more deta
![cannot indent tables](https://cloud.githubusercontent.com/assets/22090142/18375824/d5a7b2b6-7683-11e6-9f5f-383edf2b5aaf.PNG)
ils.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
