### ISSUE TITLE
Ability to copy a row which contains merged cells as-is

### ISSUE THREAD

**Issue by aiftariyani** [tinymce/tinymce#3187]
Steps to Reproduce:

-Go to https://www.tinymce.com/docs/demo/full-featured/
- Create a 4x4 table.
- Select cell B3 and perform a merge cells
- right click then select cell and click merged cell
- Enter the following into the Merge Cells Dialog and click OK 

Cols: 3
Rows: 1
- Select B3 > right click > row > copy row
- still on the B3 > select Row > Paste Row Before or Paste Row After

Actual Results :A new row is added without merged cells 
Expected Results : A new row be added to the table with the first three cells merged the same as the row that was selected.

**Comment by michaeljohnstonverint** [comment]
Video of issues: https://youtu.be/4VHbJwb6lok

**Comment by jayarjo** [comment]
@spocke I think this is something you've fixed sometime ago?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
