### ISSUE TITLE
Issues with Tables: Cannot change one property for a set of table cells without overwriting other previously-set properties

### ISSUE THREAD

**Issue by aiftariyani** [tinymce/tinymce#3188]
Steps to Reproduce:

1)Go to https://www.tinymce.com/docs/demo/full-featured/

2)Create a table and color each row
![step1](https://cloud.githubusercontent.com/assets/22090142/18381725/d3d44188-76a7-11e6-8d5c-bb500cf64a90.PNG)

3)Select all rows | right-click and set cell height = 30
![step 2](https://cloud.githubusercontent.com/assets/22090142/18381739/e5e73cea-76a7-11e6-99b6-41b2d0ecbd45.PNG)

actual result  : Result is that 2nd set of properties are applied, but first set is lost:

When modifying properties, it seems to retain the formatting that was set using the main WYSIWYG pallette selections. However, if you right-click within a table and choose "Cell Properties", then any new settings seem to wipe out the previous settings even when there shouldn't be any overlap. Example:
If right-click and set the cell width, background color, border color, etc., and then go back in and set additional properties (or change a previously set property), then all prior properties are lost (i.e., reverted back to the original settings).

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
