### ISSUE TITLE
Problem with codesample focus area

### ISSUE THREAD

**Issue by ZigaStrgar** [tinymce/tinymce#3194]
If you have tinymce inside bootstrap modal and want to use codesample the text area is not focusable so you can't edit or write new "codesample".

**Comment by jayarjo** [comment]
An actual example via [CodePen](http://codepen.io/) might help to nail the problem quicker.

**Comment by ZigaStrgar** [comment]
Hello,
here is the jsfiddle of this problem https://jsfiddle.net/xroy4svL/

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
