### ISSUE TITLE
fixed_toolbar_container target

### ISSUE THREAD

**Issue by sijad** [tinymce/tinymce#3212]
same as https://github.com/tinymce/tinymce/issues/2957
is it possible to use an element with `fixed_toolbar_container`?

**Comment by sijad** [comment]
it a little hard to use add `id` to my element in my case. I looked at the codes but I couldn't find a way to use an element instead of a selector in `fixed_toolbar_container`.

**Comment by mscreenie** [comment]
Any update on this?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
