### ISSUE TITLE
Multibyte Characters Not Encoded Correctly in Named+Numeric

### ISSUE THREAD

**Issue by jtark** [tinymce/tinymce#3213]
When TinyMCE is initialized with `entity_encoding='named+numeric'`, only the first byte of multibyte characters are encoded. For instance, `&#128512;` (unicode character `U+1F600`) ends up encoded as `&#55357;` This seems to be due to an inline implementation of the numeric encoding that doesn't account for additional bytes. The standard numeric encoding function works as expected, encoding the character properly when `entity_encoding` is set to `numeric`.

I had a fix for this a while ago, but was unable to get the pull request to function due to an anonymous email address (even after I set my email address to public). See https://github.com/tinymce/tinymce/pull/2917 for one of the pull requests if you like.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
