### ISSUE TITLE
Dialogs inputs too small with materializecss

### ISSUE THREAD

**Issue by ogero** [tinymce/tinymce#3214]
Hi, is there any chance tinymce will be fixed to be used with materializecss without clashing styles?

![20160919_174447-tinymce fiddle](https://cloud.githubusercontent.com/assets/167090/18648410/e3a12de2-7e90-11e6-84c7-a2502d8ac268.png)

Here is a fiddle reproducing the issue:
http://fiddle.tinymce.com/u7faab

Thanks.

**Comment by steve-todorov** [comment]
Having the same problem. Did you manage to find a solution?

**Comment by ogero** [comment]
Regrettably, no.

**Comment by acndeveloper** [comment]
Hi. In my project work on this way:

Have a file.css and paste this: 
`input.mce-textbox{width: auto;background: #fff;border: 1px solid #c5c5c5;display: inline-block;-webkit-transition: border linear .2s, box-shadow linear .2s;transition: border linear .2s, box-shadow linear .2s;height: 28px;resize: none;padding: 0 4px 0 4px;white-space: pre-wrap;*white-space: pre;color: #333;}`

In this case, width: auto fix all the troubles. To use the tinymce style in fields, just add de intire code.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
