### ISSUE TITLE
Result is not correct if the note is too long in IPAD

### ISSUE THREAD

**Issue by kephyz** [tinymce/tinymce#3216]
Hi,

When i put a big text in the tinymce, the result in Ipad is not ok.
In attached file, you can see a sample. I made a directly direcly on www.tinymce.com. 

Expected behavior:
- respect the width of the editor
- force the body with scroll bar maybe ?

Thanks,
![tiny](https://cloud.githubusercontent.com/assets/22325882/18678322/f5f3649e-7f5b-11e6-9a98-048712ec4158.png)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
