### ISSUE TITLE
tinyMCE line height issue on IE and chrome

### ISSUE THREAD

**Issue by youjace** [tinymce/tinymce#3219]
Hi, 
I tried pasting formatted text from word. I need the exact look of the text on word to be the same on tinyMCE but when I pasted the text, it looks ok on chrome but not on IE - it has a huge line height.
this is the text on word:
![image](https://cloud.githubusercontent.com/assets/22339509/18700820/f128aefa-800b-11e6-9d9a-164d466837ad.png)

this is what the pasted text looks like on IE:
![image](https://cloud.githubusercontent.com/assets/22339509/18700846/12b43a8a-800c-11e6-9ea3-eb4b880db8c0.png)

you can try using this link on both IE and chrome and the result is also the same:
http://fiddle.tinymce.com/EDeaab/6

any ideas anyone? Thanks!

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
