### ISSUE TITLE
resize problem on chromium ubuntu

### ISSUE THREAD

**Issue by stefanchiriac** [tinymce/tinymce#3220]
Hello,

On ubuntu 16.04 with chromium-browser 52.0.2743.116 if I try to drag to resize on height is not working and on width is resizing around 100px on the slightest move.
I tried on all tinymce 4 examples I could find on google, including the ones on demo section from the website and the result is the same.
I also tried on firefox and browsers under windows and the problem is not replicating. Seems to be only for chromium ubuntu (I didn't tried other linux flavors).

Thanks

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
