### ISSUE TITLE
InternetExplorer: block-element with max-width encapsulates the affected container

### ISSUE THREAD

**Issue by SirPaladin** [tinymce/tinymce#3235]
I think i found a bug. I'm having problems with several "old" and "modern" IEs and now i found the relating CSS-part to reproduce. 
At the moment im testing with a Microsoft Edge 12 (20.10240.16384.0) in Windows 10 on my Virtualbox but i already saw the problem in older IEs (e.g. IE 11 on Windows 7). 

Steps to reproduce: 
- Use an Internet Explorder or Edge-Browser
- open this Editor: https://www.tinymce.com/docs/demo/full-featured/
- edit the HTML in the Editor
- add an inline-style to a`<p>` (`<p style="max-width:10em;">Note that any <strong>MoxieManager</strong> file and ...`)
- click in this paragraph to set the cursor there
- --> **description of the problem**: now the cursor can't move out of the block with the keyboard-cursor-keys, you only can mark text of this block with the mouse and you can't connect this block with the other blocks (before and after) with the del-key and the backspace-key on the keyboard. 

In older IEs like IE 11 a frame is drawed around the affected block when the cursor is in the block. 
I don't know if the newest version of Edge still has this problem - dont have a virtual machine with the newest one. 

For me this issue is very important because i always import the CSS (containing max-width) of the Website-Frontend

Thanks in advance!

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
