### ISSUE TITLE
Can't delete selected text if selection is before contenteditable=false element

### ISSUE THREAD

**Issue by alexyuryev** [tinymce/tinymce#3240]
Chrome 52, firefox 49 , tinymce 4.4.3, tested on Windows 8

Steps to reproduce:
1. Open fiddle https://jsfiddle.net/n5tf7nwd/2/
2. Move the cursor between a and b
3. Press Shift+-> twice (Chrome) OR select by mouse from the "b" (including) to the middle of the yellow rectangle (ce=false) (Chrome) OR do tripple click on "ab" text (Chrome, firefox)
4. Press DEL

Expected: text before contenteditable=false is deleted, because it was selected
Actually: text is not deleted, only contenteditable=false is deleted

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
