### ISSUE TITLE
contenteditable="false" and class="mceNonEditable" is not honored in IE 11

### ISSUE THREAD

**Issue by csockman** [tinymce/tinymce#3245]
Here is a screencast demonstrating the issue: http://screencast.com/t/otpNp9jk
Here is a TinyMCE fiddle that you can use to recreate the issue: http://fiddle.tinymce.com/z8faab
Here is the sample html that I used in the screencast:

```
<div contenteditable="false" style="background-color: lightgray">A div with contenteditable="false"</div>
Test
<br />
<div class="mceNonEditable" style="background-color: lightgray">A div with class="mceNonEditable"</div>
Test
```

To summarize the issue, contenteditable="false" and class="mceNonEditable" are not honored in IE 11. Under certain conditions you can use the backspace to key to gain entry into the "protected" DIV. It should be noted that this issue seems to be IE 11 specific. It also is of note that this was not an issue in IE 11 with release 4.3.13.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
