### ISSUE TITLE
Colorpicker DOM.getPos returns wrong y with relative positioned body and scrolled

### ISSUE THREAD

**Issue by mattgast** [tinymce/tinymce#3248]
Steps to reproduce:
1. Position your body relative
2. Add a table inside tinymce
3. Scroll the body down a bit
4. Go to cell properties for any cell, select the advanced tab and open the colorpicker
5. try to select a color

Current result:
selection will be offset by scroll amount

Expected result:
Selection should match mouse pointer

Made a codepen copy of the full demo and replicated:
http://codepen.io/mattgast/pen/LRZAmQ

Screenshot:
![image](https://cloud.githubusercontent.com/assets/4122592/19135962/656e750c-8bb4-11e6-90eb-3d1b18bdc328.png)

**Comment by trailsnail** [comment]
Hi there, we have the same behaviour here:
Tiny in Fullscreenmode the same like author explained. If tiny is used in smaller containers, the picker moves only from left to right.
![color_picker_in_fixed_position_container](https://user-images.githubusercontent.com/4742603/30807781-9639c1ce-a1fb-11e7-8875-1eb166e1387c.png)
![color_picker_in_fullscreen_tiny](https://user-images.githubusercontent.com/4742603/30807782-96a14678-a1fb-11e7-9146-9b1204c4fb78.png)

**Comment by staabm** [comment]
we also experience this problem :-/

**Comment by supertemp** [comment]
We have this problem too. Subscribed.

**Comment by ajtruckle** [comment]
I have this problem. Please help. :)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
