### ISSUE TITLE
Disable all keyboard shortcuts

### ISSUE THREAD

**Issue by cyb-ahmadh** [tinymce/tinymce#3262]
Is there any way to disable editor's keyboard shortcuts?

I tried [this](http://wordpress.stackexchange.com/a/168044) but no luck for combination keys.

Please let me know if there any other ways to do it.

Thanks

**Comment by spocke** [comment]
You can disable some of them but a few are native to the browser and can't be disabled. Why exactly do you want to disable keyboard shortcuts this is normally not something you need to do.

**Comment by cyb-ahmadh** [comment]
I want to disable all these `shift` and `alt` combinations shortcuts.  Like these `shift+alt+1`, `shift+alt+2`, `shift+alt+3`,.... `shift+alt+10`,

**Comment by hparth** [comment]
I am facing same issue. Don't want default shortcuts but there no way to disable all those shortcuts.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
