### ISSUE TITLE
Reopen #2642 - Javascript error when handling multiple editor instances on Edge

### ISSUE THREAD

**Issue by CGollhardt** [tinymce/tinymce#3267]
Sorry, for a new issue for this, but I wasn't able to reopen the old issue https://github.com/tinymce/tinymce/issues/2642.

This issue seems to be closed but it is not resolved.

There is a Bug in Edge, that does not allow to remove a editor instance and create it again.
From the linked issue, the steps to reproduce:

> - calls tinymce.init() with selector equals to '#textarea_id'
> - onclick on the button will remove the textarea from the DOM, injects a new one and calls tinymce on it again.

The Issue also have had a bugfix in it:

_tinymce/classes/dom/Serializer.js_
Change
`if (Env.ie && dom.select('script,style,select,map').length > 0) {`
to
`if (Env.ie && Env.ie < 12 && dom.select('script,style,select,map').length > 0) {`

I would do a push, but i mainly develop with TFS, and have no idea about it. Currently I am mainting my own version.

Is it possible to bring this into the main branch? Or has this fix any sideeffects?
I think, Edge is an essential browser to support current days.

**Comment by spocke** [comment]
Can you setup a test case at http://fiddle.tinymce.com that reproduces the issue so that we can look at it. Thanks

**Comment by CGollhardt** [comment]
I am working on a fiddle right now. It seems like I have found bug (Edge), which is not covered by the fix above. I need to investigate a bit more.

**Comment by Niniania** [comment]
Is there any news on this ? Still getting the error in Edge in latest version of Tinymce, its making the Editor unusable for us in Edge browser as we add and destroy components and the Editor along with them and get this error.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
