### ISSUE TITLE
Chrome + init callback + custom skin

### ISSUE THREAD

**Issue by ctjhoa** [tinymce/tinymce#3273]
With a custom skin, `tinymce.init(...).then(...)` / `init_instance_callback` function is call when the `skin.css` is not fully loaded.

Chrome: 53.0.2785.143 (64-bit) (other browsers don't seem to be affected)
Tinymce: 4.4.3

Reproduction:
Follow the codepen with dev tools open.
The debug point shows that at this time the rendering is blank.

http://codepen.io/anon/pen/NRLoxx

Tinymce should be fully rendered at the debug point.

**Comment by ctjhoa** [comment]
I've found a dirty workaround:
```javascript
init_instance_callback: function() {
   doStuff();
    $('link[href="YOUR_SKIN_URL/skin.min.css"]')
        .load(function() {
            doStuff();
        });
}
``` 
Explanation:
In my case I don't mind if `doStuff` is called twice.
So for browsers without this bug `doStuff` is call once because css file will already be loaded during the execution of `init_instance_callback`

On the contrary if the skin css file is not loaded, `doStuff` will be recalled after the load of the css file.

I think that code could be adapt if you want to call `doStuff` only one time in every case.

**Comment by ctjhoa** [comment]
Some hints:
https://bugs.chromium.org/p/chromium/issues/detail?id=481922
https://bugs.chromium.org/p/chromium/issues/detail?id=637373

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
