### ISSUE TITLE
Inline .toAbsPath exception inside srcdoc iframe breaks all future editors.

### ISSUE THREAD

**Issue by Rycochet** [tinymce/tinymce#3275]
Simple enough setup - inline editor within an `<IFRAME>` that has content added to it via Javascript and using a `SRCDOC="<!DOCTYPE html>\n<html><head></head><body></body></html>"` to give a blank document to start with.

When adding the inline editor to a `<P>` with and inline `<IMG>` using a relative path the .toAbsPath errors out, and prevents any future editors from being created (ones created before this work perfectly).

The offending line is - https://github.com/tinymce/tinymce/blob/master/js/tinymce/classes/util/URI.js#L286
`base = base.split('/');`

I don't know the code, but assuming it's trying to create an absolute path, without a true url to start with - 

``` javascript
location = {
   hash: "",
   host: "",
   hostname: "",
   href: "about:srcdoc",
   origin: "null",
   pathname: "srcdoc",
   port: "",
   protocol: "about:",
   search: ""
}
```

Possibly related to #2243

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
