### ISSUE TITLE
Selected content after video/code sample/noneditable not deleted when backspacing

### ISSUE THREAD

**Issue by cyrildc** [tinymce/tinymce#3281]
**Steps to reproduce**
1. Insert a video followed by a paragraph
2. Select the paragraph and hit backspace.

**Result:** the paragraph is not deleted (same if we replace the video by a code sample or a noneditable element )

![tinymce-backspace](https://cloud.githubusercontent.com/assets/7342202/19555094/ab8caf7e-96bb-11e6-9b09-f6962def4557.gif)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
