### ISSUE TITLE
Table with only 1 cell is removed when we empty the cell

### ISSUE THREAD

**Issue by cyrildc** [tinymce/tinymce#3282]
**Steps to reproduce**
1. Insert a table of 1x1
2. Enter a paragraph
3. Empty the cell by doing 1 of the following action:
   - Select the whole paragraph and hit backspace/delete or cut.
   - Hit backspace  (or delete key) multiple times until the whole paragraph is deleted
   - Select the whole paragraph and type a letter to replace the content

**Result:** the table is deleted with the paragraph

**Expected result:** keep the table with the cell empty which currently happens with table of more than 1 cell, 

![1col](https://cloud.githubusercontent.com/assets/7342202/19556580/19f62214-96c2-11e6-8ec5-48a32cd64acf.gif)

**Note:** it works as expected with a video, the table is preserved.

![video](https://cloud.githubusercontent.com/assets/7342202/19557132/a71fe2fe-96c4-11e6-9733-e468613849bc.gif)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
