### ISSUE TITLE
Shift+Arrow near contenteditable=false selection issues

### ISSUE THREAD

**Issue by alexyuryev** [tinymce/tinymce#3291]
If you want to surround **ce=false** span by pressing **shift+arrow** you have to repeat the press 4 times (Chrome) or twice (FF).

Tested on tinymce edge/nightly/4.4.3.
1. Open [this fiddle](http://fiddle.tinymce.com/cAfaab) in Chrome and run
2. Put the cursor after "1" and before yellow rectangle
3. Start pressing Shift+Right Arrow to select rectangle

_ER: after one press rectangle is in selection
AR: after 4 presses rectangle is selected_

The same is true for backward selection or when other text is included in the selection.

In Firefox you have to press Shift+Arrow twice.

In SelectionOverrides.js we have:

```
if (VK.modifierPressed(e)) {
    return;
}
```

So, there is no override for default browser behaviour.

Also, there is no selection mark (data-mce-selected) after selection on the span in this scenario. Is it expected?

Thank you for your attention!

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
