### ISSUE TITLE
Cannot click outside table elements on Firefox

### ISSUE THREAD

**Issue by Shigeki1120** [tinymce/tinymce#3294]
Delete every content and paste a table, and try to click the right side of table.On Firefox, some weird stuff (I don't know know how to call it), comes up and you can not press enter to make a new line since you cannot focus on the right side of the table

https://www.tinymce.com/docs/demo/full-featured/

Please try to see it on Firefox

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
