### ISSUE TITLE
Delete Key does not delete Image element if the image is the only child of a paragraph in IE 

### ISSUE THREAD

**Issue by mimrezash** [tinymce/tinymce#3295]
To reproduce the issue :
1- Open Tiny Mce editor in IE edge. 
2- Open source code tool 
3- Copy following html in the source code
`<p><img title="TinyMCE Logo" src="//www.tinymce.com/images/glyph-tinymce@2x.png" alt="TinyMCE Logo" width="110" height="97" /></p>`

4- Try to delete the image using VK.DELETE 

Expected result : the image is deleted.

Actual result : the image is not deleting.

**Comment by jayarjo** [comment]
I seem to be able to delete it by Delete and Backspace here: http://codepen.io/anon/pen/GNgvRr.

**Comment by jayarjo** [comment]
@mimrezash so you think this is related: https://github.com/tinymce/tinymce/issues/3279? Although they report a bit different html structure - `img` should follow the block element (`p` in their case). So this definitely fails at the moment: 

```html
<p>text</p>
<img src="https://placehold.it/200x200" />
```

**Comment by pavlopochapsky** [comment]
@jayarjo The codepen you linked to doesn't work in IE11 with Delete key. Backspace works.
I'm using the latest 4.5.2.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
