### ISSUE TITLE
Strips a span that wraps a svg

### ISSUE THREAD

**Issue by svetoslavatanasov** [tinymce/tinymce#3304]
Steps to reproduce:

1) Open HTML editor
2) Insert `<span><svg><use xlink:href="#icon_id"></use></svg></span>`
3) The wrapping span tag is removed: `<svg><use xlink:href="#icon_id"></use></svg>`
4) If you put some text inside the use tag the span is not cleared: `<span><svg><use xlink:href="#icon_id">icon</use></svg></span>`

Is this a bug or intended behavior?

BR

**Comment by svetoslavatanasov** [comment]
Forgot to add the configuration

`
    tinymce.init({
        selector:'textarea.mceEditor',
        theme: 'modern',
        height : 500,
        resize: true,
        document_base_url : http_host,
        relative_urls : true,
        content_css : [
          '//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700,700italic&subset=latin,cyrillic-ext,greek-ext,greek,vietnamese,latin-ext,cyrillic',
          '//fonts.googleapis.com/css?family=Titillium+Web:400,300,600&subset=latin,cyrillic-ext,greek-ext,greek,vietnamese,latin-ext,cyrillic',
          http_host + 'public/styles/front/screen.css',
          http_host + 'public/styles/front/fenster.css',
          http_host + 'public/styles/admin/tiny.css'
        ],
        paste_as_text: true,
        image_advtab: true,
        image_list: image_list,
        image_class_list: [
            {title: 'left',  value: 'left'},
            {title: 'right', value: 'right'}
        ],
        plugins: [
            'advlist autolink lists link image charmap hr anchor pagebreak',
            'searchreplace wordcount visualblocks visualchars code fullscreen',
            'media save table contextmenu directionality',
            'paste textcolor colorpicker textpattern'
        ],
        codemirror: {
            indentOnInit: true,
            fullscreen: true,
            path: 'codemirror-4.8',
            config: {           // CodeMirror config object
                mode: 'application/x-httpd-php',
                lineNumbers: true
            },
            width: 800,
            height: 600
        },
        menubar: 'edit insert view format table',
        toolbar1: 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | forecolor backcolor | code',
        extended_valid_elements : '*[*]',
        init_instance_callback : function() {
            $('#tabber').show();
            $('#tiny_loading').hide();
        }
    });
`

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
