### ISSUE TITLE
Browser spellchecker not activated after enter

### ISSUE THREAD

**Issue by gitsnuit** [tinymce/tinymce#3306]
Tested with 4.4.3 with and without powerpaste 2.1.0.0 / 2.1.7-69
Only reproducible in Firefox (not in Chrome, IE11, Edge)
Tested with Firefox 49.0.2, Ubuntu 16.04
This is not reproducible with a plain text editor. 

Steps;:
1. Type one wrong spelled word and hit ENTER
2. Check if a red line is showing up below the word to indicate spelling is incorrect.

*Result:* No red line showing below the word
*Work around*: If you press space key after any word then it will show red line below that word

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
