### ISSUE TITLE
Inline Mode: Contents can be deleted when editor has no focus

### ISSUE THREAD

**Issue by flack** [tinymce/tinymce#3311]
when a tiny inline instance is enabled, it sets `contenteditable="true"` on the respective DOM node. That means if you select the content without focusing the editor (e.g. with Ctrl-A or by just drawing a rectangle with the mouse), you can delete it (e.g. with the DEL key) without tinymce being active. The problem with that is that in this case, none of tinymce's events is triggered. 

For example, I have a placeholder logic for inline tiny instances that relies to the `blur`, `focus` and `SetContent` events to render/remove a placeholder text for empty areas, but since the content can be removed by normal user interaction without focusing the editor, none of the events are fired.

You can (sort of) see the issue on the tinymce demo page, too:

https://www.tinymce.com/docs/demo/inline/

- move the mouse into the empty space between the black Codepen header and the headline
- hold down the left mouse button and draw a rectangle over the headline text
- press DEL

=> the headline text is now gone, but tinymce's controls were never shown (and thus now `blur`/`focus` events were fired)

**Comment by fyrkant** [comment]
I'm having troubles replicating this with the inline demo on the docs site, could you maybe set up a fiddle showing a better example? http://fiddle.tinymce.com

**Comment by flack** [comment]
Here you go:

http://fiddle.tinymce.com/6Bfaab

I've put the instructions in the description box

**Comment by spocke** [comment]
So I managed to reproduce this in Firefox and it seems to have to do with where the selection is when you use Ctrl+A to select all contents. It then doesn't get focus but events fire on the element where the selection is.

But this seems like a very specific bug that basically only happens if you just have one element that is editable in a document and when there is no other content on the page.

Could you describe your use case for this so we know how to prioritize this currently it doesn't seem like a very common use case normally tinymce is embedded on pages that have other content that just tiny.

**Comment by flack** [comment]
Ctrl-A is just an easy way to reproduce, you can achieve the same effect with mouse selection, if you end your selection outside of tinymce's area.

The use case is that we're building an inline editing frontend to a legacy CMS, which saves page data as an object graph. Each individual page thus consists of a large number of individual content fragments, some of which are editable with tinymce (and each may have a different editor config). So for example, a simple `ul`/`li` list might hold a separate tiny instance for each `li`, so there is a lot of non-active whitespace outside of the editable areas.

The issue was first discovered by a front-line developer doing acceptance tests for a website. He didn't even look for problems with tinymce in particular, but was rather testing removing/adding content, which he did by selecting text with the mouse and deleting it with DEL.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
