### ISSUE TITLE
Link and Code plugins does not work in Firefox 49.0.2 when in BS3 modal. Tiny version 4.4.3 (2016-09-01)

### ISSUE THREAD

**Issue by ghost** [tinymce/tinymce#3315]
**Environment**: MVC 5 with Razor. Cshtml page has a partial page contained within BS3 modal and the partial page contains the textarea. Javascript exists in parent page as script reference.

Snippet of index.cshtml page partial page call:

`@Html.Partial("_categoryeditor", Model)`

_categoryeditor.cshtml contains:

`@Html.TextAreaFor(model => category.Description, htmlAttributes: new { @class = "form-control", @rows = 4, @placeholder = "Describe the category in more detail." })`

The script declaration exists in the index.cshtml page:

```
@section Scripts
{
    <script src="~/Scripts/tinymce/tinymce.js"></script>
}
```

**Extras**: A non-modal page renders either control (link/code) editor as expected. The "disabled" behavior only exists when the editor is displayed after rendering a modal popup. I also experience this issue in Chrome v54.0.2840.71. Hope all this helps...

**PS**: The modal popup editors work fine in IE 11.447

**Comment by Substractive** [comment]
Experienced same bug in firefox 49.0.2 but works on chrome  54.0.2840.98 (64-bit).

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
