### ISSUE TITLE
Deprecation of force_p_newlines option

### ISSUE THREAD

**Issue by NavigateCMS** [tinymce/tinymce#3320]
According to the documentation:

> This option is deprecated as of version 3.5 use forced_root_block: false instead to control p vs br behavior.

But forced_root_block is not quite the same as force_p_newlines.
As the documentation explains:

> This option enables you to make sure that any non block elements or text nodes are wrapped in block elements. 

which is very nice option if you want to have a span out of a paragraph, for example. But disabling the forced_root_block causes that:

> If you set this option to false it will never produce p tags on enter, or, automatically it will instead produce br elements and Shift+Enter will produce a p.

That shouldn't be the case. One thing is to allow non block tags and the other is to disable the creation of new paragraphs on enter. I don't know the internal code, but for the final user, the results are two different situations.

Right now, if you add the two options, TinyMCE works as expected, but if the force_p_newlines is removed, then there will be no way to make the editor create new paragraphs on enter and allow non block tags at the same time.

Our suggestion is to remove the **force_p_newlines** option but create a suboption of **forced_root_block_attrs** that enables creating new paragraphs on enter.

Thank you.

**Comment by CaitlinWeb** [comment]
Haha, this is much more complex than the documentation makes it seem.

I ran into this issue because my project required that users can create links with nested block elements per the HTML5 specification. [As it says](https://www.w3.org/TR/html5/text-level-semantics.html#the-a-element):
> The a element may be wrapped around entire paragraphs, lists, tables, and so forth, even entire sections, so long as there is no interactive content within (e.g. buttons or other links).

I looked everywhere on how to do this and got "we can't do that because". Well, I looked through the source code of tinymce.js and reached a somewhat simple solution. During my journey I found out a few things:
- [forced_root_block](https://www.tinymce.com/docs/configure/content-filtering/#forced_root_block) must be false so the link isn't split up. I don't know fully what effects this has besides allowing text nodes (not within `<p>`), but in my case I can trust my users somewhat (they are web designers).
- Turning off forced_root_block forces the editor to insert `<br>` when hitting `Enter`, for paragraphs you have to hit `Shift+Enter`. Not cool, my users will not understand the shortcuts are reversed.
- It's next to impossible to implement the normal paragraph insertion/splitting as the complex logic is all enclosed within the EnterKey class, which doesn't have mce commands you could override.
- (As an aside: Holy cow, the EnterKey.js class is a disgrace. A 650+ line function called when someone hits enter. It starts with a bunch of closure functions. Following the logic was tough.)
- [force_p_newlines](https://www.tinymce.com/docs/configure/content-filtering/#force_p_newlinesdeprecated), which is what I want, is supposedly deprecated. From the way the documentation reads, you'd think this it is exclusive of forced_root_block.

**However**, looking at the EnterKey class, [I found this](https://github.com/tinymce/tinymce/blob/master/js/tinymce/classes/EnterKey.js#L534):

> `newBlockName = (settings.force_p_newlines ? 'p' : '') || settings.forced_root_block;`

What?? The deprecated setting is the default value? They aren't exclusive of each other!

The logic hinges on that variable [ref 1](https://github.com/tinymce/tinymce/blob/master/js/tinymce/classes/EnterKey.js#L563) [ref 2](https://github.com/tinymce/tinymce/blob/master/js/tinymce/classes/EnterKey.js#L617):

So this is what I did in my settings:
```
...
force_p_newlines: true,
forced_root_block: false,
...
````

Yay! That solved my issue.

As @NavigateCMS says, these two settings represent different wanted behavior, enough to warrant having **both** available, but perhaps in a clearer way. At the very least, **you must update the documentation** to reflect what the actual code is.

**Comment by CaitlinWeb** [comment]
@TinyMCE Worried that this is buried beneath all the other issues. I'm sure I'm not the only one with a use case for mixing the two settings.

I'd really like it if you could separate toggling `forced_root_block` and what element the editor uses for new lines.

**Comment by isherwood** [comment]
Has there been any change in this issue? I'd also like TinyMCE to not toss a paragraph around existing markup, yet use paragraphs by default on [Enter] (and add wrapper paragraphs at that time).

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
