### ISSUE TITLE
Position of Image resize handles wrong when transform:scale() is used to zoom in/out tinymce

### ISSUE THREAD

**Issue by erwin-beckers** [tinymce/tinymce#3321]
I'm trying to integrate tinymce in our application. One of the requirements are that the user can zoom in/out like in word or pages. To make this work i added a transform:scale() to the tiny mce container.
This works fine, except when you want to resize an image. 

As you can see in the screenshot, the resize handles are placed incorrectly due to the transform.
When i set the zoom level to 100% it is offcourse correct
![screenshot](https://cloud.githubusercontent.com/assets/7457725/20257490/3294ccda-aa4a-11e6-9c5d-6fc558ae161b.jpg)

HTML:
` <div id="#mycontainer" style="transform:scale(0.73)" > <img src="..."></div>`

JS:
```
  tinymce.init({
            selector: '#mycontainer',
            toolbar1: 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | fontselect |  fontsizeselect',
            toolbar2: 'bullist numlist outdent indent | link selectImage | forecolor backcolor'
            ...
  });
```

**Comment by erwin-beckers** [comment]
codepen example : http://codepen.io/erwinbeckers/pen/JbKKQr

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.

**Comment by samatcolumn** [comment]
This issue has been affecting us as well, @erwin-beckers has there been a solution? If not @thedrjim can we re-open this?
