### ISSUE TITLE
tinyMCE Floating toolbar not centered above the edit window but left aligned

### ISSUE THREAD

**Issue by erwin-beckers** [tinymce/tinymce#3322]
When the tiny mce text-container is smaller then the width of the floating toolbar then the toolbar is not centered above the edit container . Instead it is left-aligned and causes it to go offscreen:

![2](https://cloud.githubusercontent.com/assets/7457725/20257592/e2ba46a8-aa4a-11e6-9f11-2a07f9659e6b.jpg)

Code used to init tinyMCE :
```

        tinymce.init({
            selector: '#mytextdiv',
            theme: 'modern',
            inline: true,
            schema: 'html5',
            plugins: [
                'advlist autolink lists link image hr anchor pagebreak',
                'searchreplace wordcount visualblocks visualchars code',
                'insertdatetime media nonbreaking table contextmenu directionality',
                'paste textcolor colorpicker textpattern imagetools'
            ],
            toolbar1: 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | fontselect |  fontsizeselect',
            toolbar2: 'bullist numlist outdent indent | link selectImage | forecolor backcolor',
            menu: {
                edit: { title: 'Edit', items: 'undo redo | cut copy paste pastetext | selectall' },
                view: { title: 'View', items: 'visualaid' },
                format: { title: 'Format', items: 'bold italic underline strikethrough superscript subscript | formats | removeformat' },
                table: { title: 'Table', items: 'inserttable tableprops deletetable | cell row column' },
                tools: { title: 'Tools', items: 'spellchecker code' }
            },
            invalid_elements: "script,link",
            invalid_styles: "",
            extended_valid_elements: "p[class|style],style[type]",
            image_advtab: true,
        });

```

**Comment by donShakespeare** [comment]
How did you get the toolbar to float while using `theme: 'modern'`?

**Comment by erwin-beckers** [comment]
by using the ` inline: true` option as shown above

**Comment by erwin-beckers** [comment]
Created a sample codepen : http://codepen.io/erwinbeckers/pen/ENyyrZ

**Comment by fyrkant** [comment]
I am unable to reproduce the bug, the codepen looks like this to me: 

![screen shot 2016-11-18 at 15 21 10](https://cloud.githubusercontent.com/assets/8655649/20433180/d5b78e24-ada2-11e6-9017-57342fc01a1c.png)

**Comment by fyrkant** [comment]
Or maybe I am misunderstanding your problem? How would you want the floating toolbar to act?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
