### ISSUE TITLE
Empty Tag P (Only in Firefox Please read the issue first before giving any reference link)

### ISSUE THREAD

**Issue by ubaidsaeed** [tinymce/tinymce#3323]
I am using the latest version of tinymce 4.4.3 . I am working on asp.net mvc 5 I just simple add content in tinymce editor and save in db (SQL Server)  it is saving correctly like `<p>content</p>` but when i load it again from db it render :

```html
<p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>content</p>
```
my editor config is :

```js
tinymce.init({
        selector: ".tiny-editor-english",
        font_formats: 'Andale Mono=andale mono,times;Arial=arial,helvetica,sans-serif;Arial Black=arial black,avant garde;Book Antiqua=book antiqua,palatino;Comic Sans MS=comic sans ms,sans-serif;Courier New=courier new,courier;Georgia=georgia,palatino;Helvetica=helvetica;Impact=impact,chicago;Symbol=symbol;Tahoma=tahoma,arial,helvetica,sans-serif;Terminal=terminal,monaco;Times New Roman=times new roman,times;Trebuchet MS=trebuchet ms,geneva;Verdana=verdana,geneva;Webdings=webdings;Wingdings=wingdings,zapf dingbats',
        height: 500,
        advlist_bullet_styles: "none,default,circle,disc,square",
        advlist_number_styles: "none,default,lower-alpha,lower-greek,lower-roman,upper-alpha,upper-roman",
        readonly: read_only,
        plugins: [
          "advlist autolink lists charmap hr ",
          "searchreplace visualblocks visualchars nonbreaking",
          "table contextmenu directionality textcolor paste textcolor colorpicker textpattern"
        ],
        toolbar1: " bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | formatselect fontselect fontsizeselect",
        toolbar2: "cut copy paste | searchreplace | bullist numlist | outdent indent blockquote | undo redo | forecolor backcolor",
        menubar: false,
        toolbar_items_size: 'small'
    });
```

**Comment by jayarjo** [comment]
TinyMCE requires `&nbsp;` to be able to let you insert the cursor in those empty tags.

**Comment by jayarjo** [comment]
Make sure that you are not adding additional white-spaces when you put that html back into the textarea.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
