### ISSUE TITLE
contenteditable=false enter/delete issues

### ISSUE THREAD

**Issue by ellatrix** [tinymce/tinymce#3325]
* In Safari, pressing enter either before or after the view won't move the cursor properly or at all.
* In Firefox a border appear around the new paragraph, with the class _moz_abspos="white". It disappear when clicking somewhere else. If you press enter multiple times though, it stays.
* In all browsers deleting the previous empty line from before the view doesn't work.

Cross posting from https://core.trac.wordpress.org/ticket/38757.

**Comment by spocke** [comment]
We fixed the safari enter bug and the _moz_abspos="white". We started working on the delete bug but wasn't able to merge that in for 4.5.0 so keeping this open until we fix that.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
