### ISSUE TITLE
TinyMCE 4 issue with Arabic language in Chrome browser

### ISSUE THREAD

**Issue by Msaad-des** [tinymce/tinymce#3327]
When i try to edit a letter by selecting it and type the right letter
The new letter appears separated

That happen with TinyMCE 4 editor only in Chrome
I found that Chrome's inspector also appears it separated as the picture.

That does not happen with TinyMCE 3
Any suggestion for that issue ?

![tinymce-issue](https://cloud.githubusercontent.com/assets/23494330/20337529/52478dc4-abda-11e6-948e-d1165630795e.jpg)

**Comment by spocke** [comment]
Not knowing to much about arabic but does that text node splitting cause issues with text rendering?

I think this has to do with a fix in chrome we have we could merge the text nodes if needed. But if it doesn't cause an issue to end users maybe we don't need to?

**Comment by Msaad-des** [comment]
It doesn't cause an issue after save, but it is an issue for the editors when typing, for spell check and review.

i tried some edits to solve it as:
`setup: function (editor) {
    editor.on('NodeChange', function (plo, o) {
        // Stores a bookmark of the current selection
        var bm = tinyMCE.activeEditor.selection.getBookmark(2, true);

        // Re render the content
        tinyx = tinyMCE.activeEditor.getContent();
        tinyMCE.activeEditor.setContent(tinyx);

        // Restore the selection bookmark
        tinyMCE.activeEditor.selection.moveToBookmark(bm);
    });
},`
But it cause an issue when selecting and edit large text
Is there another way to try to merge the text nodes?

**Comment by spocke** [comment]
So to clarify this is not a Arabic specific issue but rather a general text node splitting isuse?

**Comment by Msaad-des** [comment]
Yes it cause with any language in Chrome, but the problem appear mainly with the language that has connected letters as Arabic.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
