### ISSUE TITLE
Single space editor content

### ISSUE THREAD

**Issue by petko** [tinymce/tinymce#3331]
The View Source command shows empty source code for both no content and single-space content in TinyMCE. Is this by design? Is it possible to detect somehow if the editor has absolutely no content or a single space in it?

P.S.: I understand that you may be wondering why I need to preserve single space content, but it is a good thing from UX point of view to preserve everything the user types, even something this small..

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
