### ISSUE TITLE
Links on windows os

### ISSUE THREAD

**Issue by teutdelinotte** [tinymce/tinymce#3334]
There is a problem on link editing if the word is after another link or beginning line setence's.

The issue is reproduced on https://www.tinymce.com/docs/demo/full-featured/ in a navigator ie11

**Comment by fyrkant** [comment]
Hi! 

Can you describe in more detail what kind of problem you have with editing the links? And maybe try to reproduce the problem in a [fiddle](http://fiddle.tinymce.com/)?

**Comment by teutdelinotte** [comment]
Hi !
Yes you can test here :
http://fiddle.tinymce.com/iCfaab

Look the fiddle description's

**Comment by fyrkant** [comment]
Thank you!

**Comment by teutdelinotte** [comment]
Cheers

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
