### ISSUE TITLE
attach click event listener to font select

### ISSUE THREAD

**Issue by mscreenie** [tinymce/tinymce#3346]
I've been looking through and cannot find anywhere to perform it, closest I got was an old stackoverflow post but looks like the api has changed quite a bit since.

I'm trying to attach a hover, or click event to the font selector or font size selector. Here is what I have but I'm probably a long way off:

```
 setup: function (editor) {
    editor.editorManager.get('fontselect').on('click', function (e) {
      alert(2);
     });
 }
```
I get an error saying "on" is not a valid method.

I'd realyl appreciate if someone could help me

**Comment by fyrkant** [comment]
I'm unsure if there is any built in method of attaching an event listener to a toolbar button, but you could just do it with a `document.querySelector` and the `aria-label`, like this: 

```js
tinymce.init({
    selector: "textarea",
    plugins: [
        "advlist autolink lists link image charmap print preview anchor",
        "searchreplace visualblocks code fullscreen",
        "insertdatetime media table contextmenu paste"
    ],
    toolbar: "insertfile undo redo | styleselect fontselect | bold italic |" +
                  " alignleft aligncenter alignright alignjustify | bullist numlist " +
                  "outdent indent | link image"
}).then(function (editor) {
    var fontButton = window.document.querySelector('[aria-label="Font Family"] > button');

    fontButton.addEventListener('click', function (e) {
        console.log('clicked')
    })
});
```

Notice that you have to add the event listener after the editor has initialized, otherwise there is no button to attach the listener to. 

See live version [here](http://fiddle.tinymce.com/FCfaab).

**Comment by mscreenie** [comment]
Thanks, I tried this with inline method but it seems the panel is not initialized until it is rendered by selecting text. The solution only works when inline is false.

Here is a modified fiddle: http://fiddle.tinymce.com/FCfaab/1

I've tried attaching a event to 

`
editor.theme.panel.$el.
`
inside 

```
                        editor.on('ExecCommand', function (e) {
editor.theme.panel.$el.
                        });

```

It seems some items inside tinymce are not exposed or accessible easily.

**Comment by fyrkant** [comment]
Hmm, I'm not sure if there is an event for when the toolbar is rendered (@spocke might know?) but either way that seems like a pretty unstable way to get that functionality, you are probably better off by going all in and implementing your own version of the fontselect menu.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
