### ISSUE TITLE
its not possible to edit the first Letter in a span-block

### ISSUE THREAD

**Issue by dev0xFF** [tinymce/tinymce#3352]
If I edit this document:
<div>
Text before <span style="border: solid 1px #f00">Block text</span> text after
</div>

its not possible to edit the first Letter in a span-block. If the cursor is at the 0th position of the block the element before will be edited. If I navigate with the arrow-keys from outside into the block, the cursor will be hidden at the 0th postion  and I can only edit the elements outside the block. But it works correctly at the first and the following letters.

**Comment by fyrkant** [comment]
Hi! Can you recreate the problem in a [fiddle](http://fiddle.tinymce.com/)?

**Comment by dev0xFF** [comment]
Yes, [hier](http://fiddle.tinymce.com/LCfaab)

**Comment by fyrkant** [comment]
Thank you!

**Comment by Daijobou** [comment]
Here a other example http://fiddle.tinymce.com/rDfaab

Its not possible to edit first letter from "text" or insert new characters before it.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
