### ISSUE TITLE
Error "Permission denied" when table lost focus in Edge

### ISSUE THREAD

**Issue by mesche** [tinymce/tinymce#3356]
**Description of problem**
Error "Permission denied" when a table lost the focus in Edge

Tested with: tinyMCE 4.5.0 (2016-11-23)
Issue on: Edge

**Steps to reproduce**
Fiddle: http://fiddle.tinymce.com/VCfaab

1. run code
2. place cursor into table cell "a"
3. press "Close & Reinit Editor" button
4. place cursor into table cell "b"
5. press "Close & Reinit Editor" button
6. click beside the table to select the whole table
7. try to set cursor below the table with a click

hint: I haven't found an easier way to reproduce the error reliable

**Expected result**
Cursor is below the table

**Actual result**
JS Error:  Permission denied  tinymce.js (2231,5)

**Comment by Knarzbob** [comment]
I've encountered the same problem with the latest version (4.6.5). Any news on this?

**Comment by spocke** [comment]
I have a hard time reproducing this issue any more details to this?

**Comment by mesche** [comment]
Attached a pdf that explains the steps pictorially to reproduce the issue.

[issue-3356-steps-to-reproduce.pdf](https://github.com/tinymce/tinymce/files/1245729/issue-3356-steps-to-reproduce.pdf)

**Note: The error only occurs in the MS Edge browser!!**

**Comment by spocke** [comment]
Thanks that made it simple to reproduce.

**Comment by mesche** [comment]
Are there any news?

**Comment by mesche** [comment]
Is it foreseeable, if and when the problem can be solved?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.

**Comment by de-dan** [comment]
But is it fixed?

**Comment by thedrjim** [comment]
We've tested this using TinyMCE 5.5.1 and we were unable to reproduce the error on Legacy Edge. Additionally, Legacy Edge is no longer a supported browser, as per https://www.tiny.cloud/docs/general-configuration-guide/system-requirements/#supportedwebbrowsers
