### ISSUE TITLE
Font-family and font-size removed after performing a spellcheck

### ISSUE THREAD

**Issue by gitsnuit** [tinymce/tinymce#3362]
Repro in 4.4.3 with an without power paste 2.1.7 (Chrome only)

1. Select bold and type one wrong word and press space bar.
2. Right click on that word and use spellcheck to choose the correct word.  
3. Check word's font family and size
Result: Value of font-family and font-size is not showing in drop down but format is still set
4. Click next to the word and type few words 
5. Check value of font family drop down
Result: Font-family value is not set, but font-size is set again.

**Comment by spocke** [comment]
Is this with the browser built in spellchecker? We have no control over that and it's known to be buggy.

**Comment by MartyBum** [comment]
@spocke Yes.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
