### ISSUE TITLE
It is not possible to manually set title attribute of iframe

### ISSUE THREAD

**Issue by stenman** [tinymce/tinymce#3365]
Maybe it should be possible to set the title attribute of the iframe element?

Today the title is set in the init method, like so:
```
				title: self.editorManager.translate(
						"Rich Text Area. Press ALT-F9 for menu. " +
						"Press ALT-F10 for toolbar. Press ALT-0 for help"
				),
```
I don't know _when_ this is done, so I couldn't for example remove it by simply calling `document.getElementById('mytextarea_ifr').removeAttribute('title');`

If it was possible to "manually" set the title attribute (override the translate method) in the init script, this would be a lot more convenient.

**My specific case** is that JxBrowserWebbrowser (Chromium) shows this tooltip when using the vertical scrollpane in the editor. Setting the title to empty would solve the problem in my case.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
