### ISSUE TITLE
toolbar not rendering on inlite theme when selecteing text and mouseup outside the selector

### ISSUE THREAD

**Issue by EmilioIkemiya** [tinymce/tinymce#3366]
When using tinymce with inlite theme, if mouseup is done outside the selector (tetarea, div or whatever was the selector set in the tinymce.init) when selecting a text, the toolbar is not shown.
The bug can be reproduced in this page https://www.tinymce.com/docs/demo/inlite/

**Comment by EmilioIkemiya** [comment]
One way (not pretty, but works) to fix this:
Change some lines in the theme.min.js (of inlite)
o = function(a, b) {
                var c, d, e;
                d = l(a);
                e = k.fromContextToolbars(b);
                **if(a.id != jQuery(document.getSelection().anchorNode).parents('.editable').attr('id')) {
                    return null;
                }**
                c = h.match(a, [g.element(d[0], e), f.textSelection("text"), f.emptyTextBlock(d, "insert"), g.parent(d, e)]);
                return c && c.rect ? c : null;
            },

.....
r = function(a, c) {
                var d = b.throttle(p(a, c), 0),
                    e = b.throttle(q(c, p(a, c)), 0);
                a.on("blur hide ObjectResizeStart", c.hide), a.on("click", d), **jQuery(document).on("mouseup", e), a.on("mouseup", e),** a.on("ResizeEditor ResizeWindow keyup", d), a.on("remove", c.remove), a.shortcuts.add("Alt+F10", "", c.focus)
            },

**Comment by EmilioIkemiya** [comment]
This bug can be fixed  (not a pretty way, but works) changing some lines in theme.min.js (of inlite).
...
...
o = function(a, b) {
                var c, d, e;
                d = l(a);
                e = k.fromContextToolbars(b);
                **_if(a.id != jQuery(document.getSelection().anchorNode).parents(a.settings.selector).attr('id')) {
                    return null;
                }_**
                c = h.match(a, [g.element(d[0], e), f.textSelection("text"), f.emptyTextBlock(d, "insert"), g.parent(d, e)]);
                return c && c.rect ? c : null;
            },
...
...
r = function(a, c) {
                var d = b.throttle(p(a, c), 0),
                    e = b.throttle(q(c, p(a, c)), 0);
                a.on("blur hide ObjectResizeStart", c.hide), a.on("click", d), **_jQuery(document).on("mouseup", e), a.on("nodeChange mouseup", e),_** a.on("ResizeEditor ResizeWindow keyup", d), a.on("remove", c.remove), a.shortcuts.add("Alt+F10", "", c.focus)
            },
...
...

**Comment by tonyChenHey** [comment]
Why didn't I find the method fromContextToolbars?
How can I find where to add these codes?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
