### ISSUE TITLE
eslint config

### ISSUE THREAD

**Issue by catalinux** [tinymce/tinymce#3373]
My IDE complains about `		"comma-dangle": ["error", "never"],` . Shouldn't be?

		"comma-dangle": [1, "never"],

**Comment by fyrkant** [comment]
You can use both  `0`, `1`, `2` or `"off"`, `"warn"`, `"error"`.  See the [eslint documentation](http://eslint.org/docs/user-guide/configuring#configuring-rules).

So there is nothing wrong with our `.eslintrc` file although we should probably change it so it's consistent and only uses the words instead of a mix of the numbers and words. Might be a good PR if you feel like it!

**Comment by fyrkant** [comment]
Closing this as it isn't really an issue with TinyMCE.

**Comment by catalinux** [comment]
Ok. Tx. I had some issues with that eslint and I just wanted to know which was the right reproach. Tx
