### ISSUE TITLE
Using codesample and force_root_block: '' will add special character in code

### ISSUE THREAD

**Issue by thomich** [tinymce/tinymce#3382]
Using TinyMCE 4.5.1 and codesample plugin.

1. set force_root_block: ''

2. add min. one `<br />` into editor

2. add code sample in codesample editor
![selection_004](https://cloud.githubusercontent.com/assets/4398840/21013247/a4a0963e-bd59-11e6-8c6b-b97f646f6bac.png)

3. right after adding code sample, open code editor
![selection_005](https://cloud.githubusercontent.com/assets/4398840/21013341/f9ed89da-bd59-11e6-8b5f-ccaceaa35184.png)

Checking same code with external editor (copy&paste) and watch/analyse current column:
![selection_006](https://cloud.githubusercontent.com/assets/4398840/21013413/4b411b1c-bd5a-11e6-9193-e0eef04266c2.png)
![selection_007](https://cloud.githubusercontent.com/assets/4398840/21013418/4e4eb4cc-bd5a-11e6-8842-76700a087689.png)

As i also use codemirror plugin (https://github.com/christiaan/tinymce-codemirror) i recognized it also there:
![selection_008](https://cloud.githubusercontent.com/assets/4398840/21014518/b186546a-bd5e-11e6-86f8-d422576ade81.png)

If anything else needed, let me know.

Regards
thomi

**Comment by thomich** [comment]
btw. you can reproduce it on that fiddle: http://fiddle.tinymce.com/CCfaab/5

**Comment by fyrkant** [comment]
Does it work correctly if you set `forced_root_block` to `false` instead of an empty string?

**Comment by thomich** [comment]
no :(
you can check it by testing with this fiddle http://fiddle.tinymce.com/CCfaab/6

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
