### ISSUE TITLE
On iOS, tapping the down arrow in a form skips the TinyMCE textarea

### ISSUE THREAD

**Issue by aguynamedben** [tinymce/tinymce#3384]
On the built-in iOS keyboard, there is an up arrow and a down arrow that allows people to navigate between form elements, similar to hitting TAB on a regular keyboard. TinyMCE is skipped when using these arrows.

Example form:
1. text input
2. textarea with TinyMCE
3. text input

If the focus is on element 1. in the form, and the iOS user hits the down arrow, the focus is put on input 3. The TinyMCE-enabled field is skipped.

Here's a JSFiddle you can use from iOS to replicate:
https://jsfiddle.net/u7u90mcb/1/

Here's a video:
https://drive.google.com/open?id=0B7zBbg9UsqkxSk1IZXMxQU9aWDQ

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
