### ISSUE TITLE
On iOS, cursor gets confused when tapping between traditional inputs and TinyMCE

### ISSUE THREAD

**Issue by aguynamedben** [tinymce/tinymce#3385]
With a form like this:
1. text input
2. textarea with TinyMCE
3. text input

Click into the TinyMCE textarea. Then click into the first text input. Continue to click between TinyMCE and the first text input. Soon, the cursor will get weirdly split between the first form element and TinyMCE. This makes TinyMCE pretty unusuable on iOS. Users can't reliably tap between normal inputs and TinyMCE. Sometimes, taps just do nothing. Other times, taps set the cursor to an unexpected place.

I noticed this first in my app, but was able to easily reproduce with this JSFiddle: https://jsfiddle.net/u7u90mcb/1/

Here's a video: https://drive.google.com/open?id=0B7zBbg9UsqkxcHR1VVF1bVUtd3M

**Comment by aguynamedben** [comment]
I think this might be related or similar to #2699, but I'm not sure.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
