### ISSUE TITLE
autoresize_min_height ignored on mobile

### ISSUE THREAD

**Issue by aguynamedben** [tinymce/tinymce#3386]
When using the autoresize plugin like this:

```js
tinymce.init({
  selector:'textarea',
  menubar: false,
  statusbar: false,
  toolbar: "bold italic underline bullist link code",

  plugins: 'autoresize',
  autoresize_min_height: 30,
  autoresize_max_height: 300,
  autoresize_bottom_margin: 0,
  autoresize_overflow_padding: 0,
});
```

The `autoresize_min_height` is respected on desktop web:
![a_pen_by_ben_standefer](https://cloud.githubusercontent.com/assets/107841/21060905/c28164d0-bdfe-11e6-847c-75a4b4b3e359.png)

But on mobile the `autoresize_min_height` seems to be ignored (or limited) on mobile:
![file_000](https://cloud.githubusercontent.com/assets/107841/21060994/3789a116-bdff-11e6-9205-391b635e3f32.png)

Compare the space after the initial line of text on desktop vs. mobile. It seems that the TinyMCE box can't go below a certain size on mobile. Using iOS/Chrome.

**Comment by aguynamedben** [comment]
Here's a codepen: http://codepen.io/aguynamedben/pen/ENpZbQ Compare the full page view on mobile web vs. desktop web.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
