### ISSUE TITLE
Executing Ctrl-A, Ctrl-C, Ctrl-V consecutively would throw away all webkit styles

### ISSUE THREAD

**Issue by JasonMrX** [tinymce/tinymce#3387]
**Can be reproduced here:**
http://fiddle.tinymce.com/1qfaab/4

**Steps to reproduce**
1. Select all text
2. Change text color to something else other than default (e.g. red)
3. Ctrl-A, Ctrl-C, Ctrl-V

**Expected**
text color would still be red

**Observed**
text color changed back to default

**Note**
Please do not do anything else between Ctrl-C and Ctrl-V. This is essential to reproduce this bug.

**Initial investigation:**
In here https://github.com/tinymce/tinymce/blob/5da2b31ad84c90379ac158d7649e092b52d2a06d/js/tinymce/plugins/paste/classes/Clipboard.js#L54
the webkit styles of the clipboard content are all removed because they are the same as the selected text.
However, in here https://github.com/tinymce/tinymce/blob/e5019b456b60935f8be25400e0c31bdf34583eb5/js/tinymce/classes/InsertContent.js#L253
the selected text (including the webkit styles) is deleted before the content on clipboard is pasted. 
This results in no webkit styles at all.

Thanks and regards,

Jason

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
