### ISSUE TITLE
Problem with relative URLs linking when anchor routing is used

### ISSUE THREAD

**Issue by laurybueno** [tinymce/tinymce#3393]
Hi guys,

I have experienced the following situation that may (ou may not) be a bug on TInyMCE relative link handling. 

By the way, I'm using AngularUI wrapper for TinyMCE.

Steps to reproduce:

1. Be in a URL that uses Angular 1.5 native routing (`http://localhost:8000/discussion/topic/#!/topic/2518/`)

2. Try to link to `http://localhost:8000/discussion/topic/#!/topic/2514/`

3. Resulting link proposed by TinyMCE turns into `../#!/topic/2514/`. Unfortunately, this resolves to `http://localhost:8000/discussion/#!/topic/2514/`, which is incorrect

![screenshot from 2016-12-13 11-45-32](https://cloud.githubusercontent.com/assets/1108897/21142713/a3602eb8-c12a-11e6-8dc7-4dfad53036d2.png)

This is the configuration for TinyMCE that I'm using

```js
    app.value('uiTinymceConfig', {
        base_url: '/static/tinymce-dist/',
        related_url: true,
        inline: false,
        menubar: false,
        statusbar: false,
        plugins : 'advlist lists autolink link image media',
        toolbar: 'bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | quicklink link image media fullscreen',
        skin: 'lightgray',
        theme : 'modern',
        language: 'pt_BR',
        language_url : '/static/vendor/tinymce/langs/pt_BR.js',
    })
```

Naturally, the problem goes away when i set `relative_urls: false`.

Thanks for your time!

**Comment by crustamet** [comment]
YES, it goes away because you misspelled relative_urls from your source code
related_url: true

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
