### ISSUE TITLE
Style Merging to false issue

### ISSUE THREAD

**Issue by venkatbaggu** [tinymce/tinymce#3407]
We are using custom formats, The problem here is First we are selecting the Formats-->Block-->BlueBlock

and entering some text and then we are selecting another format Formats-->Block-->GreenBlock

The output is generated as single div block instead of two divs. How to generate separate divs

Sample Code

http://codepen.io/madan535/pen/rWPdaq

**Comment by venkatbaggu** [comment]
any help?

**Comment by fyrkant** [comment]
I am not sure I understand the problem, but I believe that is how it is supposed to work. With a `block` custom style it will be added on the block. The `style_merge_false` only works on inline stuff, I think.

**Comment by venkatbaggu** [comment]
Please look at these below images
Image 1:
[http://i.imgur.com/YEXQTBP.png](url)
Image 2
[http://i.imgur.com/k0mhIWH.png](url)
 Currently, i am getting the output as it was on the image 1. But I need to get the output as it was on image 2. Do I miss any configuration?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
