### ISSUE TITLE
Insert toolbar on the left side, misplacing mce-arrow-left with mce-arrow-right

### ISSUE THREAD

**Issue by fgaeg** [tinymce/tinymce#3408]
On [line 95 from Panel.js](https://github.com/tinymce/tinymce/blob/master/js/tinymce/themes/inlite/src/main/js/tinymce/inlite/ui/Panel.js#L95) arrow left is true when that should be false and the right arrow should be true. So when the insert toolbar placed on the left side with right arrow, it doesn't trigger left arrow to be displayed (because we do have right arrow to be placed on the right side from toolbar container).

This issue seems to be relevan within this [line 56 from Layout.js](https://github.com/tinymce/tinymce/blob/master/js/tinymce/themes/inlite/src/main/js/tinymce/inlite/core/Layout.js#L56), when you trying to change `['cr-cl', 'cl-cr']` into `['cl-cr', 'cr-cl']` that's when the left arrow showed up with right arrow.

I'm sure this is not intended ui behaviour, please fix this. Thanks!

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
