### ISSUE TITLE
shift + enter leaves dangling <br> in some cases

### ISSUE THREAD

**Issue by albinohrn** [tinymce/tinymce#3410]
We've experienced some problems with a dangling `<br/>` after hitting *shift* + *enter* when last in a block. It works well when you're continuing to type after hitting *shift* + *enter* but if you change your mind and hit *backspace* you're left with a `<br/>` that is very hard to get rid of.

Steps to reproduce:

1. Open this [codepen](http://codepen.io/albinohrn/pen/JbzKpP)
2. Put cursor last
3. Hit <kbd>shift</kbd> + <kbd>enter</kbd>
4. Hit <kbd>backspace</kbd>

Expected markup:
```html
<h2 class="editable">Editable header</h2>
```

Actual markup
```html
<h2 class="editable">Editable header<br/></h2>
```

Have tried both Firefox and and Chrome

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
