### ISSUE TITLE
Toolbar styles are overridden with page styles

### ISSUE THREAD

**Issue by reddyagile** [tinymce/tinymce#3414]
When tinymce editor is configured with or without inline mode, the page styles are inherited to tinymce toolbar and UI is disturbed as shown here https://i.snag.gy/KLUtaV.jpg 

Is there any solution to avoid this css/styles conflicts ?

Demo jsfiddle : https://jsfiddle.net/fc7hgzyt/

**Comment by fyrkant** [comment]
This is not a bug but wanted behaviour and can be configured with the [preview_styles](https://www.tinymce.com/docs/configure/editor-appearance/#preview_styles) setting. You can remove the font-size like this: http://fiddle.tinymce.com/IFfaab

Although creating that fiddle I realized there is a bug with the alignment part of the menu, it doesn't seem to respect the preview_styles setting and previews the font-size any way... But not for the centered menu option? Weird, adding this to our internal bug tracker!

**Comment by fyrkant** [comment]
It seems to work to disable the preview_styles fully like this: http://fiddle.tinymce.com/IFfaab/1

**Comment by reddyagile** [comment]
It worked, Thanks.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
