### ISSUE TITLE
Operations on selected text does not work correctly when starting on an end tag

### ISSUE THREAD

**Issue by stenman** [tinymce/tinymce#3419]
I think it's easiest explained by simply recreating it.

How to recreate:
* Simply go to the [TinyMce demo site](https://www.tinymce.com/docs/demo/full-featured/) and select text **from _the end of_** "... Please try out the features provided in this full featured example." (ie. right after the punctuation) **to** however many characters you wish _forward_ in the text. 
* Press crtl+b or click the 'bold' button.
* Press it again...
* The text will still be bold

**Comment by fyrkant** [comment]
I verified this bug in this fiddle: http://fiddle.tinymce.com/bGfaab

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
