### ISSUE TITLE
Editor will be part of the HTML source code Pt into Px, I would like to ask how not to do so

### ISSUE THREAD

**Issue by insflow** [tinymce/tinymce#3423]
Editor will be part of the HTML source code Pt into Px, I would like to ask how not to do so.
example:
source :  style="width: 538pt;

result: style="width: 538px;

**Comment by spocke** [comment]
Not sure I follow when does it produce pt instead of px when you resize things?

**Comment by Luke-SF** [comment]
I believe I started a similar bug at some point, basically asking why "pt" is used in instead of px for font-size, is there a technical reason TinyMCE favors pt?

**Comment by Luke-SF** [comment]
If you look at your https://www.tiny.cloud/docs/demo/full-featured/ you can see while clicking around the example content, nearly all paragraph values in the font picker are "px" until you click the dropdown and select anything. It is very confusing if a user were to change this bigger, then smaller, and see that a title that is "24"pt is about equal to a 30px set heading below. What is the technical reason that TinyMCE has always favored "pt"?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
