### ISSUE TITLE
TypeScript declaration file

### ISSUE THREAD

**Issue by martinduparc** [tinymce/tinymce#3427]
Are there plans to add a TinyMCE declaration file for TypeScript? It is now [recommended](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) that the file gets bundled with the npm package instead of getting added to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). I can provide a declaration file. It's still a WIP but could get things started.

**Comment by chodorowicz** [comment]
Any news on that? Types on `@types/tinymce` are quite outdated.

**Comment by TheSpyder** [comment]
The TinyMCE codebase has been converted to TypeScript but we haven't defined types in a lot of places yet. This is a high priority for us and is scheduled for shortly after the 5.0 release.

**Comment by jkuchar** [comment]
@TheSpyder any updates?

**Comment by TheSpyder** [comment]
We have added types to the API source code but we aren’t sure how to deliver them yet.

TinyMCE ships as a bundle but the API types are spread across the codebase. Shipping a single .d.ts file from this will be harder than we thought.

**Comment by jdus** [comment]
But the general idea is, to write custom plugins in Typescript as well, right?

**Comment by TheSpyder** [comment]
Correct. We have this problem in our premium plugins too; they're developed in TypeScript but can't leverage any of the work we've done to add types to TinyMCE core.

**Comment by jdus** [comment]
All right, thanks for the information @TheSpyder. We have decided to migrate all our custom plugins to version 5, but weren't sure how to go about it, when we couldn't find a declaration file. Maybe we can come up with our own declarations for the modules we really need.

**Comment by jkuchar** [comment]
Maybe this can help you. https://moduscreate.com/blog/publishing-typescript-modules-npm/

**Comment by TheSpyder** [comment]
@jkuchar not really, sorry. We do have source libraries that publish their TypeScript modules to NPM, in a similar style to that, the problem is the TinyMCE package doesn't publish source modules. We bundle with rollup before publishing.

We need to investigate whether we can somehow publish the source `.d.ts` files alongside a rollup bundle or whether we'd need to bundle them together (if that's even possible).

**Comment by jdus** [comment]
Is anybody using it's own definitions file here and maybe give some insights? We are trying to roll our own step by step based on a simple plugin with few dependencies, e.g. only referencing 'PluginManager', but nothing else. We get to the point of no warnings during build, but then receive errors at runtime. I feel like where are declaring something wrong here.

**Comment by TheSpyder** [comment]
@jdus can you post an example of the issues you're seeing? I can definitely help point out issues in custom definition files.

**Comment by jdus** [comment]
For example 'Tools', which isn't used as type directly. How do I declare it, like this?

`declare module 'tinymce/core/api/util/Tools' {
    interface Tools {
        trim(str: string): string;
        ...
    }
    const Tools: Tools
    export default Tools
}`

I'm not sure what to declare as a module or namespace and about how the 'format' setting in tsconfig plays into this.

**Comment by TheSpyder** [comment]
@jdus sorry for not responding earlier, my inbox was a bit overloaded in mid August and I forgot about this.

`declare` is what you need, but `tinymce/core/api/util/Tools` is a typescript namespace reference that won't work against the compiled editor. For external use, the reference to `Tools` is:

```
declare const tinymce: any;
interface Tools {
    trim(str: string): string;
}
const Tools: Tools = tinymce.util.Tools;
```

**Comment by jkuchar** [comment]
So is there any way one can build TinyMCE plugin in TypeScript? Could I use GitHub repo somehow? This is blocker, as anyone who is using typechecking in project cannot use current TinyMCE version.

**Comment by TheSpyder** [comment]
Inside the github repo - or using the dev download, which is a snapshot of the repo - full types are available (look at all of the community plugins). We just aren't sure how to publish the types in a way that works with the compiled `tinymce.js` bundle.

I know this is a pain point. Sorry. Hopefully the team can find time to work on this soon, we've all been busy preparing a mobile-focused release to coincide with iOS 13.

**Comment by jdus** [comment]
> @jdus sorry for not responding earlier, my inbox was a bit overloaded in mid August and I forgot about this.
> 
> `declare` is what you need, but `tinymce/core/api/util/Tools` is a typescript namespace reference that won't work against the compiled editor. For external use, the reference to `Tools` is:
> 
> ```
> declare const tinymce: any;
> interface Tools {
>     trim(str: string): string;
> }
> const Tools: Tools = tinymce.util.Tools;
> ```

Thanks @TheSpyder. I haven't had time myself yet. Thanks for the head's up, I'm sure I will figure it out :)
@jkuchar: I will let you know, if I can make it work.

**Comment by jkuchar** [comment]
@jdus @TheSpyder Thank you guys! 🙂 And good luck with mobile-focused iOS 13 version!

**Comment by Fiorello** [comment]
> Inside the github repo - or using the dev download, which is a snapshot of the repo - full types are available (look at all of the community plugins). We just aren't sure how to publish the types in a way that works with the compiled `tinymce.js` bundle.
> 
> I know this is a pain point. Sorry. Hopefully the team can find time to work on this soon, we've all been busy preparing a mobile-focused release to coincide with iOS 13.

You could add the declaration parameter to your _tsconfig_ so that users using tinymce from _node_modules_ can easily use typing.

**Comment by TheSpyder** [comment]
We build TinyMCE with [both declaration and declarationMap](https://github.com/tinymce/tinymce/blob/master/tsconfig.shared.json#L8-L9), that's not the problem.

We bundle tinymce as a single JS file but in the source code the types are spread across many _many_ files. This poses two questions:

- if we create a `tinymce.d.ts` for the bundle, can it import the `.d.ts` files it was built from or do they need to be bundled into one file as well?
- if we can ship multiple `.d.ts` files, which ones do we need? I hope not all of them?

These are the questions we haven't had time to investigate yet.

**Comment by Fiorello** [comment]
I'm sorry I didn't notice `tsconfig.shared`, in any case installing tinymce from npm I can't find the `.d.ts` files.
![Screenshot 2019-09-19 at 16 11 41](https://user-images.githubusercontent.com/3278942/65251752-2fc9a700-daf8-11e9-9483-ec9a6a238d9d.jpg)

I'm not an expert of module declarations but this is my thought.

1) I think is possibile, you can import `.d.ts`file from other.
2) I think you need all the files in your module. 
You could create a folder `@types` inside tinymce module with all `.d.ts` files.

**Comment by TheSpyder** [comment]
Correct, we don't distribute them now because there's no way to use them. There are 1927 `.d.ts` files in a TinyMCE build (not including demo and test files) so it would be nice if we could avoid shipping them all.

I just took a quick look and the TinyMCE core `.d.ts` files that refer to other projects (TinyMCE is a monorepo now) still import them by the public name, so that's not going to work unless we add those other projects as source dependencies to TinyMCE on NPM. Which we don't want to do.

There's also the problem of TypeScript aliases; the `.d.ts` files still contain lines like `import Editor from 'tinymce/core/api/Editor';` which won't resolve in your project unless _you_ define the path `tinymce/core/api/Editor`.

It's a _really_ hard problem.

**Comment by werddomain** [comment]
Any update? i have to use 4.5 to be able to use it  :(

**Comment by Schleuse** [comment]
I think I've found a way to make it somewhat working for the time being.
I am using `@types/tinymce` and `@ephox/bridge` and combine those in a `.d.ts` in my project:

`/src/@types/tinymce.d.ts`:
```typescript
import { Registry } from "@ephox/bridge"

declare module 'tinymce' {
	interface Editor {
		ui: {
			registry: Registry.Registry
		}
	}
}
```

**Comment by jkuchar** [comment]
@TheSpyder Any updates on this? We still cannot update to 5.x versions because there are no type definitions at all available for TinyMCE users. This basically means that any project written in TypeScript is not able to use TinyMCE.

If it is not easy to ship types inside npm package, why not ship it separately as it was with `@types/tinymce`? I would prefer to have much slower build and having more peer dependencies then having no type definitions at all. Having 2k `.d.ts` files more is nobrainer for me I we can then typecheck our code against TinyMCE sources.

**Comment by TheSpyder** [comment]
@jkuchar I'm not working on the core editor at the moment, I'll pass this on to the team to see if we have an update

**Comment by mytskine** [comment]
I could produce a type declaration file for TinyMCE 5 using Microsoft's [api-extractor](https://api-extractor.com/) tool. The process was rather simple:
1. Create `modules/tinymce/src/core/main/ts/api/index.ts` which exports all the useful imports, e.g. `export * from './AddOnManager';`
2. `yarn build` to create the `*.d.ts` files
3. Install and init api-extractor. Configure `"projectFolder": "modules/tinymce"`,  `"mainEntryPointFilePath": "<projectFolder>/lib/core/main/ts/api/index.d.ts"` and `"reportFolder": "<projectFolder>/"`
4. Run api-extractor. It produces a ".d.ts" file in `dist/`

api-extractor cannot handle `* as X` imports, so I had to patch 3 typescript files in order to convert them into plain `{ A, B }` imports.

I hope that helps. I tried several other ways to produce these declarations but failed. This declaration file was successfully loaded in another project (a tinymce plugin which is not public).

**Comment by TheSpyder** [comment]
Interesting, it makes sense that Microsoft would have a tool for this. Thanks for the tip, hopefully we can use that to make an automated process!

**Comment by lnewson** [comment]
We've just merged the change for this, so as of TinyMCE 5.5 we'll now include a TypeScript declaration file. I unfortunately don't have a definitive timeframe for when 5.5 will be released, however given we've just released 5.4 it'll probably be a couple of months away. I'll update this again when TinyMCE 5.5 has been released for use.

**Comment by lnewson** [comment]
I should add, if anyone wants to test the new declaration file before then, they can generate the .d.ts file by building from the source: https://github.com/tinymce/tinymce/blob/develop/CONTRIBUTING.md#getting-started

**Comment by lnewson** [comment]
Hi all, just as a final update to this TinyMCE 5.5.0 was released to the community earlier today. Please let us know if you have any further issues with the new declaration file.

**Comment by dakur** [comment]
Thank you very much for your effort, it's great!

**Comment by musaffar-patel** [comment]
Would be grateful if someone would kindly provide a step by step guide to  using tinymce in a typescript project here, not having much luck myself and can't find much information elsewhere

**Comment by Simbiat** [comment]
I would like to know how to properly add tinymce.d.ts to tsconfig.json, so that TypeScript would recognize `tinymce` object, too. Tried adding it to it or the folder where it is through `paths`, `include` and `references`, but no luck =(

**Comment by unlocomqx** [comment]
This worked well for me

```ts
// index.d.ts
declare global {
  interface Window {
    jQuery: JQuery;
    tinymce: import("tinymce").EditorManager;
  }
}
```

**Comment by Simbiat** [comment]
@unlocomqx do you mean you manually added it to a `.d.ts` file? What if it is automatically generated by an IDE based on tsconfig, though?
