### ISSUE TITLE
Question: Overwriting nested style_formats classes elements

### ISSUE THREAD

**Issue by pushad** [tinymce/tinymce#3435]
I'm using Tinymce 4.x, and I've implemented the style_formats option.
They are a bunch of inline span styles that apply different classes for different font sizes that are defined in css.

At the moment I've already overloaded addClass to essentially toggle "classes" and only allow one at a time for a specific span. This however does not work for child elements, nor can I access them in the overloaded function due to what appears to be a shadow dom?

My question is:
If I have three words and I put the middle word on class "one", I then select all three and put it on class "two", It will end up like this:
```
<span class="two">
     Word1
<span class="one">
     Word2
</span>
     Word3
</span>
```
When in reality I want it to overwrite the nested span so it becomes either:
```
<span class="two">
    Word1
    Word2
    Word3
</span>
```
or at least:
```
<span class="two">
    Word1
<span class="two">
    Word2
</span>
    Word3
</span>
```
This behavior works when only using one style, but I need it to work for different custom_styles. How can I achieve this?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
