### ISSUE TITLE
iOS - clicking outside tinymce editor doesn't close keyboard

### ISSUE THREAD

**Issue by RustyDev** [tinymce/tinymce#3441]
We're running into issues with the iOS keyboard not closing when clicking outside the tinymce instance.

I've set up a simple CodePen that has a normal textarea and a tinymce instance. Typing in the textarea and then clicking `submit` properly closes the iOS keyboard. The same isn't true for the tinymce instance.

http://codepen.io/rustydev/full/eb9013ae528b9cbd700fb2e15d144bbf/

**Comment by dreignier** [comment]
We have the same bug. Pretty annoying because iOS think the focus is still in TinyMCE. And after that, if you close the keyboard manually; then you click anywhere and the keyboard re-open (but you can't type in TinyMCE).

But i think the bug is in iOS. It don't handle iframes correctly.

**Comment by MaximHordijchuk** [comment]
I've solved the issue with submit button by adding two lines to on click handler:
```
function handleSubmit(e) {
  // ...some code

  $(e.target).closest("form").find("iframe").focus();
  document.activeElement.blur();

  // ...some more code
}
```
It's kind of hacky but works well. The main idea is to focus on TinyMCE iframe and then blur

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
