### ISSUE TITLE
Problem with page plugins/code.md

### ISSUE THREAD

**Issue by Kristiansky** [tinymce/tinymce#3452]
`plugins: [
				'advlist autolink lists link image charmap print preview hr anchor pagebreak',
				'searchreplace wordcount visualblocks visualchars code fullscreen',
				'insertdatetime media nonbreaking save table contextmenu directionality',
				'emoticons template paste textcolor colorpicker textpattern imagetools'
],`
These are the plugins i use, but only the CODE doesn't work.

I **cannot click** on the textarea appearing after clicking the '<>' icon. I click but i cannot write code inside of it.
![image](https://cloud.githubusercontent.com/assets/11662094/22149818/a1a2ba2a-df1e-11e6-9eae-2f37ea736027.png)

**Comment by Kristiansky** [comment]
Here is the full javascript code:
`var handleTinyMCE = function () {
		tinymce.init({
			language : LANG,
			verify_html: false,
			selector: '.editor',
			height: 250,
			theme: 'modern',
			plugins: [
				'advlist autolink lists link image charmap print preview hr anchor pagebreak',
				'searchreplace wordcount visualblocks visualchars code fullscreen',
				'insertdatetime media nonbreaking save table contextmenu directionality',
				'emoticons template paste textcolor colorpicker textpattern imagetools'
			],
			toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
			toolbar2: 'print preview media | forecolor backcolor emoticons | code',
			code_dialog_height: 600,
			code_dialog_width: 600,
			image_advtab: true,
			templates: [
				{ title: 'URL адрес', content: '[SITE_URL]' },
				{ title: 'Вмъкване на плъгин', content: '[include][/include]' }
			],
			content_css: [
				/* SITEURL + '/assets/libraries/bootstrap/bootstrap.min.css',
				 SITEURL + '/assets/css/components.css',
				 SITEURL + '/assets/css/style.css',
				 SITEURL + '/assets/css/media.css',
				 SITEURL + '/assets/css/custom.css',
				 SITEURL + '/assets/css/font-awesome.min.css', */
			],
			setup: function (editor) {
				editor.on('change', function () {
					editor.save();
				});
			}
		});
	}`

**Comment by fyrkant** [comment]
Hi!

Are you able to reproduce this problem in a [fiddle](http://fiddle.tinymce.com/)? Otherwise it is very difficult for us to see if it is a bug in TinyMCE or something else on your page that creates this problem.

**Comment by Kristiansky** [comment]
i'm afraid it's not possible

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
