### ISSUE TITLE
Cannot read propery 'paste' of null in Special Characters

### ISSUE THREAD

**Issue by mgebiesheuvel** [tinymce/tinymce#3461]
Some special characters are not working properly. (i.e. soft hyphen, black spade suit, Xi). They return an `Uncaught TypeError: Cannot read property 'paste' of null` in the console.

The problem occurs in Chrome and Firefox.

![2017-01-30 16_21_57-tinymce _ the most advanced wysiwyg html editor](https://cloud.githubusercontent.com/assets/19167718/22428632/23e738bc-e708-11e6-8684-efe8b8d69e0b.png)
![downloadattachment](https://cloud.githubusercontent.com/assets/19167718/22429002/67bf2efe-e709-11e6-9b93-f823dca318fc.png)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.

**Comment by 4rChon** [comment]
![image](https://user-images.githubusercontent.com/6491290/127308546-f02b468e-913f-423d-ad2a-0390082ed05f.png)
Can reliably reproduce this issue by clicking outside the inner <div> containing the character, but inside the outer <td>.

In the attached image, this would be outside the blue highlighted area, but within the grey area.
