### ISSUE TITLE
In inline mode, selecting text and creating anchor deletes the text

### ISSUE THREAD

**Issue by petemolinero** [tinymce/tinymce#3465]
When using TinyMCE in inline mode, selecting text and creating an anchor around it is not possible. The editor simply _deletes_ the originally selected text.

Steps to reproduce:

1. Visit [https://www.tinymce.com/docs/demo/inline/](https://www.tinymce.com/docs/demo/inline/)
2. Select some paragraph text
3. Click `Insert`>`Anchor`
4. Enter an ID and click Ok

After completing step 4 you'll notice that your originally selected text has been deleted; an anchor now sits in its place.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.

**Comment by ashish921998** [comment]
We are facing this issue, Not able to use anchor plugin in our app. Using inline mode.
