### ISSUE TITLE
Return Markdown

### ISSUE THREAD

**Issue by KisaW** [tinymce/tinymce#3467]
Hello all,

I would like to return a Markdown instead of HTML.

I find this, but it doesn't work... (I don't see any change with or without) (https://www.tinymce.com/docs/plugins/textpattern/)

It's possible ? If yes how ?

Thank you. 

(PS : I use tinymceBundle)

**Comment by KisaW** [comment]
I Had a answer on StackOverFlow.

https://stackoverflow.com/questions/41964034/tinymcebundle-return-markdown

**Comment by donShakespeare** [comment]
Here, you can use TinyMCE as a pure Markdown Editor. Input is Markdown, output is Markdown.
Finally!!! a great MD editor for TinyMCE.
https://github.com/donShakespeare/twExoticMarkdownEditor

**Comment by vanillajonathan** [comment]
Markdown support is on the roadmap.
https://www.tiny.cloud/roadmap/

**Comment by nudge-clem** [comment]
I tried using the documentation to get TinyMCE to output markdown instead of HTML and it's very misleading. If you're using the markdown plugin with typescript it throws a bunch of errors and does not allow for the syntax suggested in the docs to be used. 

@TinyMCE team: please update the docs with a working TypeScript example for markdown output. I went digging in the node modules and could not even find the PluginAPI interface referenced in the docs. Is it even there??

This is the documentation that I referenced:
- https://www.tiny.cloud/docs/tinymce/latest/markdown/
- https://www.tiny.cloud/blog/how-to-add-import-and-export-markdown-buttons-to-rich-text-editor/
