### ISSUE TITLE
iOS: Bold/Italic appear selected when they're not

### ISSUE THREAD

**Issue by bparousis** [tinymce/tinymce#3468]
Device: iPhone 6s iOS 10.2.1

Version: TinyMCE 4.5.0

Use TinyMCE on iPhone.
1) Touch the "Bold" button to select it.
2) Type something (should be bold).
3) Touch on "Bold" again to deselect.  Square still appears around bold button making it appear as if it's still selected.
4) Type something.  It's no longer bold, but again the bold button looks like it's selected.
5) Touch in text area and square around Bold button goes away, since the focus shifts.

Expected behaviour: When I deselect the bold option it shouldn't have a square around it, since it can be confusing to the user and appears selected.  The square is similar to the one you'd get on desktop by hovering your mouse over the bold button.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
