### ISSUE TITLE
Fontsize always displays something and not always correctly

### ISSUE THREAD

**Issue by trurl-master** [tinymce/tinymce#3488]
I think it's a bug because it breaks established UX. Please correct me if it's not. Maybe there is a more obvious way to overcome this.

**What is the current behavior?**
After introducing 4.5.2, more specifically [this commit](https://github.com/tinymce/tinymce/commit/a0c1d249b3a17cb01c203254a22935608d8a7849) (if i understand correctly) fontsize is always showing some value, in my case it's '12pt'. The problem is that i don't use neither pt nor px at all and it is confusing for my users. I've set 'fontsize_formats' to 'Normal=1em Highlight=1.4em' and as a result i get toolbar element that shows me "12pt" by default and "Normal"/"Highlight" as possible options which doesn't make much sense in terms of UX.

So to overcome this i either must use pt/px or create my own toolbar element. The premier is not an option, the latter is sad.

Here is a fiddle to illustrate what i mean: http://fiddle.tinymce.com/EJfaab

**What is the expected behavior?**
Behaviour prior to 4.5.2 was quite good, there was 'Font Size' toolbar element and a set of options in a drop down. Another solution to this is to allow other font size formats other than px/pt.

Thank you!

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
