### ISSUE TITLE
"No color" button of background do not remove background color if it has class.

### ISSUE THREAD

**Issue by vusan** [tinymce/tinymce#3489]
I put inline style as well as class like this.
```
                formats: {
                    hilitecolor: {
                        inline: 'span', 'classes': 'background-color', styles: {
                            backgroundColor: '%value'
                        }
                    }
                }
```
Now the output will be like:
`<span style="background-color:#fcf" class="background-color">lorem</span>`

But selecting **no color** ([x] button on background colors) do not remove its inline color, selecting **no color** will remove its class instead. So the result would be.
` <span style="background-color:#fcf">lorem</span>`

Version of TinyMce is 4.5.0

**Comment by fyrkant** [comment]
I'm having problems reproducing this, if you check [this fiddle](http://fiddle.tinymce.com/KJfaab) and select the text and then select the no color option in the background-color toolbar it removes the inline styles and leaves the classname as is. Can you create a fiddle reproducing the problem?

**Comment by vusan** [comment]
oh yeah it remove style when we put manually. But it will not remove style if the class is put by program itself.  I slightly modify [your fiddle](http://fiddle.tinymce.com/KJfaab/1) to reproduce the problem

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
