### ISSUE TITLE
Failure issue of noneditable

### ISSUE THREAD

**Issue by epiglinux** [tinymce/tinymce#3491]
report a bug.

**What is the current behavior?**
-When configuring a custom plugin, with noneditable characteristics, the resulting insert is correct, but when editing that tag, it generates a new tag. That happens from version 4.5.0.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.
       -http://fiddle.tinymce.com/MJfaab

**What is the expected behavior?**
-That the selected tag is updated and not replicated.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
-Versions prior to 4.5.0 correctly generate the expected behavior.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
