### ISSUE TITLE
How to change floatPanel's parent?

### ISSUE THREAD

**Issue by shikelong** [tinymce/tinymce#3496]
hi. How to specify the floatpanel's parent?

Because I disable the scrollbar in body and the tinymce floatPanel's parent is body. When I scroll the page. The floatpanel's position still due to the body.  

![2017-02-20_092533](https://cloud.githubusercontent.com/assets/4499997/23108908/b66b0a0a-f74e-11e6-8c6e-9e35c1991d88.png)

My Config

```js
EDITOR_CONFIG = {
    menubar: false,
    min_height: 350,
    max_height: 800,
    plugins: ['advlist autolink lists link image charmap print preview hr anchor pagebreak',
      'searchreplace wordcount visualblocks visualchars code fullscreen',
      'insertdatetime media nonbreaking save table contextmenu directionality',
      'emoticons template paste textcolor colorpicker textpattern toc'],
    toolbar1: 'fontsizeselect | bold italic | underline strikethrough | styleselect | alignleft aligncenter alignright alignjustify | bullist numlist',
    toolbar2: 'print | outdent indent | forecolor backcolor emoticons | link image | code',
    image_title: false,
    inline: false,
    automatic_uploads: true,
    file_picker_types: 'image',
    statusbar: false,
    file_picker_callback: this.handlePickerImage.bind(this),
    language_url: langUrl
  };

```

Regards.

**Comment by donShakespeare** [comment]
I tried many things to solve this issue in my ExtJS environment. No hope.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
