### ISSUE TITLE
No cursor to the right of an image that has a float:left style in Chrome & Webkit

### ISSUE THREAD

**Issue by ryandemmer** [tinymce/tinymce#3503]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

When an image is inserted into the editor, and a float:left style is applied (via the Source Code view or the Align Left button), it is not possible to place the cursor to the right of the image. 

Clicking to the right of the image and then typing works, as if the cursor was visible.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

See this CodePen example - http://codepen.io/anon/pen/BWaQLO

1. Click to the right of the image. A cursor is shown.
2. Click on the image to select it. Click on the Align Left button to apply a float:left style.
3. Click to the right of the image. No cursor is shown.

**What is the expected behavior?**

A cursor should be visible when clicking to the right of the image.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Tinymce - Latest
Chrome - 56.0.2924.87
Safari - 10.0.3

Firefox and IE Edge do not exhibit the behaviour described above.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
