### ISSUE TITLE
Adding an extra root_block setting may help resolve force_root_block: false issues

### ISSUE THREAD

**Issue by codegaze** [tinymce/tinymce#3507]
**Do you want to request a *feature* or report a *bug*?**
Feature/Bug

> Note that not using p elements as root block can severely cripple the functionality of the editor.

Setting an additional `root_block` element settings to wrap all content when `force_root_block` is false and mode inline may help resolving these issues.

Cheers! 🍻

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
