### ISSUE TITLE
How can I make bootstrap tabs same like table 

### ISSUE THREAD

**Issue by Ahsanmughal** [tinymce/tinymce#3512]
Hi
I am looking for a feature defining dynamic tabs in editor as plugin or any other way like template ?
Here is basic [Example](https://plnkr.co/edit/HFZSD73jjjmb4IDnB5hW?p=preview) of mine to define dynamic tabs.
**But tabs and content must be also editable not static**
Thank you

**Comment by Ahsanmughal** [comment]
@nomi-ramzan

**Comment by sadiqhabib** [comment]
hi @Ahsanmughal I also started working on `tabs` but its just initial stage you can also contribute if you want. You can check my fork of this project. [Tabs-plugin](https://github.com/sadiqhabib/tinymce)
Thank you

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
