### ISSUE TITLE
On IOS:  Sometimes TinyMCE auto suggest wrong word

### ISSUE THREAD

**Issue by laeeqwtb** [tinymce/tinymce#3515]
Device: IOS
Version: TinyMCE 4.4.3

On TinyMCE full feature example page https://www.tinymce.com/docs/demo/full-featured/, the text say 'offering' and now I want to type 'ominous' in place of 'offering'. I press [Back Space] and delete all the way back to just 'o'. Then, I start typing 'm' to type the word 'ominous' BUT iPad starts suggesting words starting with 'm...' such as 'makes' or 'more'. iPad cannot see the first letter and suggest words starting with the 2nd letter that I types as the start of the new word. The auto-suggest functionality is going wrong here. Please see screenshot .

![image](https://cloud.githubusercontent.com/assets/2102705/23359781/e8952794-fd0d-11e6-823b-a32fdb2e899e.png)

**Comment by laeeqwtb** [comment]
Please reply on issue.

**Comment by poonamkapoor** [comment]
Please do revert us on this issue. We are awaiting for the fix.

**Comment by poonamkapoor** [comment]
Please update us on this.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
