### ISSUE TITLE
Font family selection does not work after changing font size

### ISSUE THREAD

**Issue by rodrigopavezi** [tinymce/tinymce#3519]
When selecting all the text and changing the font-size then trying to change the font family will not work properly. It will change the font family once but not anymore keeping the same font family. It keeps adding a span for each font family chosen. 

Example:

1. Entering a text: `<p>This is a test</p>`
2. Changing the font-size: `<p><span style="font-size: 14pt;">This is a test</span></p>`
3. Changing the font family to Comic Sans ms: `<p><span style="font-family: 'comic sans ms', sans-serif; font-size: 14pt;">This is a test</span></p>`
4. Changing font family again to Impact: 

Expected outcome:

`<p><span style="font-family: 'impact', sans-serif; font-size: 14pt;">This is a test</span></p>`

Actual outcome:

`<p><span style="font-family: impact, sans-serif; font-size: 14pt;"><span style="font-family: 'comic sans ms', sans-serif;">This is a test</span></span></p>`

This can be verified with this fiddle: http://fiddle.tinymce.com/FKfaab

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
