### ISSUE TITLE
MacOS: inline mode, insertContent() doesn't work from context menu

### ISSUE THREAD

**Issue by real-artswan** [tinymce/tinymce#3520]
I would report a bug.

In inline mode insertContent() doesn't work if it is called from context menu click handler but still works as expected if called from another places. 
Here is demo: https://jsfiddle.net/9ue2pLLz/9/ If you run it under MacOS you'll see that text inserts when you click on button but doesn't if you use editor's context menu.
I've faced with this issue under MacOS using TinyMCE 4.5.3 on both Safari and Chrome when inline: true. Under Windows it works perfect on Firefox and Chrome.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
