### ISSUE TITLE
Accessibility issue on editing text when accessing through JAWS screen reader

### ISSUE THREAD

**Issue by SoubhikMondal** [tinymce/tinymce#3523]
**Specification:**
  Windows version  : Windows 10
  Firefox Version  : 50.1.0
  JAWS version     : 18.0.2324
  Tiny MCE Version : 4.4.0

**Steps to reproduce:**
  1. Launch JAWS screen reader;
  2. Navigate to the text editing field of Tiny MCE using arrow keys (virtual cursor);
  3. JAWS will say `edit` once control reaches into editing field;
  4. Start typing characters.

**Actual Behavior:**
  We are not able to enter text there.

**Expected Behavior:**
  We should be able to enter text there, just like we can do in normal text-area

Thanks & best regards

**Comment by yerrinaidu** [comment]
Hi, I am having the similar kind of issue with tinymce, if I turn on the jaws screen reader I am not able to enter any text in the text area! Do you have the solution !?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
