### ISSUE TITLE
Textpattern error in inline mode, using custom command

### ISSUE THREAD

**Issue by cdolek** [tinymce/tinymce#3526]
Try typing `**test**` and you will see that text becomes bold, however typing **`[test]`** outputs **"Uncaught TypeError: Cannot read property 'inline' of undefined"** error.

```
tinymce.init({
    selector: 'div.tinymce',
    theme: 'inlite',
    plugins: 'textpattern',
    insert_toolbar: 'quickimage quicktable',
    selection_toolbar: 'bold italic | quicklink h2 h3 blockquote',
    inline: true,
    textpattern_patterns: [
        { start: '**', end: '**', format: 'bold' },
        { start: '[', end: ']', cmd: 'mycommand' }
    ],
    setup: function(ed){
        ed.addCommand('mycommand', function(ui, v) {
            alert('testing');
        });
    }
});
```

[codepen here](http://codepen.io/anon/pen/qraMdd)

**Comment by rachetfoot** [comment]
Are there any workarounds for this?

**Comment by cdolek** [comment]
@rachetfoot not that I know of

**Comment by wagnerflo** [comment]
From a cursory look at the code it seems to me that with inline patterns only style formats can be used. A `cmd` is unsupported. Please consider adding support.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
