### ISSUE TITLE
Default font-family and font-size

### ISSUE THREAD

**Issue by Kleppo** [tinymce/tinymce#3527]
The default font-family in TinyMCE is 'Times' and '12pt' is the default font-size.
But when I click inside the textarea, they change to 'Verdana 12px'..
I want them to be 'Verdana 12px' at init..

fiddle: http://fiddle.tinymce.com/gLfaab

**Comment by subinsunny** [comment]
Hey Kleppo, why don't you set the font to verdana at init using the init function..
like [this](http://fiddle.tinymce.com/gLfaab/1)

**Comment by justinwyllie** [comment]
For me (using TinyMCE v. 4.6.4) this worked in as much as Arial was indeed set as the default when the editor initialised. However; when the user clicks into the Editor it immediately went back to Verdana. This does not happen in the linked JSFiddle even when I switch the version to 4.6.4

I copied the JS code from the JSFiddle into our site but the issue persisted. So it seems maybe it is something to do with some other part of the configuration. Maybe the CSS? I don't know...

**Comment by SimmeNilsson** [comment]
@justinwyllie Ran into the same issue. After some digging it turned out doing a editor.setContent reset the font to Verdana if font had been set with execCommand.
[http://fiddle.tinymce.com/gLfaab/150](url)

@spocke is this intentional?

Resorted to using body_class and content_style/content_css (depending on if font known at programming time or not) instead.

**Comment by Mario-Eis** [comment]
> Hey @Kleppo, why don't you set the font to verdana during initialisation only using the init function..
> like [this](http://fiddle.tinymce.com/gLfaab/1)

Unfortunately this sets the input focus to the editor, breaking the users input flow. Can this be avoided? Cant find a way to do it...

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
