### ISSUE TITLE
Ability to add buttons to source code modal

### ISSUE THREAD

**Issue by fernandodof** [tinymce/tinymce#3528]
`Feature request/ Help request`

**What is the current behavior?**

I have seen that it's possible to add buttons

``` javascript
//https://www.tinymce.com/docs/advanced/creating-a-custom-button/
editor.addButton('mybutton', {
  text: "My Button",
  onclick: function () {
     alert("My Button clicked!");
  }
});
```

It is also possible to add button the source code button

``` javascript
//https://www.tinymce.com/docs/plugins/code/
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "code",
  toolbar: "code",
  menubar: "tools",
  code_dialog_height: 200
});
``` 

So my question is: Is it possible to add a button to the source code modal ?

Like the example below.
![picture1](https://cloud.githubusercontent.com/assets/5750640/23667016/540541c0-033b-11e7-8354-3b4acb1b7904.png)

Thank you.

**Comment by fyrkant** [comment]
No there's not an easy way to add a button to an already existing plugin's modal, you would have to make your own version of the plugin and add the wanted button. 

What kind of button/functionality do you want to add?

**Comment by fernandodof** [comment]
@fyrkant Thanks for your answer
This button would open another modal with a a form that is connected to the server. The server generarates html sinppets to be inserted on the source code modal.
I would like to give the user the opportunity to edit this generated html, but right now I just added the button to the editor ([like this](https://www.tinymce.com/docs/advanced/creating-a-custom-button/)). So the html will be inserted directly on the editor, thus not possible to be edited.

Thanks again for you response.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
