### ISSUE TITLE
<link> tags support

### ISSUE THREAD

**Issue by dev-101** [tinymce/tinymce#3536]
_Sorry if this was asked many times before, but github search removes any special characters/wildcards and issues a warning, returning unrelated anchor link issues in results._

Not sure if it can work, I have tried all extended elements options and what not, but `<link>` tags are removed even if they are just left empty (e.g. `<link />`). Is this intended operation? Is there a workaround, possibly?

Thanks!

**What is the current behavior?**
`<link>` tags are removed as soon as Source Code window is closed.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Yes, reproducible behavior @ fiddle.

**What is the expected behavior?**
Well, `<link rel="">` cannot be inside body (but, say I have specific need for it?).
On the other hand, `<link itemprop="">` is allowed / valid.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Latest TinyMCE, many recent versions are affected to say at least.

**Comment by kleand** [comment]
Same issue here

When <link> tag is inside <head> tinymce does NOT render anything at all, displays empty mean while in the code there is the hole HTML.

Please help if found any wokaround for this

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
