### ISSUE TITLE
headings in table get wrapped in span when pasting

### ISSUE THREAD

**Issue by Fiona-TU** [tinymce/tinymce#3541]
The following behaviour only seems to appear in chrome/opera/etc:

Text in headings in table cells gets wrapped in span tags when pasting text (with multiple lines and at least one empty line) from, i.e. Windows notepad/KWrite, into a table cell.

How to reproduce:

- Visit http://fiddle.tinymce.com/MLfaab/1
- Copy&Paste this text into notepad/KWrite (it seems to be important how the line breaks are encoded): 

```
Line1

Line2
```
- Copy the text from notepad/kwrite and paste it into the lower table cell
- The heading should be wrapped into a span now

Maybe it can be reproduced easier and maybe it's not only affecting headings in tables.

**Comment by Fiona-TU** [comment]
In order to use svg inside TinyMCE, we are extending the configuration by

`valid_elements: "*[*]"`

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
