### ISSUE TITLE
removing font-style format is splitting span 

### ISSUE THREAD

**Issue by AlexanderSidikov** [tinymce/tinymce#3543]
select the X´s and style it bold (ctrl+b)
http://fiddle.tinymce.com/QLfaab

creates 2 new spans.. 
is it posible to remove a style without splitting the span?

**Comment by jayarjo** [comment]
You are removing format from a string in the middle of another formatted string. Split is kind of logical? 

Is there alternative structure that you can suggest?

**Comment by AlexanderSidikov** [comment]
tiny is splitting the span. But normally the browser will wrap the text-block before and after the span into bold and than inside the span to 3 parts... 

this is the normal build in command .. chrome an firefox are wrapping the same way
document.execCommand("bold", false, null);

you can try my fiddle example here.. : https://www-archive.mozilla.org/editor/midasdemo/

its complicated because both ways have con and pros. maybe u can let the user configurate this. 

btw thx

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
