### ISSUE TITLE
[Bug Report] Odd behavior with Bootstrap Grid system

### ISSUE THREAD

**Issue by bhnow** [tinymce/tinymce#3545]
Bug Report

When use Bootstrap Grid System, empty paragraphs changes to `<br>` which also overrides closest `<div>` tag, which in turn ruins the grid and make it really hard to maintain/edit.

You can see this behavior in the action: http://fiddle.tinymce.com/PLfaab/1

Empty `p` tags should stay after removing the text inside them rather than throwing random `br` tag (which overrides the closest `div`). You can see this in the fiddle if you remove `col-xs-6` characters.

TinyMCE version: 4.5.5

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
