### ISSUE TITLE
How to Display Rupess Symbol in CharMap

### ISSUE THREAD

**Issue by ghost** [tinymce/tinymce#3548]
I have Added a new option in TinyMCE CharMap . but since font was not supporting in client system so how do we import custom font to Rupess symbol appear perfectly .
`tinymce.PluginManager.add("charmap", function(e) {
function t() {
    return [
        ["8377", "Rupess Symbol"],
        ["160", "no-break space"],
         ..So on 
        ["8207", "right-to-left mark"]
    ]
 }`
Please any one suggest or provide live fiddle with font supported and display Rupess Symbol . since we can't install font on client systems . Thanks

**Comment by Ananddwivedi92** [comment]
@fyrkant  can you look at into that . or any version which support INR Rupess Symbol or provide any fiddle which loads and font and display to charmap popup . Thanks for help in advance

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
