### ISSUE TITLE
SpellChecker is not working

### ISSUE THREAD

**Issue by udai21419** [tinymce/tinymce#3551]
BUG

*SpellChecker is not working*

Step 1) Go to https://www.tinymce.com/docs/demo/classic/
Step 2) Click on Spellchecker
Step 3) Error is displayed

Error should not come.
![screenshot](https://cloud.githubusercontent.com/assets/12740597/24235647/4791367a-0fc4-11e7-837e-c20e026376d4.png)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
