### ISSUE TITLE
`<img>` src are not updated when enable caption on insert

### ISSUE THREAD

**Issue by lordfriend** [tinymce/tinymce#3553]
**Do you want to request a *feature* or report a *bug*?**

Report a Bug

**What is the current behavior?**

check the caption checkbox in image insert dialog, then the `<img>` src attribute are not replaced automatically.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.

- add `image` plugin
- set `image_caption` to true, set `automatic_uploads` to true
- using image insert dialog, select image, check the `caption` checkbox. and click OK
- image will automatically uploaded but `<img>` src attribute not updated.

**What is the expected behavior?**

`img` src should be updated whether caption is check or not.

NOTE: if you don't check `caption` checkbox when add a new image. the src attribute is updated as expected. as well as you add caption when edit an existed image.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Current 4.5.5 ~ 4.5.2
I haven't use the older version.
Chrome latest stable

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
