### ISSUE TITLE
Bug on loading css with Firefox

### ISSUE THREAD

**Issue by FabriceGaudin** [tinymce/tinymce#3554]
On Firefox, the loading of external css is done after rendering. We can see the changes very shortly and it's not pretty. If autoresize is enabled, it makes the editor's height changes.

Here is a fiddle to reproduce:
http://fiddle.tinymce.com/pMfaab/3
The problem is on initalization. Afterwards the css is correctly loaded.

The css should be already loaded when rendered. We can see on Chrome (or any other browser) that it works correctly.

The problem occured with TinyMCE 4.4.3 but we can see with the fiddle that it's also on previous versions of TinyMCE.
The problem occured on Firefox.

If the bug can't be corrected, how can we show the editor only after the css loaded ? Is there any trick to avoid this annoying blink ?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
