### ISSUE TITLE
plugin autoresize should not resize custom height

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#3557]
I have enabled autoresize. Its a nice feature, but its not working as I expected. When I set a custom height with the right bottom corner resizer, than autoresize should not drop back to a smaller height.

Example: 
Resize height with the right bottom corner resizer. After press return key the height jumps back smaller. That should not happen, when the height is greater then needed.

On the other side. When you set autoresize_max_height and after input reach this max_height, the custom resize with right bottom corner resizer don't jump back smaller. Thats right.

**Comment by fyrkant** [comment]
Could you create a fiddle showing the issue? I'm not sure I understand what you mean with that the height jumps back smaller.

**Comment by Daijobou** [comment]
http://fiddle.tinymce.com/2Mfaab
first resize editor (with right bottom corner) and than press enter. its jump back smaller. autoresize should help for a good input, but when a user want a minimum height it shopuld not resize it smaller.

**Comment by Daijobou** [comment]
What more informations are needed?

**Comment by jaredcrystal** [comment]
+1 Also experiencing this issue

**Comment by donShakespeare** [comment]
@jaredcrystal what issue?
The initial jump when the editor loads?

**Comment by jaredcrystal** [comment]
@Daijobou explained it pretty well. Here are the repro steps:

- enable the autoresize plugin
- enable `resize` and `statusbar` so that the user can manually resize the rce
- with little to no text in the rce (cannot exceed `autoresize_max_height`)
- manually resize the rce (by dragging the bottom right corner) to make it fairly large
- press `enter` to create a new line, or backspace to delete a line

Actual behavior:
- the rce snaps to a smaller size

Expected behavior:
- the rce persists the height manually set by the user

I think @Daijobou was also trying to point out that with a lot of text (if the rce already exceeds the `autoresize_max_height`), then it correctly respects the manually resized height, and does not snap.

**Comment by jaredcrystal** [comment]
![tinymcejump](https://user-images.githubusercontent.com/14153009/33640340-2ba6fbcc-d9ed-11e7-8872-14d036be1152.gif) @fyrkant @donShakespeare here's a gif of the issue

**Comment by donShakespeare** [comment]
Makes sense now. Thanks for the GIF.

**Comment by Daijobou** [comment]
Any news here? This issue is still in 4.8.5 very annoying. ;)

**Comment by Daijobou** [comment]
Tinymce 5 have it too. Github editor make this autosize feature better. After resize its stopping autosize.

**Comment by Daijobou** [comment]
@fyrkant 
Can you remove the flag "Needs more infos"? I think this request is very clear explained. ;)
See https://github.com/tinymce/tinymce/issues/3557#issuecomment-349503709

**Comment by Daijobou** [comment]
Three years have now passed. Any chance that this wrongdoing will be corrected?
