### ISSUE TITLE
Font Family/Size showing default of system OS instead of labels

### ISSUE THREAD

**Issue by daanvanham** [tinymce/tinymce#3560]
**Do you want to request a *feature* or report a *bug*?**
I'm not sure if the really is a bug/feature or if I'm just missing a setting, but I couldn't find it.

**What is the current behavior?**
In the Font Family/Size select buttons it shows the system OS default font settings (on my Mac I get `serif 12pt` and on a Windows machine I see `Times New Roman 12pt`. With `content_css` we loaded a file which states it should use `Verdana 11pt`. After focus, it actualy jumps to those settings, but on initial loading it shows the wrong settings.

**What is the expected behavior?**
In the previous version of TinyMCE it showed the labels `Font Family` and `Font Size`. That's what I expected it to do again.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
It worked in the previous version we used (4.1.6). Behaviour is the same on all platforms and browsers.

**Comment by czirkoszoltan** [comment]
This was supposed to be an enhancement in 4.5.2. (Changelog entry: "Fixed so font size and font family select boxes always displays a value by using the runtime style as a fallback.")
However, it is sometimes annoying to the users (because font names and font sizes appear in the combo box, which are actually not in the list.)
Also, it is sometimes uninformational or misleading. Font sizes are shown as pt, even if they are set in px or em in the HTML code. And the combo boxes show some specific font or font size, even if the HTML code does not set any style. <p> is not the same as <p style="font-family: Verdana;">! The first one does change, when the content css is updated, the second one does not.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
