### ISSUE TITLE
remove pasted text from undomanager

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#3561]
Hi,

I need help to remove the pasted text from undo manager since I don't want that text to be undo.

**Comment by fyrkant** [comment]
What do you mean, you don't want pasting text into the editor to create an undo point? Why do you not want that?

**Comment by kaviyarasanaspire** [comment]
Hi,

I would like to remove the undo point for the pasted text, pasted text should not captured in the undo event. I hope you understand my question.

**Comment by fyrkant** [comment]
Ok, yes then I understand what you mean now but unfortunately I do not think there is an easy way to do this. Is there a special reason why you don't want the pasted text to become an undo point?

**Comment by kaviyarasanaspire** [comment]
I need it why because after pasted the text I did some operation to change the property of the input controls which pasted. While undoing also i am doing the same process. So while doing the modification while undoing it is not allowing me to go the previous level. 

For example i have input control with the text "1", I will modify the pasted the control to "2", but while copy pasted the "1" it was "1". so if I do undo it goes from "2" to "1". But I want to have only one control if i do undo.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
