### ISSUE TITLE
ControlSelection performances issue because of a full repaint/reflow

### ISSUE THREAD

**Issue by dreignier** [tinymce/tinymce#3563]
This is not a bug or a feature, but `ControlSelection` has a big performances issue if you use TinyMCE in a very big website.

Using TinyMCE 4.5.0, in [ControlSelection.js](https://github.com/tinymce/tinymce/blob/master/src/core/src/main/js/dom/ControlSelection.js), in the `updateResizeRect` function, line 413, you can find this line:

    controlElm = dom.$(controlElm).closest(isIE ? 'table' : 'table,img,hr')[0];

This line is just here to find the closest element according to the given CSS selector. The problem is that this line trigger a full repaint and reflow for all the page on Internet Explorer and Firefox (Chrome doesn't have the problem).

On a very big website, the full reflow for Internet Explorer can take 1 second or more. TinyMCE is just unusable on a such configuration. Because `updateResizeRect` is called everytime you touch TinyMCE (with a little throttle, but it's sill very slow).

The problem seems to be related to Sizzle. Because if you remove this line and you replace it with this:

    while (controlElm.parentNode && controlElm.tagName !== 'TABLE' && isIE && controlElm.tagName !== 'IMG' && controlElm.tagName !== 'HR') {
        controlElm = controlElm.parentNode;
    }

Everything is perfect. No full repaint anymore. Even Internet Explorer 10 is as fast as possible. This code does the same thing as the initial line, but without Sizzle. I don't know why Sizzle is triggering a full repaint just by looking for a DOM node.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
