### ISSUE TITLE
Null reference when using fontselect or fontsizeselect and content starts with HTML comment

### ISSUE THREAD

**Issue by jfcardinal** [tinymce/tinymce#3565]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Null reference is thrown.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Include fontselect or fontsizeselect in toolbar and have initial content to be edited start with HTML comment.

**What is the expected behavior?**
No exception.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I tested with v4.5.5. I did not test prior versions.

---

Using TinyMCE v4.5.5, if I include the fontselect or fontsizeselect items in a toolbar, and the initial content to be edited starts with an HTML comment, I get a script error:

Error: Unable to get property 'fontFamily' of undefined or null reference 
or
Error: Unable to get property 'fontSize' of undefined or null reference

Those error messages are from IE11. Messages vary in other browsers, but the problem is the same, i.e., there is a reference to the property of a null variable.

You can see the result on this test page:: [http://www.johncardinal.com/tests/html-edit.htm](http://www.johncardinal.com/tests/html-edit.htm)

The bug is evident in IE11, Firefox 52, and Chrome. Unless you look at the console, you might not see the error. Note, however, that the editor should occupy the full window (mceFullScreen), but it doesn't because the exception short-circuits initialization of the editor and the init_instance_callback is not called.

**Comment by TomTheRock** [comment]
bug until v4.5.7 at the newest version 4.6.4 bug is solved...but other bug with mutliple instances and filemanager still happend :/

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
