### ISSUE TITLE
Non editable elements caret jump showcase and possible solution

### ISSUE THREAD

**Issue by codegaze** [tinymce/tinymce#3567]
Hello, 
this is a bug shown with a possible solution for the caret jumps of non editable content inside tinymce editor. 

**The issue / how to reproduce it**
http://fiddle.tinymce.com/HMfaab Try to insert the non bogus content into the editor and then try to backspace your way through the content. When you reach the non editable content the caret will jump to the end of the line and with the next backspace keystroke will remove the element. If you test the "with bogus" example you'll see that the cursor can find it's place.

This bug also occur when you insert with `mceInsertContent` multiple non editable elements(not all at once, more than one in a typing "session"). There is a `&#65279` character only for the last element to keep the caret in position.

I can reproduce this with Chrome, Safari, Firefox in OSX.

**Possible Solution**
What I've done to reduce this problem to minimum: 
* I'm adding a bogus br each time I set content to the editor.
* On keypress I check if there is a bogus br in the content and if not I append it.

Do you think we can find a better/more elegant solution for this?
Cheers

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
