### ISSUE TITLE
Incompatible with "Rails Assets" files management system for Rails

### ISSUE THREAD

**Issue by ziomio** [tinymce/tinymce#3568]
**Do you want to request a *feature* or report a *bug*?**
Feature/Bug

**What is the current behavior?**
TinyMCE library does not play nice with Rails Assets ( https://rails-assets.org )...
Because TinyMCE does not define main assets in bower.json - Rails Assets is unable to correctly build a 'tinymce' gem. 

Output of `git push heroku master` command:

```
...
remote:        Bundled gems are installed into ./vendor/bundle.
remote:        Post-install message from rails-assets-tinymce:
remote:        This component doesn't define main assets in bower.json.
remote:        Please open new pull request in component's repository:
remote:        http://www.tinymce.com/
remote:        Bundle completed (7.56s)
...
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Add this line to Gemfile: 
`gem 'rails-assets-angular-ui-tinymce'`

2. Do `git push heroku master`

**What is the expected behavior?**
TinyMCE assets(files) will be loaded successfully.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 4.5.4, Rails 4.2.4

**Comment by mvkampen** [comment]
I'm using https://github.com/spohlenz/tinymce-rails as recommended in documentation.
Its far from intuitive, since plugins, theme, language are loaded individually on initialization, it defies the purpose of Rails assets pipeline. But it works.

**Comment by ziomio** [comment]
I am using it too. Thank you for suggestion, though!

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
