### ISSUE TITLE
Bug: replaceImageUri check if uri has parameters

### ISSUE THREAD

**Issue by Federico-G** [tinymce/tinymce#3569]
**Description:**
I think the function replaceImageUri needs to see if there is any parameter in the uri.

**Example:**
foo.php?id=1 **?**123456789 //cacheInvalidator() unix_timestamp
Correct: foo.php?id=1 **&**123456789

**Function:**
```javascript
function replaceImageUri(image, resultUri) {
	blobCache.removeByUri(image.src);
	replaceUrlInUndoStack(image.src, resultUri);
	editor.$(image).attr({
		src: settings.images_reuse_filename ? resultUri + cacheInvalidator() : resultUri,
		'data-mce-src': editor.convertURL(resultUri, 'src')
	});
}
```

**Version:**
4.5.6 (2017-03-30)

**Note:**
The function _addCacheSuffix checks if the url has any **?**

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
