### ISSUE TITLE
Template window plugin is not vertically centered

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#3570]
In devices with a screen resolution of 1024x768 (for example), the template window shows up at the top of the screen (top:0), with free space at the margin bottom. In higher resolutions the template window appears 40 px far up from the center of the screen.

**Comment by fyrkant** [comment]
I am having problems reproducing this, can you create a [fiddle](http://fiddle.tinymce.com/)?

**Comment by lrusso** [comment]
http://oi66.tinypic.com/34ffom8.jpg

The resolution es 1280x720, the image is from Firefox 52.0 in Windows 10. The same thing happens in a Mac Mini with the same resolution in the latest version of Firefox.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
