### ISSUE TITLE
Unable to select or edit text contained in div of set width

### ISSUE THREAD

**Issue by sndrsnk** [tinymce/tinymce#3571]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Setting the width of a `div` element when placed beside an image prevents any text within that element from being editable. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
*Steps to Replicate:*
1. In IE11, navigate [here](http://fiddle.tinymce.com/ZMfaab) and set the following source, consisting of a simple image, a `div` with a set width of `49%` and containing a header and some paragraph text: 
```
<img src="http://i0.kym-cdn.com/entries/icons/original/000/000/015/orly.jpg" alt="" />
<div style="width: 49%;">
<h1>Header</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
</div>
```
2.  When attempting to select the text, a _border_ will appear surrounding it and none of the text within it can be selected or edited. 
3. Removing the image allows for the text to be edited once again. 

**Note:** Surrounding the image in a `div` tag allows for the text to be edited. 

**What is the expected behavior?**
Text should be editable, regardless of set width. 

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
IE11

**Additional**
I believe this may have something to do with focusing, specifically in IE and its interaction with the `contenteditable` attribute. Any assistance is greatly appreciated.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
