### ISSUE TITLE
mceEditable don't work properly in IE11 on win7

### ISSUE THREAD

**Issue by a-a-davydov** [tinymce/tinymce#3573]
**bug**

I have editor with table plugin enabled.
If I create content like:

```
        <div class="tableItem mceNonEditable" contenteditable="false">
            <div class="someContent">
            </div>
            <div class="tableItemBody">
                <table>
                      <tbody class="mceEditable" contenteditable="true"><tr><td></td></tr></tbody>
                </table>
            </div>
        </div>            
```    
In chrome I get full featured table cells. So I can set carret into cell and type some text.

In IE11 I can't put carret inside table cell. So I click inside cell, but carret not set in it.

**Comment by a-a-davydov** [comment]
For mceEditable div everething is fine in IE.

**Comment by a-a-davydov** [comment]
My problem is in fiddle

http://fiddle.tinymce.com/lNfaab

**Comment by a-a-davydov** [comment]
If I use data-mce-contenteditable attribute to enable or disable editability, everything works fine in IE.

See http://fiddle.tinymce.com/rNfaab/2

**Comment by a-a-davydov** [comment]
Detail demo of influence of attributes is available in http://fiddle.tinymce.com/rNfaab/6

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
