### ISSUE TITLE
RTL problem

### ISSUE THREAD

**Issue by demis-palma** [tinymce/tinymce#3575]
**Do you want to request a *feature* or report a *bug*?**
Report a *bug*

**What is the current behavior?**
![current](https://cloud.githubusercontent.com/assets/1609992/24797291/8988ae58-1b88-11e7-9647-9655fbf6371d.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
```
tinymce.init({
directionality: "rtl"
});
```

**What is the expected behavior?**
![expected](https://cloud.githubusercontent.com/assets/1609992/24797298/8dd69c5e-1b88-11e7-846f-f4e0437cd9e4.png)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
4.4.3

**The cause**
```
.mce-container, .mce-container *, .mce-widget, .mce-widget *, .mce-reset {
...
direction: ltr;
...
}
```
has a higher specificity, and overrides
```
.mce-rtl .mce-flow-layout {
  text-align: right;
  direction: rtl;
}
```

**Comment by JulietDaisy** [comment]
You have a bug or highlight request, and you're shivering to report it. The essential thing you should do is examine for a present report by using the chase field in the upper corner. [UAE assignment Writing](http://www.uaeassignmentwriting.help/) Some person may have formally reported the bug or requested the segment. Looking for at first turns away duplicates. To be intense, endeavor different proportional words and rephrasings of what the bug or highlight may have been called.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
