### ISSUE TITLE
Using pagebreak with autoresize creates horizontal scroll

### ISSUE THREAD

**Issue by jmanos** [tinymce/tinymce#3576]
Hello,

Adding a page break to the tinymce editable area causes a horizontal scrollbar to appear across the width of the editable interface when using version 4.5.6.

This occurs with the following settings:
```javascript
tinymce.init({
	        menubar: false,
	        plugins: ['autoresize', 'pagebreak'],
	        selector: '.demo',
	        toolbar: 'pagebreak'
	    });
```

[Codepen of this issue.](https://codepen.io/anon/pen/vxqgWj)

![image](https://cloud.githubusercontent.com/assets/10673812/24809939/539718a6-1b75-11e7-875e-28244e71de7b.png)

Thank you.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
