### ISSUE TITLE
Vertical alignment

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#3579]
Hi,

We are using tinymce in our project. There we used vertical alignment property to align the text in middle using the vertical-alignment: middle property.

But while click the clear formatting it clears all the styles including vertical alignment.

So the text is going bottom aligned after the image.

Can you please help me to set the default vertical alignment to middle even after the clear formatting.

Regards,
Kavi

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
