### ISSUE TITLE
Dropdown is not fixed to the top of my menu tinymce

### ISSUE THREAD

**Issue by ghost** [tinymce/tinymce#3591]
Hello,

I'm actually using Tinymce in my application. In my view, i got two 'columns'. (see attached screenshot)

![capt1](https://cloud.githubusercontent.com/assets/20796147/25267364/ca037516-2674-11e7-8578-c0437c530e0e.png)

- At the left, we got one div which contains some text.

- At the right, we got another div which contains text to edit (from the left div). I mean, if I click on some text at left, it will be editable at the right.

If I scrolldown down my page too much in order to edit the bottom of the left column, and I click on the dropdown font style (right column, tiny mce component), nothing appears because the dropdown stayed at the top of the page.

What can I do to solve my problem ? The behavior described above only occurs on Chrome.

I tried this solution : http://jsfiddle.net/nm6wtca3/5/ but it does not fit to my needs because I got two 'columns'.

Thanks in advance,

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
