### ISSUE TITLE
Paste from Word with tracked changes that have multiple comments: text is not pasted

### ISSUE THREAD

**Issue by UTCWebDev** [tinymce/tinymce#3594]
**bug**

**current behavior?**
Paste from Word with tracked changes that have multiple comments: text is not pasted.

**steps to reproduce and if possible a minimal demo of the problem via http://fiddle.tinymce.com/kOfaab**
Copy from a Word 2016 document that has multiple comments per change. Paste into WordPress or OmniUpdate OU Campus TinyMCE wysiwyg. Tracked changes that have more than one comment per change are not pasted. Use example generic document, attached. First instance of "Changed text" is pasted. Second instance of "Changed Text" is not pasted (it has a comment on the change). New revisions are pasted. Pasting into a basic RTF editor such as Mac TextEdit behaves as expected: all accepted changes are pasted. Pasting into generic text editor behaves as expected: all copied text is pasted.
[tinymce-paste-bug-reply.docx](https://github.com/tinymce/tinymce/files/947357/tinymce-paste-bug-reply.docx)

**expected behavior**
All accepted changes from MS Word should be pasted into wysiwyg.

**versions of TinyMCE, and which browser / OS **
TinyMCE 4.5.6
Mac: Safari, Firefox, Chrome
PC: Firefox, Chrome, IE
We have not seen this problem prior to the recent update in WordPress to TinyMCE 4.5.6, but I cannot verify whether the problem existed or just has not come up until now.
Update: problem seems the same in all TinyMCE 4.x.

**Comment by UTCWebDev** [comment]
**Workaround:**

Before copy/paste from Word to TinyMCE (if the doc has reviewer comments):
 
Review Delete > Delete all Comments in Document

![screen-shot 2017-04-21 at 11 15 22 am](https://cloud.githubusercontent.com/assets/2539685/25284668/bf65109a-2685-11e7-8905-a0980797aa7c.png)

**Comment by jayarjo** [comment]
For better support of copy/paste from Word you could also try [PowerPaste](https://www.tinymce.com/docs/plugins/powerpaste/).

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
