### ISSUE TITLE
wrong border when click on image in IE 11

### ISSUE THREAD

**Issue by kot-pilot** [tinymce/tinymce#3608]
sometimes clicking on image in ie 11 causes a stripped border, which also goes over container when scroll, all works pretty well in chrome . Attaching ie and chrome screens
![image](https://cloud.githubusercontent.com/assets/13122532/25526601/f579e650-2c1c-11e7-8fd4-3e38a0ff1cdd.png)
![image](https://cloud.githubusercontent.com/assets/13122532/25526618/07afad14-2c1d-11e7-9c8d-87b59804625f.png)

**Comment by spocke** [comment]
Wasn't able to reproduce this could you tell me how exactly you are clicking and also can you provide a fiddle at fiddle.tinymce.com that reproduces the issue thanks.

**Comment by kot-pilot** [comment]
source code in editor 

<div style="width: 100%; height: 400px; background: url('http://minionomaniya.ru/wp-content/uploads/2016/01/%D0%9A%D0%B5%D0%B2%D0%B8%D0%BD.jpg') no-repeat; background-size: cover;"></div>


fiddle http://fiddle.tinymce.com/

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
