### ISSUE TITLE
selectbox returning blank text in window

### ISSUE THREAD

**Issue by jamesalvarez** [tinymce/tinymce#3609]
When I create a selectbox in a window, and try to access the data in onsubmit, it doesn't give the correct value, it remains the default:

`editor.windowManager.open({
                title: 'Text Input',
                data: { type: 'Text' },
                body: [
                    {
                        type   : 'selectbox',
                        name   : 'type',
                        label  : 'Type',
                        options : [ 'Text', 'Number', 'Email', 'Date' ],
                    },
                ],
                onsubmit: function(e) {
                    console.log(e.data.type);
                }
});`

**Comment by GNUletik** [comment]
Here is a fix https://github.com/tinymce/tinymce/pull/3598 waiting for approval

**Comment by ctjhoa** [comment]
For the record, SelectBox seems deprecated in favor of ListBox.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
