### ISSUE TITLE
Paste from Word breaks after comments or track changes

### ISSUE THREAD

**Issue by mrazzari** [tinymce/tinymce#3612]
This bug is really hard to notice when pasting from a long Word doc, as sometimes this is just a missing sentence in the middle of a paragraph. So it's a major hindrance for editors.

**Steps to repro**

I'm attaching a minimal Word XML file I'm using for testing, where I can consistently repro the issue.
This file comes from a Word doc that was used with track changes enabled, and where authors and editors had added and removed comments. 

I've confirmed this is an issue in WP 4.7.3 and in **TinyMCE edge** (see fiddle below).

1. Unzip and open the attached Word XML doc using MS Word 2010 for Windows
[even-the-best-dirty.xml.zip](https://github.com/tinymce/tinymce/files/965396/even-the-best-dirty.xml.zip)
2. Select all, Copy.
3. Open http://fiddle.tinymce.com/LOfaab
4. Paste the text into the fiddle. 
5. Notice the sentence "braving ongoing raids..." is not pasted.

The source of the problem seems to be an orphaned comment:

![image](https://cloud.githubusercontent.com/assets/324617/25544456/ebc5a374-2c30-11e7-9a39-73f654d270de.png)

I guess this is related to #3594, and it was reported years ago in #2096 and closed as can't repro. 
This new ticket provides steps to repro on edge and a narrowed-down test case. 

The workaround mentioned in #3594 (delete all commens) doesn't work here. 
I've had some success by disabling "track changes" and changing the text style to "Normal", in addition to deleting all comments.  But not in this testcase I'm posting here.

The bug only goes away if I select all text in Word and hit "Clear formatting". 
But that's of course not an option as bold etc are lost too.

**Comment by ayZagen** [comment]
+1

**Comment by lbehal** [comment]
+1

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
