### ISSUE TITLE
Inline mode on table cell in IE / Edge differs from chrome / firefox

### ISSUE THREAD

**Issue by Garytje** [tinymce/tinymce#3617]
See the Fiddle Below, 

With inline mode on a table cell in IE11 / Edge, you have to use `contenteditable="true"` to be able to see focus, and when working with multiple paragraphs within a table cell, you can not cycle trough the paragraphs using your arrow keys.

http://fiddle.tinymce.com/jPfaab

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
