### ISSUE TITLE
TinyMCE comments out SVG style tag content, browsers then ignore tag's content

### ISSUE THREAD

**Issue by Fiona-TU** [tinymce/tinymce#3618]
**Do you want to request a *feature* or report a *bug*?**
bug, maybe (?)

**What is the current behavior?**
When inserting some SVG-element and using the style-tag inside the svg-tag, TinyMCE comments out the content of the svg style tag.

Example:
```
<svg width="100%" height="100%" viewbox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
<style>
circle {
      fill: orange;
    }
</style>
<circle cx="50" cy="50" r="40"></circle>
</svg>
```

While the syntax 
`<style></style>`
**will work for the HTML style tag**, for some reason browsers don't apply the defined styles for SVG-elements.
See the following fiddles:
style tag content not commented out: https://jsfiddle.net/jytzgmn6/
style tag content commented out: https://jsfiddle.net/9yvjaomc/

Both variants pass the W3C HTML5-validator.

**What is the expected behavior?**
TinyMCE should handle svg style tags in such a way that browsers respect the defined styles and don't ignore them because they are commented out.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Current TinyMCE Version, various browsers (Firefox, Chrome, IE)

**Comment by tran136** [comment]
I also get stuck in this issue, could anyone give me solution for this? I really need it for my project. Thank you.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
