### ISSUE TITLE
Can't create a list inside a definition

### ISSUE THREAD

**Issue by ignaciogros** [tinymce/tinymce#3620]
**Steps to reproduce:**

Add a definition list:

```
<dl>
    <dt>Term</dt>
    <dd>
        <p>Definition A.</p>
        <p>Definition B.</p>
    </dd>
</dl>
```

Select the paragraphs of the definition and click on any of the list buttons (bullet or numbered).

I expected this:

```
<dl>
    <dt>Term</dt>
    <dd>
        <ul>
            <li>Definition.</li>
            <li>Definition.</li>
        </ul>
    </dd>
</dl>
```

But I got this:

```
<ul>Term
<p>Definition.</p>
<p>Definition.</p>
</ul>
```

- I'm using 4.6.
- 4.3 had the same behavior.
- It worked in 3.5.x

Thank you very much.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
