### ISSUE TITLE
Local File Picker Not Working

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce#3621]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Click on the local file selection button
Select a local file
Source URL field is not update

Also reported via chat on our site:
https://ephox.slack.com/archives/C3J25EEG2/p1493980377762480

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.
It is reproducible at https://www.tinymce.com/docs/demo/file-picker/

**What is the expected behavior?**
Pick a local file, and have the URL inserted into the Source field

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
The latest version, 4.6

**Comment by spocke** [comment]
This wasn't really a bug but rather the codepen that was incorrect and also using somewhat internal apis. I guess these apis are now no longer internal. :(

I updated the codepen so that it does the somewhat proper thing. We might need to make that thing even more strict now since it's a public api.

**Comment by spocke** [comment]
As for the customer issue there is no way for us to fix that since the browser doesn't provide an synchronous api for converting blobs to base64. Will need look into option is this is a common thing that people want to do.
