### ISSUE TITLE
When font size is changed at the end of the line and enter is pressed, new line gets the height of the larger font size

### ISSUE THREAD

**Issue by thiagolacerda** [tinymce/tinymce#3623]
Steps to reproduce:
1. Type something in the editor with a large font size -> 72, for example)
2. when done writing, change the font size to a smaller size -> 10, for example)
3. Hit enter and type something
4. New line will have 10 as the font size, but the line vertical spacing will be as if we had 72 as the font size

Expected:
New line would have font size as 10 and corresponding vertical spacing

The problem is that when we have a text with size 72 and change the size at the end of the line, we will have this:
`<span style="font-size:72pt">Text<span style="font-size:10pt"</span></span>`

And when we hit enter, that span hierarchy is pushed down to the new line.

**Comment by thiagolacerda** [comment]
Any updates on this issue?
Thanks

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
