### ISSUE TITLE
Random <g> tags being inserted into HTML

### ISSUE THREAD

**Issue by trigdev** [tinymce/tinymce#3625]
This bug seems new and have noticed it effecting more and more people.

I have not been able to replicate this myself however it is definitely happening to other people that use our system. For some reason the tinymce WYSIWYG is inserting random <g> tags into the HTML code. Below is an example:

`<p class="Normal"><g class="gr_ gr_326 gr-alert gr_gramm gr_run_anim Grammar multiReplace" id="326" data-gr-id="326">Its</g> been another busy and productive few weeks at...</p>`

If you search for **<g class="gr_** in google, you can see that heaps of other websites are having the same issue because this is being rendered into their content which is I assume is being created tinymce.
https://www.google.com.au/search?q=%3Cg+class%3D%22gr_&oq=%3Cg+class%3D%22gr_&aqs=chrome..69i57j69i59l3j0l2.343j0j7&sourceid=chrome&ie=UTF-8

This seems to be a recent/current bug because there are only a few questions about it on stackoverflow which have all been created 2017. Also the google results that show this <g> tag have all been indexed in 2017.

**Comment by spocke** [comment]
This is grammarly injecting these elements since that it not our product and we have no control over that we can't do much about this. Since the element "g" might be used for something else except grammarly.

**Comment by trigdev** [comment]
You are correct! This explains why I could never replicate the problem. Once I installed Grammarly I instantly was able to replicate it. It looks like Grammarly do not provide an API/Developer reference so there seems to be no way to prevent this? It's a concern when you see the amount of users this bug is affecting. The only solution I can think of is to use a regex function to remove all of the <g> elements.

**Comment by trigdev** [comment]
I have implemented the javascript replace function when getting the tinymce content:
`content.replace(/<\/?g[^>]*>/g, "")`
This has resolved the problem for us. I have also reported the bug to Grammarly, hopefully they can fix this on their end.

**Comment by FortisFortuna** [comment]
BeautifulSoup's unwrap() function can also help remove the <g> tags.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
