### ISSUE TITLE
TinyMCE Instance stuck on adopted width after window/screen resizes

### ISSUE THREAD

**Issue by donShakespeare** [tinymce/tinymce#3635]
![4aa2634c-8ca5-49c5-9ebd-cd4e49059c19](https://cloud.githubusercontent.com/assets/5103329/25917698/cc0466aa-357d-11e7-92b2-77bf33015a46.GIF)
https://www.tinymce.com/docs/changelog/#version460-may42017
>FIXED so that width/height of the editor gets taken from the textarea element if it's explicitly specified in styles.

**The consequence of this:**
1. If original Textarea is 100%, TinyMCE will adopt 100% = No issues!
2. If original Textarea width is not 100% TinyMCE will be stuck on fixed width; 
Therefore all else will resize except TinyMCE since, naturally, the CMS Window resize listener does not extend to the TinyMCE container DIV.

Now users have to apply a resizing script to listen for window changes,
**OR**
Manually set all TinyMCE main container DIVs to width of 100% (in head of page or TinyMCE init)

```
if(!$("#my_fluid_rte").length){
  $("head").append("<style id=my_fluid_rte> mce-tinymce[role=application]{width: 100%!important;}</style>");
}
```

I am sure this affects height too, but it did not cross my radar.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
