### ISSUE TITLE
Line feed after <br> tag is replaced with an additional space

### ISSUE THREAD

**Issue by Georg-Git** [tinymce/tinymce#3643]
TinyMCE v4.6.1: 

Steps to reproduce:
TinyMCE Full featured demo, click Tools > Source Code.
Enter:
```
<p>line 1<br />
line2</p>

```
Click OK, Open Tools > Source Code again.
Expected result:
```
<p>line 1<br />
line2</p>

```
Actual result:
`<p>line 1<br /> line2</p>`

=> The line feed after the `<br /`> tag is stripped away - and furthermore an additional space is inserted after the `<br />` tag.

By the way:
Why is the line feed in the html source code stripped away??
With line feeds in front of every `<br />` tag the html source code in the source code editor is much more easier to read!

**Comment by Georg-Git** [comment]
In wiki for tinymce 3 it is explained why replacing linebreaks with a space is a feature - and not a bug.
[http://archive.tinymce.com/wiki.php/Configuration3x:remove_linebreaks](url)

Ok - but in tinymce 4 it is not possible to disable this option anymore?

Or another way round:
What about auto insert linebreaks after the br tags?
As already done after every /p tag.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
