### ISSUE TITLE
Floating an IFRAME

### ISSUE THREAD

**Issue by ignaciogros** [tinymce/tinymce#3665]
**Do you want to request a *feature* or report a *bug*?**

A feature (but it's not the expected behavior).

**What is the current behavior?**

You can't float an IFRAME using "alignleft" or "alignright".

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.

- Add an IFRAME and write some text right after it.
- Click on the IFRAME.
- Click on "Align left".

Nothing happens.

**What is the expected behavior?**

That should float the IFRAME.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

It didn't work in previous versions.

**Thank you!**

**Comment by sitecarp** [comment]
I would also like this behavior. Ideally, embedded media placeholders would behave much like images in the editor, allowing similar resizing and alignment functions, and possibly even having the caption option. Most-importantly, the float option.

**Comment by sitecarp** [comment]
@spocke Is this under consideration? It seems like it would be a simple reapplication of code which already exists for images, applying `style="float:left;"` to the <iframe> element itself when the left-align icon is clicked. But I don't know the inner-workings of that feature.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.

**Comment by shanereichart** [comment]
@thedrjim This functionality is still desired. Can you reopen the issue? It seems beneficial over creating a new one, which I will do if you prefer.

**Comment by thedrjim** [comment]
ok, we are going to reopen your ticket and mark it as a Feature.

**Comment by shanereichart** [comment]
Are @ignaciogros and I the only ones trying to float embedded iframes/media similarly to images? It seems like it would be a common action, and simple fix for someone who is already familiar with the image plugin. I'm genuinely trying to understand how this issue has persisted for so long without activity here. Maybe others don't left or right-align images as often as my team and my clients do, so they haven't noticed this functionality is missing from iframes? Is there something strange about our request that I'm missing?

**Comment by Daijobou** [comment]
Any update? i can't center videos. I always have to edit this via the source editor.
