### ISSUE TITLE
How create floatpanel ?

### ISSUE THREAD

**Issue by Clemweb** [tinymce/tinymce#3668]
Hi,

I'm creating a custom plugin for Tinymce. I simply add a custom menubar button which display a new WindowManager with some options.
After validate window's options, I insert HTML content in Tinymce editor. All of this work's fine.

But I want to add to this custom HTML a floatpanel (like on table and image) with my own icons and actions. It must be 'attach' to my content with a class I suppose ?

I believe that it can be achieve with tinymce.ui.FloatPanel but the doc is poor.

Someone can help me by a sample code ?

Thanks a lot

+++

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
