### ISSUE TITLE
Custom plugin inline toolbar

### ISSUE THREAD

**Issue by CSI68** [tinymce/tinymce#3673]
Hello,

I need to create a new Tinymce 4 plugin wich display a new inline toolbar like image tool. (cf screenshot)

![inline-toolbar](https://cloud.githubusercontent.com/assets/2900776/26307972/837853b4-3ef7-11e7-84f1-d27646681451.jpg)

Is it possible ? If yes how to do it ?

Thanks for helping

Clément

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
