### ISSUE TITLE
Leading and trailing whitespaces being removed from text inside tag when setContent is called

### ISSUE THREAD

**Issue by thiagolacerda** [tinymce/tinymce#3675]
Steps to reproduce:
1. call setContent with some html that has leading and trailing whitespaces, like:
`tinymce.activeEditor.setContent('<div><span style="color: blue;">      Text with leading and trailing whitespaces     </span><span>followed by text with different formatting</span></div>');`
2. call getContent()

Expected:
Whitespaces can be used to perform content alignment with rest of the content, so they should be kept.

I also used the whitespace_elements attribute when calling tinymce.init, in order to include span as an element where whitespaces are not removed. When parsing the content, the whitespaces are not removed, but it is not shown in the editor as whitespaces, because they are not set as &nbsp.

As a side note, during the investigation of this issue, I thought that setting entity_encoding to named, when creating a new Serializer in setContent would fix that, since there is a map of char to replace, including ' ' -> &nbsp. But the encodeNamed function in Entities.js never matches the text with spaces with the textCharsRegExp.

Due to that I have some more questions:
1. Is the textCharsRegExp in Entities correct for named encoding? Because seems that it will never match with the char map that named encoding has.
2. Shouldn't entity_encoding and entities be forwarded to the settings parameter in Serializer creation, since it looks for those props in the settings object (https://github.com/tinymce/tinymce/blob/136c0341aa9f43b720d5942498ed1796f1cb2ccf/src/core/src/main/js/html/Writer.js#L46)? I'm referring to the Serializer created when setContent is called.

Having entity_encoding as a valid parameter of setContent args and forward it to the Serializer and also having the textCharsRegExp match the entities in the settings.entities attribute might be an option to preserve whitespaces.

If that is not the correct approach, maybe having that as an option (to preserve whitespaces) in the editor settings would be a nice approach to make the editor honor the content that was passed to setContent.

Thanks

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
