### ISSUE TITLE
How to reduce the size of tinymce.min.js

### ISSUE THREAD

**Issue by k644606347** [tinymce/tinymce#3679]
The latest version of about 440k or so, does not contain the file under the plugins; I would like to know how to reduce its size

**Comment by alecpl** [comment]
Use compression on http level. There's not much you can do, I guess. However, I see it grows significantly from version to version. I don't know, maybe authors should consider removing some bloat (I see removing old browser support didn't help much). Especially when they tend to support mobile devices better in the future.

**Comment by k644606347** [comment]
Thanks, i intend to use gzip to improve and try to rebuild tinymce.min.js, remove modules that are useless to the project but hopefully not

**Comment by Daijobou** [comment]
Little history :)
Version 4.4.3 / 377KB
Version 4.5.5 / 396KB
Version 4.6.0 / 441KB
Version 4.6.2 / 449KB

**Comment by k644606347** [comment]
@Daijobou thanks, I am considering using the old version

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
