### ISSUE TITLE
New paragraphs being inserted around image tags

### ISSUE THREAD

**Issue by jacinabox** [tinymce/tinymce#3683]
This is a bug report. I have noticed that since version 4.6.0, HTML normalization has been inserting paragraph tags around image tags. So that an image tag like &lt;img src="foo"&gt; is being turned into
&lt;/p&gt;&lt;p&gt;&lt;img src="foo"&gt;&lt;/p&gt;&lt;p&gt;. It only happens when an image is dragged to an new location in a document.

This is causing a user experience problem for us, as when an image is dragged and dropped many times in succession, it (confusingly) inserts several new paragraph breaks.

The bug happens in Chrome and Firefox since version 4.6.0. Also it did not happen in version 4.4.3, the old version we were using.

**Comment by spocke** [comment]
Can you setup a test case at http://fiddle.tinymce.com that reproduces the issue so that we can look at it. Thanks

**Comment by jacinabox** [comment]
Sure, here is my test case: `http://fiddle.tinymce.com/oRfaab/2`. Instruction: please try dragging the image to anywhere inside the paragraph next to it. You will see that new permanent paragraph breaks are added.

**Comment by danwinterwijntjes** [comment]
Yes, I also experience this issue. It basically won't let you have an `<img />` tag in the middle of a paragraph. Instead it forced the text to split into two paragraphs.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
