### ISSUE TITLE
Safari Hangs When Editing Content

### ISSUE THREAD

**Issue by PigeonCoop** [tinymce/tinymce#3685]
This is a bug report

Safari 10.1 on Sierra crashes/hangs when editing email content. It is something peculiar to the content, is it the nested tables??? There is no debug in console, the browser just gives up.

See http://fiddle.tinymce.com/XQfaab press show blocks or click on the editor below the grey background area.

This works OK on Firefox and Chrome.

TinyMCE 4.6.2 Safari 10.1 on Sierra.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
