### ISSUE TITLE
Bug: Remove text change HTML in wrong way (Webkit)

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#3688]
I'm update from 4.5.5 to 4.6.2 and a old bug changed a little, maybe here is a way to solve this problem complete. I tried to make that example very simple.

in 4.5.5: Example: http://fiddle.tinymce.com/aRfaab
in 4.6.2 Example: http://fiddle.tinymce.com/bRfaab

Original source code:
`<div class="myDiv"><strong style="display: block; color: red;">Title</strong>Text</div>`

Test in **Webkit Browser**: In both cases select (double click) red "Title" and delete it and the line break in first line. 

Result in 4.5.5:
"Text" is now bold and red.
`<div class="myDiv"><strong style="display: block; color: red;">Text<br /></strong></div>`

Result in 4.6.2
"Text" is now bold and black, but only black because its overwritten.
`<div class="myDiv"><strong style="display: block; color: red;"><span style="color: #000000;">Text</span><br /></strong></div>`

Result should be:
`<div class="myDiv">Text</div>`

When I delete all text within a tag, the tag(s) should remove too.

Example:
`<span><em><b>Text1<b></em> Text2</span>`
Result should be after remove "Text1":
`<span> Text2</span>`
B and EM are removed

**Comment by Daijobou** [comment]
Can anybody confirm this?

**Comment by Daijobou** [comment]
Tested with Webkit Browser for version 4.6.6, bug still exists.

**Comment by Daijobou** [comment]
Issue exists in 4.7.12 for webkit browser. After remove red "Title", change "Text" to bold.

Firefox working fine. After remove "Title", "Text" is not bold and not red.

Edge shows "Text" after remove "Title" bold and red.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.

**Comment by Daijobou** [comment]
The error still exists in version 5.5.1.

**Comment by thedrjim** [comment]
Hi @Daijobou, we have looked into this and we can replicate the issue. However, we believe it's a browser bug due to how `display: block` behaves when added to inline elements. Since the HTML in your demo isn't semantic HTML, could you please explain your use case?

**Comment by Daijobou** [comment]
Thanks for the answer, you should keep it closed. If I do, then I edit the text via the source code editor anyway. ;-)
