### ISSUE TITLE
TinyMCE doesn't cancel list formatting if list item contains paragraph formatting

### ISSUE THREAD

**Issue by YLeight** [tinymce/tinymce#3695]
**Do you want to request a *feature* or report a *bug*?**
I think I found a bug.

**What is the current behavior?**
TinyMCE doesn't cancel `list` formatting if the list item contains `paragraph` formatting.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
- type some text line;
- apply list formatting to the line;
- apply paragraph formatting to the line;
- cancel list formatting from the line;
You can see the behavior in any demo on the official web site.

**What is the expected behavior?**
I expect the behavior of removing `list` formatting.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I have found the behavior in TinyMCE 4.6.2 in Google Chrome 58. It works correctly in TinyMCE 4.4.1.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
