### ISSUE TITLE
TinyMCE doesn't work on Firefox from WebExtension content script

### ISSUE THREAD

**Issue by edjroot** [tinymce/tinymce#3696]
**Do you want to request a *feature* or report a *bug*?**
Bug (but I'm not sure if it's on TinyMCE's or Firefox's side).

**What is the current behavior?**
I'm developing a WebExtension for Chrome and Firefox that uses a content script to replace an old editor on a certain page by TinyMCE.

On Chrome, it works perfectly. On Firefox, the editor is only partially "built" (the toolbar is there, but the editable area is not functional). Apparently, the `iframe` is not fully generated.
The Firefox console shows the following error message: "Promise rejection value is a non-unwrappable cross-compartment wrapper. (unknown)" whenever I scroll the page, and sometimes when I click any of the editor's buttons.

**Steps and minimal demo**
Create a WebExtension with a content script that creates a `textarea` and initializes TinyMCE (I'm using the jQuery version - `$('textarea').tinymce({})` -  and haven't tested the "pure" version).

[Demo](https://drive.google.com/file/d/0B0o0PakZaNefcUZlbmN5Tmk4ZUU/view?usp=sharing). Visit http://pixeljoint.com on Firefox to observe the behavior. Try to edit content and check the console.
(The problem happens on all websites, not just the one in the example.)

**What is the expected behavior?**
The editor should be functional and no error messages should appear.
The expected behavior is observed on the latest version of Google Chrome.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 4.6.1; Firefox 53 (and Chrome 58); Windows 10 and Ubuntu 16.04; I don't know if previous versions worked.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
