### ISSUE TITLE
Bug: Pasting into selection removes spaces

### ISSUE THREAD

**Issue by withinboredom** [tinymce/tinymce#3705]
**Do you want to request a *feature* or report a *bug*?**
This is a bug (duplicate in https://github.com/Automattic/wp-calypso/issues/14579)

**What is the current behavior?**
Pasting into a selection in Chrome is broken-ish.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. write a bulleted list of sentences such as:
 - I did this Sunday
 - I did this Sunday
 - I did this Sunday
2. Change the last word of the first item to Yesterday such that it reads:
 - I did this Yesterday
 - I did this Sunday
 - I did this Sunday
3. Copy "Yesterday"
4. Select a just the word "Sunday" and paste
5. End up with:
 - I did this Yesterday
 - I did thisYesterday
 - I did thisYesterday

![wp](https://cloud.githubusercontent.com/assets/1883296/26582764/4f8c7980-4510-11e7-9789-19c8f12adfd7.gif)

![wp](https://cloud.githubusercontent.com/assets/1883296/26612572/b15681ba-4583-11e7-8542-39a55a30767d.gif)

**What is the expected behavior?**

For pasted text to not remove spaces.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Chrome 58.0.3029.110 (64-bit) in OSX affected
Safari works fine

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
