### ISSUE TITLE
Server Side Rendering not working

### ISSUE THREAD

**Issue by OskarKlintrot** [tinymce/tinymce#3709]
**Do you want to request a *feature* or report a *bug*?**
Feature, unless SSR is supposed to be working

**What is the current behavior?**
When trying to render TinyMCE on the server side in an application using dotnet core and angular I get the following exception:

```
Exception: Call to Node module failed with error: Prerendering failed because of error: ReferenceError: navigator is not defined
```

I don't know if you have any plans to make TinyMCE to work with SSR but I open this just in case.

**Comment by Afraithe** [comment]
Not something we support or have anything to do with.

**Comment by OskarKlintrot** [comment]
Well, it's your code 😜

**Comment by OskarKlintrot** [comment]
In case someone ends up here I will just share [my solution/hack/bodge](https://gist.github.com/OskarKlintrot/8f3b684faeb93f8d2b0946f63b70bd61) to get TinyMCE to work with SSR using Webpack and Angular. Maybe not the prettiest solution but it works.

**Comment by terencechow** [comment]
@Afraithe this is 100% related to your code. You are using document / navigator expecting tinymce to have access to a DOM but in server side rendered code there is no such globals... You should consider supporting it because in 2017 server side rendered code is pretty much the standard.

**Comment by fyrkant** [comment]
@terencechow In what way would server rendering benefit TinyMCE? And how would it work? The editor is not very useful until the javascript has loaded.

**Comment by terencechow** [comment]
Server side rendering benefits the user because it avoids any flash of unstyled content and because its a quicker time to first meaningful paint. https://developers.google.com/web/tools/lighthouse/audits/first-meaningful-paint

Pretty much anytime there is content preloaded into TinyMCE makes it useful.

In my case I am making a CMS and having data preloaded to TinyMCE would allow the user to start reviewing their content immediately. Think about mobile users who have to wait for a loading screen while downloading and initializing a 250kb TinyMCE js, just to display some content vs having the content immediately displayed. The user might not make their first change (ie not need functionality) until they've read a bit of the content to remember where they were working on previously. In that case waiting for 250kb in a mobile scenario is the difference between waiting a few seconds (maybe even up to half a minute depending on 3g or 4g connectivity) and having data immediately displayed. It definitely has a perceived affect on the user, especially if they are travelling or on the move, etc. 

In terms of how it would work I can't say because I don't know how TinyMCE works internally. I would investigate making the "core" library not use anything DOM related. This would make it work well with any front end frameworks that use virtual doms, ie Angular, React, Vue, etc (basically all the front end frameworks in 2017). Jquery would then be a library on top of the 'core libary' since jquery requires accessing the dom.

**Comment by fyrkant** [comment]
I would then just show the content in some other way until TinyMCE is loaded and then replace it with the editor.

**Comment by jburghardt** [comment]
Is this issue still ignored ?

**Comment by Afraithe** [comment]
Yes, TinyMCE was not built to function this way, the DOM is very much core to how TinyMCE operates.

This issue was closed over a year ago.

**Comment by chaddjohnson** [comment]
[This gist](https://gist.github.com/zhangshine/00607fa3fe89195ef0a0e88983174b37) helped me get things up and running with Next.js. I tried following the documentation [here](https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/), but I was getting `ReferenceError: navigator is not defined`.

TinyMCE does not support server-side rendering (which Next.js provides out of the box), and so in order to self-host TinyMCE I had to conditionally load modules only on the client side; hence this:

```javascript
if (typeof window !== 'undefined'){
  require ('tinymce/tinymce');
  require ('tinymce/themes/silver');
  require ('tinymce/plugins/advlist');
  require ('tinymce/plugins/autolink');
  // etc.
}
```

Also, using `require.context()` with `file-loader` to copy skins resulted in errors since I am using a monorepo (via Lerna). This can be worked around using copy-webpack-plugin to copy "skins" files or by manually copying the "skins" files to the "public" Next.js directory.

**Comment by hnrtk** [comment]
import dynamic from 'next/dynamic';

const Editor = dynamic(
  () => import('@tinymce/tinymce-react').then((mod) => mod.Editor),
  { ssr: false },
);

**Comment by greyvugrin** [comment]
For those coming here for Nuxt specifically, I provided a solution on StackOverflow: https://stackoverflow.com/a/71329883/2514961

FWIW, this definitely isn't on TinyMCE to support SSR, it's a per framework thing.

**Comment by univan0928** [comment]
Hi, nice to meet you, I have same error, how to fix it? Thanks
