### ISSUE TITLE
Memory leak - same editor instance stored (too) many times to tinymce.editors

### ISSUE THREAD

**Issue by sactor** [tinymce/tinymce#3710]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

TinyMCE leaks memory when using jQuery initialization. After you remove an instance, it is still in the tinymce.editors array.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/yRfaab/2
Please note the example removes the editor on purpose to demonstrate the issue.

**What is the expected behavior?**

tinymce.editors should be empty after removing the last editor, instead one additional editor is left each time an editor instance is removed.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

4.6.2 and 4.6.3 at least, when initializing with the $.fn.tinymce() provided by the TinyMCE jQuery plugin. I did not notice this when using 4.4.x but cannot guarantee it wasn't a problem then.

I'm currently avoiding this problem by adding this to the add function before the editor gets pushed to the editors object, but the proper fix probably should avoid calling add in the first place:
```
if (typeof editors[editor.id] !== 'undefined' && editors[editor.id] === editor) {
  return editor; /* we don't want to add it again */
}
```

**Comment by OlivierJaquemet** [comment]
We did observe the same bug in our installation.

If you want to provide a workaround in your setup, to ensure there are no memory leaks, 
see TinyMCE plugin provided in the following fiddle : 
http://fiddle.tinymce.com/CSfaab/4

it will ensure tinymce.editors array never contains more than one insance of each editor, (thus any call of the remove or destroy method will work as expected)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
