### ISSUE TITLE
Inline Insert Option - Moves caret position to top

### ISSUE THREAD

**Issue by dougdot3** [tinymce/tinymce#3711]
BUG?

Using inlite theme, you can enable two options for inserting an image. Via the selection toolbar or via the insert toolbar.

When inserting using the selection toolbar, the image or link is placed in the correct location.

When using the insert toolbar, the image or link is placed at the top of the text area.

You can see this in the sample code repository:

https://codepen.io/tinymce/pen/Gqmkja

**What is the expected behavior?**

Using the 'insert' toolbar, you would expect the insertion to happen at the location of the caret when you choose insertion, instead of moving your insertion to the top of the text area.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Tested in Google Chrome and Safari. Behaviour is the same regardless of browser.

**Comment by dougdot3** [comment]
I should note as well that you can't disable the insertion toolbar [per this issue](https://github.com/tinymce/tinymce/issues/3087).

The above issue leads to inconsistent behaviour for users and a confusing experience. And because you can't disable the insertion toolbar we don't have the option of "muting" this functionality.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
