### ISSUE TITLE
IE11 invalid links cause the field to be counted as invalid

### ISSUE THREAD

**Issue by tgthormodsgaard** [tinymce/tinymce#3714]
I noticed that invalid links in IE11 are causing our forms to be seen as invalid and won't let us save our form.  Most of the links we are using against could be used as double encoded, but we have server side validation. Here is an example link http://www.foo.com%2Ffoo%2520bar that is marking the field as invalid.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
