### ISSUE TITLE
Cannot deselect contentEditable="false" elements in iOS

### ISSUE THREAD

**Issue by claviska** [tinymce/tinymce#3715]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

Using iOS, you can tap to select a `contentEditable="false"` element but it's not possible to deselect it.

Tapping outside the element _does_ place the cursor in the correct position, but the element remains selected and it becomes impossible to type.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Minimal test case: http://fiddle.tinymce.com/GRfaab/2

**What is the expected behavior?**

Tapping outside the `contentEditable="false"` element should deselect the element and allow you to continue typing.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

- Only appears to affect iOS
- Tested on iOS 10.3.2 on both iPhone/iPad

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
