### ISSUE TITLE
[bug] toolbar small insert icon missing

### ISSUE THREAD

**Issue by seltix5** [tinymce/tinymce#3718]
hi,

when using "toolbar_items_size: 'small'" the icon in "insert" is missing.
if not using the small size, the "plus" icon is working fine.

thank you.

**Comment by seltix5** [comment]
hi,
i just compare the normal font with the small version, and there is many icons missing, is that normal ?

<blockquote class="imgur-embed-pub" lang="en" data-id="9MPPHPB"><a href="//imgur.com/9MPPHPB"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
