### ISSUE TITLE
Bug: contextmenu position Internet Explorer

### ISSUE THREAD

**Issue by dimmelsw** [tinymce/tinymce#3719]
If the contextmenu in Internet Explorer is opened with the menu key instead of right click, the position of the menu is in the top left corner of the browser window.

Firefox and Chrome open the menu at cursor position, which is the expected behavior.

**Comment by SimonGivre** [comment]
Hi there,
Same problem here but even with latest Chrome. Context menu is disable but when you press on menu key => it scrolls at the top of the page.

Many thanks

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
