### ISSUE TITLE
Destroying inline mode instance leaves stylesheets in the DOM

### ISSUE THREAD

**Issue by pribilinskiy** [tinymce/tinymce#3722]
Destroying an inline TinyMCE instance leaves a CSS stylesheet in the DOM

In this fiddle click on the Editor then move the mouse away to complete the editor's lifecycle
http://fiddle.tinymce.com/cSfaab
Then look at the content in the `<head>` section in the iframe

![image](https://user-images.githubusercontent.com/3078595/26898090-688ddf22-4bd3-11e7-87c6-a38f877c42d7.png)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
