### ISSUE TITLE
UndoManager clear() breaks the first change

### ISSUE THREAD

**Issue by pribilinskiy** [tinymce/tinymce#3724]
After invoking **`undoManager.clear();`** the first change in the Editor is not considered as a change.
i.e. an **Undo state** is not added to the history and ther **Change event** is not triggered
http://fiddle.tinymce.com/dSfaab

**Comment by spocke** [comment]
You also need to add the initial undo level. The name clear would be odd if it also did that.
So undoManager.clear(); then undoManager.add(); we should probably update the docs.

**Comment by pribilinskiy** [comment]
@spocke I hardly see the logic for the necessity to invoke the `add` method after `clear`. 

Let's look at the docs:
```
clear()	Removes all undo levels.
add()	Adds a new undo level/snapshot to the undo list.
```

So, `clear()` removes all undo states.
Then a user makes an interaction, e.g. types a character.
Such action alone must add a new undo level/snapshot to the undo list, isn't it?

imho the need to use `add()` is kind of a workaround but not something that have any sense.

**Comment by spocke** [comment]
The undo manager works by comparing the current editor contents with the previous contents. If it doesn't have an initial value then it has nothing to compare against so a initial level needs to be added.

**Comment by pribilinskiy** [comment]
Sounds like a quirk, imho.
I didn't look into source code but let's look at at this simple example:

```
if (historyState !== newState || historyStates.length === 0) {
    // add history state
};
```

**Comment by spocke** [comment]
You need the initial state otherwise you can't go back to that inital state. Since clear removes all states you need to add the initial state the when a user makes a change that new state will be the first change that the editor sees. Level 0 is special but also a level but a level that can never be removed by the user. Possible the a new function called reset could do a clear and and add at the same time. But since this is not a commonly requested feature it's not something we have on our road map to add right now. We could maybe expand the docs to include details about how it operates.

**Comment by pribilinskiy** [comment]
> reset could do a clear and add at the same time

Sounds reasonable. 

Probably not many have used the `undoManager`.

**Comment by pribilinskiy** [comment]
I wondered why TinyMCE project have almost 700 unresolved issues, now I see )
We are thinking to move on to Froala, only 30 issues only, real bug fixing, not excuses.
The only drawback is that there's no decent File manager yet, and we already have already purchased a license for MoxieManager.

**Comment by pribilinskiy** [comment]
One more thing. I've noticed a very bad habit of closing issues without further discussion. Here are 2 examples:
https://github.com/tinymce/tinymce/issues/3694
https://github.com/tinymce/tinymce/issues/3704

**Comment by pribilinskiy** [comment]
@spocke Thanks for your support!

**Comment by sneakret** [comment]
Using the undo manager should not require the caller to know how it is implemented. I see no reason that clear() should require a subsequent call to add(). What is the use case for clearing the undo manager but _not_ re-establishing an initial state?

**Comment by TheSpyder** [comment]
This is tougher than it sounds. We can't fire the `change` event in `clear()`, because it requires both a previous undo level and a new one (unless we fire it with the new level as `null`, which seems weird to me).

Similarly we can't simply call `add()` inside `clear()` because that will trigger a series of events that are a bit misleading, as well as `editor.setDirty(true)` which would be incorrect.

I'm assuming the only reason to clear undo is when the content is cleared (e.g. the `cancel` button in the autosave plugin). Rather than risk breaking plugins that are working around this issue already, and that's hard because `editor.setContent()` doesn't clear the undo, perhaps we need a new method which:

* clears the content
* clears the undo manager in a way that ensures a level 0 is set without weird events firing (perhaps a new `reset` method, I'm not sure)
* sets dirty to false

Having a single method to do them all would avoid risks of breaking plugins that rely on the current behaviour.

**Comment by lnewson** [comment]
We've added a new function in 5.0.4 which will do all the items mentioned above by @TheSpyder. The new function is `editor.resetContent(initialContent?: string)`. If the `initialContent` argument isn't passed, then the editor will reset back to the initial content it was loaded with.
