### ISSUE TITLE
formatting gets lost while selecting all text and type some text

### ISSUE THREAD

**Issue by khushangmbhavnagarwala** [tinymce/tinymce#3726]
I have found this issue in v4.5.7 where I am applying any settings into the paragraph and select all text using Ctrl + A and write something then It will be losing all the formatting.

    $scope.textelementInEditorOptions = {
        inline: true,
        menubar: false,
        statusbar: false,
        plugins: 'textcolor colorpicker link paste',
        toolbar: 'bold italic underline strikethrough alignleft aligncenter alignright alignjustify link fontselect fontsizeselect forecolor backcolor undo redo',
        font_formats: font_names,
        fontsize_formats: "8px 10px 12px 14px 16px 18px 20px 22px 24px 26px 28px 30px 32px 34px 36px 38px 40px 42px 44px 46px 48px 50px 52px 54px 56px 58px 60px 62px 64px 68px 70px 72px",
        paste_as_text: true,
        forced_root_block: 'p',
        forced_root_block_attrs: {
            'class': 'myclass',
            'style': 'font-family: Open Sans; font-size: 32px;'
        }
    };

![c098bd3a-3fd6-11e7-9097-1fc27dad0918](https://user-images.githubusercontent.com/28893663/26925949-4838f8ec-4c69-11e7-8a84-65957daf5c26.gif)

Please help me to solve this issue. Is there any way to solve this?

**Comment by adeelraza** [comment]
+1 - I'm surprised this issue isn't brought up more often. This is not the intuitive behavior from a user's perspective. If they select all and type something new, they **do not** expect the formatting to be lost.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
