### ISSUE TITLE
I find a bug

### ISSUE THREAD

**Issue by MrLiufei** [tinymce/tinymce#3727]
**Do you want to request a *feature* or report a *bug*?**
*bug*
**What is the current behavior?**
*bug*

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
when the editor has three block, like this: 

> <div>
      <div id="my-editor">
          <p class="p1">first</p>
          <p class="p2">second</p>
          <p class="p3">third</p>
      </div>
   </div>
if i set fontSize to the .p1, then...at the same time set backgroundColor to the .p2 and .p3,,,,it also apply to the .p1......... but i didn't select the .p1......what happen?????
**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
4.5.5+

**Comment by ScarlettErin** [comment]
There may be a "last known great form" section beside the establishment guidelines, [assignment star](http://www.assignmentstar.co.uk/) yet I feel that is basically everything we can do.

**Comment by MrLiufei** [comment]
Well, okay, thank you very much. I think it's quite remarkable.I'm thinking about other approaches.

**Comment by tinydylan** [comment]
Hi,

Thanks for the bug report. I tested out your steps on a [demo page](https://www.tiny.cloud/docs/demo/full-featured/) and it seems to be working correctly. I suspect this bug has been fixed since you logged it. Please let us know if the bug still occurs for you.

Thanks!


<img width="776" alt="image" src="https://user-images.githubusercontent.com/41112113/79797886-6b349880-839b-11ea-8a7c-e5a219ac6f9e.png">
