### ISSUE TITLE
Image URL changes after entering text

### ISSUE THREAD

**Issue by eLRobbo** [tinymce/tinymce#3730]
I'm not sure if this is a bug or I just have an incorrect setting.

Using RoxyFileBrowser to upload images.  Tinymce (relevant) plugins:  image, imagetools.  Toolbar: image.  Images appear in tinymce image selector, and when selected appear in editor window.  The image url at this point is correct with "../../imageLocation," which can be verified by looking at source and the image is visible.  After adding text (either by typing it in the editor window or by pasting), the image disappears (displays x), and viewing source reveals that one of the leading "../" has been automagically removed (so the url now reads "../imageLocation."

If I manually go back in and add the leading "../" the image again appears.

tinymce 4.5.3, using Internet Explorer.  When using firefox, same behavior (except there appears to be no redraw so the image erroneously still appears, but that's obviously not your problem).

**Comment by eLRobbo** [comment]
Appears that this is resolved.  User error.

**Comment by eLRobbo** [comment]
Okay, it's still having some issues.  The image is there, it just doesn't display in the editor window until saving or refreshing.  So, again, add image, paste text, image disappears (although the url is now correct), until save.

**Comment by eLRobbo** [comment]
No, definitely still a problem.  Just appears to be intermittent.

**Comment by fyrkant** [comment]
Are you able to reproduce this problem in a [fiddle](http://fiddle.tinymce.com/)? It is really hard to get at the cause of the problem if we are not able to reproduce it in an easy way.

**Comment by eLRobbo** [comment]
Okay, it would appear we have localized the issue (which would be difficult, if not impossible to reproduce in jsfiddle).  If the URL for the page has a trailing /, everything seems fine (the image path saves correctly with the two leading ../../.  If the same page URL has NO trailing /, the image location is broken (../).  Unfortunately, there will be times when our site will have trailing / and times when it will not (site.com/controller/action/ vs site.com/controller/action/id).

Also, something that's a bit buggy (but not the main issue), is if you insert an image, and then paste text, the image may disappear.  However, when you insert an image, enter a line break (hit enter), and then paste text, everything is fine.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
