### ISSUE TITLE
Update special characters map dynamically.

### ISSUE THREAD

**Issue by lk-geimfari** [tinymce/tinymce#3732]
I want to update special characters when user select some options (`select box` is also custom). How can i do it?

How it's looks:
![image](https://user-images.githubusercontent.com/15812620/26974768-8fcd86ac-4d25-11e7-9a1d-4e71349c9e87.png)

I use this, but this is not work
```javascript
var _characterTypes = {...};
var SPECIAL_CHARACTERS = _characterTypes.math;

$('#character_type').change(function () {
    var id = $(this).children(":selected").attr("id");
    SPECIAL_CHARACTERS = _characterTypes[id];
});
```
```javascript
tinymce.PluginManager.add('charmap', function (editor) {
    var isArray = tinymce.util.Tools.isArray;

    function getDefaultCharMap() {
        return SPECIAL_CHARACTERS;
    }
    // ...
    // ...
    // ...
});
```

Is it possible to update characters array **dynamically**? When user select `math` charmap should be updated using new array of characters.

**Comment by lk-geimfari** [comment]
@spocke fyrkant 5 your minutes, please.

**Comment by fyrkant** [comment]
No there is no easy way to dynamically update the charmap, you should probably just append the characters you want with the `charmap_append` setting.

**Comment by lk-geimfari** [comment]
@fyrkant Oh, it's not cool. Okay, I'll think up of something else thanks!

**Comment by jayarjo** [comment]
@lk-geimfari rather than embedding selectbox into the dialog you could create custom dropdown button on the toolbar, that will modify `charmap` accordingly and then trigger the charmap dialog. 

Another option would be to load all symbols into the dialog and then simply filter them down according to the selected set (but in this case you will have to extend dialog functionality yourself).
