### ISSUE TITLE
Link boundaries not working with RTL text

### ISSUE THREAD

**Issue by edg2s** [tinymce/tinymce#3737]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
Cursoring just jumps straight over to the next character instead of staying in the same place visually, but activating the link.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
* Enter some RTL text and make a word a link, e.g. בבבבבב [בבבבבב](#) בבבבבב
* Place your cursor int the first (right-most) word and press right to move the cursor to the left
* Observe that when you reach the link boundary, the cursor jumps over the first character on the next keypress
* The expected behaviour is the same as with LTR text, that cursoring into a link doesn't move the cursor, it just activates the link, i.e. there are **2** cursor positions at the link boundary

**What is the expected behavior?**
The cursor stops for one arrow press while it enters the link

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Tested in Chrome+Ubuntu+TinyMCE edge

**Comment by edg2s** [comment]
Separately when I tried to save an example on http://fiddle.tinymce.com all my Hebrew characters were converted to question marks on save.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.

**Comment by edg2s** [comment]
The behaviour is less bad than it used to be, but it is still not working as expected.

**Comment by edg2s** [comment]
This issue is still relevant and I have added more details reproduction steps. Could you please re-open?
