### ISSUE TITLE
Inline editor table toolbar rendered incorrectly.

### ISSUE THREAD

**Issue by StartingDreams** [tinymce/tinymce#3738]
When you attempt to edit a table using the inline editor and the width of the editor container is less than 300px wide the table toolbar is rendered incorrectly.

The table toolbar covers the table, and the carrot is missing.

Demo of issue: http://fiddle.tinymce.com/uSfaab

The toolbar is absolutely positioned, and the width of the container should not affect the toolbar position.

Tested in: Chrome 58.0.3029.110, Firefox 53.0.3, and Safari 10.0.1

(type:bug plugin:table)

**Comment by Afraithe** [comment]
Confirmed in Chrome, but does NOT happen on Firefox.

**Comment by StartingDreams** [comment]
It's happening in firefox for me.

![image](https://user-images.githubusercontent.com/13548652/27195656-95cc5556-51d5-11e7-8699-fb5e3f2b20f8.png)

**Comment by mc0** [comment]
Is there any update on this?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
