### ISSUE TITLE
Impossible to select image in editor

### ISSUE THREAD

**Issue by Stadly** [tinymce/tinymce#3739]
When a TinyMCE instance is not shown when the page is loaded, but appears later, it is not possible to select images in the editor.

You can see the issue in action in this [Codepen](https://codepen.io/Stadly/pen/PjzEjj).

I have tested it in Chrome 58.0.3029.110, using TinyMCE 4.6.3.

**Comment by spocke** [comment]
Created a simpler fiddle that illustrates the problem: http://fiddle.tinymce.com/6Sfaab can be avoided by using editor.show() instead of using css however hard to know for a user or the tinymce api.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
