### ISSUE TITLE
aria-label attributes on buttons does not reflect localization

### ISSUE THREAD

**Issue by enwin** [tinymce/tinymce#3740]
Hi everyone

I'm having an issue with localization files and accessibility. I can see that buttons like “Bold” have an `aria-label` attribute and a tooltip on rollover describing the button. After loading a localization downloaded from tinymce servers the tooltip is updated with the correct text but the `aria-label` attribute remains in english.

You can test it [on the fiddle exemple](http://fiddle.tinymce.com/5Sfaab/1). Rollover is in french but the `aria-label` is in english.

I'm of course expecting the `aria-label` attribute to be localized as well as it's the attribute that is read by screen readers.

The fiddle is running with the edge version of tinymce.

Thanks for your feedback

Cheers

**Comment by afercia** [comment]
FWIW: related https://core.trac.wordpress.org/ticket/35710

**Comment by TheSpyder** [comment]
This is improving in TinyMCE 5 - the new UI framework places a much higher priority on accessibility, so strings like tooltips for buttons and labels on dialog components are correctly set for screen readers. It's not possible to get into a scenario like this in v5.

I'm not sure whether I can schedule time to fix this in v4. I couldn't find a quick solution looking around the code.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
