### ISSUE TITLE
font size of tinymce

### ISSUE THREAD

**Issue by emaeba** [tinymce/tinymce#3741]
HI!Sorry I'm bad at English.

I have a question with font size of tinymce.
It was good in the past.
But After upgrading,It is 11pt in the default state. Moreover, 11pt does not exist.

・Setting contents
fontsize_formats: '8pt 10pt 12pt 14pt 18pt 24pt 36pt',

Current status (4.6.3)
![tinymce](https://user-images.githubusercontent.com/15938466/27111098-bc639a14-50e8-11e7-836e-7699452d62ed.png)

Before(4.3.10) IT's OK
![tinymce2](https://user-images.githubusercontent.com/15938466/27111101-c1db0fd6-50e8-11e7-9468-df4fa49e4d5b.png)

**Comment by vanillajonathan** [comment]
You might want to check with 4.4 and 4.5 too.
Then if its problem in for example 4.6.3 but not 4.5 then try 4.6.1 and 4.6.2 to narrow it down.

Also use TinyMCE Fiddle to provide a test case.
http://fiddle.tinymce.com/

**Comment by spocke** [comment]
We recently changed so it shows the current computed css font size and font family we might need to add an option to disable this behavior. Some users when expecting it to show the current font values similar to how for example word works.

**Comment by emaeba** [comment]
Thank you!
I want to add fontsize option.

**Comment by jameslemon** [comment]
I'd really appreciate it if there was a way of disabling the behaviour that shows the computed css font size. It took me hours to realise that this was a feature and not a bug.

**Comment by jameslemon** [comment]
Is there any work around on this issue yet?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
