### ISSUE TITLE
URL is undefined on older versions of safari

### ISSUE THREAD

**Issue by muthu32** [tinymce/tinymce#3743]
I am getting URL is undefined on older version of safari in mac 10.6.28.
But I have managed to solve the problem by removing module 72.
I have changed this part of code in [tinymce.min.js 4.6.3](https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.6.3/tinymce.min.js) h("72",URL),g("6i",["1g","1s","25","72"] to g("6i",["1g","1s","25"]
Now after removed undefined URL variable is gone & works fine. But I am afraid that what are the consequences of removing module 72 ?
Is there any other way to overcome this error?
Same error is also occured on basic example of tinymce. 
https://www.tinymce.com/docs/demo/basic-example/

**Comment by fyrkant** [comment]
For better compatibility with older browsers we recommend using the 4.5.x branch or the editor, so try the 4.5.7 version of tinymce instead.

**Comment by timmetj** [comment]
+1 for a fix please in 4.6.x,

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
