### ISSUE TITLE
setContent being added to the undo/redo stack

### ISSUE THREAD

**Issue by thiagolacerda** [tinymce/tinymce#3745]
According to issue #3429 , setContent calls should not be added to the undo/redo stack, but I'm able to undo that command. See the steps to reproduce below (used TinyMCE fiddle with the latest version)

1. Open a fiddle
2. call setContent with any random text (you can see that the undo button continues to be grayed out)
3. type anything in the text area (e.g. add a space)
4. hit undo button (space is gone) and you can see that the undo button is still enabled
5. hit undo button again and the text that you set using setContent is gone

What is the final desired and "by design" behavior?

Thanks

**Comment by thiagolacerda** [comment]
Adding another scenario that I have just found, which I think it is related.

Follow steps 1 and 2 of the original post, but call setContent with a string with 2 words. Select the last word, cut and paste in the beginning of the content.
hit undo -> paste is undone (correct)
hit undo again -> editor content becomes blank

That does not happen if you type the same text in the editor and do the cut and paste steps again

**Comment by spocke** [comment]
A new undo level is added when you blur the editor. So setContent doesn't add an undo level but if you do something else like focusing out a new level will be added. So multiple setContent won't add anything to the undo stack.

**Comment by thiagolacerda** [comment]
Thanks for your quick response, @spocke 

I'm aware that blur calls UndoManager.add, but with my experiments, I assured that no blur event was fired. I'm also aware that setContent does not add level to the stack.

The main reason that I opened this issue was to point out the weird UX that is happening.
An example is when TinyMCE is used as an external component, that will have an initial content that is not known until the page is loaded, so such content is displayed in the editor through the setContent API:

1. Load page
2. call tinymce.init
3. init_instance_callback calls editor.setContent
4. user cuts content in the editor
5. regrets and hit ctrl-z
6. editor content is blank

Is that behavior by design?
It is possible to avoid this by calling undoManager.clear() followed by a undoManager.add() after setContent. The undoManager.add will set the initial undo stack state to be the text that I just set in the editor. But this solution seems really hacky IMO.
Is there a better way to overcome this?
What if the init settings would have a property to indicate the initial HTML content that the editor would have? This might fix the scenario that I just pointed out, at least.
I'm happy to help and submit a PR, let me know.

Thanks

**Comment by noobiek** [comment]
Hi,
I confirm that there is some issue with undoManager. Or, perhaps we use it wrong.
The scenario in our case is
1. We have a list of docs
2. User clicks to open doc#1
3. New instance of tinyMCE is initialized, doc is shown in view area, user doesn't focus (doen't start edit)
4. User clicks to open doc#2.
5. For all tineMCE editors we call ed.undoManager.clear() and ed.remove()
6. User focuses in to start editing. Ctrl+Z doesn't work yet.
7. User inputs several letters, Undo becomes available.
8. User presses Ctrl+Z several times and sees content of doc#1.

To fix this in init_instance_callback() after setContent() we call undoManager.clear() once more.

**Comment by thiagolacerda** [comment]
Hi @spocke and @fyrkant did you guys had a chance to look at this?

Thanks a lot

**Comment by WriterStat** [comment]
I can confirm this is still a problem with the current version of tinymce. Any help? This is really super dangerous when using tinymce on a google style automated text saving system. 

A user could easily lose everything without knowing or wanting to.

If you use the popup bubble menu. Once the above happens there's no way to get the text back. Because there's no text to highlight to trigger the bubble menu.

Undo button is not being turned off. Undo stack is not being reset. This should be escalated.

To reproduce:

- Use setContent to set the text of a tinymce editor to "any sentence".
- Or open an existing text in a tinymce editor.
- Highlight and remove any text anywhere in the editor.
- Highlight some text near the removed text then the undo button is enabled.
- Click the undo button. Text is put back. But undo button is still enabled. Should not be.
- Click undo again and yikes all pre existing text, all text is removed from the editor.

In a google style automated saving system...all your text pre-existing and any the user typed in is now gone in your database, because the undo button acidentally removed all the pre-existing text in the editor. 

Is there any way to clear the undo buffer/stack or reset it to make it clean after doing a setContent? So that it does not do the above? Thanks! =) Workaround? Are we doing something wrong? =)

I like tinymce, but the above is a show stopper until we can find out why if even 1 or two users accidentally do it.

Any solutions?

Thanks again for the great software and all the hard work, we really appreciate it.

I tested on Firefox and Google Chrome. With same results.

**Comment by WriterStat** [comment]
I'm going to try:
"To fix this in init_instance_callback() after setContent() we call undoManager.clear() once more."

To keep testing. But this does seem hacky as noted above.  Possibly a parameter/option for SetContent  to clear? Thanks again for everything and the great software.

**Comment by noobiek** [comment]
Hi WriterStat,

I just checked my code now. I don't exactly remember why (most probably by trial and error) I ended up with just 
undoManager.clear();
undoManager.add();
after I load new text into editor. And I have no problems since then. tinyMCE 4.6.4
Hope that helps.

**Comment by WriterStat** [comment]
I was able to just use: _ed.undoManager.clear();
_ed being the editor.
And put it after each setContent. Seems to work now.
Or in some instances instead of using the setContent function at all, I just instead included the initial html text for the editor in the tinymce html/div area with <?php echo $current_html_text;?> Which for me also worked and then had no problems with undo.

With that said, for anyone that didn't notice the undo problem with setContent, it could really bite them and their users. =)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
