### ISSUE TITLE
With forced_root_block=false, formatting can be incorrect if the text has P tags

### ISSUE THREAD

**Issue by wingedpig** [tinymce/tinymce#3748]
See [this fiddle](http://fiddle.tinymce.com/ISfaab/2) for an example. When the text has P tags, adding formatting to a line after hitting enter can cause the formatting to encompass more than the current line.

**Comment by fyrkant** [comment]
We generally do not recommend setting forced_root_block to false, like we say in [the documentation](https://www.tinymce.com/docs/configure/content-filtering/#forced_root_block): 

> Note that not using p elements as root block can severely cripple the functionality of the editor.

 So since you seem to have p tags in the editor I would recommend using the normal forced p tag behaviour.

**Comment by wingedpig** [comment]
We use TinyMCE as an editor for composing emails and we rely on the forced_root_block=false setting. We do our best to ensure that there aren't P tags in quoted replies to emails, but there still are some. In any case, it appears to be a bug in the code.

**Comment by ozzy1986** [comment]
This is sooo retarded. Dear tinymce developers, please get your brain back together and allow users to disable auto-paragraph insertion.
At the moment I am trying to use complex shortcodes in wordpress, but I can't because each time I save it the auto paragraph ruines all code turning it into complete mess. And p tags are even inserted unlogically.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
