### ISSUE TITLE
Underline Color Does Not Match Font Color

### ISSUE THREAD

**Issue by liukwrm** [tinymce/tinymce#3751]
I see this issue on tinyMCE version 4.6.4. It can also be replicated here: http://fiddle.tinymce.com/RSfaab

Steps to Repro:
1. Type "FOO" with black colored font
2. Underline (ctrl-u) "FOO"
3. Change color to blue, cursor at the end of "FOO"
4. Type "BAR"

Expected: "BAR" is blue with a blue underline.
Actual: "BAR" is blue, but still has a black underline.

This issue has been reported before: https://github.com/tinymce/tinymce/issues/2448 and https://github.com/tinymce/tinymce/issues/1026 . 
It is still reproing in 4.6.4. 

As stated before, the issue lies in the fact that the child spans do not inherit "text-decoration: underline" from their parent.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
