### ISSUE TITLE
Buggy behaviour on using bookmark function on files

### ISSUE THREAD

**Issue by Taygair** [tinymce/tinymce#3753]
I'm using this line on marking programmatically inserted files (image, audio, video). It worked well and looks like this:
`<img id="31c91540-8097-b8b3-5eca-40be0a68b61e" alt="mario" width="27%" src="../gallery/d3007cae-bd48-4b12-86de-0ff31649f313/image/31c91540-8097-b8b3-5eca-40be0a68b61e.gif" data-mce-src="../gallery/d3007cae-bd48-4b12-86de-0ff31649f313/image/31c91540-8097-b8b3-5eca-40be0a68b61e.gif">`

Then I added the following line to capture the bookmark of an image (in case it was selected by user) before switching to the gallery where all selectable files are stored:
`var fileBookmark = tinyMCE.activeEditor.selection.getBookmark();`

The behaviour (content in tinymce after inserting the chosen file) is as follows:
`<span data-mce-type="bookmark" id="mce_1_start" data-mce-style="overflow:hidden;line-height:0px" style="overflow:hidden;line-height:0px">
""
﻿<img id="31c91540-8097-b8b3-5eca-40be0a68b61e" alt="mario" width="11%" src="../gallery/d3007cae-bd48-4b12-86de-0ff31649f313/image/31c91540-8097-b8b3-5eca-40be0a68b61e.gif" data-mce-src="../gallery/d3007cae-bd48-4b12-86de-0ff31649f313/image/31c91540-8097-b8b3-5eca-40be0a68b61e.gif">
</span>`

Looks like the image is wrapped into that bookmark by tinymce.
The file (in this case: image) is displayed in tinymce as it should , tough where do that "" before the img tag come from?

BUT when reading the content out of tinymce by
`tinymce.get('texteditor').getContent()` the tag <img> and its content isnt there anymore!

Tested in latest versions of : Safari, Firefox and Chrome with tinymce 4.6.x

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
