### ISSUE TITLE
Can't override base style set by content_css, content_style or inline style/class set in block element

### ISSUE THREAD

**Issue by thiagolacerda** [tinymce/tinymce#3754]
The content_css and content_style properties are extremely useful to give the user a base and default style to start to write stuff.
But they also make the formatting of the editor **really** rigid, meaning that user can't, by any means, apply any formatting that overrides the content_style.
For example, open http://fiddle.tinymce.com/WSfaab

I have the content_style with font-weight set to bold. But, the user can't "unbold" any part of the text:

1. Type anything (text is bold)
2. make any selection and press the bold button -> nothing happens

If the content_style had ```font-weight: normal```, I could bold and unbold as I wish. So the behavior is really inconsistent here.

The same happens if we have inline style applied to a block element, or a class applied to a block element -> child spans can't unbold.

I gave the example here with bold, but it applies to any "toggleable" formatting like italic, bold or underline.

**Comment by thiagolacerda** [comment]
Hi @spocke and @fyrkant did you guys had a chance to look at this?

Thanks

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
