### ISSUE TITLE
Feature request: Custom template for img-tags for responsive images

### ISSUE THREAD

**Issue by OskarKlintrot** [tinymce/tinymce#3757]
**Do you want to request a *feature* or report a *bug*?**
Feature

In MCImageManager you could change the way the img-tag would look like (if I understand it correct, haven't tried it myself) by doing something similar too:
```
imagemanager_insert_template : '<img src="{$url}" width="{$custom.width}" height="{$custom.height}" />'
```

This would be extremely useful to have in the image- or image tool-plugin so that you can change all img-tags to contain `sizes` and `srcset` to get better support for responsive images. For example if the back end where you upload the images to resizes the image for mobile use you can add something like `$url + ?view=mobile` to `srcset` (for example):
```
<img src="{$url + '?view=mobile'}"
     srcset="{$url + '?view=desktop'} 1024w, {$url + '?view=table'} 640w, {$url + '?view=mobile'} 320w"
     sizes="100vw"
     alt="Responsive example" />
```

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
