### ISSUE TITLE
How to get iframeElement & iframeHTML in inline Mode?

### ISSUE THREAD

**Issue by mravinash** [tinymce/tinymce#3759]
Is there a way to access iframeElement & iframeHTML in inline Mode as its there in the default mode?
![screen shot 2017-06-22 at 2 03 24 pm](https://user-images.githubusercontent.com/16475802/27424778-cb453a58-5753-11e7-9eb9-7d51fcb75246.png)

Inline Mode doesn't have that in the editor_object.
Console.log(editor) to get the object.

TinyMCE 4

**Comment by fyrkant** [comment]
You can use the `editor.getBody()` to get the main element of the editor (a body element in iframe editor and whatever element you initialize the editor on in inline mode).

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
