### ISSUE TITLE
In IOS WebView, the cursor cannot be set on a previously typed word. The popup Select/Select All appears and cursor doesn't appear

### ISSUE THREAD

**Issue by doublecheese** [tinymce/tinymce#3760]
**Do you want to request a *feature* or report a *bug*?**
Bug Report:

**What is the current behavior?**
Inside an iOS Webview, if I type a few words and tried to click on a previously typed word to set cursor back and edit. It doesn't work and shos the Select/Select All popup

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

I'm using version 3

**Comment by fyrkant** [comment]
You are using version 3 of TinyMCE? If so, please try to upgrade to the latest version and see if it works better.

**Comment by doublecheese** [comment]
I have tried it and is the same behaviour. The cursor wont go in a precious
text and the Select/Select all popup keeps coming up

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
