### ISSUE TITLE
Clicking "Edit Image" During Slow Image Upload Yields Error

### ISSUE THREAD

**Issue by mcavalletto** [tinymce/tinymce#3762]
Observed with TinyMCE 4.6.2 in multiple browsers.

Our images_upload_url script often takes a couple of seconds to transfer the image it has received to a CDN, store the metadata in our database, and return a new image URL.

If you click the "edit image" button on the image toolbar while the upload process is still underway, the edit image panel does not appear and a JavaScript error is logged in the browser console.

To reproduce in an editor with the imagetools plugin enabled:
- embed an image into your editor, 
- click on the image to bring up the image toolbar,
- click any of the the "flip" or "rotate" buttons,
- quickly click on the "edit image" button.

It will be easier to reproduce this problem if you use a very large image, or if you introduce an artificial delay in the server-side script that handles your images_upload_url submissions, such as a sleep(10) statement or its local equivalent.

It may be that there's simply no good way for TinyMCE to handle an edit request before the upload has completed, but in that case I would expect that the "edit image" button would be temporarily disabled, or would provide some kind of feedback when clicked, rather than silently failing with an console error.

![screen shot 2017-06-23 at 4 39 50 am](https://user-images.githubusercontent.com/230561/27473721-1ce305fa-57ce-11e7-851e-dba0c5000795.png)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
