### ISSUE TITLE
Tinymce inlite editor appears before the highlighted text.

### ISSUE THREAD

**Issue by karkavi980** [tinymce/tinymce#3776]
Bug

Tinymce inlite editor appears before the highlighted text.
This is reproducible in https://codepen.io/anon/pen/zzpPWR.
Use split screen setting. 

**Setting used:**

tinymce.init({
  selector: 'div.tinymce',
  theme: 'inlite',
  plugins: 'image table link paste contextmenu textpattern autolink advlist autolink lists image charmap print preview hr anchor searchreplace wordcount visualblocks visualchars code fullscreen nonbreaking save table contextmenu directionality template textcolor colorpicker textpattern noneditable',
  insert_toolbar: '',
  selection_toolbar: 'bold italic blockquote subscript superscript outdent,indent textcolor alignleft aligncenter alignright alignjustify bullist numlist,forecolor,backcolor',
  inline: true,
  paste_data_images: true,
  content_css: [
    '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
    '//www.tinymce.com/css/codepen.min.css']
});

Please see the below image for reference.
<img width="908" alt="toolbar_issue" src="https://user-images.githubusercontent.com/17291013/27653591-6574996c-5bf4-11e7-8fd7-2bf43539b4a7.png">

**What is the expected behavior?**
the toolbar should not overlap the text.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

We are using 4.6.2 and it is getting reproduced both in Chrome and Edge.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
