### ISSUE TITLE
URL character conversion when initially adding Url on text or image

### ISSUE THREAD

**Issue by Figgsaurus** [tinymce/tinymce#3783]
Do you want to request a **feature** or report a **bug**?
**Bug**

**What is the current behavior?**
When inserting url like {{ SiteURL }}  it converts the URL to {{%20SiteURL }} when updating it saves correctly as {{ SiteURL }}.

Why url like {{ SiteURL }} ? I use the editor to create mail templates.  For example have "mail tags" which get replaced at run time eg {{ SiteURL }} which gets replaced with a specific URL when a mail is sent.

Link to fiddle:
http://fiddle.tinymce.com/lUfaab/1
I have added the URL in link list for ease.
To replicate issue, highlight Site Link text, click insert -> link or link icon. Select "Site URL" from Link list or manually add {{ SiteURL }} in Url field. Then click on edit link or view source to see that the link was converted to {{%20SiteURL }}. If you select Site URL from link list or change the Url field again to {{ SiteURL }} and click Ok, it then it adds it correctly as {{ SiteURL }}. This only occurs when setting the url initially, but works correctly when updating. Remove URL and add again to see %20 being added. It also only replaces the first space with %20 and not the second. 

**What is the expected behavior?**
Expected behaviour is that it does not alter the URL.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
This issue started occuring from 4.6.0 to current 4.6.4 version. It worked correctly on previous versions from atleast 4.0.22 to 4.5.7

**UPDATE:**
Issue for image links started from 4.5.3, same issue started for text links from 4.6.0
Images: http://fiddle.tinymce.com/oUfaab/1
Bug is perhaps related to this? Issue seems to be happening since this fix was implimented https://github.com/tinymce/tinymce/issues/3469

**UPDATE 2:**
Found the issue on line 29898 of tinymce.js dev 4.6.4 mceInsertLink function.

`// Spaces are never valid in URLs and it's a very common mistake for people to make so we fix it here.
value.href = value.href.replace(' ', '%20');`

Note, this code only runs on initial insertions and not when updating links.
It also does not replace all spaces either it seems, which makes it kind of pointless.

Is there a workaround for this? If I do not want spaces to be replaced with "%20"?
Can I override this function somehow?

**Comment by Figgsaurus** [comment]
**Update 3**

For anyone interrested here is a temporary workaround
http://fiddle.tinymce.com/wUfaab/3

It overrides the `mceInsertLink` command in the setup.

It is the exact same code used in the core with this line removed:
`value.href = value.href.replace(' ', '%20');`

**For those who want all spaces to be replaced with %20** 

You should use this override as well, just uncomment this line of code in the above fiddle:
`value.href = value.href.replace(/\s+/g, '%20'); `
It will replace all spaces with %20 instead of just the first one.

**Comment by WouterTinus** [comment]
Ran into the same issue, thanks for the workaround!

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
