### ISSUE TITLE
changing mode (setMode) inside editor.on("init", ...) causes editor to be in a half readonly state

### ISSUE THREAD

**Issue by zenorbi** [tinymce/tinymce#3787]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
- If you init the editor in readonly mode
- and in the `editor.on("init", ...)` callback you change the mode using `editor.setMode("design")`
- The editor's UI will show in "design" mode, but the iframe's content will have `contenteditable="false"`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/zUfaab

**What is the expected behavior?**
I expect the editor the be either in a fully readonly or fully design mode.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE version: 4.6.4
Reproduced in:
- Chrome Version 59.0.3071.115 (Official Build) (64-bit)
- Firefox Version 54.0.1 (64-bit)
- Safari Version 10.1.1 (12603.2.4)
- Internet Explorer 11.413.15063.0 Update version 11.0.43
- Microsoft EdgeHTML 15.15063 Microsoft Edge 40.15063.0.0

**Comment by fyrkant** [comment]
Why are you initialising the editor in readonly if you are going to change it back directly after it is initialised?

**Comment by zenorbi** [comment]
@fyrkant We have a content editor window which starts in a readonly mode but once the content json loads and you have edit access to it, the readonly restriction is lifted. Rarely if the computer is too slow the json successfully loads while tinymce is initing, thus once the tinymce init completes the restriction needs to be lifted.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
