### ISSUE TITLE
Can't toggle bold (also italic and probably underline) when content has another style property

### ISSUE THREAD

**Issue by thiagolacerda** [tinymce/tinymce#3792]
Please open this fiddle: http://fiddle.tinymce.com/4Ufaab

1. put cursor in the middle of "string"
2. press bold button, in order to unbold the text
3. without moving the cursor, press bold again, to bold the text back

expected:
"string" should be bold again

actual:
nothing happens

some preliminary analysis:
When you first press bold (to unbold the text) "string" gets split into 2 span nodes as you can see below:

```
<div>
  <span style="font-size: 12pt; font-weight: bold;" data-mce-style="font-size: 12pt; font-weight: bold;">Testing</span>
  <span style="font-size: 12pt;" data-mce-style="font-size: 12pt;"> str</span>
  <span style="font-size: 12pt;" data-mce-style="font-size: 12pt;">ing</span>
</div>
```

then, leaving the cursor exactly where it was, it will place it in the middle of the two spans

This seems to be broken since forever (tested with several versions of TinyMCE)

Used Chrome on mac

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
