### ISSUE TITLE
Has http://archive.tinymce.com/develop/bugtracker_view.php?id=5671 been fixed?

### ISSUE THREAD

**Issue by mario6097** [tinymce/tinymce#3793]
Has http://archive.tinymce.com/develop/bugtracker_view.php?id=5671 been fixed? Is so, how, where? 

I have reproduced the example by yfir over there which shows the bug, and it seems that tinyMCE  is still buggy.
Your help is welcome. 
mario

**Comment by fyrkant** [comment]
No it doesn't work to put required on the textarea, but it might be an interesting feature to look into adding.

**Comment by mario6097** [comment]
Hi
it seems a bug, not a missing feature, doesn't it?

**Comment by fyrkant** [comment]
I guess it depends on how you look at it, but as it is a feature that we have never implemented I don't think it is a bug that it doesn't work. It won't "just work" as it does with a simple textarea because the textarea gets hidden and replaced with the rich text editor when tinymce is initialised so the html5 validation doesn't work as expected. But like I said, it might be something worth looking into if we can get it working in some way.

**Comment by mario6097** [comment]
Hi
sorry to insist, but which "feature that we have never implemented " are you thinking about? Anyway, a simple work around is not to have textarea field as required. I do not have an understanding of tinyMCE code, how hardwould be to fix it (or add as a new feature)?

**Comment by fyrkant** [comment]
The html5 validation that works with inputs where you can set stuff like `required` only works on normal inputs, the TinyMCE editor is not a normal input element so it doesn't work with the html5 validation "out of the box", so the feature I am talking about is to get the editor to work with the validation. 

Sorry, I can't give an estimation of how hard and when/if we can do this, but we will discuss it internally.

**Comment by mario6097** [comment]
:-)
