### ISSUE TITLE
Inserting table always on top of content in IE11

### ISSUE THREAD

**Issue by mrrohitkaushal** [tinymce/tinymce#3800]
Using the Tinymce editor with iframe, It always inserts the table on the top of the content but in case without iframe its working fine.

But as per our requirement we can use it within iframe only. is there any resolution for this compatibility issue in IE11.

**Comment by fyrkant** [comment]
This seems to work as expected for me, see [this fiddle](http://fiddle.tinymce.com/KUfaab). I can insert table in the middle of the content.

**Comment by fyrkant** [comment]
Can you reproduce the problem in a fiddle?

**Comment by mrrohitkaushal** [comment]
Yes, this is working fine as shown in fiddle.

But we are using this html file in another html file using html iframe tag.
i.e. 
<html>
<body>
	<iframe src="TinymceTest.html" width="500" height="500"></iframe>
</body>
</html>


TinymceTest.html contains content for all components as displayed in fiddle.


there it is loading all its components but not able to insert component in IE.
Always take cursor to the starting point.

**Comment by mrrohitkaushal** [comment]
@fyrkant Did you get my point?
need more explanation.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
