### ISSUE TITLE
Bug: Tooltip position is broken by combination of position:fixed and transform:translate

### ISSUE THREAD

**Issue by Nickproger** [tinymce/tinymce#3802]
![image](https://user-images.githubusercontent.com/1409078/28069112-eb80116a-6650-11e7-913f-760da430c124.png)

**Do you want to request a *feature* or report a *bug*?**
Bug.
The same issues as was closed before:
https://github.com/tinymce/tinymce/issues/2182
https://github.com/tinymce/tinymce/issues/3533
Why this PR wasn't marged?! It fix this problem!
https://github.com/tinymce/tinymce/pull/3030/files

**What is the current behavior?**
Move mouse over icons - tooltip has wrong position

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
https://jsfiddle.net/wkrzp4dc/

**What is the expected behavior?**
Tooltips should to have proper position.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
4.6.4

**Comment by DAbrashin** [comment]
+

**Comment by DAbrashin** [comment]
+

**Comment by asadovnikov** [comment]
annoying bug

**Comment by vovashevchenko** [comment]
-

**Comment by valenburm** [comment]
the same

**Comment by rndmerle** [comment]
Try to add position:static on body.

`getPos` util function from TinyMCE won't use `getBoudingClientRect` to get trigger element's position if the body isn't statically positionned (because left/top properties values applied on tooltip, which is a body child, wouldn't be accurate if body had margins for instance).

But using `getBoudingClientRect` is the only way to get the right element's coordinates when there is some parent on its own transformation layer.

**Comment by dotnetprofessional** [comment]
Ok, I think I know why this hasn't been fixed as its possibly an edge case scenario. If I run either Chrome or Edge browsers on my primary monitor (I have two), then it works as expected. However, if I use it on my secondary monitor it doesn't work and reproduces the original reported problem. So I'm not sure if that's a bug with the browsers or the product. I can repro this using the feature sample here:

https://www.tiny.cloud/docs/demo/full-featured/
