### ISSUE TITLE
Content changing to hyperlink after copying from word and pressing any key in IE

### ISSUE THREAD

**Issue by abhikapuria** [tinymce/tinymce#3807]
If I copy any content from word and paste in tinymce editor opened in IE and press space. The content is changing to hyper link. This is a behavior which is happening on https://www.tinymce.com/docs/demo/full-featured/ too

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
