### ISSUE TITLE
Selecting the line break extends the selection to nearby content

### ISSUE THREAD

**Issue by Silviu-Marian** [tinymce/tinymce#3810]
**Do you want to request a *feature* or report a *bug*?**
It's a **bug**

**What is the current behavior?**
Put a paragraph and then put a list. The resulting content is:
```html
<p>Wow here is a list:</p>
<ul>
	<li>First Item</li>
	<li>Second Item</li>
</ul>
```
Now if you select the first paragraph using **triple click** (triple click the paragraph) and hit bold, it'll also bold the list underneath. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/fVfaab/2

**What is the expected behavior?**

It should not extend the scope of the command when the line ending is selected. Here is the line ending
![image](https://user-images.githubusercontent.com/1747499/28164729-5c3e2e8a-67d9-11e7-9732-10b2df27d5f1.png)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Latest Chrome
TinyMCE version 4.6.4

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
