### ISSUE TITLE
A block style format doesn't wrap media embeds

### ISSUE THREAD

**Issue by ocean90** [tinymce/tinymce#3811]
**Do you want to request a *feature* or report a *bug*?**
A *bug*.

**What is the current behavior?**

Steps to reproduce:
* Go to http://fiddle.tinymce.com/hVfaab
* Press enter after the YouTube link, wait for the video
* Mark all content
* Select the _Wrapper_ style format
* View the source code

<img width="426" alt="editor" src="https://user-images.githubusercontent.com/617637/28170066-7a720fb0-67e4-11e7-8a2d-ee4c1877237b.png">

**What is the expected behavior?**

The expected behavior would be that there's only one `div.custom` element that wraps all the content.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Originally noticed in WordPress which is using 4.6.3 but the fiddle is using the latest stable version. Tested in Chrome.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
