### ISSUE TITLE
Formatting a single line affects all the other lines inside the same paragraph

### ISSUE THREAD

**Issue by touchaqb** [tinymce/tinymce#3816]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Formatting a single line in a paragraph makes all the other lines inside the same paragraph receive the same formatting.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1. Copy the following lines and paste inside TinyMCE:

This is a Heading
This is regular text

2. Select the first line in the editor and set its formatting to a heading type, as it wants to be;

Result: _both lines become headings_.

The bug can also be reproduced by adding some lines separated by _\<Shift-Enter\>_ and applying a format to one of them.

**What is the expected behavior?**
Only the first line should be formatted.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 4.6.4, the bug affects older versions aswell.

**Comment by Silviu-Marian** [comment]
I'm also having this issue.

**Comment by nodefiend** [comment]
our team is also experiencing this same issue

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
