### ISSUE TITLE
Expanding selection in Touch enabled Windows computers, does not work when formatting is applied form the menu

### ISSUE THREAD

**Issue by thiagolacerda** [tinymce/tinymce#3819]
This happens in IE/Edge in Windows 10, using touch.

1. Have an editor instance with content in it (the one in tinymce.com, for example)
2. Double click in a word to select it.
3. Expand the selection using touch, to select more words
4. Click in the Format menu and click Italic

Expected:
All selected content is italic
Actual:
Only the word that you first selected gets the italic style

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
