### ISSUE TITLE
Empty line after table cannot be removed when hit backspace on keyboard

### ISSUE THREAD

**Issue by qiupeing** [tinymce/tinymce#3823]
Description:
Empty line after table cannot be removed when hit Backspace on the keyboard. This issue only happens if the rich text div has parent with display: table-cell; attribute. Div B (parent without the attribute) is fine, I am able to remove the line when I hit Backspace. 

Step to Reproduce:
1. Go to http://fiddle.tinymce.com/AVfaab/3
2. Run
3. Insert a table in div A
4. Enter some text inside the table cell
5. Put the cursor after the table and hit Enter on keyboard
6. Hit Backspace on keyboard

Expected Output:
The empty line is removed

Actual Output:
The empty line after the table cannot be removed
![emptylineissue](https://user-images.githubusercontent.com/30065754/28351460-9ffa7b94-6c82-11e7-94a6-2a2d1925d417.PNG)

Browser: Google Chrome version 59.0.3071.115
TinyMCE: version 4.3.11

**Comment by qiupeing** [comment]
Any update regarding issue?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
