### ISSUE TITLE
alphabet list paste issue 

### ISSUE THREAD

**Issue by zainulhasan** [tinymce/tinymce#3824]
I am using tinymce editor version 4.0.28 and I am having issue when I copy alphabet list from word document to tinymce editor it automatically convert alphabet list to numeric list please suggest any solution. Thanks

![image](https://user-images.githubusercontent.com/10378868/28371922-c622be82-6cb7-11e7-954f-06127cdc12e5.png)

**Comment by MichaelFromin** [comment]
Does the problem persist in the most recent TinyMCE?

**Comment by zainulhasan** [comment]
yes, Latest version of TinyMCE also have this issues .

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - [https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
