### ISSUE TITLE
Bug: Window is not centered

### ISSUE THREAD

**Issue by gnuletik** [tinymce/tinymce#3831]
When opening a window in a plugin, the window is not centered horizontally.

If we put a long text, we can see it better.

Steps to reproduce:
1. Open this page: http://fiddle.tinymce.com/cWfaab/1
2. Click on the "Test example" button
3. See the opened window not centered

Expected behavior: It should be centered.

I don't know if it worked with previous versions.
It's happening with the last version ("edge").

Sorry if this was reported before. I couldn't find it.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
