### ISSUE TITLE
[Bug] Weird behavior concerning Header tag styles

### ISSUE THREAD

**Issue by thejamfx** [tinymce/tinymce#3840]
**Do you want to request a *feature* or report a *bug*?**

Bug report

**What is the current behavior?**

pasted content takes the last Header format

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

no special setup needed: fiddle.tinymce.com is enough to replicate this bug.

- Fill the editor with at least two lines of content (you can even try this on the official sites demo)
- Change both lines to any Header style (can be different ones)
- Select all and delete
- copy content from external source (in this case notepad)
- paste into editor

**What is the expected behavior?**

content should paste in with p tags instead of header ones

**Which versions of TinyMCE, and which browser / OS are affected by this issue? **

v4, chrome/windows 10

**Did this work in previous versions of TinyMCE?**

I do not know

note: if you add p tag content between the header formatted lines and do this the new content is in p tags :)

**Comment by thejamfx** [comment]
So I have to essentially backspace/delete twice? I already knew of this workaround but I felt it not as intuitive as it just going back to getting reset to p tag instead... especially if you were to say disable the statusbar or elementpath in the settings.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
