### ISSUE TITLE
ctrl+z moves cursor to the very beginning of the first line in Chrome (mac)

### ISSUE THREAD

**Issue by thiagolacerda** [tinymce/tinymce#3845]
TinyMCE does not keep the cursor in the same line when undoing typing.

Steps to repro:
1. open http://fiddle.tinymce.com/8Wfaab
2. place cursor in the end of the line and hit enter to create a new line
3. uncheck underline (you will see that the font-size gets removed, but this is already reported in #3817)
4. type anything and then hit ctrl+z

Expected:
New text should be deleted and cursor should remain on the current line
Actual:
New text is deleted but **cursor is moved to the very beginning of the first line**

Tested in Chrome in mac (but probably happens in other OSs as well)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
