### ISSUE TITLE
undomanager ignore is not working

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#3853]
Hi,

We are using tinymce and we built an custom plugin to have the equation as inside tinymce, we are inserting that equation image and in the onchange event we are decorating that image with color, back color, bold, italic etc.

So in this case the undo level is added for the inserted equation and the formatting of that image, we want to ignore that formatting by using "editor.undoManager.ignore". But it is not working as expected.

Can anyone suggest me any solution for this.

tinymce version : 4.6.4

**Comment by spocke** [comment]
That will produce multiple levels and that is by design ingore simply does things without adding levels directly if the dom has been changed the editor will pick that up when you for example move the caret inside the editor. If you want multiple changes as one undo level I suggest using transact instead of ignore this allows you to clump together the insert and the bold formatting into one level.
