### ISSUE TITLE
Inconsistent behavior for deleting floated and non floated divs

### ISSUE THREAD

**Issue by chroustradek** [tinymce/tinymce#3871]
I would like to request a bug.

If I put this code to tinymce:
```
<p>lorem ipsum</p>
<div>text to remove</div>
```
and then in editor remove all chars from `div`, in html remains this:
```
<p>lorem ipsum</p>
<div>&nbsp;</div>
```

But if I put this code to tiny:
```
<p>lorem ipsum</p>
<div style="float: left;">text to remove</div>
````
and then in editor remove all chars from `div`, in html remains this:
```
<p>lorem ipsum</p>
<p>&nbsp;</p>
```

Well, IMHO that is a bug.
I've tried on actual version, right here: https://www.tinymce.com/docs/demo/full-featured/
Thank you,
Radek

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
