### ISSUE TITLE
Writing text before/after any html tag wraps it into html too

### ISSUE THREAD

**Issue by paramsingh88** [tinymce/tinymce#3874]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
When I do setContent initially on loading tinymce and set some html tag, say a div with a class "mydiv". On insering something by editing inside tinymce around that div causes the content to be either inserted inside that mydiv or creates another div with the same attributes and add the content in there
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1. SetContent some html into the editor
2. Write something in the editor by pressing enter or go one line that div

**What is the expected behavior?**
It should not cause the newly entered text to be wrapped inside div or tags in its vicinity. I'm facing the problem since I have to implement email signature funcationality.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Latest, MacOS Sierra. No

https://codepen.io/paramsinghvc/pen/XaVOzz?editors=1010

<img width="1680" alt="screen shot 2017-08-17 at 11 33 49 pm" src="https://user-images.githubusercontent.com/19772006/29426550-950cb416-83a4-11e7-9662-81d4015c0c8f.png">

**Comment by spocke** [comment]
The forced_root_block: false causes br:s to be inserted instead of div elements and these get inserted where the caret is so if you want some other behavior here I suggest not setting that and possible set keep_styles: false this will keep the div class etc from being cloned or in your template use contenteditable=false/true regions or use the noneditable plugins to specify these regions in your contents with classes.

I'm closing this since it's not really a bug the behavior is as expected forced_root_blocks: false will produce BR:s on enter. forced_root_blocks: 'div' will produce div elements on enter with the style and class attributes cloned from the element you press enter in. keep_styles: false and forced_root_block_attrs can be used to make sure those new elements doesn't get the styles cloned or specify specific attributes to be set on the new elements.
