### ISSUE TITLE
Dynamic loading and advlist initialization

### ISSUE THREAD

**Issue by artemijan** [tinymce/tinymce#3877]
Hello. First of all thanks for such library with rich functionality.
My question is related to Dynamic loading via PluginManager and using advlist plugin.
As I sow in the docs "plugins" setting is needed to tell the tinymce which plugin to load.
But if i'm loading all the plugins via PluginManager then there is no need to specify this "plugins" setting. And all the plugins will load as expected except of advlist.
I found the [reason](https://github.com/tinymce/tinymce/blob/master/src/plugins/advlist/src/main/js/Plugin.js#L27). This method ("hasPlugin") just checks if "lists" plugin is specifed in options instead of check if it's loaded.

There is workaround - just keep "plugins" always specified ("list advlist") even if you are using dynamic loading.
Maybe make sense to check plugin like this:
`var exists = !!editor.plugins.pluginname;`
This issue is not critical but anyway.
Thanks.

**Comment by spocke** [comment]
No that is not the way plugins should be loaded you can only initialize plugins for an editor though the tinymce.init call if you need to manually load them though for example a script loader you can always just concat the files together with webpack or what ever and the call tinymce.init with the plugins you want to initialize.

I'm closing this one since there is alternative ways of doing this and it's not really a bug.

**Comment by artemijan** [comment]
thank you for quick reply. Yes, you are right i will try you approach. just use require js to build all the plugins and then call tinymce.init
