### ISSUE TITLE
IE11 or lesser: text not editable or must be clicked several times to be editable

### ISSUE THREAD

**Issue by pstephane** [tinymce/tinymce#3879]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
On IE 11 and lesser, user must click twice to edit the text wich is contained on a div element.
And when defining a height to a paragraph, user cannot edit next paragraph.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Use IE 11 or lesser
Demo: http://fiddle.tinymce.com/OXfaab/4

**What is the expected behavior?**
As IE Edge, Firefox and Chrome: user should click once to edit the text.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
IE 11 or lesser
TinyMCE 3 and 4

**Comment by spocke** [comment]
This is a known issue that can't be fixes since IE has this crappy feature built in and it's very hard to workaround and still have IME support, A11y etc.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
