### ISSUE TITLE
Unnecessary horizontal scrollbar in Microsoft Edge

### ISSUE THREAD

**Issue by thiagolacerda** [tinymce/tinymce#3883]
Horizontal scrollbar is showing in Edge when aligning text to the right

Tried the solution proposed by #3538 (by changing min-height to min-width) but it did not work

Steps:
1. open http://fiddle.tinymce.com/jYfaab on Microsoft Edge
3. align text to the right

Expected
Cursor aligns right and no horizontal scrollbar would be shown

Actual
Cursor aligns right and horizontal scrollbar is present

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
