### ISSUE TITLE
Inline floating panel doesn't work correctly in rtl pages

### ISSUE THREAD

**Issue by sassanh** [tinymce/tinymce#3884]
**Do you want to request a *feature* or report a *bug*?**
It's a bug

**What is the current behavior?**
Open this codepen: https://codepen.io/sassanh/pen/ayKXXm and click somewhere in the text, the inline floating panel doesn't show up in right place. (it's in left most part of the screen, if you increase the width from 2000 to 3000 for example, it doesn't show up at all.)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
I proved a codepen.

**What is the expected behavior?**
Floating panel show at the top of tinymce.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinymce 4.6.5 - Chrome 60 / Safari 10  - MacOS Siera (latest update) - I think it worked in previous versions of TinyMCE but I'm not sure.

The problem is with this function: https://github.com/tinymce/tinymce/blob/master/src/core/src/main/js/dom/DOMUtils.js#L860 it should calculate an equivalent of `scrollLeft` for rtl pages. Something like `scrollWidth - scrollLeft - childWidth`.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
