### ISSUE TITLE
Bug with tinymce displaying color picker menu in the wrong place

### ISSUE THREAD

**Issue by batata004** [tinymce/tinymce#3886]
In one website that I built, for accessibility reasons I have to display the toolbar at the bottom of the screen. When I click in all buttons of the toolbar that requires a dropdown to appears, TINYMCE is smart enought to show the dropdown in some place where it will be visible.

Check these 2 images below where I click in 2 buttons of the toolbar.

![a2](https://user-images.githubusercontent.com/8988923/29672160-d2815ca8-88c1-11e7-93e5-5b3ecf0b5d39.jpg)
![a3](https://user-images.githubusercontent.com/8988923/29672161-d288329e-88c1-11e7-91f9-06cb4b3de102.jpg)

You can easily see that the buttons appears at the TOP of the toolbar so the user can interact with the options available.

BUT this nice behaviour does not happen only with 2 buttons: color picker and background color picker. See the image below.

![a1](https://user-images.githubusercontent.com/8988923/29672210-f51848e4-88c1-11e7-8c97-0edbb56acfd8.jpg)

Is it possible to fix this bug and make the color picker to appear upwards? Is there an easy implementation that I can use to fix this on my own?

**Comment by batata004** [comment]
Is there anyone mantaining this git? Cause it looks like there is no interest in the devs to check bugs, I am making you a favor spending my time coming here so you can fix this and sell for premium users.

**Comment by batata004** [comment]
Nobody?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
