### ISSUE TITLE
Bug when user removes text; tinymce removing element even with focus

### ISSUE THREAD

**Issue by batata004** [tinymce/tinymce#3888]
This bug has been annoying me for a long time. Probably it's simple to fix but I never had time to investigate and report. Now I have!

For you to test this bug is pretty simple, open https://www.tinymce.com/ and in the demo editor that appears go to TOOLS -> SOURCE CODE.  Remove everything and paste the really simple code below:

```
<div>

	<div style="display:inline-block;">AAA </div>
	
	<div class="BBB" style="display:inline-block; background:#FFF000;">BBB </div>
    
    <div style="display:inline-block;">CCC </div>

</div>
```

Click OK to apply the source code. Now click in the third letter B and leave the caret of the mouse after the third letter B.

Press only 3 times the BACKSPACE key of your keyboard. After that press any key, you will see you will lose the yellow background element forever. I agree that if use pressed 4 times BACKSPACE of course if should remove the yellow element but if he hits that only 3 times it shouldnt be enougth to remove th element itself cause the user may want to type something inside it.

This happens in many use cases, sometimes it's looks random sometimes dont. With the example I provided here I am pretty sure you will be able to see this problem.

Is there someway I can prevent this from happening?

**EDIT**

What makes this bug strange is that if you add an attribute to the div containing BBB (an attribute like XX="XXX") then when you press 3 times the backspace the element does not lose it's color but it will lose the class BBB. Have no idea why.

**EDIT 2**

In the version 3 of tinymce if I used the line of code below I would never get into this bug. I think it respected the # symbol, now in the version 4 it does not do that anymore.

`valid_elements: "*[*],#div[*],#p[*]"`

**Comment by jayarjo** [comment]
I remember I have replied to this in TinyMCE Community. Here: https://community.tinymce.com/communityQuestion?id=906610000001fsRAAQ.

I'm not able to reproduce it with this example, when I only press backspace three times. Background seems to stay, however if I click some other key, or move the cursor I lose it indeed. And I believe the same will happen in Word and Google Docs.

**Comment by batata004** [comment]
Thanks @jayarjo for taking a look into this. You are indeed correct when you press BACKSPACE 3 times, it still keeps the yellow background BUT the CLASS attribute (and any other atribute you set) will be lost! 

Please @jayarjo do exactly what you did but right after you press 3 times the BACKSPACE go to the VIEW HTML CODE button and see the HTML. You will see the element that has the background is still there but it lost all its attributes. That's the bug I am reporting: it keeps background but loses everything else. This is not an expected result, it's not intuitive since the only thing that gets presrved is the background.

**Comment by batata004** [comment]
@jayarjo this bug still happens, have you tried?

**Comment by batata004** [comment]
????????

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
