### ISSUE TITLE
how do i listen the format event, like forecolor and backcolor

### ISSUE THREAD

**Issue by MrLiufei** [tinymce/tinymce#3903]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by MrLiufei** [comment]
the version is 4.5.5

**Comment by viveleroi** [comment]
I don't believe there's a format-specific event, but you *can* listen for the `ExecCommand` event because formats are internal commands.

```js
editor.on('execcommand', event => {
    if (event.command === 'mceToggleFormat') {
        // event.value is the format name, like "bold"
    }
});
```

**Comment by viveleroi** [comment]
Although on testing, it doesn't work for the textcolors plugin.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
