### ISSUE TITLE
Directionality plugin - remove direction style when needed

### ISSUE THREAD

**Issue by ndvbd** [tinymce/tinymce#3904]
There is a bug in the directionality plugin, that when setting the dir property, it doesn't remove the direction inline styling of an element, which can cause two opposing directives, for example: style="direction: rtl;" dir: ltr

The solution is simple, and I recommend you to take it to master (don't have the time to fork etc, ):

That's the new section of code in the directionality plugin

`Tools.each(blocks, function (block) {
                            // Add dir to block if the parent block doesn't already have that dir
                            if (!dom.getParent(block.parentNode, "*[dir='" + dir + "']", dom.getRoot())) {
                                if (curDir != dir) {
                                    dom.setAttrib(block, "dir", dir);
                                    dom.setStyle(block, 'direction', null);
                                } else {
                                    dom.setAttrib(block, "dir", null);
                                    dom.setStyle(block, 'direction', null);
                                }
                            } else { // if parent block has dir, no need for direction attribute
                                dom.setStyle(block.parentNode, 'direction', null);
                            }
                        });`

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
