### ISSUE TITLE
Enter-key behavior when root element is not forced

### ISSUE THREAD

**Issue by javolek** [tinymce/tinymce#3907]
There seems to be an odd and unexpected behavior of the Enter-key in the empty editor when the `forced_root_block` is set to `false`.

**What is the current behavior?**

I have summarized the current behavior in the table. It shows what appears in the editor when the Enter-key is pressed under the following circumstances:
* browser: Firefox or InternetExplorer 11
* the setting of the  `element_format`
*  the setting of `remove_trailing_brs`

Number of presses<br>of the Enter-key | FF,IE11<br>xhtml<br>true,false | FF<br>html<br>false | IE11<br>html<br>false | FF,IE11<br>html<br>true
-|-|-|-|-
0 - initial value | empty | empty | `<br>` | empty
1 | empty | `<br>` | `<br>` | empty
2 | empty | empty | empty | empty
3 | empty | `<br>` | `<br>` | `<br>`
4 | `<br/><br/>` | `<br><br>` | `<br><br>` | `<br><br>`
5 | `<br/><br/><br/>` | `<br><br><br>` | `<br><br><br>` | `<br><br><br>`

It can be reproduced here:
* `remove_trailing_brs: false`
  * html fromat: http://fiddle.tinymce.com/VYfaab/8
  * xhtml format: http://fiddle.tinymce.com/VYfaab/9
* `remove_trailing_brs: true`
  * html fromat: http://fiddle.tinymce.com/VYfaab/10
  * xhtml format: http://fiddle.tinymce.com/VYfaab/11

The fact that in the IE11 the initial value contains `<br>` was already reported, I think - i.e. here: #1993, but actually never solved.
In the IE11 there is also another oddity - the first press of the Enter-key causes no caret movement unlike in the FF.

**What is the expected behavior?**

I would expect that each press of the Enter-key produces exactly one `<br>` / `<br/>` in each browser.

I've reproduced this behavior on Windows 7 Professional.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
