### ISSUE TITLE
Bug when using Pre inside Blockquote

### ISSUE THREAD

**Issue by Swennet** [tinymce/tinymce#3908]
If you have a `<pre>` block, and remove the `<pre>` formatting by using Format->Formats->Blocks->Pre, then the `<pre>` tags are removed, and `<p>` tags are added around the selected text. This is the default, and logical behavior.

But when the `<pre>` block is inside a `<blockquote>`, and then the `<pre>` block is removed in the same way, it will not wrap `<p>` tags around the former `<pre>` content. This can cause some formatting issues.

Seeing as this behavior is different from the default behavior, it seems like a bug to me.

Steps to replicate:

- Make a `<blockquote>` element with some text inside
- Select the text inside the `<blockquote>`, and add `<pre>` formatting
- Select the same text again, and remove the `<pre>` formatting
- Now the content inside `<blockquote>` is raw (does not have `<p>` tags)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
