### ISSUE TITLE
Thick Selection Borders Render on Top of Menu and Toolbar in IE

### ISSUE THREAD

**Issue by jtark** [tinymce/tinymce#3909]
**Do you want to request a *feature* or report a *bug*?**
This is a bug.

**What is the current behavior?**
In Internet Explorer (tested on IE 11), thick selection borders on some elements will overlap the menu and toolbar when scrolling.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
I'm able to produce the thick borders by creating a table, putting a `<center>` or `<blockquote>` tag with certain styles inside of one of the `<td>` elements, putting another table inside of that tag, and selecting a cell in the nested table.

Setting the `style` attribute of the `<center>` or `<blockquote>` tag to include the `min-width` property appears to be sufficient to trigger the thick selection border.

I'm attaching some screenshots and a TXT file containing HTML source that can be used to reproduce this issue.

**What is the expected behavior?**
The thick selection borders should not be rendered on top of the menu and toolbar.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I'm using Windows 10, and it appears to affect Internet Explorer 11 (and probably older), but does not affect Edge, Chrome, or Firefox. This has been an issue since TinyMCE version 4.5.5 (and probably earlier).

**Sample HTML File**
[Selection Border Priority Problem.txt](https://github.com/tinymce/tinymce/files/1278900/Selection.Border.Priority.Problem.txt)

**Screenshots**
![1](https://user-images.githubusercontent.com/16562084/30083233-b610978e-925b-11e7-9fde-16150553d0f2.PNG)
![2](https://user-images.githubusercontent.com/16562084/30083234-b80bf858-925b-11e7-8754-5f6fc860ab82.PNG)
![3](https://user-images.githubusercontent.com/16562084/30083237-b98766cc-925b-11e7-9a7d-7e82179ad082.PNG)
![4](https://user-images.githubusercontent.com/16562084/30083239-bae613b0-925b-11e7-9af5-19ab153b6ade.PNG)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
