### ISSUE TITLE
Source code plugin is not responsive

### ISSUE THREAD

**Issue by drizgolovicha** [tinymce/tinymce#3910]
**Do you want to request a *feature* or report a *bug*?**
Bug 

**What is the current behavior?**
Currently with for "Source code" set as style with ~640px, what is much more than mobile device

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
open tinymce on iPhone 6, iPad, Google Chrome emulator, click source code icon

**What is the expected behavior?**
Window should be adjusted by screen resolution

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
majorVersion: "4", minorVersion: "6.4". mobile devices, google chrome in emulator mode

**Comment by lnewson** [comment]
Hi,

This has been fixed in TinyMCE 5.1, as we've done a lot of changes and improvements to the mobile editing experience for the new `silver` theme. It's also worth noting that mobile devices weren't actually supported officially to my knowledge until TinyMCE 4.7 when the `mobile` theme was added. As such I'm going to close this and recommend upgrading to TinyMCE 5.1 or higher to resolve this issue. If you are still having issues after upgrading, please let us know and we'll investigate further.

Thanks!
