### ISSUE TITLE
Discrepancy when pasting lists from Word with paste_as_text

### ISSUE THREAD

**Issue by rjpepmeyer** [tinymce/tinymce#3912]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When `paste_as_text` is true, a list pasted from an HTML source will look like this:
```
Foo
Bar
Baz
```
while a list pasted from a MS Word source will look like this:
```
·      Foo

·      Bar

·      Baz
```
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Paste a list from MS Word into [this fiddle](http://fiddle.tinymce.com/eZfaab).

**What is the expected behavior?**
Pasting a list from a MS Word source should work the same as pasting a list from an HTML source.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I have tested this in the current version (4.6.6) as well as 4.6.4, and I have tested in Chrome, Firefox, and Safari on OSX 10.12.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
