### ISSUE TITLE
Modal reset styles

### ISSUE THREAD

**Issue by zzap** [tinymce/tinymce#3914]
At the beginning of `skin.min.css` file, there's the reset of all styles:

```
.mce-container *,
.mce-widget,
.mce-widget *,
.mce-reset {
    margin:0;
    padding:0;
    border:0;
    outline:0;
    vertical-align:top;
    background:transparent;
    text-decoration:none;
    color:#333;
    font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;
    font-size:14px;
    text-shadow:none;
    float:none;
    position:static;
    width:auto;
    height:auto;
    white-space:nowrap;
    cursor:inherit;
    -webkit-tap-highlight-color:transparent;
    line-height:normal;
    font-weight:normal;
    text-align:left;
    -moz-box-sizing:content-box;
    -webkit-box-sizing:content-box;
    box-sizing:content-box;
    direction:ltr;
    max-width:none;
}
```

This results in `<strong>` having wrong font weight when used in modal body. 

Screenshot:

![Image](https://s.nimbus.everhelper.me/attachment/1104683/15eecnapkon8iw4ssn1c/654956-OVcBlh1VmhhcLtGt/screen.jpeg)

After overriding font-weight vertical align is not correct:

```
.mce-container strong,
.mce-widget strong,
.mce-reset strong {
    font-weight: 600 !important;
}
```

 
Screenshot:

![Image](https://s.nimbus.everhelper.me/attachment/1104682/rxekvybffeoli8zccb0y/654956-fCqfq4OrgaKL3bTY/screen.jpeg)

After defining vertical align and adjusting font size (which is the same but for some reason bold text looks smaller) I finally got correct styling:

```
.mce-container strong,
.mce-widget strong,
.mce-reset strong {
    font-weight: 600 !important;
    vertical-align: bottom;
    font-size: 15px;
}
```

Screenshot:

![Image](https://s.nimbus.everhelper.me/attachment/1104676/vq3oclzgwecc5fwf785r/654956-K69P6CreHaBxrdg5/screen.jpeg)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
