### ISSUE TITLE
removeformat does not work

### ISSUE THREAD

**Issue by samscarsella** [tinymce/tinymce#3915]
I'm attempting to remove a format option from the 'Formats > Blocks' menu. I've tried the syntax from https://www.tinymce.com/docs/configure/content-formatting/#removingaformat, and as well as nesting the `removeformat` inside of `format` (as suggested [here](https://stackoverflow.com/questions/39363968/tinymce-and-removeformat-option/46101880#46101880)).

Currently on v.4.4.3.

```
tinymce.init({
            ....
            format: {
		removeformat: {selector: 'blockquote', remove: 'all', split: true, expand: false, block_expand: false, deep: true}
            }
     });
```

**Comment by fyrkant** [comment]
To change what is shown in the styleselect dropdown you change the `style_formats` option, see this page in the documentation: https://www.tinymce.com/docs/configure/content-formatting/#style_formats

As an example here I have taken the default styles but removed the blockquote: http://fiddle.tinymce.com/AZfaab

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
