### ISSUE TITLE
Issue TinyMCE in IE and asp.net webform

### ISSUE THREAD

**Issue by xulongjun** [tinymce/tinymce#3921]
Hello,

We found a bug when we use TinyMCE in IE and asp.net webform. 
In fact, 
In a form asp.net webform. 
if we use the component TinyMCE for a textbox, and then the next field can refresh the page for ex (a dropdown list
) who refresh the page. We we return back the page, the focus is still on the textbox TinyMCE and can not fill another field. 
We must clic again the textbox and then it work. 

The problem is only with IE and no reproduce with another navigator.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
