### ISSUE TITLE
Element's class is getting extended upon hitting a new line

### ISSUE THREAD

**Issue by kskrlin** [tinymce/tinymce#3927]
When I add a class on p element; this is the text in code:

`<p class="foo">Some text</p>`
on enter it creates a new p element with this same class.
`<p class="foo"></p>`

Is there anyway to avoid this behavior or an option (feature) to remove a class manually. Is there a way to see a class name somewhere (i.e. bottom right corner)? Why the class is getting extended with the next element?

I want that first p has this class (which is added by a custom plugin) and every other (on enter) comes fresh without any class.

**Comment by PanJiaChen** [comment]
same problem? has any solutions?

**Comment by kikky7** [comment]
Didn't find time to test and explore, instead I used another html element like figure or article. Note: this is not a very good solution in semantic way and since I need that for customers, I can't tell them to just use code to add/remove classes

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
