### ISSUE TITLE
Some languages supported by Prism.js are not rendered in the codesample plugin

### ISSUE THREAD

**Issue by OlivierJaquemet** [tinymce/tinymce#3931]
Configuring custom languages and CSS in the configuration of the codesample is not enough to provide proper rendering for some languages supported by `Prism.js`.

**To reproduce**

Access the following fiddle (using any version of TinyMCE to this day) : 
http://fiddle.tinymce.com/zagaab

**Bug** : 
The JSON sample is not properly highlighted/rendered in the TinyMCE editor.

![chrome_2017-09-19_17-56-23](https://user-images.githubusercontent.com/618861/30602425-cd2fe8fc-9d64-11e7-8334-f2b5ec883e1a.png)

**Expected** : 
With an appropriate configuration, the following rendering is expected : 

![chrome_2017-09-19_17-55-54](https://user-images.githubusercontent.com/618861/30602434-d66284ac-9d64-11e7-98e6-70c88b30e818.png)

**Explanation**
The codesample plugin provides its own bundle of Prism : 
- [4.x/src/plugins/codesample/main/ts/core/Prism.ts](https://github.com/tinymce/tinymce/blob/4.x/src/plugins/codesample/main/ts/core/Prism.ts)
- [master/modules/tinymce/src/plugins/codesample/main/ts/core/Prism.ts](https://github.com/tinymce/tinymce/blob/master/modules/tinymce/src/plugins/codesample/main/ts/core/Prism.ts)

Therefore, even though the codesample plugin can be configured to specify which languages are to be rendered and with which CSS, not all languages will be supported because the rendering engine is missing.

**Requested fix** 

The codesample plugin should provide a configuration to define a custom Prism instance or JS Path to use for the rendering.

**Comment by bazooka07** [comment]
It's pretty easy to add/remove languages to codesample.

But no feature to add plugins from prism :
* line-numbers
* copy to clipboard
* autoloader  ( very nice to use language not in prism.js )
* jsonp to display source directly from Github, Gist, Bitbucket

more plugins at prismjs.com :
http://prismjs.com/download.html

**Comment by lnewson** [comment]
Hi,

This feature was added in TinyMCE 5.2, as you can now use the global PrismJS instance to render the codesamples within the editor. This can be enabled with the `codesample_global_prismjs` setting, which then allows custom languages to be used. Here's an example showing Perl and PowerShell being added: http://fiddle.tinymce.com/6bhaab

As for the plugins mentioned in the second comment, theres already https://github.com/tinymce/tinymce/issues/2771 and https://github.com/tinymce/tinymce/issues/4481 open for that so I'm going to go ahead and close this since the original request has been implemented.

Thanks!

**Comment by OlivierJaquemet** [comment]
Thank you @lnewson

**Comment by SantuarioParra** [comment]
@lnewson i have a problem , I was using that property but I can't make it works, i'm using TinyMCE 5 Vue version and i have installed the prismjs from their main page and by NPM but nothing works i still having te same problem, i'm not able to change the default theme from the pluging

**Comment by lnewson** [comment]
@SantuarioParra this was about using different languages, not themes. Themes are controlled via CSS and as such are reliant on the content CSS you provide. As an example, here's my example above adapted to use the `dark` PrismJS theme: http://fiddle.tinymce.com/6bhaab/1

Anyways, since this is a different issue, if you have any further issues please open a new issue instead. Thanks!
