### ISSUE TITLE
Change the default n/a label in dialog list options

### ISSUE THREAD

**Issue by philouphil** [tinymce/tinymce#3948]
Hello,
I'm going very well with tinymce, really big thanx to all the team.

Now I'm looking at some details, for example when you clic to add a link, in the dialog tab you have "target" with the default value "n/a".

I would like to change this label with something more user-friendly like "please choose..."

Same problem if I put a link list or any kind of option which needs a list to display.

I hope my message is clear, my english is not so good, 

Big thanx for your help !

**Comment by fyrkant** [comment]
There is a setting to set your own target list for the link plugin, see this setting for info:
https://www.tinymce.com/docs/plugins/link/#target_list

And this fiddle for a demo:
http://fiddle.tinymce.com/Sagaab

**Comment by philouphil** [comment]
Thanx fyrkant,

this works perfect for the target list, but not for a link_list for example.

Any idea/solution for link_list ? Is there any "universal" method I could use anywhere (like for image_list for example) ?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
