### ISSUE TITLE
Feature: Add files per Drag & Drop into the text field

### ISSUE THREAD

**Issue by jankout** [tinymce/tinymce#3951]
It would be great to improve the user experience with the possibility to add pictures into the TinyMCE text field per Drag and Drop. The picture could be saved automatically in a special order (e.g. with date like in WordPress?)

After loading of the picture the user could have the possibility to add the meta informations, to change the file name or to choose the visible area. But I think it should be more generally easier and quicker than now.

**Comment by jayarjo** [comment]
You can drag and drop pictures from the desktop if you have Paste plugin enabled and [paste_data_images](https://www.tinymce.com/docs/plugins/paste/#paste_data_images) set to true. 

Feature is also available in [PowerPaste](https://www.tinymce.com/docs/plugins/powerpaste/#buytinymcepowerpaste) plugin.

**Comment by philouphil** [comment]
Hello,

Of course you can, continue your search here https://www.tinymce.com/docs/configure/file-image-upload/ and there  https://www.tinymce.com/docs/advanced/handle-async-image-uploads/

But at this time I don't manage in dropping several pictures at the same, I've opened an issue for this, hoping to get an answer soon.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
