### ISSUE TITLE
WARNING: Too many active WebGL contexts. Oldest context will be lost.

### ISSUE THREAD

**Issue by robertmylne** [tinymce/tinymce#3952]
I am running multiple tinymce on the same page. I have copied both types of instructions on this page `https://www.tinymce.com/docs/get-started/multiple-editors/` but am still getting the below warning come up in the chrome console multiple times:

`[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952`

`WARNING: Too many active WebGL contexts. Oldest context will be lost.`

**Comment by robertmylne** [comment]
Found the issue, it was loading a 1x1 pixel git for each request instead of reusing the same one.

The issue is it still loads this `https://cloud.tinymce.com/stable/skins/lightgray/content.min.css` for each tinymce instance. Is there a way they can all just share the same instance? It is slowing the website down massively.

**Comment by spocke** [comment]
It needs to load the stylesheet into each editor iframe and since the browser will cache the first request it will be fast for the other ones so not really a problem.

The too many active WebGL contexts is something I would like to know how to reproduce is it possible for you to setup a fiddle of that?

**Comment by robertmylne** [comment]
I have a lot of tinymce instances 100+ and loading that many stylesheets takes time, is there a way to load one?

I will get back to you on the fiddle with the `The too many active WebGL contexts `

**Comment by AlbertMN** [comment]
I'm experiencing this too, TinyMCE stable build from cloud cdn.

**Comment by zacherkkila** [comment]
Any word on this? Same `too many active WebGL context` warning here.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
