### ISSUE TITLE
Need 750 character insert limitation feature in Tinymce library

### ISSUE THREAD

**Issue by rajeshv-optimus** [tinymce/tinymce#3953]
**Do you want to request a *feature* or report a *bug*?**
Need to set the limit of 750 character in editor.

**What is the current behavior?**
Currently in this library i am not able to set limitation of 750 character in editor.

**What is the expected behavior?**
1. On the bottom of editor show "750 character left"
2. When i start type text or paste any text on editor with space and line break then character count should be decrease.
3. When the 750 character reached then show the notification error for "Maximum number of character reached"
4. If i am typed or paste text after the "Maximum number of character reached" notification display  then the text not should be paste or typed on the editor
5. If message show "10 character left from 750" then if i paste 20 character then only 10 character paste and rest character should not paste and show the notification of "Maximum number of character reached"

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMce Version: 4.6.6
Browser: any

**Comment by Afraithe** [comment]
Can you define a character, is this with or without html? How many characters is an image worth?

**Comment by IProbablyFoundABug** [comment]
I'm sure this can be done with a plugin

**Comment by rajeshv-optimus** [comment]
@IProbablyFoundABug  Can you provide the plugin name.

**Comment by sharathdaniel** [comment]
Why a simple functionality like this is still not implemented? It should be an inbuilt feature.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
