### ISSUE TITLE
Icons use <i> instead of <span>

### ISSUE THREAD

**Issue by Bakual** [tinymce/tinymce#3954]
**Report a *bug*!**

**What is the current behavior?**
Currently, the various icons used in TinyMCE are using the `<i>` tag, which is obviously semantically wrong as it hasn't anything to do with an *italic* text. Someone probably just thought `<i>` is clever for "icon", which it isn't :smile: 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Just inspect an icon.

**What is the expected behavior?**
Icons should use the semantically correct `<span>` tag, which works fine as well.

**Comment by spocke** [comment]
Semantics are important for two reasons indexing of contents and a11y. A11y is already covered since it has role="presentation" indexing is also covered since they are empty elements so not part of any text content. Some of the popular css framework libraries at the time used i for icon the inspiration was from that since it was common practice. Sure we can change this to span or div but since it would have very little impact on anything it's not a top priority.

**Comment by Bakual** [comment]
Div would be wrong as well, as it is a block element. I know for example Bootstrap used i for icons, but afaik they changed it to span as well for semantic reasons.
I know it's likely not a top priority but eventually it should be done imho.
As for breaking skins, this may be the case. But only if those skins explicitely add the CSS to "i.icon-class" instead of just targetting the class alone (which would be better CSS).

**Comment by lostkeys** [comment]
We're going through old feature requests and this feature request is for an older version of TinyMCE that we no longer support. Icons in TinyMCE 5 are displayed using SVG's so this issue is no longer a concern. Thanks.
