### ISSUE TITLE
Question about data-mce-style

### ISSUE THREAD

**Issue by lvian** [tinymce/tinymce#3957]
Hello guys,

I'm having some problems using the Code plugin.

When the Code plugin is used, the regular styles on elements that also have the data-mce-style are replace by the ones inside data-mce-style, messing the template.

Is there a way to circumvent that behavior? Margin styles replacing only the ones that conflict would be perfect, but so far I found no material about configuring such thing.

thanks

**Comment by jayarjo** [comment]
What you mean regular styles? Can you provide a [fiddle](http://fiddle.tinymce.com)?

**Comment by lvian** [comment]
Hi @jayarjo 

Lets say my template has the following div

`<div style="background-color:black">`

It loads and is displayed without any issue when Tinymce starts, and if I edit that div in the editor, TinyMce adds the new styles like this:

`data-mce-style="padding:5px;"`

Resulting in the following div

`<div style="background-color:black" data-mce-style="padding:5px;">`

But when I open the Code pluging, TinyMce replaces the "style" content with the "data-mce-style" content, causing the original style to be lost.

**Comment by spocke** [comment]
The data-mce- prefixed attributes are internal so there are supposed to be invisible for the user so if you use the proper apis editor.getContent() and editor.setContent() for example they should never be seen externally. So how are getting the contents out of the editor?

**Comment by lvian** [comment]
I found out the data-mce-* attributes through debugging, getting content being rendered editor without using the code plugin.

So far I managed to handle the problem by duplicating all style tags on both "style" and "data-mce-style" and that basically solves the issue we were having.

I know its probably something really specific to this case, but my client system let the user pick a html template and customize some options before opening the editor.

Just felt like asking about this because It felt weird that the style was being replaced instead of merging, but I'm aware that this might be intended to avoid some problems.

thanks for the anwsers

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
