### ISSUE TITLE
Color picker fails when the position parameter of body is relative

### ISSUE THREAD

**Issue by dioobr** [tinymce/tinymce#3988]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Failed to select a color with the mouse in the plugin Color Picker. Doesn't respond as expected.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
The CSS parameter _position_ of the _body_ tag is defined as _relative_ and the scroll bar (vertical) must be greater than zero.

**What is the expected behavior?**
Cursor of the color picker is in the same position as the mouse cursor.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 4.7 (4.6.4 too)
macOS 10.12.6
Safari 11 / Google Chrome 61.0.x
Works fine on Mozilla Firefox Developer Edition 57.0b6 

I reproduced here:
https://codepen.io/anon/pen/VMXwzp

**Comment by dioobr** [comment]
I reproduced here:
https://codepen.io/anon/pen/VMXwzp

The scroll bar (vertical) must be greater than zero.

**Comment by jayarjo** [comment]
Had to move it to http://fiddle.tinymce.com/ycgaab, 'cause CodePen was constantly refreshing for me in Chrome.

Can't reproduce it in Chrome 61.0.3163.100, Windows 10.

**Comment by dioobr** [comment]
Hello jayarjo,

When change a text color, for example, click on the button "Custom...", then try to select a custom color with the mouse cursor.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
