### ISSUE TITLE
[iOS] Scrolling to Bottom when copying / cutting

### ISSUE THREAD

**Issue by Georg-Git** [tinymce/tinymce#3992]
**Bug:** Scrolling to Bottom when copying / cutting

1. Select/mark a word
2. Copy or Cut selection

**Current behavior:**
=> Screen is scrolled to bottom

**Expected behavior:**
=> stay at cursor position

**Version:**
4.7.1 **with plugin paste** => scrolled to bottom
4.7.1 **without plugin paste**: OK

**only iOS Safari**

http://fiddle.tinymce.com/Vbgaab/2

**Comment by Georg-Git** [comment]
This fiddle is more simple:
http://fiddle.tinymce.com/0cgaab

**Comment by Georg-Git** [comment]
More simple example:
http://fiddle.tinymce.com/Vbgaab/18

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
