### ISSUE TITLE
Font family and size is not kept when content is pasted repeatedly in Safari

### ISSUE THREAD

**Issue by thiagolacerda** [tinymce/tinymce#4000]
Steps to repro:

1. open http://fiddle.tinymce.com/scgaab/1
2. open TextEdit on Mac and type any text and change the font family and size to be something not default (e.g. Courier New, 36)
3. select all TextEdit content with cmd+a and copy
4. paste content in editor (fine, font family and size are correct)
5. press cmd+v again

expected:
new pasted content has the same formatting
actual:
font size and family are reset to the default values

I noticed that the function removeWebKitStyles in the paste plugin is not including the style values from the pasted content if they are the same of the current node where the cursor is. That is causing the problem, since another paragraph will be created instead of a continuation of the current formatted span.
Maybe checking if the pasted content is a paragraph and keep the formatting, even if they are the same, might fix the issue.

This probably might affect other properties that are listed in the paste_webkit_styles attribute

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
