### ISSUE TITLE
empty textarea disables tinyMCE

### ISSUE THREAD

**Issue by xentrica** [tinymce/tinymce#4012]
Creating an instance of TinyMCE dynamically, but an empty textarea flashes the caret two times then disappears and disables the textarea. Click on Bold and problem disappears. I have seen this addressed with (css body height=100%) elsewhere but does not fix for me. Am I missing something? Seems pretty critical bug, no?

**Comment by spocke** [comment]
If you setup a fiddle on fiddle.tinymce.com and describe how to reproduce it we can look into it. Thanks

**Comment by xentrica** [comment]
A bit hard to recreate in fiddle as I am creating instances of tinymce dynamically in a jsp page, adding and loading text/content from database. But I have read that tinymce handles the caret a bit differently than a regular textarea in that it "only shows the text cursor in the first line or in the part that there's some text". This seems to be what I am experiencing. If there is no first line, as a new instance that loads text(null) from ajax return might.

**Comment by xentrica** [comment]
I have found the root of what caused this. I had the settings:

    forced_root_block : 'p', 
    force_br_newlines : true,
    force_p_newlines : false,

It resolved by removing:

    force_br_newlines : true,
    force_p_newlines : false,

**Comment by xentrica** [comment]
Well I misspoke sort of. First the above should have been:

forced_root_blocks: false;

Except that does not seem to do as expected. It surrounds text with <p> tags and uses <p> for line breaks. The opposite of what the docs says it should do.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
