### ISSUE TITLE
Inlite theme + quickimage not works on mobile

### ISSUE THREAD

**Issue by t-kanstantsin** [tinymce/tinymce#4017]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When click on quickimage button in insert_toolbar nothing happens.
On google chrome - just nothing
On firefox - receive popup "Firefox prevented this site from opening 1 pop-up window. Would you like to show it?", after selecting "show" - it closes and nothing happens.
On firefox - after each try to 'insert image' number of pop-ups that was blocked increased.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
- open https://www.tinymce.com/docs/demo/inlite/
- insert new line
- click on 'insert image'

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
OS: android 6.0.1
Browsers:
- Firefox: 56.0
- GoogleChrome: 61.0.3163.98

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
