### ISSUE TITLE
[IE11] Cursor jump to outside the table

### ISSUE THREAD

**Issue by dupont-kedama** [tinymce/tinymce#4023]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When input Japanese character into table cell, caret jump to outside the table.

**The steps to reproduce**
1. open [https://www.tinymce.com/](https://www.tinymce.com/) with IE11.
1. Insert a table anywhere. (Table > any size)
1. Set Alignment left or right. (Table properties > Alignment > Select Left)
1. Input Japanese character into the table any cell. (With Windows Microsoft IME Japanese mode)

If the table have an attribute `align="left(or right)"` or `style="float:left(or right)"`, then it reproduce.

**Not reproduce**
+ other web browser(e.g. chrome)
+ Alignment > Select Center
+ Microsoft IME ASCII mode

**What is the expected behavior?**
Caret keep position.

**Which versions**
+ OS: Windows10
+ Language: Japanese
+ Browser: IE11
+ IME: Microsoft IME
+ tinymce: 4.5.6, 4.7.1

**Comment by spocke** [comment]
Not sure we can fix this one it seems to happen on plain content editable as well and we can't really control the ime other than knowing that composition is about to take place. I guess we should report this to the Microsoft since edge seems to have the same issue.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
