### ISSUE TITLE
Extra paragraph tags added when inserting details element

### ISSUE THREAD

**Issue by StefanDygPedersen** [tinymce/tinymce#4025]
Steps to reproduce the bug:
Insert the following in the editor
```<details>foo</details>```
See that it is being reformatted to:
```
<p>&nbsp;</p>
<p><details>foo</details></p>
<p>&nbsp;</p>
```

Expected behaviour would be not to insert the new extra paragraphs.

I verified that this is still a bug using the TinyMCE editor on the frontpage of your website.

**Comment by spocke** [comment]
The details should be treated as a block element I guess however the support for this element inside contenteditable is a bit funky not sure browser vendors considered that when they added support for that element.

**Comment by Otshelnik-Fm** [comment]
Hi. I use WordPress and switch between text and visual editor having such layout (spoiler) I have a problem with the appearance of non-breaking spaces (nbsp) https://yadi.sk/i/JVSzLgDO3QjzuH . Every time I switch from a text editor to a visual one, I add more spaces https://yadi.sk/i/Xi-XYPRS3Qjzyg
Details tag https://caniuse.com/#search=details

I found the solution - wrap in an additional div https://yadi.sk/i/ucdrj5P_3Qk2Ao , then the spaces do not appear. But it looks like a dirty hack

there are no third-party plug-ins in WordPress. Only the button that adds spoiler to the page

**Comment by chrispcb** [comment]
This issues is like https://github.com/tinymce/tinymce/issues/3276

All broswers support Details tag exept Edge and the old IE but isn't a surprise ;)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
