### ISSUE TITLE
Package size

### ISSUE THREAD

**Issue by bubach** [tinymce/tinymce#4028]
This is an open question about the state of the core, what has changes since beginning of the year? I'm now unable to get the package much smaller than 500-700kb depending on included modules. Full package is weighting in at 1mb.

I've used versions back at the beginning of the year, around ~4.5, with size about 300kb ... 'tiny' might have to be removed from the name.

**Comment by Afraithe** [comment]
I think we need to define what the core is, the core has actually gotten smaller between 4.5 (beginning of 2017) and 4.7

4.5.8 the core is 397kb, 134kb compressed
4.7.1 the core is 363kb, 121kb compressed

But it doesn't tell us that much, the size of the theme has increased quite a lot instead, since we moved things out of the core. You should be looking at the compressed size though, since you should be loading tinymce from a static source with compression on.

We have also moved to a more functional programming style, this does have the effect of increasing the size, but we think the trade off is worth it, we get a more stable product, more efficient coding, easier to debug, better and more comprehensive automated testing. We think that we can in the future (hopefully soon) adopt things like tree shaking to reduce the size, how much is hard to say, but it should be noticeable.

There has also been a lot of refactoring behind the scenes, this is also to make the core more easy to read, debug and improve upon. Plugins are split up to more files, the Formatter has been reworked and split into more files along with more core parts. In the end these refactoring shouldn't increase the size that much, the output files look the same in the production package.

The loading strategy have also changed over time, we no longer recommend ppl bundle everything up into 1 js file like before, with HTTP2 it doesn't have any positive effect, you might as well leave things in separate files. There is a lot of other things we have gone through to make sure things are lazy loaded, so if you load the core and don't initialize, you wont ever load the theme now for example.

You should be concerned about the size, if you see poor loading, slow rendering of the UI or things like that, that might be an indication that the files are not loading fast enough. If that is the case, look at where you are loading it from, make sure it is setup to serve static files (HTTP2!) and gzip compressed, and that you have a decent ping and bandwidth response to that location. And if your following all those best practices, and you still think it is slow, well then we probably need to do something about it.

**Comment by bubach** [comment]
Thanks for that in-depth explaination, and while I can see the benefits of a more modular structure, this Gist illustrates how bad it can also be for file-size.
https://gist.github.com/bubach/74fcecd37554fb164b9c0718ac92d41a

I'm far from a webpack/npm/module expert - but how many small files does the editor contain where - like in this example the import declarations is half the file-size when minified?

Anyway - I'll look forward to seeing the tree-shaking results!  And thanks for a great editor. :)

**Comment by Afraithe** [comment]
This is the Formatter in 4.5.x
https://github.com/tinymce/tinymce/blob/4.5.x/js/tinymce/classes/Formatter.js

This is the cleaned up Formatter structure.
https://github.com/tinymce/tinymce/tree/master/src/core/src/main/js/fmt

Dividing up the files like this is really the only sane way of doing development when files and projects get larger, this should probably been done a long time ago but we just got to it now.

The division into multiple files shouldn't add that much to the overall size, what the main increase over the last year or so is probably the Katamari library that helps us write more functional code, that coupled with hundreds and hundreds of bugfixes. Usually bug fixes adds complexity, it's not just a typo, it is more likely to be an edge case we didn't account for, so we need to add code for those. Changes to how browsers function over the last 12-16 months has also cause us to rework certain aspects, altho with the drop of old IE browser support, we manage to mitigate that and remove unused code, there is still a bit cleanup there to be done as well, but we weed them out as we find them as they are usually feature detected in various places and not obvious to be a IE codepath.

If you use compression, core, theme and a couple of plugins, you shouldn't have your browser have to load more than around 200kb or just above that (depending on the plugins you choose). That is not an unreasonable size for the complexity of the software.
