### ISSUE TITLE
TinyMCE with gulp concat and minify issues

### ISSUE THREAD

**Issue by wilker7ribeiro** [tinymce/tinymce#4030]
Currently, I'm using gulp to process all my bower components, and generate vendor.min.js file

The first issue is that https://github.com/tinymce/tinymce doesn't have the main property inside bower.json, so gulp main-bower-files cant find it and just ignores the hole package.

I think tinymce bower.json doesn't have main property because there are two options to main files, tinymce.min.js and jquery.tinymce.min.js.
I would suggest creating two separate projects.

But then, I created the main property myself, pointing to tinymce.min.js.
After that, all plugins are inside vendor.min.js together with other bower components (as it is supposed to be with gulp-concat and gulp-uglify), but tinymce keeps making requests to `/asset/plugins/PLUGINNAME/plugin.min.js`

There is no way to use TinyMCE with gulp concat and minify where everything is inside vendor.min.js?

Obs: Using angular-ui-tinymce for angularjs as well

**Comment by spocke** [comment]
A main entry would only work if tiny was just one file but it consists of multiple plugins and themes. There are details on how to bundle tinymce in module loaders here: https://www.tinymce.com/docs/advanced/usage-with-module-loaders/
Closing this one since it’s not really a bug. You can use our community forum if you have further questions.
