### ISSUE TITLE
Select only one style format at a time

### ISSUE THREAD

**Issue by gwleuverink** [tinymce/tinymce#4035]
Hi,

I have a tinyMCE instance with multiple style_formats. This works fine, but it is possible to have multiple formats selected at the same time. I'd like to disable this behaviour so only one format can be selected.

[This issue](https://github.com/tinymce/tinymce/issues/2032) proposes a solution that looked promising. Is there any chance this will be implemented or is there any other way to approach this issue?

Thanks in advance!

**Comment by spocke** [comment]
Buy default the formats merge so that you can toggle multiple classes on and off you can use the attributes: { 'class': 'abc' } format parameter to override any existing classes and then it won't merge with other formats. I'm closing this one since it's more of a question that could be answered in the tinymce community forum.

**Comment by gwleuverink** [comment]
Thanks @spocke, I will look into the attributes format parameter and will check with the community forum if I need more help.
