### ISSUE TITLE
Bug when using backspace after a nested list in IE

### ISSUE THREAD

**Issue by Jeff-14159** [tinymce/tinymce#4038]
There is an issue in IE 11 (maybe previous versions too) when pressing backspace after a nested list and pulling that element up and appending  last the previous sibling list li.

To Reproduce this use IE and the following steps:

1. First start off by typing a couple paragraphs in the editor
`<p>test1</p>`
`<p>test2</p>`
`<p>test3</p>`

2. Next convert the first paragraph into a list
`<ol>`
 ` ` `<li>`
` ` ` ` `test1`
` ` `</li>`
`</ol>`
`<p>test2</p>`
`<p>test3</p>`

3. Build out the list with at least 2 levels and you should get this
`<ol>`
` ` `<li>`
` ` ` ` `test1`
` ` ` ` `<ol>`
` ` ` ` ` ` `<li>`
` ` ` ` ` ` ` ` `test1.1`
` ` ` ` ` ` `</li>`
` ` ` ` `</ol>`
` ` `</li>`
`</ol>`
`<p>test2</p>`
`<p>test3</p>`

4. The important thing to notice at this point is that the second ol lives **within** the first li and at this point the bread crumb reads properly if on "test1.1" with ol » li » ol » li

5. Now to break it press the backspace at the beginning of paragraph "test2" what should happen is "test2" should be pulled up and appended to the end of "test1.1" ... and it actually looks like it dose but in the process it completely destroyed the structure of the lists!! and we end up with this mess:
`<ol>`
` ` `<li>`
` ` ` ` `test1`
` ` `</li>`
` ` `<ol>`
` ` ` ` `<li>`
` ` ` ` ` ` `test1.1test2`
` ` ` ` `</li>`
` ` `</ol>`
`</ol>`
`<p>test3</p>`

6. As you can see it ripped the second ol (child of the first li) out from the first li and put it back in after the li as a sibling and the bread crumb now reflect this with ol » ol » li  while this example may see trivial having a fell defined list and having half the thing shuffle around on you when you press the backspace is far from ideal.

The reason I say half the list is when you have a complex list it will only affect the parents of the last li.... so if any previous sibling li's also have lists nested in them they would be unaffected thus you end up with your last and top level list with one hierarchy and all other previous children list with the opposite hierarchy. This makes tracking parent child relationships almost impossible. 

I have tested this back to tinyMCE 4.5.7 up to the current release 4.7.1 and it only appears to be broken on IE

Thanks,
Jeff

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.

**Comment by Jeff-14159** [comment]
Hellos,
                We are long time users of TinyMCE, and we recently noticed this bug was closed due to inactivity even though it has been verified. We were wondering if it was an actual fix put in place in the newer version or if it just went away due to other code changes?

We are looking at upgrading to the newer version but would require a lot of changes on our side as we have a lot of custom handlers on things and the plugins have changed too, I think one of the paste functions we use is now considered a paid plugin.

**Comment by thedrjim** [comment]
Hello Jeff, we have reproduced your issue, but we found that it is a native IE11 content editable issue, not a TinyMCE issue. 

The paste functionality is provided by the free paste plugin, however, there is also a premium PowerPaste plugin.
