### ISSUE TITLE
Unpredictable scroll in tinymce with certain body content

### ISSUE THREAD

**Issue by hariprasadharidas** [tinymce/tinymce#4044]
[Tinymce scrolling issue.zip](https://github.com/tinymce/tinymce/files/1446491/Tinymce.scrolling.issue.zip)
**Bug details**:
Have been observing a bug in tinymce when we have a specific content in tinymce editor.

Currently whenever we have the content in tinymce and when user scrolls down to the editor, presses CTRL+END to go to end of the editor and then starts typing, the screen scrolls up and throws the section that is being edited out of screen .

**Steps** (video created is attached in the zip file):

1. Have large content inside tinymce
2. Resize tinymce such that you have an additional scrollbar on your browser (apart from the scrollbar that is in tinymce.
3. Go to the end of large content using CTRL+END
4. Start typing

**Fiddle link**:
http://fiddle.tinymce.com/Idgaab

**Expected behavior**: User should be able to type and the screen where he is typing should stay in focus
**Actual behavior**: User is able to type but the focus is lost on screen and it scrolls back to top.

**Tinymce Version**: Latest (edge and all previous versions that I tested with - 4.1.7, 4.7.1).
**Chrome Version**: 62.0.3202.75 
**OS**: Windows 7 OS. 

This was not working in previous version of tinymce either.

**Comment by hariprasadharidasnasdaq** [comment]
Just came across another similar issue, the difference is that here I am not pasting anything. The content was preexisting, so we probably don't need that step. Hopefully the video will explain it.

Thanks for the help.

**Other issue**:
https://github.com/tinymce/tinymce/issues/4031

**Comment by spocke** [comment]
This seems to be a chrome bug that is fixed in the beta channel. So I guess the only thing to do is to wait for the google to release a version that doesn't have this bug.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
