### ISSUE TITLE
Spellchecker: formatting not preserved when word corrected

### ISSUE THREAD

**Issue by Narrenschyff** [tinymce/tinymce#4061]
Bug on version 4.7.1, issue was present on previous versions as well

Currently if I apply a formatting rules on a large set of text, if I click on an incorrectly spelled word within that text and replace it with a suggestion, the word gets replaced by the suggestion and the formatting is preserved. This is OK.  However, if I have this specific word formatted (underlined in this case with different font color) differently from the rest of the text, if I click on  the suggestion dropdown and replace it with a correctly spelled word,  it will be replaced by that word with the formatting of the paragraph it is within. The original styling of that specific word will be lost.

![image](https://user-images.githubusercontent.com/2990633/32729138-aab9e804-c87a-11e7-9a00-37cc53afc285.png)
![image](https://user-images.githubusercontent.com/2990633/32729273-10b77dba-c87b-11e7-9dac-49ef9f3c8008.png)

Is this expected? Because intuitively I would expect the formatting to be preserved and just the text changed.

**Comment by spocke** [comment]
Is this the browser spellchecker, the community spellchecker or the tinymce spellchecker pro package?

**Comment by Narrenschyff** [comment]
@spocke this is the community spellchecker

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
