### ISSUE TITLE
Fix missing call of the custom url converter in the image plugin

### ISSUE THREAD

**Issue by chaeller** [tinymce/tinymce#4064]
This bug exists at least since version 4.1.9 and still exist in the current version 4.7.2.
Re-open #502
It would be great if my fix would be accepted.

Bugfix for the image plugin. If a custom URL converter is configured (configuration option "convert_urls"), it will be called after changes of the source field in the "insert/edit image" dialog.
Unfortunately the url converter is not called if the user clicks the "Ok" button directly (form submission).
I have used the Internet Explorer 11.

Test: Insert a new Image, enter JS-Code (for example"javascript:alert(document.cookie)") instead of an URL, click OK -> JS is executed!!!

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
