### ISSUE TITLE
Image upload tab misaligned

### ISSUE THREAD

**Issue by sea75300** [tinymce/tinymce#4071]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I'm using a custom skin build via Skin Creator, german language package and enabled the image upload in image tools. When I open the "Upload" tab, the file input button is displayed next to "Browser for an image". The image drop area is displayed incorrectly too.

Both does not happen when the lightgray skin is in use. First does not happen with english language enabled.

**What is the expected behavior?**

The dialog should be displayed the same way in both cases.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE 4.7.0 up to 4.7.2, tested in Firefox and Chrome

![english_style_failure](https://user-images.githubusercontent.com/13407962/32857392-ed45d79a-ca47-11e7-99c1-7f7c61637c79.png)
![german_style_failure](https://user-images.githubusercontent.com/13407962/32857394-ed6c6180-ca47-11e7-826b-697b915ee90c.png)

**Comment by jayarjo** [comment]
I guess it lacks css rules for that tab.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
