### ISSUE TITLE
Bug: Shift+Enter creates a new unremovable editable container outside root block under certain configuration

### ISSUE THREAD

**Issue by alphestdev** [tinymce/tinymce#4073]
When `<p>` tag is not a valid child element and `forced_root_block: false` TinyMCE breaks unrecoverably into more duplicates on Shift+Enter.

The issue can be reproduced here:
https://codepen.io/anon/pen/WXZBpv

Expected behavior:
Add `<br>` and jump to new line. Just like it happens with the same configuration + `forced_root_block: true`.

Current behavior:
TinyMCE creates a new `<div>` with `contentEditable="true"` outside of the original editable element. This can be repeated to create infinite amount of new clones. These new elements cannot be removed. 

Found in latest v4.7.2

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
