### ISSUE TITLE
IE11 : Long strings without space are resizing tinymce

### ISSUE THREAD

**Issue by louislebrault** [tinymce/tinymce#4077]
Long strings dont make the editor to auto break line under Internet Explorer 11. Instead it resizes the editor and put a scroll bar.

You can test it in the example at https://www.tinymce.com/ by keeping pressed any key.

**Comment by Tamakimouto** [comment]
If anyone is still trying to fix this, add this rule.

`.mce-content-body { word-break: break-all }`

**Comment by Tamakimouto** [comment]
overflow-wrap probably doesn't work in ie11, but it fixes it for me in Firefox.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
