### ISSUE TITLE
Table data (TD) border not showing properly in the new version!

### ISSUE THREAD

**Issue by infoshahin** [tinymce/tinymce#4083]
![oie_lg1iopdxsyog](https://user-images.githubusercontent.com/8981516/33055882-7a957160-ceac-11e7-9540-8ae66472be78.png)

![oie_wzaqoicuoair](https://user-images.githubusercontent.com/8981516/33055872-6fe739e2-ceac-11e7-895e-b73c91cfdb35.png)

![3](https://user-images.githubusercontent.com/8981516/33055951-dfb12ff8-ceac-11e7-91e4-3f3796877055.png)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
