### ISSUE TITLE
[FireFox 57] Unable to navigate to outside the table in TinyMCE editor

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#4084]
[FireFox 57] Unable to navigate to outside the table in TinyMCE editor

Can anyone suggest me a solution in Version 4.7.2

**Comment by Afraithe** [comment]
4.7.3 is out, can you replicate it? I could not replicate it in 4.7.2 either.

Please explain it in more detail, are you using any out of the ordinary config settings?

**Comment by codealchemy** [comment]
We came across this as well - replicated on the latest (`4.7.4`) in CodePen [here](https://codepen.io/codealchemy_1470413206/pen/LeEmXR)

Example (top: Chrome `63.0.3239.84` - as working reference, bottom: Firefox `57.0.1`)

![firefox_mce_bug](https://user-images.githubusercontent.com/4504083/33959235-ad997286-dffb-11e7-8c79-6d452124dad5.gif)

**Comment by fyrkant** [comment]
@kaviyarasanaspire @codealchemy Are you able to reproduce this in the latest version of TinyMCE?

**Comment by codealchemy** [comment]
@fyrkant yes this looks to still be happening on `4.7.9` (CodePen example above has been updated as well)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
