### ISSUE TITLE
TinyMCE Paste Plugin Bug - input event not emitted

### ISSUE THREAD

**Issue by gkubisa** [tinymce/tinymce#4085]
**Do you want to request a *feature* or report a *bug*?**

Report a *bug*.

**What is the current behavior?**

1. Use TinyMCE with the paste plugin.
2. Paste some plain text when no text is selected in the editor.

[input event] is not emitted.

JSFiddle: https://jsfiddle.net/322c0612/1/

**What is the expected behavior?**

[input event] should be emitted.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

- TinyMCE@4.7.2
- Chrome: Version 62.0.3202.94 (Official Build) (64-bit)
- OS: Ubuntu 16.04

I don't know, if it worked fine before. Other browsers and OSes might be affected, too.

[input event]: https://developer.mozilla.org/en-US/docs/Web/Events/input

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
