### ISSUE TITLE
tinymce.init causing error message in Safari browser even when doing this synced

### ISSUE THREAD

**Issue by Taygair** [tinymce/tinymce#4089]
Bug: Error message showing in Javascript console after of Safari (Mac, latest version) using tinymce.init twice:
**SyntaxError: Can't create duplicate variable: 'typeMap'**

The fully working code below does this:
1. Init tinymce
2. Wait 2 seconds (sync, making sure tinymce has enough time to properly initalize before continuing)
3. Delete previously initialized tinymce by all known commands
4. Wait 1 second (sync, making sure tinymce has enough time to properly remove)
5. Re-init tinymce 

Here the fully working sample: 
```
<script type="text/javascript">
tinymce.init({
    selector: "textarea",
    plugins: [
        "advlist autolink lists link image charmap print preview anchor",
        "searchreplace visualblocks code fullscreen",
        "insertdatetime media table contextmenu paste"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
});

// Give tinymce time for 2 seconds to initialize before removing tinymce
setTimeout(function(){
	// Completely remove tinymce by all know remove commands
	tinymce.EditorManager.execCommand('mceRemoveEditor', true, 'textarea');
	tinymce.remove('#textarea');
	tinymce.remove();
	
	// Give tinymce.init time for 1 second to be removed before re-init tinymce
	setTimeout(function(){
		// Re-init tinymce ==> This produces the error in Safari (Mac, maybe Windows too)
		tinymce.init({
    	selector: "textarea",
    	plugins: [
        	"advlist autolink lists link image charmap print preview anchor",
        	"searchreplace visualblocks code fullscreen",
        	"insertdatetime media table contextmenu paste"
    	],
    	toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
});
	}, 1000);	
}, 2000);
										

</script>

<form method="post" action="dump.php">
    <textarea name="content"></textarea>
</form>
```

Expected behaviour:
tinymce is properly cleaning up its stuff by using one of these functions, so the posted error message will not appear on calling tinymce.init again:
tinymce.EditorManager.execCommand('mceRemoveEditor', true, 'texteditor');
tinymce.remove('#texteditor');
tinymce.remove();
I have checked tinymce.min.js and couldn't find a variable called 'typeMap' nor do I use this variable name in my code.

Affected version: 4.7.2 (had this problem also in 4.5.x)
Affected browser: Thats funny, Safari (on Mac) only (tested version: 11.0.1 (12604.3.5.1.1))
It might be that this error doesn't show up in older Safari browsers.

Related to closed bug: https://github.com/tinymce/tinymce/issues/4081#issuecomment-346392019

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
