### ISSUE TITLE
Version 4.7.3 - Table bug - Breaklines below table while scrolling down

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4093]
When a new table is inserted (5x5 for example), place the pointer in the first cell/row of the table and then press the down key several times and, while you are scrolling down, the editor adds a breakline below the table for each key stroke, making an endless document.

**Comment by Afraithe** [comment]
Was not able to replicate this? What browser?

**Comment by lrusso** [comment]
I'm using Firefox, but I tried the same settings that i have for TinyMCE in the test Web (https://codepen.io/tinymce/pen/YydQrY) and what I told you before doesn't happened.

I fixed it, at least in my server, by replacing a line in the plugin.min.js table file:

s.settings.forced_root_block_attrs,"<br/>"

for:

s.settings.forced_root_block_attrs,""

This never happened to me before the new version of the Table Plugin, hope it helps.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
