### ISSUE TITLE
Version - 4.7.3 - Table bugs - New columns with a 0px width and new columns which makes the table bigger

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4098]
Bug 1) Put the cursor where it says 'place here' and add a column after that cell and it will have a 0px width. 

Bug 2) Put the cursor where it says 'place here' and add a column before that cell and it will add a column which makes the table much bigger every time you do it. After doing this, if you check the table properties, the width that appears in the width textbox is not the same the width that appears in style textbox in the advance tab.

https://codepen.io/lrusso85/pen/aVQQgg

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
