### ISSUE TITLE
Right-click pasting an image not working in FF 45.8.0

### ISSUE THREAD

**Issue by mikesugarcrm** [tinymce/tinymce#4101]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**

Copied image can only be pasted via keyboard paste.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Steps to reproduce:
1) Copy an image via print screen or the snipping tool that comes with windows
2) right click in editor and select "Paste".
3) No image is pasted. 

Repeating these steps but using the keyboard produces a successfully pasted image.

I've hacked around this issue somewhat: commenting out this call to preventDefault() in /plugins/paste/plugin.min.js:910 allows right-click paste to work:
				
				if (!isKeyBoardPaste) {
					//e.preventDefault();
				}
If you leave the preventDefault() call in place, from that point forward, the plugin looks for clipboard content of various types in various places but always comes up empty. There appear to be no data transfer items and no other avenues for retrieving the data succeed.

I suspect that leaving that hack in place would have bad consequences, but I'm interested in your team's assessment. 

**What is the expected behavior?**
Right click paste and keyboard paste should produce identical results.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
OS: Windows 7 Enterprise
Browser: Firefox 45.8.0
TinyMCE 4.5.5
This worked with version 3.5.8

Please let me know if this is a known issue with this older version of FF, or if it's fixed in a later version of tinymce, or if my hack is something we can live with. Thanks in advance for your help.

**Comment by adamjimenez** [comment]
WFM in 4.7.9, FF 59 Win 10

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
