### ISSUE TITLE
Pasting lists with abbreviations removes the abbreviated content

### ISSUE THREAD

**Issue by slushman** [tinymce/tinymce#4105]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When pasting a list from Word into a TinyMCE editor, some list items content is altered. 

Specifically, if the list item starts with an abbreviated text followed by a period (like dr. or prof.), then the abbreviated content is removed after pasting.

It does not make a difference if its a numbered or bulleted list.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Here's a Codepen demo displaying the problem:
https://codepen.io/slushman/pen/gXqypP

This bug was originally reported in WordPress, here's the bug report from WordPress CoreTrac:
https://core.trac.wordpress.org/ticket/42106

**What is the expected behavior?**
When pasting a list from Word where the list items begin with abbreviations, the list item's content would still contain the abbreviated content after pasting.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
WordPress currently uses version 4.6.7. However, I used http://fiddle.tinymce.com/ to test pasting into all the versions available between 4.6.7 and edge and they all behave this same way.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
