### ISSUE TITLE
forced_root_block deletes paragraphs when centering

### ISSUE THREAD

**Issue by arlomedia** [tinymce/tinymce#4108]
Given this source HTML...

`<p>Paragraph 1</p>`
`<p>Paragraph 2</p>`
`<p>Paragraph 3</p>`

...I can select all the text in the editor and click the Center button, and it changes to...

`<p style="text-align: center;">Paragraph 1</p>`
`<p style="text-align: center;">Paragraph 2</p>`
`<p style="text-align: center;">Paragraph 3</p>`

...as expected. However, if forced_root_block is false, it changes to...

`<p>Paragraph 1<br /> Paragraph 2<br /> Paragraph 3</p>`

It doesn't get centered, and more troubling, it combines all the existing paragraphs into one large paragraph. I understand that forced_root_block will prevent paragraphs from being created automatically, but I don't think it should remove existing paragraphs.

By the way, I'm using forced_root_block=false because most users don't understand the difference between paragraphs and line breaks and don't know they can press Shift-Enter for a line break. This is an issue in my song lyrics app because the lines within a verse need to be separated by line breaks. So I prefer the behavior where Enter always creates a line break, and users intuitively press Enter twice at the end of each verse. Then I replace two consecutive line breaks with paragraph breaks in post-processing. If there were a better way to make Enter create line breaks, I wouldn't need to change forced_root_block.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
