### ISSUE TITLE
 Version - 4.7.4 - Table bug - Context menu exceeds the editor height

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4114]
Resize the window browser in order to have the same height as the table that is in the following link (just for testing the bug). Now locate the cursor in the last row (the lastest row must be right over the TinyMCE status bar) and press the right click. The Context menu will exceed the editor height, the 'Delete table' item will be outside of the editor height. You will also see the vertical scrollbar at the right at that moment. If you cancel the context menu (by clicking somewhere else) the window will go back to the original size and the vertical scrollbar will also disappear.

https://codepen.io/lrusso85/full/wPVJBQ/

![sin nombre](https://user-images.githubusercontent.com/11498901/33792376-1e9d8ff4-dc7c-11e7-8998-f7a06660b84a.png)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
