### ISSUE TITLE
Version - 4.7.4 - Hightlight bug - Cursor can't pass the yellow text when the key down is being pressed several times.

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4116]
Place the cursor at the beginning of the document, press the down key several times (don't hold the key, just press it several times) and the cursor won't be able to pass the yellow text. This bug doesn't happen if you hold the down key.

NOTE: This only happens if the yellow text is at the beginning of the line.

https://codepen.io/lrusso85/full/eyOJWp/

**Comment by fyrkant** [comment]
I can't seem to reproduce this, which browser are you using?

**Comment by lrusso** [comment]
I'm using the latest version of Firefox. In Safari this bug doesn't exists. I don't use Chrome, so I don't know if it happens in that browser too.

**Comment by fyrkant** [comment]
Yep I can reproduce it in firefox, thank you.

**Comment by lrusso** [comment]
Your welcome.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
