### ISSUE TITLE
paste_preprocess is not working in IOS 11

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#4119]
Hi,
paste_preprocess is not working in IOS 11, is there any issue or did we changed the logic to handle in some other way.

Paste image itself is not working in IOS 11, but I handled that by having the code "var clipboardContent = getClipboardContent(Env.iOS ? e.originalEvent : e);" in editor.on('paste', function (e) event.

Can anyone give me the solution for this.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
