### ISSUE TITLE
Version 4.7.1 - Toolbar Bug - Tinymce crashes when setting toolbar to true in the init function

### ISSUE THREAD

**Issue by Drabc** [tinymce/tinymce#4122]
- This is a bug

- When setting toolbar to true in the init function it crashes 

- Fiddle with the bug http://fiddle.tinymce.com/7ggaab

- This bug at least appears in Chrome

**Comment by jayarjo** [comment]
While it's definitely undesirable outcome, but why would you do that in general?

**Comment by Drabc** [comment]
I'm passing in a variable (a boolean) into the configs
```
...
toolbar: variable
...
```

Instead, I have to do the less desirable
```
...
toolbar: variable ? false : ''
...
```

I would not have submitted an issue, but this is listed as a valid argument in the documentation for disabling the toolbar
https://www.tinymce.com/docs/configure/editor-appearance/#disablingthetoolbar

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
