### ISSUE TITLE
Paste image is not working in IOS 11

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#4123]
Hi,

pasting image is not working in ios 11, it is working after we changed the code from "var clipboardContent = getClipboardContent(e);" to "var clipboardContent = getClipboardContent(Env.iOS ? e.originalEvent : e);" in editor.on('paste', function (e)  in paste plugin.

But it "e.originalEvent" is coming as undefined, so we could not read the pasted text.

Can anyone provide us the solution for this. we are using tinymce 4.7.2

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
