### ISSUE TITLE
autosave plugin with 2 tinymce editors on a page broken?

### ISSUE THREAD

**Issue by WriterStat** [tinymce/tinymce#4128]
I have 2 tinymce editors on a page, each with separate tinymce ids.

I set the autosave plugin for the first tinymce editor.

tinymce also sets autosave on the second tinymce editor on the page even though I didn't set it.

How do I stop it from also setting autosave on the second tinymce editor? Much thanks.

Example:

Only the first editor has autosave set on it. I open the page clean. I edit in the second editor without the autosave set on it, autosave won't let me leave the page.

Cheers, -C

**Comment by WriterStat** [comment]
Needing to move on I turned the Autosave plugin off.

In case it helps someone else I used this instead for autosave:

editor.on('KeyPress', function () {
dirty1 = true;
//I placed my autosave code here. Both local and server using a debouncing code autosave system.
});

I was able then to place my own ajax server code for each separate tinymce editor and local storage code functions in the above much like google apps using a debouncing algorithm.

I created a page wide var dirty1;

Along with code for onbeforeunload using dirty1 to toggle on/off.

Wanted to use the plugin, but it seems to have some other challenges.

Will check plugin again in next version.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
