### ISSUE TITLE
CodeSample plugin Prism.js reusing problem

### ISSUE THREAD

**Issue by Razip** [tinymce/tinymce#4129]
Prism.js's code is stored inside the codesample plugin's JS file (i.e. not in a separate one) making it impossible to reuse it somewhere else on the page because you can't access it from the context it is in. Luckily, we can reuse the CSS file at least.

So please, store the code of the library separately, unless there's a major reason for it.

**Comment by Valar103769** [comment]
大佬,您好,因为那个问题被关闭了,所以来这里问一下,. 在展示页面, 引入了https://github.com/PanJiaChen/vue-element-admin/blob/master/static/tinymce4.7.5/skins/lightgray/content.min.css,但是会跟展示页其他的.css发生样式冲突,请问除了iframe的方法,有其他好的解决方法吗?tinymce编辑器使用的是tinymce-vue,展示页面使用jquery @PanJiaChen

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
