### ISSUE TITLE
tinymce 3.5.8 not showing toolbar having options to wrap, size and remove ) on image selection on IE 11. Works well with older version of IE.

### ISSUE THREAD

**Issue by irawatsanjay** [tinymce/tinymce#4132]
Cannot go for a update just for this issue. Since we have a customized version of tinymce, I want to make the fix the tinymce team made in our version of the code. Any suggestions ?

**Comment by jayarjo** [comment]
Sorry, do not understand what exactly you are asking about.

**Comment by irawatsanjay** [comment]
Cannot resize image with tinymce 3.5.8 in IE 11. Can you please mention the fix that the tinymce made for IE 11 to resolve the issue, so that I can make the same fix on our version as we cannot go for a upgrade right now.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
