### ISSUE TITLE
Custom Css Class in Styles dropdown are functioning like Listbox

### ISSUE THREAD

**Issue by jayeshmadhwani** [tinymce/tinymce#4144]
TinyMce version 4.6.4

Please see below screen shot.

Tried to change text color from dark blue to dark grey.
Color got changed but both the css classes are applied to element.
Also it applies the css based on the dropdown order.
for ex: the priority is given to the last css in dropdown.

Expected behavior:
only selected css class should be applied.

![image](https://user-images.githubusercontent.com/30536343/34721980-ce477040-f53c-11e7-8d2f-8beb5c6560a5.png)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
