### ISSUE TITLE
TinyMCE Plugin "autoresize" not working with "autoresize_max_height option"

### ISSUE THREAD

**Issue by laeeqwtb** [tinymce/tinymce#4145]
Currently I am using **TinyMCE production version (4.7.4)**  and used "**autoresize**" plugin with **autoresize_max_height: 450** but autoresize functionality not working.  The autoresize functionality was working fine with **TinyMCE production version (4.4.3)** but now I have updated editor with **TinyMCE production version (4.7.4).** After update, the autoresize functionality not working as expected.  The editor autoresize not stop when reach to autoresize_max_height value and also not creating vertical scrollbar in editor to scroll editor content in that case.

I have used following configuration with autoresize plugin with **TinyMCE production version (4.7.4)** 

autoresize_max_height: 450,
autoresize_bottom_margin: 0,
autoresize_min_height: 100,

![tinymce autoresize](https://user-images.githubusercontent.com/2102705/34723954-449ea102-f572-11e7-8d1a-6a980611d72b.png)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
