### ISSUE TITLE
Copy pasting from Word file with "strange" styling does now work

### ISSUE THREAD

**Issue by dries863** [tinymce/tinymce#4147]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I found a bug when pasting text from Word. Only a part of my text is pasted.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
- Copy the text from this Word file: 
[test-document-tinymce-past-bug.docx](https://github.com/tinymce/tinymce/files/1615311/test-document-tinymce-past-bug.docx)
- Past the text to the editor in http://fiddle.tinymce.com/

![image](https://user-images.githubusercontent.com/4720981/34724451-1da127b0-f54e-11e7-87e7-9a0063dc5c2d.png)

**What is the expected behavior?**
All text being pasted, but `Test 2.`  is not pasted as you can see in the screen.

**Probable cause**
I think the document has weird styling at the spot of the new line. It might be the styling of a comment.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
- Chrome 63
- Tinymce 4.7.4

**Comment by jayarjo** [comment]
Form what I see it happens only when Paste plugin is enabled. Without it or with PowerPaste it doesn't occur.

**Comment by dries863** [comment]
Hi Jayarjo, I see completely the opposite. When the Paste plugin (https://www.tinymce.com/docs/plugins/paste/) is enabled the copy pasting just works.

When I use the basic example (http://fiddle.tinymce.com/), It only pastes `Test 1`.

Jayarjo, did you click the enable for editing button after downloading the docx?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
