### ISSUE TITLE
Paste plugin and inline editing *paste* bug with Firefox

### ISSUE THREAD

**Issue by bago** [tinymce/tinymce#4148]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

Inline editing "broken" (content pasted outside the contenteditable).

Using Firefox
- CTRL-C to copy some text
- mouse double-click so to select the whole content of an inline editable content (in a span).
- CTRL-V to paste the content.

If the editable uses the paste plugin then the result is a broken html (the content is pasted outside the editable, sometimes the editable itself is lost).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Here is the fiddle
http://fiddle.tinymce.com/6hgaab/2

Please note the bug is there ONLY if you do the "select all" via mouse "double click" in the destination editable before you paste. If you don't run selection or you select using CTRL-A or mouse dragging then there is no bug.

**What is the expected behavior?**

Correctly paste the content.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Firefox 57 under any platform (Windows 10, Macos, Linux tested).
Works on other browser.
Didn't test previous firefox versions.

Every 4.x tinymce version seems to be affected.

**Comment by bago** [comment]
This still happens on 4.7.9

**Comment by bago** [comment]
I don't know if this was a Firefox issue, but testing with Firefox 78 I can't reproduce the issue anymore.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
