### ISSUE TITLE
Negative left absolute causes some graphical glitches sometimes.

### ISSUE THREAD

**Issue by Luke-SF** [tinymce/tinymce#4150]
**Do you want to request a *feature* or report a *bug*?** BUG

**What is the current behavior?**
In some cases, the enormous negative left absolute causes other elements to disappear with it... only in Chrome/webkit browsers, as demonstrated here:
https://bugs.chromium.org/p/chromium/issues/detail?id=800638

**What is the expected behavior?**
Perhaps this element should be display:none? What is the purpose of the negative 9 billion? Seems it may be using up graphics memory and causing this glitch.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
4.6.7, and any recent versions of Chrome/Chromium.

**Comment by Luke-SF** [comment]
This may or may not be worse for you in the current Chrome 66, there was another case that a negative large number for left value caused the whole area to disappear where it did not in previous versions:
https://bugs.chromium.org/p/chromium/issues/detail?id=831380#c12

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
