### ISSUE TITLE
Selecting text then typing a character causes cursor to jump in Chrome 63

### ISSUE THREAD

**Issue by howardjing** [tinymce/tinymce#4151]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I select some text, then start typing, the cursor sometimes jumps to a different spot. Usually it jumps to the beginning of the line, but I've seen it jump to the middle of previous paragraphs as well. 

This bug does NOT happen all the time, so I assume there's some sort of race condition going on.

Example 1:
![selection-bug](https://user-images.githubusercontent.com/831651/34797667-22ddb296-f627-11e7-9e74-0e14d2652d21.gif)

The above gif is from this [codepen](https://codepen.io/hjing/pen/ZvxRxe) example, but I've been able to reproduce it on tinymce.com as well. The code is as follows:

```javascript
tinymce.init({
  selector: 'textarea',
  height: 500,
  width: 800,
});
```

The height and width don't actually matter, I just added them to make the gif more viewable.

In the above example, I typed "hello" after selecting text. After I type the "h", the cursor jumps to the beginning of the line, so when i type "ello", the text appears as "elloh" instead of the expected "hello".

Example 2:
![selection-bug-2](https://user-images.githubusercontent.com/831651/34798706-2875b632-f62b-11e7-8473-e833d97947f3.gif)

The above bug happens on tinymce.com, and shows the cursor jumping to the line above where the cursor should actually be. This results in text that looks like the following:

```
ello
h
```

**What is the expected behavior?**
After typing the first character, the cursor should not jump around.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

I noticed this on macOS 10.12.6, running Chrome 68 with TinyMCE 4.7.4. I first noticed it on TinyMCE 4.2.6. I was not able to reproduce in Firefox 58, but since this bug doesn't happen all the time it's possible that I just didn't try enough times. I suspect there were changes in recent versions of Chrome that cause the issue, but I have not tested on older versions of Chrome to verify.

**Comment by MichaelA070** [comment]
I can confirm I have the same thing (also on MacBook - both in Chrome and Safari) - any resolution available?

**Comment by howardjing** [comment]
It's been a while, but I believe a coworker was able to reproduce this outside of tinyMCE using a contenteditable div. So while this is not a tinyMCE bug per se, it's still pretty annoying.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.

**Comment by nodexpertsdev** [comment]
I am also facing this issue in Chrome 93.0 on Mac 11.5.2. Is there any update on this?
