### ISSUE TITLE
Usability: Narrator fails to announce all the applied styles

### ISSUE THREAD

**Issue by terrimorton** [tinymce/tinymce#4152]
This issue came up during an accessibility audit.

**Summary**: Narrator fails to announce the styles which are applied to text in the editor.

**Test Environment**:

- **OS**: Windows 10 Enterprise
- **OS version**: build 16299.125
- **Browser**: Microsoft Edge 41.16299.15.0
- **Tiny MCE version**: 4.7.4 (and earlier)

**Repro Steps**:

- Start Narrator in Windows 10 (it's built-in)
- Open [https://www.tinymce.com/docs/demo/basic-example/](https://www.tinymce.com/docs/demo/basic-example/) in Edge.
- Enter some text into the editor and apply a few of the styles from toolbar.
- Now, tab back into the editor and observe narrator announcement for text with multiple styles..

**Expected Result**:
Narrator should announce all the styles applied to the text.

**Actual Result**:
Narrator fails to announce all the styles applied to the text.

**User Impact**: 
Visually impaired users, who rely on screen reader will not know what all styles applied to the text.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
