### ISSUE TITLE
TinyMCE "Link" plugin is not displaying link in link input box 

### ISSUE THREAD

**Issue by laeeqwtb** [tinymce/tinymce#4154]
Currently I am using **TinyMCE production version (4.7.4)** and used "**link**" plugin. I have found an issue with link plugin when enter text line in editor by pressing Enter key and then select all lines in editor and add link to all selected lines. Then again select text all lines in editor and click link icon to open link modal. In that case added text link is not displaying in link input box in link modal. 

![actual result](https://user-images.githubusercontent.com/2102705/34930121-f5168e80-f9ed-11e7-8bab-f0a2911da0a7.jpg)

I have also checked same on **https://www.tinymce.com/docs/demo/full-featured/** and find same issue.

![link issue](https://user-images.githubusercontent.com/2102705/34930145-18982ac6-f9ee-11e7-8175-5046623b3ae1.png)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
