### ISSUE TITLE
IOS mobile browsers: Large images display outside the editor 

### ISSUE THREAD

**Issue by amolaridas** [tinymce/tinymce#4157]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
large images, wide images and large gifs are displayed outside the editor box on mobile browsers IOS Devices.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Go to tinymce.com
select image icon and add an image
observe the image displays outside the editor box

Preview here
https://beta.weduc.co.uk/get/external/f/id/a0de40b74457b422e7b0887e0123c48ab35966e3e5b3b73e6784e4aca79cccdf.png

**What is the expected behavior?**
Scale the image correctly on the editor

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
All versions available on the tinymce website
Chrome browser
Safari browser

**Comment by studio42** [comment]
I have same problem, the images are not responsive by default.
For a so great editor, why it's not possible to add a default class for images in the config?
Eg .img-responsive for bootstrap to stop the images to be large and why is width and height set by default ?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
