### ISSUE TITLE
Image Upload - drop zone highlighting bug

### ISSUE THREAD

**Issue by gkubisa** [tinymce/tinymce#4158]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

Drop zone not highlighted in Insert Image modal -> Upload tab, when a dragged image is over the drop zone. I noticed that the mce-dragenter class is added but the styles are missing in the "modern" theme.

Additionally, the mce-dragenter class is not removed after dropping the file in the drop zone, when you go back to the Upload tab. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/rigaab

1. Click Insert Image
2. Open Upload tab
3. Drag an image over the drop zone - drop zone not highlighted.
4. Drop the image onto the drop zone.
5. Open Upload tab again - mce-dragenter class not removed from the drop zone (checked in dev-tools).

**What is the expected behavior?**

The drop zone should be highlighted, if, and only if, a file/image is dragged over the drop zone.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE: 4.7.4
Browser: Chrome Version 63.0.3239.132 (Official Build) (64-bit)
OS: Ubuntu 16.04

I don't know, if it worked before.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
