### ISSUE TITLE
Using custom images_upload_handler should set the editor to dirty.

### ISSUE THREAD

**Issue by dannoe** [tinymce/tinymce#4173]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After opening an editor with an existing base64 decoded image the images_upload_handler is triggered (with ` auto_upload: true` activated) the image is successfuly uploaded and the image src attribute is replaced/set in the editor. But the editor doesn't allow me to save (using the "save" plugin) until I manually edit something.

Use of `images_upload_url` may also be effected.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/Migaab

**What is the expected behavior?**
The editor should be marked as dirty after the img src attribute has been changed.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinymce 4.7.5 / IE11 / Win10
Did not work in previous versions.

**Possible solution**

https://github.com/tinymce/tinymce/blob/5d98aaf9657edb53398b8cba5ffa51d28491e526/src/core/main/ts/EditorUpload.ts#L93-L96 
I am not quite sure, but is adding `editor.setDirty(true)` after these lines enough/okay?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
