### ISSUE TITLE
Can't add link to nested (non)-editable elements.

### ISSUE THREAD

**Issue by dannoe** [tinymce/tinymce#4175]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Using the `noneditable` plugin. I have two nested divs. The outer one has `class="mceNonEditable"`, the inner one has `class="mceEditable`. I'm trying to add a link to an existing text in the inner (editable) div via selection and then clicking the link button, but the cursor just jumps to the beginning of the div and <strike>nothing happens</strike> you can start to type to create the link at the beginning of the editable div.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/Pigaab

**What is the expected behavior?**
I should be able to create a link via the link menu button. (It's working on Firefox 57.0.4)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
IE11, Windows 10, tinyMCE 4.7.5

**Comment by dannoe** [comment]
With `inline:true` it's also not working in Firefox 57.0.4:
http://fiddle.tinymce.com/Pigaab/5

If you don't select an existing text, the link will be inserted, but at the beginning, not at the cursor position.

**Comment by dannoe** [comment]
This is probably related to this issue: #3872
If the editable element (inside the non-editable element) loses focus, the selection is not retained.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
