### ISSUE TITLE
TinyMCE - Cursor set issue with link in editor

### ISSUE THREAD

**Issue by laeeqwtb** [tinymce/tinymce#4176]
When there only a link in editor and set cursor at the end or start of content and  load content in editor. In  that case, link is appearing selected with link icon selected in editor toolbar,  and when start writing, its writing continue with link text instead of writing text without link.

Also if there content in editor and add link at the end of content and load content in editor again and set  cursor at the end of content. In that case, link is appearing selected with link icon selected in editor toolbar.

**Steps to reproduce:**

1. Enter a link in editor
2. Set cursor in editor
3. Load editor with link content 

I have checked this issue with latest **TinyMCE version 4.7.5**

I have replicated issue on TinyMCE Fiddle URL with **TinyMCE version 4.7.5**. You can check this with exact issue.

http://fiddle.tinymce.com/Wigaab

**Expected Result**
The link should not be selected in above explained cases and editor should behave with link same as normal text in editor. When start wring after link, it should write text without link.

**Comment by fyrkant** [comment]
If you press right arrow you will "leave" the link and be able to write text.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
