### ISSUE TITLE
Dragging image from outside of editor also copies its parent elements.

### ISSUE THREAD

**Issue by adamtoms** [tinymce/tinymce#4184]
I'm unsure if this is a bug or a 'feature'. Have searched documentation and can't find any reference to the behaviour.

On dragging an image (foo.jpg) from outside of editor, it also copies the elements parent elements into the editor.

For example dragging the following
```
<ul>
  <li><img src='foo.jpg'/></li>
  <li><img src='bar.jpg'/></li></ul>
```

The editor inserts the parents and the li dragged
```
<ul>
  <li><img src='foo.jpg'/></li>
</ul>
```

I would expect just the `<img>` to be inserted.

Testing in FF 59 developer edition.

N.B. I attempted to mitigate this by registering a dragstart event to the img. Ensuring I was only dragging the correct content. However, it still insertes the elements parents

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
