### ISSUE TITLE
insertContent command auto adds p tags for comment nodes instead of keeping HTML intact

### ISSUE THREAD

**Issue by hariprasadharidas** [tinymce/tinymce#4188]
Hi, wanted to highlight a feature/bug in tinymce

**Scenario:**
Currently whenever we insert content using code below, each element gets auto inserted inside p tags. There seems to be no way to not auto enclose the content in p tags.
`tinymce.activeEditor.insertContent("<!--COMMENTS START--><p><a href='test'>test</a></p><!--COMMENTS END-->")`

**Steps:**
Open the fiddle link below and click on **Insert content** button
Fiddle example: [Fiddle link](http://fiddle.tinymce.com/rjgaab)

**Screenshot of issue:**
![image](https://user-images.githubusercontent.com/22052343/35573789-0bf8578e-05fe-11e8-9dce-c74833a9653d.png)

**Expected behavior:**
There must be a way that we can control whether p tags should get auto added or my content should stay intact.

**Tested this using many versions of tinymce and it was failing in all versions I tested (including 4.7.6)**

**Comment by hariprasadharidasnasdaq** [comment]
Hi @spocke, 
Is there someone from team you think I can reach out to in order to check on this problem we are facing here?
Thanks,
Hari

**Comment by hariprasadharidas** [comment]
@rjpepmeyer Thank you for that info, but seems like that option was not helpful for us.

**Comment by sawasawasawa** [comment]
Have you solved this? I am also having issues with `insertContent` and `forced_root_block` - the latter seems not to be working with React version I am using...

**Comment by sawasawasawa** [comment]
@hariprasadharidas I have actually mostly achieved what I needed by adding this config rule to the init config:

`valid_children: '+p[blank-field]'`

where `blank-field` is the name of the custom tag I have added. Perhaps it might help you.

**Comment by hariprasadharidas** [comment]
thank you @sawasawasawa , but this issue is more towards comment tags which are valid HTML. I think tinymce should probably add a support for this, without adding custom tag validation. Additionally, I tried using valid children, but it didn't help the scenario that is mentioned in the issue here. If you are able to find a fix for this, please let us know (maybe a fiddle? http://fiddle.tinymce.com/p3gaab/1). I'll then close this issue. Thanks in advance for the help.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
