### ISSUE TITLE
The text is not pasted to the cursor position if an anchor is added

### ISSUE THREAD

**Issue by Kobee1203** [tinymce/tinymce#4192]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
- I add an anchor 
- I move the cursor just after the anchor
- I enter some text
- I paste another text -> The text is not pasted after the entered text but before.

![tinymce_bug_anchor](https://user-images.githubusercontent.com/1423193/35632994-80a0436c-06a8-11e8-90aa-629a2ec15fec.gif)

**What is the expected behavior?**
The pasted text must be added to the cursor position

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE version: 4.7.4
Browser Chrome 63, Firefox 57, Edge 40
OS: Windows 10

**Explanation**
The problem comes from the Zero Width No-Break Space (ZWNBSP) (unicode = \uFEFF, HTML Entity = &#65279) which is not deleted. The text entered is added after the ZWNBSP. but when we paste text, it searches for the ZWNBSP and replaces it. That's why the text is pasted before.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
