### ISSUE TITLE
BUG: will not load plugins that are .min.js SIMPLE SOLUTION

### ISSUE THREAD

**Issue by silverhawk184** [tinymce/tinymce#4199]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
TinyMCE looks for plugins in the form /{plugin folder}/plugin.js. In the current release, all the js files are minified and renamed to reflect so in the form /{plugin folder}/plugin.min.js

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Download the latest Community release from the TinyMCE website (v4.7.6)
Install as directed and notice that no plugins load

**What is the expected behavior?**
Plugins such as textcolor and bullets show up in menu bar

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
v4.7.6. Not sure of others

Simple fix: go through all the plugin folders and rename the files back to plugin.js

**Comment by fyrkant** [comment]
If you load the minified tinymce build, `tinymce.min.js`, it will load the minified versions of the other files, that is plugins and theme, too.

**Comment by fox091** [comment]
> If you load the minified tinymce build, tinymce.min.js, it will load the minified versions of the other files, that is plugins and theme, too.

Note that this isn't always true.  In almost all of our production environments this happens fine, but with 2 of our environments this "minified build detection" doesn't work and TinyMCE attempts to load the *.js files rather than the *.min.js.  We have never been able to determine what is different with these environments that would cause this.  We are in the process of adding the min suffix and redeploying on the 2 bad instances to see if it will work.

**Comment by Cobra86** [comment]
I'm using ASP.Net MVC with bundles. Its working fine in the debug mode but when I switch to the release mode with bundle optimization is enable, the tinymce is loading the *.js for the plugins
This is my setup
**Bundle Class:**
var tinymce = New ScriptBundle("~/Content/Scripts/tinymce/tinymce-bundle.js").Include("~/Content/Scripts/tinymce/tinymce.min.js")
        bundles.Add(tinymce);

**Page:**
@section JavaScript
    @Scripts.Render("~/Content/Scripts/tinymce/tinymce-bundle.js");
    <script>
        $(document).ready(function () {
            testPage.pageInit();
        });
    </script>
End Section

**Tinymce Init:**
        tinymce.init({
            selector: '#TestID',
            toolbar: true,
            menubar: false,
            browser_spellcheck: true,
            height: 400,
            paste_retain_style_properties: "all",
            paste_word_valid_elements: "b,strong,i,em,h1,h2,u,p,ol,ul,li,a[href],span, color, font-size, font-color, font-family, mark",
            plugins: [
                'advlist autolink lists link image charmap print preview anchor textcolor',
                'searchreplace visualblocks code fullscreen',
                'insertdatetime media table paste code help wordcount'
            ],
            toolbar: 'formatselect | bold italic strikethrough forecolor backcolor permanentpen formatpainter | link image pageembed | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent | removeformat | code | help',
        });

**Comment by fox091** [comment]
@TheSpyder This actually did help us with this issue.  I just saw this in my inbox this morning and decided to get back around to describing the solution.

In short, we were using ASP.Net MVC bundles, or at least we thought we were, and they break TinyMCE's minified detection as well as locating other js files that should be in the same "path".  This was easily fixed for us with by setting the base path and suffix.

Why did it work on all our instances except for 2?  It turns out that our client with the botched instances had set the debug=true flags in config files to false.  We didn't know this, but we've always released our packages with the debug flag set to true and it caused the site to not actually use the bundles.  When the client flipped that config value, it caused the untested bundles to be enabled which broke this.
