### ISSUE TITLE
Allow selecting SVG elements

### ISSUE THREAD

**Issue by GabiAxel** [tinymce/tinymce#4201]
Greetings. SVG elements in TinyMCE cannot be selected by clicking, dragging or with keyboard shortcuts. I would like to request for a way to make SVG elements selectable and movable, same as IMG elements. If there is a way I could implement it with 4.7.6 that would be awesome. Thanks.

**Comment by jayarjo** [comment]
There was somewhat [similar question](https://community.tinymce.com/communityQuestion?id=9066100000097YHAAY) on our Community forum. I'll quote my answer from there:

`We do not support custom selectable elements at the moment. However what you could do is wrap your svg element into div[contenteditable="false"]. Check the fiddle here: http://fiddle.tinymce.com/Ijgaab/2.`

**Comment by alecpl** [comment]
Works for me in TinyMCE 5. There are other issues with SVG images, but I'll create a new ticket for that.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
