### ISSUE TITLE
Keep inline styles case, eg. Margin for outlook emails

### ISSUE THREAD

**Issue by alexpineda** [tinymce/tinymce#4204]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Currently inline styles are normalized to lowercase letters

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Set source code to:
```html
<div style="width:100%"> <div style="width:50px; Margin: 0 auto;">hello</div></div>
```

Result:
```html
<div style="width:100%"> <div style="width:50px; margin: 0 auto;">hello</div></div>
```

**What is the expected behavior?**
Have an option to keep case of inline styles, due to use in email clients.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I know at least from 4.5.7 to 4.7.6 this is the behavior.

**Comment by fyrkant** [comment]
Are you sure the casing of `margin` does a difference? From a quick google I found this that seems to say that outlook doesn't support margin at all: https://stackoverflow.com/questions/20347803/margin-in-html-not-working-in-outlook

**Comment by bago** [comment]
AFAIK Margin vs margin WAS something needed with outlook.com (hotmail) until few months ago. AFAIK this is not valid anymore in any email client. Unfortunately many email frameworks, blogs, tools around keep suggesting you need to use Margin if you want to use margin in email, so people keep trying ;-)

@alexpineda can you tell if you checked the uppercase vs lowercase margin issue for real? Can you provide which client/client version and which html code let you reproduce the issue?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
