### ISSUE TITLE
Insert Link issue on iOS 11

### ISSUE THREAD

**Issue by RobTDev** [tinymce/tinymce#4214]
Bug relating to the lightbox display for inserting a link on iOS devices running iOS 11

When pasting or entering content into the fields the cursor will randomly shift focus out of the field and outside the scope of any fields on the form in the lightbox.

[YouTube screen recording of the issue](https://www.youtube.com/watch?v=nSZ4VnQKLWA)

Tested and replicated the issue on iOS 11.0 - 11.2.5 both iPhone and iPad, can be replicated on tinymce.com

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
