### ISSUE TITLE
Links with blank target remove rel=nofollow

### ISSUE THREAD

**Issue by howardcox** [tinymce/tinymce#4229]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When adding a link via source view with `target="_blank"` and `rel="_nofollow"`, TinyMCE replaces the `rel` with `noreferrer noopener` and looses the `nofollow`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Paste the following into the source code editor:
```
<p><a href="/" rel="nofollow">Link no follow</a></p>
<p><a href="/" target="_blank" rel="nofollow">Link blank nofollow</a></p>
<p><a href="/" target="_blank" rel="nofollow noreferrer noopener">Link blank nofollow noreferrer noopener</a></p>
```
Closing the source view and then re-opening results in:
```
<p><a href="/" rel="nofollow">Link no follow</a></p>
<p><a href="/" target="_blank" rel="noopener noreferrer">Link blank nofollow</a></p>
<p><a href="/" target="_blank" rel="noopener noreferrer">Link blank nofollow noreferrer noopener</a></p>
```

My config is setup to allow anchors to have rel nofollow:
```
a[name|id|href|target<_blank|title|class|rel<nofollow?noopener?noreferrer]
```
Also `nofollow` is _not_ removed from normal links without a blank target.

**What is the expected behavior?**
I would expect to get `rel="nofollow noopener noreferrer"`

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE `4.5.8` installed via Composer. Reproduced in Firefox 52 and Chromium 64 on Linux.

**Comment by jayarjo** [comment]
I can reproduce this on the latest TinyMCE as well, however only with extra control characters (`rel<nofollow?noopener?noreferrer`).

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.

**Comment by Schwankenson** [comment]
It works, if you add `rel="nofollow noopener"` instead of `rel="noopener nofollow"` :)
