### ISSUE TITLE
iOS - soft keyboard keeps popping up when modal is closed with keyboard opened

### ISSUE THREAD

**Issue by kheidrich** [tinymce/tinymce#4236]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I'm using tinymce inside a modal. When I touch it to edit content and I close the modal with the soft keyboard open, after that, if I close the keyboard and touch the screen anywhere, it opens the keyboard, and will keep opening, until I open the modal again, click on the editor and close the keyboard. That makes the keyboard stop from popping.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
To reproduce, access this [CodePen](https://codepen.io/kheidrich/pen/NyYoRp)

Steps:
1. Click/Touch on the button "Open Modal"
2. Click/Touch on the editor, to edit content
3. Click/Touch on the "x" to close the modal, with keyboard opened
4. Click/Touch anywhere on the screen

**What is the expected behavior?**
It should not be opening the keyboard after I close the modal without close the keyboard and touch anywhere on the screen, except for text inputs of course.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
It happens with versions 4.6.4 and 4.7.7 of TinyMCE (versions that I've tested) and iPad (iOS 10)/iPhone (iOS 11) using Chrome and Safari.

**Comment by ModuLIZER** [comment]
I see same behavior on a SPA where there is focus on the editor with keyboard open, and then change page... every touch after this opens the keyboard.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
