### ISSUE TITLE
Inline editor image toolbar rendered incorrectly.

### ISSUE THREAD

**Issue by StartingDreams** [tinymce/tinymce#4241]
When you attempt to edit an image using the inline editor and the width of the editor container is less than 200px wide the image toolbar is rendered incorrectly.

The image toolbar covers the image, and the carrot is missing.

Demo of issue: https://codepen.io/startingdreams/pen/oEdvEv

The toolbar is absolutely positioned, and the width of the container should not affect the toolbar position.

Tested in: Chrome 64,  Firefox 58, Safari 11.0.3

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
