### ISSUE TITLE
Doesn't auto scroll at the bottom edge when body overflows its content

### ISSUE THREAD

**Issue by abelski21** [tinymce/tinymce#4244]
I'm currently using tinymce 4.4.3 on our widget for posting comments and I find it hard to fix this issue on cursor positioning in mobile safari when the tinymce content starts scrolling. 

The cursor doesn't position correctly when hitting return or next line. It only corrects when typing in on the keyboard, and turns to be wonky once you press any key after hitting the next line. 

Hoping someone knows how to fix this. I've tried adding a padding bottom but still the same. Seems like the tinymce body doesn't position correctly at the edge when hitting the next line.

Here's the gif demo of my issue:

![img_3160 trim](https://user-images.githubusercontent.com/6016540/36547871-cc9c729e-1829-11e8-9041-00cf425332e7.gif)

**Comment by spocke** [comment]
Have you tried the mobile theme. It's the official mobile support and should work better.

**Comment by abelski21** [comment]
@spocke does it support both mobile and desktop browser?

**Comment by abelski21** [comment]
Ahh you mean the additional option in config for mobile..Yeah I just tried right now. I'm still seeing the issue. I just saw in the website's [doc](https://www.tinymce.com/docs/mobile/) the latest ios version compatible is ios 10 and I'm now using ios 11.  Is it something related with the ios version? @spocke

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
