### ISSUE TITLE
Images from DOCX attempt upload each edit

### ISSUE THREAD

**Issue by eLRobbo** [tinymce/tinymce#4251]
I'm not sure if this is a bug in tinymce, moxiemanager, or word doc parser,
![2018-02-26 15_15_24-microsoft edge](https://user-images.githubusercontent.com/29283244/36693106-36496324-1b08-11e8-861d-ed0facf954c3.png)
![2018-02-26 15_16_05-windows media player](https://user-images.githubusercontent.com/29283244/36693107-3654dac4-1b08-11e8-895c-a9cad8a93d45.png)

 but someone copied and pasted a docx file to our wysiwyg editor.  It seemed to do its thing as in the view it displays more or less correctly.  However, every time I visit the editor, pop ups (4 of them) display "Image uploading ..." message.  They appear to upload, what I don't know, disappear, and then are replaced by a single "Failed to upload image: HTTP Error: 500" message.  Again, this appears to only be occurring for this docx file.  

I am at a loss as to why it appears to upload mystery images and then error out each time I visit the editor.

**Comment by spocke** [comment]
We need a dump of the HTML in the editor. Possible the raw innerHTML of the body. I'm guessing that the scanner sees base64 images and tries to upload those and the server doesn't return a proper url when doing so possible due to a too large blob size or something.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
