### ISSUE TITLE
font-family in the textarea is different than what's on the toolbar on init.

### ISSUE THREAD

**Issue by jakehjung** [tinymce/tinymce#4256]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The font-family in the textarea is different than what's on the toolbar on init.
Note that current init looks like this:

editor.on('init', function () {
   editor.execCommand('fontName', false, defaultFont);
   editor.execCommand('fontSize', false, defaultFontSize);
});

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
https://www.screencast.com/t/fuuFgtAiuund

**What is the expected behavior?**
Whatever is on the FIRST LINE of the text area should be the shown default on the toolbar.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinymce@4.6.5, chrome, any os.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
