### ISSUE TITLE
Media plugin does not work well with iframes

### ISSUE THREAD

**Issue by munkhbolde** [tinymce/tinymce#4276]
When I configure valid_elements, the media plugin automatically removes width and height from the iframe in 4.7.9. If I disable media_live_embeds, that works fine.

**Comment by fyrkant** [comment]
Can you create [fiddle](http://fiddle.tinymce.com/) reproducing the issue?

**Comment by munkhbolde** [comment]
I am so sorry for late answering. [Here](http://fiddle.tinymce.com/yogaab/3) is my fiddle.

**Comment by munkhbolde** [comment]
@fyrkant

**Comment by bares43** [comment]
Hello, I have same issue with media plugin. My fiddle is [here](http://fiddle.tinymce.com/Nygaab). When _extended_valid_elements_ for _span_ is set as _span[*]_, everything is ok. But when _span_ has some attributes, for example _span[itemprop|itemscope|itemtype|style]_, media plugin strips attributes of _iframe_ element.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
