### ISSUE TITLE
extended_valid_elements *[*] not working as expected

### ISSUE THREAD

**Issue by ahmedelgabri** [tinymce/tinymce#4291]
**Do you want to request a *feature* or report a *bug*?**
bug?

**What is the current behavior?**

Quoting the docs https://www.tinymce.com/docs/configure/content-filtering/#controlcharacters
> Use `*[*]` to include all elements and all attributes. 

But that's not the case, `i`, `b` & `script` for example are still not allowed or empty elements in general.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://jsbin.com/maqugaqeko/1/edit?html,js,output

**What is the expected behavior?**

allow all elements & attributes

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE version: 4.7.4
All browsers & OSs.

**Comment by ahmedelgabri** [comment]
Hi, any update on this?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
