### ISSUE TITLE
[IE-11.0.56] paste link is disabled in context menu, within modal popup -> source code popup

### ISSUE THREAD

**Issue by srirampearson** [tinymce/tinymce#4292]
Hi Team,

We are facing an issue with the latest IE browser version 11.0.56.

'Paste link is disabled in context menu, within modal popup -> source code popup'

Please find below the screenshot given:

https://www.screencast.com/t/KEe9UUA8tYU

Can you please fix this

Regards,
Sriram

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
