### ISSUE TITLE
lists does not work with compat3x

### ISSUE THREAD

**Issue by ignaciogros** [tinymce/tinymce#4295]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

JavaScript error in lists when the compat3x is enabled.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Add an editor with advlist and lists. Then add the compat3x and try again.

**What is the expected behavior?**

Enable compat3x and lists together, so some old plugins (like styles) work and lists_indent_on_tab too.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

I think that it happens in all the 4.x versions.

**Thank you!**

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
