### ISSUE TITLE
Right mouse click on image does not work properly in Chrome and Edge

### ISSUE THREAD

**Issue by petko** [tinymce/tinymce#4296]
Right mouse click does not select the image under mouse cursor in Chrome and Edge. You can easily reproduce it in any of the demos on tinymce.com

Right clicking on an image should:
1. select the underlying image
2. show tinymce context menu, if the plugin is active, or show the native context menu otherwise

In Firefox it works (albeit the first click after initializing the editor does not work as expected). 

In Chrome and Edge:
* if the contextmenu plugin is active, is shows the context menu, but does not select the image, so for example clicking on Image in the context menu inserts new image, instead of editing the one under the cursor
* if the context menu plugin is inactive, it select the image with the first click and shows the native context menu with the second click

In both cases what should happen is the image to be selected and the corresponding context menu to be shown, both on the first click..

**Comment by petko** [comment]
No one else experiencing this?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
