### ISSUE TITLE
Unable to write while Inline editing an A tag in Chrome 

### ISSUE THREAD

**Issue by bago** [tinymce/tinymce#4299]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Chrome: 
move at the beginning or to the end and you try to write then you are unable to write.

If you select all and start writing then you'll be able to write only a single char.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/xogaab/1

**What is the expected behavior?**

See the chars I typed appearing...

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Every tinymce 4.x
I'm testing Chrome 65 on windows but I have reports this appens on older Chromes and also on other OSes.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
