### ISSUE TITLE
Image selection is retaining in Firefox

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#4300]
Hi,

I have selected the image in the Firefox and move to other element, but image selection is retaining always.

I noticed that _moz_resizing="true" is added into the image. This is happening only for the First image selection inside the editor.

Please refer the video ref here https://www.screencast.com/t/mqCEMeJIX1

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
