### ISSUE TITLE
valid_elements converts/strips link to plain text if there is also an img rule

### ISSUE THREAD

**Issue by donShakespeare** [tinymce/tinymce#4303]
Bug!

`valid_elements` converts/strips link to plain text if there is also an `img` rule.
Worked in v3.4.9
Broken since then.

Fiddle!
```html
<script type="text/javascript">
tinymce.init({
    selector: "textarea",
    valid_elements: "a[href|target|title]", //works! no img rule
});

tinymce.init({
    selector: "div", //fails
    //inline:true,
    valid_elements: "img[*], a[href|target|title]", //fails! img present with link rule
});
</script>


<textarea><a href="http://fiddle.tinymce.com/">this link works</a></textarea>
<br><br><br>
 <div><a href="http://fiddle.tinymce.com/">this link is stripped</a></div>
```

**Comment by donShakespeare** [comment]
I have now thoroughly checked to confirm this bug.

**Comment by thorn0** [comment]
It works, just remove the space after `img[*]`:
http://fiddle.tinymce.com/Apgaab

**Comment by donShakespeare** [comment]
You are right @thorn0 very strange that a little space can create a galaxy of issues.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
