### ISSUE TITLE
window.Prism is undefined after codesample plugin loads

### ISSUE THREAD

**Issue by gkubisa** [tinymce/tinymce#4304]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

window.Prism is undefined after codesample plugin loads.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/0ogaab

The problem is that the [local `window` object](https://github.com/tinymce/tinymce/blob/ec35e25c6e5ba6fc699d65742792b7929e4318fc/src/plugins/codesample/main/ts/core/Prism.ts#L21) shadows the global `window` object, so that Prism is added to the local object instead of the global one.

**What is the expected behavior?**

window.Prism should be defined after loading the codesample plugin.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE 4.8.2
Chrome Version 69.0.3497.81 (Official Build) (64-bit)
Ubuntu 16.04

**Comment by gkubisa** [comment]
Hi @spocke , I'd like to reuse `Prism` from the `codesample` plugin. Is it expected that it is not exposed as `window.Prism`?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
