### ISSUE TITLE
Images are removed when pasting from Google Docs

### ISSUE THREAD

**Issue by gkubisa** [tinymce/tinymce#4305]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

Images are removed when pasting from Google Docs.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Create a Google Docs document containing an image.
2. Select the content, including the image, and copy it.
3. Paste into the TinyMCE editor.

**What is the expected behavior?**

The pasted image should appear in the TinyMCE editor.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE 4.7.9
Chrome Version 65.0.3325.181 (Official Build) (64-bit)
Ubuntu 16.04

Apparently it also didn't work in TinyMCE 4.2.4, see https://github.com/tinymce/tinymce/issues/2375.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.

**Comment by alvarotrigo** [comment]
@thedrjim is there any official response from the developer team regarding this?

Is it just not gonna be possible ever?
Or is it something that can be added on the roadmap?

**Comment by TheSpyder** [comment]
Have you tried it in TinyMCE 6? It seems to work (although the images are references to the google CDN and likely have the same sharing restrictions the source document does). Works in TinyMCE 5, too, in my brief testing.

**Comment by alvarotrigo** [comment]
> Have you tried it in TinyMCE 6?

It does work!! 👍 
Thanks!
