### ISSUE TITLE
Inserting a table at the bottom scrolls the view to the top

### ISSUE THREAD

**Issue by gkubisa** [tinymce/tinymce#4311]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

The view scrolls to the top after inserting a table at the bottom of the content.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Go to http://fiddle.tinymce.com/Aogaab/1.
2. Put the caret in the paragraph at the very bottom of the content.
3. Insert a table.

**What is the expected behavior?**

The view should not scroll - I'd like to immediately see the table I inserted rather than the beginning of the content.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE 4.7.9
Chrome Version 65.0.3325.181 (Official Build) (64-bit)
Ubuntu 16.04

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
