### ISSUE TITLE
Issue with Insert Link function

### ISSUE THREAD

**Issue by redhorseck** [tinymce/tinymce#4313]
I am reporting a possible bug. 

When using the Insert Link toolbar button, I will enter a URL with a couple of space in the path. When I hit ok, and look at the html code, the first space in the URL has been converted to %20. This did not happen in 4.4.3. It does happen in 4.7.7 and 4.7.9. We are using the downloaded self-hosted version, not the cloud version. We are using it in an IE based .net webbrowser control.

As an example, here is the path I want to put in the URL field:
E:\file with spaces in path\my doc.docx

In the body, I enter the text "Click". Double click the word "Click" and then click the Insert Link button in the toolbar. Enter the text url from above in the URL field. Click OK to save. View the html. Here is the resulting html:
<a href="E:\file%20with spaces in path\my doc.docx">

I don't know if this is by design or not, but we preferred when it left the url as we typed it in in earlier versions. We can not use it if it has the first space converted to %20. I do not know what version this began with, but tinymce has not always done this.

**Comment by spocke** [comment]
It seem very inconsistent what the browsers do with spaces I think they should all be converted to %20 to be a valid url. Created a fiddle here different results on FF and Chrome. https://jsfiddle.net/ddsdrnyv/

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
