### ISSUE TITLE
Insert template popup - dropdown overlapped by browser window

### ISSUE THREAD

**Issue by AlexanderHH** [tinymce/tinymce#4322]
I have the problem, that at my pop up window, with possible templates, the drop down field doesn't consider browser borders. See screenshot: 
![popup](https://user-images.githubusercontent.com/6066939/38307645-0ae945c8-381d-11e8-8cd3-4c2c3c94910b.png)
Currently there are a developer tools, but also without devtools it happens:
![image](https://user-images.githubusercontent.com/6066939/38307912-0a26058a-381e-11e8-9021-bb3cea1583d5.png)

I think it should be dynamically adjusted to the window.
I'm using the version: majorVersion: "4", minorVersion: "7.6", releaseDate: "2018-01-29" on Win10 with Chrome browser.

Also, if I move the popup around, the drop down field stays where it was opened:
![image](https://user-images.githubusercontent.com/6066939/38307959-39bee258-381e-11e8-8077-586a8a134cf5.png)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
