### ISSUE TITLE
Version 4.7.10 - Template plugin - Wrong vertical location

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4326]
Tested in the latest version of Firefox. With a 1024x768 screen resolution (or resizing the browser window to a 600px height), the template window is located far up. After resizing the window (just a few pixels), the template window automatically goes to the center of the screen.

![captura de pantalla 2018-04-05 a la s 20 03 23](https://user-images.githubusercontent.com/11498901/38396085-8642b2dc-390c-11e8-8572-347be70ebbee.png)

**Comment by spocke** [comment]
Can't seem to reproduce this. It aligns vertically on firefox when we try it.

**Comment by lrusso** [comment]
Try to first to set the browser window height to 600px, then enter www.tinymce.com and click in the Template Icon.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
