### ISSUE TITLE
Keypress doesn't fire for Enter key, unless error thrown from keydown listener within plugin

### ISSUE THREAD

**Issue by viveleroi** [tinymce/tinymce#4334]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

`keypress` events are not thrown for `Enter` keys. Natively they should be. It's strangely possible to get them to fire when I throw an error from a `keydown` event from within a plugin.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/2pgaab

Keypress doesn't fire on "Enter":

    tinymce.init({
        selector: '.editor',
        init_instance_callback: function(editor) {
            editor.setContent(content);

            editor.on('keydown', event => {
                console.log('keydown', event);
            });

            editor.on('keypress', event => {
                console.log('keypress', event);
            });
        }
    });

Keypress does fire on Enter, only when an error is thrown from `keydown`:

    tinymce.PluginManager.add('test', (editor, url) => {
        editor.on('keydown', event => {
            console.log('keydown', event);
    
            throw new Error('fake');
        });
    
        editor.on('keypress', event => {
            console.error('keypress', event);
        });
    
        return {
            getMetadata: () => {
                return {
                    name: 'test'
                };
            }
        };
    });

**What is the expected behavior?**

Keypress should always fire events for Enter.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Version 4.5.7, Chrome 65.0.3325.181 (Official Build) (64-bit) on macOS Sierra 10.12.6

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
