### ISSUE TITLE
Resizing table using resizer bars triggers editor blur

### ISSUE THREAD

**Issue by triplejumper12** [tinymce/tinymce#4342]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When you attempt to resize a table using the horizontal or vertical resizer bars, the editor triggers blur. If you are manipulating content on blur, it won't resize since the content being inserted back into the editor didn't know about the resize.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
[fiddle.tinymce.com/dDeaab/12](http://fiddle.tinymce.com/dDeaab/12)
If you have the editor in focus (seeing the editor toolbar) and you try to make the table larger by dragging on the resizer bars, it doesn't actually resize the table. It works if you resize the table without having the editor in focus, or if you use the corner resizing hotspots.

**What is the expected behavior?**
It shouldn't trigger blur on the editor

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
We are using the newest version of TinyMCE (4.7.11). It looks like the last time it worked correctly was in 4.6.7. We've been able to replicate this on Windows, Linux, and Mac in Chrome, Firefox, Microsoft Edge, and Safari.

**Comment by triplejumper12** [comment]
This appears to still be an issue in the developer preview of v5. Any plans of fixing this?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
