### ISSUE TITLE
Version 4.7.11 - Editor suggestion when pressing the enter key at the bottom of a table

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4345]
Tested in Firefox. When the editor is located at the bottom-right of a table, you will see the fake caret. Now, after pressing the enter key a `<p>&nbsp;</p>` is inserted in order to do a breakline. But, it wouldn't be better to add a `<br />` instead? When a paragraph is added, it appears as a new line but with a padding and margin that a breakline doesn't have. Or that the editor would obey the `force_br_newlines = true` in this situation? Just a suggestion. Hope it may help.

**Comment by Afraithe** [comment]
No, a paragraph is the correct thing to add, but it should probably follow the force_br_newlines setting.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
