### ISSUE TITLE
Relative image paths break with inline mode

### ISSUE THREAD

**Issue by adamjimenez** [tinymce/tinymce#4346]
My test code contains an image with a relative url. I have convert_urls enabled but it only seems to take effect after I make an edit and get the content, not on the initial viewing.
The `mce-src` value is being set correctly.
This is what I'm seeing:
![image](https://user-images.githubusercontent.com/573192/38817698-d7c9927e-4190-11e8-92cd-73ad41cf48ca.png)

Check out [the fiddle](http://fiddle.tinymce.com/Rpgaab/6).

**Comment by adamjimenez** [comment]
Added a [fiddle](http://fiddle.tinymce.com/Rpgaab/6). Seems to only happen when inline is enabled.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
