### ISSUE TITLE
StyleSheetLoader loading multiple copies of css (not verifying existence before loading).

### ISSUE THREAD

**Issue by robertleelittleiii** [tinymce/tinymce#4349]
Report a bug with: StyleSheetLoader (@class tinymce.dom.StyleSheetLoader)

StyleSheetLoader is not checking the DOM to see if a stylesheet has already been loaded. 

In my application, I am using jquery dialogs for edits on a page.  The first time I load the dialog box everything is OK.  The second time I load it, somewhere in the tinymce code StyleSheetLoader is loading and adding "skin.min.css" at the end of the head tag.  I end up with multiple copies of the "skin.min.css".  

When my application loads the dialog box, it also loads any css files and js files required to edit a page and places them at the end of the head tag.  My system checks so it doesn't load the js and css files more than one time.  The tinymce StyleSheetLoades doesn't so I end up with this:

```
<link rel="stylesheet" type="text/css" href="/assets/pages.css">
<link rel="stylesheet" type="text/css" id="u0" href="http://localhost:3000/assets/tinymce/skins/lightgray/skin.min.css">
<script type="text/javascript" src="/assets/codemirror/lib/codemirror.js"></script>
<script type="text/javascript" src="/assets/codemirror/mode/htmlmixed/htmlmixed.js"></script>
<script type="text/javascript" src="/assets/codemirror/mode/css/css.js"></script>
<script type="text/javascript" src="/assets/codemirror/mode/xml/xml.js"></script>
<script type="text/javascript" src="/assets/codemirror/mode/javascript/javascript.js"></script>
<script type="text/javascript" src="/assets/codemirror/lib/formating.js"></script>
<link rel="stylesheet" type="text/css" href="/assets/tinymce/plugins/codemirror/plugin.css">
<link rel="stylesheet" type="text/css" href="/assets/codemirror.css">
<link rel="stylesheet" type="text/css" id="u0" href="http://localhost:3000/assets/tinymce/skins/lightgray/skin.min.css">
```
This places another copy of the "skin.min.css" at the end and some of the definitions override the ones in codemirror.  

The solution is to check the DOM for the stylesheet you are loading before you add it to the DOM. Just don't add it if it's already there, saves on bandwidth/time also.  I had added some code to remove the extra "skin.min.css" links before I call codemirror for the second time and this has fixed it for now.

I have seen this issue for a long time.  I had some time today and finally figured out what was causing codemirror to blow up.   It happens in all browsers, all OSs and version 3 and 4 of tinymce.

**Comment by spocke** [comment]
Wasn't able to reproduce it here: http://fiddle.tinymce.com/3qgaab please provide a way for us to reproduce it though a fiddle. Thanks.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
