### ISSUE TITLE
Right border missing when zooming out

### ISSUE THREAD

**Issue by hristop** [tinymce/tinymce#4350]
**Do you want to request a *feature* or report a *bug*?**

Report a bug: When we use the the tinyMCE editor and zoom out to 90% the right border is disapearing. 

**What is the current behavior?**

As mentioned above, there are borders which disappear and again reappear when you start zooming out. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

It can be reproduced via your examples when using this snippet:
https://codepen.io/tinymce/pen/NGegZK
(you can add 15-20px of padding to the body so you can see the issue easier).
![90_percent_right_border_missing](https://user-images.githubusercontent.com/14230119/38994643-9d0af4d2-43ef-11e8-82b8-1aa93d67598d.jpg)

**What is the expected behavior?**

All borders should be visible

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

We tested this in Chrome on Windows and MacOS.

**Comment by spocke** [comment]
This one is weird it seem to have something to do with how the rendering engine works. It works fine in firefox for example and if you change the border thickness to thin or 1pt it works so something with px values on chrome is causing the issue.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
