### ISSUE TITLE
Image plugin: Add border color picker

### ISSUE THREAD

**Issue by ignaciogros** [tinymce/tinymce#4356]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

No color field in the "Advanced" tab.

**What is the expected behavior?**

It'd be good to have a "colorbox" field for that, and to make it work if you write something like this too: `style: border 1px solid red;`

**Thank you!**

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
