### ISSUE TITLE
Listbox selection problem in modal dialogs since 4.7.10

### ISSUE THREAD

**Issue by sjoris** [tinymce/tinymce#4359]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I have a plugin with a modal dialog with listboxes. The contents of the second listbox changes after changing the value of the first listbox. Since TinyMCE version 4.7.10 the selection of the second listbox is not updating. If you click on the second listbox, you can see that the listitems are updated, but the current selection is not changing when you click on an item.
[fiddle.tinymce.com](http://fiddle.tinymce.com/2qgaab)

**What is the expected behavior?**
The expected behavior would be to see the current selected item in the Sub list. And by clicking on OK, the selected Sub value would be inserted in the content.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
4.7.10 and 4.7.11 are giving the wrong result.
I tested in Chrome, Firefox and Edge on Windows 10. All have the same results.
This worked perfectly in TinyMCE 4.7.9 and lower.

Maybe I'm using _repaint_ or _reflow_ in a wrong way, but I couldn't find a good example or documentation about this feature.

**Comment by sjoris** [comment]
I found a fix for this problem.

I used this line to fill the listbox with new items:
`box2Field.state.set('menu', box2items);`

That just wasn't enough. I changed it to these lines, to get it to work in every TinyMCE version 4.x:
`if (box2Field.hasOwnProperty('state')) {`
  `box2Field.state.set('menu', box2items);`
`}`
`box2Field.settings.values = box2items;`
`if (box2Field.settings.hasOwnProperty('menu')) {`
`  box2Field.settings.menu = box2items;`
`}`

Now it works like a charm: [fiddle.tinymce.com](http://fiddle.tinymce.com/Sqgaab)

The previous method only worked from version 4.2.x unitl 4.7.9. Now it also works from verison 4.0.x and up.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
