### ISSUE TITLE
Problem with blockquote and unordered list

### ISSUE THREAD

**Issue by Horaigo** [tinymce/tinymce#4360]
**Do you want to request a *feature* or report a *bug*?**
*Bug*

**What is the current behavior?**
I have some problems with blockquote's selection in unordered list. Then you make unordered list and try to select with blockquote one of list's items, it's select whole item. If you change the color of any part of the element, and then try to select the text with a blockquote holding the cursor on the word with a different color, then instead of the entire element, we select only the part of element with the changed color.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
You can try to repeat this situation on one of the demos you proposed (for example on this one:
https://www.tinymce.com/docs/demo/full-featured/) if you add there a button with a quote and repeat the steps described above.

**What is the expected behavior?**
 It was expected that we would select the entire list item.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE version 4.7.7. All browsers. No

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
