### ISSUE TITLE
Text shifts down when using toolbar with inline editor and adjacent block element IE11

### ISSUE THREAD

**Issue by mradcliffe** [tinymce/tinymce#4364]
**Do you want to request a *feature* or report a *bug*?**
Bug report.

**What is the current behavior?**

Text "shifts" down below the baseline of a line while typing text after using a formatting option such as Font or Underline in an inline editor using IE11.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

* http://fiddle.tinymce.com/crgaab (4.7.11)
   1. Click below "another block element" to enter editor.
   2. Type some text.
   3. Click Underline button or change Font
   4. Type some text - notice that the text drops down while typing.
   5. Hit enter twice and the text returns to its original baseline.
* https://tinymce.com
   1. Clear out the text on tinymce.com
   2. Type some text.
   3. Click Format > Underline
   4. Type some text - notice that the text drops down while typing.
   5. Hit Enter twice and the text returns to its original baseline.

The bug is more prominent in larger font sizes and alternate line heights especially if a background is applied to the editor.

It seems the cause is related to the block level element siblings to the editor, which is the case when an editor is embedded into a web page such as https://tinymce.com or any other web page. Adding a `[data-mce-type]#_mce_caret { display: inline-block; margin-top: -0.2em }` works around the issue, but that invokes IE11's contentEditable resizable box around the caret. If there was a way to disable that box, then I think this is just another quirk to IE11.

**What is the expected behavior?**

Text remains consistent while editing similar to behavior in Chrome, Firefox, Edge and Safari so users are not confused.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

- 4.7.11, unknown testing in other versions.
- Internet Explorer 11.371
- Windows 10 Pro

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
