### ISSUE TITLE
Mobile theme should be able to enter editing screen directly

### ISSUE THREAD

**Issue by MrMilo** [tinymce/tinymce#4372]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
I'm not able to enter Editing screen directly for mobile theme, it always land into a "Book icon" screen first.

My use case is that I have a mobile apps that display a webview, which will only contain the editor, the experience would be better if user can directly enter edit mode instead of clicking "Book icon" which is an extra step.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
4.7.11

**Comment by MrMilo** [comment]
any update on this?

**Comment by MikeS1042** [comment]
I"m looking for an update on this too. It's preventing me from updating the editor to the new version.

**Comment by Mooreel** [comment]
I did a friendly user trial and out of 12 users, 11 found clicking the book icon irritating and in 5 cases it took multiple attempts to open the actual editor.

I really think this is a key ux issue and I hope it is going to be tackled?

**Comment by brianlanger** [comment]
Agree with the other comments, at least if we had the possibility to opt out from using that behaviour and letting the user engage fully in one tap. 
Silver theme works but the events wont, so dragging for example, doesn't work and it defeats the purpose of using that workaround.

**Comment by MrMilo** [comment]
still no update / work around on this?

**Comment by TheSpyder** [comment]
We've begun work on a major mobile update. I think this will be the fifth iteration of a mobile UI the company has produced since we first tried in 2013? :)

This time we're aiming to not have any mobile-specific UI elements. Modern mobile browsers, particularly Safari 13 beta, make this a much more viable experience than it used to be. In particular there seems to be less need to control the entire viewport which is why tap to edit was introduced.

It's not mentioned in the changelog, but if you use the workaround mentioned above you can already see interim progress on this as dialogs now respond to screen size. They aren't all finished however and there's still plenty of other work to do too.

**Comment by lnewson** [comment]
Hi,

TinyMCE 5.1.0 was released late last year which is what @TheSpyder was referring to above. More details can be found in the [5.1 release notes](https://www.tiny.cloud/docs/release-notes/release-notes51/#mobile). I'll go ahead and close this, but please do let us know if you have any issues with the new mobile changes.

Thanks!
