### ISSUE TITLE
Table deletion reorders paragraphs inside tinymce

### ISSUE THREAD

**Issue by hariprasadharidas** [tinymce/tinymce#4375]
Hi, Highlighting a bug in tinymce

**Scenario**: Please check the video in the zip file attached with this issue and the JSFiddle link mentioned below. 
Steps to recreate:
1. Create a content such that we have 3 paragraphs
2. Insert a table between first 2 pargraphs (with just one cell)
3. Double click and select contents of table cell and press DELETE on keyboard

**Current behavior**: Order of paragraphs are not maintained when a table is removed using DELETE button

**Expected behavior**: Order of paragraphs should be maintained when a table is removed using DELETE button

**JS Fiddle**: [Fiddle](https://codepen.io/anon/pen/XqgQYQ)

**Demo video**: [Tinymce Paragraph switch.zip](https://github.com/tinymce/tinymce/files/1971980/Tinymce.Paragraph.switch.zip)

I have tested this behavior in latest version of tinymce and in old version as well. Seems to be broken in both versions.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
