### ISSUE TITLE
Impossible to append text after links on mobile devices

### ISSUE THREAD

**Issue by alexpyzhianov** [tinymce/tinymce#4383]
**Usability issue**

When you have a link that is at the very end of the line and you want to append some text, link styling extends to it. You can only break it by pressing right arrow key, which is not obvious and means that **there is no way to do it on a mobile device or on a keyboard without arrow keys**

#3830 already raises this issue, but is closed. Still the issue is real

**What is the current behavior?**
![links-tinymce](https://user-images.githubusercontent.com/7609100/39739606-76831240-529a-11e8-90b9-fd712c55dc3a.gif)

**What is the expected behavior? (Google Docs)**
![links-gdocs](https://user-images.githubusercontent.com/7609100/39739607-769f9424-529a-11e8-9fd2-130fab246281.gif)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

I use Linux/Chromium. Tried it on my Android device. Reproducible on https://www.tinymce.com/ demo, the current version I believe is 4.7.12

**Comment by alexpyzhianov** [comment]
I can work on this and submit a PR, if we decide that the behavior should be like in the second example

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
