### ISSUE TITLE
Feature request: add a possibility to add classes to figure element while using image upload button

### ISSUE THREAD

**Issue by Mareddie** [tinymce/tinymce#4393]
As the title suggests, it would be really nice to have some styling options when it comes to generated HTML with `image_caption: true` option. For example to define classes for `<figure>` and `<figcaption>` elements. 

`image_caption` is awesome though, it needs some tweaks. Thanks!

**Comment by Afraithe** [comment]
Do you need classes, can you not reference them by parent + figure?

I believe you could force a class in by setting a new extended_value_elements for the figure tag.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
