### ISSUE TITLE
Block-style formats can't be applied to multiple table cells at once

### ISSUE THREAD

**Issue by cdhowie** [tinymce/tinymce#4397]
**Do you want to request a *feature* or report a *bug*?**

I'm not sure honestly if this is a feature request or a bug report.  Applying inline styles to multiple table cells works, so it's at least an inconsistent user experience that block styles can't be applied the same way.

**What is the current behavior?**

When multiple table cells are selected, inline styles can be applied to them all (bold, italic, etc.) but block styles cannot (list, indentation, etc.).  Block styles are applied only to the last selected cell, not all selected cells.

**What is the expected behavior?**

It would seem reasonable to me that block styles should be applicable to multiple table cells in the same way as inline styles.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

This issue is present in 4.7.12 and was tested on Chrome and Firefox.  I do not know if prior versions supported this functionality.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
