### ISSUE TITLE
Cursor only changes to "text" over content in iframe

### ISSUE THREAD

**Issue by jordan-p-jones** [tinymce/tinymce#4400]
Currently, when mousing over the tinymce rich-text block the mouse cursor only changes to the "text" style if it is over the html that has been generated so far in the frame. This is misleading because it makes the user think that the frame can only be selected by clicking near the top (in the case where no content has been created in the frame yet), even though clicking anywhere in the content area will select it.

The mouse cursor should change to the "text" style as soon as it enters the edit area.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
