### ISSUE TITLE
Wrapping multiple block elements but inline styles get applied to children

### ISSUE THREAD

**Issue by mrazzari** [tinymce/tinymce#4403]
**Do you want to request a *feature* or report a *bug*?**

Bug. Regression. Firefox only.

**What is the current behavior?**

Repro here: http://fiddle.tinymce.com/0sgaab/3

1. Select version: TinyMCE **4.6.7** or above. 
2. Click "Run" 
3. Select both paragraphs in the text editor, and click the "Blockquote" button.
4. Click the "blockquote" tag in the editor's status bar, to select it.
5. Click the "Align right" button.

![bad](https://user-images.githubusercontent.com/324617/40260354-84a9108e-5ad0-11e8-8f87-02a3bf74f661.gif)

**Current output (bad):** a text-align style will be applied to the individual paragraphs within the blockquote, and no CSS class will be applied to the blockquote.

```html
<blockquote>
<p style="text-align: right;">Paragraph 1.</p>
<p style="text-align: right;">Paragraph 2.</p>
</blockquote>
```

**What is the expected behavior?**

Again here: http://fiddle.tinymce.com/0sgaab/3

1. Select version: TinyMCE **4.6.6** or below. 
2. See steps above

![good](https://user-images.githubusercontent.com/324617/40260417-da95d0fe-5ad0-11e8-9b5c-7a65c59aeb70.gif)

**Expected output (good):** The blockquote tag gets the alignright CSS class.

```html
<blockquote class="alignright">
<p>Paragraph 1.</p>
<p>Paragraph 2.</p>
</blockquote>
```

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

This starts happening with TinyMCE 4.6.7 and is still a bug in 4.7.13, Edge or Nightly (today).
Only happens with Firefox. 
The bug is not present in Chrome or MS Edge.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
