### ISSUE TITLE
Table in non editable block can be modified

### ISSUE THREAD

**Issue by dev2k** [tinymce/tinymce#4405]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Table in non editable block can be modified. You can resize the columns and sametimes toolbar will be shown.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/Lsgaab
**What is the expected behavior?**
No modifications should be allowed
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
*

**Comment by RickeyWard** [comment]
I'm seeing this exact same behavior. When in an inline editor is in readonly mode, if you resize the page, sometimes the table editing tools from the editor activate.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
