### ISSUE TITLE
Cannot read property 'parentNode' of null when selecting clear format

### ISSUE THREAD

**Issue by safinazward** [tinymce/tinymce#4414]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
An exception is thrown after clicking on clear formatting:
Uncaught TypeError: Cannot read property 'parentNode' of null.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1- Write any text in the editor then choose superscript or subscript format.
2- Keep writing then add just space and click clear formatting.

**What is the expected behavior?**
Clear the format for the text that will be written after selecting clear format option.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Browser: Chrome Version 66.0.3359.181 (Official Build) (64-bit)
OS: Windows 10
Tinymce Version: 4.7.10
It happens just on Chrome , It works on IE11.
I do not know if it is the same bug as #4265

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
