### ISSUE TITLE
In inline mode, Toolbar doesn't hide, once toolbar had focus

### ISSUE THREAD

**Issue by alex-kowalski** [tinymce/tinymce#4424]
Hello! 
I know that when click me, toolbar is shown, and then click out of me, toolbar should be hidden. 

But I found the issue like below:

When click me and click 'font-size', and click 'font-size' again, and click out of me even several times, TINYMCE toolbar doesn't hide. 
Only when click space between font-family and font-size, and click out of me, also TINYMCE toolbar doesn't hide. 

In a word, when toolbar has focus and click out of me, it doesn't hide.

This is fiddle: http://fiddle.tinymce.com/Atgaab

You can also check this here:
https://jsfiddle.net/Larang/5gp2rkcs/12/

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
