### ISSUE TITLE
Bottom boundary of modal popup dips below bottom of screen boundary

### ISSUE THREAD

**Issue by es11support** [tinymce/tinymce#4434]
**Do you want to request a *feature* or report a *bug*?**

Possible bug.

**What is the current behavior?**

When opening either "Insert/edit image" or "Insert/edit link" dialog boxes, the bottom of the "Image List" and "Link List" boxes dip below the bottom boundary of the screen, leaving any files below the screen unclickable.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Attached is a screenshot of the behavior - the "Image List" box has a total of 30 images in it, only the first 29 are visible, and scrolling down to the bottom only gets you to 29.  Image 30 is not accessible from the drop-down.

![tinymce-link-list](https://user-images.githubusercontent.com/33695148/41180245-9aa1f326-6b3b-11e8-964b-c3194dd0c036.jpg)

**What is the expected behavior?**

I'd expect that the pop-up would recognize the bottom boundary of the screen and stop there.  You can close out of the drop-down and move the pop-up further up the screen to access files lower in the list, but I'd assume it would still cut off after the ~60th or so file (and that's not really an option, just a workaround).

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

I'm seeing it in version 4.7.13 (2018-05-16), using Firefox 60.0.2 (64-bit), on a 1920x1080 monitor.

On Google Chrome 67.0.3396.79 (Official Build) (64-bit), the 30th item in the list is BARELY visible at the bottom - it can be clicked, but anything below it cannot.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
