### ISSUE TITLE
toggle custom style formats not working as expected

### ISSUE THREAD

**Issue by Cordemans** [tinymce/tinymce#4439]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Removing a custom style be selecting the custom style again from the "Formats" dropdown menu will not toggle for every specified custom style.

It depends on the used styles:
Specifying `"#FF000"` as `background-color` will not toggle off.
Specifying `"red"` as `background-color` does work.

In this fiddle 3 custom styles are specified. Only the first style you can toggle on and off. You are not able to toggle the other styles.
http://fiddle.tinymce.com/Ntgaab

**What is the expected behavior?**
That it is possible to toggle the custom styles.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
4.7.13 (and before)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
