### ISSUE TITLE
Text to display field in Insert Link is not displaying with 'inline:true' in IPAD

### ISSUE THREAD

**Issue by mallikarjuna909** [tinymce/tinymce#4458]
Hi,

I got one issue with editor in IPAD with 'inline:true' configuration.

1. Select some text in editor
2. Click on ‘Link’ from Insert menu (Direct Link button is working)
3. 'Text to display' field is displaying empty.

When i debug i got to know that because ‘selection.getContent()’ returns empty value, even though we select some text.

Please find my snippet [here](https://codepen.io/anon/pen/KeBqmB#0)
 
Please do needful asap.

Thanks.
Malli.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
