### ISSUE TITLE
KeyDown default prevented outside inline boundary

### ISSUE THREAD

**Issue by aduth** [tinymce/tinymce#4476]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

When pressing ArrowRight on the outside right edge of an inline boundary, the event wrongly has its default behavior prevented.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Demo: http://fiddle.tinymce.com/hvgaab/1

Steps:

1. Place caret at the end of the bolded text.
2. Press ArrowRight
3. Log should show "default prevented: true"
   - Expected because TinyMCE is handling the transition to the outside edge of the inline boundary
4. Press ArrowRight once more
5. Log _should_ show "default prevented: false", but shows "default prevented: true"

**What is the expected behavior?**

TinyMCE shouldn't be handling ArrowRight from the outside edge of an inline boundary, so its default behavior should not be prevented.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE 4.7.13
Chrome Version 67.0.3396.99 (Official Build) (64-bit)
macOS High Sierra Version 10.13.5 (17F77)

**Comment by spocke** [comment]
We need to prevent all default keyboard navigation around inline boundaries since we need to control the behavior to insert our own custom behavior and the nbzwsp characters. The last caret position in the text node needs to be intercepted since it would otherwise lean left back into the boundary element since webkit/blink browsers normalizes the range to the closest left element caret position.
