### ISSUE TITLE
Markup error when removing custom format from paragraph in table

### ISSUE THREAD

**Issue by cskwg** [tinymce/tinymce#4477]
BUG: Markup error when removing custom format from paragraph in table.

VERSION: 4.7.13. Also present in 4.5.3. In IE 11 and latest Firefox.

We are using a custom 'style_formats' menu.
For example:
    items: [ { title: 'Page break before', block: 'p', classes: 'pagebreak_before' },

Within normal text, this is working fine.
Within tables it produces wrong markup.

The steps for producing this are:

- Create empty text. Insert table (3x3). Go to cell (2,2). 
- Insert some 3 paragraphs with test text.
- Select one of them and apply the P format ('pagebreak_before').
- Keep the selection in the same place and then revoke the format.

Now the <P> tags have been removed from the paragraph.

It can be reproduced in the "fiddle":
<script type="text/javascript">
tinymce.init({
    selector: "textarea",
    plugins: [
        "advlist autolink lists link image charmap print preview anchor",
        "searchreplace visualblocks code fullscreen",
        "insertdatetime media table contextmenu paste"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
	,style_formats: [ { title: 'Paragraph', items: [
							{ title: 'Page break before', block: 'p', classes: 'pagebreak_before' } ]
					} ]
});
</script>
<form method="post" action="dump.php">
    <textarea name="content"></textarea>
</form>

Although it might not happen on the first try.

The expected behavior is, that the formatting can be applied and removedrepeatedly.

Kind regards
Karl

![initial-markup](https://user-images.githubusercontent.com/4463131/42132360-e03f4e5a-7d16-11e8-91d7-d222362af485.png)
![initial-edit](https://user-images.githubusercontent.com/4463131/42132361-e06eeae8-7d16-11e8-8045-5774815f5058.png)
![good-markup](https://user-images.githubusercontent.com/4463131/42132362-e099ae04-7d16-11e8-9592-048bae0a5745.png)
![good-edit](https://user-images.githubusercontent.com/4463131/42132363-e0bfca26-7d16-11e8-804f-ea7f0b61aeb4.png)
![final-bad-markup](https://user-images.githubusercontent.com/4463131/42132364-e0e018b2-7d16-11e8-8518-b3f25b0af805.png)
![final-bad-edit](https://user-images.githubusercontent.com/4463131/42132365-e100cd1e-7d16-11e8-991e-36fc15461495.png)
![fiddle](https://user-images.githubusercontent.com/4463131/42132366-e14036a2-7d16-11e8-9b94-67058165e3ef.png)

**Comment by SimonFc** [comment]
Hi,
This seems to be the desired behavior and is due to how certain elements are allowed to be children of others. In well formatted markup text nodes are allowed to be direct children of td's, while in the root of the editor(for example) this is not the case. If you write in the root, p-tags are inserted automatically, while if you write in td's they're not.

style_formats & tiny is designed to follow this behavior and will aim for well formated markup.

**Comment by cskwg** [comment]
Hi Simon, could you please explain what your answer has to do with the question?
This behavior is very obviously wrong and it has no relationship to being in the root of the document.
The correct behavior would be to just remove the formatting class, without removing the surrounding P tags.

**Comment by SimonFc** [comment]
Hi Karl,
I understand that it might seem strange, and I thought as you did that this was obviously an incorrect behavior, but due to the design of tiny it'll always strive for whatever markup is deemed the most correct. Write in the root of the editor(without newline/pressing enter) and you'll see that the content is placed in P tags. Not so inside TD's.

In the process of toggling the class it'll reduce the P tag as much as possible. Instead of inserting a P tag without any attributes in the end for it'll just insert a text node as that is what is deemed correct in the context. (Which is that of being a child of a TD tag.)

I understand that it might seem a bit unexpected still though so I'll check if we have any plans on changing this.

**Comment by cskwg** [comment]
Hi Simon, the TD tag may contain P, as specified here: 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td
https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Flow_content
IMHO the behaviour is clearly buggy.
A single text note between two P nodes is not common and could lead to formatting errors if the P's were positioned (moved). Please keep the existing P tags.
