### ISSUE TITLE
Bug: using style_formats_autohide sometimes breaks the position of the styleselect

### ISSUE THREAD

**Issue by fabsn182** [tinymce/tinymce#4496]
When using the `style_formats_autohide`-option, tinymce calculates a wrong position for the styleselect-dropdown.
This happens when the dropdown itself is too long to be positioned below the styleselect-button and gets positioned above:

See: http://fiddle.tinymce.com/gwgaab

Also: when there isn't enough space neither below nor above the dropdown, it appears behind the button

![Pos 1](https://user-images.githubusercontent.com/13197057/42872402-25111090-8a7d-11e8-84b4-ca6f73553643.PNG)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
