### ISSUE TITLE
Inline toolbar float panel appearing when toolbar is false

### ISSUE THREAD

**Issue by stevenadams** [tinymce/tinymce#4503]
Bug

Inline mode, with toolbar set to false. The toolbar doesn't show but the float panel to house it is still added to the DOM and shows a 1px by 1px square on the screen above the content being edited when in focus.

http://fiddle.tinymce.com/Zwgaab

The float panel for toolbar is not needed

TinyMCE 4.7.11
Chrome 67.0.3396.99 - OSX

**Comment by fyrkant** [comment]
@MichaelFromin That would hide dialog windows as well so not a good idea! I guess we could fix this and not add a panel at all when both toolbar and menubar is set to false, but I think that the idea is that if you want that you should use the inlite theme maybe?

**Comment by MichaelFromin** [comment]
Understood @fyrkant  - was trying to find a workaround until a fix is done.  Perhaps a more targeted CSS selector would do the trick?

**Comment by fyrkant** [comment]
This seems to work:
```css
div.mce-tinymce-inline.mce-panel.mce-floatpanel { display:none; }
```

**Comment by stevenadams** [comment]
@fyrkant - yep put a selector in similar to that got it. Hopefully there will be a proper fix at some point. Thanks everyone for your help so far :)

**Comment by stevenadams** [comment]
@fyrkant do you know if there was ever any progress made on this? we need to use the inline option to keep the editor out of an iframe. we're using a custom toolbar. it seems like it should be an easy enough fix but i guess that depends how busy everyone is.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
