### ISSUE TITLE
aria instructions still announce alt-f9 to access menubar when the menubar is disabled

### ISSUE THREAD

**Issue by mwarner** [tinymce/tinymce#4506]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

for accessibility, TinyMCE announces that the user can hit F9 and be taken to the menu bar.  When there's no menu bar, this causes confusion.  

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

To reproduce it, simply fire up a screen reader and tab or click into an editor with the menu not enabled to hear the announcement.  Here's a demo of no menubar:  http://fiddle.tinymce.com/nxgaab

**What is the expected behavior?**

It would be best if the editor would not announce Alt-F9 when, in fact, that option doesn't work when **menubar:false**.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
latest TinyMCE, all browsers, at least on Windows.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
