### ISSUE TITLE
Chrome and Gboard can't remove image using backspace

### ISSUE THREAD

**Issue by 0xbadc0de** [tinymce/tinymce#4511]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Using backspace won't erase images, just jumps the cursor before image.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Set default keyboard to Gboard. Launch Google Chrome, navigate to [https://www.tiny.cloud/docs/demo/full-featured/](https://www.tiny.cloud/docs/demo/full-featured/). Put cursor at "Welcome" and try to remove word and image above using backspace in the virtual keyboard.

**What is the expected behavior?**
Image should be removed.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Google Chrome (68.0.3440.70) on Android (tested with 5.0.1 and 7.0.0) with Gboard (Google Keyboard)
Used version same as currently at demo page and git version (master branch).

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
