### ISSUE TITLE
Styled text copied from a list item incorrectly pasted as a new list item

### ISSUE THREAD

**Issue by OlivierJaquemet** [tinymce/tinymce#4514]
**Do you want to request a *feature* or report a *bug*?**
a bug

**Reproduce**

1. Copy an unstyled text in a list item,
2. select another text in another item and paste. 
**OK** : the selected text is replaced by the content of the clipboard, (no new list item get created)
3. Now copy a *styled* text in a list item,
2. select another text in another item and paste. 
**KO** : content of the clipboard is inserted as a new item
**Expected behavior** : the selected text should be replaced with the clipboard, without insertion of a new list item.

Reproduced here : 
https://codepen.io/anon/pen/BPxdRR

![item-list-bug](https://user-images.githubusercontent.com/618861/43593255-9d6a9916-9677-11e8-9923-36e70f6bd60a.gif)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE :

- All 4.7.x
- All 4.8.x

Browser (tested on Windows 10)

-  Google Chrome 68.0.3440.84 (64bits)
- 61.0.1 (64-bit)
- Microsoft Edge 42.17134.1.0

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.

**Comment by OlivierJaquemet** [comment]
Tested with TinyMCE 5, this bug does no longer occurs. So it can be closed as *Fixed*
https://codepen.io/olivierjaquemet/pen/LYRLZJm

![2020-12-18_08-53](https://user-images.githubusercontent.com/618861/102588970-962fe180-410e-11eb-8609-f842eb1f92af.gif)
