### ISSUE TITLE
Removal of one format style removes all of them

### ISSUE THREAD

**Issue by alserz1** [tinymce/tinymce#4524]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
Make text bold and italic, remove bold. Italic gets removed along with bold. If you try to apply other styles (underline, strikethrough) they will also get removed.

**What is the expected behavior?**
Italic shouldn't be removed.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Tested on TinyMCE v. 4.8.2-101, Chrome 68, Windows 7.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
