### ISSUE TITLE
Add custom fields on link plugin ?

### ISSUE THREAD

**Issue by ClementGuerin** [tinymce/tinymce#4527]
Hello,

I want to add **custom fields inside link plugin** (these customs fields are textbox, listbox, checkbox, ...), **I don't want to make a plugin** because I want to recover the behavior of the link plugin (detect link, can edit property, class active in toolbar, ...)

With these customs fields I want use them for add class, **I can't just use `link_class_list` because I use multiples fields** not just a listbox.

![capture d ecran 2018-08-13 a 18 01 45](https://user-images.githubusercontent.com/1357503/44043528-5fc2884e-9f23-11e8-96f6-9a5bdd83ae02.png)
 

**Do you know a method to add custom fields to the link plugin?**

Currently I use plugin for that but I really want to just custom the link plugin already existing.

My TinyMCE version : 4.5.7

Thanks in advance.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
