### ISSUE TITLE
Uploading sizable image using safari in macOS won't show in the editor

### ISSUE THREAD

**Issue by sarapng** [tinymce/tinymce#4531]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Uploading image with the size of 300kb and above using safari browser won't load or won't display the image, while same scenario is tested in Chrome and Firefox and didn't encounter the problem.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**Steps to reproduce:**
- Upload image 300kb and above 
- Click ok
- Image didn't display inside the editor

This is not mine but It does behave as stated above. [Link](https://codepen.io/nirajmchauhan/pen/EjQLpV)(credits to the owner)
When checking the Inspect element:
![screen shot 2018-08-17 at 2 46 32 pm](https://user-images.githubusercontent.com/25656865/44251835-76c9d680-a22c-11e8-942d-5df88abc1990.png)

**What is the expected behavior?**
when uploading a sizeable image it will still show inside the editor just like in Firefox and Chrome

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
- TinyMCE: 4.8.1 
- Browser: Safari 11.1.2
- OS: macOS 10.13.6
- Did this work in previous versions of TinyMCE? -> _Not sure_

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
