### ISSUE TITLE
tinyMCE version 4.5.1 in chrome paste image problem

### ISSUE THREAD

**Issue by acrens** [tinymce/tinymce#4532]
Q：Chrome browser paste image only file name，and the image is not pasted？

tinyMCE version：4.5.1

Browser：chrome v68

Thanks！

**Comment by ashickurrahman** [comment]
I am facing the same issue but in different version of chrome. 

Chrome version : 70.1 , OS : Mac OS 10.13.5

fiddle : http://fiddle.tinymce.com/U7gaab

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
