### ISSUE TITLE
Issue with nested tables in IE

### ISSUE THREAD

**Issue by michaelberres** [tinymce/tinymce#4536]
**Do you want to request a *feature* or report a *bug*?**
Report a bug that occurs only in IE.

**What is the current behavior?**
Create a table and within this table another one. Enter any text into the inner table. Afterwards, it is not longer possible to set the cursor into the outer table. No matter if you click in front of the inner table or behind it, the cursor is always set into the inner table.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/Oygaab/1

**What is the expected behavior?**
The cursor should be place into the outer table so that the user can enter text there next to the inner table.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
This issue occurs only in Internet Explorer. In Firefox as well as Chrome, everything works fine.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
