### ISSUE TITLE
Missing lightgray skin of modern theme for skin creator (default theme of TinyMCE)

### ISSUE THREAD

**Issue by rjgamer** [tinymce/tinymce#4538]
**Do you want to request a *feature* or report a *bug*?**
Feature request, maybe bug

**What is the current behavior?**
I'm missing the default lightgray skin of the modern theme for the skin creator (http://skin.tinymce.com/). The current lightgray skin on the skin creator page is more gray than white.

**What is the expected behavior?**
It would be nice the get the current default skin of TinyMCE for the skin creator too.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
4.x

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
