### ISSUE TITLE
Problem with formatting text

### ISSUE THREAD

**Issue by vbarzilovich** [tinymce/tinymce#4539]
I noticed a problem with formatting text.

This problem can sen, when text contains italics style in bold style, for example:

**This is the text line for problem visualization**

HTML:
`<p><strong>This is the text <em>line</em> for problem visualization</strong></p>`

If you select the word for and remove bold style from it, then the editor will remove the space to the left of for and the line will look like this (**linefor** without space):

**This is the text linefor problem visualization**

HTML:
`<p><strong>This is the text <em>line</em></strong>for <strong>problem visualization</strong></p>`

You can test formatting in a text editor on the site https://www.tiny.cloud/

**Comment by vbarzilovich** [comment]
I have a solution to the problem.

How can I make changes to `tinymce.js`?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
