### ISSUE TITLE
RichTextFields: Paste from Word removes white-space characters in Chrome and Firefox

### ISSUE THREAD

**Issue by haseenaa** [tinymce/tinymce#4540]
The Paste from Word function that was added to RTFs (TinyMCE) in 2016 only operates correctly in IE browsers.  Users of Chrome (widely used), Firefox, and also Edge can experience that blanks between words are removed thereby concatenating words that should remain separate

21Tips to Become the Most Productive Person You Know
#1.Check email in the afternoon so you protect the peak energy hours of **yourmornings** for your best work.
#2.Stop waiting for perfect conditions to launch a great project. Immediate **actionfuels** a positive feedback loop that drives even more action.
#3.Remember that big, brave goals release energy. So set them clearly and **thenrevisit** them every morning for 5 minutes.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
