### ISSUE TITLE
document_base_url does not work in conjunction with inline: true

### ISSUE THREAD

**Issue by jm9e** [tinymce/tinymce#4541]
These settings work as expected:
```JavaScript
tinyMceInit: {
  relative_urls: false,
  remove_script_host: true,
  document_base_url: 'https://example.com/',
  inline: false
}
```

Here however, images are not displayed with absolute URLs when using `inline: true`:
```JavaScript
tinyMceInit: {
  relative_urls: false,
  remove_script_host: true,
  document_base_url: 'https://example.com/',
  inline: true
}
```

Our assumption is that there is no `iframe` used with `inline: true` and `document_base_url` uses a `base` tag in the head section which is not present if there is no `iframe`.

If this is expected behavior I would expect it to be documented.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
