### ISSUE TITLE
When a web address is linked anything that is typed after the address will be considered a link

### ISSUE THREAD

**Issue by Anderson-Vasques** [tinymce/tinymce#4544]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When a web address is linked anything that is typed after the address will be considered a link

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Access [http://fiddle.tinymce.com/mzgaab](http://fiddle.tinymce.com/mzgaab)

1. Type `something`.
2. Select the word.
3. Click on `Insert/Edit link` icon.
4. Provide a valid link and click `OK`.
5. Go to the end of the word pressing the Right Arrow button once, or clicking at the end.
6. Press space and type any word.

Note that the new word is considered a link.

**What is the expected behavior?**
When user press the space button the link tag should be closed. The new word should not be a link, it should be a simple text.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
It works in the 4.5.9 version
I does not work in:
4.6.3 and later

I am using Chrome Version 68.0.3440.106 (Official Build) (64-bit) in a MacBook Pro HighSierra 10.13.6

**Comment by petko** [comment]
I want to give my vote for this proposal too. Typing space after a link is treated as an end of a link in most popular apps like Ms Word and Google Docs, so this is the expected behavior by most users.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
