### ISSUE TITLE
FIREFOX Issue - Editor window iframe jumps to start of content on style change

### ISSUE THREAD

**Issue by haloween** [tinymce/tinymce#4548]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
When i change style of h2 to p or p to h2 editor window jumps to the beginning of content.
https://youtu.be/j3p4djLKvuc

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Demo here: https://youtu.be/j3p4djLKvuc

Happens only in In FIREFOX - Your content must be long, then click on a paragraph and change it to h2 or other style. 

**What is the expected behavior?**
Chrome behavior is proper https://youtu.be/A4lLl4m8ulE - editor window is not skipping.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE 4.8.2, Firefox 61.0.2 , Windows 10 Pro x64

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
