### ISSUE TITLE
Portrait Camera images taken from tinymce are getting rotated by 90 degrees.

### ISSUE THREAD

**Issue by gauravsharma4471** [tinymce/tinymce#4551]
**Do you want to request a *feature* or report a *bug*?**
this is a bug

**What is the current behavior?**
image from camera roll is rotated by -90 degrees. I am taking the base64 string of the image and generating a HTML report. 
This is only happening if we are using camera or browsing to a picture taken by the camera.
We are working on hybrid application where we have integrated tinymce editor

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1) Take a image from iphone
2) open tinymce editor
3) click on camera icon and browse photo
4) add to tinymce the latest photo which has been taken

*Check the base64 string of the image which is taken and add to a another html and see the output - Image is rotated.

Actual Image - 
![image](https://user-images.githubusercontent.com/20062995/45086045-e80bf380-b11f-11e8-89db-ffbca669e6b2.png)

Image generated by base64 string by tinymce -

![image](https://user-images.githubusercontent.com/20062995/45086112-138ede00-b120-11e8-92e4-ea62bda5e4da.png)

**What is the expected behavior?**
Image should hold the correct orientation 

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

current version of tinymce is 4.7.12

**Comment by sprasad02** [comment]
Currently, I am also facing the same issue. Anything helpful would be really appreciated.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
