### ISSUE TITLE
Bullets and numbering not filtering while pasting as text

### ISSUE THREAD

**Issue by ramvenkat82** [tinymce/tinymce#4552]
**Do you want to request a *feature* or report a *bug*?**
I am using paste plugin. When i paste bullets/numbering from word, its not getting removed and retains.
**What is the current behavior?**
I could see the styles are filtered but the bullets/numbering not getting filtered.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**
Bullets/numbering has to be filtered.
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I am using version 4.6.5

Here is my code

plugins: paste,
paste_as_text: true,
paste_remove_styles_if_webkit: true,
paste_enable_default_filters : true,
paste_block_drop : false,
paste_retain_style_properties : "none",
paste_strip_class_attributes : "all",
paste_remove_spans : true,
cleanup_on_startup : true,
fix_list_elements : false,
fix_nesting : false,
fix_table_elements : false,
paste_use_dialog : true,
paste_auto_cleanup_on_paste : true,

**Comment by ramvenkat82** [comment]
Can anyone suggest me whats going wrong. I have removed all configurations and just have one as below
plugins: paste,
paste_as_text: true,

Whatever i am pasting from word, the styles are removed and pasting as text (which is what i need). The bullets or numbered lists for which the styles are removed when paste but the bullets and numbers are getting pasted. I want the bullets also to be removed while pasting or paste with style so that it will its appropriate tool bar is selected.

**Comment by ramvenkat82** [comment]
Just now i verified in IE. I could see the bullets and numbering are removed while pasting from word. Facing issue in Chrome and Firefox. Is this a bugwith the plugin ? Do we have workaround for resolving in chrome and firefox

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
