### ISSUE TITLE
Speed of keystrokes change the output in regards to &nbsp;

### ISSUE THREAD

**Issue by Schleuse** [tinymce/tinymce#4554]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

* When I enter a sequence of a characters and spaces in quick succession the output does not contain &amp;nbsp; but normal spaces. (a a a a)
* When I enter a character followed by a space, then wait a bit and continue with this sequence the output contains only &amp;nbsp; and no normal "space" (a&amp;nbsp;a&amp;nbsp;a&amp;nbsp;a)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/Qzgaab

**What is the expected behavior?**

I expect the same output regardless of the speed I enter the characters

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

I've only recently noticed this by enabling the visualchars plugin. However the content is different regardless of activating the visualchars plugin. The earliest version I've noticed this is 4.6, the latest 4.8.2. The last version where I could't see the described behaviour was 4.5.9

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
