### ISSUE TITLE
Table attributes border, cellpadding, cellspacing do not update

### ISSUE THREAD

**Issue by alexmaris** [tinymce/tinymce#4555]
**Do you want to request a *feature* or report a *bug*?**
BUG

Table attributes border, cellpadding, cellspacing do not update when option is `table_style_by_css` enabled

**What is the current behavior?**
Configure any version of TinyMCE (for example the edge on this day) with the table plugin properly configured and the `table_style_by_css` property set to `true`

1. Create a table and open the *Table Properties* dialog for it
2. Set a value of `3` in the *Border* input box
3. Click OK
4. View source code
The table's `border` attribute maintains its original value instead of the new value `3`

**What is the expected behavior?**

Configure any version of TinyMCE (for example the edge on this day) with the table plugin properly configured and the `table_style_by_css` property set to `true`

1. Create a table and open the *Table Properties* dialog for it
2. Set a value of `3` in the *Border* input box
3. Click OK
4. View source code

The table's `border` attribute has the new value `3`

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Tested on v4.8.1 on Mac/Chrome 67.0.3396.99

**Comment by blackcathikari** [comment]
Thanks for the report! I believe this has been fixed in the latest versions of both TinyMCE 4 and 5, in which case we will close this ticket soon. If you're still able to replicate it in 4.9.5 or 5.x, could you please let us know so we can investigate this further.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
