### ISSUE TITLE
Cannot drag and drop image inside the editor if it's aligned left (IE11)

### ISSUE THREAD

**Issue by mlachgar** [tinymce/tinymce#4558]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
On IE11  cannot drag and drop image inside the editor if it's aligned left (<img align="left"> or style float: left). It works on Chrome or on IE11 if the image is aligned right.

**What is the expected behavior?**
The image should ne drag and dropped inside the editor regardless of its alignment 

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE v4.8.2 and earlier on IE11
Fiddle link : http://fiddle.tinymce.com/i0gaab/1

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
