### ISSUE TITLE
Bug: Mobile theme top position cover toolbar

### ISSUE THREAD

**Issue by iyasilias** [tinymce/tinymce#4560]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug.

**What is the current behavior?**
on iOS: 
![whatsapp image 2018-09-12 at 9 57 01 am](https://user-images.githubusercontent.com/634151/45397372-4bdb7280-b672-11e8-895a-803613bf68c8.jpeg)
on Android: OK

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
```
<editor formControlName="content" [init]="{theme: 'mobile',
              mobile: {
                theme: 'mobile',
                toolbar: [ 'undo', 'bold', 'italic', 'styleselect' ]
              }}" class="editor"></editor>
```

**What is the expected behavior?**
The button should not cover the top.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I'm using "tinymce": "^4.8.2", "@tinymce/tinymce-angular": "^2.0.1"

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
