### ISSUE TITLE
when page scroll, that dropdown lists all absolute a position

### ISSUE THREAD

**Issue by fairyly** [tinymce/tinymce#4564]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
- 1.first click menu , show that dropdown,
- 2.now when page scroll, that dropdown contents all absolute a position, like fixed that position,
     it won't stick to the toolbar

![861cc5cf-7e2d-4253-8fbc-b49e873050ef](https://user-images.githubusercontent.com/17672815/45620418-703eb100-baaf-11e8-8e40-847a9ed4b362.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**

TinyMCE version : 4.8.0
OS : Windows 10
Browser : Chrome version 69.0.3497.92(64 bits)

like: [#3592](https://github.com/tinymce/tinymce/issues/3592)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
