### ISSUE TITLE
More complex sidebar example

### ISSUE THREAD

**Issue by Misiu** [tinymce/tinymce#4569]
**Do you want to request a *feature* or report a *bug*?**
feature

I'm trying to create a custom sidebar that will allow me to add variables in TinyMCE. My idea is to allow users to edit templates that are used by system to generate emails and notifications.

I found [plugin](https://github.com/ambassify/tinymce-variable) that does what I want, but it isn't actively developed, so I want to create something similar but with the features I need.

[Current sidebar example](https://www.tiny.cloud/docs/advanced/creating-a-sidebar/) is very simple, it shows how to put simple text in the sidebar. Maybe You could add a couple of buttons to that panel and show how to interact with content.

I'm also unsure where I should create content of my sidebar. The example shows that it should be done in `onshow`, but shouldn't it be in `onrender`?

**Comment by Afraithe** [comment]
Hi Misiu,

Yes the sidebar examples are very simple, in fact we don't even plugins utilizing it, YET. We had some big plans for the sidebar, but there are some issues like what happens to it in inline mode or similar. We kind of have to take another pass at the sidebar, its api etc.

For now, I think the best approach to what you want to do, is creating a html page containing what you want in the sidebar, and load that entire page in via the api.element() then for inserting stuff, use normal tinymce api's.

**Comment by Shazer2** [comment]
Hi @Afraithe,

Is there any progress on this? I'm hoping to implement some more complex functionality into the sidebar such as being able to make it resizable horizontally for the user? Is there any current method on achieving this?

**Comment by TheSpyder** [comment]
We've started using the sidebar ourselves now, most notably in our [premium commenting plugin](https://www.tiny.cloud/docs/enterprise/tiny-comments/), but it still isn't resizable.

**Comment by Shazer2** [comment]
@TheSpyder interesting example! Do you have any lead on how I might go about implementing resizing? Maybe it can be achieved through CSS?

**Comment by TheSpyder** [comment]
@Shazer2 unfortunately the only techniques I know of to dynamically resize elements on a webpage involve code, which would need a core editor change, not just CSS.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
