### ISSUE TITLE
insert row/column below/above duplicates HTML markup of cells

### ISSUE THREAD

**Issue by msclp** [tinymce/tinymce#4571]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Inserting row/cell below/after duplicates some of HTML markup from cell that belongs to selected row/column

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Create a table, insert div and inside this div write some text, select the filled cell and click insert row (below or after -  it does not matter).
Inside this newly created row in the same column, the HTML markup is duplicated (without content).

**What is the expected behavior?**
Should insert empty cells

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE version: 4.7.11
browser: Google Chrome Version 69.0.3497.92 (Official Build) (64-bit)
OS: macOS 10.13.6

I found that this bug occurred previously
https://github.com/tinymce/tinymce/issues/1449

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
