### ISSUE TITLE
Failure message not trigger on tinymce mobile theme

### ISSUE THREAD

**Issue by ardyfeb** [tinymce/tinymce#4574]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The failure message when uploading file not trigger, and the image keep attached

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

My code :  
```
imageUploadHandler = (blobInfo, success, failure) => {
        const files = blobInfo.blob()
               
        const fd = new FormData()
        fd.append('file', files)
        
        let $this = this;
        
        axios.post(API.file.upload, fd, {
            headers: {
                'Authorization': Cookies.get('token')
            }
        })
        .then(response => {
            success(response.data.data.url)
        })
        .catch(error => {
            failure(error.response.data.message)        
        })

    }
```

**What is the expected behavior?**
Throw failure message when the uploading failed

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
All android browser / no

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
