### ISSUE TITLE
Bug: Contextmenu with "autoresize" false position

### ISSUE THREAD

**Issue by eweso** [tinymce/tinymce#4576]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
When the content section, the wrapper of the iframe (".mce-edit-area"), has a fixed height and is "overflow-y: scroll" and I use the autoresize plugin to resize the iframe dynamically (without, you cannot scroll when using ios devices, because they cannot scoll inside iframe), then the contextmenu appears on the false position, when I scrolled inside that content section.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/Z0gaab/1

**What is the expected behavior?**
The contextmenu should be appended to ".mce-edit-area", so it's easier to determine the correct position. At the moment it is a direct child of ".mce-stack-layout", which is a direct child of the main wrapper. So my expected behavior is, that the conext menu should appear there, where I clicked.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

4.8.3 / Win 10 / Opera
No, did not work on previous versions, too.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
