### ISSUE TITLE
Output file content.inline.min.css includes a rule for .word-wrap

### ISSUE THREAD

**Issue by RandScullard** [tinymce/tinymce#4577]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The output file content.inline.min.css includes a rule for .word-wrap.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Just open the file skins\lightgray\content.inline.min.css and take a look at the first rule, which is .word-wrap.

 This seems to be happening because the definition of the .word-wrap mixin in Mixins.less is missing the parentheses. This looks like a mistake, because .word-wrap is only referenced as a mixin, and all of the other definitions in Mixins.less have parentheses.

**What is the expected behavior?**
There should be no style rule for .word-wrap in the final output.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
4.8.2

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
