### ISSUE TITLE
There's no such thing as Iberian Portuguese

### ISSUE THREAD

**Issue by antoniogoulao** [tinymce/tinymce#4578]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The spell check drop-down contains the following entry "Iberian Portuguese"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**
Just: Portuguese

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
All

**Comment by lnewson** [comment]
Hi,

It appears as though we've fixed this since you've logged this issue, as I'm unable to find that string in either our community or premium spellchecker plugins. Thanks for letting us know about this and since it's been fixed I'm going to go ahead and close this. Please do let us know if you're able to still find this though and we'll reopen this issue.

Thanks!
