### ISSUE TITLE
Paste plugin prevents dropping or moving images in newer Safari

### ISSUE THREAD

**Issue by aflin** [tinymce/tinymce#4582]
When paste plugin is loaded and an image is dropped from content dragged from another open window, safari (my version is 11.1.2) includes in its e.dataTransfer object dataTransfer.files.length > 0.  Chrome does not.

On line 1261 of the "paste/plugin.js" file is
```
var dataTransfer = e.dataTransfer;
if (dataTransfer && dataTransfer.files && dataTransfer.files.length > 0) {
    e.preventDefault();
}
```

In Chrome, the paste is not prevented, in Safari 11 it is. Thus the dropped image is not inserted into the editor.  This does not appear to happen in Safari 10.

There is another possibly related issue where images already in the editor cannot be moved.

You can see both these issues at https://codepen.io/tinymce/pen/NGegZK and when you replace "powerpaste" with "paste" in the "plugins:" string.

**Comment by manu37** [comment]
same occurs with (FF 64.0.2 (64-Bit))

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
