### ISSUE TITLE
Custom Element removed unexpectedly

### ISSUE THREAD

**Issue by gkubisa** [tinymce/tinymce#4584]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

Pressing Backspace when the caret is at the start of a paragraph following a "block" Custom Element removes the Custom Element.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Go to http://fiddle.tinymce.com/i1gaab
2. Place the caret at the start of Paragraph 2
3. Press Backspace

**What is the expected behavior?**

Pressing Backspace when the caret is at the start of a paragraph following a "block" Custom Element should move the caret to a position after the Custom Element and not remove the Custom Element. The paragraph should be removed, if it's empty. This is the behaviour we get, if we press Backspace at the start of a paragraph followed by a Code Sample.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

- TinyMCE 4.8.3
- Chrome 69.0.3497.100 (Official Build) (64-bit)
- Ubuntu 16.04 64 bit

**Comment by gkubisa** [comment]
It works fine when the cursor is on the left or right of the custom element. The problem is when the cursor is at the beginning of a paragraph, which is just below the custom element. The behaviour is certainly inconsistent with the handling of the code sample plugin.

Perhaps the issue would be more obvious, if the Paragraph 2 (in the fiddle) was empty. With the cursor in that empty paragraph, pressing Backspace should remove only that paragraph, however, TinyMCE removes both the empty paragraph and the custom element which is just above that paragraph. For comparison, the behaviour is correct, if the cursor is in an empty paragraph after a code sample - Backspace removes only the paragraph and the cursor appears after the code sample.

**Comment by Lewiscowles1986** [comment]
I think what is happening is that you're observing an edge case with paragraphs & text-tags, because they are compatible and can collapse.

I'll agree it can be confusing and I'm in no position to make decisions on behalf of this repo, but from a HTML standpoint it makes sense that you're deleting the end of a paragraph, merging paragraphs is a strategy for resolving.

In the example where you press backspace from one paragraph to the next there is not a line-feed character being deleted. It seems to be deleting the </p> and opening <p> tags.

To see this I'm watching in inspector (right-click "Inspect Element (Q)" in my FF).

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
