### ISSUE TITLE
Caret does not move when pressing the UP arrow

### ISSUE THREAD

**Issue by gkubisa** [tinymce/tinymce#4585]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

The caret does not move to a paragraph above an embedded iframe (inserted using the "media" plugin) on pressing the Up arrow, if the caret is initially right after the iframe.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Go to http://fiddle.tinymce.com/k1gaab/1
2. Place the caret right after the iframe containing the video.
3. Press the Up arrow on the keyboard.

**What is the expected behavior?**

The caret should move to the paragraph above.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE 4.8.3
Ubuntu 16.04 64bit
Chrome 69.0.3497.100 (Official Build) (64-bit)

**Comment by Lewiscowles1986** [comment]
TinyMCE 4.8.3
Ubuntu 18.04 64bit
Firefox 
![screenshot from 2018-10-01 19-01-07](https://user-images.githubusercontent.com/2605791/46306517-64bdb080-c5ac-11e8-949b-ce240e32f727.png)

**Comment by gkubisa** [comment]
I can reproduce in Firefox 62, Ubuntu 16.04, TinyMCE 4.8.3.

The caret stays in the same position when I press the Up arrow.

![screenshot 2018-10-01 20 49 17](https://user-images.githubusercontent.com/1692672/46309129-c46f8800-c5bb-11e8-83f9-c82d6752c1ed.png)

**Comment by androb** [comment]
This might be Ubuntu specific. Cannot replicate on Chrome 69 & Mac OS 10.14

**Comment by lnewson** [comment]
I managed to reproduce this using Firefox 62 and Chrome 69, on Fedora 28 and Win 10. Looking into the issue, it appears as though the logic that finds the previous line is instead always finding the iframe that's on the same line, which in turn causes the caret to never be able to move up a line.

Another way that I think is a bit easier to replicate, is to add some text after the iframe, then put the caret at the end of the line and then press up. What happens then, is instead of the caret moving up a line it moves to just before the iframe content. Here's a slightly altered fiddle: http://fiddle.tinymce.com/l2gaab/1

One thing I should note from my findings, is that if you put the caret on the bottom line (Paragraph 2) and then press up it does correctly move up (assuming you don't move the cursor to the right of the iframe boundary).

Another interesting find, is that if you shrink the iframe to say 20px in height then the cursor does currently move up to the top line. As such I wonder if this may have something to do with the  `ClientRect.isAbove` function [1] or potentially the `moveV` function [2] making use of that `isAbove` function?

[1] https://github.com/tinymce/tinymce/blob/4.8.3/src/core/main/ts/geom/ClientRect.ts#L65
[2] https://github.com/tinymce/tinymce/blob/4.8.3/src/core/main/ts/keyboard/CefNavigation.ts#L216

**Comment by lnewson** [comment]
This issue has been fixed in TinyMCE 5.5.0, which was released to the community earlier today. Thanks again for reporting this and please let us know if you have any further issues.
