### ISSUE TITLE
Toolbar Position doesn't refresh in mode inline

### ISSUE THREAD

**Issue by jaschaio** [tinymce/tinymce#4586]
When I set tinymce to inline mode the toolbar doesn't updates its position if the editor element changes it size:

![tinymce](https://user-images.githubusercontent.com/11058666/46307555-85d7ce80-c5b7-11e8-8435-0ff3e859e1c0.gif)

Only if I refocus the element or create a manual line break with `shift + enter` the toolbar repositions itself correctly. I couldn't find a method to rerender the toolbar / ui within the docs but maybe somebody has an idea how to solve this.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.

**Comment by jaschaio** [comment]
For anyone looking for this in the future: It appears working correctly now: https://codepen.io/jaschaio/pen/gOwRWzX
