### ISSUE TITLE
TinyMCE 5 Preview: Font size drop-down could be narrower

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce#4595]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The Font Size drop-down takes up more toolbar real estate than it needs to.

![image](https://user-images.githubusercontent.com/2160304/46488418-72935180-c7b7-11e8-87e8-fef4941f1e1c.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
https://codepen.io/tinymce/pen/79ec454375d41f576b3a9f687994570b?editors=0010

**What is the expected behavior?**
It only takes up the space it needs. (60px?)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
V5 dev preview

**Comment by TheSpyder** [comment]
There's a fixed width of `7em` on the buttons to account for the way the text might change as the cursor moves. I think this was a temporary patch for the dev preview, ideally we would measure the menu size and use that up to a _maximum_ of `7em`.

**Comment by Paradoxon101** [comment]
Is there a workaround for this?

**Comment by lostkeys** [comment]
@TheSpyder. The challenge with measuring the menu is that TinyMCE will display any inline font-size declaration it will find on the selected element, even if it's not in the original menu.

That said I could also argue that it would be fine if we calculated the max width of the defined font-size menu and truncate any long ad-hoc values that might exist. Since the identigying information is in the beginning of the string, it still has meaning even with pretty agressive truncation, such as ’xxx-la’ or ’xx-sma’.

We could also reword the values too, so that `xxx-large` would become `xxx-lg`.
