### ISSUE TITLE
V5.0.0 p1-b.6 No fixed_toolbar_container?

### ISSUE THREAD

**Issue by Georg-Git** [tinymce/tinymce#4598]
See option fixed_toolbar_container:
https://www.tiny.cloud/docs/configure/editor-appearance/#fixed_toolbar_container

Using this option in Preview1-build.6 it does not work.

**Comment by Georg-Git** [comment]
But it is noted in preview documentation:
https://www.tiny.cloud/docs-preview/configure/editor-appearance/#fixed_toolbar_container

In my use case I use Tiny like in Word, dynamical loading and editing a long text.
The Tiny Menue is the first item displayed in a browser fixed on top of a long text.
In every case the hight of the text document is higher as height of the browser display.
So in every case there will be a slider on the right side, but the tiny menu must stay on top of the display.

At first place the classic mode of tiny seems to be the perfect solution for this kind of use case.
But classic mode of tiny is using an iframe.

And an iframe in a Safari iOS browser is handled different to all the other browsers:
The hight of the iframe can't be fixed and is always extended to the height of the document.
So - while sliding a long text to the bottom the tiny menu will disappear to the top.

That was the main point for me to switch to the inline mode of tiny together with option fixed_toolbar_container.
In inline mode I can use Tiny like in classic mode without the disadvantages of a iframe.

And with fixed_toolbar_container even with different menue items and changing width of the viewport, the height of the toolbar is adopted to tinys menue height. 
Now I have to take into acount the different height of tiny and must care about the margin above the text document to ensure full display of both: the head of the text document and the full tiny menu....

**Comment by TheSpyder** [comment]
Yes, the documentation is still in progress. It's one reason we called it a developer preview and not a beta.

Our plan is to offer something similar to the "sticky toolbar" feature of our other editor:
https://jsfiddle.net/npbdLsk0/

I don't know if it will be done in time for the 5.0 release, but this sounds like it would resolve your first issue. Is that right?

I'm curious to hear more about how you're using the editor in Safari on iOS. We have a [mobile theme](https://www.tiny.cloud/docs/mobile/) in version 4 designed to provide a proper mobile editing experience, and currently the plan for TinyMCE 5  is to include the mobile theme by default. This might preclude the things you're doing to make the editor usable today.

**Comment by Georg-Git** [comment]
The other advantage of Tiny inline mode is the use of the main css style of the main document.
Tiny mobile theme still based on a iFrame - but "sticky toolbar" feature would be a solution.

**Comment by mdgbayly** [comment]
@TheSpyder We also make use of the fixed_toolbar_container on our project so that we can more precisely control the location and styling of the toolbar.  

Can you clarify in what ways you have `improved the way the inline toolbar works in version 5`. 

I tried looking at the inline demos under the developer preview but it seemed a bit buggy.
https://www.tiny.cloud/docs-preview/demo/inline/

Thanks

**Comment by TheSpyder** [comment]
Ah, so you haven't used a "fixed" container but one with similar behaviour that you exert more control over? Very interesting.

Yes, inline has become a bit buggy since we released the first dev preview (and some of the issues on that page are related to API changes not yet reflected in the docs). It should improve with our first beta planned for the end of the month.

The team working on TinyMCE 5 has previously worked on textbox.io where the inline toolbar has a few advantages. Off the top of my head, two big advantages over v4 are are that it constantly sticks to the top of the browser window (it never jumps around) and it fades out once the targeted element has scrolled off screen.
https://jsfiddle.net/textboxio/1mq3wxqh

We won't have all of the same features in v5 at launch, but the underlying technology has been rebuilt to be more flexible so that they can be. `fixed_editor_container` hasn't been implemented for the new structure. I'm happy to pass these use cases along to the product manager to consider bringing it back.

**Comment by blackcathikari** [comment]
Hi @Georg-Git and @mdgbayly,

Now that we've released RC1 and TinyMCE 5 has become more stable, we were wondering if you had any updates regarding this? In particular, have you looked at the improvements to [inline](https://www.tiny.cloud/docs-beta/demo/inline/) and the [Quick Toolbar plugin](https://www.tiny.cloud/docs-beta/plugins/quickbars/) and do either of those help solve your use cases?

**Comment by mdgbayly** [comment]
I'll try and take another look sometime, but at this point it looks like we may move away from our usage of the fixed toolbar container anyway. We're working on getting tinymce to work in shadow dom environments and by allowing tinymce to create the toolbar in the main document it works around some shadow dom issues.  Also allowing the toolbar to be dynamically repositioned as the page scrolls works better for us in some of our usages.

**Comment by blackcathikari** [comment]
Thank you for the update @mdgbayly! Sounds like TinyMCE 5 is working out well for you then. Let us know if you have any further concerns or questions!

**Comment by monnb** [comment]
Disappointed to learn that you guys are taking away flexibility in toolbar positioning.

Here's a couple of example of places we use TinyMCE with `fixed_toolbar_container` at the moment.

![tiny-mce-toolbar](https://user-images.githubusercontent.com/2154809/51652199-e9f92500-1fe2-11e9-8964-50803d10df85.png)

If it's not added back we'll likely just stay with V4. Happy to share more details on our use case if it will help.

**Comment by TheSpyder** [comment]
The setting was left off of the requirements list when we built the new UI and we won't have an equivalent solution for the release next month. That doesn't mean it can't be built later, which is why we have left this issue open. We will also be supporting v4 for quite a while yet.

We are very open to hearing about use cases and documenting different ways the editor is used - @androb in particular may be very interested in that gmail-looking interface of your first example.

**Comment by Afraithe** [comment]
Hey Monnb, we are planning in to re-implement this within a release or two, stay tuned..

**Comment by dmitry-kostin** [comment]
Thank the gods they received our message

**Comment by lnewson** [comment]
This is now back in 5.0.2, which has just been released for community. Please let us know if you find any further problems!

**Comment by Georg-Git** [comment]
[5.0.2] fixed_toolbar_container is back - now Tiny 5x is useable for me - thanks!

Only for the records:
Behavior of tiny inside Your fiddle setup on tinymce.com is still different to real live environment.
E.g. height of div selector container is overrided:

http://fiddle.tinymce.com/FCgaab/3

**Comment by blmcc-eph** [comment]
hey @Georg-Git -- Congratulations!  This issue has been selected as one of the three most helpful issues in our TinyMCE 5 Developer Challenge.  Please contact me at blake [at] tiny [dot] cloud so we can get you your gift card.  And on behalf of everyone at Tiny, thanks for your support of TinyMCE 5.
