### ISSUE TITLE
Editor bug

### ISSUE THREAD

**Issue by matteoresconi** [tinymce/tinymce#4601]
Hi everyone, I have a problem with the tinyMCE editor.
I have an HTML code made of tables and descriptions. If I write the description before the tables with the "p" tag, when the editor loads it goes into an infinite loop, but if I remove the description with the "p" tag or I replace it with an "h1" tag, the problem disappears.
Why this happen?

[proof-of-concept-2.zip](https://github.com/tinymce/tinymce/files/2454964/proof-of-concept-2.zip)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
