### ISSUE TITLE
tiny_mce issue

### ISSUE THREAD

**Issue by damkondwarpravin** [tinymce/tinymce#4605]
The application's function method receives and dynamically executes user-controlled code using onBeforeUnload, at line 7143 of /tiny_mce/tiny_mce.js. This could enable an attacker to inject and run arbitrary code.
The attacker can inject the malicious payload into the victim's browser, via external input replace. This is read by the browser in the function method, at line 7143 of /tiny_mce/tiny_mce.js. The browser then executes this code itself.

The application's function method receives and dynamically executes user-controlled code using onBeforeUnload, at line 8847 of /tiny_mce/tiny_mce_src.js. This could enable an attacker to inject and run arbitrary code. 
The attacker can inject the malicious payload into the victim's browser, via external input replace. This is read
by the browser in the function method, at line 8847 of /tiny_mce/tiny_mce_src.js. The browser then executes this code itself.

**Comment by TheSpyder** [comment]
Sorry, but copy/pasting a section of a security report into an issue doesn't help anyone. Which version of TinyMCE? Which plugins?

I can't find anything matching that function name in the code, so I can only assume it's an older editor issue  that has since been fixed or the issue is in a custom plugin bundled with that copy of the editor.

If you can provide more details we'll reopen and investigate.
