### ISSUE TITLE
Colorpicker handles stuck at bottom when floating panels are inside relative container

### ISSUE THREAD

**Issue by aprat84** [tinymce/tinymce#4637]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When an editor inserts colorpicker floating panel inside a relative/absolute/fixed container, via default behavior (body) or via ui_container configuration option, color intensity and hue handles are stuck at the bottom, when editor has been scrolled down.
Better see the fiddle.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/62gaab/1

**What is the expected behavior?**
Handles should not be stuck.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Tested in 4.6.4, 4.8.3 and latest.
Tested in Chrome 70.0.3538.67 (64-bit) and Firefox 62.0.3 (64-bit)

**Comment by fyrkant** [comment]
This seems like an edge case to me, maybe you can avoid putting position relative on the body element and wrap the content in a div with position style on it instead? Also, this seems to be fixed in the upcoming TinyMCE 5 so if you wait for that release it will solve the problem.

**Comment by aprat84** [comment]
There's no workaround, believe me, I've tried.

In my case I have an editor in a fixed positioned "popup". This is something I can't change.

The only workaround is to not use custom color picker, and resign ourselves to the 8x5 color grid.
Also, I had to set the undocumented `ui_container` option for the other floating panels to be positioned correctly (table menu, context menu, etc.).

I guess I'll have to wait for the v5.

**Comment by ajtruckle** [comment]
I have the same issue, although if I make the editor full screen it behaves somewhat better. Is it OK in v5?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
