### ISSUE TITLE
Cursor moves to a paragraph above on Enter instead of staying before a code sample

### ISSUE THREAD

**Issue by gkubisa** [tinymce/tinymce#4647]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

A new paragraph is created above the cursor and the cursor moves to that new paragraph instead of staying before the code sample.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/G2gaab

1. Put caret before a code sample
2. Press Enter

**What is the expected behavior?**

A new paragraph is created and the cursor remains just before the code sample.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE 4.8.4
Chrome 70.0.3538.67 (Official Build) (64-bit)
Ubuntu 16.04

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
