### ISSUE TITLE
Applying custom format causes issues

### ISSUE THREAD

**Issue by shaedrich** [tinymce/tinymce#4653]
**Do you want to request a *feature* or report a *bug*?**

A bug.

**What is the current behavior?**

When I register a format containing a space via `tinymce.activeEditor.formatter.register()`, everything works fine. But if I want to check it via `tinymce.activeEditor.formatter.canApply()` it throws the following exception:

> t.toLowerCase is not a function

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

When I reproduced the bug via fiddle.tinymce.com the line where the exception happened was `tinymce.activeEditor.formatter.apply()`

http://fiddle.tinymce.com/j2gaab

**What is the expected behavior?**
It should work as well as if I passed a string directly to `apply()` or at least throw a descriptive eeception.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I never tried this in any previous version.

|                        |                                                     |
| -                     |-                                                    |
| **TinyMCE** | v4.8.3 and v4.8.5 (fiddle)          |
| **browser**  | Google Chrome v70.0.3538.77 |
| **OS**           | MacOS v10.13.6                         |

**Comment by shaedrich** [comment]
Yes, that would be great. Additionally to that the docs should also include the [format parameters table](https://www.tiny.cloud/docs/configure/content-formatting/#formatparameters) on [formatter page](https://www.tiny.cloud/docs/api/tinymce/tinymce.formatter/#) and have columns explaining which one is required and which one is optional.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
