### ISSUE TITLE
Pasting images using Ctrl+V not working in Edge

### ISSUE THREAD

**Issue by gkubisa** [tinymce/tinymce#4658]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

Pasting images using CTRL+V does not work in Edge.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Open an image in an image editor, eg Paint.
2. Ctrl+A
3. Ctrl+C
4. Focus the editor at http://fiddle.tinymce.com/r3gaab/2
5. Ctrl+V

**What is the expected behavior?**

The image should be pasted into the editor.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE 4.8.5
Microsoft Edge 41.16299.726.0 (Microsoft EdgeHTML 16.16299)
Windows 10

It works fine in IE11, Chrome and Firefox.

**Comment by lnewson** [comment]
This issue appears to be with specific applications (eg paint), as if you go to say https://www.google.com/logos/google.jpg from a browser and copy/paste the image then it does work.

**Comment by gkubisa** [comment]
Yes, pasting using the context menu works fine - only Ctrl+V does not work.

Re the source application... it seems that the paste fails, if there's actual image data in the clipboard, rather than some html containing an image tag with an image URL. I suspect that the issue would be reproducible, if you copy from any image editor.

**Comment by Aetherus** [comment]
The problem only occurs on Windows.
When copying and pasting content from a docx file that contains images, the image tags are there, but the images are not shown up. I inspected the html snippet in the editor, the value of the `src` attribute of the `img` is a data uri on Linux (e.g. `data:image/png;base64,...`), and a file uri on Windows (e.g. `file:///C:\path\to\my.png`). When I put the file uri directly into the address bar in the browser, the image is rendered without problem. Do modern browsers restrict accesses to file uri when embedded in html?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
