### ISSUE TITLE
Protected variables are stripped/displayed on editor destroy

### ISSUE THREAD

**Issue by MartijnWelker** [tinymce/tinymce#4662]
Bug report/change of behaviour

In older TinyMCE versions (<= 4.7.13) when destroying an editor the `tinymce:protected` comments were left alone, but in newer version these comments are stripped and the contents are rendered as actual text.

In version `4.7.13` this was still working, but changing the version to `4.8.1` and repeating the steps shows it's broken
http://fiddle.tinymce.com/v3gaab

Steps to reproduce:
**Working version**
1. Select version 4.7.13 (if not already selected)
2. Press `toggle editor` and wait for it to load
3. Press `toggle editor` again, the editor should now be destroyed
4. No protected variables are visible

**Broken version**
1. Select version 4.8.1
2. Press `toggle editor` and wait for it to load
3. Press `toggle editor` again, the editor now displays the protected variables as plain text

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
