### ISSUE TITLE
figure inserted into the html up on one level

### ISSUE THREAD

**Issue by vmiracle13** [tinymce/tinymce#4676]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
When I am in Tinymce editor, click on standard image icon, modal appears, choose the option to add caption (check checkbox), save changes. The tag figure is inserted on one level above than the image was listed. Perhaps that the tags listed after the image are duplicated after adding/activating image caption.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Please check the code at http://fiddle.tinymce.com/crfaab/5 . When I add an image after <strong> tag before <br> tag into the div with the classes 'col-xs-2 col-md-2 text-center' without caption, it is inserted into the place where the focus was. When I edit this image and check checkbox to activate the option of adding the image caption, the image is placed on the one level above - it is displayed after the div with the classes 'col-xs-2 col-md-2 text-center' and after the figure this div is duplicated with <a> tag which was after the image inserted.

**What is the expected behavior?**
It is expected that the tag figure with the caption and the image will be inserted into the place where the image was placed initially

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
It did not work on 4.3.7 version and it does not work on 4.8.5 version.
Browser: Chrome
OS: Ubuntu 16.04

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
