### ISSUE TITLE
Don't strip leading spaces in pasted text

### ISSUE THREAD

**Issue by arlomedia** [tinymce/tinymce#4683]
Bug report

Steps to reproduce:
In a text editor, copy text containing line breaks, and spaces at the start of lines, like this:
```
text
 text
  text
```
Then paste into a TinyMCE editor.

Expected result:
The text will appear as the original, with one space at the start of the second line and two spaces at the start of the third line.

Actual result:
All the leading spaces are removed.

Other notes:
TinyMCE supports leading spaces like this when typing the text in directly. I can type any number of spaces at the start of a line and the spaces will be preserved. I would expect the pasted text to behave consistently with the typed text.

This bug might have been introduced when a previous bug I reported was fixed: https://github.com/tinymce/tinymce/issues/2607. I only noticed the problem on my site after updating to version 4.7.13. The problem also occurs on your home page, which currently uses version 4.8.5.

**Comment by lnewson** [comment]
Hi,

I was able to confirm this issue still exists in TinyMCE 4. However, it appears as though we've fixed the issue in TinyMCE 5.2.2. Looking back at the changelog it appears this issue was fixed in TinyMCE 5.0.10. As such I'm going to close this, however if you're still experiencing issues with TinyMCE 5.0.10 or above then let us know and we'll reopen this issue.

Thanks!
