### ISSUE TITLE
Disabled state for tinymce editor don't works correctly

### ISSUE THREAD

**Issue by protekshen** [tinymce/tinymce#4692]
RELATED https://github.com/tinymce/tinymce-angular/issues/52#issuecomment-443627129

![image](https://user-images.githubusercontent.com/13870417/49362081-d3bf9e80-f6ee-11e8-979b-ca3d4d37669a.png)

I prepared example for you: https://stackblitz.com/edit/tinymce-angular-disabled?file=src%2Fapp%2Fapp.component.html

![image](https://user-images.githubusercontent.com/13870417/48830743-59099180-ed86-11e8-9ab7-a1064166767f.png)

How you can see, we have 2 problems:
1) Text in editor "Test description" is black. When user see this black color for description, he don't understand that this editor is Disabled. I meen we need more light color (Need special 'disable color' for description of editor)
2) Editor buttons has hover when we move cursor on File, Edit, View, Undo, Redo and other edditor links. But Edditor is Disabled. Why we have hover?

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
