### ISSUE TITLE
Version 4.9.1 - Spellchecker keeps the SuggestionsMenu visible after disabled

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4694]
Tested in Firefox. Click in the spellchecker icon. Press the right click over 'thiz' in order to show the SuggestionsMenu for that misspelled word. Click in the spellchecker icon. Now the spellchecker is disabled but the SuggestionsMenu remains visible.

http://fiddle.tinymce.com/s5gaab

**Comment by lnewson** [comment]
This looks to be a larger issue in that context menus aren't being closed when the editor body loses focus, as you get similar behaviour if you enable the context menu plugin and then open a menu, click a toolbar button, etc...

This doesn't appear to be an issue with TinyMCE 5.0, as it is closing the context menu when the editor body loses focus. Here's an updated fiddle that uses 5.0.1: http://fiddle.tinymce.com/s5gaab/2

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
