### ISSUE TITLE
[Bug] Cannot build: Property 'cFillActiveDialog' does not exist in FigureResizeTest.ts

### ISSUE THREAD

**Issue by DMW007** [tinymce/tinymce#4701]
I followed the build instructions of tinymce's readme file and got the following exception: 

```
PS D:\Temp\tinymce> grunt
Running "validateVersion" task

Running "shell:tsc" (shell) task
src/plugins/image/test/ts/browser/FigureResizeTest.ts(47,16): error TS2339: Property 'cFillActiveDialog' does not exist on type '{ cClickOnToolbar: (label: string, selector: string) => Chain<{}, any>; cClickOnMenu: (label: string, selector: string) => Chain<{}, any>; cClickOnUi: (label: string, selector: string) => Chain<...>; ... 5 more ...; cTriggerContextMenu: (label: string, target: any, menu: any) => Chain<...>; }'.
Warning: Command failed: node ./node_modules/typescript/bin/tsc
 Use --force to continue.
```
Tried the current cloned state and the 4.9.1 state using `git checkout tags/4.9.1`. Build was running on Windows 10 x64 1803.

My goal is to bundle all dependencies for my own gulp project, since the default behavior of tinymce is lazy loading some files later. That cause trouble since they are not present on the server. So I want to run `grunt bundle --themes=modern --plugins=table,paste` (also from the readme) which fails because of missing theme js files. So I think that running `grunt` before is required to build them. 

The official tinymce npm package is not helpfull here since I need to figure out myself the required files. And I ran into errors since tinymces script files try to load e.g. fonts and other stuff that doesn't exist.

**Comment by spocke** [comment]
Yeah, we currently don't commit the package lock file. Since we don't want to constantly bump all dependencies since we change them a lot. We are looking in to way to produce reproducible builds of previous versions. I also noticed that we hadn't pushed the master from our internal stash server to github so the public repo should be building now.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
