### ISSUE TITLE
unable to remove some content  by backspace and new line is added

### ISSUE THREAD

**Issue by MennaYueyingLu** [tinymce/tinymce#4706]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When removing a "mceNonEditable" anchor by backspace, a new break line is added but the link is not removed.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1. add a link(non-editable) 2.add a small size image right after link, in the same line. 3. remove image by backspace. 4.remove link. Then a new <br> is added instead of removing the link

**What is the expected behavior?**
link should be able to remove by backspace

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
mac os, chrome Version 70.0.3538.110

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
