### ISSUE TITLE
Version 4.9.2 - Core bug - Paste event isn't catched by the undo button

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4713]
Tested in Firefox. Select the text, copy and paste it at the end of the document and the undo button won't catch that event. Now, position the cursor at the end of the document and press any key. Now the undo button will be activated and you will have two actions to undo (the key that you pressed and the paste event).

http://fiddle.tinymce.com/s7gaab

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
