### ISSUE TITLE
TinyMCE 5: Menu item hover issue

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4716]
The background color changes when you hover over a menu item. However, it is not unset back when you move the mouse pointer outside of the menu. I think it should.

**Comment by TheSpyder** [comment]
This is because moving the mouse isn't just a hover change, it sets focus to the menu item. We only have a focus style, not a hover style, which is why moving the mouse off the menu doesn't change anything.

This is a weird request we had, I think it might've been in an accessibility context, for a mixed-mode keyboard and mouse use case in menus. You can use the mouse to do some of the navigation and then finish the operation on the keyboard.

**Comment by mehronkugler** [comment]
If it's still relevant, I'm not able to reproduce this behavior in 5.1.1 using Chrome 78.

**Comment by lnewson** [comment]
I'm going to close this because as @TheSpyder mentioned above, this is intended behaviour for accessibility purposes.
