### ISSUE TITLE
Update Italian translations

### ISSUE THREAD

**Issue by cekk** [tinymce/tinymce#4727]
**Do you want to request a *feature* or report a *bug*?**

A bug in italian translation

**What is the current behavior?**

There is a missing translation and a typo.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

As reported in #1951 there is a typo in the Italian translation.
I don't know what's the workflow for this, but i tried to fix it on [transifex](https://www.transifex.com/moxiecode/tinymce/translate/#it/theme-modern/12234554) but i can't save it. I added a comment to suggest the change (like other two older comments).

The other problem is that i'm using 4.7.13 version on Plone and it seems to be a missing translation for "Tables".
I think that it should go [here](https://www.transifex.com/moxiecode/tinymce/translate/#it/core/12234429) but i don't know exactly how to add it.

I'd like to help you with these things, but i need some help on how to do it.

**Comment by lnewson** [comment]
Hi,

Thanks for reporting this and sorry you didn't get a response until now. Looking at the TinyMCE translations, the typo has been fixed in transifex and in the language packs, as can be seen in http://fiddle.tinymce.com/hihaab. As for the missing "Tables" string, that string appears to have been removed from the source code as "Table" is the only string now and that is translated as seen in the linked fiddle. As such I'll go ahead and close this, but please do let us know if you're still experiencing issues and we'll reopen this.

Thanks!

P.S. you should be able to add or correct these translations by editing the `it.js` file TinyMCE uses to store it's translations.
