### ISSUE TITLE
Version 4.9.2 - Spellchecker bug - Works with double quotes but not with single quotes

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4733]
Tested in Firefox. The spellchecker works with double quotes but no with single quotes. Click in the spellchecker icon and it will mark the word in double quotes but not the same word in single quotes.

http://fiddle.tinymce.com/T7gaab

**Comment by fyrkant** [comment]
The spellchecker plugin breaks up strings into words using a wordchar pattern that you can set with the `[spellchecker_wordchar_pattern](https://www.tiny.cloud/docs/plugins/spellchecker/#spellchecker_wordchar_pattern) setting. The default pattern does not include `'` because it would then count split words like "won't" to "won" and "t".
