### ISSUE TITLE
RTL-drop-down box, the left position is wrong on the drop-down's element injection to the dom.

### ISSUE THREAD

**Issue by shaibam** [tinymce/tinymce#4743]
**Do you want to request a *feature* or report a *bug*?**
bug 

**What is the current behavior?**
On RTL settings, when opening the drop down from a link embed option, the drop down position wrong.
it seems that the calculated position of the drop-down element is set prior to having the correct width of the element.
a simple hack for fixing this is reposisitioning the element using setTimeout 0, in the moveRel method

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Init TinyMCE to support RTL text (Hebrew) and have a link embed option on the toolbar
from the toolbar, open a link dialog.
make sure the link dialog is apart of the initial settings and that the dialog contains  a drop-down option (eg. see the "Target" option in TinyMCE's basic example).
Result: The drop-down panel is displayed but wrongly positioned.

Here is an image displaying the result:
![image](https://user-images.githubusercontent.com/1324331/50888915-5975ee80-13ff-11e9-801e-136c7138f0d4.png)

**What is the expected behavior?**
The drop-down panel should be aligned with the left border of the field that was used to open it.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
4.2.8 - 4.6.5

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
