### ISSUE TITLE
TinyMCE 5: Spellchecker does not skip emoticons

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4790]
I'm migrating from v4 and I noticed that new emoticons are not ignored by spellchecker. I.e. they are sent as part of the `text` argument in ajax request. I guess I could remove them on the server before passing to spellchecking engine, but it would be better to have it fixed before the request is being made.

I'm not sure they should be skipped always or only when are separated. E.g. `TEST<no-space>😜<space>` or `<space>😜<space>`. Sample form data sent in ajax:
```
{
  method: "spellcheck",
  lang: "en_US",
  text: "test😁 😜"
}
```

ps. I don't see spellchecker at https://www.tiny.cloud/rc/. Would be good to have it enabled.

**Comment by TheSpyder** [comment]
hmm. This wasn't an issue with the old emoticons plugin because it used images.

Our other editor tech (https://textbox.io) doesn't have this issue. This is relevant because we have had some discussion about porting the word "grab" libraries used there to TinyMCE, which would resolve this - but that's not a small task.

I'll log it for investigation.

**Comment by TheSpyder** [comment]
The open source spell checker was removed in TinyMCE 6, sorry.
