### ISSUE TITLE
TinyMCE 5: Wrong contextmenu on video object

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4793]
Steps:
1. Goto editor
2. Insert media object (e.g. mp4 file)
3. Right-click on it.

![media](https://user-images.githubusercontent.com/546788/51660406-eb5c2a80-1fad-11e9-8e01-c1a7ec6a1c4c.png)

**Comment by lnewson** [comment]
Thanks for the report @alecpl! I suspect what's happening here, is that the media plugin actually uses an image to represent the media component in certain circumstances. However the image context menu predicate likely isn't taking that into account, and as such you're seeing the image context menu when you really shouldn't be. I'll log a task so that we can investigate it further.

**Comment by lnewson** [comment]
We reviewed this recently and found that the issue has actually been fixed, we traced this back to the fix done in 5.0.4 so that the image context menu item isn't shown for placeholder images. Please let us know if you find any further issues.

Note: There is no context menu item for media, nor was there one in v4. If you'd like to see one added, then I'd ask if can you please log a new issue.
