### ISSUE TITLE
[Bug] Radio button looses state

### ISSUE THREAD

**Issue by sztrzask** [tinymce/tinymce#4796]
**Do you want to request a *feature* or report a *bug*?**
Report a bug
**What is the current behavior?**
When using `noneditable` plugin radio button inputs are loosing selection state when clicked on a noneditable parent.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
https://codepen.io/sztrzask/pen/PVqvKp

**What is the expected behavior?**
`Checked` property of input doesn't get reset to false for no apparent reason
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Issue happens in branches 4.x and 5.x on Chrome, Edge and IE11.
It worked like a charm in 3.x.

**Comment by lostkeys** [comment]
Sorry for the late reply, we haven't spent time supporting these things because you don't really have anyway to store the data. Selecting a radio button doesn't change the HTML as the `checked` attribute only applies to the default state. For a more technical explanation, [see this Stackoverflow answer](https://stackoverflow.com/questions/6003819/what-is-the-difference-between-properties-and-attributes-in-html/6004028#6004028). If you need simple checklist functionality we have built a [premium plugin](https://www.tiny.cloud/docs/plugins/checklist/) for that.
