### ISSUE TITLE
Resetting of text alignment (to left) on removing number/bullet list

### ISSUE THREAD

**Issue by atulvani** [tinymce/tinymce#4805]
Reporting BUG.

Steps to reproduce:
1. Center or right align any text.
2. Now, hit the number/bullet list button.
3. Click the same button to undo the action from step 2.

Current behavior: Action taken in step 1 is also undone, i.e. the text is set to left aligned after list removal

Expected behavior: Alignment should be preserved on removing list, just like it is when adding the list.

This bug is reproducible on the latest version.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.

**Comment by Vadym-Kyrylenko** [comment]
this issue is still relevant
