### ISSUE TITLE
Page re-scaled after leaving the editor on mobile

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4808]
Using iPhone (iOS 12.0.1):
1. Visit https://www.tiny.cloud/rc/
2. Click on the editor
3. Click blue arrow in the editor menu

The effect is that page width or scale changed (horizontal scrollbar appears) and have to be manually fixed. It does not happen every time, sometimes it's ok.

**Comment by alecpl** [comment]
I can reproduce the same issue on https://www.tiny.cloud, so it's not new.

**Comment by thedrjim** [comment]
This issue has been closed as it refers to the mobile theme that was deprecated in TinyMCE 5.1, as the default theme was extended to support both desktop and mobile. The TinyMCE documentation contains more information about the old mobile theme https://www.tiny.cloud/docs/mobile/#thelegacymobiletheme and the settings for the new mobile support https://www.tiny.cloud/docs/mobile/ . Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
