### ISSUE TITLE
Editor in Bootstrap modal show a blank page with Mobile Theme

### ISSUE THREAD

**Issue by bjournaud** [tinymce/tinymce#4818]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Create a Boostrap modal and add a TinyMce editor.
In desktop mode, everything is fine
In mobile mode, TinyMce show a book to open the editor in full page.
When you click on the book, the navigator show a empty white page without any interaction possible.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Having a textearea in a Boostrap modal
http://fiddle.tinymce.com/GBgaab/5

**What is the expected behavior?**
Show the editor Toolbar 

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
-  TinyMce 5.0.0
- Boostrap 4.2.1
- On Android 9.0 and Chromium (with mobile device switch in dev console)

**Explanation**
For Boostrap, a modal is a Div with a `modal` css class. In this class, there is `display:none;` property.
When Boostrap show the modal, it add `display:block` in the style attribut of the div but when TinyMce show the fullpage editor, it replace the modal style attribut with
```css
position:absolute!important;
top:0!important;
left:0!important;
margin:0!important;
padding:0!important;
width:100%!important;
background-color:rgba(0, 0, 0, 0)!important
```
No more display property, the modal is hidden and the editor is also hidden.

I was able to fix it with a little tweak by adding display class on open and close
```javascript
$('div.modal').on('show.bs.modal', function (event) {
        let modal = $(this);
        modal.addClass('d-block'); // Boostrap class for display-block
    });
    $('div.modal').on('hide.bs.modal', function (event) {
        let modal = $(this);        
        modal.removeClass('d-block');
    });
```

TinyMce should preserve the display value for textarea parents when TinyMce show the editor.
Or at least, adding this tweaks in Boostrap integration page (https://www.tiny.cloud/docs/integrations/bootstrap/)

**Comment by MEChasle** [comment]
I experience same issue with `tynimce 5.0.3` but your trick does not work for me.

The difference with me is that you have already your modal in your DOM. 
I use `bootstrap` through [angular-ui-bootstrap 2.5.0](https://angular-ui.github.io/bootstrap). I open modal with `$uibModal.open()`. My modal is not initially in my DOM. 
If I put your code in the modal itself, the bug is still here.

I understand that there is a problem with the focus between `bootstrap` and `tynimce` on mobile but I do not understand how to resolve it yet.

Any help, please ?

**Comment by MEChasle** [comment]
For information, I have adapted my code with https://stackoverflow.com/questions/54579110/is-it-possible-to-disable-the-mobile-ui-features-in-tinymce-5.

**Comment by thedrjim** [comment]
This issue has been closed as it refers to the mobile theme that was deprecated in TinyMCE 5.1, as the default theme was extended to support both desktop and mobile. The TinyMCE documentation contains more information about the old mobile theme https://www.tiny.cloud/docs/mobile/#thelegacymobiletheme and the settings for the new mobile support https://www.tiny.cloud/docs/mobile/ . Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
