### ISSUE TITLE
BUG - Mobile Navigation into Editor

### ISSUE THREAD

**Issue by KKubesh-Cliq** [tinymce/tinymce#4831]
Description of problem: Bug
When navigating through a form on mobile the plugin does not allow the user to click into the editor.

Visual of Step to produce issue:
![bug-reprod-tinymce](https://user-images.githubusercontent.com/40467312/52812730-ce22f500-305d-11e9-9676-35ad993febab.gif)

Expected result:
We want the user to be able to enter into the editor allow the user to enter it without clicking.

Actual results:
User is not able to go into the editor.

This is a vue application open on a mobile device using the package "@tinymce/tinymce-vue": "^2.0.0

**Comment by thedrjim** [comment]
This issue has been closed as it refers to the mobile theme that was deprecated in TinyMCE 5.1, as the default theme was extended to support both desktop and mobile. The TinyMCE documentation contains more information about the old mobile theme https://www.tiny.cloud/docs/mobile/#thelegacymobiletheme and the settings for the new mobile support https://www.tiny.cloud/docs/mobile/ . Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
