### ISSUE TITLE
[5.0.0] How to include menu items without having to redefine the whole menu?

### ISSUE THREAD

**Issue by Georg-Git** [tinymce/tinymce#4835]
**bug**
Add custom toolbar menu item (editor.ui.registry.addMenuItem) is not working.

"Code example coming soon..." here: 
https://www.tiny.cloud/docs/demo/custom-toolbar-menu-item/

addMenuItem is mentioned here with example:
https://www.tiny.cloud/docs/migration-from-4x/#custommenuitems

But it is not working:
http://fiddle.tinymce.com/oCgaab

Tiny 5.0.0

**Comment by lnewson** [comment]
You've registered the menu item correctly, however you aren't using it anywhere so I'm not sure what you mean by it's not working. So after you register a menu item, you then need to include it an a menu, either by the `menu` configuration item, or within say a toolbar menu button (see https://www.tiny.cloud/docs/ui-components/typesoftoolbarbuttons/#menubutton).

Here's an updated example showing how you can make use of your registered menu item via the menubar/menu configuration: http://fiddle.tinymce.com/oCgaab/1

I'll also make sure to follow up where we are at with the example of using menu items.

**Comment by Georg-Git** [comment]
Thanks for Your example.
But I want to use the standard tinymenu and only add one custom menu item under an existing tiny menu item e.g. "tools".

With v4.x I only need to set one parameter in my custom menu item:
`context: 'tools',`
 
And now with v5.x?
I have to redefine the whole standard menu items of tiny - to add my custom menu item?

Here my updated example:
http://fiddle.tinymce.com/oCgaab/6

A example with a full definition of tiny standard menu would be helpfull - I found only examples with parts of tiny standard menu.

**Comment by deeg** [comment]
@lnewson I tend to agree with @Georg-Git here. It seems odd to have to redefine all of the menu items without being able to inject custom menu items into an existing menu.

Is there another way similar to the old 'context' property from v4?

**Comment by lnewson** [comment]
There currently isn't any way to dynamically update/insert items into the menus, without redefining them as the context property was intentionally removed in v5. However we'd like to hear what your use case is for that, so that we can either look at bringing back that functionality or potentially come up with a new way to implement that.

**Comment by TheSpyder** [comment]
We're discussing this internally and I'd like to get some community thoughts on it. What would fit better with the v5 UI architecture is an editor configuration option to extend menus by name.

So instead of `context: 'insert'` in the menu item definition, this would be added to the editor config:
```
tinymce.init({
  ... // usual stuff
  extend_menus: [
    {
      'insert': 'myItem'
    }
  ]
}
```

With perhaps more complicated values that can be used to support the `prependToContext` property as well.

**Comment by Georg-Git** [comment]
You had changed the text in headline of my issue, so now it does not describe my problem.
I had wasted a lot of time due to the wrong documentation for migration - and still it is wrong.

According to Your documentation:
1. change "editor.addMenuItem" to "editor.ui.registry.addMenuItem"
2. change "onclick" to "onAction"

Thats all - https://www.tiny.cloud/docs/migration-from-4x/#custommenuitems


So my request is:
- complete the documentation for migration
- give a example of a definition of a full featured tiny menu

**Comment by lnewson** [comment]
@Georg-Git can you please clarify where that's said? As I've looked over the migration guide and nowhere does it say that's **all** that's needed. All I can find is one basic example showing an example of the differences and then at the bottom it says to see the menu item configuration docs for more detail about creating a menu item. Certainly we could have more detail about how to include the registered menu item, given that the context property has been removed, however as @TheSpyder mentioned above, we are looking to bring it back in another form.

Anyways, I'll make sure we have a docs task to update the [`menu`](https://www.tiny.cloud/docs/configure/editor-appearance/#menu) configuration for the default full featured menu in regards to your second point and another to look at updating the migration guide with regards to adding the registered items to the menu.

**Comment by Georg-Git** [comment]
Sorry - I missed the new link in the migration guide to the new example:
https://www.tiny.cloud/docs/ui-components/menuitems/#exampleofaddingacustommenuitem

So it was my bad luck of a early adopter 😎

And You are on the right track with Your documentation - please go ahead 🍺

Nevertheless it would be fine if You could respect my efforts in reporting and documenting a bug with a smallest reaction - at least after a year... 
https://github.com/tinymce/tinymce/issues/4344

**Comment by TheSpyder** [comment]
Sorry that your old ticket is still open after a year. We have increased the resources assigned to github tickets with the aim of working through the backlog, but the volume of tickets has also increased with the 5.x release.

Your update yesterday has already flagged it as a ticket that needs looking into (although I can't promise we will fix it quickly, we will at least respond soon).

**Comment by tuanict** [comment]
I also had the same problem when I tried to add a new menu. I had to reconfigure the entire [menu](https://www.tiny.cloud/docs/configure/editor-appearance/#menu)

I hope it is resolved soon! Thank you!

**Comment by dakur** [comment]
@TheSpyder As to the API – there are two things:
- being able to insert menu item to existing menu to the end of it
- being able to insert menu item to existing menu to whatever position (named or unnamed)

The first point could be achieved in v4 with `context` key. In v5 it is gone so whole menu has to be recreated. The second point – which is much more real-world in my experience – has never been implemented so you have to recreate the whole menu anyway.

I suggest to add an API to v5 which brings back extending particular menu with menu item and adds ability to set a position on which it should be added. That could be achieved with something like `prependTo: string` or `appendTo: string`, which would contain relevant menu item name, e.g. `prependTo: 'bold'`. If none of these keys are listed, menu item will be added to the end. There should be also something like `addToBeginningInstead: boolean`, which obviously adds menu item to the beginning instead of to the end of the menu without listing name of the first menu item.

**Comment by TheSpyder** [comment]
@dakur The removal of `context` in v5 was deliberate. I'm not saying we will _never_ bring it back, but while it made deploying plugins easier it reduced the control integrators have over their menu layout.

**Comment by dakur** [comment]
@TheSpyder I'm not saying it was not deliberate. You've asked for community thoughts, so I'm sharing mine based on my working with it. 🙂

**Comment by Somonator** [comment]
I do like this:
` menubar: 'edit view insert format table tools',
        menu: {
            tools: {title: 'Tools', items: 'nesteditem'}
        },`
It seems to work.

**Comment by bearforeverfriends** [comment]
> I using this:
> ` menubar: 'edit view insert format table tools', menu: { tools: {title: 'Tools', items: 'nesteditem'} },`
> It seems to work.

Tested.
It is working!!!

Thx for sharing.

**Comment by AccessViolator** [comment]
It's V6 now and it's still not implemented.
The feature is needed.
I hope the "genius" who decided to remove it in V5 isn't with the company anymore...
