### ISSUE TITLE
Toolbar is incorrectly positioned in inline mode when inside scroll container

### ISSUE THREAD

**Issue by mattford** [tinymce/tinymce#4839]
Bug report

**What is the current behavior?**
When using the modern theme in inline mode in a scroll container, the toolbar is misaligned if scrolled down in the scroll container

Having trouble reproducing this on fiddle, think because the result is shown in an iframe, HTML code to reproduce attached.
[test.txt](https://github.com/tinymce/tinymce/files/2880520/test.txt)

**What is the expected behavior?**
I would expect to see the toolbar correctly positioned relative to the scroll container

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
4.9.3, Chrome 72

I have tried the ui_container config option but this doesn't help. I think the problem lies in the handling of scroll container within the Modern theme

**Comment by blackcathikari** [comment]
@mattford We think we've replicated this, could you please check it's the same behaviour?

1. http://fiddle.tinymce.com/JCgaab
2. Scroll down in the editor area, inside the scroll container
3. Double click editor text

Toolbar goes to the bottom of the page, or is offset by the scroll amount if the editor was clicked into before scrolling. 

Note: can't replicate in 5.0.0.

**Comment by mattford** [comment]
@blackcathikari that's the same behaviour yes

**Comment by blackcathikari** [comment]
Thank you! I'll talk to the team about this.

**Comment by thedrjim** [comment]
This issue has been closed as it refers to the mobile theme that was deprecated in TinyMCE 5.1, as the default theme was extended to support both desktop and mobile. The TinyMCE documentation contains more information about the old mobile theme https://www.tiny.cloud/docs/mobile/#thelegacymobiletheme and the settings for the new mobile support https://www.tiny.cloud/docs/mobile/ . Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.

**Comment by mattford** [comment]
@thedrjim this issue was occurring with the `modern` theme not `mobile` so is likely still valid for tinymce 4.x

**Comment by lnewson** [comment]
Hi @mattford, this does appear to have been incorrectly closed sorry. Having said that though, TinyMCE 4 is no longer supported anyways (see https://www.tiny.cloud/blog/tinymce-4-support-window/) so I'm going to leave this closed since it's only applicable to the `modern` theme as I understand it. If that's not the case, let me know and I'll reopen it.
