### ISSUE TITLE
mobile theme trigger back

### ISSUE THREAD

**Issue by mech01nc01** [tinymce/tinymce#4841]
**Do you want to request a *feature* or report a *bug*?**
i don't know if it is a bug or a feature request

**What is the current behavior?**
in mobile view, you touch the book and the full-screen-Editor opens (nice)
if you tab back in the browser, navogation will start

Right now i detect if the full-screen-Editor is open (body-class) and Prevent the Navigation back

**If the current behavior is a bug, please provide the steps to reproduce**
see above

**What is the expected behavior?**
full-screen-Editor should close
i wouldn't Need tinymce do it for me, it would be enough if i would have the possibility to trigger something like tinyMCE.activeEditor.hidedropup()

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
"tinymce": "^5.0.0"
Chrome (Windows, Android)

**Comment by blackcathikari** [comment]
@mech01nc01 Sorry, I don't quite understand. Are you requesting:
1. A built-in way to override the browser's navigation behaviour
2. An API method that closes the editor in mobile
3. Something else?

**Comment by mech01nc01** [comment]
hi blackcathikari,

yes, an API-Method to close the mobile Editor would be great! (so i can call it when the user tries to navigate back)

**Comment by mech01nc01** [comment]
@alyrik Right now when a user tries to navigate back, i check if (document.body.className == 'tinymce-mobile-android-scroll-reload') and prevent the navigation, but that is just a bare minimum, quite far from ideal

**Comment by alyrik** [comment]
Do you add this listener initially on a page even an editor is not open?

I'm trying to implement a similar solution but only for such state when an editor window is open:

1. Start interval: check every X ms if the current editor instance has `tinymce-mobile-fullscreen-maximized` class.
2.1. If it has it means that the editor was open by user. Set `isEditorOpen` to true and add event listener for popstate.
2.2. If it hasn't but `isEditorOpen` currently set to true it means that editor was closed by user. Set `isEditorOpen` to false and remove event listener for popstate.
For other variations do nothing (it means that UI state and logic state are synchronized).

**Comment by mech01nc01** [comment]
@alyrik don't use interval, in this case it wont't cover 100% (but i don't know what technologies u are using)
i'm using vuejs and vuerouter in history mode so i can handle and intercept navigations:

router.beforeEach((to, from, next) =>
```
{
	console.debug("Router Guard: from/to", from, to);
	if (document.body.className == 'tinymce-mobile-android-scroll-reload')
	{
		console.debug("tinymce-mobile-android detected, no routing");
		next(false);
	}
	[…]
}
```

**Comment by thedrjim** [comment]
This issue has been closed as it refers to the mobile theme that was deprecated in TinyMCE 5.1, as the default theme was extended to support both desktop and mobile. The TinyMCE documentation contains more information about the old mobile theme https://www.tiny.cloud/docs/mobile/#thelegacymobiletheme and the settings for the new mobile support https://www.tiny.cloud/docs/mobile/ . Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
