### ISSUE TITLE
[5.0.1] Building Tiny all bundled - but browser is missing emojis.min.js  

### ISSUE THREAD

**Issue by Georg-Git** [tinymce/tinymce#4847]
***bug***

Building tiny with themes and plugins bundled into a single file.
No Errors in build process, but when starting editor in browser:
**404 not found**: /tinymce/plugins/emoticons/js/**emojis.min.js** 

All the other bundled plugins were OK.

Fresh installation of npm, all cached files deleted:

`grunt bundle --themes=silver --plugins=emoticons, ...`

Logs without errors:
```
..
Running "uglify:emoticons-plugin" (uglify) task
>> 2 files created 280.77 kB → 201.19 kB
..

Running "bundle:minified" (bundle) task
Appending file: js/tinymce/tinymce.min.js
Appending file: js/tinymce/themes/silver/theme.min.js
Appending file: js/tinymce/plugins/emoticons/plugin.min.js
...
>> Created bundle js: js/tinymce/tinymce.full.min.js

```

npm 6.8.0
grunt-cli 1.3.2
uglify-js 3.4.9

Tiny Master = 5.0.1

**Comment by lnewson** [comment]
Thanks for the report! Unfortunately this one is larger than just the bundling issue, as it appears the way this was implemented in v5 doesn't allow for the emoji JS file to be part of a single bundle. The reason for that decision, is the "database" is fairly large and we didn't want it slowing down the loading of the plugins/editor.

I'll discuss this with the team and see how we want to go forward with the JS database with regards to single bundles and let you know once we have something planned.

**Comment by Shepard** [comment]
I ran into this problem as well and it also pops up in other places. E.g. issue #3797 describes how you cannot currently bundle the skin CSS resources. And other plugins like powerpaste also try to load additional resources on initialisation.

While I understand the argument for wanting to split these resources off into later requests to make the initial page load faster, it means you can't control this yourself when integrating tinymce into a project. E.g. one use case might be to apply code splitting in a project and put all code related to the integration of tinymce and its plugins into one separate bundle.
Also it makes integration harder because you have to copy tinymce files around in your project (from node_modules into a directory that static resources are served from). And the biggest problem in my view is that in this case you cannot even influence the URL used for fetching the plugin resources (unlike the skin CSS resources where you can influence this with the skin_url parameter).

**Comment by TheSpyder** [comment]
If we added ways to control the path to these unbundled files, would that help? We can certainly look at this but the reason they were integrated in a separate way is that nothing about them is required for the editor to load. Bundling them would just bloat the initial download unnecessarily.

**Comment by Shepard** [comment]
I would say: yes, it solves the problem. If you can at least influence the URLs you can find ways to serve the files at that location.
Ideally I would still want to be able to decide how to bundle the files myself for said reasons. But that's probably more of a feature request.

But that's just my opinion. Ultimately the reporter of the ticket will have to say if it solves their problem. :-)

**Comment by Georg-Git** [comment]
I have no problem as far I can control the path.

When starting to look in this direction:
what about other huge plugins like table?

What about two bundled files, first file needed for fast init of tiny, second file loaded deferred?

**Comment by TheSpyder** [comment]
We made some progress on this front in 5.0.13; we built a [`tinymce.Resource`](https://github.com/tinymce/tinymce/blob/master/modules/tinymce/src/core/main/ts/api/Resource.ts) API to let external script files be loaded in a supported way that allows bundling (there isn't any documentation yet).

The [emoji JS file](https://github.com/tinymce/tinymce/blob/master/modules/tinymce/src/plugins/emoticons/main/js/emojis.js#L2) now loads in such a way that it _can_ be bundled but `grunt bundle` hasn't yet been updated to include it.
