### ISSUE TITLE
[5.0.1] Inline editor: can't edit media when using valid_elements

### ISSUE THREAD

**Issue by jordanade** [tinymce/tinymce#4851]
Using inline editor and quickbars. Content is:
```<p><iframe src="//www.youtube.com/embed/I6knlUEDjTE" frameborder="0" width="560" height="314"></iframe></p>```

Using `valid_elements: "h2,ul,ol,li,p,blockquote,br,b,strong,i,em,a,iframe"`

Live preview doesn't work, video is displayed as empty square.
**Insert/edit media** opens but fields are empty.

Error in console when opening editor:
```
Uncaught Error: Errors: 
Failed path: (data > source1)
Could not find valid *strict* value for "value" in {}

Input object: {
  "source1": {},
  "dimensions": {
    "height": "",
    "width": ""
  },
  "embed": "<iframe></iframe>",
  "source2": {
    "value": ""
  },
  "poster": {
    "value": ""
  },
  "type": "iframe"
}
```

Chrome 72, TinyMCE 5.

**Comment by lnewson** [comment]
You have a configuration issue, as you're wiping out all attributes for every element with that `valid_elements` setting, which is then causing an iframe with no elements to be created. As an very basic example, if you change that to `valid_elements: "h2,ul,ol,li,p,blockquote,br,b,strong,i,em,a,iframe[src]"` then it does render the iframe correctly because the src attribute doesn't get wiped.

**Comment by jordanade** [comment]
Ah, I didn't realize `valid_elements` worked that way. Thanks.
