### ISSUE TITLE
Link menu issues on mobile

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4862]
I'm using Chrome on desktop in mobile mode.

1. The dots, that I suppose are there to indicate number of menu "screens"/inputs, are all grey no matter where I am in the menu. In other words one of them should be using different color. And indeed it does, but difference between #ccc and #c8cbcf is none (at least for me).
2. Left/Right icons are too small for a touch device. Input cancel button (`.tinymce-mobile-icon-cancel-circle tinymce-mobile-icon`) is too small too.

**Comment by lnewson** [comment]
Thanks for the report! I'll pass the issues mentioned onto our design team so they can review.

Also just as a heads up, mobile theme isn't something we've had a chance to look at atm in v5 unfortunately, so all we've currently done is update the skin/icons to make it look like the v5 skin. So functionality wise it should still be the same as v4, which is why I've removed "TinyMCE 5" from the title.

**Comment by alecpl** [comment]
I would appreciate more love for the mobile mode sooner than later. Especially these obvious user-facing issues make the editor look unprofessional. Here's the list: #4863, #4865, and this one.

**Comment by TheSpyder** [comment]
The mobile theme is not used by default in version 5.1 and has been deprecated. This doesn’t impact the silver theme on mobile.
