### ISSUE TITLE
TinyMCE 5: An event for tabpanel switch in dialogs

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4869]
To re-style dialogs/forms I've been informed that I can use (undocumented) OpenWindow event. And it worked nice until I noticed that it gives me access to the content of the first tab only. When switching between tabs the form is re-created and I need to apply styles again.

I don't see an event I could use. So, please add it. Otherwise, I'm back to using MutationObserver which is not that nice.

**Comment by TheSpyder** [comment]
Sorry for not addressing this sooner. `OpenWindow` wasn't really designed to let you re-style dialogs, even though I did tell you it might be a reasonable solution.

Adding an event like this isn't easy either, as we have fairly clean separation between the UI and the editor (which the UI would need in order to fire this event).

We really think customising the Oxide skin is the best solution rather than applying styles at runtime. What's missing from the documentation that would make this a viable path for you? Or is there something about the skin itself we could improve?

**Comment by alecpl** [comment]
Unfortunately css is not all. I need to assign some javascript code (events) e.g. to `<select>` elements (so they look and behave as other selects in my app). Another use-case is to add some custom elements to existing dialogs.
