### ISSUE TITLE
Unable to apply a custom format with relative font size to a node multiple times.

### ISSUE THREAD

**Issue by mattcoz** [tinymce/tinymce#4885]
Here is what I'm trying to do. I have custom formats set up for changing the relative font size. Applying the format once works, gives me this:

`<span style="font-size:larger;">text</span>`

But applying the format again does nothing, what I want is this:

`<span style="font-size:larger;"><span style="font-size:larger;">text</span></span>`

This would increase the font size twice. My assumption is that they are being merged because they are the same value, but relative font sizes compound and should not be merged.

**Comment by lnewson** [comment]
This currently cannot be done with the formatting logic in TinyMCE to the best of my knowledge, as the idea is that the format is already applied so it won't try to apply it again (like you mentioned), as you wouldn't want that to happen in most cases. So I'll mark this as a feature request for something to consider adding.

One thing that may work for you as an alternative, is instead of using a format for this, register a command (eg `editor.addCommand(name, func)`) to do the logic you want. That does however mean you have to do the wrapping logic yourself (which isn't trivial) and also register a custom toolbar button or menu item, so that might not work for you either.

**Comment by lostkeys** [comment]
Hi @mattcoz! I know it has been a while since you posted this feature request, but we're doing a bit of house cleaning in our TinyMCE GitHub issue tracker. In order to better understand whether this feature request is worth keeping or not, can you elaborate more on the use case and problem you are trying to solve so we know if this feature is valuable to the broader community as well. Thanks.

**Comment by lostkeys** [comment]
We haven't heard from you within a month so we're going to close this issue. Feel free to add an update at any time and we'll reopen the issue.
