### ISSUE TITLE
TinyMCE 5: Keyboard navigation broken on "More..." button in the toolbar

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4906]
Steps:
1. On the editor in https://www.tiny.cloud/ use TAB key to goto the "More..." button and press Enter key.
3. Press Enter again. Nothing happens. Also Tab key jumps to the editing area instead of the next button (previously hidden) in the toolbar.

**Comment by wonderbugtiny** [comment]
The keyboard navigation for the toolbar drawer was fixed in 5.0.3. Please note that the expected behaviour for the `sliding` mode is: when Enter key is pressed while on the "More..." button, the focus shifts to the next toolbar button (previously hidden). And the Tab key should now work as expected.

There is one other known issue where, when you press Tab key while inside the last toolbar group (of the previously hidden toolbar), the focus shifts to the editing area. A fix has been scheduled for the same in upcoming releases. Thank you.
