### ISSUE TITLE
Left padding in editor become different for ordered/unordered lists when different font and font size are applied to lists

### ISSUE THREAD

**Issue by KateMaruk** [tinymce/tinymce#4946]
**Environment:**
_Browsers_: Chrome, Internet Explorer, Edge, Safari
_OS:_ Windows 10, MacOS
_TinyMCE editor:_ v.4.8.3

**Steps to reproduce:**
1. Create 2 ordered lists
2. For first list set font "Terminal" and size "24pt"
3. For second list set font "Georgia" and size "36pt"
4. Set left alignment for lists

**Actual result:**
Left padding for lists become different: http://img.mtrc.in/cfd18656f197

**Expected result:**
Padding should stay the same for lists despite of selected fonts and font sizes

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
