### ISSUE TITLE
Empty paragraph when a line break is used in a list

### ISSUE THREAD

**Issue by lorig** [tinymce/tinymce#4948]
I feel like this is a bug, but I welcome any advice.

I am getting empty paragraph tags added to the markup when I have a list with a line break in it, then a sub-list. For example:

`<ol><li><strong>Manage Curriculum</strong><br>With OneDrive, professors can:<ul><li>organize class assignments</li></ul></li></ol>`

Ends up like this:
`<ol><li><strong>Manage Curriculum</strong><br>With OneDrive, professors can:<p></p><ul><li>organize class assignments</li></ul></li></ol>`

If I remove the line break, the empty paragraph tag will not appear. Right now, HTML validation says: 
Error: No p element in scope but a p end tag seen.

So, whether it is actually `<p></p>` or just `</p>`, it is causing extra line space.

I believe the TinyMC version is 4.8.0. While we are using WP Bakery, this seems to happen whether I use a WP Bakery element or not.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
