### ISSUE TITLE
Bug paste ie11

### ISSUE THREAD

**Issue by raouldandresy** [tinymce/tinymce#4949]
Hi all,
i'm developing a rich text with version 4.3.9 and i'm in trouble with the plugin paste that has a strange behavior for ie11.
The case is a copy e paste from word, in chrome is working fine but with ie11 isn't retain the indentation of bullet list.
I attached a file for testing to the main site --> https://www.tiny.cloud/docs/demo/basic-example/
[Test Rich Text.docx](https://github.com/tinymce/tinymce/files/3093192/Test.Rich.Text.docx)

**Comment by TheSpyder** [comment]
Cross posted to stack overflow
https://stackoverflow.com/questions/55902005/tinymce-copy-paste-ie11

**Comment by mfromin** [comment]
Also posted here:  
https://community.tiny.cloud/communityQuestion?id=9064N000000EUByQAO

**Comment by stenava** [comment]
Hi,
I'm a colleague of Giuseppe's (raouldandresy) and I'm well aware of the issue. He's very busy at the moment so I'll add some details on his behalf.
Basically our client produced a Word file (the one uploaded in the original post) using different font styles and nested lists. One section (three levels of nested lists with different font styles) has a weird behavior: when posted into the TinyMCE editor using IE11, the second and the third list levels have a wrong indentation - the first "list item" of the second level is correctly shifted to the right but the other items are aligned again to the left. Same for the third level.
We created a new Word document from scratch and tried to create the same situation, but we failed: our document looks (to us) exactly the same as the client's, but it works just fine.
We use TinyMCE 4.9.3 but the issue can be reproduced on the TinyMCE demo of v5 as well.

Steps to reproduce the issue:
 - visit https://www.tiny.cloud/docs/demo/basic-example/ with IE11
 - paste the content of document "Test_tiny_fail.docx"
 - see the result

The same steps performed with "Test_tiny_pass.docx" give a correct result instead.

Some more details:
 - in Chrome, both documents are working fine
 - the "full featured" demo is working correctly with both files using IE11, but unfortunately buying the PowerPaste plugin is not an option for our client

Please do not hesitate to ask any more clarifications you might need,
thank you

[Test_tiny_pass.docx](https://github.com/tinymce/tinymce/files/3141372/Test_tiny_pass.docx)
[Test_tiny_fail.docx](https://github.com/tinymce/tinymce/files/3141373/Test_tiny_fail.docx)

**Comment by stenava** [comment]
Hello,
one more detail.
We tried to copy and paste the content of the two word files onto the website that Michael suggested on stackoverflow [ http://static.ephox.com/clipboard/clipboardtestms.html ] and we analyzed the results.
We noticed that all the `<li>` elements that are **not** aligned correctly in Test_tiny_fail.docx have the attribute `font-weight: bold;`
On the other hand, all the `<li>` elements in Test_tiny_pass.docx have `font-weight: normal;`
We suspect this might have something to do with the issue.
Please find below the output of the copy&paste for the two documents.

[Test_tiny_pass.txt](https://github.com/tinymce/tinymce/files/3147035/Test_tiny_pass.txt)
[Test_tiny_fail.txt](https://github.com/tinymce/tinymce/files/3147036/Test_tiny_fail.txt)

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
