### ISSUE TITLE
Insert/Edit Link not working in Safari

### ISSUE THREAD

**Issue by onlineTransport** [tinymce/tinymce#4950]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Insert edit dialog displays but no fields are available for the link. Reproducible on tiny.cloud demo:
![Screen Shot 2019-04-18 at 9 27 35 AM](https://user-images.githubusercontent.com/46717720/56365368-b59a9c80-61be-11e9-83ce-1d90637d4685.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Highlight text in editor, click Insert/Edit link icon.

**What is the expected behavior?**
I should see the fields to insert/edit link.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5, Safari latest version on Mac.

**Comment by mfromin** [comment]
This does not happen in my testing using Safari 12.1.  Do you have any plugins/extensions running in your browser?  If you disable all of them does the result change?

**Comment by onlineTransport** [comment]
There are no extensions installed in the user's Safari. It is behind a
proxy so I'm now wondering if there's something going on there.

Thank you for checking this.

Online Transport

**Comment by lnewson** [comment]
@onlineTransport is this still an issue? If so could you provide more details on how to reproduce this, as I'm unable to reproduce this locally, on http://fiddle.tinymce.com/ or on our homepage https://www.tiny.cloud/ using Safari 12.1.

One thing that would be worth checking, is to see if you're somehow running in quirks mode, as I've seen this happen in Safari/Chrome when running in quirks mode which I believe is due to a flex bug on those browsers (though TinyMCE 5 doesn't support quirks mode anyways). You can check if you're running in compatibility mode by opening the dev console and checking what `document.compatMode` returns. If it returns `BackCompat` then you're running in quirks mode.

**Comment by onlineTransport** [comment]
Unfortunately I don't have easy access to this computer, as most people use Windows here. I'm sure it is still a problem since nothing has changed but I will let you know as time allows. 

For now I have them using Chrome on their Mac and it isn't a problem.

**Comment by Mars09** [comment]
- Safari 12.1 on Mac
- TinyMCE 5.0.6
- Chrome 74

I had the same problem on Safari browser 12.1. In my case I deactivate the adBlockPlus extension, then it works. On Chrome it's the same, if you deactivate the adBlock extension then it should work as well.

**Comment by onlineTransport** [comment]
Okay, I got access to this computer today and have some news for you. Safari developer tools document.compatMode returns CSS1Compat and there are zero extensions installed:

![image](https://user-images.githubusercontent.com/46717720/58267711-2b5fce00-7d52-11e9-8951-f75c22eebb6f.png)

![image](https://user-images.githubusercontent.com/46717720/58267722-30248200-7d52-11e9-9001-da9a1af6ab07.png)

I've confirmed that the issue still exists as well. Strange.
