### ISSUE TITLE
Applying incorrect styles from style_formats items with same title (nested or not)

### ISSUE THREAD

**Issue by frazeedesign** [tinymce/tinymce#4958]
**BUG**

The current behavior is that if you have two style formats with the same title (even when nested under different items) the first style with that title is applied. The example below will always return a background color of red. Additionally, both options are checked in the dropdown. I assuming the key is based off of the title and not the array index?

```
{"title": "Background Colors", "items": [
        {"title": "Black", "selector": "*", "styles":{"background-color":"red"}}
]},
{"title": "Text Colors", "items": [
	{"title": "Black", "selector": "*", "styles":{"color":"blue"}}
]}
```

The expected behavior: To apply the correct styles from the selected option.

Affected versions: 5.0.0 - 5.0.4
Works on version: 4.9.4

http://fiddle.tinymce.com/4Ggaab

**Comment by metricjs** [comment]
Hey @frazeedesign, this occurred because formats are registered using their `title` and therefore the two formats were registered under the same name. We implemented a new option for `style_formats` in 5.6 that allows you to specify a custom `name` for formats to avoid this. You can find more information in the [5.6 release notes](https://www.tiny.cloud/docs/release-notes/release-notes56/#newoptionalnamefieldforthestyle_formatsoption) and [`style_formats` documentation](https://www.tiny.cloud/docs/configure/editor-appearance/#style_formats). So, I am going to close this ticket as fixed. If you find another issue, please feel free to create a new ticket.
