### ISSUE TITLE
Tablet issue tinymce 5 and mobile version

### ISSUE THREAD

**Issue by cfconsultancy** [tinymce/tinymce#4967]
Feature

Instead of checking for android for example it would be better to check for screen width I think

Using tinymce 5 on a large android tablet gives the mobile version instead of the full version, however there is enough screen width and height to load the full version

**Comment by spocke** [comment]
There are more things the mobile theme provides that just the screen size. It’s a more mobile friendly touch enabled ui. The desktop ui components is not optimized for touch devices also iOS has a whole set of scrolling problems that the mobile theme works around that the silver theme don’t. However you can manually configure tinymce to load the silver theme on mobile devices by just setting the mobile configuration section and setting theme to silver instead of mobile. This can be wrapped in your own if statement where you detect screen size or use media queries to switch theme so it’s very flexible. We have plans to improve the mobile experience and include support for more plugins but that would require more mobile first specific ui components to be added to the mobile theme.

**Comment by cfconsultancy** [comment]
Okay, thanks for the explanation

**Comment by TheSpyder** [comment]
We are working on better mobile optimisation for TinyMCE 5.1 which should remove the need for a dedicated mobile theme 🙂

**Comment by lostkeys** [comment]
5.1 is out with better mobile support so please try it out and if you have any issues or feedback, let us know!
