### ISSUE TITLE
TinyMCE - Copy paste bullet list issue

### ISSUE THREAD

**Issue by laeeqwtb** [tinymce/tinymce#4973]
When create a nested bullet list in Google Doc or Word Document and copy paste content in TinyMCE editor, the first level of bullet getting messed up and every level starts with the number 1 instead of 1,2,3,4,5.

Steps to reproduce issue:

1- Create bullet list in Google document like below
![1](https://user-images.githubusercontent.com/2102705/57011989-e3053280-6c21-11e9-9141-bb1d193e1e43.png)

2- Copy paste bullet list content from Google document to TinyMCE editor.
![2](https://user-images.githubusercontent.com/2102705/57011993-ea2c4080-6c21-11e9-83da-6697a86f9ac1.png)

In above screenshot, you can see the Heading1, Heading2, Heading... numbered as 1 instead of 1,2,3

I have checked this issue with latest **TinyMCE version 5.0.4.** and issue is occurring.

Expected result:

The bullet list should be same as copy paste content as 1,2,3.

**Comment by blackcathikari** [comment]
@laeeqwtb Are you using the paste or PowerPaste plugin? PowerPaste is specifically designed for copy/pasting content from Word docs, which is quite complicated. The paste plugin, being the community version, does not have the same kind of support for Word.

**Comment by topikus** [comment]
Have the same error. NO plugins (PowerPaste, Paste). Inserting a list from Google Docs breaks the numbering.

**Comment by metricjs** [comment]
@topikus If you aren't using either Paste or PowerPaste then it is the browser itself that is parsing the content for the paste, not TinyMCE. From a quick investigation, Google Docs uses invalid HTML for nested lists which the browser does not attempt to fix.

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
