### ISSUE TITLE
toolbar_drawer only for single toolbar?

### ISSUE THREAD

**Issue by manu37** [tinymce/tinymce#4977]
It seems to me that the new `toolbar_drawer` property runs just for a single toolbar. `toolbar1 ... toolbarN` are merged to a single toolbar. Bug or feature?

**Comment by lnewson** [comment]
Sorry for only getting back to this now, but it was originally intentional that `toolbarN` got merged into a single toolbar however based on community feedback in https://github.com/tinymce/tinymce/issues/4819 we've brought it back in TinyMCE 5.0.8.

However in saying that, `toolbar_drawer` isn't compatible with `toolbarN`, so if you are using toolbarN the toolbar drawer will be disabled. We've added a note for that in our docs, however that hasn't been released yet: https://github.com/tinymce/tinymce-docs/pull/1074
