### ISSUE TITLE
TinyMCE 5: browser_spellcheck issue

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#5003]
In TinyMCE4 with `browser_spellcheck:true` I was able to use both spellchecker plugin and browser spellchecker. Because browser spelling options menu was under right-click and plugin menu under left-click (on a mispelled word).

In TinyMCE5 this does not work. On right-click the editor contextmenu appears (with Link option). If I disable contextmenu with `contextmenu:false` I can get browser's contextmenu on right-click, but I still cannot get plugin's menu. Left-click does nothing.

**Comment by TheSpyder** [comment]
Yes, we changed it to right click in TinyMCE 5. No other editor I can think of uses left click to show spelling suggestions. This moves spelling in line with other editor experiences, including our premium spelling plugin so developers who choose to upgrade do not change the user experience.

We don't explicitly support having two spelling engines enabled, although yes it worked up through the 4.x versions due to the implementation details of the spelling plugin. However the implementation has now changed, sorry.

If you'd like the browser context menu to appear you can customise the context menu to exclude the `link` section, when the context menu is empty it will fall back to the browser context menu, however in scenarios where other context menu sections activate (e.g. table) the editor context menu will still override the browser menu.

**Comment by lnewson** [comment]
It's also worth noting, that while currently undocumented you can still access the native context menu by pressing CTRL while right clicking.

**Comment by alecpl** [comment]
So with `browser_spellcheck: true` and disabled spellchecker plugin you still have to use CTRL for browser spellchecking options. I don't think I like that, but I don't know how to improve that either. I'll probably have to disable contextmenu (It was disabled in Roundcube with TinyMCE 4 anyway).
