### ISSUE TITLE
Missing "Yes" and "No" localization

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#5009]
In v5 (I didn't check v4):
1. Select some text
2. Open Insert Link dialog
3. Enter "www.domain.tld" in the URL input. Click Save.
4. Another dialog should appear with a warning about external link use and http:// prefix and two buttons: Yes and No.

Result: Button labels are not localized.

ps. The dialog also has no title, maybe it should have one.

**Comment by lnewson** [comment]
I've just checked the latest language packs available for download and they now include the missing Yes/No translations. I'm not sure when this was resolved, but I suspect it might have been when the TinyMCE 5.1 translations were pushed into transifex. Anyways, since this issue has been resolved I'm going to go ahead and close this. If you have any further issues, please let us know.
