### ISSUE TITLE
tinymce/themes/modern/theme.min.js .  404 (Not Found)

### ISSUE THREAD

**Issue by suhailkc** [tinymce/tinymce#5015]
`tinymce.min.js:9 GET http://localhost:3000/vendors/tinymce/themes/modern/theme.min.js net::ERR_ABORTED 404 (Not Found)`
[error screenshot](https://ibb.co/c8FnKKz)

And I can't find 'modern' folder inside 'node_modules/tinymce/themes/'.
[screenshot](https://ibb.co/nDqpyXg)

How to fix it?

**Comment by lnewson** [comment]
The `modern` theme is a TinyMCE 4 only theme, so if you want to use `modern` make sure you use for example `tinymce: ^4.9.4` inside your package.json (or whatever package manager you're using).

Alternatively if you do want to upgrade to TinyMCE 5, then change your `theme` configuration to use `silver` instead of `modern`. For more information on migrating to TinyMCE 5, check out our migration docs here: https://www.tiny.cloud/docs/migration-from-4x/

**Comment by suhailkc** [comment]
worked. thanks

**Comment by mabing2637** [comment]
Hello,I have a error, under this.
GET http://localhost:8003/themes/modern/theme.js net::ERR_ABORTED 404 (Not Found)
my package.json 
![image](https://user-images.githubusercontent.com/34332087/91517343-1d6b0680-e920-11ea-8b49-265498165f37.png)
Can you tell me this question?

**Comment by sganzerla** [comment]
Cool,  changed angular.json  by @lnewson thank you

> O `modern`tema é um tema apenas do TinyMCE 4, portanto, se você quiser usar, `modern`certifique-se de usar, por exemplo, `"tinymce": "^4.9.4"`dentro de seu package.json (ou qualquer gerenciador de pacote que estiver usando).
> 
> Como alternativa, se você deseja atualizar para o TinyMCE 5, altere sua `theme`configuração para usar em `silver`vez de `modern`. Para obter mais informações sobre a migração para o TinyMCE 5, verifique nossos documentos de migração aqui: https://www.tiny.cloud/docs/migration-from-4x/



![image](https://user-images.githubusercontent.com/22710963/134725622-c0384223-b30e-4b14-a555-97ea3b25e655.png)
