### ISSUE TITLE
TinyMCE 5: Remove forecolor/hilitecolor does not work with custom formats

### ISSUE THREAD

**Issue by LinZhouWebDev** [tinymce/tinymce#5026]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

When using custom formats for forecolor and hilitecolor, once a color format is applied, it cannot be removed using the "remove color" option under "Text color"/"Background color" split button or "editor.formatter.remove" function

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/jJgaab 
Steps to reproduce: 
1. Select the text in the editor, apply a forecolor using "Text color" button
2. Select the text again, use "remove color" under "Text color" split button

Same goes for "Background color"

**What is the expected behavior?**

Text color / background color should be removed

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Tested on 5.0.2-5.0.6 on Google Chrome and Firefox

**Comment by lnewson** [comment]
You need to at minimum set the `remove_similar` format setting on the format if you're overriding the default format. Here's a working example: http://fiddle.tinymce.com/jJgaab/1

Note: I'd also suggest using the other format settings used in the default forecolor/hilitecolor formats, otherwise you could have other unexpected results: https://github.com/tinymce/tinymce/blob/master/modules/tinymce/src/core/main/ts/fmt/DefaultFormats.ts#L151
