### ISSUE TITLE
System fonts are too high

### ISSUE THREAD

**Issue by hulang** [tinymce/tinymce#5030]
![System Font](https://user-images.githubusercontent.com/4961831/58755798-20f5bf00-851e-11e9-847b-e6b2916d31e0.png)
I am the default configuration, how should I configure it?

**Comment by lostkeys** [comment]
I'm not sure I understand. Can you clarify how the system fonts are too high?

**Comment by hulang** [comment]
@lostkeys Yes, it's too high. Add a scroll bar.

**Comment by hulang** [comment]
@lostkeys Look at the picture, I click on the font, so high!

**Comment by lostkeys** [comment]
It is supposed to look like that. In general you don't want scrolling menus because a lot of people will not notice the scrollbar, therefore menus expand to fill all available space. If you don't want all the fonts in that list, you can configure which fonts to show using the [font-formats option](https://www.tiny.cloud/docs/configure/editor-appearance/#font_formats). Here is [an example](http://fiddle.tinymce.com/bKgaab)

**Comment by hulang** [comment]
@lostkeys I didn't say not to remove unnecessary fonts, but to add a scroll bar.
