### ISSUE TITLE
TinyMCE 5: span being removed when bold or italic are applied

### ISSUE THREAD

**Issue by therealsamsquanch** [tinymce/tinymce#5033]
I would like to report a bug.

I have a span with a custom attribute. If I selected that text and try to apply bold or italic, the span is totally removed. Using the _valid_children_ option I added span as a valid child of em, bold, i, and b, but it didn't help.

I set up a fiddle so you can see what is going on, the highlighted text is a span with a custom attribute:
http://fiddle.tinymce.com/9Jgaab

It does work if use _formats_ to turn _bold_ and _italic_ into _spans_, the classes are added and the span preserved.

I'm using Chrome 74 on Windows 10.  TinyMCE 5.0.6.

**Comment by lnewson** [comment]
A workaround to this bug is to add a class, or something similar to the span element: http://fiddle.tinymce.com/9Jgaab/1

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
Please note the official support window for TinyMCE 4 is ending on December 31, 2020. If you haven't already upgraded to TinyMCE 5 it is highly encouraged that you do so. Upgrading will give you access to the latest releases and updates made to our WYSIWYG editor focused on bringing the latest UX and developer features into the editing experience. To assist with upgrading the editor we have put together a migration guide you can use here - https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
