### ISSUE TITLE
onBlur event does not trigger on mobile

### ISSUE THREAD

**Issue by safinazward** [tinymce/tinymce#5035]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The onblur event does not trigger when we touch outside the editor.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/SJgaab/1
**What is the expected behavior?**
trigger onBlue
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
It is not working with all versions.
Note: if I set the option inline:true the bug is not there and the blur event is triggering on mobile

**Comment by thedrjim** [comment]
This issue has been closed as it refers to the mobile theme that was deprecated in TinyMCE 5.1, as the default theme was extended to support both desktop and mobile. The TinyMCE documentation contains more information about the old mobile theme https://www.tiny.cloud/docs/mobile/#thelegacymobiletheme and the settings for the new mobile support https://www.tiny.cloud/docs/mobile/ . Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.
There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all. Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.
If this issue is still relevant, please re-open this issue or create a new one.
If you have any questions or concerns, you can contact me at community-qa@tiny.cloud. You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud.
