### ISSUE TITLE
Version 5.0.8 - SpellChecker Plugin - Always says No misspellings found

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#5045]
Hello, I'm using TinyMCE 4.9.4 in my server and now I'm currently testing the TinyMCE 5.0.8 version and I noticed that the SpellChecker plugin doesn't seem to work anymore. It always says 'No misspellings found'. I double checked that in both versions, the 4.9.4 and 5.0.8 version, the data that TinymCE sends to the server (with the text of the document) and the data that TinyMCE gets from it as a result (with the misspelled words) are the same. So that's why I was thinking that it could be an issue with the new version of the plugin.

EDIT: I found the source of this issue. Adding the conditional of the suggestions variable that was available in 4.9.4 makes the spellchecker to work properly again.

NOW IN 5.0.8 (NOT WORKING)
```
var suggestions = data.words;
```

BEFORE IN 4.9.4 (WORKING)
```
if (typeof data !== 'string' && data.words) {
   suggestions = data.words;
   } else {
   suggestions = data;
}
```

**Comment by lnewson** [comment]
@lrusso I checked with the team and this is intentional as the old version without `words` was the legacy format and had been deprecated, so it was removed in TinyMCE 5.0. As you'll see in https://www.tiny.cloud/docs/plugins/spellchecker/#spellchecker_callback the service/callback now must return an object containing the `words` to use as suggestions.

Also it appears this was missed in the migration guide sorry, so I'll log an internal ticket to get that added.
