### ISSUE TITLE
Inappropriate text 'Paragraph' for 'styleselect' toolbar control

### ISSUE THREAD

**Issue by mkemmerling** [tinymce/tinymce#5089]
**What is the current behavior? Describe the bug**

Both, the 'formatselect' and 'styleselect' toolbar controls have the same text, 'Paragraph'. While this is ok for block level elements it seems to restrictive for general styles.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

See the [Custom formats example](https://www.tiny.cloud/docs/demo/format-custom/).

**What is the expected behavior?**

The text 'Formats' for the  'styleselect' control as in TinyMCE 4. The tooltip is already set to 'Formats'.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

5.0.12

**Comment by wonderbugtiny** [comment]
Hi @mkemmerling! Thanks for the report. I have logged a ticket internally for us to change the default text for the `styleselect` dropdown to be `Formats`. We will update you when the fix is available.

**Comment by wonderbugtiny** [comment]
Hi @mkemmerling, while both `styleselect` and `formatselect` do have the same initial labels, it is not intended that they are used together, because `style_format` can do everything `block_format` can (and more).

Here's some information about setting up block styles using style_format:
https://www.tiny.cloud/docs/general-configuration-guide/filter-content/#rollyourstyleformats
Please let us know if you have any other questions. Thank you!
