### ISSUE TITLE
TinyMCE 4.0.20. Editor removes <span> and <i> Tags and their content inscribed in them.

### ISSUE THREAD

**Issue by LanghaniKuldeep** [tinymce/tinymce#5103]
**What is the current behavior? Describe the bug**
Whenever I add `span` or `i` tag in the editor, It removes those `span` and `i` tags. I tried putting them in extended_valid_elements using init method. But it keeps span but removes all the inner content and `*[*]` which should work as the wild card but it is not working altogether. 

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/rOgaab/2
I added font awesome list with icons from this 
https://fontawesome.com/how-to-use/on-the-web/styling/icons-in-a-list

**What is the expected behavior?**
it shouldn't remove `span` and `i` tags.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 4.x

**Comment by LanghaniKuldeep** [comment]
So I fixed that by using `extended_valid_elements : 'i[class],span[class]',` in the configuration. But there should be a fix for that instead of using `extended_valid_elements` like a patch

**Comment by ltrouton** [comment]
Hi @LanghaniKuldeep. Just to clarify. The reason why the <i> tags are being removed is that TinyMCE by default does not support the `i` tag as it is considered a legacy tag. As a result, they are filtered out. This is also why the `span` tags are filtered out since they don’t have any valid content within them. Using the [legacyoutput](https://www.tiny.cloud/docs/plugins/legacyoutput/) plugin allows `i` tags to be used without adding it to `extended_valid_elements` but bear in mind that it does severely limit the functionality of the editor (Note: Legacyoutput works from 4.0.28 onwards). The way you are using `extended_valid_elements` is a possible solution. However, it should be noted that we do not recommend using the `i` tag since, it does not produce valid HTML5 and you may get some undesirable behaviour as this is something the editor does not natively support.

**Comment by TheSpyder** [comment]
> This is also why the `span` tags are filtered out since they don’t have any valid content within them.

To expand on this for a moment, if the `i` elements are retained the `span` tags also will be. So technically `extended_valid_elements : 'i[class]'` is all that is required. But switching from `i` to `em` is our recommended solution.
http://fiddle.tinymce.com/rOgaab/4
