### ISSUE TITLE
Icon not showing on addSplitButton's choiceitem

### ISSUE THREAD

**Issue by ClaudioFuriniJr** [tinymce/tinymce#5113]
**What is the current behavior? Describe the bug**

I'm trying to create a split button on my toolbar. I wish my choiceitem to have an icon, but the icon is not showing.

http://fiddle.tinymce.com/QOgaab

```
            setup: (editor) => {
              editor.ui.registry.addSplitButton('myButton', {
                icon: 'bold',
                tooltip: 'Bold',
                onAction: () => editor.execCommand('mceToggleFormat', false, 'bold'),
                onItemAction: (api) => editor.execCommand('mceToggleFormat', false, 'strikethrough'),
                fetch: (callback) => {
                  var items = [
                    {
                      type: 'choiceitem',
                      icon: 'bold',
                    },
                  ];
                  callback(items);
                }
              });
            },
```

![icon](https://user-images.githubusercontent.com/25485457/63051990-b74a4780-beb4-11e9-8857-9a7c0accbcd8.png)

**Comment by lnewson** [comment]
I've labelled this as a feature request, because we currently don't have a way of showing both the "checkmark" icon to show which choice is selected and regular icons. So we'd likely need to look at a way to redesign the menus to be able to show both the icon and selected item.

I should add if you don't need it to be a split button, then you might be able to use a menu button instead: http://fiddle.tinymce.com/QOgaab/1

**Comment by ClaudioFuriniJr** [comment]
Got it.
Thank you

**Comment by lnewson** [comment]
This has been added in TinyMCE 5.3.0, which was released to the community earlier today. The checkmark icon has now been moved to the right-hand side of the menu, allowing for icons to be displayed for toggle and choice menu items. Please let us know if you have any further issues.
