### ISSUE TITLE
Prevent tinyMCE from transforming self-closing tags into "standard" ones ?

### ISSUE THREAD

**Issue by arnaudbey** [tinymce/tinymce#5134]
Hey there, 
I'm using the 5.0.13 version, and I can't find a way to prevent tiny from replacing self closing XML tags like `<lb />` ( https://tei-c.org/release/doc/tei-p5-doc/fr/html/examples-lb.html ) by `<lb></lb>`. Is it possible ?
Thanks a lot !

**Comment by lnewson** [comment]
Sorry @arnaudbey that this wasn't answered until now, but yes this is possible though it's not the easiest to setup. Additionally its generally not supported since TinyMCE is a WYSIWYG HTML editor, so it's not really designed to edit XML based content, so your results may vary.

However, if you do still want to go ahead with this, here's a fiddle to show you could do this: http://fiddle.tinymce.com/ehhaab another option that might work would be to use the [`protect`](https://www.tiny.cloud/docs/configure/content-filtering/#protect) setting.

**Comment by arnaudbey** [comment]
hey there. no problem for the late answer :)
I'll have a look on this as soon as I can get back to work ! Thanks for your time :+1:

**Comment by liesahead** [comment]
Based on the example of @lnewson I went with this one to enable self-closing ability for all elements. Not sure if it's very safe and correct, but it's currently the best way I found.

```ts
setup: (editor) => {
    editor.on('PreInit', () => {
        const shortEndedElements = editor.schema.getShortEndedElements();

        if (shortEndedElements) {
            for (const tagName of Object.keys(editor.schema.children)) {
                shortEndedElements[tagName] = {};
                shortEndedElements[tagName.toUpperCase()] = {};
            }
        }
    });
},
```
