### ISSUE TITLE
Issue with NonBreaking Space in special charecters (Tinymcev5 )

### ISSUE THREAD

**Issue by srimoyeesen** [tinymce/tinymce#5138]
On selecting a non breaking space from the special characters list (charmap plugin) and then adding any text after it, Tinymce is converting that non breaking space (&nbsp;)  to a normal space.

There is no difference between normal space and non breaking space in that case. Please help resolving this issue 

For Tinymcev5

**Comment by wonderbugtiny** [comment]
@srimoyeesen Nonbreaking Space isn't included as an option in the Special Characters dialog by default in TinyMCE v5. If you are adding the option to the Special Characters dialog as part of your custom configuration, we would recommend that use the Nonbreaking Space plugin instead: https://www.tiny.cloud/docs/plugins/nonbreaking/. Please let us know if you have any other questions. Thank you!

**Comment by nishtha18mittal** [comment]
I am using Nonbreaking Space plugin, and facing the same issue, even though I have used nonbreaking_wrap option for wrapping non-breaking space (&nbsp;) but it does not work for below version of TinyMCE 5.0.13. Is there any way to prevent the non-breaking space (&nbsp;) being replaced by the editor or browser when typing additional spaces or any character in TinyMCE 5.0.5 or prior versions

**Comment by wonderbugtiny** [comment]
@nishtha18mittal Sorry, the `nonbreaking_wrap` option was an [improvement](https://www.tiny.cloud/docs/changelog/#version5013august62019) to the Nonbreaking Space plugin implemented in TinyMCE version 5.0.13. So, it is only available in versions 5.0.13 and above.

**Comment by srimoyeesen** [comment]
Hi,
If I type space from my keyboard and then check - **tinymce.activeEditor.getBody();**   ,  there is an `<p>&nbsp;</p>` inside it. Same happens when I add a non breaking space using the plugin. So my question is - How does tinymce differentiate between normal space and a non breaking space?

**Comment by wonderbugtiny** [comment]
By default, a `&nbsp;` is added when a space is inserted at the beginning or end of a line of text. `&nbsp;`s are also inserted whenever there are two or more spaces in between text content. This is done to preserve the spaces that would otherwise be removed by the browsers while rendering. Browsers collapse two or more regular spaces into a single space when rendering. The single spaces inserted within a line of text would remain a regular space unless a non-breaking space is inserted by the user. This is regular browser behaviour within contentEditable elements.
Hope this answers your question. Please let us know if you have any other questions or concerns. Thank you!
