### ISSUE TITLE
How can I add Custom Plugin to tinymce.v4

### ISSUE THREAD

**Issue by OmdaMukhtar** [tinymce/tinymce#5142]
I am using tinymce version4 with vue js , after i follow tinymce [official documentations](https://www.tiny.cloud/docs/advanced/creating-a-plugin/) and implementd in my project i get error ```field to load "../plugins/example/plugin.js"```

so here is my code 
```
<template>
    <div class="container">
        <h2 class="">Tinymce-Vue</h2>
        <editor id="app-editor" 
                api-key="jh5j9j89wyv5mbctvucc67e0o5ba3q7v4xkldjfoaqv74glt" 
                :init="inital" 
                v-model="content">
        </editor>
    </div>
</template>

<script>
import editor from '@tinymce/tinymce-vue';
import tinymceConfig from './config/tinymce';

export default {
    data(){
        return {
            content: '',
        }
    },
    components: {
        editor
    },
    computed: {
        inital(){
            return tinymceConfig.config;
        }
    }
}
</script>
```

and ```config.js ```file look like so ..
```
const config = {
    select: "#app-editor",
    plugins:"wordcount  example",
    toolbar1: "wordcount |  example",
    external_plugins: {
        example: "../plugins/example/plugin.js",
    },
}

export default {config};
```

and ```plugin.js``` file also look like so : 
```
tinymce.create('tinymce.plugins.
   init: function(editor, url) {
            editor.addButton( 'example', {
    text: 'example',
    icon: false,
    type: 'menubutton',
    menu: [
          {
           text: 'Menu 1',
           onclick:function() {
                 alert("I am Menu 1);
               }
           },
          {
           text: 'Menu 2',
           onclick:  function() {
                  alert("I am Menu 2);
               }
          }
          ]
 });
   },
      
   createControl: function() {
          return null
   },
      
tinymce.PluginManager.add('example', tinymce.plugins.example)
```

so how to fix it...

**Comment by lnewson** [comment]
@OmdaMukhtar your plugin.js is quite different to the example provided in the [documentation](https://www.tiny.cloud/docs-4x/advanced/creating-a-plugin/#exampleplugin) as you appear to be trying to use `tinymce.create` for some reason?

I'd suggest reviewing the docs again, particularly the one I linked above since it's v4 specific. If you can't get it working after that, then could you please provide a [fiddle](http://fiddle.tinymce.com/) (or something similar) with your code? To get you started, here's the example from the docs setup in fiddle: http://fiddle.tinymce.com/UPgaab

**Comment by lnewson** [comment]
I should also add if you're getting `field to load "../plugins/example/plugin.js"` then that indicates that you either haven't deployed the plugin properly or your path/URL specified in `external_plugins` is incorrect, as it means it can't load the script from that URL.

**Comment by OmdaMukhtar** [comment]
@Inewson your are right, i am a little bit confused with stuff of how to add plugin into tinymce, I thought creator of tinymce they miss something and don't complete documentation,  as you know tinymce has offer , so I searching for another place to find out and fix my issue. 

so now my issue is not related with tinymce doc's  !

okay, i need to ask you why they use ```external_plugins: {}```, cause i don't see documentation about this functions .

**Comment by lnewson** [comment]
@OmdaMukhtar the docs for external plugins is here: https://www.tiny.cloud/docs-4x/configure/integration-and-setup/#external_plugins The purpose of it is when you want to load a plugin that's outside the normal `plugins` directory or when it isn't bundled as part of your application. Custom plugins generally fall into this category, which is why you've probably seen it suggested before.

**Comment by OmdaMukhtar** [comment]
Thank you very much @lnewson to help me understand this issue as I expected.
