### ISSUE TITLE
Copy gives extra line break instead of native behaviour

### ISSUE THREAD

**Issue by versusvirus** [tinymce/tinymce#5158]
**What is the current behavior? Describe the bug**
See the gif:
Incorrect behaviour when user select the start of the line, then put ctrl+x, after then paste it at the end of the line.
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
See the gif
**What is the expected behavior?**
Native behaviour
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5.0 Chrome 76
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/33262949/64682100-8a745a80-d489-11e9-9d7d-275c1ab68307.gif)

**Comment by ltrouton** [comment]
Whilst we try to make the editor as similar to native as possible, we need to handle interactions in a way that enables efficient functioning of the editor. As a result, this is expected behaviour. It should be noted that Microsoft Word also appears to have the same behaviour. Let us know if you have any other questions.
