### ISSUE TITLE
Using Spring resource caching for scripts TinyMCE breaks in IE11

### ISSUE THREAD

**Issue by fcolmenarez** [tinymce/tinymce#5160]
**What is the current behavior? Describe the bug**
When we use Spring to enable caching of scripts the framework changes the names of the scripts. 

Ex: tinymce.min-7d3b401d5e17dfd16d76cf31a6bb2fc8.js

As a consequence TinyMCE no longer recognizes them and fails to set the basicURL property properly and relies on a fallback mechanism that works for other browsers but not IE11.

This is the part of the code that breaks:
```
        preInit = window.tinymce || window.tinyMCEPreInit;
        if (preInit) {
          baseURL = preInit.base || preInit.baseURL;
          suffix = preInit.suffix;
        } else {
          var scripts = domGlobals.document.getElementsByTagName('script');
          for (var i = 0; i < scripts.length; i++) {
            src = scripts[i].src;
            var srcScript = src.substring(src.lastIndexOf('/'));
            if (/tinymce(\.full|\.jquery|)(\.min|\.dev|)\.js/.test(src)) {
              if (srcScript.indexOf('.min') !== -1) {
                suffix = '.min';
              }
              baseURL = src.substring(0, src.lastIndexOf('/'));
              break;
            }
          }
          if (!baseURL && domGlobals.document.currentScript) {
            src = domGlobals.document.currentScript.src;
            if (src.indexOf('.min') !== -1) {
              suffix = '.min';
            }
            baseURL = src.substring(0, src.lastIndexOf('/'));
          }
        }
```
The specific line is the test:
`            if (/tinymce(\.full|\.jquery|)(\.min|\.dev|)\.js/.test(src)) {
`
Cached names fail this test.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
In your spring-servlet.xml add mapping behavior similar to this:
```
	<mvc:resources mapping="/js/**" location="classpath:/public/js/">
		<mvc:cache-control max-age="31536000" cache-public="true"/>
		<mvc:resource-chain resource-cache="false">
			<mvc:resolvers>
				<mvc:version-resolver>
					<mvc:content-version-strategy patterns="/**"/>
				</mvc:version-resolver>
			</mvc:resolvers>
		</mvc:resource-chain>
	</mvc:resources>
```
**What is the expected behavior?**
TinyMCE should be able to accept script names that have cached designations attached to them. The current test is far too restrictive.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
All versions of TinyMCE

Related to this, as the fallback doesn't work in IE11 as explained here: https://github.com/tinymce/tinymce/issues/3584

**Comment by lnewson** [comment]
Unfortunately, there's not a lot we can do here, as we can only support a fixed set of names because if `document.currentScript` isn't supported then we need to look over every script tag to try and find the right one and trying to match every possible variation just isn't feasible. Additionally, dynamic file names will never work with TinyMCE, as the suffix needs to be the same across all resources being loaded (eg plugins, css, etc...).

As such we'd suggest using a cache busting strategy that doesn't alter filenames and instead adds a query parameter or something similar. Either that or you'll need to manually set the base url and suffix either via the `window.tinyMCEPreInit` or [`base_url`](https://www.tiny.cloud/docs/configure/integration-and-setup/#base_url) and [`suffix`](https://www.tiny.cloud/docs/configure/integration-and-setup/#suffix) init settings.

Another option is the [`cache_suffix`](https://www.tiny.cloud/docs/configure/integration-and-setup/#cache_suffix) configuration setting supported by TinyMCE which will add a query parameter to provide cache busting capabilities.
