### ISSUE TITLE
Missing attributes on iframe added as content

### ISSUE THREAD

**Issue by eschiebel** [tinymce/tinymce#5181]
**What is the current behavior? Describe the bug**
When adding an iframe as content, attributes explicitly permitted via valid_elements or extended_valid_elements are removed from the element. Though the attributes are notated on the span tinymce adds as the iframe's parent and appear in the saved output, they are not on the iframe w/in the editor.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/6Rgaab

**What is the expected behavior?**
on inspecting the iframe in devtools, it should have the id, data-foo, allow, and title attributes.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinymce-cloud-stable, macos, chrome, firefox, and safari

**Comment by ltrouton** [comment]
Thanks for posting. The parent span is how TinyMCE manages iframes in the editor and it is expected that not all attributes will appear directly on the iframe. As you noted, when the content is saved, the iframe does include all of the attributes. This can also be confirmed by opening the source code view or retrieving editor content by `tinyMCE.activeEditor.getContent()`. 

Closing this ticket as expected behaviour is occurring. Let us know if you have any other issues.
