### ISSUE TITLE
A posisbility to add context toolbar to the desired HTML element

### ISSUE THREAD

**Issue by mrpsiho** [tinymce/tinymce#5182]
**Is your feature request related to a problem? Please describe.**
At the moment it is not obvious (not possible?) how to add context toolbar to, let's say, div with a certain class withing the editor area. I would like to add more editing possibilities to my users, but I cannot do that.

**Describe the solution you'd like**
Probably the solution would be that 'addContextToolbar' uses CSS selector and targets the specific element.
Or 'items' (toolbar buttons) could be set dynamically.

**Describe alternatives you've considered**
Cannot do anything.

**Comment by lnewson** [comment]
This is already possible, as the context toolbar takes in a predicate so you can lookup whatever you want from the predicate function. Here's a fiddle I created quickly to show how this could be done in combination with the TinyMCE dom API: http://fiddle.tinymce.com/ARgaab

One thing to remember though, is that since it's a context toolbar you can't just give it a list of nodes or a CSS selector, since it's activated based on the current selection. That means it needs to search up the dom tree, instead of downwards like a CSS selector would normally do. It also needs to take into consideration that you might have only selected a bit of text so the selection would be on a text node, which is why in my example I used the `editor.dom.getParent()` API.

**Comment by mrpsiho** [comment]
No, sorry, but it does not work like that. I am going to explain it better. Currently I have 'gallery' block and would like to display context toolbar on whole gallery selection, not its individual parts, like images or links which wrap images. But I cannot.

I have modified 'imageselection' toolbar, now it targets specific images only:
```
editor.target.ui.registry.addContextToolbar('imageselection', {
            predicate: function(node) {
                return node.nodeName === 'IMG' && /wp-image/i.test(node.className);
            },
            items:     'alignleft aligncenter alignright fdm_img_edit fdm_img_remove',
            position:  'node',
            scope:     'node'
        });
```

And I am using this code for gallery selection:
```
editor.target.ui.registry.addContextToolbar('galleryselection', {
            predicate: function(node) {
                if (!R.isNil(node.closest)) {
                    const parent = node.closest('div');

                    if (parent && R.includes('shortcodeGallery__item', [...parent.classList])) {
                        return true;
                    }
                    return false;
                }
                return false;
            },
            items:     'fdm_gallery_edit',
            position:  'node',
            scope: 'node'
        });
```
But this my toolbar never fires. It displays toolbars for either text selection or link selection. Probably their predicates fire earlier than this one mine.

Actually any custom element in the editor consists of text and/or links, so their toolbars will take precedence all the time. This is the problem.

What could be a solution?

**Comment by lnewson** [comment]
At this point we'll need a basic replication case in [fiddle](http://fiddle.tinymce.com) or something similar to be able to help, as our table context toolbar does effectively what you're talking about (eg it shows on the table when a cell is selected): https://github.com/tinymce/tinymce/blob/master/modules/tinymce/src/plugins/table/main/ts/ui/Buttons.ts#L143

One thing that you haven't mentioned previously, but based on the above comments, do you have the quickbars plugin enabled? As that will cause the text selection toolbar to be shown instead of other context toolbars if a selection is made, as atm we only allow one toolbar to be shown at a time. That is documented as something to be aware of in this section of the docs: https://www.tiny.cloud/docs/ui-components/contexttoolbar/#contexttoolbarpriority

**Comment by mrpsiho** [comment]
Yes, I do have 'quickbars'. I am aware of that section in the docs. This is why one of my feature proposal was to make 'items' to be set dynamically.

The only solution I know can be used just now is to re define all context toolbars used. Basically, they will be the same, just with an additional check for existing of parent 'div' wit ha certain class. I can do that for 'textselection', but I do not know toolbars' names and which items are used in context toolbars added by 'link' and/or 'autolink' plugins. Could you suggest here? Or maybe you could suggest other solutions?
