### ISSUE TITLE
Tooltip on Custom Button not getting displayed

### ISSUE THREAD

**Issue by milap1296** [tinymce/tinymce#5210]
**What is the current behavior? Describe the bug**
It is mentioned in the [tinymce docs](https://www.tiny.cloud/docs/ui-components/typesoftoolbarbuttons/#togglebuttonexampleandexplanation) that tooltip for buttons should work correctly but it is not getting displayed as expected.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
[Codepen link](https://codepen.io/milap1296/pen/KKKzdRW?editors=0010) for the same.

**What is the expected behavior?**
Tooltip option should show the correct tooltip.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE version - 5.0.14.
This worked perfectly fine in 4.9.3.

Thanks, Please lemme know if I am doing something wrong / is there any workaround for it.

**Comment by lnewson** [comment]
@milap1296 can you include a video or something to show your issue, as the codepen worked fine here on Chrome/Firefox?

I should note though, that we've yet to implement proper custom tooltips, so at this stage the tooltip is placed in the `title` attribute and therefore it'll be the browser tooltip that appears instead of the custom one as in v4. We still have the custom tooltip feature in our backlog, but unfortunately it hasn't been scheduled yet.

**Comment by milap1296** [comment]
@lnewson as you can see in the screenshot I have been opening it in chrome version 77.0, but I can't see any tooltip though it's seen in the html.
<img width="1678" alt="customTooltip" src="https://user-images.githubusercontent.com/19545730/66903259-c74ee680-f01f-11e9-9262-441dacc26c52.png">
Do you still need a video for confirmation or is it fine ?

**Comment by cfconsultancy** [comment]
I can confirm that in Chrome  77.0.3865.120 tooltips disapear (title), in firefox and IE 11 it shows the title

**Comment by lnewson** [comment]
I'm unable to reproduce this using the version of Chrome mentioned on Mac OSX or on Windows 10. However since this appears to be a browser issue and not a TinyMCE issue, I'd suggest first trying in an incognito window to make sure it's not a browser extension and if it still fails then log a bug against Chrome.

I did manage to find https://bugs.chromium.org/p/chromium/issues/detail?id=1006738 logged against Chrome already, which seems to be similar to the issue mentioned here, but the chrome developers couldn't reproduce the issue either.
