### ISSUE TITLE
More... button is missing on tablet when mobile is set to silver tiny 5.1.0

### ISSUE THREAD

**Issue by cfconsultancy** [tinymce/tinymce#5211]
First, thx for this nwe version

More... button is missing on tablet when mobile is set to silver
Affected by all browsers
`mobile: {
  theme: 'silver',
},
Desktop 
![desktop](https://user-images.githubusercontent.com/1576475/67141136-d40e4d00-f260-11e9-9c4b-02ff59580f68.jpg)

Tablet (android chrome)
![tablet](https://user-images.githubusercontent.com/1576475/67141117-b17c3400-f260-11e9-9bef-d13dcfa1efb6.jpg)

**Comment by lnewson** [comment]
This is expected, as mobile devices will now use a scrolling toolbar by default. If you want the old behaviour back, add the `toolbar_drawer` setting to your mobile configuration. eg:

```
tinymce.init({
  ...
  mobile: {
    theme: 'silver',
    toolbar_drawer: 'floating'
  }
});
```

If you wanted to to only apply to tablets, instead of phones, then you could do something like this:

```
tinymce.init({
  ...
  mobile: {
    theme: 'silver',
    toolbar_drawer: tinymce.Env.deviceType.isTablet() ? 'floating' : false
  }
});
```

I should also note, that the `theme: 'silver'` mobile configuration should no longer be needed, as silver is now the default theme on mobile in 5.1.

**Comment by cfconsultancy** [comment]
Great, but I am sorry to inform that this is not working, it still gives the scrolling toolbar

`selector: 'textarea.editme',
mobile: {
  theme: 'silver',
  toolbar_drawer: 'floating'
},
width: '100%',
height: 470,`

This however works toolbar_drawer: tinymce.Env.deviceType.isTablet() ? 'floating' : false

**Comment by lnewson** [comment]
It sounds as though you got this sorted in the end, so I'm going to close this. If you're still having any issue let me know and I'll re-open it.
