### ISSUE TITLE
Insert new paragraph after custom tag in TinyMCE

### ISSUE THREAD

**Issue by srimoyeesen** [tinymce/tinymce#5214]
I've got a small TinyMCE plugin that takes selected text and wraps it in `<ixbrl></ixbrl>` tags. It works as expected, however, when I start a new line after a line with `<ixbrl></ixbrl>` a new xbrltag is created in that line automatically. I'd like to override this behaviour and get a `<p></p>` in that line instead.

**Comment by ltrouton** [comment]
The `newblock` event could be used  to update/change the custom element back into a `p`. Alternatively, can the custom tag always be inline with a `p` block? That should resolve the issue. 

If these suggestions do not solve your issue, we will need a [Fiddle](http://fiddle.tinymce.com/baaaab) with a config that allows the issue to reproduced so that we can investigate further.

**Comment by lnewson** [comment]
Closing this as we haven't heard back from you if the above suggestion worked. If you're still having issues let us know and we'll reopen this issue. Please be sure to include the requested additional information though if you are still experiencing issues.
