### ISSUE TITLE
mobile friendly is not touchscreen-enabled laptop friendly

### ISSUE THREAD

**Issue by ampthelectrifing** [tinymce/tinymce#5217]
I thought it was a bug at first that not all the plugins were showing up and that I couldn't use my mouse to interact with the menu or toolbar, until I realized that it was treating my touchscreen laptop as a mobile device. Mobile responsiveness should be a feature you can disable, or it should be able to respond to mouse input alongside touch input. Or both probably lol

**Comment by lnewson** [comment]
@ampthelectrifing which version of TinyMCE are you using? As this largely shouldn't occur in TinyMCE 5.1 and it should be more friendly to touch devices. In saying that though, it'll still treat a touch device as a mobile device and therefore apply settings/defaults for a tablet I believe.

**Comment by ampthelectrifing** [comment]
I was using 5.1, though I've currently downgraded to 4.9 so I could use a different theme, and that worked for me. Even if I had been able to click though, in the docs it does say that mobile version limits the plugins and toolbar options, which seems silly when my device doesn't need the kind of optimization phones do.

**Comment by sontek** [comment]
My users are complaining about this as well (they use microsoft surfaces) and it is a terrible experience for them.   The mobile code also seems much buggier than the desktop code because anyone on a surface currently can't use our product anymore:

https://github.com/tinymce/tinymce/issues/5226

I'd love the ability to tell it to just work the same way everywhere (this is how its been and worked well for us before upgrading)

**Comment by lnewson** [comment]
@ampthelectrifing TinyMCE 5.1 doesn't limit the plugins when using the `silver` theme, it'll only limit them when using the older `mobile` theme. The docs haven't been updated for that yet sorry, since the docs represent the enterprise version of TinyMCE which is still using 5.0.x. In saying that though, in the upcoming 5.1.2 release we're changing when the mobile overrides activate, so it will no longer activate on desktop touch devices.

**Comment by lnewson** [comment]
TinyMCE 5.1.2 was released earlier today which should improve this since a touch device is no longer treated as a mobile device. @ampthelectrifing could you confirm if you're still experiencing this issue with 5.1.2?

**Comment by lnewson** [comment]
Closing this as we haven't heard back from you if TinyMCE 5.1.2 solved this. If you're still having issues let us know and we'll reopen this issue.
