### ISSUE TITLE
Uploading images to server only on submission

### ISSUE THREAD

**Issue by hjb1694** [tinymce/tinymce#5222]
**Is your feature request related to a problem? Please describe.**
I am wanting to upload images only when a user submits the form, not during the insertion of the image into the editor. 

**Describe the solution you'd like**
I would like to upload the images to the server only when the user submits the form.

**Describe alternatives you've considered**
I thought about adding an image input without using the editor.

**Comment by BakytzhanBektugan** [comment]
Hello! I think this applies not only to images but also to videos and files. I struggled with this problem for a while: Tinymce allows you to upload images, files and videos via ajax. And if after that you, when editing the text, want to delete the downloaded files / video / image it will not work. There are no handlers for this. You have to manually dig into the server and delete the file. And if you don’t delete the file and just remove the link to it from the html markup, then after a while your server will fill up with garbage.
I tried to solve this problem through MutationObservers, but since tinymce is added to the page through an iframe this cannot be done because you cannot bypass the cross domain policy. Because of this, you will not be able to see the changes inside the tinymce editor.
This big problem can be solved in another way, as you said simply by downloading the media data after the final confirmation of the user.
Thank you, if someone like me wants to solve this problem, then write to bakytzhan.bektugan@gmail.com.
It’s just that the froala editor has already decided all this, but it’s paid. It would be great if Tinymce also added this feature.

**Comment by Afraithe** [comment]
If you configure automatic_uploads to false, you can then trigger editor.uploadImages() manually when you save the contents, that should only give you wants actually being saved.

**Comment by lnewson** [comment]
Looks like this has been answered above, so I'm going to close this. If you're still having issues however, then let us know and we'll reopen this issue.
