### ISSUE TITLE
The Alt + Shift + M hotkey

### ISSUE THREAD

**Issue by ajtruckle** [tinymce/tinymce#5223]
![TinyMCE-Shortcuts](https://user-images.githubusercontent.com/7985331/67972123-f6f81400-fc05-11e9-9ecb-f42f6e0bf474.png)

I noticed that the advertised ALT + SHIFT + M was not working for insert image, Then I noticed looking at the help popup that the hotkey is for two features. Insert Image and Add Media.

Well, on my WordPress site I do not have the Add Media button visible and all I have is the Insert Image which simply displays the image from a given URL.

Either way, this hotkey does not function.

I am using latest wordpress 5.2.4 and the latest bbp style pack (for bbpress) that had an open to display the tiny mce editor for adding/removing topics.

But this hotkey won't work for me.

**Comment by lnewson** [comment]
TinyMCE doesn't provide any shortcuts for the image, nor media plugin by default so this is like any issue with wordpress or wordpress plugin you're using. Since there is nothing we can do to fix the issue, I'm going to close this and suggest you log an issue with wordpress or wordpress plugin directly.
