### ISSUE TITLE
Small table menu usability issues

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#5229]
In TinyMCE 5.1 when you click on the Table button, rollover menu appears.

1. Cell, Row, Column items should be de-activated because all respective submenu items are inactive.
2. Table properties and Delete items are inactive, but when you use TAB key you'll notice that to jump from Table to Cell you have to press TAB three times. So, it looks like inactive items receive focus, although it's not visible.

**Comment by lnewson** [comment]
For 1) that is expected behaviour, as it allows users to be able to see what options are there even if they aren't able to click them, which is useful for accessibility purposes. As for 2) that is a CSS bug, as the menu items should be navigable for accessibility but they should be showing a greyish background to show the item is focused. I'll log an internal ticket to get that fixed.

**Comment by lnewson** [comment]
TinyMCE 5.1.3 has just been released to community with a fix for the disabled menu items not displaying a background colour when they are focused (point 2).
