### ISSUE TITLE
Fullscreen plugin - elements visible

### ISSUE THREAD

**Issue by ajtruckle** [tinymce/tinymce#5231]
i installed the fullscreen plugin.

I see some website elements still visible.

TinyMCE v4.9.4 on WordPress

![3895905A-554B-458B-84F8-49CCB1CA057C](https://user-images.githubusercontent.com/7985331/68092878-a5f75280-fe87-11e9-8d65-25a28bfabdd5.png)

Also have it on SO:

https://stackoverflow.com/questions/58691700/tinymce-full-screen-mode-in-wordpress-and-obscuring-elements

**Comment by ajtruckle** [comment]
Also have it on SO:

https://stackoverflow.com/questions/58691700/tinymce-full-screen-mode-in-wordpress-and-obscuring-elements

**Comment by lnewson** [comment]
@ajtruckle that looks like an integration issue, as TinyMCE will try and use a fairly high z-index but if something on your site uses a higher z-index then it will still display in front of TinyMCE and there's not much we can do about that, so it's something that would need fixing on your site. You might be able to work around it by overriding the `mce-fullscreen` class and increase the z-index so that TinyMCE uses a value higher than whatever is showing in front of TinyMCE.

**Comment by ajtruckle** [comment]
It seems that the navigation bar uses 99999 so I set the z-index of the fullscreen to 600000 and it did not affect it.
