### ISSUE TITLE
Colour Picker not working

### ISSUE THREAD

**Issue by ajtruckle** [tinymce/tinymce#5236]
Not sure where to turn to here because the v4 full demo is fine. But in my editor:

![Colour](https://user-images.githubusercontent.com/7985331/68125978-ab49b100-ff0a-11e9-8f52-7b7bd7c36ea7.png)

Anywhere the above dialog is displayed I can't click on the colours at all, So I can't scale the colour. The colourpicker plugin is the one installed with wordpress.

**Comment by ajtruckle** [comment]
Duplicate of https://github.com/tinymce/tinymce/issues/3248 I think.

**Comment by lostkeys** [comment]
Do other dialogs work or is it just the color picker that doesn't work. Can you enter values in the R, B or G input field?

As I said in another issue you submitted it's almost impossible for us to test this as the host app could do all sorts of weird things to TinyMCE that we have no control over. So if something is working in our demos, but not when it's implemented in a third party service, it's equally likely an issue with their implementation of TinyMCE. Now, that said, it's in our interest to provide developers with a robust editor plugin, but in order to debug what's going on, we kind of have to rely on an experienced developer from that third party app to figure out what is going on.

**Comment by ajtruckle** [comment]
Just the colour picker window from what I can tell.

I add some feedback on the linked ticket.

In normal zoom view the left property is set to the correct % across the palette etc. But the top property is permanently set to 100%.

In full zoom mode I can use the dialog but the mouse has to be offset from the +.

**Comment by ajtruckle** [comment]
This was resolved by my WordPress theme host provider a long time ago.
