### ISSUE TITLE
Image plugin tabs ordering

### ISSUE THREAD

**Issue by francoisfreitag** [tinymce/tinymce#5239]
**Is your feature request related to a problem? Please describe.**
In my use case, users are expected to upload images more often than they link to external resources. The image dialog would be more useful to them if it offered to upload a local resource when adding an image. Defaulting to the General tab otherwise is fine.

The default tabs ordering is, top to bottom: General, Advanced, Upload.

**Describe the solution you'd like**
Either solution would solve my problem.

*Default to the Upload tab*
When the plugin is configured to allow upload, make the Upload tab the default active tab when opening the image dialog.

*Configure image tabs ordering*
A new boolean setting in the Image plugin (`upload_tab_first`?) would allow:
- `true`: place the Upload tab on top and make it the active tab when users open the image dialog,
- `false`, the default for backward compatibility, place the General tab first.

In all cases, the Advanced tab can be the last tab, because the General tab must be filled first (either by linking to an external resource or uploading an image).

**Current image dialog**
![Current state screenshot](https://user-images.githubusercontent.com/2758243/68202156-1226a300-ffbb-11e9-99a9-7009f082b358.png)

**Upload tab first**
![Suggested state screenshot](https://user-images.githubusercontent.com/2758243/68202170-15ba2a00-ffbb-11e9-9cd9-27cfdd9de6f3.png)

**Comment by lostkeys** [comment]
To be honest, we would probably get to that level of configuration. If you really want this it's possible to change the visual order with CSS using the `order` declaration since the container is flex. But it's not supported and we do not recommend it as we on (rare) occasions have to change the HTML and class names, possibly breaking your code. But if you know what you are doing it's probably ok.
