### ISSUE TITLE
Using <kbd> tags in a post?

### ISSUE THREAD

**Issue by ajtruckle** [tinymce/tinymce#5240]
Version 4.9.4

If I type in:

`<kbd>SHIFT</kbd> + <kbd>H</kbd>`

I ended up with that literal text. I do have a class defined in my WordPress website for the `kbd` tag:

`pre {
 color: #808080;
}
kbd {
padding:0.1em 0.6em;
border:1px solid #ccc;
font-size:11px;
font-family:Arial,Helvetica,sans-serif;
background-color:#f7f7f7;
color:#333;
-moz-box-shadow:0 1px 0px rgba(0, 0, 0, 0.2),0 0 0 2px #ffffff inset;
-webkit-box-shadow:0 1px 0px rgba(0, 0, 0, 0.2),0 0 0 2px #ffffff inset;
box-shadow:0 1px 0px rgba(0, 0, 0, 0.2),0 0 0 2px #ffffff inset;
-moz-border-radius:3px;
-webkit-border-radius:3px;
border-radius:3px;
display:inline-block;
margin:0 0.1em;
text-shadow:0 1px 0 #fff;
line-height:1.4;
white-space:nowrap;
}`

So how can I get my TinyMCE Editor to show keyboard shortcuts nicely?

**Comment by lostkeys** [comment]
Are you trying to format keyboard shortcuts to stand out from regular text?

**Comment by ajtruckle** [comment]
Yes.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lnewson** [comment]
You'd need to either use a custom format with a custom toggle button (similar to bold) or use the code plugin/dialog to edit the HTML directly since TinyMCE is a WYSIWYG editor so typing `<kbd>` will actually generate the HTML `&lt;kbd&gt;`.

Here's some docs that maybe of help to do that (I'm also assuming you're using TinyMCE 4 based on your previous issues):
- [Creating a custom button](https://www.tiny.cloud/docs-4x/advanced/creating-a-custom-button/#togglebutton)
- [Registering a custom format](https://www.tiny.cloud/docs-4x/configure/content-formatting/#usingcustomformats)
- [TinyMCE 5 format parameters](https://www.tiny.cloud/docs/configure/content-formatting/#formatparameters) - I've included this as it still applies to v4, but doesn't exist in the v4 docs

**Comment by lostkeys** [comment]
I'll close this issue, but feel free to reopen it if @lnewson's answers didn't work for you.

**Comment by ajtruckle** [comment]
When I get a free moment I will test these ideas.
