### ISSUE TITLE
can't apply styles to custom menuButton

### ISSUE THREAD

**Issue by zzs1020** [tinymce/tinymce#5245]
**Is your feature request related to a problem? Please describe.**
I need to add some distinguishable style to different custom menu buttons, but no way to do that since they don't have class nor ids. They all plain black/white style right now.          
![image](https://user-images.githubusercontent.com/23032993/68482329-54442480-0207-11ea-8444-4e8ceb4c530b.png)

**Describe the solution you'd like**
provide ids to each menu button or class to its parent or provide a config api to do that when use editor.ui.registry.addMenuButton?            

**Describe alternatives you've considered**
I know there is a formatselect/styleselect toolbar dropdowns, and they are by default having their own style they are applying to. But since they don't fit my business requirement so I have to add my own dropdowns. Here I used editor.ui.registry.addMenuButton, if you konw any other replacement pls suggest.

**Comment by lostkeys** [comment]
You can use first-child, last-child, nth-child etc to get the buttons and customize them. [Here is an example](http://fiddle.tinymce.com/LUgaab)

```
.tox-toolbar__group:first-child .tox-tbtn {
	background-color: #2ecc71 !important;
	color: white !important;
}
	
.tox-toolbar__group:first-child .tox-tbtn svg {
	fill: white !important;
}
	
.tox-toolbar__group:first-child .tox-tbtn:hover {
	background-color: #27ae60 !important;
}
```

![image](https://user-images.githubusercontent.com/3122929/68571886-5c4cd000-0464-11ea-8863-1dc71a2eb721.png)

Disclaimer: We do not officially support styling TinyMCE by overriding the CSS like this as it can cause issues when upgrading (changes in HTML structure, moving declarations around etc). Maintaining CSS, fixing bugs and keep up with browser support is a moving goal, requiring ongoing tweaks to the CSS and sometimes the HTML structure. 

Adding classes to elements and in effect officially saying that we won't break the css put in them only in major releases is not something we can promise in such a complex component as TinyMCE. Instead we want developers to [build custom skins](https://www.tiny.cloud/docs/advanced/creating-a-skin/) using LESS variables. But since what you need is not possible to do via the LESS variable approach, you could try the above solution. Just be mindful when making changes to the toolbar and when updating TinyMCE.

Please feel free to reopen this ticket if you have any further questions or issues around this issue.
