### ISSUE TITLE
setCursorLocation fails on context menu click

### ISSUE THREAD

**Issue by migliori** [tinymce/tinymce#5252]
setCursorLocation fails on context menu action: the cursor gets out.
(The same command works fine using editor.on("keydown"))

Pen available here: https://codepen.io/migli/pen/zYYmxyO

The cursor should be set at the target position

TinyMCE: https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.0.16/tinymce.min.js
Browser: chrome (latest)

Many thanks

**Comment by lnewson** [comment]
@migliori I tested with your codepen, but it appears to be working fine, as doing the following in the dev console after selecting the last paragraph, right-clicking and selecting "test" will return that the selection is at the start of the first paragraph:
```
> tinymce.activeEditor.selection.getRng()
Range {startContainer: p#test-paragraph, startOffset: 0, endContainer: p#test-paragraph, endOffset: 0, collapsed: true, …}
```

So can you please provide more details about what you mean by it's "failing"?

I should also add that the editor doesn't have focus since you've done an interaction with something outside the editor content by using the context menu, which means the cursor won't be visible. If you want the editor to get focus after clicking, then you'll also have to call `editor.focus();`

**Comment by migliori** [comment]
it's "failing" meant that the cursor was not active at the place it should.
`editor.focus();` is the solution I was looking for.
Thanks for your help, no bug here, I just had no idea that right click made the editor loosing the focus.
