### ISSUE TITLE
TinyMce Format Painter heading tag issue

### ISSUE THREAD

**Issue by parveenbadoni** [tinymce/tinymce#5256]
**If i copy formatting of Heading tag, it is not getting pasted on any other text**

**On the fiddle provided on the TinyMCe website - https://cdpn.io/tinymce/debug/roKWpJ 
If i select "Welcome to the TinyMCE editor demo!" and then i click on format painter icon in the toolbar, and then i select "Please try out the features" in the next line, styling of heading tag does not get copied to the selected text **

**I am using version 4 of TinyMCe and used it on Google Chrome browser version 77.**

**Comment by lincolndennis** [comment]
@parveenbadoni - In my testing, following the above steps using this link: https://cdpn.io/tinymce/debug/roKWpJ I see expected behavior: The desired style is applied to "Please try out the features" .

When the styling is not copied, are you seeing any errors in the console?

Can you reproduce the issue in this Tiny Fiddle?
http://fiddle.tinymce.com/lVgaab/1

**Comment by lincolndennis** [comment]
@parveenbadoni - Actually, since Format Painter is a Premium Plugin, and not included in this repo, the best way to get assistance with this issue would be to contact Tiny Support directly:

https://support.tiny.cloud/hc/en-us
