### ISSUE TITLE
Autoresize and resize

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#5285]
v5.1.2 
resize https://www.tiny.cloud/docs/configure/editor-appearance/#resize is default=true

but with plugin autoresize https://www.tiny.cloud/docs/plugins/autoresize/ the "resizer" right bottom in corner is missing. So you must set resizer=true in config-setting.

Example http://fiddle.tinymce.com/cWgaab

Is this a bug or maybe should be a hint in autoresizer docu?

**Comment by lnewson** [comment]
This is expected behaviour, as if you have autoresize enabled then it's meant to automatically resize the editor to the size of the content at all times, up until the max height, so there's no need for a manual resize handle. Also the manual resizer is not currently supported with the autoresize plugin, so that's why it's not mentioned in the documentation about how to turn it back on (see https://github.com/tinymce/tinymce/issues/5120 for one such issue if you turn it on).

**Comment by Daijobou** [comment]
Take a look in this editor here on github. Its autoresize and resize and working better as in tinymce. Its stops autoresize when user change size of editor. Thats the correct way in my eyes. The user should be the master and not the editor. ;)
