### ISSUE TITLE
Unable to get code sample plugin with additional languages working

### ISSUE THREAD

**Issue by brymon68** [tinymce/tinymce#5303]
**What is the current behavior?**

I am trying to enable code sample plugin with syntax highlighting for additional languages than the default 10. Specifically, I am trying to add: perl, bash, md, powershell, http, etc. 

```
tinymce.init({
  selector: 'textarea#codesample',
  height: 500,
  plugins: 'codesample code',
  codesample_languages: [
    {text: 'Powershell', value: 'powershell'},
    {text: "Perl", value:"perl"}
  ],
  toolbar: 'codesample code',
  content_css: [
    '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
    '//www.tiny.cloud/css/codepen.min.css'
  ]
});

```

I am also including the prism.js and prism.css files, but still there is no syntax highlighting taking place for perl or powershell. 

Any ideas?

**Comment by SimonFc** [comment]
We're going to look into updating the CodeSample plugin and to possibly provide an option for a custom version of Prism to make it work for additional languages. (As of now we're using an inlined version of Prism)

**Comment by brymon68** [comment]
That would be fantastic @SimonFc. Any idea on when you might include it so I can inform our community?

**Comment by SimonFc** [comment]
I can't think of any work around due to the [Prism](https://github.com/tinymce/tinymce/blob/d16a86d9ec2e4fb1f6a5b352bbf6d659da785cc4/modules/tinymce/src/plugins/codesample/main/ts/core/Prism.ts) instance in the CodeSample plugin being local to that plugin. As for a timeline, I can't say anything about that either but we'll provide you with an update once it has been fixed!

**Comment by lnewson** [comment]
TinyMCE 5.2.0 was released to the community earlier this week, which added a new `codesample_global_prismjs` setting to allow a global instance of Prism to be used instead of the embedded version. Here's a fiddle to show how to use the new setting/feature: http://fiddle.tinymce.com/6bhaab. Please let us know if you have any further issues.
