### ISSUE TITLE
Media plugin inconsistent rendering mp4 files.

### ISSUE THREAD

**Issue by brittanytang** [tinymce/tinymce#5307]
**What is the current behavior? Describe the bug**
The media plugin renders some mp4 files as an anchor tag, while others render as a video tag.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1.  Go to https://www.tiny.cloud/docs/demo/full-featured/#
2.  Open Media dialog.  Enter "https://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_2mb.mp4" into the Source field and hit save.
3.  Observe video is displayed and rendered using  Video tag.
4.  Open Media dialog.  Enter "https://file-examples.com/wp-content/uploads/2017/04/file_example_MP4_480_1_5MG.mp4" into the Source field and hit save. 
5.  Observe video is rendered as an anchor tag.

**What is the expected behavior?**
Both mp4 links should render as a video tag.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5

**Comment by lnewson** [comment]
This is caused by the Enhanced Media Embed plugin which resolves how the URL should be embedded in the editor. You'll notice this issue doesn't occur if you use the second example on the page you linked.

Since this is an issue in a premium plugin we unfortunately cannot provide support from GitHub, so if you have purchased the Enhanced Media Embed plugin please contact our [support team](https://support.tiny.cloud/hc/en-us/requests/new) who can help out with this further.
