### ISSUE TITLE
TinyMCE when you continue to press space, the text of * * between the two asterisks will be converted to italics, and the two stars will be removed

### ISSUE THREAD

**Issue by ljc520313** [tinymce/tinymce#5331]
before press space
![image](https://user-images.githubusercontent.com/7116096/71777386-2fd3b100-2fda-11ea-807f-df40254aebb1.png)

after press space
![image](https://user-images.githubusercontent.com/7116096/71777403-5eea2280-2fda-11ea-9274-09353e44ae47.png)

**Comment by SimonFc** [comment]
That is most likely because you're using the `textpattern` plugin. You can read more about the different patterns the plugin is providing [here](https://www.tiny.cloud/docs/plugins/textpattern/#textpattern_patterns). As you can see, asterisk+text+asterisk will apply the *italic* [format](https://www.tiny.cloud/docs/configure/content-formatting/#formats)

I'm going to assume that you thought this was a bug(which it isn't), hence why I'll close this. But let me know if you meant something else!

**Comment by ljc520313** [comment]
edit the hive command below
![image](https://user-images.githubusercontent.com/7116096/71790197-2c880600-306a-11ea-8519-a5dd74bbc821.png)
So I think it's a bug

**Comment by SimonFc** [comment]
@ljc520313  How is this related to TinyMCE?

**Comment by ljc520313** [comment]
press the space again, the text of * * between the two asterisks will be converted to italics, and the two stars will be removed

**Comment by ljc520313** [comment]
thanks
