### ISSUE TITLE
Cannot cut and paste table in version 5.1.5 and in demo

### ISSUE THREAD

**Issue by umbria** [tinymce/tinymce#5341]
**What is the current behavior? Describe the bug**
Cannot cut and paste table in version 5.1.5 and in demo.
It worked on very old version 3.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via 
https://www.tiny.cloud/docs/demo/full-featured/

**What is the expected behavior?**
By Ctrl+x or cut menu, it should be copied , removed and pasted.
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
It worked on v 3.
In version 5.1.5 doesn't work. It doesn't work on Firefox, chrome, Windows and Linux

**Comment by lnewson** [comment]
This is an issue in our PowerPaste plugin it seems, as it works in the non-premium example below. This has been fixed recently as part of another internal task and will be released in an upcoming PowerPaste release.

However, since this is an issue with the Premium Plugin, I'm going to close this as we don't provide support for Premium Plugins via GitHub. If you've purchased PowerPaste, please feel free to log a [support request](https://support.tiny.cloud/hc/en-us/requests/new) for further support.
