### ISSUE TITLE
Inserting tables directly from toolbar using "inserttable" action

### ISSUE THREAD

**Issue by t00** [tinymce/tinymce#5360]
I am trying to simplify the way a table can be inserted by including `inserttable` menu item directly on a toolbar instead of including a full blown `table` menu item.

The reason for this is that context menu (`table_toolbar`), when extended with `tablerowprops` and `tablecellprops`, allows convenient table editing and styling without moving back and forth to menu/toolbar.

Unfortunately it does not work and I could not find a way to make this fancymenuitem action embeddable on a toolbar.

If there is no workaround, would you be able to make it work in the mainstream tinymce?

**Comment by t00** [comment]
This is the effect I am trying to achieve:

![image](https://user-images.githubusercontent.com/1933165/72889835-82b2a580-3d08-11ea-88fa-5e781263a956.png)

**Comment by lnewson** [comment]
This won't be easy to do, as while you can get the grid to display (see http://fiddle.tinymce.com/ZZgaab/1), there's no command or API available to insert a table based on the grid selection at the moment. As such I'm going to make this as a feature request, so that we can either add the menu button, expose an API to insert a table based on the rols/cols provided or do both.

**Comment by lostkeys** [comment]
@t00 I just wanted to circle back and let you know that in TinyMCE 5.4 we released table APIs to insert tables in the way you requested. Here is a demo: http://fiddle.tinymce.com/Mqhaab/1. Here is the relevant documentation: https://www.tiny.cloud/docs/plugins/table/#commands

**Comment by t00** [comment]
@lnewson Many thanks for adding the feature - it is so simple to add a table this way - works great.
