### ISSUE TITLE
Problem with inline editor not calling onSetup

### ISSUE THREAD

**Issue by DNWEIJ** [tinymce/tinymce#5384]
https://community.tiny.cloud/communityQuestion?id=9064N000000MxVqQAK
(repeating below)

Hi there, 

See this pen:

https://codepen.io/dnweij/pen/KKpPabb

I have used the example of tinyMCE5 and removed all unnecessary stuff. (example: https://www.tiny.cloud/docs/ui-components/toolbarbuttons/)

This leaves a tinymce5 editor working and given notification via the added button of the editor.on('init', editorEventCallback) in the browser console. 

But when the editor is switched to inline (uncomment the inline:true in the pen js code) the 

editor.on('init', editorEventCallback);

is NOT called! 

I was wandering, is this by design, do I need to do something else? Or is this maybe a feature? or a  bug?

Thnks for looking into it.

**Comment by SimonFc** [comment]
I think you have a race condition going on where the `init` event fires a bit later in iframe mode. Why do you need to listen to the `init` event?

**Comment by lnewson** [comment]
As @SimonFc mentioned the issue is a bit of a race condition. As with iframe mode the UI is rendered immediately and therefore `onSetup` is called before `init`. However in inline mode the UI isn't rendered until you activate the editor, which is after `init` has fired/completed.

As such you'll need to check for `editor.initialized` and branch from there. eg:
```
if (editor.initalized) {
  editorEventCallback();
} else {
  editor.on('init', editorEventCallback);
}

return function (buttonApi) {
  editor.off('init', editorEventCallback);
}
```
