### ISSUE TITLE
Autocompleter items as HTML in dropdown

### ISSUE THREAD

**Issue by Dineshkanin** [tinymce/tinymce#5395]
Hi, 

I tried to show the HTML content in the Autocompleter dropdown but it rendered as plain text instead of HTML. 

Kindly checkout the fiddle to know what I was trying to achieve. http://fiddle.tinymce.com/jbhaab/1 and help me to achieve the same.

Thanks in Advance.

**Comment by lostkeys** [comment]
Sorry to say it works as intended. The reason is that it would inject HTML and CSS into the TinyMCE UI which might break with a future update to TinyMCE. Any CSS declaration you did not explicitly set in your autocompleter dropdown template will cascade down from the TinyMCE UI. On the other hand, this is a fairly common request so we _are_ thinking about the problem.
