### ISSUE TITLE
Tinymce 5 mobile editor in a modal using bootstrap 4 is not working

### ISSUE THREAD

**Issue by jzabate** [tinymce/tinymce#5414]
**What is the current behavior? Describe the bug**
On mobile view clicking on the book button doesn't display mobile editor of tinymce 5

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**
It should display the mobile editor where you can edit texts and format it accordingly.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Happens on both iOS and Android
TinyMCE 5
Bootstrap 4

Will provide sample fiddle when it is available.

**Comment by lnewson** [comment]
The legacy mobile theme is deprecated as of TinyMCE 5.1, so I'd suggest trying the new mobile experience in 5.1 and see if that resolves your issue: https://www.tiny.cloud/docs/release-notes/release-notes51/#mobile.

If that isn't an option, then we'll need the fiddle to be able to investigate more, though since the legacy mobile theme is deprecated we're only doing critical fixes. I should also add that it's a known issue the legacy mobile theme doesn't work in a bootstrap dialog: https://github.com/tinymce/tinymce/issues/4818

**Comment by jzabate** [comment]
Thanks @lnewson I came across on stackoverflow about it and I applied it and it worked just fine.
