### ISSUE TITLE
Image upload Handler not getting triggered if I select file other than image

### ISSUE THREAD

**Issue by SIMRAN88** [tinymce/tinymce#5442]
Hi There,

So earlier what was happening is that in V4, when I was adding to add any text file or video file entering the upload tab and clicking on the browse from computer , then an event got triggered and I was able to find the type of the file and update with validations like if it was an image file(jpeg,jpg,gif,png), I was allowing that to be added in the editor and for the files which were not of image type I used to show an error message. So in v4 the image_upload_handler used to get triggered on selecting any type  but after TinyMCE update to v5 the image_upload_handler is not getting triggered only and I am not able to validate it.

If you know why image_upload_handler is not getting triggered after selecting any file after clicking browse from the computer, please update

**Comment by lnewson** [comment]
This is expected behaviour, as only images should be able to be uploaded via the upload tab and likewise, only images should be passed to the image upload handler (as given by the name).

Testing this out currently it just rejects the upload since the file type is not an image and therefore the `images_upload_handler` isn't called, which is what should be happening. We should perhaps be showing an error message of some kind when an invalid file format is uploaded, so I'll log an internal task to look into that.
