### ISSUE TITLE
Quickbars toolbar shows on init without being focused

### ISSUE THREAD

**Issue by glenfordwilliams** [tinymce/tinymce#5456]
is there a way to disable this pop up menu?
**What is the current behavior? Describe the bug**
 everytime my app reloads they are always up and scrolls with the page. I assume it may have to do with the editor being in focus when rendered.
i have quite a few editors being rendered at the same time ..
![image](https://user-images.githubusercontent.com/1114368/75767733-444dd480-5d11-11ea-89a5-0b1e14b88fea.png)

**What is the expected behavior?**
only show up when i click on an editor

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

    "tinymce": "^5.2.0",
    "@tinymce/tinymce-react": "^3.4",

happens in both chrome and firefox

**Comment by lostkeys** [comment]
This menu is part of the [quickbars plugin](https://www.tiny.cloud/docs/plugins/quickbars/). You can either remove that from your `plugins` option or you can disable that particular menu and keep the rest of the quickbars feature by adding `quickbars_insert_toolbar: false` to your config.

**Comment by lnewson** [comment]
This actually looks like a regression in 5.2.0, as this shouldn't be getting rendered if the editor doesn't have focus. I believe this is likely due to a fix we did to ensure the selection is in the right place on init. Either way we'll look into this more and let you know when we have more information available.
