### ISSUE TITLE
Mount tox-silver-sink in custom div

### ISSUE THREAD

**Issue by dgoogles** [tinymce/tinymce#5471]
Currently tox-silver-sink gets added to the document body. Is it possible to configure it to attach somewhere else?

Specifically I want to added it to the shadow root of a custom component I am building (I know tinymce doesn't support shadow, but it kind of does in iframe mode, except for silver sink being in the wrong place);

**Comment by lnewson** [comment]
@dgoogles no that's currently not possible sorry, as having the sink in variable locations drastically increases the complexity of the positioning logic. We already have an issue open for shadom dom support, so I've just marked this as a question since we probably won't allow it to be placed in a random location and instead would just need to add support to mount it within the shadom dom, should we add shadow dom support.

**Comment by lostkeys** [comment]
@dgoogles Can you explain more about what you're trying to do by putting the sink in a shadow dom. Is it _just_ the sink or the toolbars. The only thing I can imagine is that you want to containerize and scope custom css styles...

**Comment by dgoogles** [comment]
@lostkeys, yeah that's right. When a tinymce dialog opens, it gets appended to tox-silver-sink (which is in the body of the document) But we are installing the tinymce css styles from within our component, so they don't get applied. We could add the styles to the document but we hope to leverage the encapsulation of shadow dom. I realize there is more work to be done here, but it almost works! 

I actually tried manually moving the tox-silver-sink node to within my shadow dom after it mounts and then styles are applied correctly, but that doesn't quite work as tinymce no longer thinks that its inBody().
