### ISSUE TITLE
[ms word] soft line breaks in number lists

### ISSUE THREAD

**Issue by kadse** [tinymce/tinymce#5474]
**What is the current behavior? Describe the bug**
If i have a number list in a word document, which has a soft line break at the end of the first row and after the first word of the next line exists a full stop, this first word will not be appear in TinyMCE when i copy the content from the word document and insert it into the TinyMCE editor.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Make a number list with a soft line break at the end of the first row and set a full stop after the first word after the line break. (see screenshot1 point 2)
Then copy the content from word to TinyMCE and the first word with the full stop after the soft line break will be disappear. (see screenshot2 point 2)
For comparison in both screenshots is a soft line break without a full stop after the first word shown, which will be correct inserted by TinyMCE. (point 1 on both screenshots)

![screenshot1](https://user-images.githubusercontent.com/5993662/76064393-d8c26c00-5f89-11ea-8501-4a021a52e29d.png)
![screenshot2](https://user-images.githubusercontent.com/5993662/76064397-dc55f300-5f89-11ea-92fa-e29f3a11469f.png)

**What is the expected behavior?**
That the TinyMCE doesn't drop words of the content when it will be copied and inserted from a word document. Regardless if there is a full stop after the first word after the soft line break or not.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Version: TinyMCE 5.1.6
Browser: Safari on MacOS, Chrome & Firefox (MacOS & Windows)

This issue doesn't exist in TinyMCE with premium word plugin.

**Comment by lnewson** [comment]
I believe this is likely due to the current code trying to treat it as a numbered list instead of the end of a sentence. The community paste plugin only has rudimentary word support though, so if you need proper copy/paste support I'd suggest the premium PowerPaste plugin which you've mentioned works as expected. I'll leave this open though, as it is still content loss so we'll see if there's something we can do, however I don't have a timeframe for when a fix would be available.
