### ISSUE TITLE
Downloading external files

### ISSUE THREAD

**Issue by shanehickeylk** [tinymce/tinymce#5487]
**Is your feature request related to a problem? Please describe.**
It is not currently possible to download external files by clicking a link.

**Describe the solution you'd like**
If I have a link to an external file with both a href and download value, I would like to be able to download the file by clicking the link.

**Comment by lnewson** [comment]
I'll mark this as a feature request, as you're right it's currently not possible. We likely won't allow it to be clicked within the editor itself, as users often want to edit a link, however I agree clicking the `Open link` button should work with this. Does that sound reasonable to you?

Also as a side note, I'm assuming you'd like to see a way to specify a link is a download link from within the link dialog, otherwise you'd have to manually edit the link to add the download attribute. Is that assumption correct?

**Comment by shanehickeylk** [comment]
Yes that would be great, thanks!

**Comment by linusbrolin** [comment]
> Also as a side note, I'm assuming you'd like to see a way to specify a link is a download link from within the link dialog, otherwise you'd have to manually edit the link to add the download attribute. Is that assumption correct?

This is exactly what I'm currently looking for aswell.
Is there a way to extend built-in plugins to add this functionality myself until it becomes available?
