### ISSUE TITLE
How to use the watermark function

### ISSUE THREAD

**Issue by liufurusu** [tinymce/tinymce#5501]
How to use the watermark function

**Comment by lostkeys** [comment]
Can you describe a bit more what you mean with a "watermark function"?

**Comment by liufurusu** [comment]
Watermark. A watermark is a logo, text, or pattern that is intentionally superimposed onto another image. Its purpose is to make it more difficult for the original image to be copied or used without permission.

**Comment by lnewson** [comment]
@liufurusu we know what a watermark is, but that doesn't have anything to do with "watermark function". What do you mean by "function", or what do you want to be able to do?

**Comment by lostkeys** [comment]
There is no watermark function in TinyMCE or MoxieManager. You either need to seek support from the vendor offering the watermark function you use, alternatively if you need a watermark function you need to get that from a third party vendor. 

I'm going to close this ticket, but do not hesitate to reopen it because we misunderstood something.
