### ISSUE TITLE
Every time after clicking "More"(triple dots) button, the first button in extended bar is in active status

### ISSUE THREAD

**Issue by zzs1020** [tinymce/tinymce#5506]
**What is the current behavior? Describe the bug**
Every time after clicking "More"(triple dots) button, the first button in the extended bar is in activated status
![image](https://user-images.githubusercontent.com/23032993/76772031-9ca3be00-6776-11ea-948a-00ab718ea3ca.png)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
try on your demo https://www.tiny.cloud/docs/demo/full-featured/, after click triple dots button, then change align to right, then close dots button, then open again

**What is the expected behavior?**
should in inactive status if not clicked before.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinymce 5.10.0, and your cloud version

**Comment by lostkeys** [comment]
Hi, It's not active, it gets the keyboard focus state. Unfortunately it's very similar to the enabled/active state, however a blue focus outline would be too visually disruptive so that's why it is not changed yet. Personally I'd like TinyMCE to have an invisible "button zero" that had the keyboard focus state so the keyboard focus state is invisible until an arrow key is pressed. I'll log this as a feature request.

**Comment by zzs1020** [comment]
@lostkeys thanks!
