### ISSUE TITLE
Removing black 1px borders

### ISSUE THREAD

**Issue by ErraticFox** [tinymce/tinymce#5532]
Hello, I've made my theme following the docs, but it's not covered in the documents. In my `skin.less` I have:
```less
@background-color: #2f363d;
@border-color: #ffffff00;
```
the two borders in question being in `.tox-tinymce` and `.tox:not([dir=rtl]) .tox-toolbar__group:not(:last-of-type)`. How can I do this? CSS overrides are not applying.

**Comment by lostkeys** [comment]
Hi, I tried your skin and the border color `#ffffff00` gets applied to the classes you mention. What is the expected result?

**Comment by ErraticFox** [comment]
I'm not getting the expected result, I'm getting this 
![image](https://user-images.githubusercontent.com/6486865/77456515-b924a380-6dd1-11ea-9bb1-a462a5054a82.png)

**Comment by ErraticFox** [comment]
`transparent` seems to have work, but I don't see why that hex value didn't.

**Comment by lostkeys** [comment]
Nice design! I do some digging but as I said before, I could not really replicate the issue. The borders became transparent for me (Safari on Mac). What browser are you using?
Just a heads up, if you use transparent on borders and at some point want to use dialogs with input fields you would need to explicitly set the border colors for those as they would be transparent otherwise (there are variables for most stuff). If you instead set the border color to be the same as the toolbar background color, you would benefit from all the darken and lighten modifiers that is being used all around the theme, taking care of all that for you.

**Comment by ErraticFox** [comment]
I might have forgot to compile the last save before I dragged the files over. Is there anyway to simplify the current way of making one? Currently, I cloned the repo, duped the default folder, the I compile, then put the compiled deep in the installed npm directory.

**Comment by lostkeys** [comment]
Sorry for the late reply. There are two ways to create skins, either build them from source, like you do. You could probably set up a workflow that copy files around after build. Or you could [use our new skin tool](http://skin.tiny.cloud), but you would still need to download files and put them in the correct places

The text is defined by a content skin. [Read more here](https://www.tiny.cloud/docs/advanced/creating-a-skin/#creatingacontentcssfile). You could also simply use the [content_style option](https://www.tiny.cloud/docs/configure/content-appearance/#content_style) if there is only minor changes.
