### ISSUE TITLE
Audio and video not displaying in editor

### ISSUE THREAD

**Issue by isaacholt100** [tinymce/tinymce#5540]
**What is the current behavior? Describe the bug**

When I try to insert a video or audio through insert -> media, it displays an image like so:
<img width="306" alt="Screenshot 2020-03-28 at 20 20 10" src="https://user-images.githubusercontent.com/58640393/77832944-87913c80-7131-11ea-8e6a-bb37cfde9481.png">

It works on the example editor on the home page and I haven't configured the media plugin any differently to the default settings, so I'm not sure why it's not working.

I'm using Safari on macOS Catalina.

Thanks in advance.

**Comment by lnewson** [comment]
This is intentional, though it's more likely legacy behaviour since browsers never used to have a nice way of rendering them. Currently iframes are the only elements that allow live embeds, so I'm going to mark this as a feature request/improvement.

**Comment by lostkeys** [comment]
You get the live media preview inside the editor via the [Enhanced Media Embed premium plugin](https://apps.tiny.cloud/products/enhanced-media-embed/?_ga=2.129350341.819125536.1585547866-1338173588.1580988700). It's called mediaembed in the plugin config. I'm going to close this issue, but please feel free to reopen it if there has been any misunderstanding

**Comment by lostkeys** [comment]
Sorry, I jumped the gun in this one, sorry ✋🤚. Reopening.

**Comment by NitroBAY** [comment]
media_live_embeds: "When you enable this option users will see a live preview of embedded video content within the editable area, rather than a placeholder image. This means that users can play a video clip, such as YouTube, within the editor."
Even with this option I don't see a live preview of embedded video but a placeholder image. I thought I was using the option wrong but this issue seems not to talk about this option so is this option any useful ?
For now the way one can hack around this (rather big in my opinion) limitation is by NOT using insertContent but using `editor.selection.setNode` but then you cannot resize the image/video.
