### ISSUE TITLE
Font size not apply to the li's number

### ISSUE THREAD

**Issue by wideweide** [tinymce/tinymce#5545]
Font size not apply to the li:

write a list 1,2,3
1. a
2. b
3. c

- a
- b
- c

select all then set font size to 36pt: the content's font size is 36pt ,but 1/2/3 not change

TinyMCE 5, chrome/firefox

**Comment by lostkeys** [comment]
This is expected. The reason is a bit technical. To set the font size of an individual list item, the CSS font-size property has to be targeting the `<li>` itself. This is not how TinyMCE works, it puts the selected text in-between spans thus not targeting the list item and the bullet/number. The reason is because of the _remove formatting_ functionality (which a fair number of people use). If you have set font-size 24px to the list item itself, and then do a partial selection of the list item and hit remove format button, we got a problem. There is no format to remove. We then have to add spans and do stuff like this `<li style="font-size: 24px"><span style="font-size: initial">This is a</span> list item</li>` when you press remove format and adding formats when you pushed a remove format is weird.

If TinyMCE was primarily used as a word processor where the HTML was more like a file format, then we could do all sorts of weird stuff. But since TinyMCE is used heavily in CMSes where the HTML code expects to be neat and tidy and accessible, we need to pay close attention to what actually happens to the HTML code. 

One could say that different people have different expectations on what applying and removing format actually means. For some it's primarily about the visual appearance. But for others, it's the technical output that matters.

That said, you're not the first person asking for this, we're thinking about different ways to tackle this. Anyone with an opinion is hereby invited to share it here 😄

**Comment by wideweide** [comment]
When set font-size,most expected thing is : set the size to whole ul/ol,may be just same degree,just like H1,H2...

So if I want to do this,what is the best pratice to define my own list trees? 
* css with a class name treeOne, then define .treeOne ul li,.treeOne ul li ul...
* then just add class name to top ul/ol

**Comment by wideweide** [comment]
As mentioned above，We can change list's style.

Simple way is just set the style to ul/ol,it will be better than now, just my opnion

**Comment by truonglocbinh** [comment]
@lostkeys Did we fix now ?

**Comment by TheSpyder** [comment]
Yes, in the current release selecting the entire contents of a list item and applying a font size will change the size of the list number.
