### ISSUE TITLE
Tinymce multiple initialization problem

### ISSUE THREAD

**Issue by umairakhtar52** [tinymce/tinymce#5550]
i created Two Editor with English and Arabic using tinymce 5.2. like Bellow
tinymce.init({
	mode : "exact",
  selector: '#textAreaEnId',  // change this value according to your HTML
  plugin: 'a_tinymce_plugin',
  a_plugin_option: true,
  a_configuration_option: 400,
  theme: "silver",
  language: "en",
  directionality: "ltr"
});

tinymce.init({
	mode : "exact",
  selector: '#textAreaArId',  // change this value according to your HTML
  plugin: 'a_tinymce_plugin',
  a_plugin_option: true,
  a_configuration_option: 400,
  theme: "silver",
  language: "ar",
  directionality: "rtl"
});

but the output of First Text Editor with English Submenus are in Arabic. see the Screenshot below.
![Capture](https://user-images.githubusercontent.com/50137239/78252796-d7df1480-750c-11ea-8756-a26c67056acf.PNG)

**Comment by lincolndennis** [comment]
@umairakhtar52 
Can you replicate this problem, with the actual configs you are using, in a Tiny Fiddle? If so, please Fork the Fiddle, and posted the newly-generated URL: http://fiddle.tinymce.com/baaaab

**Comment by lnewson** [comment]
TinyMCE doesn't support rendering the UI in 2 or more different languages. This has come up a couple times before and we've not yet seen a good reason to have the editor rendered in different languages within the same page since the page is normally only ever in one language.

As such I'm marking this as a feature request, but before we look into this, can you please provide some details about your use case for loading the editor in different languages?

**Comment by lnewson** [comment]
I'm going to close this since the additional information requested hasn't been provided. If you can provide the details about your use case or why you'd like to see this feature then we'll be happy to reopen this request.
