### ISSUE TITLE
How to set  dialog postion of view source ?

### ISSUE THREAD

**Issue by wideweide** [tinymce/tinymce#5551]
**Is your feature request related to a problem? Please describe.**
When view source code, pop up a dialog -- how to set the dialog's postiion,just cover the editor 

**Describe the solution you'd like**

When view source code,not pop up dialog,just switch the editor area to view souce and edit

**Comment by sudheerb** [comment]
Hi @lostkeys 
Its been almost 3 years since this feature request has been made. Is this request prioritised by TinyMCE team? 
For people like us who are migrating from CKEditor to TinyMCE, we miss the functionality of being able to view the Source Code in-place by just switching the mode from Design to Source mode instead of opening a new pop-up window altogether in TinyMCE.

Please let us know your thoughts on this and let us know if we can expect this functionality anytime soon in TinyMCE.

**Comment by lostkeys** [comment]
Thanks for surfacing this ticket. We implemented the inline code functionality late last year in the [Advanced Code premium plugin](https://www.tiny.cloud/tinymce/features/advanced-code-editor/) and it will get more improvements like fullscreen and copy code among other things in TinyMCE 6.4 that is being released next week.
