### ISSUE TITLE
HTML code inside pre and code tags does not work

### ISSUE THREAD

**Issue by manish-in-java** [tinymce/tinymce#5559]
**What is the current behavior? Describe the bug**

Consider the following HTML code.

```
<pre><code>&lt;article&gt;
    &lt;header&gt;Breaking News&lt;/header&gt;
    &lt;main&gt;
        &lt;p&gt;Lorem ipsum dolor sit amet.&lt;/p&gt;
    &lt;/main&gt;
    &lt;footer&gt;January 1, 2020&lt;/footer&gt;
&lt;/article&gt;</code></pre>
```

If included in a plain HTML file, this gets displayed correctly in browsers as:

```
<article>
    <header>Breaking News</header>
    <main>
        <p>Lorem ipsum dolor sit amet.</p>
    </main>
    <footer>January 1, 2020</footer>
</article>
```

However, applying TinyMCE to a `textarea` containing the snippet shown above converts it to:

```
<pre><code></code></pre>
<article>
    <header>Breaking News</header>
    <main>
        <p>Lorem ipsum dolor sit amet.</p>
    </main>
    <footer>January 1, 2020</footer>
</article>
<pre><code></code></pre>
```

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

This [pen](https://codepen.io/m-----/pen/XWbvZwX) shows the problem in question.

**What is the expected behavior?**

TinyMCE should preserve the original HTML snippet.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

I am using v4.8.2. I have also tested it on the latest v5.2.1, which demonstrates the same problem.

**Additional information**

I have seen #3162. I am already encoding the tags inside the `code` tag so I am expecting TinyMCE to just work.

**Comment by lnewson** [comment]
You aren't encoding the content within the textarea, only the content within the pre/code elements. So basically when used within a textarea it needs to be double encoded since the browser decodes it when rendering the textarea. Here's a forked version showing it works when encoded correctly: https://codepen.io/lnewso/pen/MWwNqLB

**Comment by lnewson** [comment]
For reference, this came up last week as well in https://github.com/tinymce/tinymce/issues/5522, so I'll talk to our docs team to see what we can get added to the docs to clear this up.

**Comment by manish-in-java** [comment]
Can you suggest how to call `setContent` after encoding in the `init` event?

**Comment by lnewson** [comment]
Using any of the TinyMCE API's you don't need to double encode it, so you'd just use something like this:
```js
setup: (editor) => {
  editor.on('init', () => {
    editor.setContent(`<pre><code>&lt;article&gt;
    &lt;header&gt;Breaking News&lt;/header&gt;
    &lt;main&gt;
        &lt;p&gt;Lorem ipsum dolor sit amet.&lt;/p&gt;
    &lt;/main&gt;
    &lt;footer&gt;January 1, 2020&lt;/footer&gt;
&lt;/article&gt;</code></pre>`);
  });
}
```

The only reason it's needed for textarea is that textarea element only allows text content (see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#Technical_summary). While browsers do some "magic" to get it to work if you happen to use `<pre>` instead of `&lt;pre&gt;` it's not technically valid HTML.
