### ISSUE TITLE
editor click event not triggering in readonly

### ISSUE THREAD

**Issue by SIMRAN88** [tinymce/tinymce#5584]
**editor click event is not triggering in readonly mode**

**1.add click event and on click try to return something
2.make the editor mode readonly**

**the click event must be triggered if we click anywhere on the editor**

**Tinymce 5.2.1 all browsers(mostly chrome)**

**Comment by lnewson** [comment]
This is expected behaviour as when the editor is in readonly mode it shouldn't react to any events. The reason being click events could change the dom or similar and there's no way to know what is safe and what isn't. If you do need to listen to a click or similar event hen in readonly mode then you'd need to bind and unbind the event yourself as needed.

I should note we have an internal task logged to investigate if there is a way to handle this better, however at this stage this is expected behaviour.
