### ISSUE TITLE
Sets the inserted HTML to not allow line breaks

### ISSUE THREAD

**Issue by oldpubcat** [tinymce/tinymce#5597]
code
```
            let html = `
                    <div class="box">
                    <div class="content">
                        <span class="number">1</span>
                        <span class="title" >title</span>
                    </div>
                    <div class="title1Close" contenteditable="false">x</div>
                    </div>`;
            myEditor.execCommand('mceInsertContent', false, html);
```

The 'title' element can wrap normally. How can I disable this. 

Another question:      How do you click on it to select it, and then press enter to insert a new line under it

**Comment by lostkeys** [comment]
What so you mean by disabling the wrap on the title element? Prevent line breaks in it?

In order to have an element be “block selectable” you need to make it no editable using contenteditable false.

**Comment by oldpubcat** [comment]
You can't `enter` because it's a title, but this can be edited,  The problem was solved, There is another problem. I want to click and select it, add some style, and then I can insert a new line under it by 'enter'

**Comment by lostkeys** [comment]
If I understand you correctly, you want to select an element, apply styles to it, and then simply press enter to make a new line. Unfortunately that is not how TinyMCE works. [You can make an element selectable](http://fiddle.tinymce.com/Eghaab) by using noneditable false but then you loose the ability to apply formatting to it, because it is you know, non editable. And pressing enter on a selectable element replaces is. It's the same principle if you select a piece of regular text and type a few characters, the selected text will be replaced.

We have no plans to change this behavior so I'm going to close this ticket for now. But I'm interested to know more about your use-case so please feel free to post a more indepth explanation of what you are trying to achieve (and perhaps some screenshots). Also please reopen the ticket if I've misunderstood what you're trying to achieve. Thx.
