### ISSUE TITLE
Custom plugins not working on mobile

### ISSUE THREAD

**Issue by developeronboard** [tinymce/tinymce#5600]
I had included a custom plugin in my editor. It works well on web but not working on mobile any suggestions please?

**Comment by lnewson** [comment]
@developeronboard can you please let us know what version of TinyMCE you're using? Also are you using the `mobile` theme at all?

If you are using the legacy/deprecated mobile theme, then that is expected behaviour as it only supported 3 plugins as noted here: https://www.tiny.cloud/docs/mobile/#legacymobiletheme-configuringtheplugins As such if you want to use a custom plugin on mobile, we'd suggest upgrading to TinyMCE 5.1 or higher and using the `silver` theme which is our current supported theme that works on desktop and mobile.

**Comment by developeronboard** [comment]
Currently am using V5.0.5. The only solution is to upgrade to V5.1 or higher?

**Comment by lnewson** [comment]
Yes unfortunately, as the legacy mobile theme didn't support custom plugins or even many TinyMCE community plugins for that matter.

**Comment by developeronboard** [comment]
If I upgraded `tinymce.init({
  selector: 'textarea',
  theme: 'silver',
  mobile: {
    theme: 'mobile',
    plugins: 'autosave lists autolink'
  }
});
` this set of code is the correct configuration right?

**Comment by lnewson** [comment]
No, you're still telling TinyMCE to use the legacy mobile theme and then disabling pretty much all plugins on mobile. You'll want to remove the following from your init configuration:
```
mobile: { theme: 'mobile', plugins: 'autosave lists autolink' }
```

**Comment by lnewson** [comment]
I'm going to close this given the behaviour is expected and we've said how to get this working (ie use 5.1.0 or higher with the silver theme). If you're still having issues then please let us know.

**Comment by developeronboard** [comment]
@lnewson can you tell me how to work this [https://www.tiny.cloud/docs/ui-components/autocompleter/#](url) in mobile browsers?

**Comment by lnewson** [comment]
@developeronboard it works largely in the same way as in desktop. You type/input a specific set of characters and a menu pops up.

**Comment by lnewson** [comment]
I should add you shouldn't need to do any extra configuration to get it to work on mobile devices. So if it works on desktop then it should work on mobile as well, assuming you are using the `silver` theme.

**Comment by developeronboard** [comment]
@lnewson the autocompleter works well on both mobile and desktop if `ch: ':'` when i change `ch:'@'` works only on desktop browsers but not in my android mobile browsers. [http://fiddle.tinymce.com/Zghaab](url) this is my fiddle kindly check with mobile.

**Comment by lnewson** [comment]
@developeronboard sorry, I did forget that we don't currently support the autocompleter on Android devices, see: [5.1 Known Issues](https://www.tiny.cloud/docs/release-notes/release-notes51/#autocompleterandkeypresseventissuesonandroid). This is unfortunately due to the inconsistent implementation Android uses for all browser-based input, as it doesn't let us know when a character is pressed and instead only sends a composition end event when a space or other certain characters are pressed. We do have a task to try and find a way to get that to work, but it hasn't been scheduled yet.

Anyways, I assume you're using an Android device and that's why it's not working? I tested the fiddle locally using iOS and it works fine.

**Comment by developeronboard** [comment]
@lnewson in android mobile browsers autocomplete works with characters like !,#,$,%,&,*, expect '@' .

**Comment by aert** [comment]
Hey @lnewson, is there an issue on github we can follow to stay informed about this issue ?

**Comment by Morshalin** [comment]
Check this, its working in my aplication.
mobile: {
        theme: "silver",
        height: 400,
    },

**Comment by Yash-Bhanushali-21** [comment]
This issue is still persistent on Android. Will this issue be fixed? Is there any round about for this issue at all ? @lnewson

**Comment by ThallesLazaro** [comment]
In February 2024 and the issue still persists on Android.

**Comment by ThallesLazaro** [comment]
In February 2024 and the issue still persists on Android.

**Comment by TheSpyder** [comment]
Android doesn't implement the full input events spec (and can't, due to the design of their software keyboard). We're finally making an attempt with #9376, but if that doesn't work I don't know if Android will _ever_ get autocomplete.
