### ISSUE TITLE
Language missing

### ISSUE THREAD

**Issue by Mejans** [tinymce/tinymce#5607]
Hello,
on the web page where the different locales are listed there is no traces of the Occitan language.
How comes such a situation?
When will it be merged?

**Comment by lnewson** [comment]
All language packs available on our [download page](https://www.tiny.cloud/get-tiny/language-packages/) are based on community submitted translations. Looking at Occitan in transifex, it's somewhat translated but is only at 72% and as such doesn't meet the 90% threshold mentioned to show. So that means you'll unfortunately need to wait for the translations to hit that threshold, or attempt to do the translations yourself (eg using an automated service).

**Comment by Mejans** [comment]
Now it's 92% @lnewson :partying_face: 
It can be imported!

**Comment by lnewson** [comment]
Thanks @Mejans. I'll have to follow up as to why it's not showing on the download page as I'm not overly familiar with that part of the process sorry. In the meantime, I've manually pulled your translations down and I've attached the Occitan language pack for you to use: [tinymce_languages.zip](https://github.com/tinymce/tinymce/files/4545794/tinymce_languages.zip)
