### ISSUE TITLE
Run multiple tinymce versions on same codebase

### ISSUE THREAD

**Issue by manoj-mass** [tinymce/tinymce#5621]
Hi,

We are planning to migrate our huge codebase in an incremental manner. So part of our angularjs code base will be migrated to reactjs which would run on top of angularjs code base. These two code bases will have two different TinyMCE versions (4 and 5) running.

Is this something possible, would it be problematic of having two different TinyMCE versions in the same code base. Thanks.

**Comment by lnewson** [comment]
This should work fine, provided they are on different pages. If it's a single page application then it likely won't work or will causes unexpected side-effects. The reason being TinyMCE being modular relies on adding a `tinymce` global on the page, so if two different versions are loaded on the one page they'll both try to write to that one global.

It's worth mentioning if it is a single page application, there are some ways around it but they aren't pretty. It basically involves manually deleting the globals and any potential CSS, etc... loaded for global purposes (eg skins) when loading different TinyMCE versions. We actually do this ourselves in one of our testing libraries here:
- https://github.com/tinymce/miniature/blob/master/src/main/ts/loader/Script.ts#L29
- https://github.com/tinymce/miniature/blob/master/src/main/ts/loader/Globals.ts#L5

I should note that's in a much more controlled environment though so your results may vary and is partly needed due to https://github.com/tinymce/tinymce/issues/3722 since TinyMCE currently isn't removing stylesheets when all editor instances have been destroyed.

**Comment by manoj-mass** [comment]
Noted with thanks. I will go through this.

**Comment by lnewson** [comment]
Cheers 👍 and feel free to ask anymore questions if you do run into issues.
