### ISSUE TITLE
Not handling invalid callbacks

### ISSUE THREAD

**Issue by blairzotron** [tinymce/tinymce#5635]
If I remove all instances of the inline editor using ``tinymce.remove()`` then re-initialize the inline editors (using a singular call to tinymce.init with a selector that applies to multiple divs) I get an error on line 26218 of 5.2.2 (dev version) when typing in the reloaded editor because it is trying to call an undefined callback, which is easily fixed with the following:
``		if( !callback ){
			return false;
			}``

Am I doing something wrong by using tinymce.remove() and then initializing the editors again? Is there a re-init method I didn't see? The reason I am doing this is because the user can click options (outside of tinyMCE) that add more editable text areas to the DOM and I need those to be activated.

**Comment by lnewson** [comment]
@blairzotron can you please provide a small replication case, as we'll need to see the issue to be able to debug what's going on? This could be a [fiddle](http://fiddle.tinymce.com/) or similar.

As a general rule rule removing the editor and re-initialising should be fine. I gave it a quick test and didn't get any errors, so this might be something specific to your setup. 

Also worth noting you can call `tinymce.init` with a [target] (https://www.tiny.cloud/docs/configure/integration-and-setup/#target) DOM element. So if you're just adding new textareas and want them converted you could call that combined with your regular config instead of shutting down all the editors and re-initialising.

**Comment by blairzotron** [comment]
I tried to reproduce with fiddle.tinymce.com but had no luck. 
I have custom plugins in my own environment so I now suspect that is where the issue is . 
Thanks for your response!
