### ISSUE TITLE
Youtube code attributes are not wrapped

### ISSUE THREAD

**Issue by humblehumanbeing** [tinymce/tinymce#5636]
Use TinyMCE as default editor in Joomla
Turn Joomla text filter ON in TinyMCE settings. That is TinyMCE won't filter out any.
Add a stabdard Youtube embed code:

`<iframe width="1129" height="635" src="https://www.youtube.com/embed/b1LjegNN09M" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

Save the article
Actual result:
It doesn't wrap the attribute, it adds a value to the attribute as follows

`<iframe width="1129" height="635" src="https://www.youtube.com/embed/b1LjegNN09M" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen"></iframe>`

I am using TinyMCE 4.5.11 on Joomla 3.9.18

**Comment by lnewson** [comment]
Hi @humblehumanbeing,

So a few points to start off, we don't maintain the Joomla integration, nor do we support TinyMCE 4.5 anymore sorry. We currently only support TinyMCE 4.9 for critical issues and then TinyMCE 5 for full support. As such, any Joomla specific issue we'd recommend logging with them instead.

Having said those disclaimers, I assume you're issue is with the `allowfullscreen` attribute being expanded to `allowfullscreen="allowfullscreen"`. Is that correct? If so, this is intended due to the best practices, as noted on this MDN page: https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute

> Boolean attributes are considered to be true if they're present on the element at all, regardless of their actual value; as a rule, you should specify the empty string ("") in value (some people use the attribute's name; this works but is non-standard). See the example below for a practical demonstration.

We could look at making it use an empty string such as `allowfullscreen=""` as an improvement, but as I mentioned it is currently intended since it's a best practice for producing good/valid HTML.

I'd also ask, is this actually causing an issue? or is it just that you don't like to see the expanded attribute form?

**Comment by lnewson** [comment]
Closing due to a lack of additional information. If you can provide the information requested above then we'll be happy to reopen this issue.
