### ISSUE TITLE
automatic_uploads problem

### ISSUE THREAD

**Issue by zsj621** [tinymce/tinymce#5650]
Tinymce5.2.2
At the beginning, I thought that the image_upload_handler function will only be executed when automatic_uploads is false. In fact, I got the exact opposite result. When the automatic_uploads is true, the images_upload_handler function will be executed.

**Comment by lnewson** [comment]
Yes, this is expected behaviour. If you have `automatic_uploads` disabled, then no images will be uploaded without manually telling the editor to upload via `editor.uploadImages()`. The `images_upload_handler` is called when the editor will try to upload images so that you can determine how and where to upload the images.

**Comment by lnewson** [comment]
Closing this as there haven't been any other followup questions in 7 days. If you have any further questions please feel free to log another issue.
