### ISSUE TITLE
Not to able to caputre the active span

### ISSUE THREAD

**Issue by developeronboard** [tinymce/tinymce#5661]
`selectedNode = ed.selection.getNode();
className = selectedNode.getAttribute('class');` this code works and gets the active span's when we enter Backspace but not works while entering Delete key, any suggestions are welcomed

**Comment by lnewson** [comment]
@developeronboard what you're asking isn't very clear sorry. Can you please create a [fiddle](http://fiddle.tinymce.com/) or similar to show what you are attempting to do?

**Comment by developeronboard** [comment]
`<span class="atwho-inserted" data-atwho-at-query="@" contenteditable="true"><span class="mentions" style="background: #f3f4f4; pointer-events: none;" data-mce-style="background: #f3f4f4; pointer-events: none;">User1</span></span>`  i have a span tag like this when we press Backspace key after this span tinymce capturing the class and id name by `let ed = tinyMCE.activeEditor;
selectedNode = ed.selection.getNode();
let className = selectedNode.getAttribute('class');
let id_name = selectedNode.getAttribute('id');`  but not same behaviour is encountered when we press Delete Key.

**Comment by lnewson** [comment]
That still isn't clear sorry, but it does help. Since you haven't provided a fiddle, small video or reproduction case, which is the easiest way for us to help, let me ask some more questions based on the information provided:
- Where are you placing the cursor when pressing backspace or delete?
- Are you attempting to do any other actions besides pressing the backspace/delete keys?
- When exactly are you attempting to run this code? is it in a `keydown` handler?
- Can you please provide the output of `ed.selection.getBookmark(3)` when you're calling `ed.selection.getNode()`?

Lastly, it'd be helpful if you can explain what you are attempting to accomplish. Are you just trying to remove the span, change the class, or something else?

**Comment by developeronboard** [comment]
**Where are you placing the cursor when pressing backspace or delete?**
      While pressing backspace key cursor is placed after the span and for delete key cursor is placed     before the span tag.
**Are you attempting to do any other actions besides pressing the backspace/delete keys?**
     Yes i want to capture deleting span's class and **id.**
**When exactly are you attempting to run this code?**
     It is a `keyup` handler
**Can you please provide the output of `ed.selection.getBookmark(3)` when you're calling `ed.selection.getNode()`?**
    Object { start: "p[0]/text()[2],18", end: "p[0]/text()[2],18" }

Lastly, I want to capture the removing span's classname and id, so that i can delete that span at a single time not word by word by using this code `tinymce.activeEditor.dom.remove(id_name);`

**Comment by developeronboard** [comment]
@lnewson are you there?

**Comment by lnewson** [comment]
@developeronboard sorry for not getting back to this sooner, however we've been really busy with getting TinyMCE 5.3.0 out.

As for what you're trying to do, I don't think it'll ever work as expected sorry as you're doing the logic in a `keyup` handler. Additionally, `selection.getNode()` is just the common node within the selection, so there's no guarantee that it'll be the span element you want to delete as the selection can either be inside the span or outside and appear the same. That is what's causing the issue here, as where the caret is being placed is outside the span and pressing delete will keep it outside (this is native browser behaviour).

As a suggestion, could you turn the span into a contenteditable false element instead? That would prevent editing the content inside the span, but it'd make sure when pressing backspace/delete the entire span will be deleted.
