### ISSUE TITLE
Inline mode toolbar does not obey toolbar_mode as floating

### ISSUE THREAD

**Issue by jcursoli** [tinymce/tinymce#5692]
**What is the current behavior? Describe the bug**
When you instantiate an inline editor, and specify toolbar_mode as floating, it does not obey the floating options, but instead wraps the options to the next line.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

[You can see the codesandbox repro here](https://codesandbox.io/s/immutable-lake-x9whx)

**What is the expected behavior?**
as the screen gets smaller in width we should see the floating options, not wrapped options.
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I have checked on the latest version 5.3.0, and version 5.2.2

**Comment by lnewson** [comment]
Hi @jcursoli, this is actually expected behaviour as you are attempting to use the [multiple toolbars](https://www.tiny.cloud/docs/configure/editor-appearance/#usingmultipletoolbars) feature which is incompatible with the toolbar drawer. You should see this in the toolbar_mode docs:
> The toolbar modes are not available when using multiple toolbars or the toolbar(n) option.

 I've updated your codesandbox to change the toolbar to a string, rather than an array and you can see it works now: https://codesandbox.io/s/relaxed-yalow-q1qq0

**Comment by jcursoli** [comment]
@lnewson thanks for the help, i didn't realize using an array with 1 item counted as multiple toolbars. but now that i think about it, that makes sense. 

Again thanks for the help.
