### ISSUE TITLE
Broken "images_dataimg_filter" option (since 5.3.0)

### ISSUE THREAD

**Issue by dmitriy-komarov** [tinymce/tinymce#5756]
[`images_dataimg_filter` option](https://www.tiny.cloud/docs/configure/file-image-upload/#images_dataimg_filter) was used to disable converting Base64 images into Blobs. In 5.3.0 there is a new algorithm replacing Base64 images with Blobs all time not respecting 
`images_dataimg_filter` option.

This change was related to #5557 (issue with Safari with too large Base64 images), but the lack of the option to avoid Blobs affects to TinyMCE in all browsers now.

If option `images_dataimg_filter` can not be used anymore, I suppose TinyMCE should provide some option like `disable_blobs` in order to provide ability to insert Base64 icons into the content.

**Comment by lnewson** [comment]
Thanks @dmitriy-komarov for letting us know about this! It appears our automated test for this is broken, which is why this was missed. We're going to release a hotfix for this later today.

I do want to mention that the docs are actually incorrect about what this is supposed to be used for. It's meant to be used to prevent certain images (eg icons, emojis, etc...) from being uploaded. We'll correct the docs to reflect that.

We would like to hear more about your use case though. It sounds as though you just need to prevent icons from being uploaded, is that correct? Or do you need it to remain as a base64 image within the editor? The reason I ask this is some of the new features planned in future releases will require us to internally store only blobs within the editor for base64 images. As such we've marked this setting as deprecated and we want to look at adding a new option to solve potential use cases, so any information you can give us about your use case would be much appreciated.

**Comment by dmitriy-komarov** [comment]
Hi @lnewson ,

I now this option is not exactly for this, but we use it to keep Base64 in src because this is the easiest way to access images data for any further modifications (it's more easy than accessing Blobs) by custom plugins or external tools. The option `images_dataimg_filter` is the only known way to do it (check StackOverflow please, there is a number of users who do the same).

**Comment by lnewson** [comment]
This was fixed in TInyMCE 5.3.2, which was released on June 10th. Sorry for not letting you know when it was released.
