### ISSUE TITLE
Textarea not clickable

### ISSUE THREAD

**Issue by bteles** [tinymce/tinymce#5841]
I'm using the api. When I click anywhere on the text area it does focus, it works only in the first line.
 I don't know what to do, please help!

**Comment by lostkeys** [comment]
It's a bit difficult to understand what the problem is with this limited information. Can you make a [TinyMCE Fiddle](http://fiddle.tinymce.com) and isolate the problem for us to better understand the problem.

The first that comes to mind is that the iframe html body isn't taking up the whole editor area so when you click inside the editor, your're actually clicking outside of the HTML body, thus not registrating as a focus event. But I'm just speculating wildly here...

**Comment by bteles** [comment]
That's exactly what is happening. I've just noticed that the version that I'm using is: 4.0.23. Can that be the cause of the problem?

**Comment by lostkeys** [comment]
TinyMCE 4.0 is very old. Regardless the resolution it's time to upgrade. 

You could quickly test a fix by adding this to your config (should work in 4.x too):
```
content_style: "body, html {height: 100%; }",
```

**Comment by bteles** [comment]
It didn't work. I'll have to upgrade (I've already did a test and it worked just fine), but thank for the support!

**Comment by lostkeys** [comment]
Cool. Don't hesitate to reach out if you hit any issues, we're here to help.
