### ISSUE TITLE
Adding custom text in statusbar in TinyMCE 5.x

### ISSUE THREAD

**Issue by nathanielcarolina** [tinymce/tinymce#5915]
In TinyMCE 4.x, one could access the statusbar via `editor.theme.panel` and also insert custom text as follows:

```
        const statusbar = editor.theme.panel && editor.theme.panel.find('#statusbar')[0]

        if (statusbar) {
          statusbar.insert(
            {
              type: 'label',
              name: 'myCustomLabel',
              text: 'myCustomText',
              classes: 'myCustomLabel',
              disabled: editor.settings.readonly
            },
            0
          )
```

What would be its equivalent in TinyMCE 5.x?

**Comment by metricjs** [comment]
Hey @nathanielcarolina. Unfortunately TinyMCE 5.x doesn't have an API for this, since our focus on accessibility would make this potentially rather complicated to implement, and for you to configure. However, we're not against implementing this in the future, as long as we understand what is actually needed. So, could you please describe your use case and we'll log this as a feature request?

**Comment by lnewson** [comment]
As there's been no reply for a month I'm going to close this. If you're still having troubles, then could you please include the details requested above and then we'll be happy to reopen this.

**Comment by bardware** [comment]
> describe your use case

I know I'm late to the party. Still, I'm trying to count the characters present in my TinyMCE instance so it fits into my DB column on the server. I'm looking at a small plugin like [maxchars](https://jsfiddle.net/tmakin/wqbpsvbf/) .
This inserts a label into the Status bar to display when there are more characters present than allowed.

**Comment by ewuski** [comment]
Did you get to anything @bardware ? I am trying to adapt this plugin to work in `tinymce-react` v4.2.0 https://gist.github.com/ClementParis016/ab06847c41160c22f278e4cabe4a0879
