### ISSUE TITLE
Any menu box shows out of place in Firefox when i move page vertical scroll.

### ISSUE THREAD

**Issue by andyjnet** [tinymce/tinymce#5930]
**What is the current behavior? Describe the bug**
When using the tinymce plugin from firefox the context menu of any option is out of place, even testing from your example

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
using Firefox Developer edition (last version) i open: https://www.tiny.cloud/docs/demo/full-featured/, then open tiny color picker, move vertical scroll, when open again color picker it is out of place.

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Last in your demo page / Windows 10 Pro
![tinymcerror](https://user-images.githubusercontent.com/4154735/89129309-5f905c00-d4ca-11ea-9c25-b860936b229c.png)

**Comment by lnewson** [comment]
Hi @andyjnet,

Thanks for the report, however I'm unable to reproduce this using Firefox Developer Edition 80.0b3. Are you able to reproduce this on either the Beta or Stable versions? Also have you tried to reproduce this in a private window (to ensure it's not an extension causing issues)?

These menu's just use absolute positioning, so scrolling shouldn't cause an issue unless it's in a scrollable container (which isn't something we currently support, see #5097), or something similar. Since our website has none of those cases, I'm more inclined to think it may be a bug in the Developer Edition. However, I can't say for sure without a way to replicate the issue.

**Comment by andyjnet** [comment]
Hi @lnewson, thanks for replying. The version of firefox where I have the issue is the same as you say 80.0b3 (64-bit) and it is stable version of developer edition.   I am testing right now  and everything seems to be fine, which makes me think that there could be some problem with my browser when I wrote this ticket. So, everything is fine, thank you very much for your help.
