### ISSUE TITLE
Adding link without http:// or https:// doesn't work

### ISSUE THREAD

**Issue by gavilletloic** [tinymce/tinymce#5938]
Hello,

I'm not sure if it's a bug or the default behavior. However, I forward feedback from customers.

This issue is for plugin "link".

If you write "youtube.com", it doesn't work. You must add "http://" or "https://. 

The easiest solution would be to set the input type to "url" and add a warning message when url is not valid.

![link_plugin](https://i.ibb.co/PmfknZB/tpn-19-9-screenshot-01.png)

**Comment by lnewson** [comment]
Hi @gavilletloic, this is currently expected behaviour, as it'll assume the links are internal. You can change this behaviour by enabling the [link_assume_external_targets](https://www.tiny.cloud/docs/plugins/link/#link_assume_external_targets) setting. That'll ensure users are requested to prefix a protocol when saving.

I should add the [link_default_protocol](https://www.tiny.cloud/docs/plugins/link/#link_default_protocol) may also be of use to you, as it'll control which protocol is prepended.

**Comment by gavilletloic** [comment]
Ok, thanks for the explanation.
