### ISSUE TITLE
[5.x]Error with webpack

### ISSUE THREAD

**Issue by sinbargit** [tinymce/tinymce#5939]
I do follow the [Usage with module loaders]( https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/), but they're still not working, It sends some HTTP request to get skin.min.css  content.min.css, and it got a 404 since there no those CSS in my site, that CSS should be bundled into one CSS via webpack.  Is there any way I can make it do not send the request? could you give a whole guide for TinyMCE use with webpack?
And after init, there is an invisible div which class is `tox tox-tinymce` which has a `visibility: hidden` style,
That far away with **Out of the box**

**Comment by lnewson** [comment]
Hi @sinbargit, I'd suggest taking a look at this answer provided by the community: https://github.com/tinymce/tinymce/issues/2836#issuecomment-544790987. Because TinyMCE loads the content in an iframe, any content CSS either needs to be loaded from a remote server or alternatively needs to be passed via the `content_style` setting in addition to disabling the content css from loading.

We're aware the documentation for that isn't very clear sorry, but it's being tracked in our docs backlog here: https://github.com/tinymce/tinymce-docs/issues/1466

**Comment by sinbargit** [comment]
Could you tell me how to make that work? After I remove the `visibility: hidden
` The UI is like below.
![image](https://user-images.githubusercontent.com/16011848/89385785-bc8e4b00-d732-11ea-83d5-bc397fb8ab53.png)

And there no content load fail except a webpack heartbeat
![image](https://user-images.githubusercontent.com/16011848/89385805-c2842c00-d732-11ea-921e-d4a64b7173ef.png)

**Comment by sinbargit** [comment]
thank goodness, it works, I will close this issue, but I think there should be a whole guide about webpack.
