### ISSUE TITLE
Is wiris plugin compatible with tinymce version 5?

### ISSUE THREAD

**Issue by SIMRAN88** [tinymce/tinymce#5943]
Hey , This is really important for my project. We are working on tinymce 5.2.1 and want to use the premium partner plugin wiris. https://www.tiny.cloud/blog/adding-math-and-equations-to-tinymce-is-easy-with-wiris/ 
In the given link it is not mentioned if the wiris plugin would work from the latest version. Please help on this.

**Comment by rohittm** [comment]
@SIMRAN88 This is a question for the MathType plugin developers as they are the ones providing the solutions for TinyMCE, and also, they are the author of the article you have mentioned in your initial query. 

From their docs here: https://docs.wiris.com/en/mathtype/mathtype_web/integrations/html/tinymce#requirements, it needs TinyMCE 2.0 or higher installed. So, it seems like it'll work on TinyMCE 5.2.1 (plus, here's where they have mentioned how it'll work with Tiny MCE 5: https://d.pr/i/baZjd0).

If you want to be entirely sure about this, I would recommend reaching out to there support at http://www.wiris.com/en/contact. Since it is more of a pre-sales question, reaching out to the sales email on that page would be helpful.

I hope that helps and points you in the right direction.

**Comment by SIMRAN88** [comment]
Thanks @rohittm

**Comment by lnewson** [comment]
Thanks for jumping in and answering this @rohittm! Anyways, that is correct and as mentioned above, I'd also suggest reaching out to the WIRIS MathType team directly for more specific information.
