### ISSUE TITLE
TinyMCE and Drag Conflict Issues

### ISSUE THREAD

**Issue by andrew2558** [tinymce/tinymce#5960]
My page reads as follows.

The problem is that when I use draggabilly to drag the move-line, dragging to the left is fine, but when I drag it to the right, it doesn't work in the area where the tinymce compiler is located. How do I fix this problem?

![wo7Y8](https://user-images.githubusercontent.com/25080605/89749850-18bee980-dafc-11ea-8555-b5db5f19f22a.gif)

```html
<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>TinyMCE Drag</title>
 <script src="../lib/jquery3.5.1/jquery-3.5.1.js"></script>
 <script src="../lib/tinymce_5.4.0/js/tinymce.min.js"></script>
 <script src="../lib/draggabilly/draggabilly.pkgd.min.js"></script>

 <style>
 html,
 body {
 margin: 0;
 padding: 0;
 height: 100%;
 width: 100%;
 }
 .all-warp {
 display: flex;
 flex-direction: row;
 width: 100%;
 height: 100%;
 }
 .left {
 width: 200px;
 background-color: burlywood;
 }
 .move-line {
 width: 4px;
 background-color: crimson;
 cursor:e-resize;
 }
 .editor-warp {
 flex-grow: 2;
 }
 </style>
</head>
<body>
 <div class="all-warp">
 <div class="left"></div>
 <div class="move-line"></div>
 <div class="editor-warp">
 <textarea id="editor"></textarea>
 </div>
 </div>

 <script>
 $(document).ready(function () {
 var $draggable = $('.move-line').draggabilly({
 axis: 'x',
 containment: '.all-warp'
 })
 });
 tinymce.init({
 selector: '#editor',
 menubar: false,
 statusbar: false,
 language: 'zh_CN',
 resize: false,
 height:500,
 });
 </script>
</body>
</html>
```

**Comment by lnewson** [comment]
Hi @andrew2558, this doesn't sound like a TinyMCE problem, so I'm not sure how much assistance we can give. I don't know much about the draggabilly library you're using, but this would likely be a better question for them.

What I imagine the issue is, is that because when the cursor goes over the editor content the mouseover events will be sent to the iframe instead of the root document/window. A solution that might work in that case, would be to add a div that overlays the editor when you start dragging.

**Comment by andrew2558** [comment]
Thanks @lnewson , This problem is not only with draggabilly dragging, but also with javascript drag events, thanks for the solution you gave to solve the problem. I will give it a try.
