### ISSUE TITLE
TinyMCE paste plugin appends %MCEPASTEBIN% to pasted content in inline editor on Edge

### ISSUE THREAD

**Issue by mumat** [tinymce/tinymce#6019]
**What is the current behavior? Describe the bug**

When pasting content into a TinyMCE inline editor in an Edge browser the string "%MCEPASTEBIN%" is sometimes appended to the content.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

[Reproduction setup on fiddle.tinymce.com](http://fiddle.tinymce.com/gshaab)

1. Open the fiddle in an Edge browser
2. Paste some text (formatted or unformatted) into the editor
3. Sometimes the string "%MCEPASTEBIN%" is appended to the content

**What is the expected behavior?**

Only the copied text is pasted into the editor.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE: v5 current
Browser: Microsoft Edge 42.17134.1098.0

**Comment by mumat** [comment]
After some further investigation we found out, that the div used by PasteBin for inserting content is correctly removed but the default content of it (%MCEPASTEBIN%) is appended as plain text behind this div which causes it to remain in the DOM after pasting is finished.

Looking into the PasteBin code we found the line `const getPasteBinParent = (editor: Editor): Element => Env.ie && editor.inline ? document.body : editor.getBody();` [PasteBin.ts:15](https://github.com/tinymce/tinymce/blob/9ded70be0077bfdd0af022cc9eda00c55e573c9f/modules/tinymce/src/plugins/paste/main/ts/core/PasteBin.ts#L15) changing this line to return `editor.getBody()` instead of `document.body` seems to fix the issue for Edge.

**Comment by ashfordneil** [comment]
Hi Matthias!
Thanks for finding this for us, but unfortunately the version of Edge you're using is no longer supported by TinyMCE. We have some more information about the browsers we support [in the docs here](https://www.tiny.cloud/docs/enterprise/system-requirements/#supportedwebbrowsers) but the summary (for Edge) is as follows.

* We support the latest major version of Edge (85.x)
* We support previous major versions of Edge, *if* the major version that replaced them was released within the last 60 days. For example:
  * Edge 84.x is in support, as the first 85.x release was 25 days ago
  * Edge 83.x is not in support, as the first 84.x release was 67 days ago

Seeing as you've already done the digging to find and fix the bug, I would normally suggest that you write some tests for this logic and open a PR. However, we don't run our automated test suites on the legacy edge browser in CI any more, and we're trying to remove Edge specific code where we find it in the codebase these days to reduce technical debt. As there isn't anything we can do to fix this bug, I'm going to close the issue. If the error still occurs in the newer (chromium based) version of Edge*, or any other browser, please create a new ticket or reopen this one.

*We've tried to replicate this in the newer Edge, and have been unable to. If you can replicate the bug there, please let us know the exact steps (including the text you tried to paste, and operating system) so that we can follow along.
