### ISSUE TITLE
Toolbar menu options are hidden behind modal on popup

### ISSUE THREAD

**Issue by SuppSoftAdminZ** [tinymce/tinymce#6100]
The toolbar menu options work fine on page when not part of a popup. However, once the component is rendered in a popup, the toolbar menu options are displaying behind the popup. 

Expected Behavior is for the toolbar menu options to display on the popup screen along with the component itself

I'm using Microsoft Edge. TinyMCE version "@tinymce/tinymce-react": "^3.7.0". This is my first attempt at using TinyMCE so not sure if it worked in other versions.
![TinyMCE ToolBar issue](https://user-images.githubusercontent.com/34314680/95868794-a3100d80-0d38-11eb-803b-f165aede8018.png)

**Comment by lincolndennis** [comment]
This can to happen if the z-index of the dialog is set around 1000 or higher. The easiest way to solve this should be applying CSS to the menu itself, something like:

```
.tox.tox-tinymce-aux {
  z-index: 4000;
}
```

Or, if you are using the [fullscreen plugin](https://www.tiny.cloud/docs/plugins/fullscreen/) ( As otherwise it will show similar problems ):
```
.tox.tox-tinymce-aux,
.tox-fullscreen .tox.tox-tinymce-aux {
  z-index: 4000;
}
```
( Replacing 4000 with whatever value is higher than their z-index  for the dialog ).

**Comment by SuppSoftAdminZ** [comment]
Thanks Lincoln!  That works perfectly!
