### ISSUE TITLE
Problem editing codesample code.

### ISSUE THREAD

**Issue by gesquivelob** [tinymce/tinymce#6115]
Hi! Im experiencing some issues with codesample feature, the problem is when I add a code sample, all is working fine, but when trying to edit the code (after saving the content to mysql), tiny.cloud plugin is not interpreting correctly the previous saved code, and this happens:

When creating the codesample all works fine:

![Screenshot_20201017_142905](https://user-images.githubusercontent.com/17990642/96352066-193ca900-1086-11eb-801e-81130c7bfb6b.jpg)

But after saving in mysql and editing again the code looks like this: 

![Screenshot_20201017_142826](https://user-images.githubusercontent.com/17990642/96351971-2b6a1780-1085-11eb-9b8f-472453a5a219.jpg)

By the way, the code is saved correctly in mysql without any modifications.

I think the problem is when tiny.cloud plugin reads the `<p>` tags and split the `<pre>` tags.

**Comment by lnewson** [comment]
Hi @gesquivelob, this is likely an issue with how you're rendering the content from your database. When rendering the textarea that TinyMCE loads from, you need to ensure to escape the content otherwise it'll generate invalid HTML and lead to issues such as this.

Here's a list of previous issues, where other users have run into this same issue that might help you:
- https://github.com/tinymce/tinymce/issues/6009
- https://github.com/tinymce/tinymce/issues/5559
- https://github.com/tinymce/tinymce/issues/5522

**Comment by webtinax** [comment]
Yes I problem rendering the content from my database and content loaded on tinymce THANK YOU [lnewson](https://github.com/lnewson) for help
