### ISSUE TITLE
change Button .tox-statusbar__wordcount text to text constant

### ISSUE THREAD

**Issue by nadjak77** [tinymce/tinymce#6117]
**What is the current behavior? Describe the bug**
in the right bottom of the editor you can see how many words are tiped. The text "words" ist always in english.
We user TinyMCE in Joomla and want to translate it.
See issue at joomla:
https://github.com/joomla/joomla-cms/issues/31136

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Open TinyMCE and see right, bottom the count of the words yout tiped. "Words" is in english.

**What is the expected behavior?**
"Words" should be a language string to be translated.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by lnewson** [comment]
Hi @nadjak77,

This appears to be working fine to me, as can be seen in this fiddle: http://fiddle.tinymce.com/Svhaab. Can you please provide a way to reproduce the issue, outside Joomla? Based on the linked Joomla GitHub issue, it seems to be using an incorrect `langs/de.js` file as `{0} words` is the correct source string.

I should add though, I do know that the community translations in transifex are outdated (they are from 5.1 I believe), so that could be the problem here as well if Joomla are consuming them. I'll do some digging and see if that's the issue.

**Comment by lnewson** [comment]
I checked Transifex and our language packs at https://www.tiny.cloud/get-tiny/language-packages/ and they include the `{0} words` translation (it currently includes both `{0} words` and `Words:  {0}`).  Here's another fiddle to show what happens when I use the German language pack I download from the previously mentioned link: http://fiddle.tinymce.com/Svhaab/1. You'll see this is also translating the `words` string in the statusbar.

As such I'm afraid this is an issue with the language packs Joomla are distributing, so I'm afraid you'll need to reopen the linked issue and get them to fix it.

**Comment by nadjak77** [comment]
Thanks. I will go back to Joomla with my issue.
