### ISSUE TITLE
"GET /static/tinymce/langs/en_US.js HTTP/1.1" 404 

### ISSUE THREAD

**Issue by AM0k84** [tinymce/tinymce#6121]
I install TinyMCE and it works great but Django return 
'"GET /static/tinymce/langs/en_US.js HTTP/1.1" 404 ' 
and I don't know why...
Some ideas?

**Comment by JamesToohey** [comment]
Hi @AM0k84, one thing to check is that you haven't set `language: 'en_US'` in the TinyMCE configuration, as that's the default and there is no language pack.

Otherwise, unfortunately we aren't able to help with the specifics of a Django implementation, maybe it's worth asking in [django-tinymce](https://github.com/jazzband/django-tinymce), assuming you're using their plugin?
