### ISSUE TITLE
Tinymce multiple instances in multiple languages on the same page

### ISSUE THREAD

**Issue by AhmedMa3rouf** [tinymce/tinymce#6131]
I want to use multiple instances in multiple languages on the same page, but it failed
this is my code
tinymce.init({
        selector: '.EngEditor',
        directionality: 'ltr',
        language: 'en_US'});
tinymce.init({
        selector: '.arEditor',
        directionality: 'rtl',
        language: 'ar'
    });

it will work with the last configure only (Arabic in my case)

**Comment by lnewson** [comment]
Hi @abhishekdev, TinyMCE doesn't support rendering the UI in 2 or more different languages. This has come up a couple of times before and we've not yet seen a good reason to have the editor rendered in different languages within the same page since the page is normally only ever in one language.

As such I'm marking this as a feature request, but before we look into this, can you please provide some details about your use case for loading the editor in different languages?

**Comment by lnewson** [comment]
Hi, we are closing this as there have been no additional details provided in the last month. If you can provide the details requested above, then we'd be happy to re-open this feature request.
