### ISSUE TITLE
Fullscreen doesn't work properly 

### ISSUE THREAD

**Issue by AEK-BKF** [tinymce/tinymce#6139]
**What is the current behavior? Describe the bug**
As in attached, Fullscreen plugin doesn't work properly, the width is fine, but not the height.
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Click on Full-screen button -> Width is fine, Heigh not. ( See attached)
**What is the expected behavior?**
Should fit the whole screen.
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Version: 5
Browser : Mozilla / Chrome / Opera
OS : Ubuntu 18.04

![Screenshot from 2020-10-25 14-01-05](https://user-images.githubusercontent.com/16412739/97105363-2a5f6880-16cb-11eb-9947-c72c6c828f3f.png)

**Comment by lnewson** [comment]
@AEK-BKF can you please include a [fiddle](https://fiddle.tiny.cloud/), or a way to reproduce this? We can't assist without being able to see why it's not going fullscreen I'm afraid. Also could you please let us know the exact TinyMCE version, as it's possibly something that has been fixed in a newer version of TinyMCE.

**Comment by lnewson** [comment]
Hi, we are closing this as there have been no additional details provided in the last month. If you can provide the details requested above, then we'd be happy to re-open this issue and investigate.
