### ISSUE TITLE
image_list select "None" error

### ISSUE THREAD

**Issue by webdevnerdstuff** [tinymce/tinymce#6150]
**Describe the bug**
When using image plugin feature _image_list_, if you select the default "None" it causes the following error.

`Uncaught (in promise) Failed to get image dimensions`

**Steps to reproduce**
Click on Image icon. Select "None" from Image List. Notice in the console the error.

Example: This occurs on your site as well as mine. https://www.tiny.cloud/docs/demo/full-featured/

**What is the expected behavior?**
Either "None" should not be selectable, or there should be no error if it is selected.

**Which version of TinyMCE?**
TinyMCE v5.5.1

**Comment by lnewson** [comment]
Thanks for the report @webdevnerdstuff! I can confirm that this is a bug and it's caused by the image plugin incorrectly trying to fetch the image dimensions for a blank/empty URL. This shouldn't have any impact to the actual functionality though, so you could safely ignore the console error until this is fixed. Anyways, I've logged an internal issue to get this fixed and we'll let you know when a fix is available.
