### ISSUE TITLE
plugin:link  link_target dom  with release5.5.1 display wrong 

### ISSUE THREAD

**Issue by mallocLNode** [tinymce/tinymce#6151]
**What is the current behavior? Describe the bug**
link_target dom display wrong
![image](https://user-images.githubusercontent.com/26710678/97389111-95e84680-1914-11eb-9782-993db5691e1b.png)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
in my tinymce-vue project,version 5.5.1 displays wrong，when i change it to 5.4.2,it works fine
**What is the expected behavior?**
![image](https://user-images.githubusercontent.com/26710678/97389135-a6002600-1914-11eb-8027-13ee45c6e5c8.png)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
5.5.1 ；chrome/macos10.14.6 /no

**Comment by lostkeys** [comment]
Hi @mallocLNode! This is because the CSS styles for the dropdown doesn't exist in TinyMCE 5.5.1. If you are self hosting TinyMCE you need to make sure you're using the skin css for the same version of TinyMCE that you are using.

This can happen if you are loading the latest version of the TinyMCE javascript file from our cloud or an another CDN and have generated your own skin file that you host yourself.

Please reopen the issue if this didn't solve your issue.

**Comment by mallocLNode** [comment]
@lostkeys thanks for the help.i do generate my own skin file...
since i quoted `"tinymce": "^5.4.2"` in my package.json，when i excuted `npm install`，it automaticly updated to 5.5.1 in node_modules folder...but i forgot to update my local 'public/tinymce/skin' folder...
Again thanks for the help.

**Comment by lostkeys** [comment]
Happy to hear this was the issue. I have tripped over this many times and I spend my days in TinyMCE 😅
