### ISSUE TITLE
I set the height and width of tinymce, but it did not succeed.

### ISSUE THREAD

**Issue by munitioner** [tinymce/tinymce#6161]
I set the height and width of tinymce, but it did not succeed.
my codesandbox project https://codesandbox.io/s/async-surf-srhqk?file=/src/App.vue

**Comment by lnewson** [comment]
Hi @munitioner, the reason the height isn't working is you've enabled the `autoresize` plugin, so the height setting will be ignored. If you want the editor to always be at least 500px you should use the [min_height](https://www.tiny.cloud/docs/plugins/autoresize/#min_height) setting instead.

As for the width, you haven't enabled that in your code sandbox so that's the reason it's not working.

**Comment by lnewson** [comment]
Here's an updated code sandbox showing it working: https://codesandbox.io/s/nifty-christian-jph8h?file=/src/App.vue:1311-1356. The only changes are these 2 lines:
```
min_height: 500,
width: 400,
```

**Comment by munitioner** [comment]
Thanks for your reply, thanks again
