### ISSUE TITLE
How to add the right mouse button to tinymce to copy and paste？

### ISSUE THREAD

**Issue by munitioner** [tinymce/tinymce#6162]
How to add the right mouse button to tinymce to copy and paste？

**Comment by ashfordneil** [comment]
This one is unfortunately a little complex, but there are some options available.

Option 1: Add `copy` and `paste` to the [context menu setting](https://www.tiny.cloud/docs/ui-components/contextmenu/#contextmenu) — this can be unreliable, due to some security concerns (for more info see [here](https://www.lucidchart.com/techblog/2014/12/02/definitive-guide-copying-pasting-javascript/))

Option 2: Use the native context menu — by default it'll come up if you hold control while you right click, but you can also make it the default by setting `contextmenu: false` in your settings

Option 3: Copy and paste using the regular keyboard shortcuts: control C / control V. It's not really what you wanted, I know, but it is reliable and it'll work.

**Comment by munitioner** [comment]
Thank you for your answer

**Comment by aniket-kale** [comment]
> This one is unfortunately a little complex, but there are some options available.
> 
> Option 1: Add `copy` and `paste` to the [context menu setting](https://www.tiny.cloud/docs/ui-components/contextmenu/#contextmenu) — this can be unreliable, due to some security concerns (for more info see [here](https://www.lucidchart.com/techblog/2014/12/02/definitive-guide-copying-pasting-javascript/))
> 
> Option 2: Use the native context menu — by default it'll come up if you hold control while you right click, but you can also make it the default by setting `contextmenu: false` in your settings
> 
> Option 3: Copy and paste using the regular keyboard shortcuts: control C / control V. It's not really what you wanted, I know, but it is reliable and it'll work.

Option 2 And Option 3 are best. Thanks @ashfordneil
