### ISSUE TITLE
 Editor overlays any dropdown tool when I scroll over a vuetify dialog, it helps

### ISSUE THREAD

**Issue by anderson383** [tinymce/tinymce#6164]
It is not a bug but I have not found a property that solves this problem of overlapping of any drop-down tool, I scroll and it gets even if I close the modal it also keeps coming out.

![image](https://user-images.githubusercontent.com/56322216/97815751-5d22d700-1c5e-11eb-8c74-aa26f40155d2.png)

**Comment by Nice2Work** [comment]
I am having a similar issue with this editor, and I was so happy that I found a nice one, anyway, when using the editor in a dialog/modal/anything that pops up, all the dropdowns are failing, After 4 days of testing this now came up and our system is using ONLY dialog boxes for editors (unlike Quill or Jodit not having those issues) tiny does have it, and I wonder if there is a solution for this. 

I am using VueJS, Quasar (front end with their dialog box) but I do remember this issue was already there when I was working with jQuery.

**Comment by lnewson** [comment]
Hi @anderson383 this is a known limitation, as TinyMCE doesn't currently work inside scrollable elements. The improvement to add that is currently being tracked via https://github.com/tinymce/tinymce/issues/5097, so I'm going to close this as a duplicate. I should add there are some workarounds listed in that ticket that may work for you.
