### ISSUE TITLE
Text-align does not work on inline elements

### ISSUE THREAD

**Issue by sgurin** [tinymce/tinymce#6189]
Hi, Got strange behaviour of the editor.

Select all text and change color. After that you can not use text-align property because the whole text is inside inline span.

https://codepen.io/Oplatonova/pen/LYZrWEz?editors=0011

https://prnt.sc/vepfqt

**Comment by ashfordneil** [comment]
This looks like it's caused by a bug in your config. If you look at the difference between your specification:

```typescript
alignright : {selector : 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li,table,img,span', styles: {'text-align':'right'}}
```

and then the relevant section of the builtin alignright format specification:

```typescript
      {
        selector: 'figure,p,h1,h2,h3,h4,h5,h6,td,th,tr,div,ul,ol,li',
        styles: {
          textAlign: 'right'
        },
        inherit: false,
        preview: 'font-family font-size',
        defaultBlock: 'div'
      },
```

you can see that we don't allow the alrignright format to be applied to `span` elements. As your codepen shows, applying the `text-align: right;` style to an inline element like a span won't result in the text being moved to the right of the screen — instead it's moved to the right hand side of the element, which itself stays pinned to the left. If you remove `span` from your selector everything will work as expected, and the formatter will apply the style to a more appropriate element.
