### ISSUE TITLE
a11y: NVDA reads editor's iframe title twice

### ISSUE THREAD

**Issue by JacksonHowe** [tinymce/tinymce#6190]
**What is the current behavior? Describe the bug**

When using NVDA+Firefox and focusing on the editor, the screenreader reads "Rich Text Area. Press ALT-0 for help” twice in a row. This text is the editor's iframe's *title* attribute.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

1. Enable NVDA
2. Using Firefox, open an instance of TinyMCE on a website
3. Navigate through the page until the focus is on the editor
4. The screenreader reads "Rich Text Area. Press ALT-0 for help" twice in a row

**What is the expected behavior?**

When focusing on the editor, the screenreader should only read "Rich Text Area. Press ALT-0 for help" once, not twice.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE v5 using Firefox+NVDA on Windows 10

**Comment by MarcoZehe** [comment]
In an iframe, the document accessible child of the iframe accessible gets the title as the its accessible name. Chrome doesn't do this. So when focus lands within the document, NVDA's hierarchical ancestry reporting kicks in, walking the iframe and document accessibles and noticing that they are different from the previous focus ancestry, and thus reporting both names and roles. Since the name is the same for both the iframe and document accessibles in Firefox, it is reported twice, whereas in Chrome, it is only reported once.
