### ISSUE TITLE
Preview does not show markup outside of the mceTmpl class

### ISSUE THREAD

**Issue by idac73** [tinymce/tinymce#6233]
**Current Behavior**
HTML outside of the `mceTmpl` is not showing in preview, however documentation states it should.
https://www.tiny.cloud/docs/plugins/template/#makingtemplates

**Steps to reproduce with minimal demo**
https://codepen.io/tinymce/pen/eYJMgZR - this is taken from the blog post https://www.tiny.cloud/blog/tinymce-templates/ 
Just add `preview` to the config

**What is the expected behavior?**
The HTML outside of the `mceTmpl`should display in the preview as documented.

**TinyMCE version** 
v5. I am unsure if this worked in a previous version.

**Comment by wendelcosta** [comment]
Hi thrash4life, I’ve ran the Codepen mentioned and I’m trying to understand what is happening here. 
The template plugin has a preview functionality itself, it doesn’t need the preview plugin, which is a separate feature/plugin. 
Could you please give more information on which ‘preview’ functionality are you referring to?

**Comment by thrash4life** [comment]
Hi @wendelcosta thanks for your correspondence. In reference to the question you asked, I understood "preview" to imply the `preview` plugin and not the template's preview frame.

I presumed that if a template contains the `mceTmpl` class, then when a user elects to utilize the `preview` plugin to view authored content within a template, that the user should be able to see the entire template along with the authored content within the `preview` plugin's modal.

This would make sense, so that the user can see the entire experience when utilizing the `preview` plugin.

This presumption was based upon the documentation [here](https://www.tiny.cloud/docs/plugins/template/#makingtemplates) "_All html outside the div will simply be presented to the user in the preview frame._" 

So if the context for the word "preview" in the documentation was to infer the template's preview frame and not the `preview` plugin, then that is where my confusion is rooted. If that is true, perhaps an additional qualifier to the documentation above may resolve any future confusion, such as:  "_All html outside the div will simply be presented to the user in the **template's** preview frame._"

The prevention of markup outside the `mceTmpl` class from being injected into the textarea / authoring space is a fantastic feature.

If the `preview` plugin is functioning correctly by design, that is to say, the `preview` plugin will not show content outside the `mceTmpl` class, then I'd like to promote this bug report to a feature request.

And that feature request would be, "When using the `preview` plugin with a template containing a `mceTmpl` class, the `preview` plugin should render the entire template, and not just the content within the `mceTmpl` class.

**Comment by JamesToohey** [comment]
Hi @thrash4life, thanks for the additional information, it's much appreciated!

I'm just trying to understand your use case a little better so I thought I'd clarify a few things.

We agree that the documentation wording could be improved, so I've logged an internal ticket for that.

Usually, the purpose of the `mceTmpl` class is to provide optional additional content around the template which can be used to give context to the template, rather than actually being markup you would want displayed in your page.

If the `preview` plugin dialog were to render this content, we feel it would break most use cases and misrepresent what is inside the editor.

Sorry to ask for yet more information, but it would be good to understand a little more about the types of markup you would want appearing the template preview, and the `preview` plugin dialog, but not in the editor content itself? Maybe you could provide an example of a template you're using where you would like this behaviour from the `preview` plugin?

**Comment by thrash4life** [comment]
Apologies for the delayed response. Hopefully the following will help clarify.

The word "preview" is being used in two contexts in the following use case.
- When presented like this: `preview`
  - I am referring to the preview plugin.
- When presented as standard text like this: preview
  - I am referring to what the user sees when the `preview` plugin button is clicked. 

### Here is the use case:
- **As a:** 
  - Content author, using the `template` and `preview` plugins to bootstrap content creation in TinyMCE
- **I would like:**
  - The `preview` plugin to render a preview of the template in its entirety, including markup outside the `mceTmpl` class
- **So I can:**
  - Preview the content as it would be viewed by the consumer.
- **I know this is done when:**
  - A content author, creating content using a template that has the `mceTmpl` class, can click the `preview` plugin button and see a preview of the entire template with the authored content, as this preview would be representative of the final product a consumer would see. 

We are using the `mceTmpl` class as intended, we just want the WYSIWYG's `preview` plugin to show the entire template and not just a preview of the content in the `mceTmpl` class.

For instance, we have a template like this:
```html
<html>
<head>
<title>Template</title>
</head>
<body>
<header>Banner text and media (not 🚫 accessible in the WYSIWYG area)</header>
<main class="mceTmpl">User authored content here (✅ accessible to the WYSWIYG area)</main>
<footer>Copyright / Unsubscribe content (not 🚫 accessible in the WYSIWYG area)</footer>
</body>
</html>
```
Inside the WYSIWYG, content authors only see the `mceTmpl` content.
When using the `preview` plugin, they would like to see the entire `<body>` of the template, so they can literally preview what the final product will look like to consumers of the content.

**Comment by thrash4life** [comment]
Hi @JamesToohey - if this issue isn't worth pursuing, that's ok. I've created a workaround for the team without any custom TinyMCE work required.

**Comment by thrash4life** [comment]
Hah! 😆 - So now I'm trying out a hacked version of the `preview` plugin so (referencing the example above) the `header` and `footer` content would appear in the preview modal by placing empty tags with `id` attributes in the template and replacing the `innerHTML` with the desired HTML when the `preview` modal is spawned.
