### ISSUE TITLE
Can I customize context popover

### ISSUE THREAD

**Issue by StarkShang** [tinymce/tinymce#6247]
There are context menu, context form and context toolbar mentioned in document. And is there a custom context popover for personalized demand?
Or is there a way to add custom html component to editor?

**Comment by lostkeys** [comment]
While you can create your own custom context toolbars, TinyMCE does not support loading custom html into a context toolbar (or any other component).

The reason is primarily in the nature of CSS – it's right there in the name: cascading... If the TinyMCE CSS changes, it will bleed into any third party UI injected by developers, possibly breaking it. Sometimes we also need to change the DOM structure of UI components.

While many developers know exactly how handle this, there are many that will hang themselves with all the rope given to them. Also we have a substantial number of customers running TinyMCE off our cloud, thus always running the latest version. If they do custom styling like this, TinyMCE might break for them without warning, and we cannot have that.
