### ISSUE TITLE
Table toobar position problem

### ISSUE THREAD

**Issue by DexterStudio** [tinymce/tinymce#6258]
![image](https://user-images.githubusercontent.com/19588378/99883396-30148380-2c62-11eb-9ec4-5772c6a8b8ef.png)
like this image , when table height bigger then input area , and first row in top ,  the table toobar positon is bad.
how to change  table toobar positon?

**Comment by wendelcosta** [comment]
Hi @DexterStudio , thank you for reporting this. 

We are are aware of this issue and have it logged internally for us to investigate and improve this behaviour for this situation. Please note that this is an expected behaviour as there is no where else for the toolbar to render on this particular scenario.

So that we can try to always improve our product, what would be your expected behaviour?

A current possible workaround for this would be to set the `table_toolbar` to an empty string and configure the toolbar controls in the main toolbar instead, as in this fiddle: https://fiddle.tiny.cloud/PUgaab.

Alternatively, a custom context toolbar can be created that targets the cells which can be seen in https://fiddle.tiny.cloud/qzhaab.

**Comment by lostkeys** [comment]
Hey @DexterStudio, the issue with the table toolbar covering the first couple of table rows has been fixed in the latest version of TinyMCE released yesterday.
