### ISSUE TITLE
Inline editor set max-height the table toolbar is not sticky

### ISSUE THREAD

**Issue by Valgeria** [tinymce/tinymce#6303]
I am using TinyMCE editor. In Inline editor option set "max-height:350px; overflow:auto;" to the editor. Then the table toolbar is not sticky. See the below image.
![image](https://user-images.githubusercontent.com/21060460/100966906-0443a880-3554-11eb-956d-fc69472916ab.png)

Code: https://codepen.io/venkat5299/pen/GRjpLpa

**Note**: If we didn't set "max height" the table toolbar is sticky.

Thanks.

**Comment by JamesToohey** [comment]
Hi @Valgeria, this appears to be an issue with TinyMCE receiving browser scroll events due to `overflow: auto`.

Try adding the following to your TinyMCE config as a workaround (using `editor.dom.bind` ensures this listener is cleaned up by TinyMCE when it is destroyed):

```
  setup: (editor) => {
    editor.on('init', () => {
      editor.dom.bind(editor.getBody(), 'scroll', () => {
        editor.fire('ScrollContent');
      });
    });
  }
```

[Here’s a working example in a Fiddle](https://fiddle.tiny.cloud/00haab)

**Comment by Valgeria** [comment]
@JamesToohey ,
Thanks for your reply. The issue is solved me.

Thanks

**Comment by eytan600** [comment]
I have the same problem, but in Visual Studio Code.
There is another way to solve it? Without TinyMCE?
