### ISSUE TITLE
Accessibility: Keyboard focus on toolbar buttons does not activate tooltip

### ISSUE THREAD

**Issue by jimunoz1990** [tinymce/tinymce#6342]
**Summary:** Keyboard focus on toolbar buttons does not activate tooltip

**Expected behavior:** Keyboard focus on toolbar buttons does activate tooltip

**Browsers/OS affected:**
Tested on:
- MacOS/Windows/Chrome OS
- Chrome and Firefox

![Screenshot 2020-12-14 at 1 17 59 PM - Display 2](https://user-images.githubusercontent.com/2072649/102125233-f709a200-3e0e-11eb-8353-12ee2f0ff42e.png)

**Comment by toni-carlson** [comment]
I would like to +1 this issue. 

I also have some additional information to add:

The editor buttons' tooltips are title elements, but title elements aren’t ideal for accessibility for two reasons:
1. The screen reader reads them out and they usually have redundant content. In this case, there is an aria-label with the same label as the title, which means the screen reader will read the button name twice, such as `Italic, button. Italic`.
2. Title do not show on focus, so additional information for keyboard only (but not screen reader) users is not shown. The information in titles usually is not too important where it needs to be shown, but it’s nice to have and for some users can be very important.

We really should attempt to change these over to a popover instead of relying on the title attribute if we can.

**Comment by toni-carlson** [comment]
@tylerkelly13 Not sure if you are the correct person, but I saw on other tickets that you addressed accessibility tickets. Hoping TinyMCE can review this one!

**Comment by tylerkelly13** [comment]
Hi @toni-carlson !

Unfortunately I can't help, I've moved on and I'm no-longer working on this project.
Hopefully someone will respond to this issue soon :)
