### ISSUE TITLE
codesample plugin is not compatible with prism.js(1.22)

### ISSUE THREAD

**Issue by ikhvjs** [tinymce/tinymce#6354]
code generated by codesample is 
```html
<pre classname="langxxxxx">
  <code>
  </code>
</pre>
```

but prism.js(1.22) format is:
```html
<pre>
  <code classname="langxxxxx">
  </code>
</pre>
```
Test env: Tinymce v5.6.2

**Comment by lostkeys** [comment]
Thanks for you comment. This would be a feature request.

**Comment by lnewson** [comment]
To further add to what @lostkeys said, PrismJS supports both:
```
<pre classname="langxxxxx">
  <code>
  </code>
</pre>
```
and
```
<pre>
  <code classname="langxxxxx">
  </code>
</pre>
```

Per the recommendations though, it's preferred for the class to be on the `code` element instead of the `pre` element so we'll be treating this as a feature request to change to the recommendation or provide a way to configure which element the class is rendered on.
