### ISSUE TITLE
Link & Code Editors not working when using TinyMCE editors inside Bootstrap modals when using Bootstrap v5.

### ISSUE THREAD

**Issue by sigraham** [tinymce/tinymce#6391]
**What is the current behavior? Describe the bug**
When using a TinyMCE editor inside a Bootstrap v5 modal, text inputs shown on the link editor and the textarea shown on the code editor cannot be selected. This seems like it is likely to be the same issue experienced for previous versions of Bootstrap (where Bootstrap prevents focus of elements outside of the open modal) but the fix proposed on this page https://www.tiny.cloud/docs/integrations/bootstrap/ does not work for Bootstrap v5.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
See http://fiddle.tiny.cloud/gRgaab/179 which is a fork of the fiddle linked from the TinyMCE documentation https://www.tiny.cloud/docs/integrations/bootstrap/

**What is the expected behavior?**
Users should be able to select and type in link editors and code editors (and any other TinyMCE inputs shown within TinyMCE dialogs) when TinyMCE editors are rendered inside Bootstrap modals.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Issue found using TinyMCE 5 and Bootstrap v5.0

**Comment by lnewson** [comment]
Hi @sigraham,

Bootstrap 5 is currently still only in beta, so it may not be stable and we don't document it for that reason. Additionally, I'd generally recommend contacting the Bootstrap team with any issues you have like this, as the root cause is that Bootstrap is blocking other dialogs from grabbing focus.

Having said all that though, after having looked through the docs and source code for Bootstrap 5 I see 2 possible options:
- Disable the modal dialog grabbing focus by setting the "focus" setting to false. See https://getbootstrap.com/docs/5.0/components/modal/#options
- Change the workaround we document to listen to native events instead, as Bootstrap 5 appears to have swapped from using jQuery to using native events. Here's a fiddle showing that working: http://fiddle.tiny.cloud/gRgaab/180
