### ISSUE TITLE
Blur event not emitted

### ISSUE THREAD

**Issue by legrottagliegionata** [tinymce/tinymce#6430]
**What is the current behavior? Describe the bug**
Blur event not emitted if click on dev tool panel or windows bar

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
https://fiddle.tiny.cloud/udhaab/7

**What is the expected behavior?**
Blur event

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
All version

**Comment by metricjs** [comment]
Hi @legrottagliegionata, unfortunately this is browser behaviour. The TinyMCE `blur` event only works when you click within the browser window, and the dev tools and window bar are not counted as being within the window. Switching tabs or clicking to another window has the same behaviour.

If you want to listen for a `blur` event for clicks that aren't within the window, you could also listen to `blur` on the window. For example:

```
window.addEventListener('blur', function (e) {
    console.log('native blur');
});
```

Alternatively, you could listen to the `focusout` event instead of `blur`, as it bubbles up. For the differences between `blur` and `focusout`, see the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Element/blur_event).

**Comment by legrottagliegionata** [comment]
Hi @metricjs 

in [this example](https://fiddle.tiny.cloud/udhaab/9) I added an `<div contenteditable="true"></div>`. 
The standard blue event is emitted when i click i windows bar or devTool panel.

Only in tinymce editor blur event don't work correctly. Why?

In the meantime I'll try the focusout event.

Thanks, Gionata

**Comment by metricjs** [comment]
TinyMCE's `editor.on('blur', () => { ... }` is not equivalent to `document.getElementById("blurTest").addEventListener ("blur", { ... })` or `window.addEventListener('blur', { ... }`. TinyMCE's `blur` event is specific to the editor's context, and is only triggered by clicks _within_ the window TinyMCE is in, and the windows bar and dev tools are not considered to be within the window. That's why you would need to listen to `blur` on the window or another element to detect clicks to the dev tools and windows bar, or use `focusout` as it is not restricted like `blur` is.
