### ISSUE TITLE
Fix Passive Violation Warning in Browser Console

### ISSUE THREAD

**Issue by hscstudio** [tinymce/tinymce#6447]
At Tinymce (version 5, maybe version 4 too), You will see warning about [Violation] in dev console, I know someone have report this issue: #4312 https://github.com/tinymce/tinymce/issues/4312, but this issue closed by @fyrkant with this message

> I wouldn't call these errors, maybe more like recommendations from chrome to use modern stuff like passive event listeners? Passive event listeners are not supported by IE11, so it is nothing we will start using in the near future in TinyMCE. Closing this issue as it isn't really an issue.

If you feel bothered by this warning then you can fix it.

In `node_modules/tinymce/tinymce.js` change `target.addEventListener(name, callback, capture || false);` to `target.addEventListener(name, callback, { capture: capture || false, passive: false });`

AND in `node_modules/tinymce/themes/silver/theme.js` change `element.dom.addEventListener(event, wrapped, useCapture);` to `element.dom.addEventListener(event, wrapped, { capture: useCapture, passive: false });`

Or You can crete file dot sh (patch.sh) on Your root project

```sh
sed -i '' 's/element.dom.addEventListener(event, wrapped, useCapture)/element.dom.addEventListener(event, wrapped, { capture: useCapture, passive: false })/g' node_modules/tinymce/themes/silver/theme.js
sed -i '' 's/target.addEventListener(name, callback, capture || false)/target.addEventListener(name, callback, { capture: capture || false, passive: false })/g' node_modules/tinymce/tinymce.js
```

And then run on terminal `sh patch.sh`

Solved :)

**Comment by ashfordneil** [comment]
Hi @hscstudio,

Firstly, I'd like to thank you for contributing to the TinyMCE community. However, we are going to close this issue, because it isn't really an issue with TinyMCE, it's more of a commentary on previously reported issues. Unfortunately we can't use your suggestion on our end, as we need to support some legacy browsers that that won't work for.

In future, we would recommend leaving such comments on the original issue, even if it's closed, especially for workarounds like this. That way all of the info is in one place and is easier for the original contributors to find
