### ISSUE TITLE
How to add inline style for Inline Image with caption

### ISSUE THREAD

**Issue by Rajesh-Thiyagarajan** [tinymce/tinymce#6458]
Editor
![image](https://user-images.githubusercontent.com/67726510/105492361-d5a99a80-5c85-11eb-8385-d84d4e9af1b4.png)

align-center, align-right, etc.. classes are added for Inline image with caption **( while click Justify Center, Left, Right, ALL)**
![image](https://user-images.githubusercontent.com/67726510/105492856-916aca00-5c86-11eb-8f39-04521ef69074.png)

Inline styles are added for Inline image without caption **( while click Justify Center, Left, Right, ALL)**
![image](https://user-images.githubusercontent.com/67726510/105493258-266dc300-5c87-11eb-92ac-645443c68d6e.png)
 
I need a same inline style behavior for Inline image with caption instead or align-center, align-right, etc.. classes

Could you please help me to do that ?

**Comment by JamesToohey** [comment]
Hi @Rajesh-Thiyagarajan, I apologise for the delay in getting back to you with a solution.

This is because the way styles are applied to `img`s and `figure`s is configured differently in the TinyMCE formatter. I have labelled this as a feature request (all formats to use inline styles) for our PM team to look at.

In the meantime, [here is a fiddle](https://fiddle.tiny.cloud/s4haab/2) where I have added manual overrides for the alignment formats to use inline styles. You can see the various pages for more information in the `Description` field in the fiddle.

**Comment by Rajesh-Thiyagarajan** [comment]
@JamesToohey Thanks for your reply.
