### ISSUE TITLE
legacyoutput plugin incompatible with fontsize_formats

### ISSUE THREAD

**Issue by augustography** [tinymce/tinymce#6467]
V5.6.2, entire V5 series

We're using tinymce as an email template editor compatible with older versions of Outlook (2010) which require <font> styling for text link colours to remain as intended on forward/reply.

legacyoutput plugin works fine in tinymce V5, apart from when fontsize_formats are customised.

Including custom font sizes with fontsize_formats with the legacyoutput plugin causes the font size to always be zero `<font size="0">` no matter the font size selected.

This worked fine in 4.9.11.

Example:
https://fiddle.tiny.cloud/t3haab

**Comment by lnewson** [comment]
Hi @augustography,

This is expected, as if you're using the legacy output plugin and overriding the defaults, you are expected to also provide legacy fontsizes. Additionally, there's no way to map the values you've configured to legacy values, so you'll notice in TinyMCE 4 it actually doesn't respect what you've configured and will always use it's default values. That was a bug, as it didn't allow customization and something that was fixed in TinyMCE 5.

If you do want to manually configure it, you'll need to do something like this:
```
fontsize_formats: "10pt=2 12pt=3"
```

**Comment by augustography** [comment]
Ok thanks - that configuration works.

Can Tinymce please update the documentation of https://www.tiny.cloud/docs/configure/editor-appearance/#fontsize_formats to include this manual configuration to override the expected value?

```
fontsize_formats: "10pt=2 12pt=3"
```

Might also be good to include in the migration notes: https://www.tiny.cloud/docs/migration-from-4x/
