### ISSUE TITLE
imagetools_toolbar bug with quickbars plugin?

### ISSUE THREAD

**Issue by bibos** [tinymce/tinymce#6474]
Hi,

It seems there is a bug when using the "quickbars" plugin, and the "imagetools_toolbar", option...
Whatever you put in this last one, you will still have the 3 aligntext buttons shown... ?

You can try here:https://www.tiny.cloud/docs/demo/image-tools/ 

Edit on codepen and just add "quickbars" in the plugins... 

![tiny1](https://user-images.githubusercontent.com/12428556/106151567-c68e8500-617c-11eb-9b80-8a1f8260da88.jpg)
![tiny2](https://user-images.githubusercontent.com/12428556/106151580-ca220c00-617c-11eb-815c-d7feb9f615ab.jpg)

Am I missing something?

**Comment by lnewson** [comment]
Hi @bibos,

This is because there are 2 different context toolbars that are being merged together, as they are both applicable to images. There's the imagetools context toolbar and the quickbars image context toolbar. They are controlled via different settings:
- [imagetools_toolbar](https://www.tiny.cloud/docs/plugins/opensource/imagetools/#imagetools_toolbar) -  this controls the items to the right of the separator, as you've noted.
- [quickbars_image_toolbar](https://www.tiny.cloud/docs/plugins/opensource/quickbars/#quickbars_image_toolbar) -  this controls the 3 items to the left of the separator.

If you don't want the quickbars image context toolbar to show, you can disable it by following: https://www.tiny.cloud/docs/plugins/opensource/quickbars/#exampledisablingthequickimagetoolbar

**Comment by bibos** [comment]
Thanks a lot!
I missed that...

Sorry for the false alert :)
