### ISSUE TITLE
Docuementation: Pagebreak plugin documentation needs to be updated?

### ISSUE THREAD

**Issue by DNWEIJ** [tinymce/tinymce#6531]
Hi, 

trying to use the pagebreak plugin.

Changing the settings to  inserted pagebreak html via the pagebreak_seprator. 
The documentation states: 
'....They enable you to specify how the page break should be generated in the HTML source code.... '
My understanding is that this part is talking about the pagebreak_seperator  AND that i am able to push in my own defined snippet of html being the html seperator.

However, it doesn't matter what i put into the pagebreak_seprator setting, the seperator is always generated the same.
Looking in the code, I see that indeed there is always placed a img tag with a class:

`e.content = e.content.replace(pageBreakSeparatorRegExp, getPlaceholderHtml());`
So to me the text is really unclear on what now actually happens. 
The result of clicking the pagebreak button, is that an img tag is added to the html (looking at it via the browser inspector)

More over:
The pagebreak plugin setting like
tinymce.init({
    pagebreak_separator: '',

Doesn't result in a html where i can find:   BUT instead see an img tag with a mce-pagebreak  class.

Please update the documentation
so it is clear what the purpose is of the pagebreak_seperator (if it still has a purpose) and also change the default value, wich is also not inserted if there is NO pagebreak_seperator defined in the tinmce.init 
It seems now, that the pagerbreak_seperator is used as a `search for and replace with img tag`

HOW TO REPRODUCE:
Go to the code pen of tinymce and add the pagebreak_seperator to the init: 
`tinymce.init({
    pagebreak_separator: '',
`

thnks, 
Daniël

**Comment by lostkeys** [comment]
Hi @DNWEIJ! What you put in the `pagebreak_separator` renders when submitting the data out of TinyMCE while inside the editor it's showing as an image that is not configurable. I agree that in the spirit of WYSIWYG any custom separator should be shown within the editor too. I'll log a internal feature request to look more into that.

To solve your problem here and now, you can create a [custom toolbar button](https://www.tiny.cloud/docs/ui-components/toolbarbuttons/) that inserts any HTML of your choice using the [insertContent command](https://www.tiny.cloud/docs/advanced/editor-command-identifiers/) which will be shown within the editor aswell.
