### ISSUE TITLE
I can't find what I'm looking for: api/tinymce/tinymce.shortcuts.html

### ISSUE THREAD

**Issue by ghazpar** [tinymce/tinymce#6565]
In what circumstances does add or remove return false?

**Comment by JamesToohey** [comment]
Hi @ghazpar, [here is the documentation](https://www.tiny.cloud/docs/api/tinymce/tinymce.shortcuts/#methods) for the `shortcuts` API. 

This page mentions:
```
`add`
Return value
Boolean - true/false state if the shortcut was added or not.

`remove`
Return value
Boolean - true/false state if the shortcut was removed or not.
```

[In your other issue,](https://github.com/tinymce/tinymce/issues/6561) you were receiving `false` on `remove` because the shortcut was not yet registered at the time when you tried to remove it.

Let me know if this doesn't answer your question.
