### ISSUE TITLE
Changing IMG elements via code results in editor displaying correctly, but html in POST with the old src attribute

### ISSUE THREAD

**Issue by ienaxxx** [tinymce/tinymce#6572]
Hello everyone.
When changing DOM elements via code inside the tinymce editor, either via its domQuery component or via JQuery, pointing at the editor's iframe, text elements and other element types seems to work OK, but modifying an IMG element is not working correctly, since the HTML inside the editor is correctly (and visibly) changed, but the value being sent via POST (being a textarea used here, classic-way) does not change (or at least reverse back to original src attribute)

I made numerous attempts, with various methods.
As per you can see in the fiddle example, I also used all of these methods, after element modification:
- ed.setDirty(true);
- ed.nodeChanged();
- ed.save();

to try to "communicate" to TinyMCE that something has changed.

fiddle: https://fiddle.tiny.cloud/t6haab/5    <--- note that examples 2-6 don't work because they need jquery

question on StackOverflow: https://stackoverflow.com/questions/66355369/tinymce-5-doesnt-properly-set-html-sent-in-post-when-changing-img-elements-via

expected behavior: form submission results in correct HTML being sent in POST (as per visible in the iframe)

Env data:
O.S.:          Windows 10
browser:    Chrome 88.0.4324.190 (64 bit) AND Firefox 85.0.2 (64 bit)
tinyMCE Version:    community - self-hosted - 5.7.0

Thank you in advance to everyone that will look into this.

![click_method1](https://user-images.githubusercontent.com/42164549/109516724-cf8ab300-7aa8-11eb-9221-0c51eba669c2.JPG)
![crazyweirdthing_method6](https://user-images.githubusercontent.com/42164549/109516728-d0234980-7aa8-11eb-8d88-09d3d45b4616.JPG)
![initial_state](https://user-images.githubusercontent.com/42164549/109516729-d0234980-7aa8-11eb-9245-0996392b5fde.JPG)
![POST_HTML](https://user-images.githubusercontent.com/42164549/109516731-d0234980-7aa8-11eb-8f68-0d050ee3c6ce.JPG)

**Comment by JamesToohey** [comment]
Hi @ienaxxx, the reason you are seeing this behaviour is due to TinyMCE's internal storage of attributes. In this case, TinyMCE uses a `data-mce-src` attribute to store the image source before setting the `src` attribute on the element to ensure it is not changed by the browser.

We recommend you use the [DOMUtils API](https://www.tiny.cloud/docs/api/tinymce.dom/tinymce.dom.domutils/#setattrib) for manipulations like this, as it allows TinyMCE to perform any additional tasks it needs to when modifying the content, most of which cannot be done after the fact.

**Comment by ienaxxx** [comment]
Hello James,
 thank you very much for your response. Changing data-mce-src works perfectly. I don't understand why this is only for some attributes, but this is my problem.

I Tried to use tinymce's DomQuery in the first function: tst_elementMod_method1(), as you can see in  the fiddle or in the stackoverflow example.

Do you mean I should use tinymce.activeEditor.dom.setAttrib() instead of the .attr() method of the domQuery object, to work just with the src attribute alone and it'll change the other one by itself?

Thank you again. Goodbye.

**Comment by JamesToohey** [comment]
Hi @ienaxxx, 

>Do you mean I should use tinymce.activeEditor.dom.setAttrib() instead of the .attr() method of the domQuery object, to work just with the src attribute alone and it'll change the other one by itself?

That's correct, you can use `setAttrib` from our DOMUtils API to change the `src` attribute and it will handle all the internal attributes automatically, you should not set any of these manually yourself.

**Comment by ienaxxx** [comment]
Understood, thank you very much James.

**Comment by JamesBonney-Iterable** [comment]
I just ran into this issue while using `setAttribs` via the DOMUtils API in version 6.3.1. My implementation is in react (@tinymce/tinymce-react). I was able to modify an image src successfully and it would appear in the editor, but the change was not reflected when saved (the original issue). My solution was to call `focus()` on the editor following `setAttribs`. Otherwise the change would not be realized (unless you also performed some other action like adding text)
```
htmlEditor.current?.dom.setAttribs(selectedImage, attrs);
htmlEditor.current?.focus();
```
