### ISSUE TITLE
Problem with Codesample

### ISSUE THREAD

**Issue by mr-nazari** [tinymce/tinymce#6577]
> *affected page: https://www.tiny.cloud/docs/plugins/opensource/directionality/*

see this image 
https://i.stack.imgur.com/Z9z1C.png

how to solve this problem?

**Comment by mr-nazari** [comment]
Yes this is for codesample plugin. please solve this problem.

**Comment by ashfordneil** [comment]
Hi @mr-nazari,

We've had a similar ticket #6546 come up recently. I've made a note for our product team to investigate ways that we can improve how we handle our codesample plugin (and maybe similar plugins) in RTL environments. I'm going to close this ticket so that we can keep all of that discussion in the once place, but we'll make a note that more than one user is asking for this. You're welcome to comment on or subscribe to notifications on #6546 to be kept in the loop as well, of course.
