### ISSUE TITLE
Media plugin - display issue with videos

### ISSUE THREAD

**Issue by guio12** [tinymce/tinymce#6583]
**What is the current behavior? Describe the bug**

It happens with TinyMCE **5.7.0**, **5.6.2** works fine.

When I use the Media plugin with a youtube video for example (embedded or not), a second preview is displayed below the main one. The second preview is removed as soon as I click anywhere in the page.

![tinymce_1](https://user-images.githubusercontent.com/36823544/109842598-83777400-7c4a-11eb-8690-e359a47d906b.png)

![tinymce_2](https://user-images.githubusercontent.com/36823544/109842700-a30e9c80-7c4a-11eb-8b61-7714da1ae295.png)

 

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

Unfortunately I can't reproduce this issue via your fiddle...

**Comment by lnewson** [comment]
Hi @guio12,

If you're seeing this happening, then it likely means one of the CSS files is failing to load. What you're seeing, according to your screenshot of the DOM, is what is supposed to be an offscreen clone of the element being shown and there are styles for the `mce-offscreen-selection` class that would normally cause that duplicate to appear in an offscreen location so you'd never see it.

As such, can you take a look and see if the `skins/ui/oxide/content.min.css` file is being loaded correctly (or just see if anything is failing to load)? If not, then can you provide more details about your environment, such as:
- What browser you're using?
- Are you using any integrations? (eg React, Angular, Vue)
- Are you using a module loader/bundler? (eg webpack, rollup, etc..)

I should also note there was a regression identified in 5.7.0 that we'll be fixing in a 5.7.1 patch, which may also help with this given you said it worked in 5.6.2. If you're using Tiny Cloud, you can test this by using the `5-dev` channel instead of the `5` or `5-stable` channel.

**Comment by guio12** [comment]
Hi @lnewson, sorry for the delay.

What you're saying about the CSS file/class makes sense but I will show you what I found:

So, 5.6.2 or 5.7.0, the file is loaded properly

![tinymce-offscreen1](https://user-images.githubusercontent.com/36823544/110447532-9e217100-80c0-11eb-99f5-465ca5851cc4.png)

What seems weird considering what you were explaining before is that in 5.6.2, I can't find any (offscreen) clone, so the `mce-offscreen-selection `class is not even used.

![tinymce-562](https://user-images.githubusercontent.com/36823544/110447739-ce690f80-80c0-11eb-8100-b7e95827c272.png)


**More importantly I guess (5.7.0), what I called the second preview (the clone) is removed from the DOM (and not only handled by the CSS class) as soon as I click anywhere on the page.**



Also, this is coming from your fiddle, 5.6.2 or 5.7.0 show no sign of this clone either

![tinymce_fiddle](https://user-images.githubusercontent.com/36823544/110450928-f60da700-80c3-11eb-9e22-b3b558f1b68d.png)

**Comment by lnewson** [comment]
Sorry for the delayed response, but without answers to the questions asked in my first comment and some way to replicate the issue, I'm not sure we can provide much help here.

For clarity, the offscreen element appears when a media, image, etc... element is selected inside the editor.

**Comment by guio12** [comment]
Still not fixed in **5.7.1**, **5.8.0** and **5.8.1**. 

> What browser you're using?

I tried Chrome, Firefox, Opera...

> Are you using any integrations? (eg React, Angular, Vue)

I'm using a custom Vue.js (2.6.12) component 

> Are you using a module loader/bundler? (eg webpack, rollup, etc..)

Yes I'm using Webpack 4.44.2.


Could you help me with that ? I would rather not change my configuration massively since everything worked fine in 5.6.2.

**Comment by guio12** [comment]
Still not fixed in 5.8.2. On top of that, I no longer can use 5.6.2 because of this security issue:
https://www.npmjs.com/advisories/1749

What do you suggest?

**Comment by guio12** [comment]
![tinymce_bug2](https://user-images.githubusercontent.com/36823544/123293564-61b13e00-d514-11eb-8f7e-5a9aadf2f125.png)

**Comment by lnewson** [comment]
That screenshot shows the problem is what I had suggested in an earlier reply. You're not loading the relevant `skins/ui/oxide/content.min.css` file correctly. As you've said you're using webpack, I'm going to assume you're bundling the JS and CSS instead of serving is separate. So to be able to help further, we'd need to see how you're doing that.

As a tip, if you're bundling that you need to use the `raw-loader` or similar to load the content CSS since it's placed inside an iframe. Here's an example that's using vue 2: https://github.com/tinymce/tinymce/issues/2836#issuecomment-544790987

**Comment by guio12** [comment]
Like I said, this worked fine on **5.6.2**, I'm not trying to implement a TinyMCE config for the first time here.

All 3 CSS files (2 + 1 custom) are loaded properly
```
<style lang="scss">
  @import "~tinymce/skins/ui/oxide/skin.min.css";
  @import "~tinymce/skins/ui/oxide/content.min.css";
  @import "./../../../scss/components/Form/HRichText.scss";
</style>
```

To make it work with >= **5.7** I ended up importing the 2 TinyMCE CSS files once again but differently:
```
import contentStyle from '!!css-loader!tinymce/skins/ui/oxide/content.css';
import contentStyle2 from '!!css-loader!tinymce/skins/content/default/content.css';
```
```'content_style': contentStyle.toString() + '\n' + contentStyle2.toString(),```


You could have at least warn about this needed config change under the 'breaking changes' part in the changelog.

Thanks anyway @lnewson

**Comment by lnewson** [comment]
> All 3 CSS files (2 + 1 custom) are loaded properly

This is not the correct way to load the content CSS files. As mentioned above, the content is loaded inside of an iframe, so loading the `content.min.css` will not work, as it will apply to the content outside of the editor, not inside. As it's an iframe, it either needs the stylesheets to be loaded remotely or to be injected via the `content_style` setting. The above is okay to load the skin CSS however.

This is nothing new and has been like this since TinyMCE 4.x, so it's not a breaking change. You would have had this same issue with noneditable elements, etc... before 5.7.0 and it would have also meant that resize handlers wouldn't have been working properly. The thing that changed in TinyMCE 5.7.0 was that media elements got resize support, which meant that the offscreen clone was required so that the media could be clicked, etc... without causing the content to be played.

I should add that we're away the docs are rather lacking in regards to how to use module loaders while attempting to bundle all the content. That issue can be seen in the documentation repo here: https://github.com/tinymce/tinymce-docs/issues/1466. Our documentation team are actually currently working on this as we speak, so there should be some improved documentation up soon.

Anyways, I'm glad you were able to resolve the issue and I'm sorry that you ran into this due to the lack of documentation on this subject. I'll go ahead and close this now, but do let us know if you run into any further issues.
