### ISSUE TITLE
images_upload_handler how to set img alt

### ISSUE THREAD

**Issue by leifen** [tinymce/tinymce#6585]
<pre>
images_upload_handler: (blobInfo, success, failure) => {
      const formData = new FormData()
        formData.append('file', blobInfo.blob())
        uploadImg(formData)
          .then(res => {
            console.log('result:', res)
            if (res.code === 200) {
              const file = res.data
              success(file.url)
              return
            }
            failure('upload fail')
          })
          .catch(() => {
            failure('upload fail')
          })
      },
</pre>

**Comment by lostkeys** [comment]
Hi @leifen. I don't think you can do that through the image upload handler. Since each image is unique and the alt text is there to describe the image, you are supposed to use the image dialog to manually add alt-text. A less intrusive example of adding alt text is to create your own context toolbar form, [here is an example](https://tinymce.github.io/tinymce-demos/images/image-alt-text-context-form.html).

I can repoen this issue and create a feature request for you if you provide some more details into your specific use case and why you need to set the alt text through the upload handler.
