### ISSUE TITLE
I can't find what I'm looking for: index.md

### ISSUE THREAD

**Issue by nicole-wrh** [tinymce/tinymce#6611]
i found a problem about file_picker_callback
when i use it to upload image by iphone, it doesn't work
But it works on other models

**Comment by SimonFc** [comment]
@nicole-wrh Since the [file_picker_callback](https://www.tiny.cloud/docs/configure/file-image-upload/#file_picker_callback) require you to implement specific functionality, could you provide some information on your specific use-case? Preferably create a demo at https://fiddle.tiny.cloud/ and explain in detail the steps required to replicate this issue. What file type are you trying to upload etc. Thanks!

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
