### ISSUE TITLE
bug in firefox

### ISSUE THREAD

**Issue by bone-soup** [tinymce/tinymce#6618]
Paste TXT text in Firefox browser, delete the last empty line, the editor will be at the top and the cursor is still at the bottom.

**Comment by SimonFc** [comment]
Hi, we require more information in order to be able to replicate this issue. Could you:
1. Set up the configuration you have at https://fiddle.tiny.cloud/
2. Provide the content you paste.

Thanks

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
