### ISSUE TITLE
** Enter to <em> 

### ISSUE THREAD

**Issue by lhd-1727865856** [tinymce/tinymce#6626]
For example：
  *AAAA* BBBBB
Enter before A and B *AAAA* Become the _AAAA_ italics

**Comment by lhd-1727865856** [comment]
**

**Comment by SimonFc** [comment]
Hi,

We have the [Text Pattern](https://www.tiny.cloud/docs/plugins/opensource/textpattern/) plugin that provides some basic markdown patters and this can be configured to use a single * for _italic_ instead of two as mentioned in the docs.

> For example：
> _AAAA_ BBBBB
> Enter before A and B _AAAA_ Become the _AAAA_ italics

It's unclear whether this is a bug-report or a feature request of some kind and as such I'll close this. Please comment with more information clarifying the problem or open a new issue that follows the template.
