### ISSUE TITLE
Selection issue in inline editor on mobile only with special characters 

### ISSUE THREAD

**Issue by vishalkanade1** [tinymce/tinymce#6643]
**What is the current behavior? Describe the bug**
when we try to select text with special charater it is not selecting properly to execute command only in mobile devices.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
please see this https://d.pr/v/g8KZcF

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
we have used the latest verion tinymce 5 and it is affted in mobile devices.

**Comment by SimonFc** [comment]
I'm unable to replicate this issue using iOS 14.4.1 with content which I think is the same. Even so, can you set up a demo at https://fiddle.tiny.cloud/ using the exact **configuration** and **content** needed to replicate this. Thanks!

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
