### ISSUE TITLE
menus don't show..

### ISSUE THREAD

**Issue by nicerapp** [tinymce/tinymce#6647]
at https://nicer.app/apps/eyJjbXMiOnsicGFnZSI6ImluZGV4In19 , i try to get a TinyMCE editor going. (version 5.7.1)

however, perhaps due to the fact that i'm loading this into an absolute-positioned DIV, it won't show the dropdown menu to select a different font.

i'm completely stuck, and am hoping for some help..

**Comment by SimonFc** [comment]
This appears to be due to the usage of `overflow: hidden;` on the `<html>` element. TinyMCE is using an external element for putting things like menus and dialogs inside, which is then positioned on top of the editor. If you put `overflow: hidden;` on the `<body>` element instead, TinyMCE's elements will no longer be hidden and it looks like you achieve the same effect on your site in general which I think you were looking for.

I'll close this issue as it does not appear to be an issue with TinyMCE but rather a requirement for TinyMCE. Feel free to comment here if you find something indicates otherwise and I'll re-open it.
