### ISSUE TITLE
How to change header row to normal row?

### ISSUE THREAD

**Issue by Valgeria** [tinymce/tinymce#6648]
Hi,

I am using tinyMCE. I am changing normal table row to header row using the below code. it's working.

```
table_header_type: 'sectionCells',
 
  setup: function(editor)
  {
     editor.ui.registry.addButton('tableheader',
                    {
                        icon: 'table',
                        tooltip: "Header Table",

                        onAction: function(api)
                        {
                            
                      editor.execCommand('mceTableRowType', false, { type: 'header' });

                        }
     });    
  }
```
See below image:
**### ![image](https://user-images.githubusercontent.com/21060460/111777379-3ac1eb00-88d9-11eb-89a9-f87904a7d568.png)**

Code : https://codepen.io/venkat5299/pen/GRjpLpa

I want to change again header row to normal row. Is possible in tinyMCE? Is there any option in tinyMCE?

If exist please suggest me.

Thanks.

**Comment by HAFRMO** [comment]
Hello.
You should be able to simply use the same command, but use `'body'`instead of ''header'` for it to work, see the command in https://www.tiny.cloud/docs/plugins/opensource/table/#commands
Additionally you may need to be aware of your settings on table_header_type ( https://www.tiny.cloud/docs/plugins/opensource/table/#table_header_type ) to get the result you expected.

**Comment by Valgeria** [comment]
@HAFRMO 
Could you please try with below snippet.

Code : [https://codepen.io/venkat5299/pen/GRjpLpa]

Thanks

**Comment by HAFRMO** [comment]
You are currently using `editor.execCommand('mceTableRowType', false, { type: 'header' });` to make a row into a header. Using `editor.execCommand('mceTableRowType', false, { type: 'body' });` will change it away from a header.
Just be aware that this behavior may change due to the `table_headertype`, though it works as intended on the codepen example you provided.
To use the code provided in the first post, the following code should provide you with a button to add to the toolbar that does what you want if added to the setup:
```
editor.ui.registry.addButton('tablebody',
{
  icon: 'table',
  tooltip: "Body Table",

  onAction: function(api)
  {
    editor.execCommand('mceTableRowType', false, { type: 'body' });
  }
});
```
