### ISSUE TITLE
Adding custom component in editor.ui.registry.addAutocompleter

### ISSUE THREAD

**Issue by shrnetomi** [tinymce/tinymce#6669]
**Is your feature request related to a problem? Please describe.**
Unable to add already created Vue component in autocompleter

**Describe the solution you'd like**
Code can be written such a way that it would render Vue components in tinymce autocompleter.

**Describe alternatives you've considered**
Adding customise css may help.

**Comment by JamesToohey** [comment]
Hi @shrnetomi,

Unfortunately the TinyMCE autocompleter cannot natively support Vue components. Items in the autocompleter must abide by TinyMCE's consistent styling for various reasons, including accessibility.

Could you elaborate more what you are trying to achieve?

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
