### ISSUE TITLE
Support shadow DOM

### ISSUE THREAD

**Issue by ghost** [tinymce/tinymce#6674]
Does TinyMCE support shadow DOM? It doesn't seem to, but let me know if there is something I missed. As long as it does not support shadow DOM, it cannot be used with frameworks like Lit-Element.

**Comment by JamesToohey** [comment]
Hi @yujiri8, at this stage Shadow DOM support is experimental in TinyMCE >5.5. We'd love to hear more about your specific use case to help us with further improvements.

**Comment by samuelvernon** [comment]
Hi James,

I implemeted the tinymce editor in the shadow dom with fixed_toolbar_container_target like this:

```
tinymce.init( {
  target: item, // <-- item was created before
  toolbar: true,
  inline: true,
  menubar: false,
  statusbar: false,
    fixed_toolbar_container_target: toolbar // <-- toolbar was created before
} );
```

It works fine until I hit the ENTER or TAB key or I click a button in the toolbar. Then the editor looses the focus and it starts to write in the body of the document instead.

Here is an example https://jsfiddle.net/g31f7uqm/

Any ideas how to fix the issue? Thank you!

**Comment by lnewson** [comment]
Hi @samuelvernon, I'm afraid at this stage TinyMCE only has experimental Shadow DOM support for classic/iframe editors. This is largely because the browser selection APIs either don't exist or don't yet implement the same functionality for Shadow DOM as they do for regular windows/documents and as such inline editing unfortunately isn't possible at this stage. We're keeping an eye on the browser APIs as they evolve, but they are still in planning stages in the relevant working groups at this stage.

See https://github.com/tinymce/tinymce/issues/6158#issuecomment-719872983 and https://github.com/tinymce/tinymce/pull/4737#issuecomment-719317085 for more information.

**Comment by yujiri8** [comment]
Sorry for not getting back to yall.

> Hi @yujiri8, at this stage Shadow DOM support is experimental in TinyMCE >5.5. We'd love to hear more about your specific use case to help us with further improvements.

Sorry for not getting back to you. To answer the question, I am developing a commercial web service that needs to offer WYSIWYG for users to write HTML emails, but the app is built in Lit-Element, with the whole thing inside shadow DOM. For the time being, I've figured out a way to use Quill (which doesn't support shadow DOM) by putting it in the top level DOM and passing it down through multiple levels of `<slot>`s.
