### ISSUE TITLE
How do I insert to the end by using  `editor.insertContent` ?

### ISSUE THREAD

**Issue by ttttttssssss** [tinymce/tinymce#6694]
**Documentation/Product Version**
TinyMCE 5 Documentation

**Related page URL (if applicable)**
https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#insertcontent
**I would like to know...**
+ `editor.insertContent(<p>hello</p>);` This function will be inserted at the beginning. So how do I insert to the end？
+ The second parameter is ambiguous. =>`args (Object) - Optional args to pass to insert call.`

**Comment by JamesToohey** [comment]
Hi @ttttttssssss,

As a follow up to what @tylerkelly13 has said, you can change your selection using the [`editor.selection.setCursorLocation`](https://www.tiny.cloud/docs/api/tinymce.dom/tinymce.dom.selection/#setcursorlocation) API so that when you call `editor.insertContent()` the new content will appear where you want it.

Here is an example (note I've commented in some extra functionality you may wish to include to improve user experience): https://fiddle.tiny.cloud/b9haab

**Comment by ttttttssssss** [comment]
Thanks for @JamesToohey 's example. It helps me a lot.
