### ISSUE TITLE
Table - advanced editor

### ISSUE THREAD

**Issue by itajackass** [tinymce/tinymce#6695]
I'd like to add a "CSS margin-top/bottom" to tables using GUI interface.
Sometime I need to insert 2 table (one next the other one): if I use a brealine or a new empty paragraph to add a "space" between the tables....the space is too much. If i don't insert anything in the middle...tables are too much closer.
I need to edit html code manually to insert a margin-bottom:10px to first table.
I'd like possibility to insert margin using GUI.

**Comment by lnewson** [comment]
Hi @itajackass, thanks for the submission. I can confirm there's no way to configure margins for tables outside of using the code view dialog to manually add them. As such, I've marked this as a feature request for our Product Team to review.

**Comment by lostkeys** [comment]
Would the following CSS solve your problem? 
```
table + table {
    margin-top: 10px;
}
```

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
