### ISSUE TITLE
select multiple cells on table tinymce mobile

### ISSUE THREAD

**Issue by eranga93** [tinymce/tinymce#6708]
**Is your feature request related to a problem? Please describe.**
cannot select multiple cells on table in the mobile view

**Describe the solution you'd like**
being able to select multiple cells on table and apply changes

**Describe alternatives you've considered**

**Comment by SimonFc** [comment]
Just so that we're on the same page: a cell selection is done by double clicking on a single cell on touch devices and its this feature which isn't working for you (this isn't about the table picker which is [disabled](https://www.tiny.cloud/docs/mobile/#mobiledefaultsforselectedsettings) on mobile devices)

What device, browser and version are you using? Thanks.

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
