### ISSUE TITLE
Font style, color change is not triggering change event

### ISSUE THREAD

**Issue by codTango** [tinymce/tinymce#6749]
**What is the current behavior? Describe the bug**
After set some new content within the editor, changing of font style and color won't trigger change event for the first time.

https://fiddle.tiny.cloud/hAhaab
With this demo, after run the demo, here are the steps to reproduce:
1. open developer console
2. select a word and change its font or color
2. inspect devtool, it logs the changed content in console
3. click "Change Content" button, it resets a new content to editor
4. select a word and change its font or color

**What is the expected behavior?**
**Expectd**: it changes the font or color for the word, and it logs the changed content in console on devtools again
**Actual**: it changes the font or color for the word, but it doesn't log the changed content in console on devtool. But it will trigger change event next time when you change font or color.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE@5.7.0 on Chrome@89; it has the same issue with TinyMCE@5.6.2

**Comment by lnewson** [comment]
Hi @codTango,

This is expected behaviour due to the way you're somewhat incorrectly resetting the editor. The problem is that you're clearing the undo history, but you're not adding back an initial state. As such an initial state is created on the first change (in this case you change the font/color). If you change that to either ensure an initial state is added using `undoManger.add` or use the `resetContent` API (recommended) then it'll work as expected.

Here's an updated example using the `resetContent` API which works as expected: https://fiddle.tiny.cloud/hAhaab/1

**Comment by codTango** [comment]
Got it, thanks so much!
