### ISSUE TITLE
I think I found an xss bug

### ISSUE THREAD

**Issue by ShayneWilliams** [tinymce/tinymce#6764]
**What is the current behavior? Describe the bug**

Okay so I was using tinymce with my app, and I hadn't yet gotten to sanitizing the code, because I thought it would be handled, and to a certain extent it was. But then I saw that I was able to embed a youtube video in one of my entries. So to see if this was the desired behavior, I made another entry and tried to copy over the embed iframes, but realized it wasn't allowing it through, because it was being sanitized. Meaning that The first entry that has the video being rendered as an iframe rather than just text wasn't sanitized properly for some reason or another. Instead of keeping it to myself, I figured i'd let everyone know. Also I discovered this page when I copied a webpage into my app, so maybe that had something to do with it. 

The screenshot has what it looks like, the documents have the actual code going on behind the scenes.
![xss screenshot1](https://user-images.githubusercontent.com/65196635/115974245-31e3bb00-a510-11eb-99e3-bd2aa44528ac.png)
[xss doc1.txt](https://github.com/tinymce/tinymce/files/6370857/xss.doc1.txt)
[xss doc2.txt](https://github.com/tinymce/tinymce/files/6370858/xss.doc2.txt)

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

I'm using version 5.7.1

**Comment by ashfordneil** [comment]
Thank you for bringing this matter to our attention.

We have assessed the issue and have concluded this isn't an XSS vulnerability in the product. We believe that the cause is likely to be related to content encoding outside of TinyMCE itself. If you were to provide more detailed information on how to reproduce the issue, that would help with further assessment.

If you'd like to follow-up on this issue or provide more information, please do so by emailing infosec@tiny.cloud. Please see [Reporting TinyMCE Security Issues](https://www.tiny.cloud/docs/advanced/security/#reportingtinymcesecurityissues) for more information.

Thanks again for your help in ensuring the security of our products.
