### ISSUE TITLE
font-family: 'Times New Roman' generates SQL syntax error

### ISSUE THREAD

**Issue by jmatbastos** [tinymce/tinymce#6770]
Bug:
font-family: 'Times New Roman' generates SQL syntax error
`<span style="font-family: 'Times New Roman';">`

Expected behavior:
`<span style="font-family: &quot;Times New Roman&quot;;">`

**Comment by spocke** [comment]
If you get and SQL error if the html has single quotes in the content it suggest to me that the SQL query parameters is not correctly escaped and that you might have a SQL injection security issue on your hands. This error is likely happening if you disable the editor and use a plain textarea with a single quote as well. I'm closing this ticket since this is an error generated on the server and highly likely a implementation issue rather than a bug or issue with tinymce.
