### ISSUE TITLE
dropped file type is not supported / drag&drop image doesn't work.

### ISSUE THREAD

**Issue by n1crack** [tinymce/tinymce#6797]
**What is the current behavior? Describe the bug**

When I drag and drop an image to tinymce, I get an error. "Dropped file type is not supported.".  Image upload is working other than drag & drop. Everything else is ok.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

[https://www.tiny.cloud/docs/tinydrive/introduction/#demo](https://www.tiny.cloud/docs/tinydrive/introduction/#demo)

**What is the expected behavior?**

When I drag and drop an image, I expect the file to be inserted to tinymce.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

I don't remember.

another example : 

[https://www.tiny.cloud/docs/demo/local-upload/](https://www.tiny.cloud/docs/demo/local-upload/)

![image](https://user-images.githubusercontent.com/712404/117391578-ddb9dd00-aef8-11eb-864d-19912c1e6065.png)

**Comment by AnujShr** [comment]
Is there any fix or workaround for this issue?

**Comment by gzalo** [comment]
I'm having the same issue 😞

**Comment by t2nel** [comment]
After a lot of trial and error, I got it working by adding _paste_ plugin and _paste_data_images:true_
If you use _images_upload_url_ option, it will also post it to backend. 

https://fiddle.tiny.cloud/eLhaab
`<script type="text/javascript">
tinymce.init({selector: "textarea", plugins: ["paste"], paste_data_images: true});
</script>
<textarea></textarea>`

It is still either a bug or documentation issue, because if you follow the documentation and demos, it doesn't work.
