### ISSUE TITLE
indent source code option

### ISSUE THREAD

**Issue by insinfo** [tinymce/tinymce#6840]
it was ideal to have an option to indent the output HTML code
as this facilitates code editing by switch code editing and visual editing

**Comment by lostkeys** [comment]
Hi @insinfo! can you clarify what you mean by "output", do you mean the source code view or the form data submitted out of TinyMCE?

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
