### ISSUE TITLE
Need Download as word

### ISSUE THREAD

**Issue by shancasperon** [tinymce/tinymce#6881]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by lostkeys** [comment]
Hi @shancasperon! While i can sort of figure out what you want, I need some more details before I can properly address your feature request. Can you elaborate on your use-case?

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.

That said, Export to Word document is planned as a premium plugin for TinyMCE 7 so stay tuned over at https://tiny.cloud
