### ISSUE TITLE
`fgid` div tag attribute

### ISSUE THREAD

**Issue by binaryRex** [tinymce/tinymce#6895]
Hi, I currently have a web application using the editor and I noticed that for some of our users, their text conten contains this `fgid` attribute in the following format:

`<div class="paragraph" fgid="80981">some text content added</div>`

However, this behavior cannot be replicated from the development team, and so I do want to check 
1. if this attribute is introduced by the editor?
2. if so, under what circumstances will it be introduced?
3. what are some of the ways that we can prevent the editor from producing such attributes?

Currently I am using the following version "@tinymce/tinymce-vue": "^3.2.8",

Thanks a lot!

**Comment by lnewson** [comment]
Hi @binaryRex, I can confirm the editor doesn't produce this attribute in any form. It's likely being added by certain users browser extensions, as that's where we've seen strange attributes or elements come from previously.

As for removing it, https://stackoverflow.com/a/67344188/11275515 is a similar StackOverflow question. In this case, if you want to clean it up using TinyMCE I'd suggest using an attribute filter instead of a node filter like so:
```
setup: (editor) => {
  editor.on('PreInit',() => {
    // Create a custom attribtue filter to remove unwanted content when getting content from the editor
    editor.serializer.addAttributeFilter('fgid', (nodes) => {
      nodes.forEach((node) => node.remove());
    });
  });
}
```
and here's a working example: https://fiddle.tiny.cloud/cFhaab

**Comment by binaryRex** [comment]
Hi @lnewson, thanks for the confirmation and the suggested solution :)
