### ISSUE TITLE
Weird copy and paste behavior with wrappers with custom element block

### ISSUE THREAD

**Issue by Hellysonrp** [tinymce/tinymce#6943]
**What is the current behavior? Describe the bug**
I'm creating a custom element to use as wrapper for some data that will be processed afterwards.
Consider this HTML:
```html
<my-custom-block>
    <p>copy me!</p>
</my-custom-block>
```
If you copy the text inside `p` and paste anywhere in `p` (even overwriting the text itself), `my-custom-block` will be copied with the text, resulting in an unexpected behavior.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
https://fiddle.tiny.cloud/nGhaab

**What is the expected behavior?**
If `my-text-block` is replaced with another block, such as `div` or `blockquote`, this won't happen.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5.8.1
Google Chrome 93.0.4535.3 (Official Build) dev (64-bit) (cohort: Dev)
Windows 10 OS Version 1909 (Build 18363.1379)

**Comment by halfninja** [comment]
Not just direct parent, it seems to copy _all_ custom element ancestors, so we have a `layout-row` containing `layout-col` items and the pasted text is inside a new single `layout-col` in a new `layout-row`.

**Comment by danderozier** [comment]
After some digging, I think I found the underlying issue. When a selection is copied, TinyMCE serializes its contents into HTML During this process, it checks whether any a selected node's parents are "wrap" elements. Any parents that are "wrap" elements are included in the serialized HTML.

"Wrap" elements include `<pre>`, headings, and inline elements. Presumably this is what allows copy/paste within or across node boundaries.

See `getSelectionFragment()` and `getWrapElements()` here:
https://github.dev/tinymce/tinymce/blob/develop/modules/tinymce/src/core/main/ts/selection/FragmentReader.ts#L48

The problem is that during this check, TinyMCE relies on a hard-coded list of block elements to determine whether an element is block or inline, and since custom elements aren't in the list, TinyMCE treats them as inline elements, which in turn are 'wrap' elements and thus included in the serialized HTML for copy.

See `isWrapElement()`, `isInline()` here: 
https://github.dev/tinymce/tinymce/blob/develop/modules/tinymce/src/core/main/ts/dom/ElementType.ts#L55

**Comment by lixaotec** [comment]
In fact i was looking for this behavior, but it seems i cannot copy with the underkining html custom elements 
How can i achieve that? I wish to set and keep hidden html tags and properties  and make them copyable within the text .. for pasting ahead
