### ISSUE TITLE
Custom addContextMenu not working

### ISSUE THREAD

**Issue by HereThereBDragons** [tinymce/tinymce#6960]
addContextMenu broke (?) between 5.7.0 and 5.7.1

TinyMCE Fiddle: https://fiddle.tiny.cloud/gohaab

Additional right-click context menu displays on 5.7.0, not on 5.7.1+ (including current version 5.8.1

Probably related to these 'bug fixes':
- Fixed a bug where context menu items with names that contained uppercase characters were not displayed.
- Fixed context menu items lacking support for the disabled and shortcut properties.

(This fiddle is from the tinyMCE blog: https://www.tiny.cloud/blog/tinymce-spellchecker/)

**Comment by HereThereBDragons** [comment]
Repro:
- set fiddle to run with TinyMCE 5.7.0
- right-click in editor to see custom context menu
- set fiddle to run with TinyMCE 5.7.1+
- right-click in editor - no custom context menu

**Comment by lnewson** [comment]
Hi @HereThereBDragons, thanks for the report! I can confirm this is working as expected though. The problem is actually in the custom `useBrowserSpellcheck` context menu in the fiddle provided/mentioned in our blog, as its returning invalid data. As per the [documentation](https://www.tiny.cloud/docs/ui-components/contextmenu/#registeringcontextmenusections) the update function should return a string or an array of menu items to show, not a boolean.

So the problem here was that in 5.7.0, it was never using the context menu and was only ever using the regular menu item that used the same name. Now we have two options, we can either remove the context menu altogether which will make it work the same as 5.7.0 or lower, or we can fix the context menu so it does what I believe it was intended to do which is only show when the selection is collapsed. Here's an example: https://fiddle.tiny.cloud/gohaab/9.

Thanks for bringing to our attention that the blog is incorrect! I'll pass this onto the correct team to get the blog post fixed.

**Comment by RobinJoe** [comment]
Hello @HereThereBDragons, thanks again for brining this up, I've made the change to our blog post. Thanks to @lnewson for sorting out the solution. The changes should be live now at https://www.tiny.cloud/blog/tinymce-spellchecker/.
