### ISSUE TITLE
Support for JS events

### ISSUE THREAD

**Issue by Vipin-R-Bharadwaj** [tinymce/tinymce#7199]
The js events defined in script editor are being stripped on saving the content. Adding the code in valid_elements are also not helping.

**Comment by lorenzo-pomili** [comment]
Hello @Vipin-R-Bharadwaj

I may not understand well how to reproduce the issue could you please provide a [fiddle](https://fiddle.tiny.cloud/) with an example?

Thanks

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
