### ISSUE TITLE
autoresize makes toolbar2 use fixed position?

### ISSUE THREAD

**Issue by joyously** [tinymce/tinymce#7210]
**What is the current behavior? Describe the bug**
When using the skin creator at http://skin.tiny.cloud/t5/ I chose the autoresize plugin and specified toolbar1 and toolbar2. Since the editor doesn't take up the entire page (very common), scrolling the page shows that the second toolbar is fixed to one spot and doesn't scroll.

**Expected behavior**
The toolbar should scroll with the rest of the interface.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
whichever version is being used at http://skin.tiny.cloud/t5/ right now

**Comment by metricjs** [comment]
Hi @joyously, I had a quick attempt at replicating this and wasn't able to. I made a [fiddle](https://fiddle.tiny.cloud/KNhaab) to show the config I tried - is this what you did too? Also, what browser and OS are you using? I'm wondering if this might be browser specific.

**Comment by joyously** [comment]
Hi, it seems to be behaving differently now. I tried all sorts of things on the fiddle and never got it to reproduce. But at the skin tool site, I see it.
1. click Reset to Defaults 
2. click the 3 dots on the menu to show the second row
3. scroll the page
The second row is fixed position. I expect it to scroll as it does on the fiddle page.
It's probably something on the skin page itself, but I was having this trouble in my integration so I thought I'd report it.

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.

**Comment by joyously** [comment]
I think you missed the "more info" I provided back in 2021.
I just tried it again (whatever version is on the skin test site) and it still has the problem.
I'm using the latest Firefox on Ubuntu 22.04 LTS.
![Peek 2024-02-19 09-23](https://github.com/tinymce/tinymce/assets/7957680/dba9f5ec-0e21-40e5-af48-b1463d1724ef)

**Comment by TheSpyder** [comment]
TinyMCE 5 has passed end-of-life and that skin tool will be taken down at some point. I appreciate your efforts in updating the replication information, but the fix for integration scenarios like this ([ui_mode](https://www.tiny.cloud/docs/tinymce/latest/ui-mode-configuration-options/#ui_mode)) is a TinyMCE 6 feature.
