### ISSUE TITLE
Custom plugin image placeholder attribute ("data-mce-placeholder") stripped from source code

### ISSUE THREAD

**Issue by shanereichart** [tinymce/tinymce#7211]
I'm not certain I've identified a bug. I may have misunderstood the purpose of the "data-mce-placeholder" attribute.

We have a custom slideshow plugin which inserts a single image placeholder into the editor with the "data-mce-placeholder" attribute. This attribute nicely prevents the inbuilt "Images" plugin from recognizing the inserted image within the editor, so TinyMCE doesn't highlight the "Insert/edit images" button when the placeholder is selected/highlighted.

Everything works as expected until the View Source is saved, or the page is saved (and TinyMCE handles the POST to our server). In either case, the "data-mce-placeholder" attribute is stripped out by TinyMCE. It is obviously by design, but I don't understand why. I'm hoping there is a way to either prevent it from being stripped, or a better way to dynamically disable the Images tool in the editor when one of our placeholders is selected/highlighted.

**Comment by metricjs** [comment]
Hi @shanereichart, 

`data-mce-placeholder` is very much meant to be internal use only - any attributes starting with `data-mce-` are. That's why it will be stripped out on `getContent`, which is also why it is removed in View Source and such. 

Instead, you probably want to do something similar to what our Emoticons plugin does with emoticon images - you can see an example [here](https://github.com/tinymce/tinymce/blob/58cfb8d37093229bc3621a05c0bfd009e0086f42/modules/tinymce/src/plugins/emoticons/main/ts/core/Filters.ts#L14).

You can set up a Parser filter like this during `PreInit`, and it will run whenever `setContent` or `insertContent` is run. This allows you to add a custom attribute of any name which will persist at `getContent`, and the relevant internal attributes are re-added on `setContent` based on the existence of that custom attribute. It also means TinyMCE is handling the setting of the internal attributes a bit more than how you're probably doing it right now, which is possibly a bit safer. :)

**Comment by shanereichart** [comment]
@metricjs Thanks! We'll take a look at that and update this issue accordingly.

**Comment by shanereichart** [comment]
@metricjs This does address our need. Thank you!
