### ISSUE TITLE
Way to Filter Output for Content Insertion

### ISSUE THREAD

**Issue by lsycxyj** [tinymce/tinymce#7294]
Do you want to request a feature or report a bug?
Feature

What is the current behavior?
There's no way to filter output for content insertion. For example, when an img is inserted using image plugin, there's
no way to add custom style to it.

What is the expected behavior?
Having an API or option to define and use filter/hook to customize the output of mceInsertContent or some  specified cases to intercept output (eg. Insert Media / Image).

Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?
5.8 / Any OS

**Comment by lsycxyj** [comment]
The filter API may be like this:
https://github.com/lsycxyj/tinymce/tree/feature/filters

**Comment by lnewson** [comment]
Hi @lsycxyj,

This should already possible via 2 existing mechanisms:
- Editor Events
- Parser filters

**Editor Events**
This is done by using the `BeforeSetContent` event, which can be found here: https://www.tiny.cloud/docs/advanced/events/#editorcoreevents.

Here's a basic example of how the content can be changed via this mechanism (it adds a new line to the content):
```js
tinymce.init({
  ...
  setup: function(editor) {
    editor.on('BeforeSetContent', function(e) {
      e.content += '<p>*&nbsp;</p>';
    });
  }
});
```

We can further detect if this is being used for `editor.insertContent()` instead of the `editor.setContent()` API by inspecting the `e.selection` property from the `BeforeSetContent` event (Note: This will also be true if using the `editor.selection.setContent()` API).

**Parser filters**
This allows more fine grained processing, as it's run after `BeforeSetContent` is fired and once the content has been parsed into an Abstract Syntax Tree (AST), so it lets you process the tree for specific nodes. This can be done by using the `editor.parser.addNodeFilter()` or `editor.parser.addAttributeFilter()`: https://www.tiny.cloud/docs/api/tinymce.html/tinymce.html.domparser/. This is built around the `Node` API which is what's used to represent the AST: https://www.tiny.cloud/docs/api/tinymce.html/tinymce.html.node/.

Here's a basic example of how the content can be changed via this mechanism (it removes `colspan` elements):
```js
tinymce.init({
  ...
  setup: function(editor) {
    editor.on('PreInit', function(e) {
      editor.parser.addNodeFilter('colgroup', function(nodes) {
        nodes.forEach(function(node) {
          node.remove();
        });
      });
    });
  }
});
```

Have you tried using either of these and if so are they missing something that you require?
