### ISSUE TITLE
The slowest part of TinyMCE: SaxParser

### ISSUE THREAD

**Issue by thecodrr** [tinymce/tinymce#7341]
**What is the current behavior? Describe the bug**

I am not sure if anyone will take notice here but TinyMCE is _slow_. It is slower than it should be — not because of some magic but because of the way somethings have been coded.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

Paste a document with around 2k nodes (paragraphs). Styling doesn't matter. Just paste around 10-15k words. Then try to type something. You'll notice a slight lag. It isn't anything too bad. Now copy/paste the whole content around 10 times. Maybe 20 times. You'll feel the performance go down incrementally.

**What is the expected behavior?**

It should be _fast_. Faster than it is right now.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Doesn't matter. The Sax Parser has only gotten worse.

---
That's with the template. Now. Off to the real issue here.

_Before I begin, I must make myself clear. I am not here to rant or anything. I truly, really, appreciate what TinyMCE folks have done here but..._

But _performance_ is/was clearly not a goal. If someone takes a cursory look over the whole codebase, they'll notice how "freely" `Regex`es are being used. By freely I mean, stuff like this:

https://github.com/tinymce/tinymce/blob/HEAD/modules/tinymce/src/core/main/ts/api/html/SaxParser.ts#L364-L373

This gets created and compiled on **every single function call**. Why not just put in the global namespace and save us all the trouble? Clearly, there is nothing "dynamic" in it.

Anyway, that isn't even the worst part.

I ran a basic profile to see what was actually slowing TinyMCE down...only to find out that `SaxParser` is parsing the **whole goddamn html document** on every single action. Seriously. And not even once. TWICE!

You might be wondering. What constitutes as an "action" here. Well, as far as I know, copy/pasting, _focusing_ the editor (yes!), typing a single letter in the document. I am happy Scrolling is not a part of it.

Alright. You might be able to convince me that calling the parser is necessary on every single action. But you cannot justify how slow it is. Run it a 1000 times on every action, I really don't care, but at least it should be fast so the whole browser doesn't crash.

And all this is due to carelessness. A simple google search for "sax parser" returns multiple parsers that can easily parse a good sized document per 1ms. Why not just use/modify those to handle TinyMCE use-case? Clearly, the one TinyMCE has right now is probably the slowest one around (I haven't benchmarked it yet).

---
I have went over the parser code and everything else. Here's what I don't understand: why not only parse a part of the document? Oh it is relatively hard to do but you can save so many seconds of CPU work by working on only the node that has changed. There will be cases where the whole document or multiple nodes will change, of course, but I don't see why they cannot be handled?

If that cannot be done then at least apply some sort of caching. Most of the times, the document is growing. It is very rare that a person would erase the whole document.

And if even that cannot be done, why not just use a 3rd party SaxParser that is faster?

---

Parsers are hard to get right and harder to get fast. I am not here to complain about why TinyMCE is slow — I know why it is slow. Please don't throw a "if you got an issue, just open a PR" at me. I am here to discuss ideas and possible ways to improve TinyMCE's performance. I don't think that is an impossible feat and with a little bit of effort it can be done.

**Comment by TheSpyder** [comment]
Hi,

Thank you for your detailed thoughts. I wanted to take my time and respond to this properly.

We are already working on a project to replace SaxParser; it has become difficult to maintain, adds to our bundle size and has been a constant source of security flaws. However it is not slow. When we evaluated alternatives, popular JS libraries to parse HTML, they were all quite a bit slower. What you have to realise is our parser doesn't just parse, it also forms a sanitisation layer to protect our users - so we aren't purely measuring the few milliseconds a good parser takes to read the string.

What we're currently aiming for is a swap to the built-in browser [DomParser](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) then adding [DomPurify](https://www.npmjs.com/package/dompurify) to sanitise. The first stage of this is already in PR:
https://github.com/tinymce/tinymce/pull/7337

The problems you are describing seem to be more about how often the parser is run rather than an intrinsic performance issue with the parser itself. Micro-optimising things like how often a regex is compiled won't make any noticeable difference.

We are not able to replicate the parser executing on focus - and it shouldn't really be running as the user types, either, but the document does need to be serialised to store the undo history which can be slow. If you have replication steps that demonstrate the parser running in unexpected places we're happy to take a look at whether those can be addressed.

Regarding your statements about partial work:

> I have went over the parser code and everything else. Here's what I don't understand: why not only parse a part of the document? Oh it is relatively hard to do but you can save so many seconds of CPU work by working on only the node that has changed. There will be cases where the whole document or multiple nodes will change, of course, but I don't see why they cannot be handled?

You might be confusing the terminology here. A parser (technically a lexer, but lexing tends to be included with parsing) takes a string and produces a document; parsing "a part of the document" doesn't really make sense.

The sorts of things you seem to be asking for here really require moving away from ContentEditable as a document store, which is an active long-term project for us. Our real-time collaboration offering [uses a model-based editor approach](https://www.tiny.cloud/blog/real-time-collaborative-editing-slate-js) and I am hopeful this model will one day be made available in the open source core for use separate to RTC.

**Comment by thecodrr** [comment]
@TheSpyder thank you for your detailed response. I really appreciate you taking the time to reply.

> However it is not slow.

I went ahead and extracted the SaxParser to benchmark it against almost all the sax parsers around. It _is_ actually the slowest. Or one of the slowest. On a 300 KB document, it takes about 1.2s to parse (just parse, no document building) whereas projects like [easysax](https://github.com/vflash/easysax) can do it in 40-80ms. I can share the benchmark code, if required.

I agree that you guys are doing the sanitizing but that's not the slowest part. I have profiled the SaxParser, the slowest part is parsing. Sanitizing is basically just a check that runs once a token has been parsed to see if it should be added to the document or not. Overly simplified but that's not a hot path, or at least it isn't the worst hot path.

> What we're currently aiming for is a swap to the built-in browser DomParser then adding DomPurify to sanitise. The first stage of this is already in PR:
#7337

I noticed the new direction and I appreciate you guys taking action regarding this. However, I have a few questions:

1. TinyMCE runs in the browser. The browser is already very good with parsing HTML and building a DOM. It is also relatively very trivial to include sanitisation. My question is, why parse it again and again on every action? This might seem redundant but I don't think you got me the first time. Partial parsing is possible and feasible because you guys already have a DOM. TinyMCE has detailed information about each change, where it happened, what caused it, etc. etc. Aside from that, you have the whole DOM just a call away. I don't see the rationale behind parsing the same document over and over again. Especially when the browser is already doing it for you.
2. Why serialize the whole document to store the undo level? Since you already have the serialized document, when not just apply diffs to calculate the changed part? The thing is, you are unnessarily doing the parsing over and over. Once you have the serialized document state, there's simply no way you cannot keep it synced with ContentEditable. You guys are already building a kind of a virtual DOM.
3. This is actually something I couldn't figure out. Why does the SaxParser support XML? As far as I know, tinymce only runs in the browser which is dominated by HTML. Moreover, there is a lot of "fixing broken HTML" logic which is unnecessary when you are parsing a document already parsed by the browser. Then there's the many types of attributes syntaxes you guys support for no reason I could see. You can only get unformed HTML at one point in time, mostly, and that is the initialization. Once the document is inside the browser, there's no point in doing extra work the browser is already doing.

I don't think moving away from ContentEditable is required or even feasible at this point. The problem isn't the ContentEditable but the approach behind parsing.

At this point, just replacing the sax parser would improve the performance almost 10x.

_I also noticed that the Sax Parser was first introduced in v3.x, which is a long time. Whoever made it, really didn't have performance as a focus at the time._

**Comment by spocke** [comment]
I just want to chime in here since I wrote the SaxParser all those years ago. It was written in a time when IE 7 was the dominating browser and it was pretty much broken when it came to parsing HTML to the dom. For example it could end up with dom nodes with circular references and other strange things. So a parser was needed. However IE was also very slow at tokenizing string character by character like modern sax like parsers can do so it had to be based on regexps so that you would get some native speed performance since the JS engine was so slow. Also a lot of the parser has inlined code for speed since stack frame switching by calling functions was just to slow on the old IE js engine. So basically the SaxParser is no longer relevant in todays super fast js engines. However it's likely fast compared to using the native DOMParser but that is comparing oranges and apples as is comparing performance now on jit based js engines vs the old interpreted IE engine.
It also parses xml since back then XHTML was a big thing.
The new alt model that is currently part of the rtc plugin does things differently. It uses operations as undo state so it will not store the whole html as a snapshot. It also uses vdom to render the view and speed improvements to getting out the html quickly can be done by caching html fragments based on the immutable model so that only changed nodes gets reserialized. So we are improving lots of things now.

**Comment by thecodrr** [comment]
> It was written in a time when IE 7 was the dominating browser

As I suspected. I knew there had to be a reason to support all those syntaxes that are no longer relevant today.

> However it's likely fast compared to using the native DOMParser but that is comparing oranges and apples as is comparing performance now on jit based js engines vs the old interpreted IE engine.

Quite the contrary actually — native DOMParser is very, _very_ fast. The thing is you can just skip the parsing stage since you already have a DOM. Instead of operating on a string, you can directly operate on the DOM. You'll just have to build the DOM the first time when the HTML is externally loaded (e.g. copy/pasting, first initialization etc). For that, DOMParser would be more than sufficient.

> The new alt model that is currently part of the rtc plugin does things differently. 

Afaik it's built on Slate. Slate is not the most performant editor out there. The fastest Rich Text editors I have come across are Quill.js (mostly abandoned now) and [TipTap](https://tiptap.dev/examples/book). Both are model based, of course, but I think if TinyMCE takes out the parsing (and building) stage during editing, and only does it when absolutely necessary (copy/paste, first init), it can easily become fast enough on 90% of the devices.

**Comment by spocke** [comment]
> Quite the contrary actually — native DOMParser is very, very fast.

Yes if you count raw parsing but you need to consider the whole process and what impact it has. The current parser sax parses and filters out invalid elements and attributes the it builds a node tree using an internal ast node structure in the dom parser where it filters and restructures invalid nesting according to the schema. The native dom parser will just parse and and produce a dom fragment. So all that filtering needs then to be done on native dom nodes or we need to convert that tree from dom to an internal ast node representation and do the steps after either way it will be lots of processing going on after the parse step. We also need to take into account compatibility with existing plugins and integrations etc so it not an easy switch we are looking into proxying the ast node interface over dom nodes etc. I did some tests and traversing a dom tree vs a ast node tree is 2-4 times slower and you also have dom mutation vs pure js ast tree mutation to consider. Since we are currently in the process of getting a rid of the SaxParser we are still not knowing what the finial result would be by using the DOMParser approach so currently it's a work in progress all we know is that the SaxParser will get removed that is the main goal.
> Afaik it's built on Slate. Slate is not the most performant editor out there.

We chose slate for mostly other reasons than performance we needed a model that would support all the complexity that a full featured editor like tinymce needs and we did look at other engines in the evaluation process during the planning phase. Some of these other models have a very flat design probably making them faster but also less flexible.

Performance is a balance it's all what you are willing to trade. Compatibility, flexibility, future proofing all comes into play.

**Comment by thecodrr** [comment]
> Performance is a balance it's all what you are willing to trade. Compatibility, flexibility, future proofing all comes into play.

Imagine a person trying to paste 27k words into TinyMCE but the browser tab keeps crashing. That person doesn't care what flexibility or what tradeoffs you are making. For him, TinyMCE is buggy, slow, and just overall non-functional. So this view that performance should be traded off for X or Z makes no sense — the things humans hate the most is waiting. Everything should be performant _first_ and featureful _second_.

> Yes if you count raw parsing but you need to consider the whole process and what impact it has. The current parser sax parses and filters out invalid elements and attributes the it builds a node tree using an internal ast node structure in the dom parser where it filters and restructures invalid nesting according to the schema.

...and then it passes those AST nodes to the browser for rendering. Here's a very simplified version of what is currently happening (correct me if I am wrong):

1. HTML is passed to TinyMCE
2. TinyMCE takes the HTML, parses it (including sanitizing) using SaxParser
3. On each tag processed, it passes it off to the DomParser (if valid)
4. The DomParser takes the tag, builds an AST node and renders it into the browser (by creating an `HTMLElement`).

It does all this _a lot_ of times.

Now from the profiled result, a huge chunk is taken by the parser (around 50%). The `processEnd` function stands out the most. Regex execution (`Regex.exec`) is on the second number. The sanitization methods don't even appear in the flamegraph.

> Since we are currently in the process of getting a rid of the SaxParser we are still not knowing what the finial result would be by using the DOMParser approach so currently it's a work in progress all we know is that the SaxParser will get removed that is the main goal.

This is good. I am sure the performance benefit will be huge.

> I did some tests and traversing a dom tree vs a ast node tree is 2-4 times slower and you also have dom mutation vs pure js ast tree mutation to consider.

You don't have to walk the DOM tree. The browser already gives you higher level APIs (`querySelectorAll` for one) for traversing the DOM which should be significantly faster (not tested).

> So all that filtering needs then to be done on native dom nodes

Yes and I don't see a problem in that. If you do it right, TinyMCE will take less memory, do less work, and give out the same result faster. The main thing is that browsers are very powerful nowadays (soon even Sanitization will be part of browsers), and parsing, rendering, filtering HTML is a solved problem on the browser level i.e. don't do work the browser is already doing.

> it will be lots of processing going on after the parse step.

I am sure it takes a lot of processing to render a web page. But do you ever notice a lag in rendering? It's almost instantaneous (taking out the network activity) even for pages 10MB in size. APIs like `querySelectorAll` probably do all the work natively whereas manually traversing a DOM requires the browser to pass you each DOM node one by one. That would be slow, of course, but it's also unnecessary.

> We also need to take into account compatibility with existing plugins and integrations etc so it not an easy switch we are looking into proxying the ast node interface over dom nodes etc.

If the core API doesn't break, I don't see how Plugins will be affected? Plugins are using higher level APIs. Things like the DOMParser or SaxParser don't concern them — their output does. Keep the output the same and nothing should break.

> a very flat design probably making them faster but also less flexible.

TipTap (i.e. ProseMirror) is actually very flexible and their API is almost as powerful (or is expected to be) as TinyMCE but that decision is irrelevant here. The RTC version won't be the one most used so that's a problem for another day.

**Comment by spocke** [comment]
Performance is a feature but needs to be balanced against other features it doesn't always come first. If it did then this editor wouldn't be what it is today lots of decisions have been feature first based decisions since a customer/user needed it. However that doesn't mean we want the product to be slow so if it's bad UX due to performance issues then we optimize.

We do lots of different traversing walking the tree etc querySelectorAll just solves one particular area traversing and if you have lots and lots of calls to that api it start stacking up. The test I made was a full tree traversal something that is required to for example convert the tree to a slate model tree. 

Some plugins use filtering of the content by adding listeners the dom parser so they are exposed to the ast nodes. So compatibility thinking needs to be part of this process.

The idea is to eventually replace the core with the rtc core. But it has it's own set of performance problems and considerations since it does have a rendering step as well on top of all this parsing, filtering and tree traversal. But we are constantly doing performance tests and tuning of that.

**Comment by TheSpyder** [comment]
SaxParser has been deleted (#7597). But I don't think this change will improve performance as you expected it to.
