### ISSUE TITLE
I can't find what I'm looking for: demo/basic-example.md

### ISSUE THREAD

**Issue by FA-Bubba** [tinymce/tinymce#7348]
Can TinyMCE save the formatted text in an HTML marked-up format?  That is, will line feeds be saved as "<br>" and will Bolded Text be wrapped with "<b>" & "</b>" ?

Also, If my style is to end a sentence with a period followed by two spaces, will TinyMCE save that as ". &nbsp; &nbsp; "?

My goal is to save a paragraph as HTML marked-up text in a mySQL database, so it can be referenced and displayed statically on multiple web pages.

My thanks in advance!

**Comment by lorenzo-pomili** [comment]
Hello @FA-Bubba

Did you read this: [https://www.tiny.cloud/blog/how-to-get-content-and-set-content-in-tinymce/](https://www.tiny.cloud/blog/how-to-get-content-and-set-content-in-tinymce/)?
If this article is not helpful to you could you provide a [fiddle](https://fiddle.tiny.cloud/) with a minimal example of what have you tried to do and what is the expected result?

Thanks

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
