### ISSUE TITLE
Include Jumpmarks to TinyMce 2.1

### ISSUE THREAD

**Issue by juanlondonoforero** [tinymce/tinymce#7353]
Currently it's possible to add anchors but not possible to have anchors to the same page (jumpmarks)
I found this page where they describe the same problem but there isn't a solution:  https://forum.cmsmadesimple.org/viewtopic.php?t=21280

Ideally I want to add the value to "theme_advanced_buttons" in the function tinyMCE.init() but if there isn't one then I guess I will have to change the javascript function getAnchorListHTML in advlink.js...but how?
Thanks

**Comment by lorenzo-pomili** [comment]
Hello @juanlondonoforero,
I'm afraid that TinyMCE 2.1 is no longer supported, have you had the same issue in a more recent version?

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
