### ISSUE TITLE
Unable to style tooltips

### ISSUE THREAD

**Issue by joyously** [tinymce/tinymce#7377]
When I use the skin generator at http://skin.tiny.cloud/t5/ I can set the LESS variables that I find in the `oxide/src/less/theme/components/*.less` files and see the changes. But this doesn't seem to work for the variables that are in `tooltip.less`.
I can use the browser Developer Tools to change CSS and affect various parts of TinyMCE, but changing the tooltip CSS has no effect.

I can't see how to inspect the tooltip itself, but it seems like it isn't using the same classes as the tooltip CSS is using.

**What is the expected behavior?**
Changing the tooltip CSS should change the rendering of the tooltip.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I tested with version 5.10 on Ubuntu, Firefox 93.

**Comment by TheSpyder** [comment]
TinyMCE 5 does not render custom tooltips, as TinyMCE 4 did. It only uses browser tooltips. Bringing back custom tooltips is something we initially planned to do, which is why `tooltip.less` was created when the release work began, but it was never implemented. The file is still unused. Sorry.

I'll close this as we're tracking it in #5018, and it is in our backlog, but I'm still not sure when we'll get to it.
