### ISSUE TITLE
Table plugin issue in modal popup bootstrap theme

### ISSUE THREAD

**Issue by dave-lw** [tinymce/tinymce#7383]
**What is the current behavior? Describe the bug**
See video for quite clear demo
video: https://share.vidyard.com/watch/bhAxfjqab3kvBnckoTtY6F

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
not sure i have a quick way to demonstrate

**What is the expected behavior?**
proper cell selection

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinyMCE version - Version: 5.6.1 (2020-11-25)
Chrome Version 95.0.4638.69 (Official Build) (64-bit)

**Comment by dave-lw** [comment]
and here's one more video about the popup tools once table is created - they also dont work.
https://share.vidyard.com/watch/56ABbgb8KFBzx4bXHBddCt

**Comment by lnewson** [comment]
Hi @dave-lw,

The problem here, based on your videos, is that bootstrap has a focus trap when the modal is open which won't let focus move to other popup components. As such we have documented a workaround (see https://www.tiny.cloud/docs/integrations/bootstrap/#usingtinymceinabootstrapdialog) on how to prevent bootstrap doing that. Have you implemented that?

**Comment by dave-lw** [comment]
oh thank you i will try!

**Comment by dave-lw** [comment]
works!  Thanks so much.
