### ISSUE TITLE
Link plugin, two dots auto prepend.

### ISSUE THREAD

**Issue by chrislone** [tinymce/tinymce#7387]
Hi,there. 
I just confused by a feature/bug. When I use link plugin, this is what I input:

![image](https://user-images.githubusercontent.com/16998691/142193012-6d43d826-9c5a-4ef1-aad7-aabd8d18d0a2.png)

when I open it next time, it will become this:

![image](https://user-images.githubusercontent.com/16998691/142193170-3441efce-5b2a-4dc7-b2c1-c3e41e73a264.png)

two dots before link are not I want. How can I prevent this?

@tinymce/tinymce-vue version: 3.2.8
browser: Chrome  95.0.4638.69
OS: window 10

Thanks.

**Comment by lnewson** [comment]
Hi @chrislone,

TinyMCE will convert the URLs on the same domain as the URL might work while editing but then when published it might be a different URL and no longer work. More details about how this works can be found here: https://www.tiny.cloud/docs/configure/url-handling/#qhowdoiconvertmyurlstorelativeabsoluteorabsolutewithdomain

So in your case I'm assuming you'd want absolute URLs instead of relative URLs, so to do that you'd need to add the following options (as noted in the docs):
```
relative_urls : false,
remove_script_host : true
```

**Comment by chrislone** [comment]
Thanke for your reply so quikly @lnewson
It seems the **convert_urls** option in the docs is what I want, I just want the plugin don't convert the config.
And I think I should look more at the English docs instead of Chinese docs.

This solved my problem. Thanks again.

**Comment by lnewson** [comment]
Glad to hear you got this sorted :+1:
