### ISSUE TITLE
TinyMCE changes html code adding style tag with background-image

### ISSUE THREAD

**Issue by MYSIVMAKARII** [tinymce/tinymce#7416]
Hi, developers! Something happened with my TinyMCE. It starts change html code adding something. I don't know what to do. Ask for help!

Before:

<img width="1178" alt="Снимок экрана 2021-11-23 в 21 53 12" src="https://user-images.githubusercontent.com/77324079/143094399-d995cfd0-371b-4c3b-be0e-29d580a24e09.png">

After:

<img width="1164" alt="Снимок экрана 2021-11-23 в 21 52 58" src="https://user-images.githubusercontent.com/77324079/143094406-0a9bd9aa-eaea-46ab-8b17-c664412a1086.png">

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
