### ISSUE TITLE
default style i want to remove

### ISSUE THREAD

**Issue by raselcse13** [tinymce/tinymce#7434]
i was facing  extra space every div

data-mce-style i want remove this class please help me

**Comment by raselcse13** [comment]
this is invisible data-mce-style if debug then i can found

**Comment by raselcse13** [comment]
Duplicate of #
![dublicat](https://user-images.githubusercontent.com/24198895/144787657-4e0ae9b4-b91a-4496-bc7e-5e565c793709.png)

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
