### ISSUE TITLE
[6.0.0-alpha.20211209] Tiny try to load a non existing file: "default"

### ISSUE THREAD

**Issue by Georg-Git** [tinymce/tinymce#7458]
**After init Tiny try to load a non existing file with name "default"**

[https://fiddle.tiny.cloud/YRhaab/1](https://fiddle.tiny.cloud/YRhaab/1)
and check Browser Debugger:

![image](https://user-images.githubusercontent.com/1309628/145436432-ed26eb17-8d35-4868-ab7a-2ab1e9094357.png)

Browser: Chrome and Firefox
Tinymce Inline Mode [6.0.0-alpha.20211209]

Tiny <6.0.0 does not show this behavior

**Comment by lnewson** [comment]
Thanks for the report @Georg-Git and thanks for testing out 6.0! I can confirm this issue and it's caused by an issue with the swap to using the new Options API we've been developing in 6.0. The problem here is the `editor.inline` check is failing in the following because it hasn't been initialised yet. I'll get that fixed up later today 👍 
https://github.com/tinymce/tinymce/blob/cce70e3a73c7510e90edbb16b8a0e010380b032b/modules/tinymce/src/core/main/ts/api/Options.ts#L288
