### ISSUE TITLE
Broken links in readme file

### ISSUE THREAD

**Issue by placoderm** [tinymce/tinymce#7671]
These links in the [readMe.md](https://github.com/tinymce/tinymce/blob/develop/README.md) file are broken:

[TinyMCE Cloud Deployment Quick Start Guide](https://www.tiny.cloud/docs/tinymce/6/cloud-quick-start.html)
[TinyMCE Self-hosted Deployment Guide](https://www.tiny.cloud/docs/tinymce/6/npm-projects.html)
[TinyMCE classic editing mode](https://www.tiny.cloud/docs/tinymce/6/use-tinymce-classic.html).
[TinyMCE inline editing mode](https://www.tiny.cloud/docs/tinymce/6/use-tinymce-inline.html).
[TinyMCE distraction-free editing mode](https://www.tiny.cloud/docs/tinymce/6/use-tinymce-distraction-free.html).

**Comment by TheSpyder** [comment]
Sorry about that. We had to update the readme file to publish the 6.0.0 release, since the readme is baked into the NPM package, but the new documentation website was delayed. It might be another couple of weeks before the new links work; we'll leave this issue open until then.

In the meantime the 5.x readme still points to the old links:
https://github.com/tinymce/tinymce/tree/release/5.10

**Comment by TildaDares** [comment]
I opened an issue for another one I found in #7697

**Comment by ssougnez** [comment]
Hello, any updates on this? I upgraded to tinymce 6 and it's difficult to use without the documentation :-)

**Comment by TheSpyder** [comment]
My apologies for the delay. The TinyMCE 6 release coincides with a new documentation system so the updates for it were a bit slower to start than we expected.

Because the documentation is (as always) open source, I can show you our progress :)
https://github.com/tinymce/tinymce-docs/tree/staging/docs-6 is our development branch, you can compile and run a working copy. It's looking pretty good but with so many changes the migration guide is going to be one of the last things we finish, unfortunately.

Our speed has picked up now (we've opened [more than 20 PRs this week](https://github.com/tinymce/tinymce-docs/pulls?q=is%3Apr)) and QA on the docs is underway. Once that's done I'll share a URL to use even if we haven't officially linked to it on the website.

**Comment by ssougnez** [comment]
Ha ha, no need to apologize :-) we will wait :-)

**Comment by TheSpyder** [comment]
The docs are now live. Note the links in the readme changed after this was logged, so the OP links are still broken, but the readme links all work.

**Comment by placoderm** [comment]
Thanks!
