### ISSUE TITLE
2022: This package now forces you to upgrade after 30 days, NOT FREE software, does not belong on Github

### ISSUE THREAD

**Issue by slothentic** [tinymce/tinymce#7682]
This company now bricks your editor after 30 days. They claim that it's "Free Forever" product, that claim is false, see screenshot below of what will happen 30 days after you install it.

This is NOT a functional editor after 30 days, this is a broken product, and an absolute bait and switch. This company needs to be investigated for false and mis-leading claims about a free forever product that gets rendered un-usable after a period of time. That is a FREE TRIAL, not a FREE FOREVER product.

Damning evidence of a broken product:

![Screen Shot 2022-03-11 at 7 21 04 AM](https://user-images.githubusercontent.com/821287/157866590-31103880-0750-434d-beca-46c7b9c2db3b.png)
.

I'm sure you're going to claim that the "core" editor still works. It's about as useful as a textarea without those plugins. Change your language to not be a lie.

What a shame your company has become.

**Comment by smalos** [comment]
Premium features from the makers of TinyMCE.

https://www.tiny.cloud/docs/enterprise/

**Comment by lofcz** [comment]
Could you please elaborate on where they claim "Free Forever" as in "Premium Features Free Forever"?
Also while anyone can voice their opinion what does/does not belong on GitHub it is barely more than a rant as GH specifies that in [ToS](https://docs.github.com/en/github/site-policy/github-terms-of-service).

While some recent steps within 6.0 release are _misfortune_ from a consumer perspecive (marking several plugins as premium) they are well within IP holder rights. We also got a more permissive license (LGPL -> MIT) which at least for me is well worth the 
said change of licensing of a few plugins.

Until further evidence is provided I'm downvoting this issue as it seems like a major misunderstanding on OP's side and the tone of it is quite off.

**Comment by EkimChau** [comment]
Hello [slothentic](https://github.com/slothentic),

There appears to be a misunderstanding in Tiny’s open source core model.  To clarify Tiny has open source products that are free to use and premium add-ons which are licensed under a paid subscription.  What is free and what is premium are clearly labeled on our website https://www.tiny.cloud/docs/plugins/.  Our pricing plans also describe what is free and what comes with a subscription https://www.tiny.cloud/pricing/.

It appears what you signed up for was our **Free Forever plan**, which comes with a **30 day free trial of premium features**. This allows new customers to evaluate our premium plugins at no cost and assess if it is right for their use case.  The paid subscriptions support Tiny’s continual investment in R&D of our core, as well as enhancements to premium offerings, and allow us to provide professional product support.

At the end of the trial, access to our premium offerings will require an ongoing subscription, otherwise, the plugins will fail to load, which is what's happening here.  If you do not wish to proceed with the premium features you can turn off these notifications by turning off the premium plugins in the configuration, this should only take a few minutes.  

We are sorry for the frustration you feel, but in order to continue to invest heavily in an enterprise-grade editor, we have embraced this model in order to sustain our professional engineering efforts.

Best regards,

TinyMCE Product Team

**Comment by EkimChau** [comment]
I will close out this issue, for any further commercial support related issues please contact https://support.tiny.cloud/hc/en-us

Best regards,

TinyMCE Product Team
