### ISSUE TITLE
Paste plugin 404 Not Found

### ISSUE THREAD

**Issue by markonastic** [tinymce/tinymce#7685]
**What is the current behavior? Describe the bug**
When using the paste plugin I get error 404

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
When using self-hosting with TinyMCE-Angular I get that the paste plugin doesn't exist.
![tinymce](https://user-images.githubusercontent.com/17621541/158146681-88f13095-7f2e-4a00-b728-3e56220bd51c.png)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I used TinyMCE version 6.0.0 & TinyMCE-Angular version 5.0.1
It works when using TinyMCE version 5.10.3

And just to mention that issue #7658  is also a problem with the same version

**Comment by markonastic** [comment]
Hi @lnewson,
Thank you for your reply.
I'll then use version 5.10.3 until full documentation is released :)

**Comment by dmoebius** [comment]
14 months later, the paste plugin is still mentioned as available on https://www.tiny.cloud/docs/plugins/opensource/paste/

**Comment by TheSpyder** [comment]
Because that's the TinyMCE 5 docs, which still includes the paste plugin. It was never listed on the TinyMCE 6 docs.
https://www.tiny.cloud/docs/tinymce/6/

**Comment by Webreaper** [comment]
I just spent 20 minutes trying to figure out why paste isn't loading. Since the url mentioned by @dmoebius is still live and it's not entirely clear it's for v5 when dropping into the page halfway down from a google search, perhaps Tiny can update the docs to explicitly state that "These plugins are merged into Core in v6, so if you get a 404, and you're not on v5 (which is now unsupported) that's why".
