### ISSUE TITLE
tinymce.EditorOptions.get() cannot get a custom option

### ISSUE THREAD

**Issue by migliori** [tinymce/tinymce#7767]
Hello,

I'm updating a plugin that had some custom settings with Tinymce V5.
Until now, I retrieved the plugin settings with `editor.settings.mysettings`.

In Tinymce V6 the documentation led me to `tinymce.activeEditor.options.get('mysettings')`, but it doesn't work with custom options names like "mysettings".

Here's a sample code. I put it [here on Codepen](https://codepen.io/migli/pen/gOoEOrR) too for convenience.

```
tinymce.init({
    selector: "textarea#default",
    mysettings: "test",
    setup: (editor) => {
        editor.on("click", () => {
            console.log(tinymce.activeEditor.options.get("selector"));      // textarea#default
            console.log(tinymce.activeEditor.options.get("mysettings")); // undefined
        });
    }
});
```

So my question is: **what is the right way to set and get custom options with Tinymce V6?**

Thanks

**Comment by lnewson** [comment]
Hi @migliori,

For TinyMCE 6 custom options need to be registered before they can be fetched. This can be done using the `editor.options.register()` API: https://www.tiny.cloud/docs/tinymce/6/apis/tinymce.editoroptions/#register

Here's an updated example with that done:
```
tinymce.init({
    selector: "textarea#default",
    mysettings: "test",
    setup: (editor) => {
		editor.options.register("mysettings", { processor: "string" });
        editor.on("click", () => {
            console.log(tinymce.activeEditor.options.get("selector"));
            console.log(tinymce.activeEditor.options.get("mysettings"));
        });
    }
});
```

The option spec needs a `processor` to say how the option should be parsed and validated. In the example I gave above its parsing and validating the value as a string. It can be either a set of built-in processors or a custom one (see [EditorOptions.ts](https://github.com/tinymce/tinymce/blob/master/modules/tinymce/src/core/main/ts/api/EditorOptions.ts#L19)). The other useful property to provide is `default` which allows setting the default value for the custom option.

**Comment by migliori** [comment]
Thanks, that's perfect (maybe it would be an idea to add this in the documentation).

For information, I'm working on a new version of my [Tinymce Bootstrap plugin](https://www.tinymce-bootstrap-plugin.com/) with Tinymce V6 and Bootstrap 5.

I was in contact some time ago with Andrew Robers. If you are interested in a collaboration, the form of which remains to be discussed, please do not hesitate to get in touch.

**Comment by NullBrowbeat** [comment]
Hello,

Sorry for reviving a dead post here, but I stumbled across the problem of trying to validate a nested object, which seems to be related to this post.

I am currently writing a custom plugin for TinyMCE 6 and I want the options to be given as a nested object in the configuration.
I made it work so far with the following code:

In my Example.ts file:
```
import { TinyMCE } from "tinymce";
import MyPlugin from "../../bla/blub/Plugin.ts";

declare const tinymce: TinyMCE;

MyPlugin();

tinymce.init({
   //some basic configuration stuff
   myConfigurationObject: {
     someNestedValue: 123,
     //some more values
   }
})
```

In my Plugin.ts file:
```
const setup = (editor: Editor): void => {
   editor.on("BeforeSetContent", function() {
      editor.options.register("myConfigurationObject", {
         processor: "object",
         default: {
            someNestedValue: 456
         }
      });
   });
   editor.on("LoadContent", function() {
      console.log(editor.options.isRegistered("myConfigurationObject"));
      console.log(editor.options.get("myConfigurationObject").someNestedValue));
   });
}
```

Now my questions are:

1. Is there a way to have individual nested values in said object, which can be tested for their existence with `.isRegistered()` and also read with `.get()`? All my experiments so far have failed me. :/ Ideally I would wish to have a complex configuration object, if need be with a custom Processor (even though there I want more specific error messages than just "Invalid value passed for the myConfigurationObject option" depending on which property is faulty) and where I can then also set the individual properties to default values, which then can individually retrieved by editor.options.get("myConfigurationObject.someNestedValue") or editor.options.get("myConfigurationObject").get("someNestedValue") or something like this. :|
2. Is the "BeforeSetContent"-Hook even the appropriate lifecycle hook for this? I noticed that I can't do it in the "init" hook, since then my code doesn't find the configuration. (And also note that I try to override the registered default-Value with my configuration passed to the TinyMCE-Config in the init-phase, so that the default value is only taken, if it can't find a given configuration.)

Thanks

**Comment by TheSpyder** [comment]
1. We don't tend to use nested values ourselves - you'll notice we flatten config options in the style `pluginname_category_subcategory` - so this isn't really in the design of the options API I'm afraid.
2. You're already within the `setup` function, registering the option should work right there rather than waiting for any events.

**Comment by NullBrowbeat** [comment]
Alright, thank you very much for your answer. :)
And keep up the great work on TinyMce! ;-)

Have a nice one
