### ISSUE TITLE
Styles are lost when displaying rich text content in html because class styles are used instead of inline styles

### ISSUE THREAD

**Issue by SimmonsSue** [tinymce/tinymce#7810]
When I edit the module with code， I found that styles were lost when displaying rich text content in html because class styles are used instead of inline styles.
Why not use inline styles ？

**Comment by lostkeys** [comment]
Hi @SimmonsSue! can you provide more details of what you are doing and [some reproduction using our fiddle tool](https://fiddle.tiny.cloud)

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
