### ISSUE TITLE
`forced_root_block` setting is ignored in some cases.

### ISSUE THREAD

**Issue by liesahead** [tinymce/tinymce#7821]
**What is the current behavior? Describe the bug**
Let's save `forced_root_block` is set to default `p` value. We have such html.

![image](https://user-images.githubusercontent.com/32300784/168043499-2df8022c-0fb2-42ee-9c2a-1da0d9fa13a3.png)

But after user goes to normal editing and clicks `Enter` couple of times and enters `fdfd` text it will become like this:
![image](https://user-images.githubusercontent.com/32300784/168043852-162481a5-f5fc-4bae-a726-b1dfa6b3ba4c.png)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Described above.

**What is the expected behavior?**
Editor should use `forced_root_block`  element setting to create new block-level elements.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Tinymce v6
Chrome v100

**Comment by liesahead** [comment]
@TheSpyder , could you check that?

**Comment by TheSpyder** [comment]
`forced_root_block` defines the tag used to force blocks when there are none, for example during `setContent` or when converting a list item to a text block. Pressing enter inside an existing block will generally split the block using the same tag name except in specific cases such as at the end of a heading tag. Our assumption is that if `forced_root_block` is set, the blocks in the document are generally already using that tag.

We may have made a mistake in the `newline_behavior` description, linked to from the `forced_root_block` documentation, because it does describe `forced_root_block` as operating in the way you suggest.

**Comment by liesahead** [comment]
We might need to switch to some other editor library as v6 has too serious breaking changes and it feels like it's different library that doesn't fit our needs anymore..
