### ISSUE TITLE
You must select a template for this document

### ISSUE THREAD

**Issue by EssexDavidC67** [tinymce/tinymce#7825]
When trying to save a document I am getting the above message. It works fine in IE, but not in Chrome or Edge.

When looking at the Console there is an error message see attached screenshot.

Any help / advice much appreciated

<img width="277" alt="Seax Error" src="https://user-images.githubusercontent.com/105491289/168264914-d97fc8cb-4307-4f48-b975-419a92ff11a4.PNG">

**Comment by lostkeys** [comment]
Hi @EssexDavidC67! We need more into to be able to help you, here is our questionare template to get you started:

**What is the current behavior? Describe the bug**

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by lnewson** [comment]
Based on the information in the exception, it appears you are using TinyMCE 3. That version of TinyMCE is no longer supported and at this stage only the latest versions of TinyMCE 5 and 6 are supported community versions. So if you're having issues then you could try upgrading to a supported version.

**Comment by lnewson** [comment]
As there's been no update on this for some time I'm going to close it. If the requested information above can be provided we'll be happy to reopen this issue.
