### ISSUE TITLE
[6.0] Media plugin + valid_elements = "TypeError: rule is undefined"

### ISSUE THREAD

**Issue by jordanade** [tinymce/tinymce#7870]
**What is the current behavior? Describe the bug**
Using media plugin with any `valid_elements` specification produces `TypeError: rule is undefined`

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
https://jsfiddle.net/r3c9jLp5/1/

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Version 6. Worked in previous version.

**Comment by lnewson** [comment]
Hi @jordanade,

This is expected as the media plugin no longer forcibly overrides the schema like it did in TinyMCE 5. As such if using the media plugin you need to ensure that you also include the media elements within the Schema (e.g. via `valid_elements`). This is noted in the migration guide here: https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/#media
> The schema must, therefore, be configured to allow usage of the media elements, and the media element attributes.

Note: We do have an internal task to improve this error message so that it's clearer why it's failing.

**Comment by jordanade** [comment]
Thank you @lnewson. In my real deployment I had already included `iframe[src|frameborder|style|scrolling|class|width|height|name|align]`. I have no idea what is meant by the "media elements" otherwise. Is that `video`, `audio`, and `object`? I have to include those even if I have no intention of using them? 

I just added them to my `valid_elements` and I'm still getting the error:
```valid_elements: "h2/h1,ul,ol,li,-p,small,br,blockquote,hr,strong/b,em/i,a[href|target|class<button],iframe[src|frameborder|style|scrolling|class|width|height|name|align],video,audio,object,table,thead,tbody,tr,th,td",```

Are there attribute values that must also be included? Could the documentation be updated to indicate exactly what `valid_elements` must include to avoid producing this error?

**Comment by TheSpyder** [comment]
The exception looks like it's coming from this code:
https://github.com/tinymce/tinymce/blob/c12fb6af3b6b72886946dd3fb1bb1b8be249949f/modules/tinymce/src/plugins/media/main/ts/core/FilterContent.ts#L20-L29

So for now you need to define `embed` as a valid element.

**Comment by lnewson** [comment]
The media elements are listed in the doc I linked, but yes it appears to be missing `embed` sorry. I'll log an internal docs ticket to get that fixed. So to be clear the elements required by the media plugin are `iframe`, `video`, `audio`, `embed` and `object` (similar to how the lists plugin requires `li`, `ul`, `ol`, etc...). The media plugin itself has no way of blocking certain urls based on the type of URL provided so it needs to have all allowed. If you'd like to have that be customized so that it blocks certain media content that would need to be a separate feature request.

**Comment by jordanade** [comment]
Thanks @lnewson and @TheSpyder. It works now.
