### ISSUE TITLE
Copy picture + text from MS word, the text is preserved but the picture is lost

### ISSUE THREAD

**Issue by SimmonsSue** [tinymce/tinymce#7872]
Copy image + text from MS word, the text is preserved but the image is lost. Setting paste_data_images to true also didn't help.

**Comment by TheSpyder** [comment]
MS Word doesn't include images in clipboard data in the normal way (the `img` tags have `file://` references). We have a premium plugin that is able to grab the image data in an advanced way:

https://www.tiny.cloud/tinymce/features/powerpaste/

**Comment by SimmonsSue** [comment]
> 

This demo also cannot successfully copy the text + picture, prompting that the picture import failed

**Comment by TheSpyder** [comment]
Not all images are supported; in particular word art and similar diagrams drawn in MS Word simply aren't available on the clipboard in _any_ form. This can also extend to regular images depending on the context (there are a complex set of rules that determine what MS Word places on the clipboard).

The only browser which can import those correctly is Safari on macOS because it reads the `file://` data (which is a rendering of the MS Word image) and makes that available to the editor during paste operations.

**Comment by ranjithreddykeesari** [comment]
I'm also facing similar issue. When I copy an individual image from a word file it's working as expected but when I'm trying to copy image with the other text/content, the text is rendering but image is lost. I'm using powerpaste plugin and also kept paste_data_images: true.

If you have any solution that would be great. I tried on Chrome and Edge browsers.

**Comment by bbb324** [comment]
> MS Word doesn't include images in clipboard data in the normal way (the `img` tags have `file://` references). We have a premium plugin that is able to grab the image data in an advanced way:
> 
> https://www.tiny.cloud/tinymce/features/powerpaste/

Is there any browser api that enable to copy both text and image into tinymce editor, I just wonder how tinymce implement such thing
