### ISSUE TITLE
Error: NS_ERROR_UNEXPECTED

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#794]
Description of problem:

Version 4.0b3 (2013-05-15)

Error: NS_ERROR_UNEXPECTED: Unexpected error
Source File: http://example.com/tinymce/js/tinymce/tinymce.min.js
Line: 4

Steps to reproduce:
1. use firefox (my ver is 21)
2. after a few pages are loaded with mce on it, it happens rather randomly.  triggers error on multiple diff computers and os

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T6013](http://archive.tinymce.com/develop/bugtracker_view.php?id=6013) posted by [simon@c7.ca](http://archive.tinymce.com/profile.php?name=simon@c7.ca)_
> 
> _**Tags:** [firefox 4x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by eximius313** [comment]
I have the same issue. It happens on Firefox, when Ajax loads TinyMce, call init functions and after ajax submitting the form I get this error:
![image](https://cloud.githubusercontent.com/assets/5578017/12679532/0618b2ae-c6a5-11e5-992c-df53a5d6162b.png)

**Comment by kidneyball** [comment]
I ran into the same issue recently with tinymce 3.5.11 (Yes it is a very old version but I think the same concept apply the new versions).

In an ajax request we remove the div containing the tinyMCE and the underlying textarea and then rerender the whole div. It turns out the old tinyMCE editor instance is still in the ```tinymce.editors``` array. (If you run ```tinymce.editors.size()``` in the console, you can see its size keep increasing after each rerendering). When you call ```tinymce.triggerSave```, it actually loop through all the editors and call ```save``` on them. For those leaked instances, the underlying textareas were actually deleted, I assumed that caused the exception.

Following is my cure for now.

```js
    /**
     * Remove a tinymce editor from the page environment.
     * tinymce.remove (at least up to 3.5.11) does not remove the editor from editors array.
     * We need to do it manually.
     */
    HRX.removeTinyMCEInstance = function(editor) {
        var oldLength = tinymce.editors.size()
        tinymce.remove(editor)
        if (oldLength == tinymce.editors.size()) {
            tinymce.editors.remove(editor)
        }
    }

    HRX.cleanUpTinyMCE = function() {
        tinymce.editors.filter(function(editor) {
            var $textarea = jQuery("textarea#" + editor.id + ":not(:visible)");
            return $textarea.size() == 0;
        }).each(function(editor) {
            try {
                HRX.removeTinyMCEInstance(editor)
            } catch (err) {
                LOG.error(err)
            }
        })
    }
```

I call ```clearnUpTinyMCE``` every time after rerendering and it fix the issue.

**Comment by caiosm1005** [comment]
I am facing the same issue. My form is recreated using AJAX. It works as expected in all browser except Firefox, which throws `NS_ERROR_UNEXPECTED`.

Waiting for a fix.

**Comment by waspinator** [comment]
I had this issue when creating a tinymce instance in a modal. I think I kind of fixed it by calling `tinymce.remove();` when hiding the modal instead of before calling `tinymce.init()`

**Comment by akshayjai1** [comment]
Hi all,
We were facing an issue, in firefox only
var tab contains reference to a div, we removed the div using parent.removeChild(tab)

Now after this we were calling tab.destroy() // a dojo function to remove connections of tab from dom

Now this was giving us NS_ERROR_UNEXPECTED

We spent a lot of time finding the solution, then on our our expert Mrinal Malhan, suggested that
 tab. destroy()   should be replaced with tab.domNode.remove()

and it solved the problem. 

Do try this in case it works for you

**Comment by vortexacm** [comment]
To prevent fail on ajax load and jquery, usage this before ajax call

if( typeof window.tinymce != 'undefined' && $(window.tinymce.editors).length > 0 ){
	$(window.tinymce.editors).each(function(idx) { 
		try {
        		tinymce.remove(idx);
    			} catch (e) {}
				
		});
	}

**Comment by caiosm1005** [comment]
Sometimes we don't have control over Ajax refreshes.

We use a RAD platform that does this automatically. We need a way to sort
this AFTER using Ajax and removing the HTML from the document.
Em 13/07/2016 12:16, "vortexacm" <notifications@github.com> escreveu:

To prevent fail on ajax load and jquery, usage this before ajax call

if( typeof window.tinymce != 'undefined' &&
$(window.tinymce.editors).length > 0 ){
$(window.tinymce.editors).each(function(idx) {
try {
tinymce.remove(idx);
} catch (e) {}

    });
}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tinymce/tinymce/issues/794#issuecomment-232387940>, or mute
the thread
<https://github.com/notifications/unsubscribe/AEQP-iBc5JiBR6we-MZ25ivhklXRRdCpks5qVQE7gaJpZM4HPSTr>
.

**Comment by fanfavorite** [comment]
I received this error in FireFox when trying remove a previously initialized editor where the HTML was removed without calling a remove function in TinyMCE. It's best to use the TinyMCE remove function before removing the content, however in my case I couldn't, so I do this before I reinitialize:

if (typeof tinymce != "undefined") {
	var ed = tinymce.get(id);
	if (ed) {
		try {
			ed.remove();
		} catch(e) {
			delete tinymce.editors[id];
		}
	}
}

**Comment by thedrjim** [comment]
This issue has been closed due to inactivity. Tiny will soon be working with members of the community to close other old issues on our GitHub repositories.

There are some excellent discussions and reports in the main TinyMCE GitHub repository, but with so many open issues, we cannot monitor them all.* *Reviewing all of the issues individually would be an enormous task, requiring time that could be better spent developing new features and fixing bugs. Therefore, we are closing issues that have been inactive for over 365 days, with some exceptions.

If this issue is still relevant, please re-open this issue or create a new one.

If you have any questions or concerns, you can contact me at community-qa@tiny.cloud . You can also join the discussion on our mailing list at the following link: community-qa+subscribe@tiny.cloud .
