### ISSUE TITLE
Code Sample Plugin - PrismJS Security Vulnerability

### ISSUE THREAD

**Issue by venkatt05** [tinymce/tinymce#7958]
We are using **Code Sample** plugin and we see that it uses PrismJS library. We found that PrismJS version  `< 1.27.0` is open for vulnerabilities.

Reference: [https://snyk.io/vuln/npm:prismjs](https://snyk.io/vuln/npm:prismjs)

We are using `TinyMCE v5.10.1` and we see that it uses a vulnerable version of PrismJS. Please advise whether there is any patched version with the PrismJS fixes that we can upgrade to.

Thanks !

**Comment by TheSpyder** [comment]
Please use our infosec email address to report security concerns rather than logging a github issue:
https://www.tiny.cloud/docs/tinymce/6/security/#reporting-tinymce-security-issues

The vulnerability appears to be only in the command-line plugin, which TinyMCE does not use. We will however add upgrading PrismJS to our task list for the next 5.x patch release. Thank you for pointing this out.

**Comment by venkatt05** [comment]
Great. Thanks !
