### ISSUE TITLE
Unsetting attribute serializer nodeFilter causes exception if attribute filter matches attribute

### ISSUE THREAD

**Issue by MarkoNV** [tinymce/tinymce#7959]
If serializer node filter unsets attribute, attribute filter gets old list, which doesn't apply anymore and error can occure.

https://fiddle.tiny.cloud/ohiaab/1

Open fiddle, open source and insert iframe (e.g. YouTube share).

Expected behaviour:
iframe in editor should have src attribute, but in view source and on save should be transformed in data-src

Actual behaviour:
opening code and saving throws error:
`Uncaught TypeError: uri is undefined`

**Comment by TheSpyder** [comment]
The failure comes not from where the `uri is undefined` is thrown, but the code that calls it _with_ undefined, which is here (in v6, line 52):
https://github.com/tinymce/tinymce/blob/2d8b95517a43d1f1967a2f3898371865a2fa18e4/modules/tinymce/src/core/main/ts/dom/DomSerializerFilters.ts#L30-L58

This is a filter dealing with our own internal `data-mce-src` attributes. However the cause of the bug is actually the code that runs the filters:
https://github.com/tinymce/tinymce/blob/2d8b95517a43d1f1967a2f3898371865a2fa18e4/modules/tinymce/src/core/main/ts/html/FilterNode.ts#L76-L84

It collects filters that can apply to the node or children of the node but doesn't check between running each of them whether the next filter is still valid for all the collected nodes. Our internal attribute filter is designed for nodes with a `src`, it's collected to run here because the node starts with one. Your filter runs before ours and the attribute it depends on is removed.

This mid-loop mutation isn't something we've considered, thank you for the replication case! I'll log this in our tracker as something to look at.

In theory this is an easy fix, because each `match.nodes` array is unique so we can just splice out nodes that no longer match, but it will require further analysis and testing to be sure.

**Comment by TheSpyder** [comment]
We're aiming to release TinyMCE 6.2 in a few weeks, this fix will be included.
