### ISSUE TITLE
"Fullpage" plugin successor is unclear

### ISSUE THREAD

**Issue by cappic90** [tinymce/tinymce#8037]
Hey TinyMCE team,

We are currently using TinyMCE 5 in the context of Vue.js with a license. In our interface we allow uploading and editing landing pages, full HTML5 documents, with the editor. The Advanced Code plugin together with the Fullpage plugin allows exactly what we currently need for our customers. Now in the documentation "Fullpage" is marked as deprecated, however no alternative is mentioned. Does this mean that in TinyMCE 6 you will no longer be able to offer the possibility to edit for example the `<head>` area of a web page in the editor? What would be the correct procedure?

**Comment by arianox** [comment]
Same problem!

**Comment by smalos** [comment]
@ashfordneil 
Can you answer that question since you removed the plugin?

https://github.com/tinymce/tinymce/pull/7362/commits/a6f76c7c3863825ea9d3bb3b0888297740c1ddd0

**Comment by TheSpyder** [comment]
Neil no longer works for Tiny. Removing the plugin was a team decision, not his alone, I'll pass this on to our product manager for further comment.

**Comment by lostkeys** [comment]
Hi all,

The Fullpage plugin was removed because it had a lot of bugs and issues and costed us too much money to maintain. We acknowledge the problem exist but the fullpage plugin was not the right solution, at least for us. We are thinking about other ideas on how to solve this and would love more insights into the various use-cases you are trying to solve with this feature. 

You could all do me a favor and [hop over to our feature request portal and submit a feature request](https://www.tiny.cloud/roadmap/). Please describe in more detail the problem you are solving with fullpage. Just writing "bring back fullpage plugin" doesn't help us design a new feature.

Yours,
Fredrik Danielsson – Product Manager

**Comment by morgan-wowk** [comment]
This plugin deprecation and no modern alternative has spun up a significant revisit of our use of TinyMCE and unfortunately may result in needing to move to a new solution altogether. For context, we had relied on this feature to be able to provide an email editor service that includes writing `html` and `body` elements.

**Comment by n-rodriguez** [comment]
@lostkeys Hi there! Any news since 2022? (we are in mid-2025 now an no alternative exists). Thank you!

**Comment by n-rodriguez** [comment]
> The Fullpage plugin was removed because it had a lot of bugs and issues and costed us too much money to maintain

The 500 most expensive LOC 😄 https://github.com/tinymce/tinymce-dist/blob/5.8.2/plugins/fullpage/plugin.js

(vs "Last week 657,169 developers chose TinyMCE for their web app")

**Comment by n-rodriguez** [comment]
> This plugin deprecation and no modern alternative has spun up a significant revisit of our use of TinyMCE and unfortunately may result in needing to move to a new solution altogether. For context, we had relied on this feature to be able to provide an email editor service that includes writing `html` and `body` elements.

@morgan-wowk I got the very same use case. How did you solve this issue? Thank you!
