### ISSUE TITLE
TinyMCE 5 Scroll bar keeps jumping up and down/blinking after uploaded multiple files

### ISSUE THREAD

**Issue by shindevelop95** [tinymce/tinymce#8039]
Hi TinyMCE Team, I'm facing an issue whereby the scrollbar keeps jittering when I try to upload a file in the rich text editor. After some troubleshooting on our side, we found out that then there is a caret that is causing the issue. This is because the caret will be shown/hidden alternately and this causes the editor to increase/decreases in height which is affecting the scrollbar. Would there be a possible fix on your side for this?

Test environment: Window 10, Chrome

https://user-images.githubusercontent.com/72658204/182826757-72030134-6218-4659-b0ff-5f8e00db0c25.mp4

**Comment by yacodes** [comment]
Hi @shindevelop95, thanks for reporting this. Is it possible for you to create a reproduction case in a TinyMCE [Fiddle](http://fiddle.tinymce.com/), an open source repository, or using a sandbox platform such as Codepen or JSFiddle?

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
