### ISSUE TITLE
Undo through the keybind CTRL Z works when the inline editor does not have focus

### ISSUE THREAD

**Issue by kaerumm** [tinymce/tinymce#8117]
**What is the current behavior? Describe the bug**
CTRL + Z still works when the inline editor loses focus by clicking outside of it without focusing another element

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) 
or similar.**

https://fiddle.tiny.cloud/Bmiaab
1. Give focus to the inline tinymce editor and make some changes to the body
2. Click outside of it so as to blur it
3. Press CTRL+Z to trigger an undo

Repeating these same steps on the normal tinymce editor or the textarea element does not seem to present the same behaviour. 

**What is the expected behavior?**
Pressing CTRL + Z should not trigger an undo, exactly like the normal editor and textarea element below the tinymce inline editor behaves.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I have confirmed this bug to happen ( through the provided fiddle ) as far back as version 4.0

**Comment by Kaerum** [comment]
I have looked a bit more into it, and it seems to be a browser-related behaviour issue. The problem still happens if you substitute inline tinymce for some other element with contentEditable set to true.

When an undo and redo action happens while following the instructions above, TinyMCE does not emit a Redo or Undo event.
