### ISSUE TITLE
tinymce 5.6.2 when I insert content by 'editor.insertContent',   generating node withcontenteditable=false,  press Enter  and node deleted

### ISSUE THREAD

**Issue by virtualwj** [tinymce/tinymce#8175]
**What is the current behavior? Describe the bug**
node with contenteditable=false, press Enter  and node deleted

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

**What is the expected behavior?**
press Enter  and node not delete, i just want enter for new line
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by TheSpyder** [comment]
Can you make a fiddle demonstrating this? We have changed quite a bit of code in this area recently and may have already resolved the issue.

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
