### ISSUE TITLE
Tinymce removes html, body and head tags

### ISSUE THREAD

**Issue by alexander-braun** [tinymce/tinymce#8186]
**What is the current behavior? Describe the bug**
Html, head and body tags get removed.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
This 
```
 <html>
    <head></head>
    <body>
       <div>Hello</div>
   </body>
 </html>
```
is beeing transformed to this 
```<div> Hello </div> ```
directly after init.

**What is the expected behavior?**
HTML is kept intact.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinymce 6.2.0 
@tinymce/tinymce-angular 7.0.0

**Comment by lostkeys** [comment]
Hi @alexander-braun , This cabability was handled by the fullpage plugin in TinyMCE 5, which we removed in TinyMCE 6 because it had so many bugs and was too expensive to maintain. Currently we have nothing planned, but I recommend you to go to our [roadmap website and submit a feature request](https://www.tiny.cloud/roadmap/). If you decide to do that, please tell us what problem you are trying to solve using this feature, The impact of having and not having it, and perhaps even if you are willing to become a paying customer to get it. A well formulated problem helps us prioritize among features. Thanks
