### ISSUE TITLE
paste_data_images doesn't pass a valid blob to images_upload_handler

### ISSUE THREAD

**Issue by liitfr** [tinymce/tinymce#8212]
**What is the current behavior? Describe the bug**

I'm using compressor.js to reduce file size before uploading to server.
Compression is done inside images_upload_handler. 
Compression works fine when I pick an image from quick image toolbar (Quickbars).
But, when i'm drag&dropping this same image from my windows explorer, compressor.js returns following error : 
"The first argument must be a File or Blob object"

It looks like these two scenarii don't pass same parameter to images_upload_handler.

As a workaround, i have to set paste_data_images to false

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

reproduction can be found here : https://codesandbox.io/s/ecstatic-kepler-4yd85q?file=/src/App.tsx

**What is the expected behavior?**

Both scenarii should return a valid blobinfo parameter.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

tinymce: 6.2.0
@tinymce/tinymce-react: 4.2.0
OS: windows 11 22h2
browser: chrome 106.0.5249.119

**Comment by spocke** [comment]
The compressor js is using a is-blob package that checks if the input object is a blob by doing `value instanceof Blob` however since the blob from the drop event is not created in the main window but rather created inside the editors iframe that instanceof check will fail since prototypes are bound to particular windows. You can however just import the blob into the current window scope before passing it into the compress function and that seems to work.

I updated the codepen with that change:
https://codesandbox.io/s/pensive-elbakyan-1900zg?file=/src/App.tsx

**Comment by liitfr** [comment]
thank you for your quick answer.
Your solution works just fine ! thanks a lot.
You teach me something new, about blob & iframe scope. thank you.
I'm closing this issue.

**Comment by chuoke** [comment]
Thank you both. TIL. 

If need the name, maybe do this:
```
const file = new File([blobInfo.blob()], blobInfo.blob().name, { type: blobInfo.blob().type });
```
