### ISSUE TITLE
Insert a video poster that has a large height and the screen cannot scroll auto

### ISSUE THREAD

**Issue by zhaokaide** [tinymce/tinymce#8243]
**What is the current behavior? Describe the bug**
Insert a video poster that has a large height and the screen cannot scroll auto

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
1、Add a video that has a large height
2、The video Poster is captured and also has a large height
3、The editor cannot scroll auto

**What is the expected behavior?**
The editor can scroll auto

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by yacodes** [comment]
Hi @zhaokaide, thanks for reporting this. Can you create a reproduction case in a TinyMCE [Fiddle](http://fiddle.tinymce.com/)? Also can you specify which versions of TinyMCE do you use?

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
