### ISSUE TITLE
[BUG] v6.3.0: Colorswatch display a check mark for all the colors and not only one

### ISSUE THREAD

**Issue by ghost** [tinymce/tinymce#8293]
**What is the current behavior? Describe the bug**

Since version 6.3.0, Colorswatch is now supposed to display a check mark for the selected color ([see the changelog](https://www.tiny.cloud/docs/tinymce/6/changelog/#improved:~:text=Colorswatch%20now%20displays%20a%20checkmark%20for%20selected%20color.)). However, all the colors are checked.

![1](https://user-images.githubusercontent.com/59090546/203515370-7b923ab3-974e-451f-8899-dd0341583850.png)
![2](https://user-images.githubusercontent.com/59090546/203515373-98aaf173-1e2b-4ebd-a673-1c52aed28ec8.png)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

```js
tinymce.init({
	selector: '#editor',
	toolbar: 'forecolor backcolor',
	// Extra options...
});
```

**What is the expected behavior?**

Only the selected color should display a check mark.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

- TinyMCE version: **6.3.0**
- Browser: **Google Chrome v107.0.5304.107**
- OS: **Windows 10**

**Comment by spocke** [comment]
Can't seem to reproduce that issue. So we would need some more information here.

1. Could you setup a fiddle where this can be reproduced.
2. Could you make sure that the css files are all updated where you are testing it and not cached in the browser.
3. Your skin above seems to be black. If you are using a custom skin make sure that it gets rebuilt with the oxide skin since changes have been made to the less files.

Here is a fiddle where I tested it on https://fiddle.tiny.cloud/ktiaab it uses the dark skin that comes with tinymce.
