### ISSUE TITLE
table border style not being applied

### ISSUE THREAD

**Issue by dani-ttci** [tinymce/tinymce#8305]
**What is the current behavior? Describe the bug**
I am working on modifying table and it seems that border style are not being applied correctly, because this style is not being added on each cell. It actually works on this [demo page](https://www.tiny.cloud/tinymce/features/advanced-tables/) but not on this [demo page](https://codepen.io/pen)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
You can test [here](https://codepen.io/pen). 
To replicate, simply highlight a table and update table properties. Add a border style and color and click save.

**What is the expected behavior?**
It should display correctly like what is being shown [here](https://www.tiny.cloud/tinymce/features/advanced-tables/)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Im using react tinymce which uses tinymce v6

**Comment by lostkeys** [comment]
Hi @dani-ttci, tables are difficult because there are many different ways to style a table and browsers treat it a bit differently. Before TinyMCE 5, tables were completely unstyled in the editor and you had to start from scratch styling them every time. Also it provided an ugly first-run experience so we added some default styles to the table to make it look a bit better. 

However it comes with some trade-offs. To get a consistent look, table borders are applied to the table cell. Those take precedence over any styles you put on the table element through the table properties dialog. Try change the border via the table cell properties dialog.

This is not an easy problem to solve because different developers have different requirements. For some, the HTML output is more important, for example in website CMS'es. To others, the user experience is more important because end-user's in general doesn't know anything about styling HTML tables.

I'd love to hear more abour your use-case, your requirements and any trade-offs you are willing to accept between conrol over the HTML output vs end-user "simplicity".

— Fredrik, Product Manager

**Comment by chagins** [comment]
Hi @lostkeys 
I use "tinymce": "6.3.1" on React ("@tinymce/tinymce-react": "4.2.0") and i have the same problem:

1. Insert a table and select some cells.
![image](https://user-images.githubusercontent.com/46863533/213499457-496bdebc-adc9-43be-b5a3-c482be822fb6.png)

2. Set cells border
![image](https://user-images.githubusercontent.com/46863533/213499556-70201774-a3b0-47b0-8c29-365273c6ce6f.png)

3. Result - some borders did not change color:
![image](https://user-images.githubusercontent.com/46863533/213499687-6161882e-48eb-4ab1-b522-aa5894ac75df.png)

**Comment by ozyjac-733** [comment]
Hi @lostkeys

You said:   Before TinyMCE 5, tables were completely unstyled in the editor and you had to start from scratch styling them every time. Also it provided an ugly first-run experience so _**we added some default styles to the tabl**_e to make it look a bit better._

Is it possible to change the default styles or turn them off?

**Comment by TheSpyder** [comment]
@ozyjac-733 yes, using the `content_css` and `content_style` options.

**Comment by mauricioprado00** [comment]
solution in here:
https://github.com/tinymce/tinymce/pull/10160

please vote up so they push the fix:
https://github.com/tinymce/tinymce/discussions/10165
