### ISSUE TITLE
Set target _blank when pasting a link

### ISSUE THREAD

**Issue by Gabsato02** [tinymce/tinymce#8364]
Hey,

right now, Tiny is not applying the default_link_target attribute when you paste a link. It works only if you create the link by clicking on the button at the toolbar.

It would be nice if we could paste a link and have it automatically set to target _blank.

Right now working with @tinymce/tinymce-vue": "^3.2.8".

**Comment by yacodes** [comment]
Hi @Gabsato02, thanks for reporting this. This varies between different users — some want to add `target="_blank"` by default, others don't. We prefer not to add any additional attributes by default.

However you can add your own pre- and post-processing logic of paste behavior with [paste_preprocess](https://www.tiny.cloud/docs/tinymce/6/copy-and-paste/#paste_preprocess) and [paste_postprocess](https://www.tiny.cloud/docs/tinymce/6/copy-and-paste/#paste_postprocess). Just take a look at examples in the documentation and you can easily implement what you want. Good luck!

Will close this issue, since it can be fixed without updating editor's core.
