### ISSUE TITLE
editor.selection.getContent({ format: 'html' }) access to the content is not correct.

### ISSUE THREAD

**Issue by wudi98** [tinymce/tinymce#8395]
When I use ```editor.selection.getContent({ format: 'html' })```,It doesn't get the element right, it's plain text.

**Steps:**
1.You can go to this page and edit it: [https://codesandbox.io/s/strange-curie-8id3qh?file=/src/App.js](https://codesandbox.io/s/strange-curie-8id3qh?file=/src/App.js)
2.You can choose any text and put any style on it.
<img width="553" alt="image" src="https://user-images.githubusercontent.com/47620997/212796681-c47d1f8c-44e8-42c8-b10e-79202a5269c8.png">
3.Unfocus after adding the style.
4.Then select the sentence you just styled and click the "add Comment" button to get its html content.
5.We can see in the console that the content we get is plain text, not html content.
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/47620997/212797366-9290fb89-acc1-47d5-b2fb-e79a9ff6ca3e.png">

**expected behavior：**
Correctly get html content instead of text.

I'm using "@tinymce/tinymce-react": "^3.14.0"
MacBook pro

**Comment by HAFRMO** [comment]
This is expected behavior. The result you get back is as 'close' as it can get. As what you have selected is just plain text ( wrapped in html that formats it ) it will only return plain text. It won't try to wrap it in a span that contains all formatting that any ancestor might impose upon it.

I understand this might be somewhat vexing if you are selecting the entire content of an html element ( such as a bold text ) and expected to get the <b>-tags as well. It is possible you might wish to change the selection to include them ( By way of javascript ) in that case.
