### ISSUE TITLE
Improve icon stroke width consistency

### ISSUE THREAD

**Issue by purplespider** [tinymce/tinymce#8478]
I'd really like to see some improvement to the icon design in TinyMCE 5, mainly in making the stroke width consistent: 

---
For example, take these commonly used icons:
<img width="195" alt="Screenshot 2023-02-22 at 10 27 16@2x" src="https://user-images.githubusercontent.com/329880/220593588-1013acee-6dcf-4bee-9efa-bbd8a5e5f259.png">
* The way the lines on the link icon go from think to thin looks out of place, as this doesn't align with any other icon.

---
Looking at the image, embed and table icons:
<img width="125" alt="Screenshot 2023-02-22 at 10 28 14@2x" src="https://user-images.githubusercontent.com/329880/220593859-fa0acffc-a541-449e-bc38-ea39858ca44a.png">
* They all have internal lines, but each one has a different line width.
* The outer box of the table icon, is smaller than the ones on the other 2 icons.

---
Elsewhere the source code icon appears to have a thinner stoke width than most other icons:
<img width="38" alt="Screenshot 2023-02-22 at 10 34 51@2x" src="https://user-images.githubusercontent.com/329880/220595405-22c92fb0-4174-4e4e-aa7e-19e1dac96f75.png">

**Comment by lostkeys** [comment]
Hi @purplespider. Thanks for the feedback. As the designer of these icons, I both agree and disagree. It was a while since these icons were created but if I recall correctly, the link icon "stroke" being thinner at the top-right and bottom-left sides are a rounding issue in the SVG optimizer and I never really got around fixing that. As for the other icons the general strategy were to optimize them for regular low resolution screens and the main stroke is 2 px. But a consistent 2px stroke everywhere in the icon would not offer enough fidelity in the image and globe icons above. As for the table icon, it's just a matter of personal preference not having them square.

We got a [premium icon pack](https://www.tiny.cloud/docs/tinymce/6/premium-skins-and-icons/) that is designed for higher resolution screens found for example on MacBooks that has a 1.25 px stroke width, and strokes are more uniform throughout. A drawback is that there is an antialiasing artifact when viewed on regular monitors.

<img width="525" alt="thin-icon-pack" src="https://user-images.githubusercontent.com/3122929/220662237-435069a0-9175-4f02-99b4-3288fa2ae12c.png">

**Comment by purplespider** [comment]
Thanks for the explanation, @lostkeys. Yes, those icons do look nice, but I see what you mean about the antialiasing issues on lo-res screens.

The odd link icon was the first thing I noticed upon trying TinyMCE v5, and is probably what made me scrutinise the other icons further TBH! So it would be ace to get that resolved at least. Oddly I noticed in the [screenshot](https://camo.githubusercontent.com/703496cf0c2806ff6aba376c72b0a50e016329d68ccc4b92d0bbbbdf51347fd0/68747470733a2f2f7777772e74696e792e636c6f75642f73746f726167652f6769746875622d726561646d652d696d616765732f74696e796d63652d656469746f722d36782e706e67) in the [repo readme](https://github.com/tinymce/tinymce), that the link icon is displaying correctly. 🤔 

<img width="106" alt="Screenshot 2023-02-22 at 15 48 48@2x" src="https://user-images.githubusercontent.com/329880/220677666-3e9175b1-7500-4f9c-8152-77d79e1c38c6.png">

**Comment by TheSpyder** [comment]
> Oddly I noticed in the screenshot in the repo readme, that the link icon is displaying correctly. 🤔

Yes, chances are the problem is the SVG optimiser. If you look at the [source SVG](https://github.com/tinymce/tinymce/blob/develop/modules/oxide-icons-default/src/svg/link.svg), it's the same as the screenshot.
<img src="https://raw.githubusercontent.com/tinymce/tinymce/develop/modules/oxide-icons-default/src/svg/link.svg">

We haven't upgraded the optimiser in a while and probably need to re-evaluate it.
