### ISSUE TITLE
addIcon() examples are not working

### ISSUE THREAD

**Issue by jackwu982** [tinymce/tinymce#8548]
I use `addButton` icon use  `addIcon` examples but it not working
`editor.ui.registry.addIcon('triangleUp', '<svg height="24" width="24"><path d="M12 0 L24 24 L0 24 Z" /></svg>');`

 that i change name to `triangle_up` code is working
`editor.ui.registry.addIcon('triangle_up', '<svg height="24" width="24"><path d="M12 0 L24 24 L0 24 Z" /></svg>');`

my version is `5.10.5`
url: `https://www.tiny.cloud/docs/api/tinymce.editor.ui/tinymce.editor.ui.registry/#addicon`

so  I'm not sure if the documentation is wrong.

**Comment by lostkeys** [comment]
Hi @jackwu982. We need you to create a replication case [TinyMCE fiddle](https://fiddle.tiny.cloud). Also [TinyMCE 5 reaches end of support](https://github.com/tinymce/tinymce/discussions/8544) this month so we will address this in v6 if there is a bug in TinyMCE.

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
