### ISSUE TITLE
TinyMCE 6: metadata custom element tag gets stripped in Tinymce 6 but not other single-word tags

### ISSUE THREAD

**Issue by andlimey** [tinymce/tinymce#8566]
**What is the current behavior? Describe the bug**
Our project's use of TinyMCE allows users to insert `metadata` tags. It works on TinyMCE 5, but when we upgraded to version 6, the `metadata` tags were stripped from the editor. Other single-word tags appear as expected.

**Fiddle Link**
https://fiddle.tiny.cloud/y2iaab/2

**What is the expected behavior?**
From the fiddle, `Metadata` should appear.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
This works previously in TinyMCE 5, but not 6.

**Comment by TheSpyder** [comment]
Looks like DOMPurify is removing it. We recently added an option to disable that part of our parsing - this isn't a solution I recommend, just proof that it's the cause
https://fiddle.tiny.cloud/y2iaab/3

We configure DOMPurify to keep custom elements, I wonder why it's removing this one specifically.

**Comment by spocke** [comment]
I think it's because `metadata` is a SVG element.

Documented here:
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/metadata

Here it's listed in the DOMPurify SVG set:
https://github.com/cure53/DOMPurify/blob/main/src/tags.js#L149

'mask' is also removed another SVG element added it to the fiddle here so flippling on and off the xss_sanitization option you will see that it will remove or not remove the mask element as well:
https://fiddle.tiny.cloud/y2iaab/4

I would recommend using prefixes for custom elements so that you don't get element clashes like this. The recommended way to have custom elements is so use `<prefix>-<tagname>` so in this case `something-metadata` for the tag name instead of just `metadata`. The html and svg specs will continue to evolve and new tags are added all the time so to avoid conflicts prefix them if possible.

**Comment by andlimey** [comment]
I see. Thanks for looking into this! I think my team will most likely adhere to the `<prefix>-<tagname>` recommendation.

**Comment by TheSpyder** [comment]
Glad to hear it! We might look at noting this in our documentation as well.
