### ISSUE TITLE
When i use it in microapp, style is wrong

### ISSUE THREAD

**Issue by QbjGKNick** [tinymce/tinymce#8669]
**What is the current behavior? Describe the bug**
I use it in microapp, this style is wrong

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
![image](https://user-images.githubusercontent.com/18567408/233062462-5c4e4c65-0ee9-4cf8-8740-94f723cf5cd4.png)

**What is the expected behavior?**
![image](https://user-images.githubusercontent.com/18567408/233062669-463e1392-2b4d-494e-bacb-42ee840a20e5.png)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Latest chrome version on PC and latest TinyMCE version.

**Comment by lorenzo-pomili** [comment]
could you provide an example to reproduce this issue?

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
