### ISSUE TITLE
Image uploading doesn't work on Firefox 112

### ISSUE THREAD

**Issue by okzgn** [tinymce/tinymce#8692]
I saw this error on Firefox 112, but probably happens in other versions too.

Just click or press enter inside editor to show the upload images tool and when you select the image to upload the image blob don't appears in the editor. (https://fiddle.tiny.cloud/N6iaab)

It suppose to put the image blob inside the editor of TinyMCE 6.4.2 on Windows without problems.

**Comment by spocke** [comment]
I wasn't able to reproduce this this is what I tried:

1. Opened the provided fiddle https://fiddle.tiny.cloud/N6iaab in Firefox 112.0.2 (64-bit) on Windows 11
2. Clicked inside the editor so that the `quickbar` toolbar with the `quickimage` button appeared
3. Clicked the `quickimage` or `Insert image` button
4. Picked a file in the file picker this case a PNG file
5. Observed that it inserted correctly inside the editor

Could you try this in private mode to see if any extensions interfere?
Are there anything different in exact Firefox version or OS version that the one that I tested?
Does it work on Chrome or Edge on the same OS?
What type of image file did you pick JPG, PNG other?

**Comment by okzgn** [comment]
Right now it works without issues. Thanks.
