### ISSUE TITLE
tinymce6 not work in wechat

### ISSUE THREAD

**Issue by ginkosen** [tinymce/tinymce#8697]
**tinymce6 cannot be used normally in WeChat.**

**https://ginkosen.github.io/tinymce6/**

**work corect**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? **

TinyMCE: 6.4.2
UA: Mozilla/5.0 (iPhone; CPU iPhone OS 16_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/8.0.37(0x18002523) NetType/WIFI Language/zh_CN

**Did this work in previous versions of TinyMCE?**
Yes, TinyMCE: 5.10.7 work well

**Comment by lostkeys** [comment]
Hi @ginkosen. I'm afraid you need to be more specific. Usually we cannot support integrations into other services, so if your issue is specifically with WeChat, you should contact them to troubleshoot your issue. If the issue is with TinyMCE, we usually require you to be able to [replicate your issue in TinyMCE using for example our fiddle tool](https://fiddle.tiny.cloud/).

Please submit a new issue with more details if the problem ultimately is with TinyMCE.

— Fredrik, Product Manager

**Comment by ginkosen** [comment]
Thanks for rely. I will try what you say.

Thanks again.
