### ISSUE TITLE
Why can't I focus on the input box when inserting images, but there's no problem inserting videos

### ISSUE THREAD

**Issue by yu244** [tinymce/tinymce#8707]
I am using versions 5.10.2 and 6.1, both of which have this issue.

And I am using it on Vue 3.

May I ask what may be the cause and how can I modify the code. Thanks!

![GIF 2023-5-9 14-12-41](https://user-images.githubusercontent.com/72492174/237010125-c2ad8e12-851f-42fd-9a5a-da08d790448e.gif)

**Comment by spocke** [comment]
I wasn't able to reproduce this could you setup a codesandbox that show this error. Could be that some other script on the page is interfering with normal browser behavior since I've not seen any similar reports or a reason why the vue integration should some how break the focus of dialogs. Making a codesanbox isolates the problem and makes it easier for us to spot what ever the problem might be.

**Comment by devin-huang** [comment]
@spocke You need to use the elementUI dialog box component package to reproduce
