### ISSUE TITLE
Problem with loading tinymce4?

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#871]
I dont know its a bug with tinymce4, my internet provider, samsung software(laptop).

From time to time(very rare) I have problems with tinymce to load.

new site.. not in cache.. dev console

* 404 missing plugin.js
refresh F5
* 404 missing tinymce..css...
refresh F5
* all right.. tinymce is now here and working fine.

Have another the same problems? If not.. its a problem on my side. Sorry.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T6091](http://archive.tinymce.com/develop/bugtracker_view.php?id=6091) posted by [Editorant](http://archive.tinymce.com/profile.php?name=Editorant)_

> _**Tags:** [4x]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by DarkSide666** [comment]
2 years have passed, but this nasty bug is still not fixed in last version 4.2.8 :(

**Comment by spocke** [comment]
Seems like a very implementation specific bug. Since if it was a generic bug that happens 100% of the time then we would have fixed it by now. When using the script bundler tinymce wont be able to fint it's own base url. There are ways around that like using the cdn version or set the tinymce = {base: url, suffix: "min"} object before loading the editor script.

So I'm closing this one since it's not a bug.
