### ISSUE TITLE
V6 is still using browser native execCommand?

### ISSUE THREAD

**Issue by Troy-Yang** [tinymce/tinymce#8873]
**What is the current behavior? Describe the bug**
After debugging into core code, tinyMCE v6 still uses the browser native execCommand:
```
      editor.on('beforeinput input', inputBlocker, true);
      editor.getDoc().execCommand(command);
      editor.off('beforeinput input', inputBlocker);
```
This will result in the jsdom testing failing when we write the unit test because of document.execCommand is not supported.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

https://codesandbox.io/s/objective-feistel-8v3mdq?file=/index.html

**What is the expected behavior?**
TinyMce declares v6 is using self-command

https://www.tiny.cloud/docs/tinymce/6/editor-command-identifiers/#core-editor-commands
https://www.tiny.cloud/blog/tinymce-exec-commands/

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinyMCE v6
browser: chrome 
os: mac

**Comment by TheSpyder** [comment]
We don't support using TinyMCE in JSDom. Certainly it would make some things easier to test, but it's not a priority for us at the moment.

**Comment by Troy-Yang** [comment]
Hey @TheSpyder , I didn't fully mean the problem on JSDom, but just wondering if the V6 is still using native execCommand which tinyMCE said they are using self-command rather than native command?

**Comment by TheSpyder** [comment]
I don't believe we say anywhere that we _never_ use the native `execCommand`. The blog post does say:
> The TinyMCE 6 API execCommand is not related to Document.execCommand web API

But all that's trying to explain is that the TinyMCE API for executing commands has the same name as the native one, which is an unfortunate decision made near the start of TinyMCE's life and not one we can change now.

We do use the native `execCommand` - as you discovered - because TinyMCE still relies on ContentEditable for the document model. Some operations are just not viable for us to implement custom handling in this style of editor, it's better to delegate to the browser.

**Comment by Troy-Yang** [comment]
Thanks for the clarify, I was just misunderstood by the v6 docs
> The following tables show the existing editor commands. These commands are provided by tinymce and not by the browser’s internal commands. These commands can be executed using the [execCommand](https://www.tiny.cloud/docs/tinymce/6/apis/tinymce.editor/#execCommand) function.
