### ISSUE TITLE
Some types are missing from the TypeScript public API

### ISSUE THREAD

**Issue by The4thLaw** [tinymce/tinymce#8956]
**What is the current behavior? Describe the bug**

I'm writing an application that relies on the Autocompleter and on dialogs. My application relies on TypeScript.

To improve type checking, I'd like to rely on types like `AutocompleterItemSpec`, `AutocompleterInstanceApi` or `BodyComponentSpec`. However, they are not exported. They're included in namespaces like `PublicDialog_d` or `PublicInlineContent_d` but namespaces aren't exported so that is of no use for external projects.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

Since it's a build issue, I cannot provide a fiddle, but here is some sample code:

```javascript
import { AutocompleterItemSpec, Editor } from 'tinymce'
```

`Editor` can be resolved, but `AutocompleterItemSpec` cannot.

Please let me know if you need a better example.

**What is the expected behavior?**

Types related to the public API of TinyMCE should be exported to improve type safety.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE v6.2.0 is affected. I have no experience with previous releases. I'm also using TypeScript 5.1.6.

**Workaround**

I can work around the issue by copy-pasting the type definitions in my project. That's not ideal, but TypeScript can manage.

Thanks.

**Comment by TheSpyder** [comment]
Some types we didn't see much need to expose, because the values aren't usually stored in variables. And when values are passed inline as function arguments, the TypeScript compiler is able to infer the type:
```
  editor.ui.registry.addAutocompleter('myMenu', {});
// error: Argument of type '{}' is not assignable to parameter of type 'AutocompleterSpec'.
```

And similarly with the function parameters to the autocompleter `onAction` property. Types aren't specified here but the compiler knows what the type of `autocompleteApi` is:
https://github.com/tinymce/tinymce/blob/c7ad44ff0f6b95a752bbd4e2f38d26758f390b16/modules/tinymce/src/plugins/charmap/main/ts/ui/Autocompletion.ts#L9-L21

As for `BodyComponentSpec`, there are so many UI components that we grouped them under `Ui` rather than expose them individually:

```
import { Ui } from 'tinymce';

const myButton: Ui.Dialog.BodyComponentSpec = {
  type: 'button',
  name: 'myButton',
  text: 'my button',
};
```

We don't have documentation specifically for our types, but perhaps we need some to make things like this more obvious.
