### ISSUE TITLE
The Editor incorrectly displays the type of text that is active with the cursor

### ISSUE THREAD

**Issue by best-username** [tinymce/tinymce#9000]
**What is the current behavior? Describe the bug**
The Editor incorrectly displays the type of text that is active with the cursor. 
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
![image](https://github.com/tinymce/tinymce/assets/35339682/2a9430cb-9009-4b7e-b6f6-e80888e453eb)

**What is the expected behavior?**
The indicator at the top should be updated to reflect the type of text being edited.
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 6
Chrome Version 114.0.5735.198 (Official Build) (x86_64)
MacOS 13.4.1

**Comment by TheSpyder** [comment]
It will update only if the active block element is configured as one the user can choose. Please provide more information about your use case and configuration, or ideally a demo on fiddle.

**Comment by lostkeys** [comment]
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.
