### ISSUE TITLE
Does valid_children ever work?

### ISSUE THREAD

**Issue by YvesRijckaert** [tinymce/tinymce#9055]
**What is the current behavior? Describe the bug**
We would like to use tiny MCE as a rich text editor, but we have some rules around which elements can be children of certain elements and which not.
I think valid_children is supposed to control what child elements can exist within specified parent elements. But it never works.

For example in this codepen: https://codepen.io/yvesrijckaert/pen/ZEVxJOX
From the syntax, we only allow text and a tags to be children of paragraphs. But those rules are not enforced? I can still add `<em>` or `<strong>` as children of `<p>` ?

**What is the expected behavior?**

valid_children should actually enforce what you put in it

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

version 6.7.0 but I tested with older versions as well

**Comment by lostkeys** [comment]
You're doin it wrong. The HTML spec is the starting point and you'll have to explicitly tell it what not to support. `valid_children: "-p[strong]"` will prevent adding `<strong>` elements inside `<p>`

**Comment by YvesRijckaert** [comment]
I tried that but it also does not work 
![DF775EC4-D2C0-4129-BFBD-EB6600DBE501](https://github.com/tinymce/tinymce/assets/22968325/0213a296-1ea3-4e7b-a9bc-ac57329beb43)

**Comment by YvesRijckaert** [comment]
Thank you for the detailed explanation!

I followed your instructions and implemented `-body[strong],-p[strong]`. However, I noticed that there are still scenarios where I'm able to add bold text within paragraphs, notably using the cmd+b keyboard shortcut or changing the default text value.

To provide some context: I'm currently evaluating various rich text editors to find one that aligns best with our needs. Our schema has specific requirements. For instance, it does not permit blockquotes within table cells. Moreover, we intend to introduce custom node types which need to be factored into the schema as well.

TinyMCE has caught our attention, particularly due to its robust copy and paste capabilities. But not having the ability to easily customise the schema is a blocker.

Thanks again for your assistance :)

**Comment by spocke** [comment]
All formatting operations should just follow the schema rules so if you remove bold form P elements then you should not be able to apply bold using the UI for keyboard shortcuts however some browsers have native APIs that does it as well so one might need to prevent `beforeinput` and other things from trying to apply bold. But your case where blockquotes in tables should be preventable by altering the schema rules since there is a.f.a.k. no built in browser action to apply blockquotes to text.

**Comment by ferdnyc** [comment]
@YvesRijckaert 

> I followed your instructions and implemented `-body[strong],-p[strong]`. However, I noticed that there are still scenarios where I'm able to add bold text within paragraphs, notably using the cmd+b keyboard shortcut or changing the default text value.

Hmm. In playing around with your pen, I found that I couldn't use <kbd>Ctrl</kbd>+<kbd>b</kbd> to bold/unbold text in that first paragraph. (This is using Google Chrome on Linux x86_64.) But I _could_ still bold/unbold text on your second line, because it's actually in a `<div>`, not a `<p>`. **AND** I could _also_ bold/unbold the text on your _**third**_ line: It's italicized, so the bold was actually _inside an `<em>`_ that's inside a `<p>`, which apparently even `-p[strong],-body[strong]` doesn't prevent.

Which really does expose the shortcomings of the current `valid_children` implementation. If it only examines the _immediate_ parent element, it's practically impossible to usefully restrict elements with it. (Though, as @spocke noted, that's not _really_ its intended purpose, as `invalid_elements` exists to completely restrict elements. `valid_children` is more for enforcing specific rules of DOM hierarchy.)

Still, `valid_children` it seems so trivially easy to circumvent as to be effectively useless. Since (for example) putting a `<div>` inside a table cell, then putting a `<blockquote>` inside the `<div>`, will easily sidestep a `-td[blockquote],-th[blockquote],-table[blockquote]` type restriction.

**Comment by YvesRijckaert** [comment]
Not having an easy (bug free) way to bring our own schema is a blocker for us so we have decided not to go with tiny. It's unfortunate since I really like the editor. But hopefully something they can implement in the future.
