### ISSUE TITLE
Copying text from MS Word causes some content to increase in font size and some to disappear

### ISSUE THREAD

**Issue by dchandramohanan** [tinymce/tinymce#9131]
Copying text from MS Word causes some content to increase in font size and some to disappear

[Word sample .docx](https://github.com/tinymce/tinymce/files/13242111/Word.sample.docx)

To Reproduce
=============
When copying the content from the attached file the entire 2nd paragraph disappears and the font size of the 3rd paragraph is increased from 16 to 30. This issue is available in tinymce 6 . 

https://fiddle.tiny.cloud/kYezcadwkM/2

**Comment by TheSpyder** [comment]
The text is there but it's white because "text outline" isn't a style browsers support.

TinyMCE 6 [removed the open source word import handling](https://github.com/tinymce/tinymce/discussions/7487). We now only offer this via our [premium powerpaste plugin](https://www.tiny.cloud/tinymce/features/powerpaste/), which can fix this by removing formatting on pasted content.
