### ISSUE TITLE
Add config removeViewBox=false for svgo

### ISSUE THREAD

**Issue by woody-li** [tinymce/tinymce#9189]
## 📝 Provide a description of the new feature or improvement
Add  `removeViewBox=false` config for svgo in https://github.com/tinymce/tinymce/blob/develop/modules/oxide-icons-default/gulpfile.js#L7

### 🫶 What is the motivation?
The svgo remove `viewbox` attribute by mistake.
But it's a important data for svg source data, especially for scale which is the  `S` letter means.

### 🔗 What is the consequence of not having this feature?
The icon system in tinymce based on svg graph.
We need to adjust the icon (toolbar button) size sometimes.
It can't get desired results without viewbox, only svg element changed size, but graph don't.

### 🚦 How important would you rate the requested feature or improvement?
I think it's a important feature.
The maintainers(exclude some extreme ones) of svgo expressing that it shouldn't remove viewbox attribute (not the default option at least).

**Comment by lostkeys** [comment]
Hi @woody-li. Now, this was introduced a while ago, but IIRC the main motivation was to prevent people from being lazy and resize the icons. You are correct, the S stands for scalable, but your physical pixels in your monitor don't scale. So when you scale down the icons from 24px to say 20px, all coordinates end up fractions instead of integers and the once sharp line becomes a diffused gray mess and a terrible eye sore. (and removing it saved some bytes)

The main reason we used SVGs is not for the scalability, but being able to manipulate them via code, mainly setting colors. We considered icon fonts, but they are harder to compile and only allow setting the color of the whole glyph, where as with SVG, each element inside the SVG can be individually styled, something we take advantage of with the fore and back color icons.

Under the current "policy", the correct way is to [create your own SVG icons](https://www.tiny.cloud/docs/tinymce/6/creating-an-icon-pack/) drawn in the desired size, or use one of [our icon packs](https://www.tiny.cloud/docs/tinymce/6/premium-skins-and-icons/).

We are happy to hear peoples opinions on this, please give feedback and 👍 to guide us how important it is to change (or keep) this policy.

(As a sidenote, I'm intrigued by the way Bootstrap sizes their icons, by using ems in the SVG and use font-size to quickly change the size of the SVG.)

**Comment by woody-li** [comment]
Thanks for your reply.

Create custom icons or use icon packs would resolve some needs.

But is it possible for a dynamic size while responsiving.
Such as bigger icon in large width, smaller icon in narrow width.
