### ISSUE TITLE
Font Size Input 

### ISSUE THREAD

**Issue by wolfomat** [tinymce/tinymce#9216]
## 📝 Provide detailed reproduction steps (if any)
Look at: https://codepen.io/wolfomat/pen/NWoedGa
1. Use TinyMCE 6.8.1
2. Create a minimal Editor using toolbar = 'fontsizeinput'
3. Define, even it is regarding to the documentation the default, font_size_input_default_unit:'pt',

### ✔️ Expected result
I'd expect that in the input-box the unit would be for example Npt, where N is any number

### ❌ Actual result
The shown and used Unit in the font-size-input is PX.

### ❓ Possible solution
I'd guess that when the editor is initialized, the setting is not evaluated correctly. when changing the pt unit in the font-input-field, the editor will still work.

## 📃 Other details
- Browser: any
- OS: windows
- First affected version: 6.8.1 and lower (6.7.0)
- Worked in version: not sure.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by wolfomat** [comment]
> @wolfomat Did you get this to work? I am having the same problem

Hi @pennan88 ; in fact i did not get this to work

**Comment by pennan88** [comment]
@wolfomat Yes. i noticed that as well. Hopefully it gets fixed someday

**Comment by nonam4** [comment]
Also waiting for a fix

**Comment by nonam4** [comment]
I think I found a workaround on this issue (in my case this worked. I'm using react):

```
// Editor.tsx
import { Editor as EditorType } from 'tinymce'
export type TextEditorType = {
  onInit: (editor: EditorType) => void
}
function Editor( {
  onInit
}: TextEditorType ): JSX.Element {
  ..... 
  return (
    <Editor
      onInit={ ( _, editor ) => onInit( editor as unknown as EditorType ) }
      ..... other props
    />
  )
}

// MyComponent.tsx
function MyComponent() {
  ....
  function onEditorInit(editor: EditorType) {
    // this do the trick
    editor.execCommand( "fontSize", false, "10pt" )
  }

  return <Editor
    onInit={onEditorInit}  
  />
}
```

This forces editor to update it's font size and this also updates `fontsizeinput` to update it's value.

**Comment by pennan88** [comment]
@nonam4 Hello! 
This did work in react just like you said but sadly i am using Blazor WASM so the same solution did not work, but i think its still on the right path so I'll keep trying different approaches.

**Comment by renatolopes47** [comment]
Hi, did anyone got any solution for this? Thanks

**Comment by LaughingJohn** [comment]
Just hit this one myself..

**Comment by Mohamed3nan** [comment]
same, I think the problem in the theme.js file

**Comment by TheSpyder** [comment]
If you read our docs carefully, the `font_size_input_default_unit` option only changes what happens when the user types a number without a unit in the box. It doesn't adjust the value displayed.
https://www.tiny.cloud/docs/tinymce/latest/user-formatting-options/#font_size_input_default_unit

The browser standards demand `px` and don't give us a way to translate to `pt` or any other value, nor do they provide enough accuracy to convert ourselves. The computed style is returned to only 4 decimal places; we could try to approximate a `pt` conversion with rounding but there would be a lot of edge cases.
![Image](https://github.com/user-attachments/assets/6af84ccb-fc99-4b79-adab-6eb7a77afe66)

So we do the best we can:
* display the CSS `font-size` set directly on the element, if there is one
* fall back to `window.getComputedStyle()` which will always show `px`.

The only way to show a `pt` value in an empty editor is set the content to `<p style="font-size: 10pt;">&nbsp;</p>`.
