### ISSUE TITLE
TinyMCE Rearranging My Text

### ISSUE THREAD

**Issue by craigbass76** [tinymce/tinymce#9444]
I'm hitting the Source Code button to edit a link. I want the link to read:
```
<a target="_blank" href="doc.html">Doc</a>
```
And when I save, the link gets changed to:
```
<a href="doc.html" target="_blank">Doc</a>
```

Is there a way to make TinyMCE leave my source code changes alone? my `tinymce.init` plugins section is this:
```
preview importcss searchreplace autosave save directionality code visualblocks visualchars fullscreen image media template codesample table charmap pagebreak nonbreaking anchor insertdatetime advlist lists wordcount help charmap emoticons accordion
```

**Comment by lostkeys** [comment]
No, unfortunately not. TinyMCE isn't that type of HTML editor that would retain HTML markup verbatim. Just curious, what is the motivation for having attributes kept in order?

**Comment by craigbass76** [comment]
`target="_blank"` seems to be working more consistently when it's first.

**Comment by TheSpyder** [comment]
This is actually a browser thing. We use the browser to both store and serialise HTML, and attribute order is undefined in the standard.

We hit it in our tests all the time; running on varied browsers and platforms, elements with multiple attributes return a different order mostly at random.

**Comment by spocke** [comment]
You can configure a specific order to be enforced but we do not retain the input source order since that would mean we would need to track that in some way separate from the browser. Here is an example on how you can enforce attribute order: https://fiddle.tiny.cloud/rQ0tLyuXLt/1 by default it will first put in the global attributes like `id` and `title` then the element specific ones like `href` for links.

So this is the attribute order that gets applied by default: ```
[ "id", "accesskey", "class", "dir", "lang", "style", "tabindex", "title", "role", "contenteditable", "contextmenu",
    "draggable", "dropzone", "hidden", "spellcheck", "translate", "xml:lang", "href", "target", "rel", "media",
    "hreflang", "type", "charset", "name", "rev", "shape", "coords", "download"
]```
