### ISSUE TITLE
Affected version of CVE-2024-29881

### ISSUE THREAD

**Issue by cedric-anne** [tinymce/tinymce#9513]
## 📝 Provide detailed reproduction steps (if any)

When executing the `npm audit` command on a project that is using the 6.8.3 version of the TinyMCE package, it reports that the package must be upgraded to fix the security issue detailed in https://github.com/advisories/GHSA-5359-pvf2-pw78.

```
$ npm ls tinymce
@opensource/project@ /project/path
`-- tinymce@6.8.3

$ npm audit
# npm audit report

tinymce  <7.0.0
Severity: moderate
TinyMCE Cross-Site Scripting (XSS) vulnerability in handling external SVG files through Object or Embed elements - https://github.com/advisories/GHSA-5359-pvf2-pw78
fix available via `npm audit fix --force`
Will install tinymce@7.0.0, which is a breaking change
node_modules/tinymce

1 moderate severity vulnerability

To address all issues (including breaking changes), run:
  npm audit fix --force
```

But, as described in the advisory, the versions >= 6.8.1 can be considered as secured as long as the `convert_unsafe_embeds` option is set to `true`.

### ✔️ Expected result
Version `>= 6.8.1` is considered as safe.

### ❌ Actual result
Version `>= 6.8.1` is considered as vulnerable.

### ❓ Possible solution
Use the same `Affected versions` and `Patched version` as  in https://github.com/advisories/GHSA-438c-3975-5x3f.

**Comment by ThiefMaster** [comment]
Yeah this is quite noisy and triggers dependabot updates to a new major version (with a significant license change!) - but at least it helps people find out about that license change in v7...

**Comment by tjdett** [comment]
Tiny's InfoSec team thought long and hard about the timing and the specified version range for [CVE-2024-29881][CVE-2024-29881] and [CVE-2024-29203][CVE-2024-29203]. We don't think there were any good options, but we think our choices here are consistent with previous advisories and the most likely to lead to good security outcomes.

### Why we did it this way

The benchmark we set for "safe" with TinyMCE is "secure by default". For many of our previous advisories we have published workarounds to make an earlier version just as secure as one listed as safe, but _only if the editor is correctly configured_.

The changes we needed to meet the "safe by default" benchmark with [CVE-2024-29881][CVE-2024-29881] and [CVE-2024-29203][CVE-2024-29203] were breaking product changes, so without abandoning semantic versioning the earliest we could make them default behaviour was 7.0. Major version upgrades aren't something you do immediately, so we needed an easy workaround for 6.x, and that's why `convert_unsafe_embeds` and `sandbox_iframes` are available from 6.8.1 onwards.

We're quite aware the usual practice of many devs is to fix security issues by just upgrading the package version. That's why we delayed publishing these two CVEs until after the release of TinyMCE 7.0. We've seen what happens when a safe version hasn't been released when the CVE drops, and we really didn't want to do that here.

### "OK, but I'm not ready for 7.x yet and I want a clean scan!"

Most good software composition analysis tools will have a way to ignore CVEs that are false positives or not relevant because workarounds are in place. Unfortunately, `npm audit` isn't one of them ([yet](https://github.com/npm/rfcs/pull/18)).

You don't need to use a commercial tool to get this feature. [npm-audit-resolver](https://www.npmjs.com/package/npm-audit-resolver) is aimed at solving this problem, and if you're using [yarn npm audit](https://yarnpkg.com/cli/npm/audit), there's an `--ignore` flag you can use.

Tiny's not going to vouch for a particular solution, but internally we do use [OWASP dependency-check](https://jeremylong.github.io/DependencyCheck/) (which is [open source](https://github.com/jeremylong/DependencyCheck/blob/main/LICENSE.txt) and [supports NPM](https://jeremylong.github.io/DependencyCheck/analyzers/nodejs.html)) to do software composition analysis, so we know suppressing CVEs as [false positives](https://jeremylong.github.io/DependencyCheck/general/suppression.html) is pretty normal. 

If you've confirmed that your usage of TinyMCE 6.x is safe with `convert_unsafe_embeds` and `sandbox_iframes` and you're not ready for 7.x just yet, then suppress the CVE. After that it's on your dev team to make sure they don't reintroduce vulnerable usage, so I'd recommend some code comments and making a note to review the suppression list periodically.

[CVE-2024-29881]: https://github.com/tinymce/tinymce/security/advisories/GHSA-5359-pvf2-pw78
[CVE-2024-29203]: https://github.com/tinymce/tinymce/security/advisories/GHSA-438c-3975-5x3f

**Comment by tjdett** [comment]
@cedric-anne Thank you for raising this issue. On double-checking some details, I finally noticed that [CVE-2024-29203][CVE-2024-29203] was published with the wrong version range.

There was some last-minute discussion about whether to combine both advisories into [CVE-2024-29881][CVE-2024-29881] or split them apart. Apparently when we split them we got our wires crossed when discussing the workaround in 6.8.1 and the "secure by default" change in 7.0.0, and the rest of the team just assumed the version ranges were the same.

I've now corrected the version range on [CVE-2024-29203] [CVE-2024-29203] to match [CVE-2024-29881][CVE-2024-29881].

[CVE-2024-29881]: https://github.com/tinymce/tinymce/security/advisories/GHSA-5359-pvf2-pw78
[CVE-2024-29203]: https://github.com/tinymce/tinymce/security/advisories/GHSA-438c-3975-5x3f

**Comment by cedric-anne** [comment]
@tjdett
Thanks for the explaination.
Considering the versions < 7.0.0 as vulnerable by default is indeed the best option to ensure that everyone that uses these versions will be warn about this vulnerability.

**Comment by fballiano** [comment]
Why aren't you not releasing 6.8.5?
