### ISSUE TITLE
Cookie improvements

### ISSUE THREAD

**Issue by MJHath** [tinymce/tinymce#9573]
## 📝 Provide a description of the new feature or improvement
*Describe your idea for the new feature or improvement*

During some page debugging, I noticed that I was seeing a lot of the following 'issues' in Chrome:

> Cookies with the SameSite=None; Secure and not Partitioned attributes that operate in cross-site contexts are third-party cookies

Having investigated, all 16 entries relate to tinymce js files, https://cdn.tiny.cloud/1<key>/tinymce/6/tinymce.min.js or similar

### 🫶 What is the motivation?
*Pitch why this feature or improvement should be implemented.*

Google states that "In future Chrome versions, reading third-party cookies will be blocked. This behavior protects user data from cross-site tracking.".

### 🔗 What is the consequence of not having this feature?
*This helps understand the underlying pain-points*

Functions of TinyMCE that require these cookies could stop working

### 🚦 How important would you rate the requested feature or improvement?
*Choose from nice-to-have, important or critical.*

Important (although I guess it depends how many support cases you want, should TinyMCE stop working!! 😃 )

---

If you'd like to see this implemented sooner, add a 👍 reaction to this post.
![Screenshot 2024-04-14 213921](https://github.com/tinymce/tinymce/assets/13164647/3450989a-95b6-440f-b70d-14f130a97949)

**Comment by TheSpyder** [comment]
We are aware of [Google's plans in this area](https://developers.google.com/privacy-sandbox/blog/cookie-countdown-2023oct), but thank you for making sure 🙂 

What you are seeing is cookies from [the Tiny website](https://tiny.cloud), our cloud service does not use or require cookies.

**Comment by TheSpyder** [comment]
The cookies are registered to `*.tiny.cloud` because some areas of the website use subdomains. Unfortunately, that means requests to `cdn.tiny.cloud` are interpreted by the browser as needing cookies even though they are not.

There's nothing TinyMCE can do to control when the browser sends cookies. Until our website is updated, all you can do is delete the `tiny.cloud` cookies (there's a chrome option under privacy where you can search for and delete just the cookies registered to that domain).
