### ISSUE TITLE
When editing within a <pre> block, <br> tags should not be added

### ISSUE THREAD

**Issue by davidnmbond** [tinymce/tinymce#9576]
## 📝 Detailed reproduction steps
1. Start with content containing 5 lines preformatted content inside <pre> </pre>
2. Put the cursor at the end of line 3
3. Press return
4. Inspect the resultant code

### ✔️ Expected result
The preformatted content has an extra newline character only

### ❌ Actual result
a [br] tag has been added at cursor location

### ❓ Possible solution
Detect the previous tag when pressing return.  If it's a [pre] tag, don't add [br].

## 📃 Other details
N/A

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by lostkeys** [comment]
Hi @davidnmbond. Can you please edit your message because it seems like it got messed up.

**Comment by TheSpyder** [comment]
Any phrasing content is legal inside `pre` tags, which is the same content restriction as `p` tags. The only difference is how white space is treated.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre

Note that if you use the format block feature to change the `pre` tag to a `p`, content entered within TinyMCE remains on multiple lines.

**Comment by davidnmbond** [comment]
It is HIGHLY unlikely that anyone editing text inside pre tags wants anything other than newline characters.

I don't believe that this should have been closed.

**Comment by TheSpyder** [comment]
It's been this way as far back as I can remember. We are a rich text editor, not a plain text editor.

The oldest version we have on our cloud service is from 7 and a half years ago, but I'm sure older versions do it too.
https://fiddle.tiny.cloud/Iw4kHT7dix/0

**Comment by gh-andre** [comment]
> It's been this way as far back as I can remember.

If something has been done incorrectly for a long time, it doesn't make it right. The `pre` tag specification clearly states that HTML elements are not expected within `pre` tags, and the following example goes on to say that paragraphs should be indicated by blank lines, etc.

> The [pre](https://html.spec.whatwg.org/multipage/grouping-content.html#the-pre-element) element [represents](https://html.spec.whatwg.org/multipage/dom.html#represents) a block of preformatted text, in which structure is represented by typographic conventions rather than by elements.

https://html.spec.whatwg.org/multipage/grouping-content.html#the-pre-element

Things get even worse, if I take a `pre` content with LF line breaks and add a single new line by pressing Enter, it creates a messy `pre` element with inconsistent new lines like this (Enter was pressed after `DEF`:

```HTML
<pre>
ABC
DEF<br>123
XYZ
```

There is a setting that I thought would control this - `br_in_pre`, but it turned out to be a fairly useless one that simply terminates the current `pre` element and either starts a new one or a new paragraph (if it's in the end of `pre` - not even documented properly).

I hope TinyMCE team will reconsider this issue and keep all whitespace in `pre` tags untouched and will insert Enter keystrokes as LF characters.

**Comment by davidnmbond** [comment]
TinyMCE goes against the specs here. TIL.

Would love a fix for this bug.

**Comment by TheSpyder** [comment]
> If something has been done incorrectly for a long time, it doesn't make it right.

Selectively choosing from the standards isn't right either. Yes the standard provides examples with newlines but it also uses words like "could" and "can". The content model for `pre` tags is [phrasing content](https://html.spec.whatwg.org/multipage/dom.html#phrasing-content-2); that allows a wide range of inline HTML tags including `br`.

I'm not denying that we break convention, but we do follow the standard. Inserting newlines would be a feature request; we are not a plain text editor. In a `pre` tag, whether a `br` tag or newline is used the rendered rich text content will appear identical.

You could try at overriding the enter key to disable our default behaviour when the cursor is in a `pre` tag and insert a text newline instead?

**Comment by gh-andre** [comment]
@TheSpyder 

> Selectively choosing from the standards isn't right either.

Well, quoting the primary meaning of the element expressed in the first paragraph of the spec is hardly "selective choosing".

Phrasing content is indeed allowed in `pre` tags, which may be used for a variety of legitimate reasons, such as adding semantic structure with elements like `code`, improve accessibility by adding elements for assistive technologies to read, or just to enhance readability, such as adding `a` or `span` tags, etc.

Using `br` in `pre` is like using b` for emphasizing text instead of using `em` - it can definitely be used this way, but that wouldn't be the best practice. Similarly here - the content of the `pre` tag flattened with `br`, not always consistently, looks to me something that can be improved.
