### ISSUE TITLE
Copy-pasted parsed URLs are (incorrectly) URL encoding ampersands

### ISSUE THREAD

**Issue by vigarov** [tinymce/tinymce#9618]
## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud) or similar.
1. Copy a link containing an ampersand (such as http://www.example.com/?test=amper&sand  )
2. Write some text in a [TinyMCE editor](https://fiddle.tiny.cloud/e2PLqfJQyw/0)
3. Select some of the written text of the previous step
4. Paste the copied link of step 1. in the editor. This immediately creates a hyperlink on the selected text 

### ✔️ Expected result
The hyperlink directs to `http://www.example.com/?test=amper&sand`

### ❌ Actual result
The hyperlink directs to `http://www.example.com/?test=amper&amp;sand`

### ❓ Possible solution
Unsure, but probably linked to parsing done in `applyLinkToSelection` in [modules/tinymce/src/core/main/ts/api/commands/LinkCommands.ts](https://github.com/tinymce/tinymce/blob/e9cf42d0ae2b0329820e1c13e835fba8fd64b98d/modules/tinymce/src/core/main/ts/api/commands/LinkCommands.ts#L42) called at [modules/tinymce/src/core/main/ts/paste/SmartPaste.ts line 47](https://github.com/tinymce/tinymce/blob/e9cf42d0ae2b0329820e1c13e835fba8fd64b98d/modules/tinymce/src/core/main/ts/paste/SmartPaste.ts#L47)

## 📃 Other details
- Browser: Firefox 125.0.3 (64 bits)
- OS: Windows
- First affected version: 6.1.0 seems to be the first version implementing the "autolink when pasting on selected text" functionality out of the box according to my tests with different versions on the fiddle. Although I've noticed the bug on Vancouver ServiceNow instances which run TinyMCE v5.
- Worked in version: unknown

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
Browsers support links to [`https://www.google.com/search?sourceid=chrome&amp;q=blah`](https://www.google.com/search?sourceid=chrome&amp;q=blah) just as well as [`https://www.google.com/search?sourceid=chrome&q=blah`](https://www.google.com/search?sourceid=chrome&q=blah). They are equivalent as far as navigating to them is concerned.

The HTML standard demands that `&` characters in attributes be escaped as `&amp;`. `<a href` is an attribute like any other. Browsers support this violation because it's such a common mistake, but when DOM APIs are used to set a `href` attribute it's encoded.

The code you linked to ends with `editor.formatter.apply('link', linkDetails, anchor);` which leads here:
https://github.com/tinymce/tinymce/blob/2ffd16dbca1f73df5507b6c3a82c82adda7f20ec/modules/tinymce/src/core/main/ts/fmt/DefaultFormats.ts#L224-L228

And that code boils down to a straight call to `elm.setAttribute()`. Here's an example showing what happens without TinyMCE involved at all.
https://fiddle.tiny.cloud/fv1qEtD9ZZ/0
