### ISSUE TITLE
cannot remove BOLD formatting from text copied from team calendars

### ISSUE THREAD

**Issue by long-l58** [tinymce/tinymce#9698]
## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud) or similar.
1. Open Microsoft team calendar
2. Copy any text that is BOLD 
3. paste into RTE, try removing format.

### ✔️ Expected result
formatting should be removed from copied text

### ❌ Actual result
formatting remains, and cannot be removed at all

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment]
We don't use Microsoft Teams. Please provide more information about the content that is pasted, such as a demo that begins with the content after pasting into TinyMCE.

**Comment by smalos** [comment]
I don't see this problem when I copy a text `normaltext boldtext` from MS Teams.
(where normaltext is not bold and boldtext is bold)

Both "clear formatting" and removing bold work fine.
I should mention that I am using the new teams, if that is relevant.

TinyMCE source after pasting:
`<p>normaltext <strong>boldtext</strong></p>`

**Comment by long-l58** [comment]
Hi,

It a very specific text, so go into Teams Calendar, click into any meeting.
copy the Bold title text. and past this into tinymce.

Formatting will not be removed.

**Comment by long-l58** [comment]
![image](https://github.com/tinymce/tinymce/assets/172410579/950e9994-d4ea-438c-8a3d-cbfff9cad77e)

**Comment by lostkeys** [comment]
Sorry, without any replication case, there is little we can do.

**Comment by smalos** [comment]
As expected, the formatting issue arises exclusively when copying from the old (classic) version of Teams. I was able to replicate the problem. After pasting the text, the source code appears as follows:

`<h1 class="ui-text awm awn bdc bhl awt cs bhm cu bhn ec awv" dir="auto" data-tid="calv2-sf-meeting-subject-view">Monthly call</h1>`

As you can see,  the H-tag is used instead of bold text. By removing the headings in TinyMCE, the text returns to normal.

**Comment by TheSpyder** [comment]
Ah. Yes if the text is a H1 change it to a paragraph to remove the bold appearance.
