### ISSUE TITLE
Getting usage data with TinyMCE api

### ISSUE THREAD

**Issue by seojisoosoo** [tinymce/tinymce#9704]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

In order to check whether the editor usage of TinyMCE exceeds a specific value, I wish there was an API that can receive usage data. Of course, if there is a lot of usage, an e-mail will be sent, but I want to implement functions such as notification functions using usage data.

 **Describe the solution you'd like**

API to get usage data

 **Describe alternatives you've considered**

**Comment by TheSpyder** [comment]
This is the editor repository, not cloud hosting support.

We do not offer premium support via GitHub. If you have a support subscription, please contact our support team directly: https://support.tiny.cloud/hc/en-us/requests/new

**Comment by strongbad03** [comment]
I read the OP's post and your response @TheSpyder a couple times. OP's post is definitely a feature request, not a cloud hosting support request, because I have the same desire for this feature. As a data engineer, I'd like to pull TinyMCE usage data from a REST API. In cases where a company serves multiple clients, it would be helpful to know the usage/consumption rate of TinyMCE by client by date.

**Comment by TheSpyder** [comment]
@strongbad03 any sort of REST API would not be provided by the editor. It would be provided by the hosting service. My comment stands. Requests for an API should be directed to our hosting service team through a support ticket; they may accept it as a feature request.
