### ISSUE TITLE
The newline_behavior: 'linebreak' attribute breaks Tab and Enter key ordered and unordered list functionality

### ISSUE THREAD

**Issue by DAdq26** [tinymce/tinymce#9771]
When using newline_behavior: 'linebreak' to avoid new paragraph after hiting enter, this option breaks key tab and Enter with ordered and unordered list
(with version 7.1.1)

### ✔️ Expected result
I fill the editor with a text i want to style with ordered list and keep both enter key and tab key functionality as usual
- Hit Enter once add new item list
- Hit Enter twice, leave out the list and back to root node
- Hit Tab, add deep level to the list

### ❌ Actual result
We are blocked inside the first item list hitting Enter
No possibility to leave out the list unless i unselect ordered format
Hit Tab has a strange behaviour...

Thanks you for your job,

If you have any issue about that it would be appreciate

**Comment by TheSpyder** [comment]
As I mentioned in the other issue this is the behaviour you ask for when `linebreak` is used. The [docs for this setting](https://www.tiny.cloud/docs/tinymce/latest/content-behavior-options/#newline_behavior) state:

> `default` inserts a block (defined by [forced_root_block](https://www.tiny.cloud/docs/tinymce/latest/content-filtering/#forced_root_block)) on Enter, and a br tag on Shift+Enter.
> ...
> `linebreak` forces the above Shift+Enter behavior in all cases.

If you use `default` and follow your steps but pressing shift+enter instead, the same thing will happen. Tab is weird for the same reason applying a block style like `h2` is weird in this mode. When the user is not creating block tags, a block operation applies to the nearest block it can find; usually the whole document (or in your `tab` case the whole list).

You can't have it both ways. You put the editor in a mode where pressing enter twice should produce two `br` tags rather than create new block tags. The editor can't assume that just because you're in a list it means you want to make a new block tag instead of what you configured it to do.

If you want lists to behave normally you need to allow block operations. `linebreak` was a developer-requested feature specifically to disable block operations on enter. `linebreak` is a mode designed for very specific situations, there are probably better ways to achieve the effect you're looking for by avoiding paragraphs.

**Comment by DAdq26** [comment]
HI
Yes i understand the behaviour but it did not respond to the normal case we used in v5 (for web page editor, email editor etc.)
We tried a lot of cross options but everytime it makes a side effect on others inside component. (trying line breaks with br as you mentioned as a developer requested feature, disabling root block etc etc)

Sadly in the future the usage of tinymce and this kind of roadmap could break on more time our app and forced us to search a new texteditor

Thanks for all

Take care

**Comment by TheSpyder** [comment]
Yes version 5 had `forced_root_block: false` which we removed in 6. Most of the time using CSS `p { margin:0 }` achieves the same effect developers were using `forced_root_block: false` for, and it's a more consistent user experience.

> note: perhaps i misunderstood this part of your answer "If you want lists to behave normally you need to allow block operation" what is the options corresponding to that?

If you use `invert` instead of `linebreak`, then shift+enter will insert a block tag and restore list behaviour. However it could also be used to insert a paragraph.
