### ISSUE TITLE
How to disable html auto format

### ISSUE THREAD

**Issue by jun1432** [tinymce/tinymce#9956]
## 📝 Provide detailed reproduction steps (if any)
This is so customized as I'm using the community version. I have this use case that I have a tinymce on top and bottom while html drag and drop in the middle.

top:
tinymce, content: `<div class="test">`

middle:
drag and drop html

bottom:
tinymce, content: `</div> <!-- closing tag for class .test -->`

### ✔️ Expected result
Tinymce editor will accept, only opening tag or only closing tag. I tried other options given from stackoverflow and nothing is working for my use case. As I tried adding a closing tag on source code after I click save button, the closing tag is removed and only the comment remains. While adding an opening tag, it will automatically adding a closing tag.

### ❌ Actual result
The actual result that I want to achieve is to retain the opening tag or closing tag only if added on the tinymce editor using the code plugin.

### ❓ Possible solution
Still checking the code plugin if there are code lines that I need to comment to make this work but I think it is not advisable.

## 📃 Other details
jQuery 3.7.1
Bootstrap 5.3
Tinymce 6.7.0

**Comment by lostkeys** [comment]
Hi @jun1432! This is not a bug. We spent a lot of time making sure TinyMCE produces valid HTML. Since the HTML is our "data format" the editor relies on having valid HTML to ensure the complex dom operations we perform works correctly and predictably. At this time we have no plans to change that. 

I suggest you create a discussion post here (or on Stack Overflow) describing the problem and what you are trying to achieve and we and the community might be able to find a better way to get to your end goal than relying on open HTML tags.

— Fredrik, Product Manager
